In [1]:
for o_num, o_elt in enumerate([[1,2],[3,4,5]]):
    print("%d element in the outer list" % (o_num))
    for i_num, i_elt in enumerate(o_elt):
        print("%d element in the inner list is %s" %(i_num ,type(i_elt))) 

0 element in the outer list
0 element in the inner list is <class 'int'>
1 element in the inner list is <class 'int'>
1 element in the outer list
0 element in the inner list is <class 'int'>
1 element in the inner list is <class 'int'>
2 element in the inner list is <class 'int'>


In [2]:
[[1,2],[3,4,5]][1][0]

3

In [3]:
a="Arnab"
print("Arnab")

Arnab


In [4]:
type(a)

str

In [5]:
type(Arnab)

NameError: name 'Arnab' is not defined

In [ ]:
Dict={1:'Arnab', 'Dey': 2, 'Sarkar':'3'}

In [ ]:
Dict['Dey']

2

In [ ]:
for a in Dict:
    print(a)

1
Dey
Sarkar


In [ ]:
Dict[2]="Arnab"

In [ ]:
Dict

{1: 'Arnab', 'Dey': 2, 'Sarkar': '3', 2: 'Arnab'}

In [ ]:
2 in Dict

True

In [ ]:
s=set(Dict)

In [ ]:
"Dey" in set(Dict)

True

In [ ]:
"Arnab" in set(Dict)

False

In [ ]:
%whos

Variable   Type    Data/Info
----------------------------
Dict       dict    n=4
a          str     Sarkar
i_elt      int     5
i_num      int     2
o_elt      list    n=3
o_num      int     1
s          set     {1, 'Dey', 2, 'Sarkar'}


In [ ]:
2.00 in Dict

True

This is a limitation as 2 and 2.00 are not same.

In [ ]:
List=2*['Arnab']+3*['Sarkar']+6*['Dey']

In [ ]:
L_set=set(List)

In [ ]:
L_set

{'Arnab', 'Dey', 'Sarkar'}

In [ ]:
count_list=[List.count(a) for a in L_set]

In [ ]:
count_list

[3, 6, 2]

In [ ]:
Dict={a: List.count(a) for a in L_set}

In [ ]:
Dict

{'Sarkar': 3, 'Dey': 6, 'Arnab': 2}

In [ ]:
Dict.sort()

AttributeError: 'dict' object has no attribute 'sort'

In [ ]:
L_set.sort()

AttributeError: 'set' object has no attribute 'sort'

In [ ]:
List

['Arnab',
 'Arnab',
 'Sarkar',
 'Sarkar',
 'Sarkar',
 'Dey',
 'Dey',
 'Dey',
 'Dey',
 'Dey',
 'Dey']

In [ ]:
List.sort()

In [ ]:
List

['Arnab',
 'Arnab',
 'Dey',
 'Dey',
 'Dey',
 'Dey',
 'Dey',
 'Dey',
 'Sarkar',
 'Sarkar',
 'Sarkar']

In [ ]:
List_unique=list(L_set)

In [ ]:
List_unique

['Sarkar', 'Dey', 'Arnab']

In [ ]:
List_unique.sort()

In [ ]:
List_unique

['Arnab', 'Dey', 'Sarkar']

## Side effects

In [ ]:
L1=['Arnab']

In [ ]:
L2=['Dey']

In [ ]:
L3=L1+L2

In [ ]:
L3

['Arnab', 'Dey']

In [ ]:
Dict1={1: L1, 2: L2}

In [ ]:
Dict1

{1: ['Arnab'], 2: ['Dey']}

In [ ]:
L2.append('Sarkar')

In [ ]:
L3

['Arnab', 'Dey']

In [ ]:
Dict1

{1: ['Arnab'], 2: ['Dey', 'Sarkar']}

In [ ]:
L2

['Dey', 'Sarkar']

In [ ]:
L3

['Arnab', 'Dey']

So observe that **L3** is not updated even if we change L2 but the 
dict is updated.

In [ ]:
def func1(a=2,b=3):
     return b/a

In [ ]:
func1()

1.5

In [ ]:
func1(3,4)

1.3333333333333333

In [ ]:
def func2(x):
    b=x
    a=x-1
    return func1(a,b)

In [ ]:
func2(3)

1.5

In [ ]:
func2(1)

ZeroDivisionError: division by zero

In [ ]:
%debug

> /var/folders/yq/6h47_f4s3g16nl2gbhk2pvv80000gn/T/ipykernel_41951/1185926188.py(2)func1()
      1 def func1(a=2,b=3):
----> 2      return b/a

*** NameError: name 'ibdb' is not defined
      1 def func1(a=2,b=3):
----> 2      return b/a


a = 0
b = 1
0.0
*** ZeroDivisionError: division by zero
0
<class 'int'>
> /var/folders/yq/6h47_f4s3g16nl2gbhk2pvv80000gn/T/ipykernel_41951/850707893.py(4)func2()
      1 def func2(x):
      2     b=x
      3     a=x-1
----> 4     return func1(a,b)

> /var/folders/yq/6h47_f4s3g16nl2gbhk2pvv80000gn/T/ipykernel_41951/2483606204.py(1)<module>()
----> 1 func2(1)

----> 1 func2(1)


> /var/folders/yq/6h47_f4s3g16nl2gbhk2pvv80000gn/T/ipykernel_41951/850707893.py(4)func2()
      1 def func2(x):
      2     b=x
      3     a=x-1
----> 4     return func1(a,b)

<class 'int'>
1
1
*** ZeroDivisionError: division by zero
> /var/folders/yq/6h47_f4s3g16nl2gbhk2pvv80000gn/T/ipykernel_41951/1185926188.py(2)func1()
      1 def func1(a=2,b=3):
----> 2      return b/a

*

In [ ]:
%pdb on

Automatic pdb calling has been turned ON


In [ ]:
func2(1)

ZeroDivisionError: division by zero

> /var/folders/yq/6h47_f4s3g16nl2gbhk2pvv80000gn/T/ipykernel_41951/1185926188.py(2)func1()
      1 def func1(a=2,b=3):
----> 2      return b/a



In [ ]:
%pdb off

Automatic pdb calling has been turned OFF


In [21]:
import numpy as np

a=np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [22]:
a[0]

0

In [23]:
a[0]=2

In [24]:
a

array([2, 1, 2, 3, 4, 5])

In [26]:
samp_array=np.array("numbers",[1,2,3])

TypeError: Field elements must be 2- or 3-tuples, got '1'

In [27]:
import array as arr

samp_array=arr.array("i",[1,2,3,4])

In [28]:
samp_array

array('i', [1, 2, 3, 4])

In [29]:
arr.array("s", ['a'])

ValueError: bad typecode (must be b, B, u, h, H, i, I, l, L, q, Q, f or d)

In [30]:
A=np.array([[1],
            [2]])

In [31]:
type(A)

numpy.ndarray

In [32]:
A.shape

(2, 1)

In [33]:
A.size

2

In [34]:
B=np.array([[1,2]])

In [35]:
type(B)

numpy.ndarray

In [36]:
B.shape

(1, 2)

In [37]:
C1=np.array(list(range(6)))

In [38]:
C1.shape

(6,)

In [39]:
D1=np.arange(6)

In [40]:
D1

array([0, 1, 2, 3, 4, 5])

In [41]:
D1.shape

(6,)

In [42]:
D1.ndim

1

In [43]:
D2=np.array([list(np.arange(6))])

In [44]:
D2

array([[0, 1, 2, 3, 4, 5]])

In [45]:
D2.shape

(1, 6)

In [46]:
C2=np.array([list(range(6))])

In [47]:
C2.shape

(1, 6)

In [48]:
type(C2.shape)

tuple

In [49]:
C2[C2<2]

array([0, 1])

In [50]:
C2[C2>=4]

array([4, 5])

In [51]:
C2[C2!=2]

array([0, 1, 3, 4, 5])

In [52]:
B+C1

ValueError: operands could not be broadcast together with shapes (1,2) (6,) 

In [53]:
B+C2

ValueError: operands could not be broadcast together with shapes (1,2) (1,6) 

In [54]:
np.hstack([B,C2])

array([[1, 2, 0, 1, 2, 3, 4, 5]])

In [63]:
C1+D

NameError: name 'D' is not defined

In [64]:
E=np.linspace(0,2,6)

In [71]:
np.concatenate([B,C2])

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 6

In [72]:
Join=np.concatenate([C1,D1])

In [73]:
Join.ndim

1

In [74]:
Join.shape

(12,)

In [75]:
Join.size

12

In [76]:
Join.sort()

In [77]:
Join

array([0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5])

In [78]:
Join<3

array([ True,  True,  True,  True,  True,  True, False, False, False,
       False, False, False])

In [79]:
Join.sum()

30

In [80]:
Join.var()

2.9166666666666665

In [81]:
Join.std()

1.707825127659933

In [82]:
Join.std(ddof=1)

1.7837651700316894

In [83]:
D2.sum()

15

In [84]:
D2.min()

0

In [85]:
D2.var(ddof=1)

3.5

In [86]:
D3=np.vstack([D2,np.zeros(6)])

In [87]:
D3

array([[0., 1., 2., 3., 4., 5.],
       [0., 0., 0., 0., 0., 0.]])

In [88]:
D4=np.vstack([D1,2*np.ones(6)])

In [89]:
D4

array([[0., 1., 2., 3., 4., 5.],
       [2., 2., 2., 2., 2., 2.]])

In [90]:
D4.shape

(2, 6)

In [91]:
D5=np.full((1,6),2)

In [94]:
Join1=np.vstack([D1,D5])

In [95]:
Join1

array([[0, 1, 2, 3, 4, 5],
       [2, 2, 2, 2, 2, 2]])

In [96]:
D4==Join1

array([[ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

In [100]:
Join2=np.vstack([np.vstack([C2,C2]),np.vstack([C1,D2])])

In [101]:
Join2

array([[0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5]])

In [103]:
Join3=np.hstack([np.vstack([C2,C1]),np.vstack([C2,D2])])

In [104]:
Join3

array([[0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5]])

In [105]:
Join3.sort()

In [106]:
Join3

array([[0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5],
       [0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5]])

In [107]:
%whos

Variable     Type       Data/Info
---------------------------------
A            ndarray    2x1: 2 elems, type `int64`, 16 bytes
B            ndarray    1x2: 2 elems, type `int64`, 16 bytes
C1           ndarray    6: 6 elems, type `int64`, 48 bytes
C2           ndarray    1x6: 6 elems, type `int64`, 48 bytes
D1           ndarray    6: 6 elems, type `int64`, 48 bytes
D2           ndarray    1x6: 6 elems, type `int64`, 48 bytes
D3           ndarray    2x6: 12 elems, type `float64`, 96 bytes
D4           ndarray    2x6: 12 elems, type `float64`, 96 bytes
D5           ndarray    1x6: 6 elems, type `int64`, 48 bytes
E            ndarray    6: 6 elems, type `float64`, 48 bytes
Join         ndarray    12: 12 elems, type `int64`, 96 bytes
Join1        ndarray    2x6: 12 elems, type `int64`, 96 bytes
Join2        ndarray    4x6: 24 elems, type `int64`, 192 bytes
Join3        ndarray    2x12: 24 elems, type `int64`, 192 bytes
a            ndarray    6: 6 elems, type `int64`, 48 bytes
arr        

In [108]:
Join3

array([[0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5],
       [0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5]])

In [110]:
np.concatenate([C1,C2])

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

In [113]:
np.concatenate([[C1],[C1]])

array([[0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5]])

In [114]:
np.concatenate([[C2],[C2]])

array([[[0, 1, 2, 3, 4, 5]],

       [[0, 1, 2, 3, 4, 5]]])

In [115]:
np.hstack([C2,C1])

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [117]:
np.hstack([C1,C1])

array([0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5])

In [118]:
np.hstack([C2,D2])

array([[0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5]])

In [119]:
Join3.shape

(2, 12)

In [120]:
Join3.size

24

In [121]:
Join3.ndim

2

In [126]:
D=np.array([[1,2,3],
   np.arange(3),
   np.arange(3,6),
   [10,15,16]])

In [127]:
D

array([[ 1,  2,  3],
       [ 0,  1,  2],
       [ 3,  4,  5],
       [10, 15, 16]])

In [130]:
F=D[1:3,1:]
F

array([[1, 2],
       [4, 5]])

In [132]:
F[0,0]

1

In [133]:
F[0,0]=5

In [134]:
D

array([[ 1,  2,  3],
       [ 0,  5,  2],
       [ 3,  4,  5],
       [10, 15, 16]])

Observe that D[1,1] has changed. Hence it is better to make a hard copy.

In [135]:
D_new=np.array([[1,2,3],
   np.arange(3),
   np.arange(3,6),
   [10,15,16]])

In [136]:
D_new

array([[ 1,  2,  3],
       [ 0,  1,  2],
       [ 3,  4,  5],
       [10, 15, 16]])

In [138]:
F_new=D[1:3,1:].copy()
F_new

array([[5, 2],
       [4, 5]])

In [139]:
F_new[0,0]

5

In [140]:
F_new[0,0]=5

In [141]:
F_new

array([[5, 2],
       [4, 5]])

In [142]:
D_new

array([[ 1,  2,  3],
       [ 0,  1,  2],
       [ 3,  4,  5],
       [10, 15, 16]])

D_new is not changed/affected now.

In [149]:
# We can choose by conditional statement as well
print(D_new[:,0]%2!=0)
F_mod=D_new[D_new[:,0]%2!=0, 2:]
F_mod

[ True False  True False]


array([[3],
       [5]])

In [152]:
F_mod[1,0]=4
F_mod

array([[3],
       [4]])

In [153]:
D_new

array([[ 1,  2,  3],
       [ 0,  1,  2],
       [ 3,  4,  5],
       [10, 15, 16]])

In [154]:
D_new.max(axis=0)

array([10, 15, 16])

In [155]:
D_new.min(axis=1)

array([ 1,  0,  3, 10])

In [158]:
D_new.std(axis=1, ddof=1)

array([1.        , 1.        , 1.        , 3.21455025])

In [159]:
3+[1,2]

TypeError: unsupported operand type(s) for +: 'int' and 'list'

In [160]:
rg=np.random.default_rng(2100)

In [161]:
rg.random(5)

array([0.29903711, 0.94885201, 0.26654812, 0.56245983, 0.04065328])

In [162]:
rg=np.random.default_rng(2100)

In [163]:
rg.random((4,5))

array([[0.29903711, 0.94885201, 0.26654812, 0.56245983, 0.04065328],
       [0.36256605, 0.31074318, 0.02194126, 0.22750713, 0.44676944],
       [0.50925882, 0.20031094, 0.75986071, 0.08795936, 0.52239343],
       [0.66922298, 0.84199534, 0.32375193, 0.10112876, 0.47771869]])

In [171]:
rg=np.random.default_rng(2100)

In [172]:
help(rg.normal)

Help on built-in function normal:

normal(...) method of numpy.random._generator.Generator instance
    normal(loc=0.0, scale=1.0, size=None)
    
    Draw random samples from a normal (Gaussian) distribution.
    
    The probability density function of the normal distribution, first
    derived by De Moivre and 200 years later by both Gauss and Laplace
    independently [2]_, is often called the bell curve because of
    its characteristic shape (see the example below).
    
    The normal distributions occurs often in nature.  For example, it
    describes the commonly occurring distribution of samples influenced
    by a large number of tiny, random disturbances, each with its own
    unique distribution [2]_.
    
    Parameters
    ----------
    loc : float or array_like of floats
        Mean ("centre") of the distribution.
    scale : float or array_like of floats
        Standard deviation (spread or "width") of the distribution. Must be
        non-negative.
    size : int o

In [173]:
rg.normal(100,25,size=(4,5))

array([[125.60630007,  56.65822447,  97.76765969,  72.65630162,
        108.02488174],
       [ 72.41986161,  80.60016141,  91.75806967,  63.73436272,
        126.72719347],
       [ 94.93971205,  67.84995443,  95.18259881,  69.53453121,
        104.15492382],
       [115.12328328, 145.55885189,  74.12818679, 118.58540606,
        106.89730353]])