# Data Science Numpy & CSV's

## Tasks Today:

1) <b>Numpy</b> <br>
 &nbsp;&nbsp;&nbsp;&nbsp; a) Python List Comparison <br>
 &nbsp;&nbsp;&nbsp;&nbsp; b) In-Class Exercise #1 <br>
 &nbsp;&nbsp;&nbsp;&nbsp; c) Importing <br>
 &nbsp;&nbsp;&nbsp;&nbsp; d) Creating an NDArray <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - np.array() <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - np.zeros() <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - np.ones() <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - np.arange() <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Making Lists into NDArrays <br>
 &nbsp;&nbsp;&nbsp;&nbsp; e) Performing Calculations on NDArrays <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Summation <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Difference <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Multiplication <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Division <br>
 &nbsp;&nbsp;&nbsp;&nbsp; f) Numpy Subsetting <br>
 &nbsp;&nbsp;&nbsp;&nbsp; g) Multi-dimensional Arrays <br>
 &nbsp;&nbsp;&nbsp;&nbsp; h) Indexing NDArrays <br>
 &nbsp;&nbsp;&nbsp;&nbsp; i) Checking NDArray Type <br>
 &nbsp;&nbsp;&nbsp;&nbsp; j) Altering NDArray Type <br>
 &nbsp;&nbsp;&nbsp;&nbsp; k) Checking the Shape <br>
 &nbsp;&nbsp;&nbsp;&nbsp; l) Altering the Shape <br>
 &nbsp;&nbsp;&nbsp;&nbsp; m) In-Class Exercise #2 <br>
 &nbsp;&nbsp;&nbsp;&nbsp; n) Complex Indexing & Assigning <br>
 &nbsp;&nbsp;&nbsp;&nbsp; o) Elementwise Multplication <br>
 &nbsp;&nbsp;&nbsp;&nbsp; p) np.where() <br>
 &nbsp;&nbsp;&nbsp;&nbsp; q) Random Sampling <br>

2) <b>Working With CSV's</b> <br>
 &nbsp;&nbsp;&nbsp;&nbsp; a) Imports <br>
 &nbsp;&nbsp;&nbsp;&nbsp; b) Reading a CSV <br>
 &nbsp;&nbsp;&nbsp;&nbsp; c) Loading a CSV's Data <br>
 &nbsp;&nbsp;&nbsp;&nbsp; d) Checking Number of Records <br>
 
3) <b>Exercises</b> <br>
 &nbsp;&nbsp;&nbsp;&nbsp; a) #1 - Calculate BMI with NDArrays <br>
 &nbsp;&nbsp;&nbsp;&nbsp; b) #2 - Find the Average Sum of Marathon Runners <br>
 &nbsp;&nbsp;&nbsp;&nbsp; c) #3 - Random Matrix Function <br>
 &nbsp;&nbsp;&nbsp;&nbsp; d) #4 - Comparing Boston Red Sox Hitting Numbers <br>

## Numpy <br>

<p>NumPy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.</p>
<ul>
    <li>Shape = Rows & Columns</li>
    <li>Matrix = Entire Array</li>
    <li>Vector = Variables to be applied (same vector as the one used in physics)</li>
    <li>Array = Similar to lists</li>
</ul>

#### Python List Comparison

<p>Lists are flexible, dynamic python objects that do their job quite well. But they do not support some mathematical operations in an intuitive way. Consider the summation of two lists, $l_1$ and $l_2$</p>

In [1]:
# create two lists and sum both of them together (results may not be what you expect)
l_1 = [1,2,3]
l_2 = [4,5,6]

l_1 + l_2
l_1 - l_2

# what if we want l_1 + l_2 = [5, 7, 9]

TypeError: unsupported operand type(s) for -: 'list' and 'list'

<p>If we wanted to sum lists elementwise, we could write our own function that does the job entirely within the framework of python</p>

#### In-Class Exercise #1 - Write a function that sums the indexes of two lists <br>
<p>Ex: [2, 3, 4] + [1, 5, 2] = [3, 8, 6]</p>

In [4]:
# input: two lists
# output: one list where indexess are the sum of the same numbered indexees of the input lists

def addLists(lst1, lst2):
    empty = []
    for num in range(len(lst1)):
        empty.append(lst1[num] + lst2[num])
    return empty

addLists(l_1, l_2)

    

[5, 7, 9]

#### Importing

In [11]:
# always import as np, standard across all of data science
!pip install numpy
import numpy as np

#### Creating an NDArray <br>
<p>NumPy is based around a class called the $\textit{NDArray}$, which is a flexible vector / matrix class that implements the intuitive matrix and vector arithmatic lacking in basic Python. Let's start by creating some NDArrays:</p>

###### - np.array()

In [12]:
arr1 = np.array([2,4,6])
arr2 = np.array([1,7,11])
print(arr1, type(arr1))
print(arr2, type(arr2))

[2 4 6] <class 'numpy.ndarray'>
[ 1  7 11] <class 'numpy.ndarray'>


###### - np.zeros()

In [13]:
# Shape -- np.zeros() has a parameter of "shape" that must be given
arr0 = np.zeros((3,2))
print(arr0, type(arr0))
arr0[2][1]

[[0. 0.]
 [0. 0.]
 [0. 0.]] <class 'numpy.ndarray'>


0.0

###### - np.ones()

In [14]:
arr_ones = np.ones((3,2), int)
print(arr_ones)

# notice no dots after the numbers, because we specified the datatype to be integer

[[1 1]
 [1 1]
 [1 1]]


###### - np.arange()

In [15]:
arr1100 = np.arage(1, 101, 2)
arr1100

AttributeError: module 'numpy' has no attribute 'arage'

###### - Making Lists into NDArrays

In [ ]:
animals = ['fennec fox', 'orca', '']

#### Performing Calculations on NDArrays

###### - Summation

In [16]:
print(arr1, arr2)
arr1 + arr2

[2 4 6] [ 1  7 11]


array([ 3, 11, 17])

###### - Difference

In [19]:
print(arr1, arr2)
arr1 - arr2

[2 4 6] [ 1  7 11]


array([ 1, -3, -5])

###### - Multiplication

In [18]:
print(arr1, arr2)
arr1 * arr2

[2 4 6] [ 1  7 11]


array([ 2, 28, 66])

###### - Division

In [17]:
print(arr1, arr2)
arr1 / arr2

[2 4 6] [ 1  7 11]


array([2.        , 0.57142857, 0.54545455])

#### Modulo

In [25]:
print(arr1, arr2)
result_mod = arr1 % arr2

[2 4 6] [ 1  7 11]


#### Floor Division

In [21]:
print(arr1, arr2)
arr1 // arr2

[2 4 6] [ 1  7 11]


array([2, 0, 0], dtype=int32)

#### Numpy Subsetting

In [27]:
# result3 <= 800
# where is arr1 evenly divisible by arr2?
# answer:
print(result_mod, result_mod == 0)

# needs a fix
test_ndStrings = np.array(['Bob', 'Mark', 'Angelica', 'Barb'])
print(test_ndStrings[test_ndStrings[0] == ''])

# test_ndStrings = np.array(['Bob','Mark','Angelica','Barb'])
# print(test_ndStrings[test_ndStrings[0] == 'B'])

# conditioal check, returns true or false
# print(arr1 < 2)
# print(arr2 >= 2)

# conditional check, that returns the elements that meet the given condition



[0 4 6] [ True False False]
[]


#### Multi-dimensional Arrays <br>
<p>NumPy seamlessly supports multidimensional arrays and matrices of arbitrary dimension without nesting NDArrays. NDArrays themselves are flexible and extensible and may be defined with such dimensions, with a rich API of common functions to facilitate their use. Let's start by building a two dimensional 3x3 matrix by conversion from a nested group of core python lists $M = [l_0, l_1, l_2]$:</p>

In [28]:
aList = [0,1,2]
bList = [3,4,5]
cList = [6,7,8]

# first step: convert lists into a Matrix
M = [aList, bList, cList]


# second step: place Matrix inside NDArray
ND_M = np.array(M)
ND_M


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Indexing NDArrays <br>
<p> Similar to lists within lists; however, the syntax looks more like C programming language.... It is [1, 2] to access the second row, third element.</p>

In [31]:
# row, column
print(ND_M[2, 2])

# or the normal double bracket notation
ND_M[1][1]

8


4

#### Assigning Values in NDArrays

In [33]:
ND_M[0, 0] = 34.434532
print(ND_M)
ND_M.dtype # if we try to add a float to an int32 array, we'll just get the int32 conversion of the float

[[34  1  2]
 [ 3  4  5]
 [ 6  7  8]]


dtype('int32')

<p>Notice above how we ended up with a 1 in the target element's place. This is a data type issue. The .dtype() method is supported by all NDArrays, as well as the .astype() method for casting between data types:</p>

#### Checking NDArray Type

In [34]:
# usind the .dtype() method
ND_M.dtype

dtype('int32')

#### Altering NDArray Type

In [35]:
# convert ND_M from int32 to float32
float_ND_M = ND_M.astype(np.float32)

In [ ]:
# Checking the Shape of the ND_M Numpy Array
# Using the method .shape


#### Checking the Shape <br>
<p>The behavior and properties of an NDArray are often sensitively dependent on the $\textit{shape}$ of the NDArray itself. The shape of an array can be found by calling the .shape method, which will return a tuple containing the array's dimensions:</p>

In [36]:
 # shape is always rows x columns
# Checking the Shape of the ND_M Numpy Array
# Using the method .shape

# print(type(result_changed.shape))

shapereturn = ND_M.shape
print(type(shapereturn))

<class 'tuple'>


#### Altering the Shape <br>
<p>As long as the number of elements remains fixed, we can reshape NDArrays at will:</p>

In [38]:
# Change the shape of the numpy array
# Using the method .reshape()

# The reshape should be a multiple of the original shape
# Meaning we can have a shape of (1,9) or (9,1) or (3,3)

# (9,1) == 9 rows , 1 column
# (1,9) == 1 column, 9 rows

print(ND_M, '\n')
print(ND_M.reshape(1,9), '\n')
print(ND_M.reshape(9,1), '\n')

print(x19[0,5])
print(x91[5,0])

[[34  1  2]
 [ 3  4  5]
 [ 6  7  8]] 

[[34  1  2  3  4  5  6  7  8]] 

[[34]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]] 



NameError: name 'x19' is not defined

In [ ]:
# keep in mind that the shape numbers do matter, (9, 1) is different than (1, 9)


#### In-Class Exercise #2 - Create a matrix of range 0 up to 16 and reshape it into a 4x4 matrice

In [42]:
"""
OUTPUT
    array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])
"""
newarray = np.arange(0,16).reshape(4,4)
print(newarray)

# python range, np.array(), np.reshape()
fourxfour = np.array(range(0,16)).reshape(4,4)
print(fourxfour)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


#### Complex Indexing & Assinging

In [47]:
print('Seting up matrix:')
print('Before assignment: all zeros:')
M = np.zeros((6,6))
print(M)
print('\n')

# remember bracket comma notation M[row, column]
# except with complex indexing and assignment, we're essentially replacing row and column with a slice

# Set every first element in each row to 1
M[:,0] = 1
print('After assignment of 1 to first column:')
print(M)
print('\n')

# Set all elements in rows 3 to 5 (Excluding 5) to be equal to the number 5
M[3:5, :] = 5
print('After assinging 5 to rows 3-5 not including 5:')
print(M)
print('\n')

# Set all elements in rows 3 to 5 (Excluding 5) to be equal to the number 5 excluding first and last columns
M[3:5, 1:6] = 2
print('After assinging 2 to rows 3-5 not including 5 or first/last colums:')
print(M)
print('\n')

# reset the matrix back to 0
M *= 0
print('After reset:')
print(M)
print('\n')

# Creating a vector in numpy
M[0, :] = v
print('After assigning vector v to row 0 of matrix M:')
print(M)
print('\n')


# Set the first row to that range of vector numbers we just created
fourxfour = np.array(range(0,16)).reshape(4,4)
M[2:, 2:] = fourxfour
print('After assigning')

#################
# M[rows,columns]
#################

Seting up matrix:
Before assignment: all zeros:
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


After assignment of 1 to first column:
[[1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]]


After assinging 5 to rows 3-5 not including 5:
[[1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5.]
 [1. 0. 0. 0. 0. 0.]]


After assinging 2 to rows 3-5 not including 5:
[[1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [5. 2. 2. 2. 2. 2.]
 [5. 2. 2. 2. 2. 2.]
 [1. 0. 0. 0. 0. 0.]]




#### Elementwise Multiplication

<p>As long as the shapes of NDArrays are 'compatible', they can be multiplied elementwise, broadcasted, used in inner products, and much much more. 'Compatible' in this context can mean compatible in the linear algebraic sense, i.e. for inner products and other matrix multiplication, or simply sharing a dimension in such a manner that broadcasting 'makes sense'. Here are some examples of this:</p>

In [50]:
# Initialize a vector of range 6, then reset Matrix to zero and run vector multiplication on the matrix
v61 = np.arange(6).reshape(6,1)
v16 = np.arange(6)
M[0, :] = 0
print(M*v61)
print(M*v16)

# Reset the Matrix to 0


[[ 0.  0.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.  0.]
 [ 2.  0.  0.  0.  0.  0.]
 [15.  6.  6.  6.  6.  6.]
 [20.  8.  8.  8.  8.  8.]
 [ 5.  0.  0.  0.  0.  0.]]
[[ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  2.  4.  6.  8. 10.]
 [ 0.  2.  4.  6.  8. 10.]
 [ 0.  0.  0.  0.  0.  0.]]


array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  2.,  4.,  6.,  8., 10.],
       [ 0.,  2.,  4.,  6.,  8., 10.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

#### np.where() <br>
<p>If statement within NDArrays that allows you to run conditionals on the entire array</p>

In [55]:
newarray = np.array(range(10, 401, 10)).reshape(4,10)
print(newarray)
print('\n')
print('Get the locations of numbers divisibale by 20')
np.where(newarray%20==0) # where is returning two vectors- one of row numbers and one of column numbers
# Transform Data based on boolean mask == True

x = newarray[np.where(newarray%20==0)].reshape(4,5) # subsetting
print(x)

newarray[np.where(newarray%20==0)] = 0 
# using np.where() for complex assignment can be helpful for cleaning data
print(newarray)


[[ 10  20  30  40  50  60  70  80  90 100]
 [110 120 130 140 150 160 170 180 190 200]
 [210 220 230 240 250 260 270 280 290 300]
 [310 320 330 340 350 360 370 380 390 400]]


Get the locations of numbers divisibale by 20
[[ 20  40  60  80 100]
 [120 140 160 180 200]
 [220 240 260 280 300]
 [320 340 360 380 400]]
[[ 10  20  30  40  50  60  70  80  90 100]
 [110 120 130 140 150 160 170 180 190 200]
 [210 220 230 240 250 260 270 280 290 300]
 [310 320 330 340 350 360 370 380 390 400]]


#### Random Sampling <br>
<p>NumPy provides machinery to work with random numbers - something often needed in a broad spectrum of data science applications.</p>

In [57]:
# np.random.uniform()

# A single call generates a single random number between 0 and 1

print('Here is a random number: %s' % np.random.uniform())

# You can also pass some parameters or bounds

print('Here is a random number between 0 and 1 Million: %s' % np.random.uniform(0, 1e6))

# You can also generate a bunch of random numbers all at once

print('Here are 5 random numbers between 0 and 10: %s' % np.random.uniform(0, 10, 5))

# Even matrices with shapes as a parameter

print('Here is a 3x3 matrix with numbers between 0 and 10: \n %s' % np.random.uniform(0, 10, (3, 3)))

# integers: randint()
print(f'Here is a random integer between 0 and 100: \n {np.random.randint(0,101)}')

Here is a random number: 0.7990855282605822
Here is a random number between 0 and 1 Million: 964416.1229041505
Here are 5 random numbers between 0 and 10: [0.17136218 6.78759102 3.16653454 8.67263449 1.0493684 ]
Here is a 3x3 matrix with numbers between 0 and 10: 
 [[7.08793437 6.11416087 8.25988995]
 [7.53119511 2.01027038 2.69601791]
 [8.21337405 5.73957427 0.53796632]]
Here is a random integer between 0 and 100: 
 52


## Working With CSV's

#### Imports

In [58]:
import csv
import numpy as np
from datetime import datetime

#### Reading a CSV

In [ ]:
# Creating Function to open and read CSV data
# essentially we can open a file in the background of python, read that file, and then close it once its been read

def open_csv(filename, delimiter=','):
    # define an empty list in which to store our data
    data = []
    # built-in open within a with block
    with open(filename, encoding='utf-8') as mData:
        # use the csv module reader method to create a list
        oData = csv.reader(mData, delimiter=delimiter)

        # loop over whats in the csv.reader and add that row by row to the data list
        for row in oData:
            data.append(row)


    return data

#### Loading a CSV's Data 

In [ ]:
FIELDS = ['Rk', 'Pos', 'Name', 'Age', 'G', 'PA', 'AB', 'R', 'H', '2B', '3B', 'HR', 'RBI', 'SB', 'CS', 
          'BB', 'SO', 'BA', 'OBP', 'SLG', 'OPS', 'OPS+', 'TB', 'GDP', 'HBP', 'SH', 'SF', 'IBB']

# i = integer, f = float, |s25 = string with 25 characters
DATATYPES = [('rk', 'i'), ('pos', '|S25'), ('name', '|S25'), ('age', 'i'), ('g', 'i'), ('pa', 'i'), ('ab', 'i'),
                ('r', 'i'), ('h', 'i'), ('2b', 'i'), ('3b', 'i'), ('hr', 'i'), ('rbi', 'i'), ('sb', 'i'), ('cs', 'i'),
                ('bb', 'i'), ('so', 'i'), ('ba', 'f'), ('obp', 'f'), ('slg', 'f'), ('ops', 'f'), ('opsp', 'i'),
                ('tb', 'i'), ('gdp', 'i'), ('hbp', 'i'), ('sh', 'i'), ('sf', 'i'), ('ibb', 'i')]

# instead of loading csv normally, let's load it into a numpy array to calculate results on



#### Summing the top 5 hitters for HR's

In [ ]:
# find the top 5 hr hitters

# Step 1: Get all HR data into a variable
# Step 2: Get all Player Names
# Step 3: Create new list for new_names (empty to start)
# Step 4: Decode the player names into regular strings
# Step 5: Grab all data and place inside of a zipped list
# Step 6: Sort values based on HR data

# Step 1


# Step 2


# Step 3


# Step 4

# print(new_names)

# Step 5

# print(zipped_values)

# Step 6


# Exercises To Complete.... <br>
<p>Given in separate file after completion of this file</p>