In [2]:
import numpy as np

In [4]:
a = np.array([1,2,3])

In [5]:
len(a)

3

In [7]:
a.sort()

In [8]:
array([1,2,3])

NameError: name 'array' is not defined

In [9]:
a

array([1, 2, 3])

In [10]:
a = np.arange(17)

In [11]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [12]:
r =range(17)

In [13]:
[3 * i for i in r]

[0, 3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48]

In [14]:
3 * a

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48])

In [15]:
a**2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256])

In [16]:
%%timeit
[i**2 for i in range(1000)]

166 µs ± 1.26 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [17]:
%%timeit
np.arrange(1000)**2

AttributeError: module 'numpy' has no attribute 'arrange'

In [18]:
%%timeit
np.arange(1000)**2

1.42 µs ± 8.83 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [19]:
a = np.array([[1, 2, 3], [4, 5, 6]])

In [20]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
a.shape

(2, 3)

In [22]:
a[0, :]

array([1, 2, 3])

In [23]:
a[:, 0]

array([1, 4])

In [25]:
A = a[0:2, 0:2]
A

array([[1, 2],
       [4, 5]])

In [26]:
Ainv = np.linalg.inv(A)

In [27]:
Ainv

array([[-1.66666667,  0.66666667],
       [ 1.33333333, -0.33333333]])

In [28]:
A + Ainv

array([[-0.66666667,  2.66666667],
       [ 5.33333333,  4.66666667]])

In [29]:
A * Ainv

array([[-1.66666667,  1.33333333],
       [ 5.33333333, -1.66666667]])

In [30]:
A @ Ainv

array([[1.00000000e+00, 0.00000000e+00],
       [2.22044605e-16, 1.00000000e+00]])

In [31]:
a = np.(arange(16)

SyntaxError: invalid syntax (3300251486.py, line 1)

In [32]:
a = np.arange(16)

In [33]:
a.reshape((2, 8))

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [34]:
b = a.reshape((4, 4))

In [35]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [36]:
a.reshape((-1, 2))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [37]:
a.reshape((-1, 1))

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15]])

In [38]:
import math

In [39]:
math.e

2.718281828459045

In [40]:
np.e

2.718281828459045

In [41]:
math.e == np.e

True

In [42]:
np.pi

3.141592653589793

In [43]:
np.tau

AttributeError: module 'numpy' has no attribute 'tau'

In [44]:
math.tau

6.283185307179586

In [45]:
np.cos(math.tau)

1.0

In [46]:
np.sin(math.tau)

-2.4492935982947064e-16

In [47]:
np.log(np.e)

1.0

In [48]:
np.log10(np.e)

0.4342944819032518

In [51]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [52]:
angles = math.tau* np.arange(5) / 4

In [53]:
angles

array([0.        , 1.57079633, 3.14159265, 4.71238898, 6.28318531])

In [54]:
a = np.cos(angles)

In [55]:
a

array([ 1.0000000e+00,  6.1232340e-17, -1.0000000e+00, -1.8369702e-16,
        1.0000000e+00])

In [56]:
angles = np.linspace(0, math.tau, 100)

In [57]:
np.cos(angles)

array([ 1.        ,  0.99798668,  0.99195481,  0.9819287 ,  0.9679487 ,
        0.95007112,  0.92836793,  0.90292654,  0.87384938,  0.84125353,
        0.80527026,  0.76604444,  0.72373404,  0.67850941,  0.63055267,
        0.58005691,  0.52722547,  0.47227107,  0.41541501,  0.35688622,
        0.29692038,  0.23575894,  0.17364818,  0.1108382 ,  0.04758192,
       -0.01586596, -0.07924996, -0.14231484, -0.20480667, -0.26647381,
       -0.32706796, -0.38634513, -0.44406661, -0.5       , -0.55392006,
       -0.60560969, -0.65486073, -0.70147489, -0.74526445, -0.78605309,
       -0.82367658, -0.85798341, -0.88883545, -0.91610846, -0.93969262,
       -0.95949297, -0.97542979, -0.98743889, -0.99547192, -0.99949654,
       -0.99949654, -0.99547192, -0.98743889, -0.97542979, -0.95949297,
       -0.93969262, -0.91610846, -0.88883545, -0.85798341, -0.82367658,
       -0.78605309, -0.74526445, -0.70147489, -0.65486073, -0.60560969,
       -0.55392006, -0.5       , -0.44406661, -0.38634513, -0.32

In [58]:
np.arange(16).reshape((4, 17))

ValueError: cannot reshape array of size 16 into shape (4,17)

In [59]:
A = np.random.rand(5, 5)

In [60]:
A

array([[0.32273781, 0.13873295, 0.8482229 , 0.65077901, 0.7188897 ],
       [0.04423137, 0.74493349, 0.88401706, 0.62543012, 0.63119496],
       [0.0036191 , 0.90203045, 0.15553226, 0.5638374 , 0.05763237],
       [0.88879207, 0.64360305, 0.78562682, 0.94633039, 0.33535556],
       [0.9214733 , 0.77282759, 0.62812459, 0.93780683, 0.51182214]])

In [61]:
Ainv = np.linalg.inv(A)

In [62]:
Ainv

array([[-1.41538664,  0.50202958, -1.52790565,  0.0708414 ,  1.49451937],
       [-1.97253831,  1.66361816, -0.54836433, -0.54160227,  1.13555648],
       [-1.23941194,  1.8363272 , -1.36357637,  2.33269571, -1.89866024],
       [ 3.42835675, -3.1889894 ,  3.07602539,  0.54705746, -1.58741415],
       [ 0.76597261,  0.17372624, -0.38393502, -3.17487447,  2.78716735]])

In [63]:
I = A @ Ainv


In [64]:
I[np.isclose(I, 0)] = 0

In [65]:
I

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])