<a href="https://colab.research.google.com/github/ingAliBahrami/classTutorial/blob/main/OOP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
r= np.random.randn()
r
if r > 0:
  outcome =  'positive'
else:
  outcome = 'negetive'

print(f'the number is' + ' ' + outcome)


the number is negetive


In [ ]:
caketype = 'carrot'
if caketype == 'carrot':
  print('total yam!')
elif caketype == 'chocolate':
  print('yammy as well!')
elif caketype == 'friutcake':
  print('is this thing good for me?')
else:
  print("ok, i'll try it.")



total yam!


In [ ]:
if 1<3 and 4==4:
  print('both conditionals are true')
else :
  print('at least one conditional is false')

both conditionals are true


In [ ]:
import numpy as np
def dotproduct(a,b):
  # check both vectors are numpy arrays
if not (isinstance(a,np.ndarray) and isinstance(b,np.ndarray)):
   raise Exception('input must be numpy arrays')
  # check both vrctors have same lenght
  if not len(a) == len(b):
   raise Exception('inputs must be the same lenght')
  return sum(a*b)

  #return the dot product

a = np.array([1,2,3,4])
b = np.array([-1,12,3,-4])
# np.dot(a,b) # or sum(a*b)
dotproduct(a,b)

16

In [ ]:
import numpy as np
numbers = np.linspace(3,17.1,25)

for i in range(len(numbers)):
  x = numbers[i]
  print('iteration'+ ' ' + str(i)+' ' + 'has a value of'+ ' '  + str(x))

iteration 0 has a value of 3.0
iteration 1 has a value of 3.5875
iteration 2 has a value of 4.175
iteration 3 has a value of 4.7625
iteration 4 has a value of 5.35
iteration 5 has a value of 5.9375
iteration 6 has a value of 6.525
iteration 7 has a value of 7.1125
iteration 8 has a value of 7.7
iteration 9 has a value of 8.287500000000001
iteration 10 has a value of 8.875
iteration 11 has a value of 9.4625
iteration 12 has a value of 10.05
iteration 13 has a value of 10.6375
iteration 14 has a value of 11.225
iteration 15 has a value of 11.8125
iteration 16 has a value of 12.4
iteration 17 has a value of 12.9875
iteration 18 has a value of 13.575000000000001
iteration 19 has a value of 14.1625
iteration 20 has a value of 14.75
iteration 21 has a value of 15.3375
iteration 22 has a value of 15.925
iteration 23 has a value of 16.512500000000003
iteration 24 has a value of 17.1


In [ ]:
for n in range(18):
  if n%2 == 0:
    print(str(n) +' '+ 'an even number')
  else:
    print(str(n) +' '+ 'an odd number')

  print('done testing')



0 an even number
done testing
1 an odd number
done testing
2 an even number
done testing
3 an odd number
done testing
4 an even number
done testing
5 an odd number
done testing
6 an even number
done testing
7 an odd number
done testing
8 an even number
done testing
9 an odd number
done testing
10 an even number
done testing
11 an odd number
done testing
12 an even number
done testing
13 an odd number
done testing
14 an even number
done testing
15 an odd number
done testing
16 an even number
done testing
17 an odd number
done testing


In [ ]:
def fibseq(N):
  v = [0,1]
  for i in range(N):
    v.append(sum(v[-2:]))
  print(v)

fibseq(7)


[0, 1, 1, 2, 3, 5, 8, 13, 21]


In [ ]:
import numpy as np
ns = np.linspace(-5,5,7)
for i,n in enumerate(ns):
  print('index' + ' ' + str(i) + ' ' + 'has a value of' + ' ' +str(ns[i]))

index 0 has a value of -5.0
index 1 has a value of -3.333333333333333
index 2 has a value of -1.6666666666666665
index 3 has a value of 0.0
index 4 has a value of 1.666666666666667
index 5 has a value of 3.333333333333334
index 6 has a value of 5.0


In [ ]:
text = 'Hello my name is Ali '
vowels = np.zeros (len(text))
for i,l in enumerate(text):
  print(i,l)

0 H
1 e
2 l
3 l
4 o
5  
6 m
7 y
8  
9 n
10 a
11 m
12 e
13  
14 i
15 s
16  
17 A
18 l
19 i
20  


In [ ]:
lista = [3,4,5,6,3,-17]
listb = ['q','w','e','r','t','y']
for i in range (len(lista)):
  print(str(lista[i]) + ' ' + listb[i])

3 q
4 w
5 e
6 r
3 t
-17 y


In [ ]:
lista = [3,4,5,6,]
listb = ['q','w','e','r','t','y']
for a,b in zip(lista, listb):
  print (str(a)+ ' ' + str(b))

3 q
4 w
5 e
6 r


In [ ]:
names = ['a','b','c','d']
values = [10,20,30,40]
D = dict(zip(names, values))
D


{'a': 10, 'b': 20, 'c': 30, 'd': 40}

In [ ]:
for i in range(10):
  if i%2 == 0:
    continue    # means skip it or ignor it and do the vise versa
  print(i)




1
3
5
7
9


In [ ]:
text = 'Hello my name is Mike'
for i in text:
  if i in 'aeiou':  # being lowe case and capital letter is essential here
    continue
  print(i)

H
l
l
 
m
y
 
n
m
 
s
 
M
k


In [ ]:
# r = np.zeros(10)
r = np.full(10,0)
r

NameError: ignored

In [ ]:
import numpy as np
shape = (4,5)
r = np.zeros(shape)
r

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
# exercise :to compare tree methods of creating an array
# N = 10000
# r[i] = i**2
# time test
import time
import numpy as np
time.perf_counter()
N = 10000
toc = [0]*3
# list append
tic = time.perf_counter()
r = []
for i in range(N):
  r.append( i**2)
toc[0] = (time.perf_counter() - tic)*1000 # to convert it to mili second



# numpy append
tic = time.perf_counter()
r = np.array([])
for i in range(N):
  np.append(r, i**2)
toc[1] = (time.perf_counter() - tic)*1000


# numpy initialization
tic = time.perf_counter()
r = np.zeros(N)
for i in range(N):
  r[i] = i**2
toc[2] = (time.perf_counter() - tic)*1000
toc






[5.181577999792353, 43.77786099985315, 4.461446000277647]

In [ ]:
import random
r = random.randint(1,10)
print('r is large') if r>5 else print('r is small')

r is large


In [ ]:
for i in range(10):
  print(i**2)

0
1
4
9
16
25
36
49
64
81


In [ ]:
lst = [i**2 for i in range(10) if i>=5]
lst

[25, 36, 49, 64, 81]

In [ ]:
# exercise: convert the follwing loops into a single-line loop
text = ['promissing', 'yves', 'that', 'home', 'one', 'nob']
# for word in text:
 # print(word[0])

[print(word[0]) for word in text];

p
y
t
h
o
n


In [ ]:
newlist = ['']*10
#for i in range(10):
  #if 1 % 2 == 1:
    #newlist[i] = 'odd'
  #else:
    #newlist[i] = i

#newlist
n1 = ['odd' if 1%2==1 else i for i in range(10,0)]
n1

[]

In [ ]:
import numpy as np
# repeat without using numpy
x1 = np.linspace(-3,3,11)
y1 = x1**2
x2 = [i/(5/3) for i in range(-5,3)]
y2 = [i**2 for i in x2]
print(x1)
print(y1)
print('')
print('')
print(x2)
print(y2)


[-3.  -2.4 -1.8 -1.2 -0.6  0.   0.6  1.2  1.8  2.4  3. ]
[9.   5.76 3.24 1.44 0.36 0.   0.36 1.44 3.24 5.76 9.  ]


[-3.0, -2.4, -1.7999999999999998, -1.2, -0.6, 0.0, 0.6, 1.2]
[9.0, 5.76, 3.2399999999999993, 1.44, 0.36, 0.0, 0.36, 1.44]


In [ ]:
i = 0
while True:
  print(i)
  i += 1
  if i==8:
    break

#i = 0
#while i<8:
 # print(i)
  #i += 1


0
1
2
3
4
5
6
7


In [ ]:
# exercise: poisson counter
# 1) specify a target np.exp(-lambda -> 10)
# 2) initialize a counter=0, currval == 1
# 3) multipy the currval by a random number u[0,1]
# 4) repeat step 3 until currval < target
# 5) return the number of times that you go through step 4

In [ ]:
import numpy as np
x=np.array([[1,2,3],
            [2,3,4],
            [3,4,5],
            [4,5,6]])

w=np.array([10,20,30])
print(x), print(''), print(w);

for i in range(x.shape[0]):
   x[i,:] += w
x

[[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]]

[10 20 30]


array([[11, 22, 33],
       [12, 23, 34],
       [13, 24, 35],
       [14, 25, 36]])

In [ ]:
fimport numpy as np
v = np.array([-1,0,1,0],ndmin=2).T
print(x), print('')
x*v

SyntaxError: ignored

In [ ]:
class Shomaresh:
  def __init__(self, v: int, i: int ) -> None:
    self.val = v
    self.incr = i

  def afzayesh(self) -> None:
    self.val += self.incr
  def __repr__(self) -> str:
    return str(self.val)







In [ ]:
from re import X
class Point:
  """"nemayeshe yek noghte dar 2d."""
noghte1 = Point()
noghte1.x = 10.0
noghte1.y = 20.0
x = noghte1.x
y = noghte1.y
'(%g, %g)' %(noghte1.x, noghte1.y)
import math
fasele = math.sqrt(noghte1.x**2 + noghte1.y**2)
fasele

22.360679774997898

In [ ]:
def f():
  print('ali')
f()
def g():
  return 'ali'
g()
def h(p):
  print(p)
h('ali')

ali
ali


In [ ]:
def fact(n):
  if n == 1:
    return 1
  else:
    return n * fact(n-1)

fact(5)


120

In [ ]:
class Test:
  ''' class for add & mul'''
  def __init__(self, a, b):
    self.a = a
    self.b = b

  def add(self):
    return self.a + self.b

  def mul(self):
    return self.a * self.b

ob1 = Test(2, 3)

print(ob1.a)
print(ob1.b)
print(ob1.add())
print(ob1.mul())
print(ob1.__dict__)
print(ob1.__doc__)

ob2 = Test(6, 1)
x = ob2.add()
print(x)
print(ob2.a)
print(ob2.b)
print(ob2.add())
print(ob2.mul())
print(ob2.__dict__)
print(ob2.__doc__)

class Test:
  ''' class for add & mul'''
  def set_var(self, a, b):
    self.a = a
    self.b = b

  def add(self):
    return self.a + self.b

  def mul(self):
    return self.a * self.b

ob1 = Test()
ob1.set_var(2,3)
print(ob1.a)
print(ob1.b)
print(ob1.add())
print(ob1.mul())


2
3
5
6
{'a': 2, 'b': 3}
 class for add & mul
7
6
1
7
6
{'a': 6, 'b': 1}
 class for add & mul
2
3
5
6


In [ ]:
import traitlets
class Book:
  def __init__(self, author, title):
    self.author = author
    self.title = title

  def info(self):
    print(self.title, ':' + self.author)

x = Book('shirafkan', 'c++')
x.info()


In [ ]:
class Student:
  def __init__(self, name, score = None):
    self.d = {}
    self.d['name'] = name
    self.d['score'] = score

  def get_Stu(self):
    return self.d

lst = []
ob1 = Student('mahsa', 20)
ob2 = Student ('ali', 17)
lst.append(ob1.get_Stu())
lst.append(ob2.get_Stu())
print(lst)
print(lst[0])
print(lst[1])

[{'name': 'mahsa', 'score': 20}, {'name': 'ali', 'score': 17}]
{'name': 'mahsa', 'score': 20}
{'name': 'ali', 'score': 17}


In [ ]:
class Circle:
  def __init__(self, r):
    self.r = r

  def area(self):
    return self.r ** 2 * 3.14

x= Circle(8)
print(x.area())
print(isinstance(x, Circle))


200.96
True


In [ ]:
class Counter:
  def __init__(self, x):
    self.x = x

  def up(self):
    self.x += 1

  def down(self):
    self.x -= 1

ob = Counter(4)
print(ob.x)
ob.up()
ob.up()
print(ob.x)
ob.down()
print(ob.x)




4
6
5


class C():
  def __init__(self):
    self.s = ''

  def get_string(self):
    self.s = input('name more nazara ra vared konid:')

  def show(self):
    print(self.s.upper())

ob = C()
ob.get_string()
ob.show()


In [9]:
class Email:
  def f(self):
    self.sent = False

  def g(self):
    self.sent = True

ob = Email()
ob.g()
print(ob.sent)


True


In [15]:
class Machine:
  model = 'peugeot'
  def __init__(self, t):
    self.t = t

m1 = Machine('206')
m2 = Machine('207')
print(m1.model)
print(m2.model)
print(m1.t)
print(m2.t)


peugeot
peugeot
206
207


In [23]:
class C:
  lst = []
  def __init__(self, name):
    self.name = name

  def f(self, x):
    self.lst.append(x)

ob1 = C('A')
ob2 = C('B')

ob1.f(1)
ob1.f(2)
ob1.f(3)

print(ob1.lst)
print(ob2.lst)

ob2.f(4)
print(ob2.lst)

[1, 2, 3]
[1, 2, 3]
[1, 2, 3, 4]


In [25]:
class C:
  def __init__(self, name):
    self.name = name
    self.lst = []

  def f(self, x):
    self.lst.append(x)

ob1 = C('A')
ob2 = C('B')

ob1.f(1)
ob1.f(2)
ob1.f(3)

print(ob1.lst)
print(ob2.lst)

ob2.f(4)
print(ob2.lst)

[1, 2, 3]
[]
[4]


In [33]:
from os import name
class Student:
  stream = 'cse'  # class variable
  def __init__(self, name, score):
    self.name = name       #intance variable
    self.score = score     #intance variable

# objects of Student class
s1 = Student('ali', 19)
s2 = Student('sara', 18)

print(s1.name)
print(s2.name)

print(s1.stream)
print(s2.stream)
print(Student.stream)





ali
sara
cse
cse
cse


In [36]:
class Dog:
  animal = 'dog'
  def __init__(self, b, c):
    self.b = b
    self.c = c

d1 = Dog('pug', 'brown')
d2 = Dog('bulldog', 'black')

print(d1.animal)
print(d2.animal)

print(d1.b)
print(d2.b)
print(d1.c)
print(d2.c)


dog
dog
pug
bulldog
brown
black


In [58]:
# Private
class Test:
  def __init__(self, a, b):
    self.a = a    # public
    self.__b = b    # private, no access out of class

  def f(self):
    self.__b = 2     # or += 1 for example
    print(self.__b)
ob = Test(1, 2)
print(ob.a)
# print(ob.b)   # error
# print(ob.__b)  # attribute error
ob.f()
print(ob.__dict__)
# how we access to private out of class
print(ob._Test__b)  # majic method named Mangling
# we can modify too
ob._Test__b = 8
print(ob._Test__b)


1
2
{'a': 1, '_Test__b': 2}
2
8


In [3]:
# private
class S:
  def __init__(self, x):
    self.__a = x

  def f(self):
    print(self.__a)
    self.__a += 1
    return(self.__a)

  def g(self, m):
    print(m + self.f())

ob = S(1)
print(ob.__dict__)
print(ob.f())
ob.g(8)

{'_S__a': 1}
1
2
2
11


In [6]:
class AB:
  __x = 3

  def show(self):
    print(self.__x)

ob =  AB()
ob.show()
print(ob._AB__x)


3
3


In [12]:
class ABC:
  def __f(self):
    print(1)

  def g(self):
    return(self.__f())

ob = ABC()
ob.g()
# ob.__f(())    # AttributeError: 'ABC' object has no attribute '__f'
ob._ABC__f()    # Mangling

1
1
