<a href="https://colab.research.google.com/github/JorgeEncinas/lp_numpy/blob/main/LP_Numpy_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
L = [1, 2, 3]

In [ ]:
A = np.array([1, 2, 3])

In [ ]:
L, A, A.dtype

([1, 2, 3], array([1, 2, 3]), dtype('int64'))

In [ ]:
for l in L:
  print(l)

1
2
3


In [ ]:
for a in A:
  print(a)

1
2
3


In [ ]:
L.append(4)
L

[1, 2, 3, 4]

In [ ]:
# NumPy has no "append" method though.
A.append(4)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [ ]:
L += [5]
L

[1, 2, 3, 4, 5]

In [ ]:
# This will broadcast this Rank-0 across your Rank-1 Vector
A + np.array([4])

array([5, 6, 7])

In [ ]:
A + np.array([1, 2, 3])

array([2, 4, 6])

In [ ]:
# Now it must have some intuitive way of broadcasting, otherwise it won't "get" it.
A + np.array([1, 2])

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [ ]:
#This also broadcasts
2 * A

array([2, 4, 6])

In [ ]:
# With a normal list we get a repetition of it instead
2 * L

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [ ]:
# Same as adding
L + L

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [ ]:
display(A)
np.array([1, 2, 3]) * A

array([1, 2, 3])

array([1, 4, 9])

In [ ]:
L2 = []
for e in L:
  L2.append(e + 3)
L2

[4, 5, 6, 7, 8]

In [ ]:
L2 = [e + 3 for e in L]
L2

[4, 5, 6, 7, 8]

In [ ]:
L**2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [ ]:
L2 = []
for e in L:
  L2.append(e**2)
L2

[1, 4, 9, 16, 25]

In [ ]:
A**2

array([1, 4, 9])

In [ ]:
# If you apply a function to a numpy array, it usually applies Element-Wise
np.log(A)

array([0.        , 0.69314718, 1.09861229])

In [ ]:
np.sqrt(A)

array([1.        , 1.41421356, 1.73205081])

In [ ]:
np.exp(A)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [ ]:
np.tanh(A)

array([0.76159416, 0.96402758, 0.99505475])

In [ ]:
# DOT PRODUCT or INNER PRODUCT in NumPy

a = np.array([1, 2])
b = np.array([3, 4])

In [ ]:
dot = 0
for e, f in zip(a, b):
  dot += e * f
print(dot)

11


In [ ]:
np.dot(a, b)

11

In [ ]:
dot = 0
for i in range(len(a)):
  dot += a[i] * b[i]
dot

11

In [ ]:
#Element-wise
display(a * b)

#Since the Dot Product is just the sum of these elements, we could just sum these.
display(np.sum(a*b))

array([3, 8])

11

In [ ]:
(a*b).sum()

11

In [ ]:
a.dot(b)

11

In [ ]:
a @ b #Also the dot product

11

In [ ]:
# Magnitude of a vector
# Square root, of the sum, of all the elements squared

# Another way to compute the Dot Product is:
# a.T b = ||a|| ||b|| cos (theta_a_b)

# Since we don't know the cosine, what we can do is calculate the cosine, given we have all other values.

magnitude_a = np.sqrt(np.sum(a**2))
magnitude_a

2.23606797749979

In [ ]:
magnitude_b = np.sqrt(np.sum(b**2))
magnitude_b

5.0

In [ ]:
a.dot(b)

11

In [ ]:
np.linalg.norm(a)

2.23606797749979

In [ ]:
# cosine = a.dot(b) / norm_a * norm_b
cosine_angle = (a.dot(b)) / (magnitude_a * magnitude_b)
cosine_angle

0.9838699100999074

In [ ]:
angle = np.arccos(cosine_angle)
angle

0.17985349979247847

# Speed Test
Let's see speed in action

In [ ]:
from datetime import datetime
import numpy as np

a = np.random.randn(100)
b = np.random.randn(100)
T = 100000

def slow_dot_product(a, b):
  result = 0
  for e, f in zip(a, b):
    result += e*f
  return result

t0 = datetime.now()
for t in range(T):
  slow_dot_product(a, b)
dt1 = datetime.now() - t0

t0 = datetime.now()
for t in range(T):
  np.dot(a, b)
dt2 = datetime.now() - t0

display(dt1.total_seconds())
display(dt2.total_seconds())
display(dt1.total_seconds() / dt2.total_seconds())

4.001476

0.112513

35.56456587238808

 # Matrices
 This is just a quick demo.
 Numpy has a numpy.matrix, which must be 2 dimensional, so it's not recommended.
 What we use instead is a ndarray. If you see a numpy.matrix object, first transform it into a numpy array

In [ ]:
L = [[1, 2], [3, 4]]
L

[[1, 2], [3, 4]]

In [ ]:
L[0]

[1, 2]

In [ ]:
L[0][1]

2

In [ ]:
A = np.array([[1, 2], [3, 4]])
A

array([[1, 2],
       [3, 4]])

In [ ]:
A[0][1]

2

In [ ]:
A[0]

array([1, 2])

In [ ]:
A[0, 1]

2

In [ ]:
A[:, 0]

array([1, 3])

In [ ]:
A[0, :]

array([1, 2])

In [ ]:
A.T

array([[1, 3],
       [2, 4]])

In [ ]:
np.exp(A)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [ ]:
np.exp(L) #Treats it as if it were a NumPy array, even if it's not.

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [ ]:
B = np.array([[1,2,3], [4,5,6]])

In [ ]:
A.dot(B)

array([[ 9, 12, 15],
       [19, 26, 33]])

In [ ]:
A * B

ValueError: operands could not be broadcast together with shapes (2,2) (2,3) 

In [ ]:
B.T.dot(A)

array([[13, 18],
       [17, 24],
       [21, 30]])

In [ ]:
A.dot(B)

array([[ 9, 12, 15],
       [19, 26, 33]])

In [ ]:
A.dot(B.T)

ValueError: shapes (2,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

# Other NumPy operations
- Determinant
- Inverse

In [ ]:
np.linalg.det(A)

-2.0000000000000004

In [ ]:
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [ ]:
np.linalg.inv(A).dot(A)

array([[1.00000000e+00, 0.00000000e+00],
       [1.11022302e-16, 1.00000000e+00]])

Inverting a Matrix is not an exact operation. It's inaccurate.
The algorithms are not exact, so be careful, and check if your equation can be simplified.

This inaccuracy in computation is why our Determinant is also not -2 exactly.

In [ ]:
np.trace(A) #Matrix Trace

5

In [ ]:
np.diag(A) #Diag function.

array([1, 4])

In [ ]:
# If you put in a Vector, it'll turn your diagonal vector into a matrix that has zeros elsewhere
# If you put in a Matrix, it returns the diagonal.
np.diag([1, 4])

array([[1, 0],
       [0, 4]])

In [ ]:
# EigenValues and EigenVectors
np.linalg.eig(A)

EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))

In [ ]:
# What are these?
# In Eigen Decomposition, the first returned object is an Array with all the eigenvalues.
# The second return value is an array containing all the Eigen Vectors, organized into a Matrix


# We can use what we know about Eigen Decomposition to check if this is correct
np.linalg.eig(A)

EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))

In [ ]:
Lam, V = np.linalg.eig(A)
Lam, V

(array([-0.37228132,  5.37228132]),
 array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

In [ ]:
V[:,0] * Lam[0] == A @ V[:, 0]

array([ True, False])

In [ ]:
# NumPy applied this similarity element-wise.
# Now why is one True, one False?

In [ ]:
data1 = V[:,0] * Lam[0]
data1

array([ 0.30697009, -0.21062466])

In [ ]:
data2 = A @ V[:, 0]
data2

array([ 0.30697009, -0.21062466])

In [ ]:
# This is due to numerical precision

In [ ]:
data1.dtype, data2.dtype

(dtype('float64'), dtype('float64'))

In [ ]:
#In NumPy, the correct way to compare whether two arrays are the same we must use allclose()
np.allclose(data1, data2)

True

In [ ]:
np.allclose(V @ np.diag(Lam), A @ V)

True

In [ ]:
# As a final note, if you know that your matrix is symmetric,
# You can use np.linalg.eigh
# Which is better for that scenario.
# The "H" stands for "Hermitian" (conjugate symmetric)
# Which is the Complex Analogue of the Matrix Transpose.

# It does BOTH a Transpose, and takes the Complex Conjugate of the elements.
# NumPy DOES handle Complex Numbers, if you're doing Signal Processing or Quantum Mechanics or something like that.

# In practice, you'll use Eigen Decomposition on a Symmetric Matrix like the Covariance.

In [ ]:
V

array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]])

In [ ]:
V[:, 0]

array([-0.82456484,  0.56576746])

In [ ]:
V[:]

array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]])

In [ ]:
V[0]

array([-0.82456484, -0.41597356])

# Solving Linear Systems
A very common problem in all areas of science. <br/>
x_1 + x_2 = 2200 <br/>
1.5x_1 + 4x_2 = 5050

In [ ]:
import numpy as np
x = np.array([[1, 1]]).T
x

array([[1],
       [1]])

In [ ]:
A = np.array([[1, 1], [1.5, 4]])
A

array([[1. , 1. ],
       [1.5, 4. ]])

In [ ]:
b = np.array([[2200, 5050]]).T
b

array([[2200],
       [5050]])

In [ ]:
x = np.linalg.solve(A, b) #Do this
x_otherform = np.linalg.inv(A).dot(b) #Don't do this. It's less precise

x, x_otherform

(array([[1500.],
        [ 700.]]),
 array([[1500.],
        [ 700.]]))

In [ ]:
# The inverse algorithm is slower and less precise than it could be.
# Instead use np.linalg.solve

In [ ]:
# Seems like it was possible to do without transposing
b = np.array([2200, 5050])
x = np.linalg.solve(A, b)
x

array([1500.,  700.])

In [ ]:
# You might handle Thousands of dimensions. Use solve() and not .inv().dot() for efficiency and precision.

# Generating Data
Sometimes you need to generate data. For example, Neural Network weight initialization, or creating synthetic datasets to test a model.

In [ ]:
# Use np.zeros() to create an array filled with zeros
a = np.zeros((2,3))
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# np.ones()
b = np.ones((2, 3))
b

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# Initialize with any other value
a = np.ones((2, 3)) * 10
a

array([[10., 10., 10.],
       [10., 10., 10.]])

In [ ]:
# Identity Matrix
# Matrix Analog of the number 1.

c = np.eye(3)
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# Saying eye() is common in other languages and their APIs like MatLab.

In [ ]:
# To create random numbers...
d = np.random.random()
d

0.8810564930402036

In [ ]:
np.random.random((2, 3))

array([[0.0924776 , 0.94263745, 0.15621132],
       [0.03475935, 0.82621969, 0.7154918 ]])

In [ ]:
# What distribution did those numbers come from?
# You could use a Uniform or a Normal distribution.
# Random draws from the uniform distribution.

In [ ]:
# A common technique is to visualize the data points in a HISTOGRAM.
# Now let's see the normal distribution
np.random.randn(2, 3)

array([[-0.91797977, -2.10290634,  0.15724408],
       [-2.42597467, -0.13188305, -2.6218925 ]])

In [ ]:
# This data has mean 0 and variance 1
# This function does NOT accept a tuple. Instead it receives a separate argument per dimension.

In [ ]:
R = np.random.randn(10000)
R.mean()

-0.00036178621844960477

In [ ]:
R.var() # Variance

1.0011736217730163

In [ ]:
np.mean(R)

-0.00036178621844960477

In [ ]:
R.std() # Standard Deviation

1.000586638813959

In [ ]:
R = np.random.randn(10000, 3)

In [ ]:
# We usually want to calculate the mean or sum of each column
R.mean(axis=0)

array([ 0.00529505,  0.00763796, -0.00046847])

In [ ]:
R.mean(axis=1)

array([ 0.25531414, -0.05510039,  0.27230654, ..., -0.09346405,
        0.41103997, -0.00992862])

In [ ]:
R.mean(axis=1).shape

(10000,)

In [ ]:
R.shape

(10000, 3)

In [ ]:
R.mean(axis=0).shape

(3,)

# Covariance

In [ ]:
#When you have vectors, the analog of the Variance is the Covariance
np.cov(R).shape

(10000, 10000)

In [ ]:
# The cov function, by default, treats each column as a vector observation.
# This is not the convention on the rest of the numpy stack.

In [ ]:
np.cov(R.T).shape

(3, 3)

In [ ]:
np.cov(R.T)

array([[ 0.98356133,  0.00254066,  0.00124049],
       [ 0.00254066,  0.99309368, -0.01521238],
       [ 0.00124049, -0.01521238,  1.01601972]])

In [ ]:
np.cov(R, rowvar=False) #The default is true.

array([[ 0.98356133,  0.00254066,  0.00124049],
       [ 0.00254066,  0.99309368, -0.01521238],
       [ 0.00124049, -0.01521238,  1.01601972]])

In [ ]:
np.cov(R.T, rowvar=False)

array([[ 0.4464526 , -0.48389329,  0.07211646, ...,  0.21206015,
        -0.69712204, -0.30602068],
       [-0.48389329,  0.92706968,  0.52379486, ...,  0.13490869,
         1.69863463,  0.0955145 ],
       [ 0.07211646,  0.52379486,  0.91169543, ...,  0.579631  ,
         1.29743602, -0.40255219],
       ...,
       [ 0.21206015,  0.13490869,  0.579631  , ...,  0.43119315,
         0.52328021, -0.35932699],
       [-0.69712204,  1.69863463,  1.29743602, ...,  0.52328021,
         3.29755783, -0.0753681 ],
       [-0.30602068,  0.0955145 , -0.40255219, ..., -0.35932699,
        -0.0753681 ,  0.34830317]])

In [ ]:
# As you can see, rowvar=False makes it so we compute the variance taking each row as an observation.
# From ChatGPT:
"""
rowvar=True (default):
    Each row represents a variable, and each column represents an observation.
    This means that the covariance is computed between rows.

rowvar=False:
    Each column represents a variable, and each row represents an observation.
    In this case, the covariance is computed between columns.

For example:
    - If your data is organized such that each row contains observations of a variable,
      and each column represents a different observation, leave rowvar=True.

    - If your data is organized such that each column contains observations of a variable,
      and each row represents a different observation, set rowvar=False.

"""
###

'\nrowvar=True (default): \n    Each row represents a variable, and each column represents an observation. \n    This means that the covariance is computed between rows.\n\nrowvar=False: \n    Each column represents a variable, and each row represents an observation.\n    In this case, the covariance is computed between columns.\n\nFor example:\n    - If your data is organized such that each row contains observations of a variable,\n      and each column represents a different observation, leave rowvar=True.\n    \n    - If your data is organized such that each column contains observations of a variable,\n      and each row represents a different observation, set rowvar=False.\n\n'

In [ ]:
# Now let's create random arrays with only integers.
# For that there exists np.random.randint()
# np.random.randint(low, high=None, size=None dtype="I") I think it's I? not quite clear on that

In [ ]:
np.random.randint(0, 10, size=(3, 3))

array([[5, 7, 9],
       [3, 7, 2],
       [1, 4, 8]])

In [ ]:
np.random.randint(0, 10)

9

In [ ]:
#Now let's see numpy.random.choice() to get a selection from a 1-D array
# You could see how this helps selecting from a database.

# np.random.choice(a, size=None, replace=True, p=None)
# a: 1-D array-like or int
# size: int or tuple of ints, optional. Output shape. How many samples will be drawn too.
#   For example, shape (m, n, k) will have m * n * k samples drawn.
# replace: boolean, optional.
#     For things like bootstrapping, choose if replacement is possible.
# p: 1-D array-like, optional.
#     Probabilities associated with each entry in a.
#     If not given, the sample assumes a UNIFORM DISTRIBUTION over all entries in "a"


In [ ]:
np.random.choice(10, size=(3, 3))

array([[5, 3, 1],
       [0, 9, 1],
       [7, 7, 0]])

# EXERCISE: Speed Test
Do a speed test between Matrix Multiplication and doing it by hand. So implement a matrix multiplication for lists.

Bonus: how does time increase with respect to input size? (You'll often see "with respect to" abbreviated as "wrt", by the way)

In [ ]:
import numpy as np
from datetime import datetime

def list_matmul(m1, m2):
  def multiply_and_aggregate(m1_row_idx, m2_col_idx):
    aggregate = 0
    for k in range(0, len(m1[m1_row_idx]), 1):
      aggregate += m1[m1_row_idx][k] * m2[k][m2_col_idx]
    return aggregate


  l1_rows, l1_cols = len(m1), len(m1[0])
  l2_rows, l2_cols = len(m2), len(m2[0])
  if (l1_cols != l2_rows): #I know a validation would need way more checks than this bc these are lists and not a matrix, but oh well.
    raise Exception("Inner dimensions must match")
  #result = [[None] * l2_cols] * l1_rows do NOT do this because Python creates the same object in secret. So when you modify one, both are modified.
  result = [[[None] for _ in range(0, l2_cols, 1)] for _ in range(0, l1_rows, 1)]
  for i in range(0, l2_cols, 1): #Which column we're at?
    for j in range(0, l1_rows, 1): #Which row we're at?
      aggregation = multiply_and_aggregate(j, i)
      result[j][i] = aggregation
  return result

In [ ]:
A_list = [[1, 2, 3], [4, 5, 6]]
B_list = [[7], [8], [9]]
display(list_matmul(A_list, B_list))

A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[7], [8], [9]])

A.dot(B)

[[50], [122]]

array([[ 50],
       [122]])

In [ ]:
t0 = datetime.now()
manual_result = list_matmul(A_list, B_list)
difference_1 = datetime.now() - t0

t0 = datetime.now()
npresult = A.dot(B)
difference_2 = datetime.now() - t0

display(manual_result, npresult)
difference_1.total_seconds(), difference_2.total_seconds()

[[76, 82], [184, 199], [292, 316]]

array([[ 76,  82],
       [184, 199],
       [292, 316]])

(0.00015, 0.000103)

In [ ]:
A_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
B_list = [[10, 11], [12, 13], [14, 15]]
display(list_matmul(A_list, B_list))

A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[10, 11], [12, 13], [14, 15]])

A.dot(B)

[[76, 82], [184, 199], [292, 316]]

array([[ 76,  82],
       [184, 199],
       [292, 316]])

In [ ]:
t0 = datetime.now()
manual_result = list_matmul(A_list, B_list)
difference_1 = datetime.now() - t0

t0 = datetime.now()
npresult = A.dot(B)
difference_2 = datetime.now() - t0

display(manual_result, npresult)
difference_1.total_seconds(), difference_2.total_seconds()

[[76, 82], [184, 199], [292, 316]]

array([[ 76,  82],
       [184, 199],
       [292, 316]])

(0.00016, 0.001591)

In [ ]:
# Quite the surprising results!