In [15]:
import numpy as np

CURVE_CENTER = 80

grades  = np.array([72, 35, 64, 88, 51, 90, 74, 12])
def curve(grades):
    average = grades.mean()
    change = CURVE_CENTER -average
    new_grades = grades + change
    return np.clip(new_grades, grades, 100)
print(curve(grades))

[ 91.25  54.25  83.25 100.    70.25 100.    93.25  31.25]


In [16]:
temperatures = np.array([
   29.3, 42.1, 18.8, 16.1, 38.0, 12.5,
  12.6, 49.9, 38.6, 31.3, 9.2, 22.2
 ])
print(temperatures.shape)

temperatures = temperatures.reshape(2,2,3)
print(temperatures.shape)
print(temperatures)

print(np.swapaxes(temperatures,1,2))

(12,)
(2, 2, 3)
[[[29.3 42.1 18.8]
  [16.1 38.  12.5]]

 [[12.6 49.9 38.6]
  [31.3  9.2 22.2]]]
[[[29.3 16.1]
  [42.1 38. ]
  [18.8 12.5]]

 [[12.6 31.3]
  [49.9  9.2]
  [38.6 22.2]]]


In [17]:
table = np.array([
    [5, 3, 7, 1],
    [2, 6, 7 ,9],
    [1, 1, 1, 1],
    [4, 3, 2, 0],
])

print(table.max())
print(table.max(axis=0))
print(table.max(axis=1))
# I don't understand the concept of axis in numpy as of now


9
[5 6 7 9]
[7 9 1 4]


In [18]:
A = np.arrange(32).reshape(4,1,8)
print(A)

B = np.arrange(48).reshape(1,6,8)


AttributeError: module 'numpy' has no attribute 'arrange'

In [ ]:
# indexing

square = np.array([
    [16, 3, 2, 13],
    [5, 10, 11, 8],
    [9, 6, 7, 12],
    [4, 15, 14, 1]
 ])

for i in range(4):
    assert square[:, i].sum() == 34
    assert square[i, :].sum() == 34

assert square[:2, :2].sum() == 34
assert square[2:, :2].sum() == 34

assert square[:2, 2:].sum() == 34

assert square[2:, 2:].sum() == 34

    

In [ ]:
# masking and filtering

numbers = np.linspace(5,50,24,dtype=int).reshape(4, -1)

print(numbers)

mask = numbers % 4 == 0

print(mask)

print(numbers[mask])

by_four = numbers[numbers%4 == 0]
print(by_four)

[[ 5  6  8 10 12 14]
 [16 18 20 22 24 26]
 [28 30 32 34 36 38]
 [40 42 44 46 48 50]]
[[False False  True False  True False]
 [ True False  True False  True False]
 [ True False  True False  True False]
 [ True False  True False  True False]]
[ 8 12 16 20 24 28 32 36 40 44 48]
[ 8 12 16 20 24 28 32 36 40 44 48]


In [ ]:
from numpy.random import default_rng

rng = default_rng()

values = rng.standard_normal(10000)
values[:5]

std = values.std()

print(std)

filtered = values[(values > -2 * std) & (values < 2 * std)]
print(filtered.size)

print(values.size)

filtered.size / values.size

In [ ]:
# transposing an array
a = np.array([[1, 2],[3, 4],[5, 6],])
print(a.T) # or a.transpose()
 

In [ ]:
# sorting
data = np.array([[7, 1, 4],[8, 6, 5],[1, 2, 3]])

print(np.sort(data))

print(np.sort(data, axis=None))

print(np.sort(data, axis=0))

In [ ]:
# concatenate
a = np.array([[4, 8],[6, 1]])
b = np.array([[3, 5],[7, 2]])

hp = np.hstack((a,b))
print(hp)

hp = np.vstack((b,a))

print(np.concatenate((a, b)))

print(np.concatenate((a, b), axis=None))

[[4 8 3 5]
 [6 1 7 2]]
[[4 8]
 [6 1]
 [3 5]
 [7 2]]
[4 8 6 1 3 5 7 2]


In [ ]:
# Practical Example
# Maclaurin Series


from math import e, factorial
import numpy as np

fac = np.vectorize(factorial)

def e_x(x, terms=10):
    """Approximates e^x using a given number of terms of the Maclaurin series"""

    n = np.arange(terms)
    return np.sum((x ** n)/ fac(n))

if __name__ == "__main__":
    print("Actual", e **3)
    print("N (terms)\tMaclaurin\tError")

    for n in range(1, 14):
        maclaurin = e_x(3, terms=n)
        print(f"{n}\t\t{maclaurin:.03f}\t\t{e**3 - maclaurin:.03f}")

Actual 20.085536923187664
N (terms)	Maclaurin	Error
1		1.000		19.086
2		4.000		16.086
3		8.500		11.586
4		13.000		7.086
5		16.375		3.711
6		18.400		1.686
7		19.412		0.673
8		19.846		0.239
9		20.009		0.076
10		20.063		0.022
11		20.080		0.006
12		20.084		0.001
13		20.085		0.000


In [ ]:
# storage
a = np.array([1, 3, 5.5, 7.7, 9.2], dtype=np.single)
print(a)


[1.  3.  5.5 7.7 9.2]


In [ ]:
# structured array

data = np.array([
    ("joe", 32, 6),
    ("mary", 15, 20),
    ("felipe", 80, 100),
    ("choice", 38, 9001),
], dtype= [("name", str, 10), ("age", int), ("power", int)])

print(data[0])

print(data["name"])

print(data[data["power"] > 9000]["name"])

print(np.sort(data[data["age"] > 20], order="power")["name"])

('joe', 32, 6)
['joe' 'mary' 'felipe' 'choice']
['choice']
['joe' 'felipe' 'choice']


In [ ]:
import matplotlib.image as mpimg

img = mpimg.imread("kitty.jpg")
print(type(img))
print(img.shape) # image of height 1299 width 1920, color scale 3(RGB)

## changing color

# output = img.copy()
# output[:, :, :2] = 0
# mpimg.imsave("blue.jpg", output) # blue color

# gray color
# averages = img.mean(axis=2)
# mpimg.imsave("bad-gray.jpg", averages, cmap="gray")

# better gray
weights = np.array([0.3, 0.59, 0.11])
grayscale = img @ weights
mpimg.imsave("good-gray.jpg", grayscale, cmap="gray")

<class 'numpy.ndarray'>
(1299, 1920, 3)
