In [1]:
import pandas as pd
import numpy as np

In [4]:
a = np.array([2,1,4,3,5])
np.argsort(a)[::-1]

array([4, 2, 3, 0, 1], dtype=int64)

In [2]:
a = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [3]:
a

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [4]:
np.sum(a, axis=(1, 2))

array([21, 57])

In [4]:
a = np.array([1, 2])
b = np.array([1, 2])
(a==b).all()

True

In [5]:
a = 0
(a==0).all()

AttributeError: 'bool' object has no attribute 'all'

In [3]:
np.random.randn(8, 3, 3)

array([[[ 1.48459242,  2.09489369, -0.99460213],
        [-0.40176713, -0.71332846,  0.39779828],
        [-0.26474698, -0.92628683,  2.27855238]],

       [[ 1.12684377,  0.58931845, -0.48690251],
        [ 1.42743482,  2.74076073,  0.634394  ],
        [-0.73874086,  0.20314903, -2.38297459]],

       [[-0.24666204, -1.9611269 ,  0.43909627],
        [-0.19979776, -0.55792967,  1.63070721],
        [-1.68037061, -0.29649051, -0.43486662]],

       [[-0.44153741, -0.98908892,  0.42463343],
        [ 0.59428596,  1.10144648,  1.02151715],
        [-0.48486152, -0.3441854 ,  0.6966443 ]],

       [[ 0.12491987,  1.2965434 , -0.27044197],
        [-0.60148744, -1.16016611,  0.75708208],
        [ 0.48069606,  0.96872913,  0.69952   ]],

       [[ 0.76715833, -0.72727853, -1.13212312],
        [-0.15404362, -0.01572187, -1.2851021 ],
        [-0.91080485,  0.65961002,  0.44856067]],

       [[ 1.00455016,  1.85006535, -1.42151377],
        [ 0.70037019, -0.91811455, -1.21428081],
        

In [5]:
a = np.array([1, 2, 3])
b = np.array([1, 5, 3])
((a == 1) and (b == 1)).sum()

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [13]:
np.where(a == 2)[0][0]

1

In [23]:
a = np.array([2, 1, 3])

In [24]:
a[::-1].sort()

In [25]:
a

array([3, 2, 1])