#### Numpy arrays

##### What is Numpy?


NumPy is a Python library used for working with arrays, linear algebra, fourier transform, and matrices.A numpy array is similar to a list. NumPy stands for Numerical Python and it is an open source project.The array object in NumPy is called **ndarray**, it provides a lot of supporting functions that make working with ndarray very easy.

Arrays are very frequently used in data science, where speed and resources are very important.

NumPy is usually imported under the np alias.

It's usually fixed in size and each element is of the same type. We can cast a list to a numpy array by first importing `numpy`:

In [25]:
import numpy as np
import pandas as pd

In [26]:
df=pd.DataFrame({'a':[1,2,1],'b':[1,1,1]})
df['a']==1

0     True
1    False
2     True
Name: a, dtype: bool

In [2]:
np.dot(np.array([1,-1]),np.array([1,1]))

0

In [3]:
# Create a python list

a = ["0", 1, "two", "3", 4]

In [4]:
print(np.__version__)

1.23.0


In [6]:
type(a)

list

In [7]:
# a to array
a = np.array(["0", 1, "two", "3", 4])

In [8]:
type(a)

numpy.ndarray

In [9]:
a.dtype

dtype('<U11')

In [11]:
b = np.array([3.1, 11.02, 6.2, 213.2, 5.2])
type(b)
b.dtype

dtype('float64')

In [12]:
# Create numpy array

c = np.array([20, 1, 2, 3, 4])
c

array([20,  1,  2,  3,  4])

In [13]:
# Assign the first element to 100

c[0] = 100
c

array([100,   1,   2,   3,   4])

In [14]:
# Assign the 5th element to 0

c[4] = 0
c

array([100,   1,   2,   3,   0])

In [15]:
z = np.array([10, 2, 30, 40,50])

# Enter your code here
z[1]=20

In [16]:
z

array([10, 20, 30, 40, 50])

In [18]:
z.size

5

In [19]:
z.ndim

1

In [21]:
z.max()

50

In [22]:
z.min()

10

In [23]:
z.mean()

30.0

In [24]:
A = np.array([[1,2],[3,4],[5,6],[7,8]])

B = np.array([[1,2,3],[4,5,6],[7,8,9]])

np.dot(A,B)

ValueError: shapes (4,2) and (3,3) not aligned: 2 (dim 1) != 3 (dim 0)

In [27]:
 3+2*2

7

In [28]:
int(3.2)

3

In [29]:
A='1234567'
A[1::2]

'246'

In [30]:
 Name="Michael Jackson"
 Name.find('el')

5

In [32]:
A='1'
B='2'
A+B

'12'

In [33]:
 tuple1=("A","B","C" )
 tuple1[-1]

'C'

In [35]:
A=((11,12),[21,22])
A[0][1]

12

In [37]:
'1,2,3,4'.split(',')

['1', '2', '3', '4']

In [41]:
V={'A','B','C'}
V.add('C')

In [42]:
print(V)

{'A', 'C', 'B'}


In [48]:
class Points(object):

    def __init__(self,x,y):

        self.x=x

        self.y=y

def print_point(self):

    print('x=',self.x,' y=',self.y)

    p1=Points(1,2)

    p1.print_point()

In [50]:
p1.print_point()

AttributeError: 'Points' object has no attribute 'print_point'

In [51]:
a=np.array([0,1,0,1,0])

b=np.array([1,0,1,0,1])

a*b

array([0, 0, 0, 0, 0])

In [52]:
a=np.array([0,1])

b=np.array([1,0])

np.dot(a,b)

0

In [53]:
a=np.array([1,1,1,1,1])

a+10

array([11, 11, 11, 11, 11])