<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

## 1 Lists, Arrays & Dictionaries

### 1.1 Let’s compare

In [1]:
import numpy as np

In [5]:
# Python Lists
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

In [6]:
# Numpy Arrays
np_super_names = np.array(["Black Widow", "Iron Man", "Doctor Strange"])
np_real_names = np.array(["Natasha Romanoff", "Tony Stark", "Stephen Strange"])

In [7]:
# Dictionaries
superhero_info = {"Natasha Romanoff": "Black Widow",
                  "Tony Stark": "Iron Man",
                  "Stephen Strange": "Doctor Strange"}

Dictionaries use a key and associated value separated by a `:`
Others:
1. choose any name for variables: py and np are just suggestions
2. "arrays" = "NumPy arrays"
3. "lists" = "Python lists"

### 1.2 Accessing data from a list (or array)

In [8]:
# Python is zero-indexed language, and starts counting at 0
# accessing particular element = specify relevant index

py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

In [11]:
# Example 1
print(py_real_names[0])

Natasha Romanoff


In [12]:
# Example 2
print(py_super_names[0])

Black Widow


In [13]:
# Example 3
# negative index: count from back of list
# for eg: index -1 give last element
print(py_super_names[2])    # Forward indexing 
                            # We need to know the size 
                            # beforehand for this to work.

Doctor Strange


In [14]:
print(py_super_names[-1])   # Reverse indexing

Doctor Strange


### 1.3 Accessing data from a dictionary

In [15]:
superhero_info = {"Natasha Romanoff": "Black Widow",
                  "Tony Stark": "Iron Man",
                  "Stephen Strange": "Doctor Strange"
                  }

In [16]:
print(superhero_info["Natasha Romanoff"])

Black Widow


In [17]:
superhero_info.keys()

dict_keys(['Natasha Romanoff', 'Tony Stark', 'Stephen Strange'])

In [18]:
superhero_info.values()

dict_values(['Black Widow', 'Iron Man', 'Doctor Strange'])

### 1.4 Higher dimensional lists

In [19]:
py_superhero_info = [['Natasha Romanoff', 'Black Widow'],
                     ['Tony Stark', 'Iron Man'],
                     ['Stephen Strange', 'Doctor Strange']]

## 2 Lists vs. Arrays

### 2.1 Size

In [20]:

# Your code here
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)      # Reusing the Python list 
                                        # to create a NEW
                                        # NumPy array

In [21]:
# 2D Lists
len(py_list_2d)

10

In [22]:
# 2D Arrays
len(np_array_2d)

10

In [23]:
# 2D Arrays
np_array_2d.shape

(10, 2)

There is an absence of brackets () in `shape` above as `shape` is not a function
it is property or attribute of NumPy array

### 2.2 Arrays are fussy about type

In [32]:
# Your code here
# lists vs arrays: arrays prefers a single data type
# lists are more accommodating
py_list = [1, 1.5, 'A']
np.array(py_list)

# change type (typecast) using astypes()
# NumPy arrays tolerate only a single type

array(['1', '1.5', 'A'], dtype='<U32')

### 2.3 Adding a number

In [25]:
# Setup
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         # Reusing the Python list
                                     # to create a NEW
                                     # NumPy array

In [26]:
# Lists
py_list + 10        # Won't work!

TypeError: can only concatenate list (not "int") to list

In [27]:
# Arrays
np_array + 10

array([11, 12, 13, 14, 15])

### 2.4 Adding another list

In [29]:
# Setup
py_list_1 = [1, 2, 3, 4, 5]
py_list_2 = [10, 20, 30, 40, 50]

np_array_1 = np.array(py_list_1)
np_array_2 = np.array(py_list_2)

In [30]:
# Lists
py_list_1 + py_list_2

[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]

In [31]:
# Arrays
np_array_1 + np_array_2

array([11, 22, 33, 44, 55])

### 2.5 Multiplying by a Number

In [33]:
# Setup
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

In [34]:
# Lists
py_list*2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [41]:
# Arrays
np_array*2

# multiplying by a number makes a list grow
# array multiplies elements by number

array([ 2,  4,  6,  8, 10])

### 2.6 Squaring

In [37]:
# Setup
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

In [38]:
# Lists
py_list**2                      # Won't work!  

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [39]:
# Arrays
np_array**2

array([ 1,  4,  9, 16, 25])

### 2.7 Asking questions

In [42]:
# Setup
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

In [43]:
# Lists
py_list == 3     # Works, but what IS the question?

False

In [44]:
py_list > 3      # Won't work!

TypeError: '>' not supported between instances of 'list' and 'int'

In [45]:
# Arrays
np_array == 3  

array([False, False,  True, False, False])

In [46]:
np_array > 3  

array([False, False, False,  True,  True])

### 2.8 Mathematics

In [47]:
# Setup
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

In [48]:
# Lists
sum(py_list)     # sum() is a base Python function

15

In [49]:
max(py_list)     # max() is a base Python function

5

In [50]:
min(py_list)     # min() is a base Python function

1

In [51]:
py_list.sum()   # Won't work!

AttributeError: 'list' object has no attribute 'sum'

In [52]:
# Arrays
np_array.sum()

15

In [53]:
np_array.mean()

3.0

In [54]:
np_array.max()

5

In [55]:
np_array.min()

1

## Exercise 1 :  Total recall?

1. Two similarities between lists and arrays
- `len()` function could be used to check the number of elements in the lists and arrays.
- when accessing or retrieving data in lists and arrays, the index corresponding to the data's position needs to be used.

2. Two differences between lists and arrays
- *multiplying numbers to lists will create a longer lists while multiplying numbers to arrays will multiply the number to each of the value inside the array.*
- *adding lists together will result in a longer list while adding arrays together will add the corresponding values together.*

3. What is a dictionary?
- *A dictionary consists of a collection of key-value pairs where each key-value pair maps the key to the associated value.*


## Exercise 2 :  Index me

In [1]:
# Your solution here
py_list = ["a1", "b2", "c3", "d4", "e5", "f6", "g7", "h8", "i9", "j10"]
print(py_list[0])   # Prints 'a1'
print(py_list[2])   # Prints 'c3'
print(py_list[4])   # Prints 'e5'
print(py_list[6])   # Prints 'g7'
print(py_list[8])   # Prints 'i9'


a1
c3
e5
g7
i9


## Exercise 3 :  Capitalise Heros

In [2]:
# Your solution here
superhero_info = {"Natasha Romanoff": "Black Widow",
                  "Tony Stark": "Iron Man",
                  "Stephen Strange": "Doctor Strange"
                  }

superhero_info['Tony Stark'] = superhero_info['Tony Stark'].upper()                  
superhero_info['Natasha Romanoff'] = superhero_info['Natasha Romanoff'].upper()
superhero_info['Stephen Strange'] = superhero_info['Stephen Strange'].upper()
print(superhero_info)

{'Natasha Romanoff': 'BLACK WIDOW', 'Tony Stark': 'IRON MAN', 'Stephen Strange': 'DOCTOR STRANGE'}


In [2]:
superhero_info = {"Natasha Romanoff": "Black Widow",
                  "Tony Stark": "Iron Man",
                  "Stephen Strange": "Doctor Strange"
                  }

for x in superhero_info:       # x is just a suggestion, can use other alternatives to define
    superhero_info[x] = superhero_info[x].upper()    
print(superhero_info)

{'Natasha Romanoff': 'BLACK WIDOW', 'Tony Stark': 'IRON MAN', 'Stephen Strange': 'DOCTOR STRANGE'}


## Exercise 4 :  How many ones

In [3]:
# Your solution here

# Use a NumPy array
# Ask a question
# False is considered 0, and True is considered 1 by sum()
# determine number of 1's in the list

numbers=[45, 60, 1, 30, 96, 1, 96, 57, 16, 1,
        99, 62, 86, 43, 42, 60, 59, 1, 1, 35,
        83, 47, 34, 28, 68, 23, 22, 92, 1, 79,
        1, 29, 94, 72, 46, 47, 1, 74, 32, 20,
        8, 37, 35, 1, 89, 29, 86, 19, 43, 61]  
numbers_np_array = np.array(numbers)
sum(numbers_np_array == 1)

9