<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

# What to expect in this chapter

In [2]:
import numpy as np

# 1 Lists, Arrays & Dictionaries

## 1.1 Let’s compare

**Python Lists**

In [11]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]    # List of super names
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"] # List of real names

In [12]:
py_fruits = ["apple", "grape", "banana"]         # List of fruits
py_vegetables = ["spinach", "corn", "potato"]    # list of vegetables

**Numpy Arrays**

In [8]:
np_super_names = np.array(["Black Widow", "Iron Man", "Doctor Strange"])         # List of super names
np_real_names = np.array(["Natasha Romanoff", "Tony Stark", "Stephen Strange"])  # List of real names

In [9]:
np_fruits = np.array(["apple", "grape", "banana"])             # array of fruits
np_vegetables = np.array(["spinach", "corn", "potato"])        # array of vegetables

**Dictionary**

In [13]:
superhero_info = {
    "Natasha Romanoff": "Black Widow",            # Dictionary with superhero names as the key and real names as the associated value
    "Tony Stark": "Iron Man",
    "Stephen Strange": "Doctor Strange"
}

## 1.2 Accessing data from a list (or array)

In [22]:
py_real_names[0]     # Accessing data from the value at the 0 position

'Natasha Romanoff'

In [16]:
py_fruits[2]

'banana'

In [17]:
py_super_names[0]

'Black Widow'

In [18]:
py_super_names[2]    # Forward indexing 

'Doctor Strange'

In [19]:
py_vegetables[-2]     # reverse indexing

'corn'

In [20]:
py_super_names[-1]

'Doctor Strange'

## 1.3 Accessing data from a dictionary

In [23]:
superhero_info = {
    "Natasha Romanoff": "Black Widow",
    "Tony Stark": "Iron Man",
    "Stephen Strange": "Doctor Strange"
}                  

In [29]:
superhero_info["Natasha Romanoff"]  # retrieving the value of the key 'Natasha Romanoff'

'Black Widow'

In [25]:
superhero_info["Stephen Strange"]

'Doctor Strange'

In [27]:
superhero_info.keys()  # access all the keys

dict_keys(['Natasha Romanoff', 'Tony Stark', 'Stephen Strange'])

In [28]:
superhero_info.values() # access all the values

dict_values(['Black Widow', 'Iron Man', 'Doctor Strange'])

## 1.4 Higher dimensional lists

In [31]:
py_superhero_info = [['Natasha Romanoff', 'Black Widow'],
                     ['Tony Stark', 'Iron Man'],
                     ['Stephen Strange', 'Doctor Strange']]

# 2 Lists vs. Arrays

## 2.1 Size

In [32]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)      # Converting the np array to py list

**List**

In [36]:
py_list_2d   # create list

[[1, 'A'],
 [2, 'B'],
 [3, 'C'],
 [4, 'D'],
 [5, 'E'],
 [6, 'F'],
 [7, 'G'],
 [8, 'H'],
 [9, 'I'],
 [10, 'J']]

In [38]:
len(py_list_2d)    # To find out the size of list

10

**Array**

In [35]:
np_array_2d   # list out array  

array([['1', 'A'],
       ['2', 'B'],
       ['3', 'C'],
       ['4', 'D'],
       ['5', 'E'],
       ['6', 'F'],
       ['7', 'G'],
       ['8', 'H'],
       ['9', 'I'],
       ['10', 'J']], dtype='<U11')

In [39]:
len(np_array_2d) # To find out size of array

10

In [41]:
np_array_2d.shape  # To find out how many rows and columns in the 2D array

(10, 2)

## 2.2 Arrays are fussy about type

In [43]:
py_list = [1, 1.5, 'A']
np_array = np.array(py_list)

**List**

In [44]:
py_list

[1, 1.5, 'A']

**Arrays**

In [46]:
np_array    # array can only have a single data type

array(['1', '1.5', 'A'], dtype='<U32')

## 2.3 Adding a number

In [48]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         # creating a np array from the py list 

**List**

In [53]:
py_list + 10        # will not work for list

TypeError: can only concatenate list (not "int") to list

**Arrays**

In [52]:
np_array + 10              # adding 10 to every element in the array

array([11, 12, 13, 14, 15])

In [55]:
np_array + 100             # adding 100 to every element in the array

array([101, 102, 103, 104, 105])

## 2.4 Adding another list

In [57]:
py_list_1 = [1, 2, 3, 4, 5]
py_list_2 = [10, 20, 30, 40, 50]

np_array_1 = np.array(py_list_1)
np_array_2 = np.array(py_list_2)

**List**

In [60]:
py_list_1 + py_list_2     # adding lists combines the lists

[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]

**Arrays**

In [59]:
np_array_1 + np_array_2    # adding arrays will allow the elements to add up

array([11, 22, 33, 44, 55])

## 2.5 Multiplying by a Number

In [61]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

**Lists**

In [64]:
py_list*2  # multiplying a list by a number will make the list grow

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

**Arrays**

In [63]:
np_array*2  # multiplying an array by a number will multiply its elements by the number

array([ 2,  4,  6,  8, 10])

## 2.6 Squaring

In [65]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

**Lists**

In [66]:
py_list**2                      # List cannot be square rooted as it is not supported

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

**Arrays**

In [68]:
np_array**2                   # elements in the array can be square rooted 

array([ 1,  4,  9, 16, 25])

## 2.7 Asking questions

In [69]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

**Lists**

Example 1

In [70]:
py_list == 3     # List will not tell you whether an element is present in the list

False

Example 2

In [71]:
py_list > 3     

TypeError: '>' not supported between instances of 'list' and 'int'

**Arrays**

Example 1

In [72]:
np_array == 3    # Tells you if each element in the array is the element that you have specified 

array([False, False,  True, False, False])

Example 2

In [73]:
np_array > 3 

array([False, False, False,  True,  True])

In [75]:
sum(np_array > 3)   # Adds up the values present in the array: False = 0, True = 1

2

## 2.8 Mathematics

In [76]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

**Example 1**

**List**

In [90]:
sum(py_list)     # sum() is a base Python function` # adding up the element in the list

15

**Arrays**

In [91]:
np_array.sum()  # adding up the elements in the array

15

**Example 2**

**List**

In [92]:
max(py_list)     # max() is a base Python function  #finding the maximum element in the list

5

**Arrays**

In [93]:
np_array.max()    #finding the maximum element in the array

5

**Example 3**

**Lists**

In [94]:
min(py_list)     # min() is a base Python function # finding the minimum element in the list

1

**Arrays**

In [95]:
np_array.min()  # finding the minimum element in the array

1

**Example 4**


**Lists**

In [86]:
py_list.sum()   # .sum() will not work as it is not a built-in function for python lists

AttributeError: 'list' object has no attribute 'sum'

In [96]:
sum(py_list)

15

**Arrays**

In [87]:
np_array.mean()   # finding the mean in the array

3.0

**Example 5**

**Arrays**

In [97]:
np_array.std()   # finding standard deviation in the array

1.4142135623730951

# Exercises & Self-Assessment

In [ ]:



# Your solution here




## Footnotes