<a href="https://colab.research.google.com/github/ahmedtabsho/PytorchTutorial/blob/main/LearnPytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Tensors
* A torch. Tensor is multi-dimensional matrix contianing elements of a single data type.
* Similar to Numpy Arrays, but full of fun things that make them work better on GPU's (vs regular CPU)
* default data type of float32.
* More suitable for deep learning than a numpy array.

In [ ]:
import torch
import numpy as np

#Numpy ARRAYS

In [ ]:
np1 = np.random.rand(3,4)
np1

array([[0.99454812, 0.42007796, 0.16802658, 0.17690531],
       [0.61320486, 0.77123504, 0.70468011, 0.39391321],
       [0.35748469, 0.99573695, 0.62571858, 0.19021678]])

In [ ]:
np1.dtype

dtype('float64')

#TENSORS

In [ ]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[ 0.9387, -2.5283,  0.3542, -0.5822],
        [-0.9331,  1.4947, -2.7205, -0.8517],
        [-1.9059, -1.3564,  0.3054,  1.1344]])

In [ ]:
tensor_2d.dtype

torch.float32

In [ ]:
tensor_3d = torch.zeros(3,4,5)
tensor_3d

tensor([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]])

In [ ]:
torch.tensor(np1)

tensor([[0.9945, 0.4201, 0.1680, 0.1769],
        [0.6132, 0.7712, 0.7047, 0.3939],
        [0.3575, 0.9957, 0.6257, 0.1902]], dtype=torch.float64)

#Tesor_ops

In [ ]:
my_torch = torch.arange(10)

In [ ]:
# Reshape and View
my_torch = my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
# Reshape if we don't know the number of items using -1
my_torch2 = torch.arange(10)
my_torch2

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
my_torch2 = my_torch2.reshape(2, -1)
my_torch2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
my_torch2 = my_torch2.reshape(-1, 5)
my_torch2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
my_torch2 = my_torch2.view(-1, 5)
my_torch2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
# reshape and view almost the same

In [ ]:
# with reshape and view, they will update
my_torch5 = torch.arange(10)
my_torch5

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
my_torch6 = my_torch5.reshape(2,5)
my_torch6

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
my_torch5[1] = 342
my_torch5

tensor([  0, 342,   2,   3,   4,   5,   6,   7,   8,   9])

In [ ]:
my_torch6

tensor([[  0, 342,   2,   3,   4],
        [  5,   6,   7,   8,   9]])

In [ ]:
# Slices
my_torch7 = torch.arange(10)
my_torch7

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
my_torch7[7]

tensor(7)

In [ ]:
# Grab Slice
my_torch8 = my_torch7.reshape(5,2)
my_torch8

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [ ]:
my_torch8[:,1]

tensor([1, 3, 5, 7, 9])

In [ ]:
my_torch8[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])

#Tensor Math Operations
* Add, Subtract, Multiply, Divide, Remainders, Exponents
* Shorthand and uh, Longhand
* Reassignment

In [ ]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [ ]:
#Addition
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [ ]:
# Addition Longhand
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [ ]:
# Subtraction
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [ ]:
# Sub Funcion
torch.sub(tensor_a, tensor_b)

tensor([-4, -4, -4, -4])

In [ ]:
# Multiplication
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [ ]:
# Division
tensor_b / tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [ ]:
# Remainder Modules
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [ ]:
# Remainder Longhand
torch.remainder(tensor_b, tensor_a)

tensor([0, 0, 1, 0])

In [ ]:
# Exponents / power
torch.pow(tensor_b, tensor_a)
tensor_b **  tensor_a

tensor([   5,   36,  343, 4096])

In [ ]:
tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 12])

In [ ]:
# Reassignment
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [ ]:
tensor_a += tensor_b

In [ ]:
tensor_a

tensor([ 6,  8, 10, 12])

In [ ]:
 # tensor_a = tensor_a + tensor_b
 tensor_a.add_(tensor_b)

tensor([11, 14, 17, 20])