<a href="https://colab.research.google.com/github/AkshayKohad/ML-Tutorial/blob/main/Q1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1255]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# other imports if necessary
from sklearn.model_selection import train_test_split

In [1256]:
data = pd.read_csv('Q1Data.csv')
data.head()

data = data.iloc[:,[0,1,2,3,4,5,22]]

data['Genus'] = pd.factorize(data['Genus'])[0]
data['Genus']
unique_counts = data["Genus"].value_counts()
print(unique_counts)
data.head()

0    4150
3    1593
1     542
2     310
4     270
7     148
5     114
6      68
Name: Genus, dtype: int64


MFCCs_ 1  MFCCs_ 2  MFCCs_ 3  MFCCs_ 4  MFCCs_ 5  MFCCs_ 6  Genus
0  0.152936 -0.105586  0.200722  0.317201  0.260764  0.100945      0
1  0.171534 -0.098975  0.268425  0.338672  0.268353  0.060835      0
2  0.152317 -0.082973  0.287128  0.276014  0.189867  0.008714      0
3  0.224392  0.118985  0.329432  0.372088  0.361005  0.015501      0
4  0.087817 -0.068345  0.306967  0.330923  0.249144  0.006884      0

In [1257]:
val = list(data.iloc[:,6])

num_val = data.values

print(num_val.shape)

(7195, 7)


In [1258]:
unique_values = list(set(val))
unique_values

[0, 1, 2, 3, 4, 5, 6, 7]

In [1259]:
predictor = data.iloc[:,[0,1,2,3,4,5]]
response = data.iloc[:,[6]]

print(predictor)
print(response)
predictor_Training,predictor_test,response_Training,response_test = train_test_split(predictor,response,test_size=0.8,shuffle=True,random_state=0)

      MFCCs_ 1  MFCCs_ 2  MFCCs_ 3  MFCCs_ 4  MFCCs_ 5  MFCCs_ 6
0     0.152936 -0.105586  0.200722  0.317201  0.260764  0.100945
1     0.171534 -0.098975  0.268425  0.338672  0.268353  0.060835
2     0.152317 -0.082973  0.287128  0.276014  0.189867  0.008714
3     0.224392  0.118985  0.329432  0.372088  0.361005  0.015501
4     0.087817 -0.068345  0.306967  0.330923  0.249144  0.006884
...        ...       ...       ...       ...       ...       ...
7190 -0.554504 -0.337717  0.035533  0.034511  0.443451  0.093889
7191 -0.517273 -0.370574  0.030673  0.068097  0.402890  0.096628
7192 -0.582557 -0.343237  0.029468  0.064179  0.385596  0.114905
7193 -0.519497 -0.307553 -0.004921  0.072865  0.377131  0.086866
7194 -0.508833 -0.324106  0.062068  0.078211  0.397188  0.094596

[7195 rows x 6 columns]
      Genus
0         0
1         0
2         0
3         0
4         0
...     ...
7190      7
7191      7
7192      7
7193      7
7194      7

[7195 rows x 1 columns]


In [1260]:
# Training_data = predictor_Training + response_Training
Training_data = pd.concat([predictor_Training, response_Training], axis=1, ignore_index=True)
Training_data = Training_data.values
Training_data

array([[ 0.27467064, -0.00588234,  0.3798425 , ...,  0.3008921 ,
         0.04171176,  0.        ],
       [ 0.48183722,  0.42900511,  0.2016512 , ...,  0.15801238,
         0.05756245,  3.        ],
       [ 0.55778453,  0.39555308,  0.20568461, ...,  0.18644029,
         0.09954799,  3.        ],
       ...,
       [ 1.        ,  0.30349834,  0.32046497, ...,  0.33499858,
         0.09162156,  0.        ],
       [ 0.37867804,  0.43087997,  0.61824348, ..., -0.00888817,
        -0.10676814,  0.        ],
       [ 0.23485212,  0.52137576,  0.60482508, ..., -0.01903177,
        -0.10584264,  0.        ]])

In [1261]:
response_test = response_test.values

In [1262]:
predictor_test = predictor_test.values
predictor_test


array([[ 0.02135551,  0.71202305,  0.54095894,  0.0065615 , -0.01239631,
        -0.03990581],
       [ 0.23577558,  0.17933623,  0.50782454,  0.27300755,  0.07964708,
        -0.06737581],
       [ 0.42711874,  0.22012468,  0.56297878,  0.24425565,  0.07636767,
        -0.07160264],
       ...,
       [ 0.60592561,  0.43083445,  0.21832192,  0.02337051,  0.14857513,
         0.03840976],
       [ 0.26671083,  0.73573358,  0.23377212, -0.07586708,  0.14019334,
         0.08021178],
       [ 0.16180043,  0.32645826,  0.31136768,  0.17152383,  0.21179285,
         0.08369208]])

In [1263]:
# Calculating entropy
def entropy(var):
  N = var.shape[0]
  values,counts = np.unique(var,return_counts = True)

  ent = 0.0

  for i in counts:
    p = i/N
    ent += (p*np.log2(p))

  return -ent


In [1264]:
def divide_data(data,feature,threshold):
  DATA = {0:{'data': [],'len':0},1:{'data': [],'len':0}}

  # feat_values = list(data[feature].value_counts().index)
  # occurence = list(data[feature].value_counts())


  print(data.shape)

  for ix in range(len(data)):
    result = data[ix][feature]

    val = 1

    if result<=threshold:
      val = 0


    DATA[val]['data'].append(data[ix])


    DATA[val]['len'] += 1

  DATA[0]['data'] = np.array(DATA[0]['data'])
  DATA[1]['data'] = np.array(DATA[1]['data'])

  return DATA


In [1265]:
# import numpy as np

# def divide_data(data, feature, threshold):
#     """
#     Divide the dataset into two based on the specified feature and threshold.

#     Parameters:
#     - data: 2D NumPy array representing the dataset.
#     - feature: Index of the feature for splitting.
#     - threshold: Threshold value for the split.

#     Returns:
#     - A dictionary containing two subsets of the data.
#     """
#     DATA = {0: {'data': [], 'len': 0}, 1: {'data': [], 'len': 0}}

#     for ix in range(len(data)):
#         result = data[ix][feature]

#         # Determine the subset based on the threshold
#         val = 1 if result > threshold else 0

#         # Append the data point to the corresponding subset
#         DATA[val]['data'].append(data[ix])

#         # Update the length of the subset
#         DATA[val]['len'] += 1

#     # Convert lists to NumPy arrays for efficient operations
#     DATA[0]['data'] = np.array(DATA[0]['data'])
#     DATA[1]['data'] = np.array(DATA[1]['data'])

#     return DATA


In [1266]:
divide_data(Training_data,0,0.5)

(1439, 7)


{0: {'data': array([[ 2.74670640e-01, -5.88233900e-03,  3.79842500e-01, ...,
           3.00892099e-01,  4.17117650e-02,  0.00000000e+00],
         [ 4.81837216e-01,  4.29005111e-01,  2.01651203e-01, ...,
           1.58012375e-01,  5.75624510e-02,  3.00000000e+00],
         [ 2.74216704e-01,  3.45092271e-01,  6.28744324e-01, ...,
           4.82781000e-04, -3.67944620e-02,  0.00000000e+00],
         ...,
         [ 1.76690884e-01,  1.05816820e-02,  4.26816212e-01, ...,
           8.22863230e-02, -8.11103330e-02,  0.00000000e+00],
         [ 3.78678041e-01,  4.30879968e-01,  6.18243476e-01, ...,
          -8.88817400e-03, -1.06768144e-01,  0.00000000e+00],
         [ 2.34852121e-01,  5.21375759e-01,  6.04825084e-01, ...,
          -1.90317700e-02, -1.05842644e-01,  0.00000000e+00]]),
  'len': 1141},
 1: {'data': array([[ 0.55778453,  0.39555308,  0.20568461, ...,  0.18644029,
           0.09954799,  3.        ],
         [ 0.53958268,  0.61259108,  0.47803658, ..., -0.02957588,
       

In [1267]:
res = divide_data(Training_data,1,0.5)
print(res[1])

(1439, 7)
{'data': array([[ 0.53958268,  0.61259108,  0.47803658, ..., -0.02957588,
         0.35417908,  0.        ],
       [ 0.67192828,  0.70018668,  0.62989277, ..., -0.05483586,
         0.4711212 ,  0.        ],
       [ 0.50984789,  0.61843351,  0.19950866, ...,  0.15289267,
         0.02503255,  3.        ],
       ...,
       [ 0.91123997,  0.52418541,  0.74605851, ..., -0.01981714,
        -0.02024164,  0.        ],
       [ 0.10907303,  0.5991774 ,  0.41163607, ...,  0.25106522,
         0.3207631 ,  4.        ],
       [ 0.23485212,  0.52137576,  0.60482508, ..., -0.01903177,
        -0.10584264,  0.        ]]), 'len': 281}


In [1268]:
# Information Gain

def information_gain(data,feature):
  examples = data.shape[0]
  DATA = divide_data(data,feature)

  keys = DATA.keys()

  ent_of_children = 0.0

  for key in keys:
    ent_of_children += ((DATA[key]['len']/examples)*entropy(DATA[key]['data']['Play Golf']))

  info_gain = entropy(data['Play Golf']) - ent_of_children
  return info_gain

In [1270]:
def gini_index_calculate(data, feature):
    res_data = []

    for i in range(len(data)):
        res_data.append([data[i][feature], data[i][6]])

    res_gini_index = float('inf')
    threshold = 0

    # Sort res_data based on feature values
    res_data.sort(key=lambda x: x[0])
    record = set()
    for i in range(len(res_data) - 1):
        if res_data[i][0] in record:
          continue

        record.add(res_data[i][0])

        less_equal_threshold = {j: 0 for j in range(8)}
        greater_threshold = {j: 0 for j in range(8)}

        less_equal_threshold['len'] = 0
        greater_threshold['len'] = 0

        for j in range(len(res_data)):
            if res_data[j][0] <= res_data[i][0]:
                less_equal_threshold[int(res_data[j][1])] += 1
                less_equal_threshold['len'] += 1

            else:
                greater_threshold[int(res_data[j][1])] += 1
                greater_threshold['len']+=1

        ans1 = 1 - sum((greater_threshold[j] / max(greater_threshold['len'], 1))**2 for j in range(8))
        ans2 = 1 - sum((less_equal_threshold[j] / max(less_equal_threshold['len'], 1))**2 for j in range(8))

        total_len = greater_threshold['len'] + less_equal_threshold['len']

        if total_len == 0:
            continue

        greater_len = greater_threshold['len']
        less_equal_len = less_equal_threshold['len']
        ans = (greater_len / total_len) * ans1 + (less_equal_len / total_len) * ans2

        if ans <= res_gini_index:
            res_gini_index = ans
            threshold = res_data[i][0]

    return res_gini_index, threshold


In [1271]:
res_gini,threshold = gini_index_calculate(Training_data,1)

In [1272]:
res = divide_data(Training_data,1,threshold)
print(res[1]['len'],res[0]['len'])

(1439, 7)
676 763


In [1273]:
#DECISION TREE

In [1274]:
class DecisionTree:

  #constructor
  def __init__(self,depth=0,max_depth=5):
    # Creating Node
    self.children = {}
    self.fkey = None
    self.max_depth = max_depth
    self.depth = depth
    self.target = None
    self.threshold = None

  def train(self,data):
    features = [0,1,2,3,4,5]

    res_gini_index = 2
    res_threshold = -1
    res_feature = -1
    for f in features:
      gini_index,threshold = gini_index_calculate(data,f)

      if res_gini_index >= gini_index:
        res_gini_index = gini_index
        res_threshold = threshold
        res_feature = f


    # finding the best features

    self.fkey = res_feature


    # Splitting the data
    DATA = divide_data(data,self.fkey,res_threshold)


    self.threshold = res_threshold
    # Giving a Target Label to Node

    genus_values = data[:, 6]
    print(genus_values)
    genus_values = list(genus_values)

    record_genus_cnt = {0:0,1:0,2:0,3:0,4:0,5:0,6:0,7:0}

    for j in range(len(genus_values)):
      record_genus_cnt[int(genus_values[j])] += 1

    label = -1
    label_cnt = 0
    zero_cnt = 0
    for j in range(8):
      if label_cnt <= record_genus_cnt[j]:
        label_cnt = record_genus_cnt[j]
        label = j

      if record_genus_cnt[j]==0:
        zero_cnt += 1

    self.target = label

    if zero_cnt == 8 or zero_cnt==7:
      return





    # Stopping Conditions #

    have_data = 0

    keys = DATA.keys()

    # print(keys)
    # print(threshold)
    # print(DATA[0]['len'],DATA[0]['len'])
    for key in keys:
      if DATA[key]['len'] > 0:
        have_data += 1


    # 1. If it is pure node

    if have_data < 1:
      return

    # 2. Early stop if you have reached max depth

    if self.depth >= self.max_depth:
      return


    print("\t"*self.depth + "Making Tree with - ",self.fkey)

    # Recursively train child Node


    # print(DATA[0])
    new_data = DATA[0]['data']
    # print(new_data)
    # print(DATA[key]['data'])
    self.children[0] = DecisionTree(depth = self.depth+1)
    self.children[0].train(new_data)

    new_data = DATA[1]['data']
    # print(new_data)
    # print(DATA[key]['data'])
    self.children[1] = DecisionTree(depth = self.depth+1)
    self.children[1].train(new_data)

    return

  def predict(self,test):
    if self.children == {}:
      return self.target

    if self.threshold <= test[self.fkey] :
     return self.children[0].predict(test)
    else:
      return self.children[1].predict(test)



In [1275]:
model = DecisionTree()
model.train(Training_data)

# type(Training_data)

(1439, 7)
[0. 3. 3. ... 0. 0. 0.]
Making Tree with -  2
(714, 7)
[0. 3. 3. 0. 3. 1. 3. 0. 0. 1. 1. 3. 3. 4. 1. 0. 1. 0. 5. 0. 0. 3. 1. 3.
 3. 0. 2. 0. 3. 3. 4. 1. 0. 3. 3. 0. 3. 1. 3. 1. 3. 3. 1. 0. 3. 1. 0. 3.
 3. 4. 3. 1. 3. 4. 3. 0. 0. 3. 0. 3. 3. 3. 1. 4. 7. 3. 0. 3. 0. 3. 3. 3.
 3. 4. 3. 3. 3. 0. 0. 3. 3. 3. 2. 0. 4. 3. 3. 0. 0. 3. 3. 3. 0. 3. 3. 0.
 4. 1. 1. 3. 1. 3. 4. 3. 7. 3. 3. 7. 4. 0. 0. 3. 3. 3. 4. 1. 1. 3. 3. 6.
 1. 3. 3. 3. 2. 1. 4. 0. 7. 0. 7. 3. 2. 3. 3. 1. 3. 0. 4. 1. 0. 0. 4. 3.
 3. 0. 3. 3. 3. 2. 1. 1. 3. 3. 0. 3. 2. 4. 3. 3. 3. 3. 3. 4. 0. 0. 1. 3.
 3. 4. 3. 3. 3. 1. 0. 3. 1. 7. 3. 0. 0. 3. 3. 4. 4. 3. 3. 0. 6. 1. 3. 2.
 3. 4. 0. 0. 5. 3. 2. 3. 0. 3. 2. 3. 3. 2. 4. 4. 3. 7. 1. 7. 3. 3. 3. 1.
 0. 5. 3. 1. 3. 3. 3. 1. 3. 0. 6. 3. 1. 0. 3. 4. 1. 0. 5. 0. 3. 3. 0. 0.
 3. 3. 2. 0. 0. 0. 5. 3. 0. 3. 0. 1. 0. 3. 2. 3. 0. 3. 0. 0. 0. 0. 3. 7.
 2. 2. 0. 1. 3. 3. 3. 2. 3. 3. 0. 3. 1. 3. 4. 3. 2. 3. 7. 1. 5. 0. 6. 5.
 1. 0. 1. 3. 2. 3. 1. 3. 0. 4. 0. 3. 3. 0. 3. 0. 0. 3. 3. 0

In [1276]:
# response_test =
cnt_correct = 0
cnt_incorrect = 0
for i in range(len(response_test)):
  val = model.predict(predictor_test[i])

  if val == response_test[i]:
    cnt_correct += 1

  else:
    cnt_incorrect += 1

result = cnt_correct/(cnt_incorrect + cnt_correct)

print(result)


0.07261987491313412


In [1277]:
# answer = []
# for i in range(15):
#   model = DecisionTree(0,i+1)
#   model.train(Training_data)
#   cnt_correct = 0
#   cnt_incorrect = 0
#   for i in range(len(response_test)):
#     val = model.predict(predictor_test[i])

#     if val == response_test[i]:
#       cnt_correct += 1

#     else:
#       cnt_incorrect += 1

#   result = cnt_correct/(cnt_incorrect + cnt_correct)
#   answer.append(result)
#   print(result)



In [1278]:
# answer