# Question 1

In [55]:
import numpy as np 
from termcolor import colored 

# Number of items and baskets
num_items = 100
num_baskets = 100

# Create a dictionary to hold the baskets and their items
baskets = {}

counts = {i: 0 for i in range(1, num_items + 1)}  # Initializing all counts to 0

# Go through each basket number
for b in range(1, num_baskets + 1):
    # Find and add items that divide the basket number with no remainder
    basket_items = [i for i in range(1, num_items + 1) if b % i == 0]
    
    # Add this list of items to the current basket
    baskets[b] = np.array(basket_items)

    # For each item that we just placed in a basket, increment its count
    for item in basket_items:
        counts[item] += 1  # Increment the count for this item

# Now, 'baskets' contains all the information.
# For example, to access basket 12, you would use:
print("Items in basket 12:", baskets[12])

# And if you want to see all baskets:
for basket_num, items in baskets.items():
    print(f"Basket {basket_num}: {items}")





Items in basket 12: [ 1  2  3  4  6 12]
Basket 1: [1]
Basket 2: [1 2]
Basket 3: [1 3]
Basket 4: [1 2 4]
Basket 5: [1 5]
Basket 6: [1 2 3 6]
Basket 7: [1 7]
Basket 8: [1 2 4 8]
Basket 9: [1 3 9]
Basket 10: [ 1  2  5 10]
Basket 11: [ 1 11]
Basket 12: [ 1  2  3  4  6 12]
Basket 13: [ 1 13]
Basket 14: [ 1  2  7 14]
Basket 15: [ 1  3  5 15]
Basket 16: [ 1  2  4  8 16]
Basket 17: [ 1 17]
Basket 18: [ 1  2  3  6  9 18]
Basket 19: [ 1 19]
Basket 20: [ 1  2  4  5 10 20]
Basket 21: [ 1  3  7 21]
Basket 22: [ 1  2 11 22]
Basket 23: [ 1 23]
Basket 24: [ 1  2  3  4  6  8 12 24]
Basket 25: [ 1  5 25]
Basket 26: [ 1  2 13 26]
Basket 27: [ 1  3  9 27]
Basket 28: [ 1  2  4  7 14 28]
Basket 29: [ 1 29]
Basket 30: [ 1  2  3  5  6 10 15 30]
Basket 31: [ 1 31]
Basket 32: [ 1  2  4  8 16 32]
Basket 33: [ 1  3 11 33]
Basket 34: [ 1  2 17 34]
Basket 35: [ 1  5  7 35]
Basket 36: [ 1  2  3  4  6  9 12 18 36]
Basket 37: [ 1 37]
Basket 38: [ 1  2 19 38]
Basket 39: [ 1  3 13 39]
Basket 40: [ 1  2  4  5  8 10 20 40

In [33]:
support_threshold = 15

def items_above_threshold(support_threshold):
    items_15 = []
    for item, count in counts.items():
        if count>support_threshold:
            items_15.append(item)

    return items_15

items_above_threshold(15)

[1, 2, 3, 4, 5, 6]

In [56]:
def find_pairs(baskets):
    max_value = max(max(value) for value in baskets.values())

    items_pairs = np.zeros((max_value, max_value))

    for item, basket in baskets.items():
        for i in range(len(basket)):
            for j in range(i+1, len(basket)):  
                pair = (basket[i]-1, basket[j]-1)
                items_pairs[pair[0],pair[1]] +=1

    return items_pairs
find_pairs(baskets)


array([[ 0., 50., 33., ...,  1.,  1.,  1.],
       [ 0.,  0., 16., ...,  1.,  0.,  1.],
       [ 0.,  0.,  0., ...,  0.,  1.,  0.],
       ...,
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]])

In [47]:
# List to store the positions

def pairs_above_threshold(support_threshold):
    item_pairs_no = []

    # Go through each element and check if it's greater than 15.
    for row_index, row in enumerate(find_pairs(baskets)):
        for col_index, value in enumerate(row):
            if value >= support_threshold:
                item_pairs_no.append((row_index+1, col_index+1, value))  # Save the row and column index
    return item_pairs_no

pairs = pairs_above_threshold(support_threshold)

# Print the pairs
for position in pairs:
    print(f"Row {position[0]} Col {position[1]} has a value greater than 15. It has a value of {position[2]}")

# Print the total
count = len(pairs)
print(f"Number of elements greater than 15: {count}")


Row 1 Col 2 has a value greater than 15. It has a value of 50.0
Row 1 Col 3 has a value greater than 15. It has a value of 33.0
Row 1 Col 4 has a value greater than 15. It has a value of 25.0
Row 1 Col 5 has a value greater than 15. It has a value of 20.0
Row 1 Col 6 has a value greater than 15. It has a value of 16.0
Row 2 Col 3 has a value greater than 15. It has a value of 16.0
Row 2 Col 4 has a value greater than 15. It has a value of 25.0
Row 2 Col 6 has a value greater than 15. It has a value of 16.0
Row 3 Col 6 has a value greater than 15. It has a value of 16.0
Number of elements greater than 15: 9


In [43]:
def largest_baskets(baskets):
    largest = 0
    largest_baskets = []  # This will store the IDs of the baskets with the most items

    for basketID, basket_lst in baskets.items():
        current_length = len(basket_lst)
        
        # If the current basket matches the largest size, add it to the list
        if current_length == largest:
            largest_baskets.append(basketID)
        
        # If the current basket exceeds the largest size, update the largest size
        # and reset the list
        elif current_length > largest:
            largest = current_length
            largest_baskets = [basketID] 
    return largest_baskets, largest

ans = largest_baskets(baskets)

print(f"The Largest baskets are {ans[0]} with a size of {ans[1]}")




The Largest baskets are [60, 72, 84, 90, 96] with a size of 12


In [46]:
def support(x):
    return counts[x]

def pair_support(x,y):
    return find_pairs(baskets)[x-1][y-1]

def triple_support(x,y,z):
    count = 0 
    for basketID, blist in baskets.items():
        if x in blist and y in blist and z in blist:
            count+=1
    return count


confidence57__2 = triple_support(2,5,7)/pair_support(5,7)
confidence23__5 = triple_support(2,3,4)/pair_support(2,3) 

print(f"The confidence for (5,7) --> 2 is {colored(confidence57__2,'green')}.")
print(f"The confidence for (2,3) --> 4 is {colored(confidence23__5,'green')}.")

def prob(j):
    return counts[j]/len(baskets)

interest57_2 = confidence57__2-prob(2)
interest23_4 = confidence23__5-prob(4)


print(f"The Interest for (5,7) --> 2 is {colored(interest57_2,'green')}.")
print(f"The Interest for (2,3) --> 4 is {colored(interest23_4,'green')}.")

print('No these are not interesting')




The confidence for (5,7) --> 2 is 0.5.
The confidence for (2,3) --> 4 is 0.5.
The Interest for (5,7) --> 2 is 0.0.
The Interest for (2,3) --> 4 is 0.25.
No these are not interesting


# Question 2

In [2]:
transactions = {
    1: ['Bread', 'Milk', 'Diaper', 'Beer'],
    2: ['Bread', 'Diaper', 'Beer', 'Eggs'],
    3: ['Milk', 'Diaper', 'Beer', 'Coke'],
    4: ['Bread', 'Milk', 'Diaper', 'Beer', 'Coke'],
    5: ['Bread', 'Milk', 'Diaper', 'Coke'],
    6: ['Bread', 'Diaper', 'Beer']
}

In [5]:
from itertools import combinations

# Given data
transactions = {
    1: ['Bread', 'Milk', 'Diaper', 'Beer'],
    2: ['Bread', 'Diaper', 'Beer', 'Eggs'],
    3: ['Milk', 'Diaper', 'Beer', 'Coke'],
    4: ['Bread', 'Milk', 'Diaper', 'Beer', 'Coke'],
    5: ['Bread', 'Milk', 'Diaper', 'Coke'],
    6: ['Bread', 'Diaper', 'Beer']
}

# Total number of transactions
total_transactions = len(transactions)

# Minimum support threshold
min_support_threshold = total_transactions * 0.5  # 50%

# Utility function to calculate itemsets with size 'size' that meet the minimum support threshold
def find_frequent_itemsets(itemset_candidates, size):
    valid_itemsets = {}
    for items in itemset_candidates:
        itemset = set(items)
        print(itemset)
        count = sum(1 for transaction in transactions.values() if itemset.issubset(transaction))
        
        if count >= min_support_threshold:
            valid_itemsets[items] = count
    
    # Print the frequent itemsets of the current size
    print(f"Frequent itemsets of size {size}:")
    for items, count in valid_itemsets.items():
        print(f"{items}: appears in {count} transactions")
    print("-----")
    return valid_itemsets

# (a) Frequent itemsets of size 1
item_counts = {}
for transaction in transactions.values():
    for item in transaction:
        if item in item_counts:
            item_counts[item] += 1
        else:
            item_counts[item] = 1

# Filter items that meet the minimum support threshold
frequent_items = {item: count for item, count in item_counts.items() if count >= min_support_threshold}

# (b) Frequent itemsets of size 2
# Generate all unique combinations of the frequent items of size 2
candidates_2 = list(combinations(frequent_items, 2))
print()
frequent_itemsets_2 = find_frequent_itemsets(candidates_2, 2)

# (c) Frequent itemsets of size 3
# Generate all unique combinations of the frequent items of size 3
candidates_3 = list(combinations(frequent_items, 3))
frequent_itemsets_3 = find_frequent_itemsets(candidates_3, 3)

print(frequent_items)
# (d) Can we proceed further?
# We cannot proceed if there are no frequent itemsets of size 3 or if the number of frequent items is less than 4.
if not frequent_itemsets_3 or len(frequent_items) < 4:
    print("Cannot proceed further with the Apriori algorithm as there are no larger frequent itemsets.")

    # Assuming item_counts is a dictionary with items and their counts
# and min_support_threshold is the minimum count threshold for an item to be considered frequent




Frequent itemsets of size 2:
('Bread', 'Milk'): appears in 3 transactions
('Bread', 'Diaper'): appears in 5 transactions
('Bread', 'Beer'): appears in 4 transactions
('Milk', 'Diaper'): appears in 4 transactions
('Milk', 'Beer'): appears in 3 transactions
('Milk', 'Coke'): appears in 3 transactions
('Diaper', 'Beer'): appears in 5 transactions
('Diaper', 'Coke'): appears in 3 transactions
-----
Frequent itemsets of size 3:
('Bread', 'Milk', 'Diaper'): appears in 3 transactions
('Bread', 'Diaper', 'Beer'): appears in 4 transactions
('Milk', 'Diaper', 'Beer'): appears in 3 transactions
('Milk', 'Diaper', 'Coke'): appears in 3 transactions
-----
{'Bread': 5, 'Milk': 4, 'Diaper': 6, 'Beer': 5, 'Coke': 3}


In [8]:
transactions = {
    1: ['Bread', 'Milk', 'Diaper', 'Beer'],
    2: ['Bread', 'Diaper', 'Beer', 'Eggs'],
    3: ['Milk', 'Diaper', 'Beer', 'Coke'],
    4: ['Bread', 'Milk', 'Diaper', 'Beer', 'Coke'],
    5: ['Bread', 'Milk', 'Diaper', 'Coke'],
    6: ['Bread', 'Diaper', 'Beer']
}

item_counts = {}
for transaction in transactions.values():
    for item in transaction:
        if item in item_counts:
            item_counts[item] += 1
        else:
            item_counts[item] = 1

            
candidates_2 = list(combinations(frequent_items, 2))
frequent_itemsets_2 = find_frequent_itemsets(candidates_2, 2)

frequent_items = {}  # Initialize an empty dictionary for frequent items

# Iterate over each item and its count in the item_counts dictionary
print(item_counts)
for item, count in item_counts.items():
    # Check if the count of the item meets or exceeds the minimum support threshold
    print(item, count)
    if count >= min_support_threshold:
        # If the condition is met, add the item and its count to the frequent_items dictionary
        frequent_items[item] = count
# Now frequent_items contains all items from item_counts that have a count >= min_support_threshold

Frequent itemsets of size 2:
('Bread', 'Milk'): appears in 3 transactions
('Bread', 'Diaper'): appears in 5 transactions
('Bread', 'Beer'): appears in 4 transactions
('Milk', 'Diaper'): appears in 4 transactions
('Milk', 'Beer'): appears in 3 transactions
('Milk', 'Coke'): appears in 3 transactions
('Diaper', 'Beer'): appears in 5 transactions
('Diaper', 'Coke'): appears in 3 transactions
-----
{'Bread': 5, 'Milk': 4, 'Diaper': 6, 'Beer': 5, 'Eggs': 1, 'Coke': 3}
Bread 5
Milk 4
Diaper 6
Beer 5
Eggs 1
Coke 3


In [18]:
from collections import defaultdict

# Given transaction data
transactions = {
    1: ['Bread', 'Milk', 'Diaper', 'Beer'],
    2: ['Bread', 'Diaper', 'Beer', 'Eggs'],
    3: ['Milk', 'Diaper', 'Beer', 'Coke'],
    4: ['Bread', 'Milk', 'Diaper', 'Beer', 'Coke'],
    5: ['Bread', 'Milk', 'Diaper', 'Coke'],
    6: ['Bread', 'Diaper', 'Beer']
}

# Assuming you have determined frequent_pairs from previous steps
frequent_pairs = {('Bread', 'Diaper'), ('Milk', 'Diaper'), ('Diaper', 'Beer'), ('Bread', 'Beer')} # example based on your transactions

# Constructing item_counts based on transactions
item_counts = defaultdict(int)
for items in transactions.values():
    for item in items:
        item_counts[item] += 1

# Generating rules and calculating confidence
rules = []
confidences = {}

for (item1, item2) in frequent_pairs:
    # Calculate support counts for the pair and individual items
    support_pair = sum(1 for items in transactions.values() if item1 in items and item2 in items)
    support_item1 = item_counts[item1]
    support_item2 = item_counts[item2]

    # Confidence for rules "item1 -> item2" and "item2 -> item1"
    confidence_item1_to_item2 = support_pair / support_item1
    confidence_item2_to_item1 = support_pair / support_item2

    # If confidence is 50% or greater, add to the list of rules
    if confidence_item1_to_item2 >= 0.5:
        rule = (item1, item2)
        rules.append(rule)
        confidences[rule] = confidence_item1_to_item2

    if confidence_item2_to_item1 >= 0.5:
        rule = (item2, item1)
        rules.append(rule)
        confidences[rule] = confidence_item2_to_item1

# Print rules and their confidence levels
for rule in rules:
    print(f"Rule: {rule[0]} -> {rule[1]}. Confidence: {confidences[rule]:.2%}")


Rule: Diaper -> Beer. Confidence: 83.33%
Rule: Beer -> Diaper. Confidence: 100.00%
Rule: Bread -> Beer. Confidence: 80.00%
Rule: Beer -> Bread. Confidence: 80.00%
Rule: Bread -> Diaper. Confidence: 100.00%
Rule: Diaper -> Bread. Confidence: 83.33%
Rule: Milk -> Diaper. Confidence: 100.00%
Rule: Diaper -> Milk. Confidence: 66.67%


In [3]:
def apriori_pass1(baskets, support_threshold):
    counts = {}
    for transaction, basket  in baskets.items():
        for item in basket:
            if item in counts:
                counts[item] +=1
            else:
                counts[item] = 1

    frequent_items = {}
    for key, value in counts.items():
        if value/len(baskets) >= support_threshold:
            frequent_items[key] = value
    return counts, frequent_items


print(apriori_pass1(transactions, 0.5)[1])


def apriori_later(baskets):
    pass

{'Bread': 5, 'Milk': 4, 'Diaper': 6, 'Beer': 5, 'Coke': 3}


# Question 3

In [64]:
baskets = {
    1: [1,2,3],
    2: [2,3,4],
    3: [3,4,5],
    4: [4,5,6],
    5: [1,3,5],
    6: [2,4,6],
    7: [1,3,4],
    8: [2,4,5],
    9: [3,5,6],
    10: [1,2,6],
    11: [2,3,5],
    12: [3,4,6]
}

support_threshold = 4

def pcy(basket):
    counts = {}
    for key, lst in basket.items():
        for item in lst:
            if item in counts:
                counts[item] +=1
            else:
                counts[item] = 1
        #for pair in find_pairs(basket):
            #print(pair)
        # hash pair to bucket 
        # add count to the bucket:

    return counts 

pcy(baskets)
print(find_pairs(baskets))



[[0. 2. 3. 1. 1. 1.]
 [0. 0. 3. 3. 2. 2.]
 [0. 0. 0. 4. 4. 2.]
 [0. 0. 0. 0. 3. 3.]
 [0. 0. 0. 0. 0. 2.]
 [0. 0. 0. 0. 0. 0.]]


In [6]:
from itertools import combinations
from collections import defaultdict

# Given data
baskets = {
    1: [1,2,3],
    2: [2,3,4],
    3: [3,4,5],
    4: [4,5,6],
    5: [1,3,5],
    6: [2,4,6],
    7: [1,3,4],
    8: [2,4,5],
    9: [3,5,6],
    10: [1,2,6],
    11: [2,3,5],
    12: [3,4,6]
}

# Support threshold
support_threshold = 4

# Count occurrences of each item
single_item_counts = defaultdict(int)
for items in baskets.values():
    for item in items:
        single_item_counts[item] += 1

# Determine frequent single items based on the support threshold
frequent_single_items = set(item for item, count in single_item_counts.items() if count >= support_threshold)

# Count occurrences of pairs (Step 1 of the PCY algorithm)
pair_counts = defaultdict(int)
for items in baskets.values():
    # Create pairs from the basket, only considering items that are frequent
    pairs = combinations([item for item in items if item in frequent_single_items], 2)
    for pair in pairs:
        pair_counts[pair] += 1

# Determine frequent pairs based on the support threshold
frequent_pairs = set(pair for pair, count in pair_counts.items() if count >= support_threshold)
print("Frequent pairs:", frequent_pairs)


Frequent pairs: {(3, 4), (3, 5)}


In [10]:
# Define the number of buckets
num_buckets = 11

# Create a hash table for the buckets
buckets = defaultdict(int)

# Hash function
def hash_pair(pair):
    return (pair[0] * pair[1]) % num_buckets

# Hash each pair to the corresponding bucket and increase the count
for pair in pair_counts:
    bucket = hash_pair(pair)
    buckets[bucket] += 1

# The result can be printed or used in the next steps
for pair, count in pair_counts.items():
    print(f"Pair {pair} is hashed to bucket {hash_pair(pair)}")


print(buckets)


Pair (1, 2) is hashed to bucket 2
Pair (1, 3) is hashed to bucket 3
Pair (2, 3) is hashed to bucket 6
Pair (2, 4) is hashed to bucket 8
Pair (3, 4) is hashed to bucket 1
Pair (3, 5) is hashed to bucket 4
Pair (4, 5) is hashed to bucket 9
Pair (4, 6) is hashed to bucket 2
Pair (5, 6) is hashed to bucket 8
Pair (1, 5) is hashed to bucket 5
Pair (2, 6) is hashed to bucket 1
Pair (1, 4) is hashed to bucket 4
Pair (2, 5) is hashed to bucket 10
Pair (3, 6) is hashed to bucket 7
Pair (1, 6) is hashed to bucket 6
defaultdict(<class 'int'>, {2: 2, 3: 1, 6: 2, 8: 2, 1: 2, 4: 2, 9: 1, 5: 1, 10: 1, 7: 1})


In [14]:
# Determine frequent buckets
frequent_buckets = {bucket for bucket, count in buckets.items() if count >= support_threshold}
print("Frequent buckets:", frequent_buckets)


print(buckets.items())
for bucket, counts in buckets.items():
    print(bucket, counts)


Frequent buckets: set()
dict_items([(2, 2), (3, 1), (6, 2), (8, 2), (1, 2), (4, 2), (9, 1), (5, 1), (10, 1), (7, 1)])
2 2
3 1
6 2
8 2
1 2
4 2
9 1
5 1
10 1
7 1


In [17]:
from itertools import combinations
from collections import defaultdict

# Data
baskets = {
    1: [1,2,3],
    2: [2,3,4],
    3: [3,4,5],
    4: [4,5,6],
    5: [1,3,5],
    6: [2,4,6],
    7: [1,3,4],
    8: [2,4,5],
    9: [3,5,6],
    10: [1,2,6],
    11: [2,3,5],
    12: [3,4,6]
}

# Support threshold
support_threshold = 4

# Initialize default dictionary for item counts
item_counts = defaultdict(int)

# Count each item's occurrence
for basket in baskets.values():
    for item in basket:
        item_counts[item] += 1

# Filter items by support threshold
frequent_items = {item for item, count in item_counts.items() if count >= support_threshold}

# a) To find the frequent pairs, we first identify all pairs then filter by support threshold
pair_counts = defaultdict(int)

# Hash function
def hash_pair(pair):
    return (pair[0] * pair[1]) % 11

# Hash table for the buckets
buckets = defaultdict(int)

# Find all pairs and hash them to buckets
for basket in baskets.values():
    for pair in combinations(basket, 2):  # Get all 2-combinations of items in the basket
        # We only consider pairs where both items are frequent
        if pair[0] in frequent_items and pair[1] in frequent_items:
            buckets[hash_pair(pair)] += 1  # Hash the pair to a bucket and increment the bucket's count
            pair_counts[pair] += 1

# Frequent pairs are those that meet or exceed the support threshold
frequent_pairs = {pair for pair, count in pair_counts.items() if count >= support_threshold}

print("a) Frequent pairs:", frequent_pairs)

# b) Mapping pairs to buckets
pair_bucket_mapping = {pair: hash_pair(pair) for pair in pair_counts}
print("b) Pair to bucket mapping:", pair_bucket_mapping)

# c) Identifying frequent buckets
print("c) Bucket counts:")
for bucket, count in buckets.items():
    print(f"Bucket {bucket}: {count} items")

frequent_buckets = {bucket for bucket, count in buckets.items() if count >= support_threshold}
print("Frequent buckets:", frequent_buckets)

# d) In the second pass of the PCY algorithm, we're focusing on the pairs that are in the frequent buckets.
second_pass_pairs = {pair for pair in pair_counts if hash_pair(pair) in frequent_buckets}
print("d) Pairs considered in the 2nd pass:", second_pass_pairs)


a) Frequent pairs: {(3, 4), (3, 5)}
b) Pair to bucket mapping: {(1, 2): 2, (1, 3): 3, (2, 3): 6, (2, 4): 8, (3, 4): 1, (3, 5): 4, (4, 5): 9, (4, 6): 2, (5, 6): 8, (1, 5): 5, (2, 6): 1, (1, 4): 4, (2, 5): 10, (3, 6): 7, (1, 6): 6}
c) Bucket counts:
Bucket 2: 5 items
Bucket 3: 3 items
Bucket 6: 4 items
Bucket 8: 5 items
Bucket 1: 6 items
Bucket 4: 5 items
Bucket 9: 3 items
Bucket 5: 1 items
Bucket 10: 2 items
Bucket 7: 2 items
Frequent buckets: {1, 2, 4, 6, 8}
d) Pairs considered in the 2nd pass: {(2, 4), (1, 2), (3, 4), (4, 6), (1, 4), (2, 3), (2, 6), (5, 6), (1, 6), (3, 5)}
