<a href="https://colab.research.google.com/github/Krisho1/Machine-Learning-Foundations-Math-Probability-Statistics-and-Computer-Science-Python-Codes-/blob/main/data_structure_and_algorithm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import tensorflow as tf
import torch
import pandas as pd
import matplotlib.pyplot as plt
import time
import random

##Constant Time

In [2]:
def take_first(my_list):
  return my_list[0]

In [3]:
short_list = [12,13,10,22,65,1]

In [4]:
tic = time.process_time()
first = take_first(short_list)
toc = time.process_time()

In [5]:
tic

10.633747239

In [6]:
first

12

In [7]:
toc

10.633826683

In [8]:
toc - tic


7.944400000070573e-05

In [9]:
long_list = [42]* 10**8

In [10]:
len(long_list)

100000000

In [11]:
tic = time.process_time()
first = take_first(long_list)
toc = time.process_time()

In [12]:
first

42

In [13]:
toc-tic

8.908699999921055e-05

In [14]:
list_length = [10**l for l in range(1,8)]
list_length

[10, 100, 1000, 10000, 100000, 1000000, 10000000]

In [15]:
constant_time = []


for l in list_length:
  lst = [42]*l
  tic = time.process_time()
  first = take_first(lst)
  toc = time.process_time()
  constant_time.append(toc-tic)

In [16]:
constant_df  =pd.DataFrame(list(zip(list_length,constant_time)), columns= ['n', 'time'])
constant_df

n          time
0        10  6.517000e-06
1       100  1.028000e-06
2      1000  8.550000e-07
3     10000  1.770000e-06
4    100000  2.020000e-06
5   1000000  7.894000e-06
6  10000000  3.401280e-04

## Linear

In [17]:
def find_max(my_list):
  max_val = my_list[0];
  for val in my_list[1:]:
    if val > max_val:
      max_val = val
  return max_val

In [18]:
short_list

[12, 13, 10, 22, 65, 1]

In [19]:
tic = time.process_time()
max_val = find_max(short_list)
toc = time.process_time()

In [20]:
max_val

65

In [21]:
toc-tic

6.79620000010317e-05

In [22]:
tic = time.process_time()
max_val = find_max(long_list)
toc = time.process_time()

In [23]:
toc-tic

6.324226981999999

## List

In [24]:
t = [25,3,6]

In [25]:
t.append(23)

In [26]:
t

[25, 3, 6, 23]

In [27]:
t[2]

6

In [28]:
#t/2  No math operation on list

In [29]:
x = np.array([25,2,3])

In [30]:
x[2]

3

In [31]:
x/3

array([8.33333333, 0.66666667, 1.        ])

In [32]:
y = torch.tensor([[25,2,3],[5,4,33]])
y

tensor([[25,  2,  3],
        [ 5,  4, 33]])

In [33]:
y[0,2]

tensor(3)

In [34]:
y/2

tensor([[12.5000,  1.0000,  1.5000],
        [ 2.5000,  2.0000, 16.5000]])

In [35]:
x = np.append(x,26)

In [36]:
x

array([25,  2,  3, 26])

##Stack

In [37]:
s = []

In [38]:
s.append('5 of diamond')
s

['5 of diamond']

In [39]:
s.append('ace of spades')
s

['5 of diamond', 'ace of spades']

In [40]:
s.append('Jocker of Diamond')
s

['5 of diamond', 'ace of spades', 'Jocker of Diamond']

In [41]:
s.pop()
s

['5 of diamond', 'ace of spades']

##Searching and Sorting

Binary Search

In [42]:
b = np.array([25,33,66,3,7,2,8,9,2,33,567,3])
b

array([ 25,  33,  66,   3,   7,   2,   8,   9,   2,  33, 567,   3])

In [43]:
b.sort() #Uses Quick Sort
b

array([  2,   2,   3,   3,   7,   8,   9,  25,  33,  33,  66, 567])

In [44]:
def binary_search(array, value):

    low = 0
    high = len(array)-1

    while low <= high:
        midpoint = (low + high) // 2 # rounds down to nearest integer after division
        if value < array[midpoint]:
            high = midpoint-1
        elif value > array[midpoint]:
            low = midpoint+1
        else:
            return midpoint
    return -1



In [45]:
binary_search(b,2)

0

In [46]:
def recursive_binary_search(array, value, low, high):

    if low <= high:

        midpoint = (low + high) // 2

        if array[midpoint] == value:
            return midpoint
        elif array[midpoint] > value:
            return recursive_binary_search(array, value, low, midpoint-1)
        else:
            return recursive_binary_search(array, value, midpoint+1, high)
    else:
        return -1

In [47]:
recursive_binary_search(b,25,0,len(b)-1)

7

##Bubble Sort

In [48]:
bs = np.array([2,88,6,55,4,76,89,4,54,83])
bs

array([ 2, 88,  6, 55,  4, 76, 89,  4, 54, 83])

In [49]:
def bubblesort(array):
  n = len(array)-1
  for i in range(n):
    for j in range(0,n):
      if array[j]>array[j+1]:
        array[j],array[j+1] = array[j+1],array[j]
  return array

In [50]:
bubblesort(bs)

array([ 2,  4,  4,  6, 54, 55, 76, 83, 88, 89])

##Merge Sort

In [51]:
'''
def merge_sort(my_list):

  midpoint = len(my_list)//2

  left_half = my_list[:midpoint]
  right_half = my_list[midpoint +1:]

  #recursive till 2 elements left

  left_half = merge_sort(left_half)
  right_half = merge_sort(right_half)


  my_list = []

  while len(left_half) > 0 and len(right_half) > 0:
    if left_half[0] < right_half[0]:
      my_list.append(left_half.pop(0))
    else:
      my_list.append(right_half.pop(0))

  for i in left_half:
    my_list.append(i)
  for i in right_half:
    my_list.append(i)


  return my_list

'''



'\ndef merge_sort(my_list):\n\n  midpoint = len(my_list)//2\n\n  left_half = my_list[:midpoint]\n  right_half = my_list[midpoint +1:]\n\n  #recursive till 2 elements left\n\n  left_half = merge_sort(left_half)\n  right_half = merge_sort(right_half)\n\n\n  my_list = []\n\n  while len(left_half) > 0 and len(right_half) > 0:\n    if left_half[0] < right_half[0]:\n      my_list.append(left_half.pop(0))\n    else:\n      my_list.append(right_half.pop(0))\n\n  for i in left_half:\n    my_list.append(i)\n  for i in right_half:\n    my_list.append(i)\n\n\n  return my_list\n\n'

In [52]:
def merge_sort(my_list): # using list instead of array so we can .pop() (np arrays don't pop with built-in method)

    if len(my_list) > 1: # if length is 1, no need to sort (at deepest recursion, some will have len 1, others len 2)

        # 1. Halve:
        midpoint = len(my_list) // 2 # Note: This is ~O(log n) behavior
        left_half = my_list[:midpoint]
        right_half = my_list[midpoint:]

        # 2. Sort (recursively):
        left_half = merge_sort(left_half)
        right_half = merge_sort(right_half)

        my_list = []

        # 3. Merge:
        while len(left_half)>0 and len(right_half)>0: # Note: This inner loop exhibits ~O(n) behavior

            if left_half[0] < right_half[0]:
                my_list.append(left_half.pop(0)) # pop first element

            else: # 1st element of right half < 1st element of left
                my_list.append(right_half.pop(0))

        # If any elements remain from either half, they must be the largest value:
        for i in left_half:
            my_list.append(i)
        for i in right_half:
            my_list.append(i)

    return my_list

In [53]:
m = [2,5,7,87,3,55,22,0,44,56,88,99,100]

In [54]:
merge_sort(m)

[0, 2, 3, 5, 7, 22, 44, 55, 56, 87, 88, 99, 100]

## Quick Sort

In [55]:
def quick_sort(array):
  _quick_sort(array,0,len(array)-1)
  return array

In [56]:
def _quick_sort(array,low,high):
  if low < high:
    p_index = partition(array,low,high)

    _quick_sort(array,low,p_index -1)

    _quick_sort(array,p_index+1,high)

  return array


In [57]:
def partition(array, low, high):

    # 1. Use the final element as the pivot:
    pivot = array[high]

    i = (low-1) # index of element on small side
    for j in range(low, high): # like a bubble swap, we compare pivot to all elements between low and high
        if array[j] < pivot: # if value < pivot, it's correctly on left so increment the smaller element's index...
            i = i+1
            array[i], array[j] = array[j], array[i]
    array[i+1], array[high] = array[high], array[i+1] # ...otherwise, swap greater value to right of pivot (now what we want)
    return(i+1) # return index of correctly positioned pivot

In [58]:
b = np.array([25, 2, 5, 14, 22, 11, 96, 1, 101])

In [59]:
quick_sort(b)

array([  1,   2,   5,  11,  14,  22,  25,  96, 101])

##Sets


In [60]:
inventory = {}  #Creating a dictionary
inventory

{}

In [61]:
inventory['hammer'] = [17]  #Key Value Pair
inventory

{'hammer': [17]}

In [62]:
inventory['nails'] = [33]
inventory['bolts'] = [43]
inventory['Brush'] = ['none']

In [63]:
inventory

{'hammer': [17], 'nails': [33], 'bolts': [43], 'Brush': ['none']}

In [66]:
inventory['Brush'] = [0]
inventory

{'hammer': [17, 3], 'nails': [33], 'bolts': [43], 'Brush': [0], 'brush': [0]}

In [67]:
inventory['hammer'].append(3)
inventory

{'hammer': [17, 3, 3],
 'nails': [33],
 'bolts': [43],
 'Brush': [0],
 'brush': [0]}

##Hashing

In [69]:
number = 5551234567
number

5551234567

In [70]:
split_num = [digit for digit in str(number)]
split_num

['5', '5', '5', '1', '2', '3', '4', '5', '6', '7']

In [72]:
final_digit = int(''.join(split_num[-2:]))    #As it varies most often
final_digit

67

In [73]:
hash = final_digit % 10
hash

7

In [74]:
def simple_hash(value):
  split_v = [digit for digit in str(value)]
  final_v = int(''.join(split_v[-2:]))
  hash = final_v %10
  return hash

In [75]:
simple_hash(number)

7

In [80]:
simple_hash(9788833988)

8

###Collison

In [81]:
simple_hash(555)

5

In [82]:
simple_hash(125)

5

Three common ways to resolve collisions:
1. Change the modulus denominator (e.g., `10` --> `11`); this adds procedural (and thus time) complexity to hash algo
2. Change the hash function entirely; ditto w.r.t. procedural complexity
3. Store a list (or similar) at the index, e.g.:

In [83]:
hash_table ={}

In [87]:
hash_table[simple_hash(555)] = [555]
hash_table

{5: [555]}

In [88]:
hash_table[simple_hash(125)].append(125)
hash_table

{5: [555, 125]}

Such a list is called a **bucket**.

Worst case:
* All of the values hash to the same hash value (e.g., `5`)
* Thus, all of the values are stored in a single bucket
* Searching through the bucket has linear O($n$) time complexity

Alternatively, we can increase memory complexity instead of time complexity:
* Use very large modulus denominator
* Reduces probability of collisions
* If use denominator of `1e9`, we have a hash table with a billion buckets

Could also have a second hash function *inside* of the bucket (e.g., if we know we'll have a few very large buckets).

There is no "perfect hash". It depends on the values you're working with. There are many options to consider with various trade-offs.

###Load Factor




Metric that guides hashing decisions:
$$ \text{load factor} = \frac{n_\text{values}}{n_\text{buckets}} $$

In [90]:
10/1e9

1e-08

If we have ten values to store, but a billion buckets...
$$ \text{load factor} = \frac{10}{10^9} = 10^{-8}$$

...we are probably using much more memory than we need to. This is the case whenever load factor $\approx 0$.

On the other hand, if the load factor is approaching one, $n_\text{values} \approx n_\text{buckets}$ and we may want to consider a larger hash table.

If load factor $>1$, then collisions are guaranteed and the case for a larger hash table is even stronger.

##Hash Maps

In [91]:
hash_map = {}

In [92]:
hash_map[simple_hash(8883334447)] = ('8883334447','John Doe')
hash_map

{7: ('8883334447', 'John Doe')}

In [94]:
hash_map[simple_hash(5551234568)] = (5551234568, 'Johnny Dochevski')
hash_map

{7: ('8883334447', 'John Doe'), 8: (5551234568, 'Johnny Dochevski')}

### String Keys

If our keys are character strings, we can still make use of hashing by converting the character string into an integer.

For example, we could use the [ASCII table](http://www.asciitable.com) to convert `Jon` to `112157156`.