# Ex No 1.a: Basic NumPy Array Operations

Aim:
To understand the basics of NumPy arrays, including creation, attributes, slicing and indexing.

Scenario:
You are a data scientist working with a dataset of students' scores in various subjects. You need to organize this data efficiently for analysis.

Sample Dataset:
data = [
    [85, 92, 78, 90],
    [88, 79, 85, 93],
    [91, 85, 87, 88],
    [76, 88, 84, 91]
]
subjects = ['Math', 'Physics', 'Chemistry', 'Biology']

Task to be Performed:
1.	Create a NumPy array from the given dataset.
2.	Retrieve the attributes of the array (shape, size, dtype).
3.	Slice the array to get the scores of the first two students.
4.	Index the array to get the score of the second student in Chemistry.


In [ ]:
#1.
import numpy as np
data = np.array([ [85, 92, 78, 90], [88, 79, 85, 93], [91, 85, 87, 88], [76, 88, 84, 91] ])
subjects = np.array(['Math', 'Physics', 'Chemistry', 'Biology'])
print(data)
print(subjects)
#2.
print("Shape:", data.shape)
print("Size:",data.size)
print("Data type:",data.dtype)
#3.
print("Scores of the first two students:",data[:2])
#4.
print("Score of the second student in Chemistry : ",data[1,2])

[[85 92 78 90]
 [88 79 85 93]
 [91 85 87 88]
 [76 88 84 91]]
['Math' 'Physics' 'Chemistry' 'Biology']
Shape: (4, 4)
Size: 16
Data type: int32
Scores of the first two students: [[85 92 78 90]
 [88 79 85 93]]
Score of the second student in Chemistry :  85


# Ex No 1.b: Basic NumPy Array Operations

Aim: To understand the basics of NumPy arrays, including creation, attributes, slicing and indexing.

Scenario: You are a financial analyst working with a dataset of monthly sales revenue for a company over a year. You need to organize and analyze this data efficiently.

Sample Dataset:
months = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December']
sales_revenue = [12000, 15000, 17000, 13000, 16000, 18000, 20000, 19000, 17500, 16000, 15000, 16500]

Task to be Performed:
1.	Create a NumPy array from the sales revenue list.
2.	Retrieve the attributes of the array (shape, size, dtype).
3.	Slice the array to get the sales revenue for the first half of the year.
4.	Index the array to get the sales revenue for May.
5.	Calculate the total sales revenue for the year.
6.	Find the month with the highest sales revenue.
Expected Output:
Shape: (12,)
Size: 12
Data type: int32
First half of the year sales revenue: [12000 15000 17000 13000 16000 18000]
Sales revenue for May: 16000
Total sales revenue for the year: 195500
Month with highest sales revenue: July


In [ ]:
#1.
import numpy as np
data = np.array([12000, 15000, 17000, 13000, 16000, 18000, 20000, 19000, 17500, 16000, 15000, 16500])
print("Sales revenue list:",data)
#2.
print("Shape:", data.shape)
print("Size:",data.size)
print("Data type:",data.dtype)
#3.
print("Sales of first half:",data[0:6])
#4.
print("Sales of May:",data[4])
#5.
sum = np.sum(data)
print("Total Sales revenue:",sum)
#6.
high = np.max(data)
print("Highest sales revenue:",high)

Sales revenue list: [12000 15000 17000 13000 16000 18000 20000 19000 17500 16000 15000 16500]
Shape: (12,)
Size: 12
Data type: int64
Sales of first half: [12000 15000 17000 13000 16000 18000]
Sales of May: 16000
Total Sales revenue: 195000
Highest sales revenue: 20000
