In [ ]:
## from datasets import list_datasets, load_dataset
import pandas as pd
import numpy as np

ds = pd.read_csv("titanic3.csv")
print(ds)
pd.isnull(ds)


In [ ]:
num11 = 1
num22 = 2
result = num11 + num22


numz, numy = 1, 4
print(numz + numy)
print(result)


name = 'Peter James'
age = '12'
print(name + age)

text = "Peter is {} years old"
age = 12
result = text.format(age)
print(result)

## reverse a given string
text = "This is for practice purpose"
print(text[::-1])


## Using enumerate keyword
animals = ['cat', 'goat', 'dog']
for index, value in enumerate(animals):
    print(str(index) + ' '+ str(value))
    print(f'{str(index)} {str(value)}')


## Fibonacci
a, b = 0, 1
while a < 100:
    print(a)
    a, b = b, a+b


## Recurssion in Python
def sum_recursion(n):
    return 0 if(n == 0) else n + sum_recursion(n-1)

sum_recursion(6)

## using recurssion to calculate factorial
def factorial_recursion(n):
    return 1 if(n == 0) else n * factorial_recursion(n-1)

factorial_recursion(5)

In [35]:
## Data Structures
## Running time analysis

## Doubly Linked List
import collections
my_list = collections.deque([])
my_list.append(10)
my_list.append("James")
my_list.append(False)

print(my_list)

deque([10, 'James', False])


In [54]:
## Numpy

import numpy as np

python_list = [1,2,3,4]
numpy_array = np.array(python_list)
print(type(numpy_array))

arr = np.array([1,2,3,4,5])
print(arr)

arr[0] = 12
print(arr)

np.insert(arr, 2, 30)


<class 'numpy.ndarray'>
[1 2 3 4 5]
[12  2  3  4  5]
0
[1 2 3]
1
[4 5 6]


In [57]:
## Multi dimensional array
nums = np.array([[1,2,3],[4,5,6]])
for row in nums:
    for item in row:
        print(item)

1
2
3
4
5
6


In [ ]:
## Basic Statistics for ML
## Mean
## The mean or the expected value of x: E(x) of a random variable is the mean average value
## in the population

expected value = summation (outcome * probability)