question1. Generate a list of 100 integers containing values between 90 to 130 and store it in the variable `int_list`.
After generating the list, f

In [1]:
import random

# Generate a list of 100 integers between 90 and 130
int_list = [random.randint(90, 130) for _ in range(100)]


(i) Write a Python function to calculate the mean of a given list of numbers.

Create a function to find the median of a list of numbers.

In [2]:
def calculate_mean(nums):
    return sum(nums) / len(nums)


In [ ]:
def calculate_median(nums):
    sorted_nums = sorted(nums)
    n = len(sorted_nums)
    if n % 2 == 0:
        return (sorted_nums[n//2 - 1] + sorted_nums[n//2]) / 2
    else:
        return sorted_nums[n//2]


 (ii) Develop a program to compute the mode of a list of integers.



In [3]:
from collections import Counter

def calculate_mode(nums):
    count = Counter(nums)
    most_common = count.most_common(1)
    return most_common[0][0]  # Returns the most frequent number


(iii) Implement a function to calculate the weighted mean of a list of values and their corresponding weights.

In [ ]:
def calculate_weighted_mean(values, weights):
    weighted_sum = sum(val * wt for val, wt in zip(values, weights))
    total_weight = sum(weights)
    return weighted_sum / total_weight if total_weight != 0 else None


 (iv) Write a Python function to find the geometric mean of a list of positive numbers.

In [ ]:
import math

def calculate_geometric_mean(nums):
    product = 1
    for num in nums:
        product *= num
    return product**(1/len(nums)) if len(nums) > 0 else None



  (v) Create a program to calculate the harmonic mean of a list of values.

In [ ]:
def calculate_harmonic_mean(nums):
    if all(num > 0 for num in nums):
        return len(nums) / sum(1/num for num in nums)
    else:
        return None  # Harmonic mean is undefined for non-positive numbers


  (vi) Build a function to determine the midrange of a list of numbers (average of the minimum and maximum)

In [ ]:
def calculate_midrange(nums):
    return (min(nums) + max(nums)) / 2


 (vii) Implement a Python program to find the trimmed mean of a list, excluding a certain percentage of
outliers.


In [ ]:
def calculate_trimmed_mean(nums, trim_percentage):
    sorted_nums = sorted(nums)
    n = len(sorted_nums)
    trim_count = int(n * trim_percentage / 100)

    trimmed_nums = sorted_nums[trim_count:n-trim_count]
    return sum(trimmed_nums) / len(trimmed_nums) if len(trimmed_nums) > 0 else None


question2.. Generate a list of 500 integers containing values between 200 to 300 and store it in the variable `int_list2`.
After generating the list, find the following:

In [ ]:
import random

# Generate a list of 500 integers between 200 and 300
int_list2 = [random.randint(200, 300) for _ in range(500)]


  (i) Compare the given list of visualization for the given data:

    

    1. Frequency & Gaussian distribution

    2. Frequency smoothened KDE plot

    3. Gaussian distribution & smoothened KDE plot

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import scipy.stats as stats

# Frequency Plot & Gaussian Distribution
plt.figure(figsize=(14, 7))
sns.histplot(int_list2, kde=True, stat='density', bins=30, color='skyblue', edgecolor='black')
plt.title('Frequency & Gaussian Distribution')
plt.xlabel('Value')
plt.ylabel('Density')
plt.grid(True)
plt.show()

# Smoothened KDE Plot
plt.figure(figsize=(14, 7))
sns.kdeplot(int_list2, shade=True, color='red')
plt.title('Frequency Smoothened KDE Plot')
plt.xlabel('Value')
plt.ylabel('Density')
plt.grid(True)
plt.show()

# Gaussian Distribution & Smoothened KDE Plot
plt.figure(figsize=(14, 7))
sns.kdeplot(int_list2, shade=True, color='red')
sns.histplot(int_list2, kde=True, stat='density', bins=30, color='skyblue', edgecolor='black')
plt.title('Gaussian Distribution & Smoothened KDE Plot')
plt.xlabel('Value')
plt.ylabel('Density')
plt.grid(True)
plt.show()


 (ii) Write a Python function to calculate the range of a given list of numbers.

In [ ]:
def calculate_range(nums):
    return max(nums) - min(nums)

# Calculate range of int_list2
range_val = calculate_range(int_list2)
print(f"Range: {range_val}")


  (iii) Create a program to find the variance and standard deviation of a list of numbers.

In [ ]:
def calculate_variance(nums):
    mean = sum(nums) / len(nums)
    return sum((x - mean) ** 2 for x in nums) / len(nums)

def calculate_standard_deviation(nums):
    return calculate_variance(nums) ** 0.5

# Calculate variance and standard deviation of int_list2
variance = calculate_variance(int_list2)
std_deviation = calculate_standard_deviation(int_list2)

print(f"Variance: {variance}")
print(f"Standard Deviation: {std_deviation}")


 (iv) Implement a function to compute the interquartile range (IQR) of a list of values.

In [ ]:
def calculate_iqr(nums):
    sorted_nums = sorted(nums)
    n = len(sorted_nums)

    # Q1 (25th percentile) and Q3 (75th percentile)
    Q1 = np.percentile(sorted_nums, 25)
    Q3 = np.percentile(sorted_nums, 75)

    return Q3 - Q1

# Calculate the IQR of int_list2
iqr = calculate_iqr(int_list2)
print(f"Interquartile Range (IQR): {iqr}")


 (v) Build a program to calculate the coefficient of variation for a dataset.

In [ ]:
def calculate_coefficient_of_variation(nums):
    mean = calculate_mean(nums)
    std_deviation = calculate_standard_deviation(nums)
    return std_deviation / mean

# Calculate Coefficient of Variation of int_list2
coefficient_of_variation = calculate_coefficient_of_variation(int_list2)
print(f"Coefficient of Variation: {coefficient_of_variation}")


 (vi) Write a Python function to find the mean absolute deviation (MAD) of a list of numbers.

In [ ]:
def calculate_mad(nums):
    mean = sum(nums) / len(nums)
    return sum(abs(x - mean) for x in nums) / len(nums)

# Calculate MAD of int_list2
mad = calculate_mad(int_list2)
print(f"Mean Absolute Deviation (MAD): {mad}")


  (vii) Create a program to calculate the quartile deviation of a list of values.

In [ ]:
def calculate_quartile_deviation(nums):
    sorted_nums = sorted(nums)
    Q1 = np.percentile(sorted_nums, 25)
    Q3 = np.percentile(sorted_nums, 75)
    return (Q3 - Q1) / 2

# Calculate Quartile Deviation of int_list2
quartile_deviation = calculate_quartile_deviation(int_list2)
print(f"Quartile Deviation: {quartile_deviation}")


 (viii) Implement a function to find the range-based coefficient of dispersion for a dataset.

In [ ]:
def calculate_range_based_dispersion(nums):
    return (max(nums) - min(nums)) / (max(nums) + min(nums))

# Calculate Range-Based Coefficient of Dispersion for int_list2
dispersion = calculate_range_based_dispersion(int_list2)
print(f"Range-Based Coefficient of Dispersion: {dispersion}")


3.   Write a Python class representing a discrete random variable with methods to calculate its expected
value and variance.

In [7]:
class DiscreteRandomVariable:
    def __init__(self, values, probabilities):
        """
        Initialize the discrete random variable with given values and probabilities.

        :param values: List of values the random variable can take.
        :param probabilities: List of probabilities associated with each value.
        """
        if len(values) != len(probabilities):
            raise ValueError("The number of values and probabilities must be the same.")

        if sum(probabilities) != 1:
            raise ValueError("The sum of probabilities must be 1.")

        self.values = values
        self.probabilities = probabilities

    def expected_value(self):
        """
        Calculate the expected value (mean) of the discrete random variable.

        :return: Expected value of the random variable.
        """
        return sum(value * prob for value, prob in zip(self.values, self.probabilities))

    def variance(self):
        """
        Calculate the variance of the discrete random variable.

        :return: Variance of the random variable.
        """
        expected_val = self.expected_value()
        # Calculate E(X^2)
        expected_val_squared = sum((value**2) * prob for value, prob in zip(self.values, self.probabilities))
        # Variance formula: Var(X) = E(X^2) - (E(X))^2
        return expected_val_squared - expected_val**2

# Example usage:
values = [1, 2, 3, 4]  # Example values for the random variable
probabilities = [0.1, 0.2, 0.4, 0.3]  # Corresponding probabilities for each value

# Create an instance of DiscreteRandomVariable
random_var = DiscreteRandomVariable(values, probabilities)

# Calculate expected value and variance
expected_val = random_var.expected_value()
variance_val = random_var.variance()

print(f"Expected Value: {expected_val}")
print(f"Variance: {variance_val}")


Expected Value: 2.9000000000000004
Variance: 0.8899999999999988


4.  Implement a program to simulate the rolling of a fair six-sided die and calculate the expected value and
variance of the outcomes.


In [6]:
import random

def simulate_die_rolls(num_rolls):
    # Simulate rolling a fair six-sided die
    rolls = [random.randint(1, 6) for _ in range(num_rolls)]
    return rolls

def calculate_expected_value(rolls):
    # The expected value of a fair die is 3.5 (mean of 1, 2, 3, 4, 5, 6)
    return sum(rolls) / len(rolls)

def calculate_variance(rolls, expected_value):
    # Variance = E(X^2) - (E(X))^2
    expected_value_squared = sum(x**2 for x in rolls) / len(rolls)
    return expected_value_squared - expected_value**2

# Simulate 1000 rolls of a fair six-sided die
num_rolls = 1000
rolls = simulate_die_rolls(num_rolls)

# Calculate expected value and variance from simulation
expected_val = calculate_expected_value(rolls)
variance_val = calculate_variance(rolls, expected_val)

# Display the results
print(f"Simulated Expected Value: {expected_val:.2f}")
print(f"Simulated Variance: {variance_val:.2f}")

# Theoretical Expected Value and Variance for a fair six-sided die
theoretical_expected_value = 3.5
theoretical_variance = (35 / 6) - theoretical_expected_value ** 2  # Var(X) = E(X^2) - (E(X))^2

print(f"Theoretical Expected Value: {theoretical_expected_value}")
print(f"Theoretical Variance: {theoretical_variance:.2f}")


Simulated Expected Value: 3.40
Simulated Variance: 2.83
Theoretical Expected Value: 3.5
Theoretical Variance: -6.42


5.   Create a Python function to generate random samples from a given probability distribution (e.g.,
binomial, Poisson) and calculate their mean and variance.

In [5]:
import numpy as np

def generate_random_samples(distribution_type, *params, num_samples=1000):
    """
    Generate random samples from a specified probability distribution and calculate their mean and variance.

    :param distribution_type: The type of the distribution ('binomial', 'poisson', etc.).
    :param params: Parameters for the chosen distribution.
                   For 'binomial': n (number of trials), p (probability of success).
                   For 'poisson': lam (rate or expected value).
    :param num_samples: The number of random samples to generate (default is 1000).
    :return: The mean and variance of the generated samples.
    """

    # Generate random samples based on the chosen distribution
    if distribution_type == 'binomial':
        n, p = params
        samples = np.random.binomial(n, p, num_samples)
    elif distribution_type == 'poisson':
        lam = params[0]
        samples = np.random.poisson(lam, num_samples)
    else:
        raise ValueError("Unsupported distribution type. Use 'binomial' or 'poisson'.")

    # Calculate mean and variance
    mean = np.mean(samples)
    variance = np.var(samples)

    return mean, variance

# Example Usage:
# 1. Binomial Distribution with n=10 trials, p=0.5 probability of success
binomial_mean, binomial_variance = generate_random_samples('binomial', 10, 0.5)
print(f"Binomial Distribution (n=10, p=0.5): Mean = {binomial_mean}, Variance = {binomial_variance}")

# 2. Poisson Distribution with lambda=5 (expected number of events)
poisson_mean, poisson_variance = generate_random_samples('poisson', 5)
print(f"Poisson Distribution (lambda=5): Mean = {poisson_mean}, Variance = {poisson_variance}")


Binomial Distribution (n=10, p=0.5): Mean = 5.0, Variance = 2.466
Poisson Distribution (lambda=5): Mean = 4.966, Variance = 5.090843999999999


6.  Write a Python script to generate random numbers from a Gaussian (normal) distribution and compute
the mean, variance, and standard deviation of the samples.

In [4]:
import numpy as np

def generate_normal_samples(mean, std_dev, num_samples=1000):
    """
    Generate random numbers from a normal (Gaussian) distribution and calculate their mean,
    variance, and standard deviation.

    :param mean: The mean (mu) of the normal distribution.
    :param std_dev: The standard deviation (sigma) of the normal distribution.
    :param num_samples: The number of random samples to generate (default is 1000).
    :return: Mean, variance, and standard deviation of the generated samples.
    """
    # Generate random samples from a normal distribution
    samples = np.random.normal(loc=mean, scale=std_dev, size=num_samples)

    # Calculate mean, variance, and standard deviation
    sample_mean = np.mean(samples)
    sample_variance = np.var(samples)
    sample_std_dev = np.std(samples)

    return sample_mean, sample_variance, sample_std_dev

# Example usage:
mean = 0  # Mean of the distribution
std_dev = 1  # Standard deviation of the distribution
num_samples = 1000  # Number of samples to generate

# Generate the samples and calculate statistics
sample_mean, sample_variance, sample_std_dev = generate_normal_samples(mean, std_dev, num_samples)

# Display the results
print(f"Generated {num_samples} samples from a Gaussian distribution:")
print(f"Sample Mean: {sample_mean:.2f}")
print(f"Sample Variance: {sample_variance:.2f}")
print(f"Sample Standard Deviation: {sample_std_dev:.2f}")

# Compare with theoretical values for Gaussian distribution
print("\nTheoretical values:")
print(f"Theoretical Mean: {mean}")
print(f"Theoretical Variance: {std_dev**2}")
print(f"Theoretical Standard Deviation: {std_dev}")


Generated 1000 samples from a Gaussian distribution:
Sample Mean: 0.03
Sample Variance: 1.01
Sample Standard Deviation: 1.01

Theoretical values:
Theoretical Mean: 0
Theoretical Variance: 1
Theoretical Standard Deviation: 1


7.  (i) Write a Python function that calculates their skewness.

In [8]:
def calculate_skewness(column):
    return column.skew()


(ii) Create a program that determines whether the columns exhibit positive skewness, negative skewness, or is
approximately symmetric.

In [ ]:
def determine_skewness_type(column):
    skew = calculate_skewness(column)
    if skew > 0:
        return "Positive skew"
    elif skew < 0:
        return "Negative skew"
    else:
        return "Approximately symmetric"


 (iii) Write a function that calculates the covariance between two columns.

In [9]:
def calculate_covariance(column1, column2):
    return column1.cov(column2)


  (iv) Implement a Python program that calculates the Pearson correlation coefficient between two columns.

In [ ]:
def calculate_pearson_correlation(column1, column2):
    return column1.corr(column2)


 (v) Write a script to visualize the correlation between two specific columns in a Pandas DataFrame using
scatter plots.

In [11]:
def plot_scatter(column1, column2):
    plt.figure(figsize=(8, 6))
    plt.scatter(column1, column2, alpha=0.6)
    plt.title(f'Scatter Plot of {column1.name} vs {column2.name}')
    plt.xlabel(column1.name)
    plt.ylabel(column2.name)
    plt.grid(True)
    plt.show()


8.. Write a Python function to calculate the probability density function (PDF) of a continuous random
variable for a given normal distribution.


In [10]:
import numpy as np

def normal_pdf(x, mu, sigma):
    """
    Calculate the Probability Density Function (PDF) of a normal distribution.

    :param x: The value at which to compute the PDF.
    :param mu: The mean of the normal distribution (mu).
    :param sigma: The standard deviation of the normal distribution (sigma).
    :return: The PDF value at x for the normal distribution.
    """
    # Calculate the PDF using the formula for a normal distribution
    coefficient = 1 / (sigma * np.sqrt(2 * np.pi))
    exponent = np.exp(-0.5 * ((x - mu) / sigma) ** 2)
    return coefficient * exponent

# Example usage:
mu = 0  # Mean of the distribution
sigma = 1  # Standard deviation of the distribution
x_values = [-3, -1, 0, 1, 3]  # Values at which to compute the PDF

# Calculate and print the PDF for each value in x_values
for x in x_values:
    pdf_value = normal_pdf(x, mu, sigma)
    print(f"PDF at x = {x}: {pdf_value:.4f}")


PDF at x = -3: 0.0044
PDF at x = -1: 0.2420
PDF at x = 0: 0.3989
PDF at x = 1: 0.2420
PDF at x = 3: 0.0044


9.  Create a program to calculate the cumulative distribution function (CDF) of exponential distribution.

In [12]:
import numpy as np

def exponential_cdf(x, lambd):
    """
    Calculate the CDF of an exponential distribution.

    :param x: The value at which to calculate the CDF.
    :param lambd: The rate parameter (lambda) of the exponential distribution.
    :return: The CDF value at x for the exponential distribution.
    """
    if x < 0:
        return 0  # Exponential CDF is 0 for negative x
    return 1 - np.exp(-lambd * x)

# Example usage
lambda_value = 1.5  # Rate parameter (lambda)
x_values = [0, 1, 2, 3, 4]  # Values to calculate the CDF

# Calculate and print the CDF for each value in x_values
for x in x_values:
    cdf_value = exponential_cdf(x, lambda_value)
    print(f"CDF at x = {x}: {cdf_value:.4f}")


CDF at x = 0: 0.0000
CDF at x = 1: 0.7769
CDF at x = 2: 0.9502
CDF at x = 3: 0.9889
CDF at x = 4: 0.9975


10.. Write a Python function to calculate the probability mass function (PMF) of Poisson distribution.

In [13]:
import math

def poisson_pmf(k, lambd):
    """
    Calculate the Probability Mass Function (PMF) of a Poisson distribution.

    :param k: The number of occurrences (random variable).
    :param lambd: The rate parameter (lambda) of the Poisson distribution.
    :return: The PMF value for the Poisson distribution at k.
    """
    if k < 0 or lambd <= 0:
        raise ValueError("k must be a non-negative integer and lambda must be positive.")

    # Calculate the PMF using the formula
    pmf_value = (lambd**k * math.exp(-lambd)) / math.factorial(k)
    return pmf_value

# Example usage:
lambda_value = 3  # Rate parameter (lambda)
k_values = [0, 1, 2, 3, 4, 5]  # Number of occurrences (k)

# Calculate and print the PMF for each value in k_values
for k in k_values:
    pmf_value = poisson_pmf(k, lambda_value)
    print(f"PMF at k = {k}: {pmf_value:.4f}")


PMF at k = 0: 0.0498
PMF at k = 1: 0.1494
PMF at k = 2: 0.2240
PMF at k = 3: 0.2240
PMF at k = 4: 0.1680
PMF at k = 5: 0.1008


11. A company wants to test if a new website layout leads to a higher conversion rate (percentage of visitors
who make a purchase). They collect data from the old and new layouts to compare.

In [14]:
import numpy as np
from statsmodels.stats.proportion import proportions_ztest

# Generate data
old_layout = np.array([1] * 50 + [0] * 950)  # 50 purchases out of 1000 visitors
new_layout = np.array([1] * 70 + [0] * 930)  # 70 purchases out of 1000 visitors

# Calculate the number of successes (purchases) and the total number of trials (visitors)
successes = np.array([np.sum(old_layout), np.sum(new_layout)])
totals = np.array([len(old_layout), len(new_layout)])

# Perform z-test for proportions
z_stat, p_value = proportions_ztest(successes, totals, alternative='larger')

# Output the results
print(f"Z-statistic: {z_stat:.4f}")
print(f"P-value: {p_value:.4f}")

# Interpretation of the p-value
if p_value < 0.05:
    print("The new layout leads to a statistically significant higher conversion rate.")
else:
    print("There is no statistically significant difference in conversion rates between the old and new layouts.")


Z-statistic: -1.8831
P-value: 0.9702
There is no statistically significant difference in conversion rates between the old and new layouts.


12. A tutoring service claims that its program improves students' exam scores. A sample of students who
participated in the program was taken, and their scores before and after the program were recorded.


Use the below code to generate samples of respective arrays of marks:

```python

before_program = np.array([75, 80, 85, 70, 90, 78, 92, 88, 82, 87])

after_program = np.array([80, 85, 90, 80, 92, 80, 95, 90, 85, 88])

```

Use z-test to find if the claims made by tutor are true or false.

In [15]:
import numpy as np
from scipy.stats import norm

# Sample data
before_program = np.array([75, 80, 85, 70, 90, 78, 92, 88, 82, 87])
after_program = np.array([80, 85, 90, 80, 92, 80, 95, 90, 85, 88])

# Step 1: Calculate the differences (after - before)
differences = after_program - before_program

# Step 2: Calculate the mean and standard deviation of the differences
mean_difference = np.mean(differences)
std_difference = np.std(differences, ddof=1)  # Sample standard deviation

# Step 3: Number of paired samples
n = len(differences)

# Step 4: Calculate the z-statistic
z_statistic = mean_difference / (std_difference / np.sqrt(n))

# Step 5: Calculate the p-value (one-tailed test)
p_value = 1 - norm.cdf(z_statistic)

# Output the results
print(f"Z-statistic: {z_statistic:.4f}")
print(f"P-value: {p_value:.4f}")

# Interpretation of the p-value
if p_value < 0.05:
    print("The tutoring program has a statistically significant effect on exam scores.")
else:
    print("There is no statistically significant effect of the tutoring program on exam scores.")


Z-statistic: 4.5932
P-value: 0.0000
The tutoring program has a statistically significant effect on exam scores.


13.  A pharmaceutical company wants to determine if a new drug is effective in reducing blood pressure. They
conduct a study and record blood pressure measurements before and after administering the drug.


Use the below code to generate samples of respective arrays of blood pressure:


```python

before_drug = np.array([145, 150, 140, 135, 155, 160, 152, 148, 130, 138])

after_drug = np.array([130, 140, 132, 128, 145, 148, 138, 136, 125, 130])

  ```


Implement z-test to find if the drug really works or not.

In [16]:
import numpy as np
from scipy.stats import norm

# Sample data
before_drug = np.array([145, 150, 140, 135, 155, 160, 152, 148, 130, 138])
after_drug = np.array([130, 140, 132, 128, 145, 148, 138, 136, 125, 130])

# Step 1: Calculate the differences (before - after)
differences = before_drug - after_drug

# Step 2: Calculate the mean and standard deviation of the differences
mean_difference = np.mean(differences)
std_difference = np.std(differences, ddof=1)  # Sample standard deviation

# Step 3: Number of paired samples
n = len(differences)

# Step 4: Calculate the z-statistic
z_statistic = mean_difference / (std_difference / np.sqrt(n))

# Step 5: Calculate the p-value (one-tailed test)
p_value = 1 - norm.cdf(z_statistic)

# Output the results
print(f"Z-statistic: {z_statistic:.4f}")
print(f"P-value: {p_value:.4f}")

# Interpretation of the p-value
if p_value < 0.05:
    print("The drug has a statistically significant effect in reducing blood pressure.")
else:
    print("There is no statistically significant effect of the drug in reducing blood pressure.")


Z-statistic: 10.0499
P-value: 0.0000
The drug has a statistically significant effect in reducing blood pressure.


14.. A customer service department claims that their average response time is less than 5 minutes. A sample
of recent customer interactions was taken, and the response times were recorded.


Implement the below code to generate the array of response time:

```python

response_times = np.array([4.3, 3.8, 5.1, 4.9, 4.7, 4.2, 5.2, 4.5, 4.6, 4.4])

```

Implement z-test to find the claims made by customer service department are tru or false.

In [17]:
import numpy as np
from scipy.stats import norm

# Sample data
response_times = np.array([4.3, 3.8, 5.1, 4.9, 4.7, 4.2, 5.2, 4.5, 4.6, 4.4])

# Population mean (claimed by customer service)
population_mean = 5

# Step 1: Calculate the sample mean and standard deviation
sample_mean = np.mean(response_times)
sample_std = np.std(response_times, ddof=1)  # Sample standard deviation
n = len(response_times)

# Step 2: Calculate the z-statistic
z_statistic = (sample_mean - population_mean) / (sample_std / np.sqrt(n))

# Step 3: Calculate the p-value for one-tailed test
p_value = norm.cdf(z_statistic)  # One-tailed test

# Output the results
print(f"Z-statistic: {z_statistic:.4f}")
print(f"P-value: {p_value:.4f}")

# Interpretation of the p-value
if p_value < 0.05:
    print("The customer service department's claim is statistically significant: response times are less than 5 minutes on average.")
else:
    print("There is no statistical evidence to support the customer service department's claim that response times are less than 5 minutes.")


Z-statistic: -3.1845
P-value: 0.0007
The customer service department's claim is statistically significant: response times are less than 5 minutes on average.


15.. A company is testing two different website layouts to see which one leads to higher click-through rates.
Write a Python function to perform an A/B test analysis, including calculating the t-statistic, degrees of
freedom, and p-value.


Use the following data:

```python

layout_a_clicks = [28, 32, 33, 29, 31, 34, 30, 35, 36, 37]

layout_b_clicks = [40, 41, 38, 42, 39, 44, 43, 41, 45, 47]

In [18]:
import numpy as np
from scipy import stats

# Data: Number of clicks for layouts A and B
layout_a_clicks = [28, 32, 33, 29, 31, 34, 30, 35, 36, 37]
layout_b_clicks = [40, 41, 38, 42, 39, 44, 43, 41, 45, 47]

# Step 1: Calculate sample means and standard deviations
mean_a = np.mean(layout_a_clicks)
mean_b = np.mean(layout_b_clicks)

std_a = np.std(layout_a_clicks, ddof=1)
std_b = np.std(layout_b_clicks, ddof=1)

n_a = len(layout_a_clicks)
n_b = len(layout_b_clicks)

# Step 2: Calculate pooled standard error (SE)
SE = np.sqrt((std_a**2 / n_a) + (std_b**2 / n_b))

# Step 3: Calculate the t-statistic
t_statistic = (mean_a - mean_b) / SE

# Step 4: Calculate degrees of freedom (using Welch's approximation)
df = ((std_a**2 / n_a + std_b**2 / n_b)**2) / \
     ((std_a**2 / n_a)**2 / (n_a - 1) + (std_b**2 / n_b)**2 / (n_b - 1))

# Step 5: Calculate the p-value (two-tailed test)
p_value = 2 * (1 - stats.t.cdf(abs(t_statistic), df))  # Two-tailed test

# Step 6: Output the results
print(f"Mean of Layout A: {mean_a:.2f}")
print(f"Mean of Layout B: {mean_b:.2f}")
print(f"Standard deviation of Layout A: {std_a:.2f}")
print(f"Standard deviation of Layout B: {std_b:.2f}")
print(f"t-statistic: {t_statistic:.4f}")
print(f"Degrees of freedom: {df:.2f}")
print(f"P-value: {p_value:.4f}")

# Step 7: Interpretation of results
if p_value < 0.05:
    print("There is a significant difference between the click-through rates of Layout A and Layout B.")
else:
    print("There is no significant difference between the click-through rates of Layout A and Layout B.")


Mean of Layout A: 32.50
Mean of Layout B: 42.00
Standard deviation of Layout A: 3.03
Standard deviation of Layout B: 2.79
t-statistic: -7.2981
Degrees of freedom: 17.88
P-value: 0.0000
There is a significant difference between the click-through rates of Layout A and Layout B.


16.  A pharmaceutical company wants to determine if a new drug is more effective than an existing drug in
reducing cholesterol levels. Create a program to analyze the clinical trial data and calculate the tstatistic and p-value for the treatment effect.


Use the following data of cholestrol level:

```python

existing_drug_levels = [180, 182, 175, 185, 178, 176, 172, 184, 179, 183]

new_drug_levels = [170, 172, 165, 168, 175, 173, 170, 178, 172, 176]

In [19]:
import numpy as np
from scipy import stats

# Data: Cholesterol levels for existing and new drugs
existing_drug_levels = [180, 182, 175, 185, 178, 176, 172, 184, 179, 183]
new_drug_levels = [170, 172, 165, 168, 175, 173, 170, 178, 172, 176]

# Step 1: Calculate sample means and standard deviations
mean_existing = np.mean(existing_drug_levels)
mean_new = np.mean(new_drug_levels)

std_existing = np.std(existing_drug_levels, ddof=1)  # Sample standard deviation
std_new = np.std(new_drug_levels, ddof=1)  # Sample standard deviation

n_existing = len(existing_drug_levels)
n_new = len(new_drug_levels)

# Step 2: Calculate pooled standard error (SE)
SE = np.sqrt((std_existing**2 / n_existing) + (std_new**2 / n_new))

# Step 3: Calculate the t-statistic
t_statistic = (mean_existing - mean_new) / SE

# Step 4: Calculate degrees of freedom (using Welch's approximation)
df = ((std_existing**2 / n_existing + std_new**2 / n_new)**2) / \
     ((std_existing**2 / n_existing)**2 / (n_existing - 1) + (std_new**2 / n_new)**2 / (n_new - 1))

# Step 5: Calculate the p-value (one-tailed test)
p_value = stats.t.cdf(t_statistic, df)  # One-tailed test (since we are testing if the new drug is more effective)

# Output the results
print(f"Mean cholesterol level (Existing Drug): {mean_existing:.2f}")
print(f"Mean cholesterol level (New Drug): {mean_new:.2f}")
print(f"Standard deviation (Existing Drug): {std_existing:.2f}")
print(f"Standard deviation (New Drug): {std_new:.2f}")
print(f"t-statistic: {t_statistic:.4f}")
print(f"Degrees of freedom: {df:.2f}")
print(f"P-value: {p_value:.4f}")

# Step 6: Interpretation of results
if p_value < 0.05:
    print("The new drug is statistically more effective in reducing cholesterol levels.")
else:
    print("There is no statistically significant difference in cholesterol levels between the new and existing drugs.")


Mean cholesterol level (Existing Drug): 179.40
Mean cholesterol level (New Drug): 171.90
Standard deviation (Existing Drug): 4.22
Standard deviation (New Drug): 3.87
t-statistic: 4.1405
Degrees of freedom: 17.87
P-value: 0.9997
There is no statistically significant difference in cholesterol levels between the new and existing drugs.


17.   A school district introduces an educational intervention program to improve math scores. Write a Python
function to analyze pre- and post-intervention test scores, calculating the t-statistic and p-value to
determine if the intervention had a significant impact.


Use the following data of test score:


  ```python

  pre_intervention_scores = [80, 85, 90, 75, 88, 82, 92, 78, 85, 87]

  post_intervention_scores = [90, 92, 88, 92, 95, 91, 96, 93, 89, 93

In [20]:
import numpy as np
from scipy import stats

# Data: Cholesterol levels for existing and new drugs
existing_drug_levels = [180, 182, 175, 185, 178, 176, 172, 184, 179, 183]
new_drug_levels = [170, 172, 165, 168, 175, 173, 170, 178, 172, 176]

# Step 1: Calculate sample means and standard deviations
mean_existing = np.mean(existing_drug_levels)
mean_new = np.mean(new_drug_levels)

std_existing = np.std(existing_drug_levels, ddof=1)  # Sample standard deviation
std_new = np.std(new_drug_levels, ddof=1)  # Sample standard deviation

n_existing = len(existing_drug_levels)
n_new = len(new_drug_levels)

# Step 2: Calculate pooled standard error (SE)
SE = np.sqrt((std_existing**2 / n_existing) + (std_new**2 / n_new))

# Step 3: Calculate the t-statistic
t_statistic = (mean_existing - mean_new) / SE

# Step 4: Calculate degrees of freedom (using Welch's approximation)
df = ((std_existing**2 / n_existing + std_new**2 / n_new)**2) / \
     ((std_existing**2 / n_existing)**2 / (n_existing - 1) + (std_new**2 / n_new)**2 / (n_new - 1))

# Step 5: Calculate the p-value (one-tailed test)
p_value = stats.t.cdf(t_statistic, df)  # One-tailed test (since we are testing if the new drug is more effective)

# Output the results
print(f"Mean cholesterol level (Existing Drug): {mean_existing:.2f}")
print(f"Mean cholesterol level (New Drug): {mean_new:.2f}")
print(f"Standard deviation (Existing Drug): {std_existing:.2f}")
print(f"Standard deviation (New Drug): {std_new:.2f}")
print(f"t-statistic: {t_statistic:.4f}")
print(f"Degrees of freedom: {df:.2f}")
print(f"P-value: {p_value:.4f}")

# Step 6: Interpretation of results
if p_value < 0.05:
    print("The new drug is statistically more effective in reducing cholesterol levels.")
else:
    print("There is no statistically significant difference in cholesterol levels between the new and existing drugs.")


Mean cholesterol level (Existing Drug): 179.40
Mean cholesterol level (New Drug): 171.90
Standard deviation (Existing Drug): 4.22
Standard deviation (New Drug): 3.87
t-statistic: 4.1405
Degrees of freedom: 17.87
P-value: 0.9997
There is no statistically significant difference in cholesterol levels between the new and existing drugs.


18.   An HR department wants to investigate if there's a gender-based salary gap within the company. Develop
a program to analyze salary data, calculate the t-statistic, and determine if there's a statistically
significant difference between the average salaries of male and female employees.


Use the below code to generate synthetic data:


```python

# Generate synthetic salary data for male and female employees

np.random.seed(0)  # For reproducibility

male_salaries = np.random.normal(loc=50000, scale=10000, size=20)

female_salaries = np.random.normal(loc=55000, scale=9000, size=20)

In [21]:
import numpy as np
from scipy import stats

# Generate synthetic salary data for male and female employees
np.random.seed(0)  # For reproducibility

male_salaries = np.random.normal(loc=50000, scale=10000, size=20)
female_salaries = np.random.normal(loc=55000, scale=9000, size=20)

# Step 1: Calculate sample means and standard deviations
mean_male = np.mean(male_salaries)
mean_female = np.mean(female_salaries)

std_male = np.std(male_salaries, ddof=1)  # Sample standard deviation
std_female = np.std(female_salaries, ddof=1)  # Sample standard deviation

n_male = len(male_salaries)
n_female = len(female_salaries)

# Step 2: Calculate pooled standard error (SE)
SE = np.sqrt((std_male**2 / n_male) + (std_female**2 / n_female))

# Step 3: Calculate the t-statistic
t_statistic = (mean_male - mean_female) / SE

# Step 4: Calculate degrees of freedom (using Welch's approximation)
df = ((std_male**2 / n_male + std_female**2 / n_female)**2) / \
     ((std_male**2 / n_male)**2 / (n_male - 1) + (std_female**2 / n_female)**2 / (n_female - 1))

# Step 5: Calculate the p-value (two-tailed test)
p_value = 2 * (1 - stats.t.cdf(abs(t_statistic), df))  # Two-tailed test

# Output the results
print(f"Mean salary (Male): {mean_male:.2f}")
print(f"Mean salary (Female): {mean_female:.2f}")
print(f"Standard deviation (Male): {std_male:.2f}")
print(f"Standard deviation (Female): {std_female:.2f}")
print(f"t-statistic: {t_statistic:.4f}")
print(f"Degrees of freedom: {df:.2f}")
print(f"P-value: {p_value:.4f}")

# Step 6: Interpretation of results
if p_value < 0.05:
    print("There is a statistically significant difference in the average salaries of male and female employees.")
else:
    print("There is no statistically significant difference in the average salaries of male and female employees.")


Mean salary (Male): 55693.35
Mean salary (Female): 55501.75
Standard deviation (Male): 8722.69
Standard deviation (Female): 10968.10
t-statistic: 0.0611
Degrees of freedom: 36.17
P-value: 0.9516
There is no statistically significant difference in the average salaries of male and female employees.


19.   A manufacturer produces two different versions of a product and wants to compare their quality scores.
Create a Python function to analyze quality assessment data, calculate the t-statistic, and decide
whether there's a significant difference in quality between the two versions.


Use the following data:


```python

version1_scores = [85, 88, 82, 89, 87, 84, 90, 88, 85, 86, 91, 83, 87, 84, 89, 86, 84, 88, 85, 86, 89, 90, 87, 88, 85]

version2_scores = [80, 78, 83, 81, 79, 82, 76, 80, 78, 81, 77, 82, 80, 79, 82, 79, 80, 81, 79, 82, 79, 78, 80, 81, 82]

In [22]:
import numpy as np
from scipy import stats

# Data: Quality scores for Version 1 and Version 2
version1_scores = [85, 88, 82, 89, 87, 84, 90, 88, 85, 86, 91, 83, 87, 84, 89, 86, 84, 88, 85, 86, 89, 90, 87, 88, 85]
version2_scores = [80, 78, 83, 81, 79, 82, 76, 80, 78, 81, 77, 82, 80, 79, 82, 79, 80, 81, 79, 82, 79, 78, 80, 81, 82]

# Step 1: Calculate sample means and standard deviations
mean_version1 = np.mean(version1_scores)
mean_version2 = np.mean(version2_scores)

std_version1 = np.std(version1_scores, ddof=1)  # Sample standard deviation
std_version2 = np.std(version2_scores, ddof=1)  # Sample standard deviation

n_version1 = len(version1_scores)
n_version2 = len(version2_scores)

# Step 2: Calculate pooled standard error (SE)
SE = np.sqrt((std_version1**2 / n_version1) + (std_version2**2 / n_version2))

# Step 3: Calculate the t-statistic
t_statistic = (mean_version1 - mean_version2) / SE

# Step 4: Calculate degrees of freedom (using Welch's approximation)
df = ((std_version1**2 / n_version1 + std_version2**2 / n_version2)**2) / \
     ((std_version1**2 / n_version1)**2 / (n_version1 - 1) + (std_version2**2 / n_version2)**2 / (n_version2 - 1))

# Step 5: Calculate the p-value (two-tailed test)
p_value = 2 * (1 - stats.t.cdf(abs(t_statistic), df))  # Two-tailed test

# Output the results
print(f"Mean score (Version 1): {mean_version1:.2f}")
print(f"Mean score (Version 2): {mean_version2:.2f}")
print(f"Standard deviation (Version 1): {std_version1:.2f}")
print(f"Standard deviation (Version 2): {std_version2:.2f}")
print(f"t-statistic: {t_statistic:.4f}")
print(f"Degrees of freedom: {df:.2f}")
print(f"P-value: {p_value:.4f}")

# Step 6: Interpretation of results
if p_value < 0.05:
    print("There is a statistically significant difference in the quality scores between the two versions.")
else:
    print("There is no statistically significant difference in the quality scores between the two versions.")


Mean score (Version 1): 86.64
Mean score (Version 2): 79.96
Standard deviation (Version 1): 2.36
Standard deviation (Version 2): 1.77
t-statistic: 11.3258
Degrees of freedom: 44.47
P-value: 0.0000
There is a statistically significant difference in the quality scores between the two versions.


 20. A restaurant chain collects customer satisfaction scores for two different branches. Write a program to
analyze the scores, calculate the t-statistic, and determine if there's a statistically significant difference in
customer satisfaction between the branches.


Use the below data of scores:

  ```python

branch_a_scores = [4, 5, 3, 4, 5, 4, 5, 3, 4, 4, 5, 4, 4, 3, 4, 5, 5, 4, 3, 4, 5, 4, 3, 5, 4, 4, 5, 3, 4, 5, 4]

branch_b_scores = [3, 4, 2, 3, 4, 3, 4, 2, 3, 3, 4, 3, 3, 2, 3, 4, 4, 3, 2, 3, 4, 3, 2, 4, 3, 3, 4, 2, 3, 4, 3]

In [23]:
import numpy as np
from scipy import stats

# Data: Customer satisfaction scores for Branch A and Branch B
branch_a_scores = [4, 5, 3, 4, 5, 4, 5, 3, 4, 4, 5, 4, 4, 3, 4, 5, 5, 4, 3, 4, 5, 4, 3, 5, 4, 4, 5, 3, 4, 5, 4]
branch_b_scores = [3, 4, 2, 3, 4, 3, 4, 2, 3, 3, 4, 3, 3, 2, 3, 4, 4, 3, 2, 3, 4, 3, 2, 4, 3, 3, 4, 2, 3, 4, 3]

# Step 1: Calculate sample means and standard deviations
mean_a = np.mean(branch_a_scores)
mean_b = np.mean(branch_b_scores)

std_a = np.std(branch_a_scores, ddof=1)  # Sample standard deviation for Branch A
std_b = np.std(branch_b_scores, ddof=1)  # Sample standard deviation for Branch B

n_a = len(branch_a_scores)
n_b = len(branch_b_scores)

# Step 2: Calculate pooled standard error (SE)
SE = np.sqrt((std_a**2 / n_a) + (std_b**2 / n_b))

# Step 3: Calculate the t-statistic
t_statistic = (mean_a - mean_b) / SE

# Step 4: Calculate degrees of freedom (using Welch's approximation)
df = ((std_a**2 / n_a + std_b**2 / n_b)**2) / \
     ((std_a**2 / n_a)**2 / (n_a - 1) + (std_b**2 / n_b)**2 / (n_b - 1))

# Step 5: Calculate the p-value (two-tailed test)
p_value = 2 * (1 - stats.t.cdf(abs(t_statistic), df))  # Two-tailed test

# Output the results
print(f"Mean score (Branch A): {mean_a:.2f}")
print(f"Mean score (Branch B): {mean_b:.2f}")
print(f"Standard deviation (Branch A): {std_a:.2f}")
print(f"Standard deviation (Branch B): {std_b:.2f}")
print(f"t-statistic: {t_statistic:.4f}")
print(f"Degrees of freedom: {df:.2f}")
print(f"P-value: {p_value:.4f}")

# Step 6: Interpretation of results
if p_value < 0.05:
    print("There is a statistically significant difference in customer satisfaction between Branch A and Branch B.")
else:
    print("There is no statistically significant difference in customer satisfaction between Branch A and Branch B.")


Mean score (Branch A): 4.13
Mean score (Branch B): 3.13
Standard deviation (Branch A): 0.72
Standard deviation (Branch B): 0.72
t-statistic: 5.4801
Degrees of freedom: 60.00
P-value: 0.0000
There is a statistically significant difference in customer satisfaction between Branch A and Branch B.


21..A political analyst wants to determine if there is a significant association between age groups and voter
preferences (Candidate A or Candidate B). They collect data from a sample of 500 voters and classify
them into different age groups and candidate preferences. Perform a Chi-Square test to determine if
there is a significant association between age groups and voter preferences.


Use the below code to generate data:

```python

np.random.seed(0)

age_groups = np.random.choice([ 18 30 , 31 50 , 51+', 51+'], size=30)

voter_preferences = np.random.choice(['Candidate A', 'Candidate B'], size=30)

In [24]:
import numpy as np
import pandas as pd
from scipy.stats import chi2_contingency

# Step 1: Generate synthetic data
np.random.seed(0)

# Simulating 30 voters with age groups and preferences
age_groups = np.random.choice(['18-30', '31-50', '51+'], size=30)
voter_preferences = np.random.choice(['Candidate A', 'Candidate B'], size=30)

# Step 2: Create a contingency table
data = pd.crosstab(age_groups, voter_preferences, margins=False)

# Step 3: Perform the Chi-Square test of independence
chi2, p_value, dof, expected = chi2_contingency(data)

# Step 4: Output the results
print("Contingency Table:")
print(data)
print("\nChi-Square Statistic:", chi2)
print("Degrees of Freedom:", dof)
print("Expected Frequencies Table:")
print(expected)
print("P-value:", p_value)

# Step 5: Interpretation of results
if p_value < 0.05:
    print("\nThere is a significant association between age groups and voter preferences.")
else:
    print("\nThere is no significant association between age groups and voter preferences.")


Contingency Table:
col_0  Candidate A  Candidate B
row_0                          
18-30            4            8
31-50            6            5
51+              4            3

Chi-Square Statistic: 1.4401669758812612
Degrees of Freedom: 2
Expected Frequencies Table:
[[5.6        6.4       ]
 [5.13333333 5.86666667]
 [3.26666667 3.73333333]]
P-value: 0.48671161971286614

There is no significant association between age groups and voter preferences.


 22. A company conducted a customer satisfaction survey to determine if there is a significant relationship
between product satisfaction levels (Satisfied, Neutral, Dissatisfied) and the region where customers are
located (East, West, North, South). The survey data is summarized in a contingency table. Conduct a ChiSquare test to determine if there is a significant relationship between product satisfaction levels and
customer regions.


Sample data:

```python

#Sample data: Product satisfaction levels (rows) vs. Customer regions (columns)

data = np.array([[50, 30, 40, 20], [30, 40, 30, 50], [20, 30, 40, 30]])

In [25]:
import numpy as np
from scipy.stats import chi2_contingency

# Sample data: Product satisfaction levels (rows) vs. Customer regions (columns)
# Rows represent satisfaction levels: Satisfied, Neutral, Dissatisfied
# Columns represent customer regions: East, West, North, South
data = np.array([[50, 30, 40, 20], [30, 40, 30, 50], [20, 30, 40, 30]])

# Step 1: Perform the Chi-Square test of independence
chi2_stat, p_value, dof, expected = chi2_contingency(data)

# Step 2: Output the results
print("Observed Data:")
print(data)
print("\nChi-Square Statistic:", chi2_stat)
print("Degrees of Freedom:", dof)
print("Expected Frequencies Table:")
print(expected)
print("P-value:", p_value)

# Step 3: Interpretation of results
if p_value < 0.05:
    print("\nThere is a significant relationship between product satisfaction levels and customer regions.")
else:
    print("\nThere is no significant relationship between product satisfaction levels and customer regions.")


Observed Data:
[[50 30 40 20]
 [30 40 30 50]
 [20 30 40 30]]

Chi-Square Statistic: 27.777056277056275
Degrees of Freedom: 6
Expected Frequencies Table:
[[34.14634146 34.14634146 37.56097561 34.14634146]
 [36.58536585 36.58536585 40.24390244 36.58536585]
 [29.26829268 29.26829268 32.19512195 29.26829268]]
P-value: 0.00010349448486004387

There is a significant relationship between product satisfaction levels and customer regions.


 23. A company implemented an employee training program to improve job performance (Effective, Neutral,
Ineffective). After the training, they collected data from a sample of employees and classified them based
on their job performance before and after the training. Perform a Chi-Square test to determine if there is a
significant difference between job performance levels before and after the training.


Sample data:

```python

# Sample data: Job performance levels before (rows) and after (columns) training

data = np.array([[50, 30, 20], [30, 40, 30], [20, 30, 40]])

In [26]:
import numpy as np
from scipy.stats import chi2_contingency

# Sample data: Job performance levels before (rows) and after (columns) training
# Rows: Before training (Effective, Neutral, Ineffective)
# Columns: After training (Effective, Neutral, Ineffective)
data = np.array([[50, 30, 20], [30, 40, 30], [20, 30, 40]])

# Step 1: Perform the Chi-Square test of independence
chi2_stat, p_value, dof, expected = chi2_contingency(data)

# Step 2: Output the results
print("Observed Data:")
print(data)
print("\nChi-Square Statistic:", chi2_stat)
print("Degrees of Freedom:", dof)
print("Expected Frequencies Table:")
print(expected)
print("P-value:", p_value)

# Step 3: Interpretation of results
if p_value < 0.05:
    print("\nThere is a significant difference in job performance levels before and after training.")
else:
    print("\nThere is no significant difference in job performance levels before and after training.")


Observed Data:
[[50 30 20]
 [30 40 30]
 [20 30 40]]

Chi-Square Statistic: 22.161728395061726
Degrees of Freedom: 4
Expected Frequencies Table:
[[34.48275862 34.48275862 31.03448276]
 [34.48275862 34.48275862 31.03448276]
 [31.03448276 31.03448276 27.93103448]]
P-value: 0.00018609719479882557

There is a significant difference in job performance levels before and after training.


 24. A company produces three different versions of a product: Standard, Premium, and Deluxe. The
company wants to determine if there is a significant difference in customer satisfaction scores among the
three product versions. They conducted a survey and collected customer satisfaction scores for each
version from a random sample of customers. Perform an ANOVA test to determine if there is a significant
difference in customer satisfaction scores.


  Use the following data:

  ```python

  # Sample data: Customer satisfaction scores for each product version

  standard_scores = [80, 85, 90, 78, 88, 82, 92, 78, 85, 87]

  premium_scores = [90, 92, 88, 92, 95, 91, 96, 93, 89, 93]

  deluxe_scores = [95, 98, 92, 97, 96, 94, 98, 97, 92, 99]

In [27]:
import numpy as np
from scipy.stats import f_oneway

# Sample data: Customer satisfaction scores for each product version
standard_scores = [80, 85, 90, 78, 88, 82, 92, 78, 85, 87]
premium_scores = [90, 92, 88, 92, 95, 91, 96, 93, 89, 93]
deluxe_scores = [95, 98, 92, 97, 96, 94, 98, 97, 92, 99]

# Step 1: Perform the One-Way ANOVA test
f_stat, p_value = f_oneway(standard_scores, premium_scores, deluxe_scores)

# Step 2: Output the results
print("F-statistic:", f_stat)
print("P-value:", p_value)

# Step 3: Interpretation of results
if p_value < 0.05:
    print("\nThere is a significant difference in customer satisfaction scores among the product versions.")
else:
    print("\nThere is no significant difference in customer satisfaction scores among the product versions.")


F-statistic: 27.03556231003039
P-value: 3.5786328857349003e-07

There is a significant difference in customer satisfaction scores among the product versions.
