DATA SCIENCE AND ANALYSIS

In [1]:
#DATA SCIENCE AND ANALYSIS IS USED FOR SOLVING BUSINESS PROBLEMS
#STEPS TO FOLLOW
#1.GET INFORMATION ABOUT THE BUSINESS OR ORGAISATION
#2.KNOW THE PROBLEM AT HAND
#3.GETTING THE RIGHT DATA
###EDA - EXPLORATORY DATA ANALYSIS
#1 DATA CLEANING
#2.DATA TRANSFORMATION
#3.DISCREPTIVE ANALYSIS(PYTHON,POWERBI,TABLEAU)
#4.DATA VISUALIZATION
###MACHINE LEARNING (PYHTON)(LINEAR REGRESSON,BINARY CLASSIFICATION,MULTICLASSIFICATION,CLUSTERING
# TEXT OR SENTIMENT ANALYSIS)
#1.PREPROCESSING
#2.MODEL BUILDING
#3.EVALUATION (VERIFICATION)
#4.MODEL DEVELOPEMENT
###DEEP LEARNING


In [2]:
#NUMPY : used for numerical operation done in array(array accepts only one data type)
import numpy as np
print(dir(np))


['False_', 'ScalarType', 'True_', '_CopyMode', '_NoValue', '__NUMPY_SETUP__', '__all__', '__array_api_version__', '__array_namespace_info__', '__builtins__', '__cached__', '__config__', '__dir__', '__doc__', '__expired_attributes__', '__file__', '__former_attrs__', '__future_scalars__', '__getattr__', '__loader__', '__name__', '__numpy_submodules__', '__package__', '__path__', '__spec__', '__version__', '_array_api_info', '_core', '_distributor_init', '_expired_attrs_2_0', '_get_promotion_state', '_globals', '_int_extended_msg', '_mat', '_msg', '_no_nep50_warning', '_pyinstaller_hooks_dir', '_pytesttester', '_set_promotion_state', '_specific_msg', '_type_info', '_typing', '_utils', 'abs', 'absolute', 'acos', 'acosh', 'add', 'all', 'allclose', 'amax', 'amin', 'angle', 'any', 'append', 'apply_along_axis', 'apply_over_axes', 'arange', 'arccos', 'arccosh', 'arcsin', 'arcsinh', 'arctan', 'arctan2', 'arctanh', 'argmax', 'argmin', 'argpartition', 'argsort', 'argwhere', 'around', 'array', 'arr

In [3]:
##AN ARRAY IS USED FOR STORING DATA IN ROWS AND COLUMNS
array1 = np.array([75,85,60,47])
array1

array([75, 85, 60, 47])

In [4]:
array1.ndim # checking the number of an array dimension

1

In [5]:
array1.shape # to check the shape of an array linear array

(4,)

In [6]:
array1.dtype # to check th data type of an array

dtype('int64')

In [7]:
array2 = np.array([[47,85,69,60],[80,85,64,90]])
arr2=np.array([[10,29,30,49,40,29],[80,90,12,34,59,90]])
arr2
array2

array([[47, 85, 69, 60],
       [80, 85, 64, 90]])

In [8]:
array2.ndim
arr2.ndim

2

In [9]:
array2.dtype
arr2.dtype

dtype('int64')

In [10]:
array2.shape #matrix
arr2.shape

(2, 6)

NUMPY ARRAY


In [11]:
#creating an array where all values are zero
np.zeros(20)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [12]:
np.zeros((4,5,))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
#creating an array where all values are 1

In [14]:
np.ones(30)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [15]:
np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [16]:
np.ones((5,6)) *15

array([[15., 15., 15., 15., 15., 15.],
       [15., 15., 15., 15., 15., 15.],
       [15., 15., 15., 15., 15., 15.],
       [15., 15., 15., 15., 15., 15.],
       [15., 15., 15., 15., 15., 15.]])

LIN SPACE

In [17]:
#USED FOR generating an arrays that are evenely spaced,the codition requires to set an interval.

In [18]:
np.linspace (20,70)

array([20.        , 21.02040816, 22.04081633, 23.06122449, 24.08163265,
       25.10204082, 26.12244898, 27.14285714, 28.16326531, 29.18367347,
       30.20408163, 31.2244898 , 32.24489796, 33.26530612, 34.28571429,
       35.30612245, 36.32653061, 37.34693878, 38.36734694, 39.3877551 ,
       40.40816327, 41.42857143, 42.44897959, 43.46938776, 44.48979592,
       45.51020408, 46.53061224, 47.55102041, 48.57142857, 49.59183673,
       50.6122449 , 51.63265306, 52.65306122, 53.67346939, 54.69387755,
       55.71428571, 56.73469388, 57.75510204, 58.7755102 , 59.79591837,
       60.81632653, 61.83673469, 62.85714286, 63.87755102, 64.89795918,
       65.91836735, 66.93877551, 67.95918367, 68.97959184, 70.        ])

eye creates a two dimentional array

In [5]:
##it will put 1 in dignal and 0 in surrounding
np.eye(10)
#np.eye(20)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [20]:
# arange-range of array
array4 = np.arange(1,101)
array4

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [21]:
array4 = np.arange(1,101,7) ##taking step before the next value
array4

array([ 1,  8, 15, 22, 29, 36, 43, 50, 57, 64, 71, 78, 85, 92, 99])

In [22]:
array5 = np.random.randint(15,105,)
array5

62

In [23]:
array5 = np.random.randint(15,105,100) # START,END,TOTAL NO GENERATED
array5

array([ 57,  94,  25,  49, 104,  44,  58, 100,  20,  16,  42,  88,  25,
        37,  36,  86,  34,  98,  30,  82,  44,  30,  40,  88,  63,  52,
        36,  63,  41,  20,  79, 100,  86,  37,  51,  98,  95,  67,  66,
        83,  58,  76,  60,  30,  16,  99,  84, 100,  91,  71, 100,  42,
        18,  71,  84,  85,  85,  72,  89,  60,  92,  82,  67,  77,  70,
        98,  73,  40,  64,  21,  16,  79,  80,  39,  56,  68,  88,  17,
        58,  39,  33,  33, 100,  63,  17,  81,  49,  48,  51, 101,  60,
        31,  66,  34,  40,  79,  73,  62,  40,  59], dtype=int32)

In [24]:
np.random.seed(5)
array5 = np.random.randint(15,105,100)
array5

array([ 93,  76,  31,  88,  23,  77,  42,  45,  95,  22,  91,  30,  68,
        95,  42,  59,  92,  90,  80,  62,  45,  99, 101,  33,  24,  56,
        77,  16,  97,  31,  93,  20,  73,  15,  95,  19,  51,  66,  42,
        46,  17,  83,  53,  98,  34,  33,  22,  45,  77,  26,  82,  80,
        70,  18,  93,  42,  44,  48, 104, 100,  22,  31,  29,  46,  24,
        53,  62,  31,  20,  49,  60,  74,  39,  28,  46,  47,  91,  59,
        20,  29,  62,  97,  15,  22, 101,  31,  79,  23,  59,  52,  90,
        20,  37,  67,  84,  97,  75,  44, 103,  94], dtype=int32)

In [25]:
#converting 1 dimention array to 2 dimention array
array6 =array5.reshape(10,10)
array6

array([[ 93,  76,  31,  88,  23,  77,  42,  45,  95,  22],
       [ 91,  30,  68,  95,  42,  59,  92,  90,  80,  62],
       [ 45,  99, 101,  33,  24,  56,  77,  16,  97,  31],
       [ 93,  20,  73,  15,  95,  19,  51,  66,  42,  46],
       [ 17,  83,  53,  98,  34,  33,  22,  45,  77,  26],
       [ 82,  80,  70,  18,  93,  42,  44,  48, 104, 100],
       [ 22,  31,  29,  46,  24,  53,  62,  31,  20,  49],
       [ 60,  74,  39,  28,  46,  47,  91,  59,  20,  29],
       [ 62,  97,  15,  22, 101,  31,  79,  23,  59,  52],
       [ 90,  20,  37,  67,  84,  97,  75,  44, 103,  94]], dtype=int32)

In [26]:
array6[4,4]

np.int32(34)

In [27]:
#selecting range of values from 2 dimentional array using index location start to stop
array6[3:7,3:6]

array([[15, 95, 19],
       [98, 34, 33],
       [18, 93, 42],
       [46, 24, 53]], dtype=int32)

In [28]:
array6[3:7,3:6] =100 #broadcasting is distriputing values over selected places
array6

array([[ 93,  76,  31,  88,  23,  77,  42,  45,  95,  22],
       [ 91,  30,  68,  95,  42,  59,  92,  90,  80,  62],
       [ 45,  99, 101,  33,  24,  56,  77,  16,  97,  31],
       [ 93,  20,  73, 100, 100, 100,  51,  66,  42,  46],
       [ 17,  83,  53, 100, 100, 100,  22,  45,  77,  26],
       [ 82,  80,  70, 100, 100, 100,  44,  48, 104, 100],
       [ 22,  31,  29, 100, 100, 100,  62,  31,  20,  49],
       [ 60,  74,  39,  28,  46,  47,  91,  59,  20,  29],
       [ 62,  97,  15,  22, 101,  31,  79,  23,  59,  52],
       [ 90,  20,  37,  67,  84,  97,  75,  44, 103,  94]], dtype=int32)

In [29]:
array7 = array6.flatten() #to return 2 dimention array to 1 dimention
array7

array([ 93,  76,  31,  88,  23,  77,  42,  45,  95,  22,  91,  30,  68,
        95,  42,  59,  92,  90,  80,  62,  45,  99, 101,  33,  24,  56,
        77,  16,  97,  31,  93,  20,  73, 100, 100, 100,  51,  66,  42,
        46,  17,  83,  53, 100, 100, 100,  22,  45,  77,  26,  82,  80,
        70, 100, 100, 100,  44,  48, 104, 100,  22,  31,  29, 100, 100,
       100,  62,  31,  20,  49,  60,  74,  39,  28,  46,  47,  91,  59,
        20,  29,  62,  97,  15,  22, 101,  31,  79,  23,  59,  52,  90,
        20,  37,  67,  84,  97,  75,  44, 103,  94], dtype=int32)

statistics in array

In [30]:
np.sum(array7) ##sum

np.int64(6311)

In [31]:
np.max(array7) ##maximum

np.int32(104)

In [32]:
np.min(array7)

np.int32(15)

In [33]:
np.mean(array7)

np.float64(63.11)

In [34]:
np.median(array7)

np.float64(62.0)

In [35]:
np.percentile(array7,50) # to check the percentage

np.float64(62.0)

In [36]:
np.argmax(array7) #to located the first maximum value

np.int64(58)

understanding data analysis and visual representation

In [37]:
#1.DOMAIN KNOWLEDGE
#2.COMMUNICATION SKILSS
#3.PROBLEM-SOLVING AND CRITICAL THINKING
#4.COLLABORATION AND TEAMWORK
#5.ETHICS AND DATA PRIVACY
#6.PROJECT MANAGEMENT
#7.BUSINESS ACUMEN
#8. ADAPTABILITY AND CONTINUOUS LEARNING
#9. THE ART OF COMMUNICATION
#10.TAILORING COMMNICATION TO YOUR AUDIENCE
#11.PERSUASIVE COMMUNICATION
#12.MASTERING VISUALIZATION TOOLS
#13.CHOOSING RIGHT COLORS
#14.CHOOSING THE RIGHT VISUALS
#15.DESIGN PRINCIPLES
#16.DATA STORYTELLING AND CONTEXT
#17. USING DASHBOARD EFFECTIVLY
#18.INFOGRAPHICS AND INTERACTIVE REPORTS
#19.SIMPLfYING COMPLEX DATA
#20.