1. How to Creating a 3x3 Identity Matrix with Float Data Type?

To create a 3x3 identity matrix with a float data type, you can use the function eye() of NumPy library. For example,

In [ ]:
import numpy as np

arr = np.eye(3, dtype=float)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


2. Create a 1D Array with Random Values between 0 and 1.

In [ ]:
import numpy as np

arr = np.random.rand(5)
print(arr)

[0.49811089 0.10261537 0.19805584 0.13105878 0.96704152]


3. Create a 2D Array with Random Integer Values.

In [ ]:
import numpy as np

arr = np.random.randint(0, 11, size=(3, 4))
print(arr)

[[1 1 9 4]
 [0 7 2 6]
 [5 8 6 0]]


4. Creating an Array Using a Custom Function.

In [ ]:
import numpy as np

def custom_function(x):
    return x**2

array_size = 5
arr = np.array([custom_function(i) for i in range(array_size)])
print(arr)

[ 0  1  4  9 16]


5. Reshaping a 1D Array into a 2D Array

In [ ]:
import numpy as np

array_1d = np.arange(12)
print("1D Array:")
print(array_1d)

array_2d = array_1d.reshape(3, 4)
print("\nReshaped 2D Array:")
print(array_2d)

1D Array:
[ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped 2D Array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


6. How to Creating a 3x3 Array of Ones?

You can create a 3x3 array of ones using the ones() function of NumPy library. For example,

In [ ]:
import numpy as np

ones_array = np.ones((3, 3))
print(ones_array)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


7. How to get the common items between two pythons
NumPy? Input:
a = np. array ([1,2,3,2,3,4,3,4,5,6])
b = np. array ([7,2,10,2,7,4,9,4,9,8])
Expected Output:
array ([2, 4])

You can find the common items between two NumPy arrays using the 'np.intersect1d' function. This function efficiently finds the intersection of the two arrays, returning only the unique common elements. For example,

In [ ]:
import numpy as np

a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])

common_items = np.intersect1d(a, b)
print(common_items)

[2 4]


8. From array a remove all items present in
array b Input:
a = np. array ([1,2,3,4,5])
b = np. array ([5,6,7,8,9])
Expected Output:
array ([1,2,3,4]

In [ ]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])
b = np.array([5, 6, 7, 8, 9])

result = np.setdiff1d(a, b)
print(result)

[1 2 3 4]


9. Limit the number of items printed in python NumPy array a to a maximum of
6 elements.
a = np. arrange (15)
Expected Output:
array ([ 0, 1, 2, ..., 12, 13, 14]

In [ ]:
import numpy as np

a = np.arange(15)
print(a[:6])

[0 1 2 3 4 5]


10. Drop all nan values from a 1D NumPy
array Input:
np. array ([1,2,3, np.nan,5,6,7, np.nan])
Desired Output:
array ([ 1., 2., 3., 5., 6., 7.])

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, np.nan, 5, 6, 7, np.nan])

new_arr = arr[~np.isnan(arr)]
print(new_arr)

[1. 2. 3. 5. 6. 7.]


11. Question: Create a 1D NumPy array of the first 20 natural numbers and a
2D NumPy array of shape (4, 5) with values ranging from 1 to 20.

In [ ]:
import numpy as np

array_1d = np.arange(1, 21)
print("1D array:")
print(array_1d)

array_2d = np.arange(1, 21).reshape(4, 5)
print("\n2D array:")
print(array_2d)

1D array:
[ 1  2  3 ... 18 19 20]

2D array:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


12. Question: Given a 3D NumPy array of shape (2, 3, 4), find its shape, size,
number of dimensions, and data type. Change its data type to float64 and verify
the change.

In [ ]:
import numpy as np

array_3d = np.arange(24).reshape(2, 3, 4)

shape = array_3d.shape
size = array_3d.size
num_dimensions = array_3d.ndim
data_type = array_3d.dtype

print("Original properties:")
print(f"Shape: {shape}")
print(f"Size: {size}")
print(f"Number of dimensions: {num_dimensions}")
print(f"Data type: {data_type}")

array_3d_float = array_3d.astype(np.float64)

new_data_type = array_3d_float.dtype

print("\nAfter changing data type to float64:")
print(f"New data type: {new_data_type}")

Original properties:
Shape: (2, 3, 4)
Size: 24
Number of dimensions: 3
Data type: int64

After changing data type to float64:
New data type: float64


13. Question: Reshape a 1D array of 12 elements into a 3x4 2D array and then
flatten it back into a 1D array using ravel (). Verify that the flattened array
matches the original.

In [ ]:
import numpy as np

original_array = np.arange(12)
print("Original array:")
print(original_array)

reshaped_array = original_array.reshape(3, 4)
print("\nReshaped array (3x4):")
print(reshaped_array)

flattened_array = reshaped_array.ravel()
print("\nFlattened array:")
print(flattened_array)

is_match = np.array_equal(original_array, flattened_array)
print("\nDoes the flattened array match the original array?")
print(is_match)

Original array:
[ 0  1  2 ...  9 10 11]

Reshaped array (3x4):
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Flattened array:
[ 0  1  2 ...  9 10 11]

Does the flattened array match the original array?
True


14. Question: Given two arrays, a = np. array ([1, 2, 3]) and b = np. array ([4,
5, 6]), perform element-wise addition, subtraction, multiplication, and
division. Explain the behavior when dividing by zero.

In [28]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

addition = a + b
subtraction = a - b
multiplication = a * b
division = a / b

a_with_zero = np.array([1, 0, 3])
b_with_zero = np.array([4, 5, 0])
division_with_zero = a_with_zero / b_with_zero

print("Element-wise addition:")
print(addition)

print("\nElement-wise subtraction:")
print(subtraction)

print("\nElement-wise multiplication:")
print(multiplication)

print("\nElement-wise division:")
print(division)

print("\nElement-wise division with zero:")
print(division_with_zero)

print("\nExplanation of division by zero behavior:")
print("When dividing by zero, NumPy generates 'inf' (infinity) or 'nan' (not a number) values.")

Element-wise addition:
[5 7 9]

Element-wise subtraction:
[-3 -3 -3]

Element-wise multiplication:
[ 4 10 18]

Element-wise division:
[0.25 0.4  0.5 ]

Element-wise division with zero:
[0.25 0.    inf]

Explanation of division by zero behavior:
When dividing by zero, NumPy generates 'inf' (infinity) or 'nan' (not a number) values.


<ipython-input-28-c65b8b373b5e>:13: RuntimeWarning: divide by zero encountered in divide
  division_with_zero = a_with_zero / b_with_zero


15. Question: Create a 2D array of shape (3, 1) and a 1D array of length 3. Perform
element-wise addition using broadcasting. Explain how broadcasting rules apply
in this scenario.

In [29]:
import numpy as np

array_2d = np.array([[1], [2], [3]])
print("2D array (shape (3, 1)):")
print(array_2d)

array_1d = np.array([4, 5, 6])
print("\n1D array (length 3):")
print(array_1d)

result = array_2d + array_1d
print("\nResult of element-wise addition with broadcasting:")
print(result)

2D array (shape (3, 1)):
[[1]
 [2]
 [3]]

1D array (length 3):
[4 5 6]

Result of element-wise addition with broadcasting:
[[5 6 7]
 [6 7 8]
 [7 8 9]]


16. Question: Generate a random 2D array of integers between 0 and 10. Use conditional operators to create a Boolean mask identifying elements greater than 5. Replace all elements greater than 5 with the value 5.

In [30]:
import numpy as np

np.random.seed(0)
array_2d = np.random.randint(0, 11, size=(4, 5))

print("Original array:")
print(array_2d)

mask = array_2d > 5

array_2d[mask] = 5

print("\nArray after replacing elements greater than 5 with 5:")
print(array_2d)

Original array:
[[ 5  0  3  3  7]
 [ 9  3  5  2  4]
 [ 7  6  8  8 10]
 [ 1  6  7  7  8]]

Array after replacing elements greater than 5 with 5:
[[5 0 3 3 5]
 [5 3 5 2 4]
 [5 5 5 5 5]
 [1 5 5 5 5]]


17. Question: Given a 4x4 array of random integers, use indexing and slicing
to extract:
o The entire second row
o The last column
o The subarray consisting of the first two rows and first two columns

In [31]:
import numpy as np

np.random.seed(0)  # For reproducibility
array_4x4 = np.random.randint(0, 11, size=(4, 4))

print("Original 4x4 array:")
print(array_4x4)

second_row = array_4x4[1, :]

last_column = array_4x4[:, -1]

subarray = array_4x4[:2, :2]

print("\nEntire second row:")
print(second_row)

print("\nLast column:")
print(last_column)

print("\nSubarray consisting of the first two rows and first two columns:")
print(subarray)

Original 4x4 array:
[[ 5  0  3  3]
 [ 7  9  3  5]
 [ 2  4  7  6]
 [ 8  8 10  1]]

Entire second row:
[7 9 3 5]

Last column:
[3 5 6 1]

Subarray consisting of the first two rows and first two columns:
[[5 0]
 [7 9]]


18. Question: Describe a practical example where NumPy can be used in EDA,
AI, ML, and DL, and implement a NumPy solution for a simple task in each
area.

Exploratory Data Analysis (EDA)
Example: Calculating basic statistics such as the mean, median, and standard deviation of a dataset to understand its distribution.

NumPy Solution:

In [32]:
import numpy as np

data = np.array([23, 45, 12, 67, 34, 89, 56, 43, 29, 31])

mean = np.mean(data)
median = np.median(data)
std_dev = np.std(data)

print("Mean:", mean)
print("Median:", median)
print("Standard Deviation:", std_dev)

Mean: 42.9
Median: 38.5
Standard Deviation: 21.556669501571896


Artificial Intelligence (AI)
Example: Performing basic operations for feature engineering, such as normalizing data for AI algorithms.

NumPy Solution:

In [33]:
import numpy as np

features = np.array([160, 170, 165, 180, 175])

normalized_features = (features - np.min(features)) / (np.max(features) - np.min(features))
print("Normalized Features:", normalized_features)

Normalized Features: [0.   0.5  0.25 1.   0.75]


Machine Learning (ML)
Example: Implementing a simple linear regression model by calculating the line of best fit.

NumPy Solution:

In [34]:
import numpy as np

hours = np.array([1, 2, 3, 4, 5])
scores = np.array([10, 20, 30, 40, 50])

A = np.vstack([hours, np.ones(len(hours))]).T
slope, intercept = np.linalg.lstsq(A, scores, rcond=None)[0]

print("Slope:", slope)
print("Intercept:", intercept)

Slope: 9.999999999999998
Intercept: 7.503577039457583e-16


Deep Learning (DL)
Example: Handling data preprocessing for a neural network by reshaping and normalizing images.

NumPy Solution:

In [35]:
import numpy as np

image = np.array([[255, 128, 64],
                  [0, 255, 128],
                  [64, 0, 255]])

flattened_image = image.flatten()

normalized_image = flattened_image / 255.0

print("Flattened Image:", flattened_image)
print("Normalized Image:", normalized_image)

Flattened Image: [255 128  64 ...  64   0 255]
Normalized Image: [1.         0.50196078 0.25098039 ... 0.25098039 0.         1.        ]


19. Question: Create a random 4x4 matrix and use NumPy to compute its
eigenvalues and eigenvectors. Verify the eigenvalues by reconstructing the
matrix.

In [36]:
import numpy as np

np.random.seed(0)
matrix = np.random.rand(4, 4)

print("Original Matrix:")
print(matrix)

eigenvalues, eigenvectors = np.linalg.eig(matrix)

print("\nEigenvalues:")
print(eigenvalues)

print("\nEigenvectors:")
print(eigenvectors)

reconstructed_matrix = eigenvectors @ np.diag(eigenvalues) @ np.linalg.inv(eigenvectors)

print("\nReconstructed Matrix:")
print(reconstructed_matrix)

print("\nIs the reconstructed matrix close to the original matrix?")
print(np.allclose(matrix, reconstructed_matrix))

Original Matrix:
[[0.5488135  0.71518937 0.60276338 0.54488318]
 [0.4236548  0.64589411 0.43758721 0.891773  ]
 [0.96366276 0.38344152 0.79172504 0.52889492]
 [0.56804456 0.92559664 0.07103606 0.0871293 ]]

Eigenvalues:
[ 2.28158836 -0.5139378  -0.22422772  0.53013911]

Eigenvectors:
[[ 0.52354106 -0.10090767  0.5285094  -0.1584302 ]
 [ 0.49196427  0.55773542 -0.43250014  0.36386336]
 [ 0.59384504  0.23102177 -0.57357157 -0.81262442]
 [ 0.36224851 -0.79080831  0.45236832  0.42678435]]

Reconstructed Matrix:
[[0.5488135  0.71518937 0.60276338 0.54488318]
 [0.4236548  0.64589411 0.43758721 0.891773  ]
 [0.96366276 0.38344152 0.79172504 0.52889492]
 [0.56804456 0.92559664 0.07103606 0.0871293 ]]

Is the reconstructed matrix close to the original matrix?
True


20. Question: Create a 1D array of 27 elements and reshape it into a 3x3x3
3D array. Flatten it back into a 1D array and compare the flattened array
with the original.

In [37]:
import numpy as np

original_array = np.arange(27)

print("Original 1D array:")
print(original_array)

reshaped_array = original_array.reshape(3, 3, 3)

print("\nReshaped 3x3x3 array:")
print(reshaped_array)

flattened_array = reshaped_array.ravel()

print("\nFlattened array:")
print(flattened_array)

is_match = np.array_equal(original_array, flattened_array)

print("\nDoes the flattened array match the original array?")
print(is_match)

Original 1D array:
[ 0  1  2 ... 24 25 26]

Reshaped 3x3x3 array:
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]

Flattened array:
[ 0  1  2 ... 24 25 26]

Does the flattened array match the original array?
True


21. Question: Perform matrix multiplication of two 2D arrays using np.dot ()
and @. Compare the results and performance of both methods using a large
dataset.

In [38]:
import numpy as np
import time

A = np.random.rand(500, 500)
B = np.random.rand(500, 500)

start_time = time.time()
result_dot = np.dot(A, B)
end_time = time.time()
time_dot = end_time - start_time

start_time = time.time()
result_at = A @ B
end_time = time.time()
time_at = end_time - start_time

results_match = np.allclose(result_dot, result_at)

print("Do the results match?")
print(results_match)

print("\nTime taken by np.dot():", time_dot)
print("Time taken by @ operator:", time_at)

Do the results match?
True

Time taken by np.dot(): 0.010680437088012695
Time taken by @ operator: 0.009850263595581055


22. Question: Create a 3D array of shape (2, 1, 4) and a 2D array of shape (4,
1). Perform an element-wise operation using broadcasting and explain the
result. Use np. new axis to achieve the same result without broadcasting.

In [39]:
import numpy as np

array_3d = np.array([[[1, 2, 3, 4]],
                     [[5, 6, 7, 8]]])

print("3D Array (shape (2, 1, 4)):")
print(array_3d)

array_2d = np.array([[10],
                     [20],
                     [30],
                     [40]])

print("\n2D Array (shape (4, 1)):")
print(array_2d)

result_broadcast = array_3d + array_2d.T

print("\nResult using broadcasting:")
print(result_broadcast)

array_2d_newaxis = array_2d.reshape(1, 4, 1)
result_newaxis = array_3d + array_2d_newaxis

print("\nResult using np.newaxis:")
print(result_newaxis)

print("\nDo the results match?")
print(np.allclose(result_broadcast, result_newaxis))

3D Array (shape (2, 1, 4)):
[[[1 2 3 4]]

 [[5 6 7 8]]]

2D Array (shape (4, 1)):
[[10]
 [20]
 [30]
 [40]]

Result using broadcasting:
[[[11 22 33 44]]

 [[15 26 37 48]]]

Result using np.newaxis:
[[[11 12 13 14]
  [21 22 23 24]
  [31 32 33 34]
  [41 42 43 44]]

 [[15 16 17 18]
  [25 26 27 28]
  [35 36 37 38]
  [45 46 47 48]]]

Do the results match?
False


23. Question: Generate a 2D array of random floats between 0 and 1. Use
conditional operators to create a Boolean mask for values less than 0.5.
Replace these values with their squares and leave the rest unchanged.

In [40]:
import numpy as np

np.random.seed(0)
array_2d = np.random.rand(4, 5)

print("Original 2D array:")
print(array_2d)

mask = array_2d < 0.5

array_2d[mask] = array_2d[mask] ** 2

print("\nModified 2D array:")
print(array_2d)

Original 2D array:
[[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548 ]
 [0.64589411 0.43758721 0.891773   0.96366276 0.38344152]
 [0.79172504 0.52889492 0.56804456 0.92559664 0.07103606]
 [0.0871293  0.0202184  0.83261985 0.77815675 0.87001215]]

Modified 2D array:
[[5.48813504e-01 7.15189366e-01 6.02763376e-01 5.44883183e-01
  1.79483389e-01]
 [6.45894113e-01 1.91482567e-01 8.91773001e-01 9.63662761e-01
  1.47027398e-01]
 [7.91725038e-01 5.28894920e-01 5.68044561e-01 9.25596638e-01
  5.04612156e-03]
 [7.59151487e-03 4.08783595e-04 8.32619846e-01 7.78156751e-01
  8.70012148e-01]]


24. Question: Given a 5x5 array of sequential integers, use slicing to:
o Extract the diagonal elements
o Replace the elements of the middle row with zeros
o Flip the array vertically and horizontally

In [41]:
import numpy as np

array_5x5 = np.arange(25).reshape(5, 5)

print("Original 5x5 array:")
print(array_5x5)

diagonal_elements = np.diag(array_5x5)

print("\nDiagonal elements:")
print(diagonal_elements)

array_5x5[2, :] = 0

print("\nArray with middle row replaced by zeros:")
print(array_5x5)

flipped_array = np.flipud(np.fliplr(array_5x5))

print("\nArray flipped vertically and horizontally:")
print(flipped_array)

Original 5x5 array:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

Diagonal elements:
[ 0  6 12 18 24]

Array with middle row replaced by zeros:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [ 0  0  0  0  0]
 [15 16 17 18 19]
 [20 21 22 23 24]]

Array flipped vertically and horizontally:
[[24 23 22 21 20]
 [19 18 17 16 15]
 [ 0  0  0  0  0]
 [ 9  8  7  6  5]
 [ 4  3  2  1  0]]


25. Question: Create a 4D array of shape (2, 3, 4, 5) with random integers.
Use advanced slicing to extract a subarray and compute the mean along a
specified axis.

In [42]:
import numpy as np

np.random.seed(0)
array_4d = np.random.randint(0, 10, size=(2, 3, 4, 5))

print("Original 4D array:")
print(array_4d)

subarray = array_4d[0, 1, :, :]

print("\nExtracted subarray (shape {}):".format(subarray.shape))
print(subarray)

mean_along_axis_0 = np.mean(subarray, axis=0)

print("\nMean along axis 0 of the subarray (shape {}):".format(mean_along_axis_0.shape))
print(mean_along_axis_0)

Original 4D array:
[[[[5 0 3 3 7]
   [9 3 5 2 4]
   [7 6 8 8 1]
   [6 7 7 8 1]]

  [[5 9 8 9 4]
   [3 0 3 5 0]
   [2 3 8 1 3]
   [3 3 7 0 1]]

  [[9 9 0 4 7]
   [3 2 7 2 0]
   [0 4 5 5 6]
   [8 4 1 4 9]]]


 [[[8 1 1 7 9]
   [9 3 6 7 2]
   [0 3 5 9 4]
   [4 6 4 4 3]]

  [[4 4 8 4 3]
   [7 5 5 0 1]
   [5 9 3 0 5]
   [0 1 2 4 2]]

  [[0 3 2 0 7]
   [5 9 0 2 7]
   [2 9 2 3 3]
   [2 3 4 1 2]]]]

Extracted subarray (shape (4, 5)):
[[5 9 8 9 4]
 [3 0 3 5 0]
 [2 3 8 1 3]
 [3 3 7 0 1]]

Mean along axis 0 of the subarray (shape (5,)):
[3.25 3.75 6.5  3.75 2.  ]


26. Question: Given an array of shape (10, 20), reshape it to (20, 10) and (5,
40). Discuss the impact on the array's shape, size, and dimensionality.

Reshaping an array changes its shape but not its size or the total number of elements. The impact of reshaping an array from shape (10, 20) to (20, 10) and (5, 40):

Original Array
Shape: (10, 20)
Size: The total number of elements is 10 * 20 = 200.
Dimensionality: The array has 2 dimensions.
Reshaping to (20, 10)
New Shape: (20, 10)
This shape is obtained by swapping the dimensions of the original array.
Size: The total number of elements remains 20 * 10 = 200.
Dimensionality: The dimensionality remains 2.
Effect: The reshaped array has the same total number of elements but a different arrangement in terms of rows and columns. This does not alter the size or the number of dimensions.

Reshaping to (5, 40)
New Shape: (5, 40)
This shape has 5 rows and 40 columns.
Size: The total number of elements is still 5 * 40 = 200.
Dimensionality: The dimensionality remains 2.
Effect: The reshaped array has the same total number of elements but different row and column counts compared to the previous reshapes.

Summary of Reshaping
Impact on Shape:

Changing the shape of an array adjusts how the data is organized but does not change the total number of elements. For example, reshaping (10, 20) to (20, 10) or (5, 40) just rearranges the data.
Impact on Size:

The total number of elements (size) remains constant. In all reshapes, the size of the array is 200 elements.
Impact on Dimensionality:

The dimensionality (number of axes) remains the same. In these cases, the array retains 2 dimensions throughout reshaping.

27. Question: Generate a large 2D array and demonstrate the use of np. reshape
() and unravel () to manipulate its shape for various linear algebra operations.

In [43]:
import numpy as np

np.random.seed(0)
large_array = np.random.randint(1, 100, size=(6, 12))

print("Original 2D array (shape (6, 12)):")
print(large_array)

reshaped_4x18 = np.reshape(large_array, (4, 18))
print("\nReshaped array (shape (4, 18)):")
print(reshaped_4x18)

reshaped_3x24 = np.reshape(large_array, (3, 24))
print("\nReshaped array (shape (3, 24)):")
print(reshaped_3x24)

flattened_array = np.ravel(large_array)
print("\nFlattened array (shape (72,)):")
print(flattened_array)

matrix1 = np.reshape(flattened_array, (6, 12))
matrix2 = np.reshape(flattened_array, (12, 6))

product = np.dot(matrix1, matrix2)
print("\nMatrix multiplication result (shape (6, 6)):")
print(product)

Original 2D array (shape (6, 12)):
[[45 48 65 ... 88 71 89]
 [89 13 59 ... 38 26 78]
 [73 10 21 ... 89 50 30]
 [20 20 15 ... 32 75 24]
 [36 76 56 ...  6 39 18]
 [80  5 43 ... 36 12 47]]

Reshaped array (shape (4, 18)):
[[45 48 65 ... 66 40 88]
 [47 89 82 ... 89 50 30]
 [20 20 15 ... 29 35  1]
 [ 1 37 54 ... 36 12 47]]

Reshaped array (shape (3, 24)):
[[45 48 65 ... 38 26 78]
 [73 10 21 ... 32 75 24]
 [36 76 56 ... 36 12 47]]

Flattened array (shape (72,)):
[45 48 65 ... 36 12 47]

Matrix multiplication result (shape (6, 6)):
[[35356 24560 33395 33614 28585 33504]
 [32642 34465 39231 36346 32597 27949]
 [29418 32947 37315 34069 32315 25709]
 [20956 18414 22633 22871 19801 14979]
 [23602 14567 18957 22633 19734 19184]
 [20978 21740 24408 22012 21099 20554]]


28. Question: Given a 6x6 matrix, use advanced indexing and slicing to extract
the upper triangular part of the matrix and set the lower triangular part to zero.
Verify the result.

In [44]:
import numpy as np

np.random.seed(0)
matrix_6x6 = np.random.randint(1, 100, size=(6, 6))

print("Original 6x6 matrix:")
print(matrix_6x6)

upper_triangular = np.triu(matrix_6x6)

print("\nUpper triangular part of the matrix:")
print(upper_triangular)

lower_triangular_mask = np.tril(np.ones_like(matrix_6x6), -1)

matrix_with_lower_zeroed = matrix_6x6 * lower_triangular_mask

print("\nMatrix with lower triangular part set to zero:")
print(matrix_with_lower_zeroed)

verification = np.all(matrix_with_lower_zeroed == np.triu(matrix_6x6))

print("\nVerification that the matrix has zeros in the lower triangle and the upper triangle is preserved:")
print("Verification result:", verification)

Original 6x6 matrix:
[[45 48 65 68 68 10]
 [84 22 37 88 71 89]
 [89 13 59 66 40 88]
 [47 89 82 38 26 78]
 [73 10 21 81 70 80]
 [48 65 83 89 50 30]]

Upper triangular part of the matrix:
[[45 48 65 68 68 10]
 [ 0 22 37 88 71 89]
 [ 0  0 59 66 40 88]
 [ 0  0  0 38 26 78]
 [ 0  0  0  0 70 80]
 [ 0  0  0  0  0 30]]

Matrix with lower triangular part set to zero:
[[ 0  0  0  0  0  0]
 [84  0  0  0  0  0]
 [89 13  0  0  0  0]
 [47 89 82  0  0  0]
 [73 10 21 81  0  0]
 [48 65 83 89 50  0]]

Verification that the matrix has zeros in the lower triangle and the upper triangle is preserved:
Verification result: False
