In [46]:
import numpy as np
import torch
import tensorflow as tf

In [25]:
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [26]:
a.T

array([1, 2, 3])

In [27]:
b = np.array([[1, 2, 3]])
print(b)

[[1 2 3]]


In [29]:
print(b.T)

[[1]
 [2]
 [3]]


In [33]:
x = np.array([25, 2, 5])

In [37]:
x.T

array([25,  2,  5])

In [38]:
x.shape

(3,)

In [39]:
y = np.array([[25], [2], [5]])

In [41]:
y.shape

(3, 1)

In [42]:
y_t = y.T
y.T

array([[25,  2,  5]])

In [43]:
x

array([25,  2,  5])

In [44]:
(25**2 + 2**2 + 5**2)**(1/2)

25.573423705088842

In [45]:
np.linalg.norm(x)

np.float64(25.573423705088842)

In [48]:
X_pt = torch.tensor([[25, 2], [5, 26], [3, 7]])
X_pt

tensor([[25,  2],
        [ 5, 26],
        [ 3,  7]])

In [49]:
X_pt.shape

torch.Size([3, 2])

In [58]:
tf.config.run_functions_eagerly(True)

In [62]:
X_tf = tf.Variable([[25, 2], [5, 26], [3, 7]])
print(X_tf.numpy())

[[25  2]
 [ 5 26]
 [ 3  7]]


In [56]:
tf.shape(X_tf)

RecursionError: maximum recursion depth exceeded