In [99]:
%load_ext autoreload
%autoreload 2
    
%load_ext line_profiler
%load_ext snakeviz
%load_ext memory_profiler

import mahjong_hand_distance as mhd
import numpy as np
import mahjong

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
The line_profiler extension is already loaded. To reload it, use:
  %reload_ext line_profiler
The snakeviz extension is already loaded. To reload it, use:
  %reload_ext snakeviz
The memory_profiler extension is already loaded. To reload it, use:
  %reload_ext memory_profiler


In [122]:
import einops

In [2]:
hand = mhd.Hand([f"{i+1}c" for i in range(9)]+[f"{i+1}d" for i in range(5)])

In [4]:
hands = hand.neighboring_hands(1)[:3]
hands = [h.neighboring_hands()[:3] for h in hands]

In [162]:
a=[4,5,6]

In [316]:
%timeit hand.neighboring_hands(1)

15.7 ms ± 1.83 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [ ]:
%timeit hand.neighboring_hands(2)

In [318]:
len(hand.neighboring_hands(1))

476

In [320]:
len(hand.neighboring_hands(2))

220388

In [317]:
%timeit hand.neighboring_hands_alt(1)

21.3 ms ± 1.44 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [ ]:
%timeit hand.neighboring_hands_alt(2)

In [331]:
%timeit a[a.any((-1, -2))]

319 μs ± 26.7 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [188]:
new_data = hand._neighboring_hands_data(hand._data)

(34, 1, 4, 9) (1, 14, 4, 9)
(34, 14, 4, 9)
(34, 14, 4, 9)
(4, 9)
(34, 14, 4, 9)


In [103]:
new_data = new_data[:3]

Currently, doesn't work for 3d arrays 

In [111]:
poss_draws = np.bitwise_and(mhd.hand.VALID_DATA, new_data < 4)
poss_discards = new_data > 0

In [120]:
poss_draws.shape

(3, 4, 9)

In [118]:
mhd.tile.POSS_TILES[poss_draws[0].flatten()].shape

(34, 4, 9)

In [131]:
mhd.tile.POSS_TILES[None].shape

(1, 36, 4, 9)

In [132]:
einops.rearrange(poss_draws, 'hands suits values -> hands (suits values) 1 1').shape

(3, 36, 1, 1)

In [192]:
%%timeit
draws = einops.repeat(mhd.tile.POSS_TILES, 'tiles suits values -> hands tiles suits values', hands=poss_draws.shape[0])
discards = einops.repeat(mhd.tile.POSS_TILES, 'tiles suits values -> hands tiles suits values', hands=poss_draws.shape[0])

12.4 μs ± 315 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [193]:
a = [1,2,3,4,5,6]

In [206]:
a[:3]

[1, 2, 3]

In [204]:
' '.join(a[5:])

TypeError: sequence item 0: expected str instance, int found

In [ ]:
draws = einops.repeat(mhd.tile.POSS_TILES, 'tiles suits values -> hands tiles suits values', hands=poss_draws.shape[0])


In [ ]:
pd = einops.rearrange(poss_draws, 'hands suits values -> hands (suits values)')
pc = einops.rearrange(poss_discards, 'hands suits values -> hands (suits values)')

In [165]:
draws[~pd] = 0
draws = einops.rearrange(draws, 'hands tiles suits values -> 1 tiles hands suits values')
discards[~pd] = 0
discards = einops.rearrange(discards, 'hands tiles suits values -> tiles 1 hands suits values')

In [169]:
tmp = (new_data[:3]+(draws-discards))

In [185]:
tmp.reshape((-1, 4, 9)).shape

(3888, 4, 9)

In [184]:
np.unique(tmp[tmp.any((3,4))], axis=0).shape

(3404, 4, 9)

In [ ]:
tmp[tmp.]

In [152]:
tiles.shape

(3, 36, 4, 9)

In [142]:
tiles.shape

(3, 36, 4, 9)

In [141]:
pd.shape

(3, 36)

In [140]:
tiles[pd].shape

(102, 4, 9)

In [ ]:
poss_draws = np.expand_dims(POSS_TILES[poss_draws.flatten()], 1)
poss_discards = np.expand_dims(POSS_TILES[poss_discards.flatten()], 0)

In [74]:
t = mhd.hand.POSS_TILES[:,None]
t[poss_draws.reshape((10, -1)).transpose()[..., None, None]]

ValueError: cannot reshape array of size 72 into shape (10,newaxis)

In [96]:
mhd.hand.POSS_TILES.shape

(36, 4, 9)

In [92]:
mhd.hand.POSS_TILES.shape

(36, 4, 9)

In [98]:
poss_draws.reshape((2, ))

(2, 4, 9)

In [94]:
poss_draws.shape

(2, 4, 9)

In [95]:
data = np.repeat(np.expand_dims(hand._data, 0), 2, 0)
poss_draws = np.bitwise_and(mhd.tile.VALID_DATA, data < 4)
poss_discards = data > 0

poss_draws = np.expand_dims(mhd.hand.POSS_TILES[poss_draws.flatten(), None], 1)
poss_discards = np.expand_dims(mhd.hand.POSS_TILES[poss_discards.flatten()], 0)

poss_changes = (poss_draws - poss_discards)

IndexError: boolean index did not match indexed array along axis 0; size of axis is 36 but size of corresponding boolean axis is 72

In [20]:
poss_changes.shape

(34, 14, 4, 9)

In [6]:
hand._neighboring_hands_data(new_data[:10])

IndexError: boolean index did not match indexed array along axis 0; size of axis is 36 but size of corresponding boolean axis is 360

In [324]:
len(hand.neighboring_hands_alt(1))

(462, 4, 9)
(462, 4, 9)


462

In [ ]:
len(hand.neighboring_hands_alt(2))

In [311]:
new_hands.shape

(462, 4, 9)

In [314]:
a = np.zeros((0,4,9))

In [272]:
poss_tiles = np.zeros((36, 36))
poss_tiles[*np.diag_indices(34)] = 1
poss_tiles = poss_tiles.reshape((36, 4, 9))

In [309]:
poss_draws = np.bitwise_and(mhd.tile.VALID_DATA, hand._data < 4)
poss_discards = hand._data > 0

poss_draws = np.expand_dims(poss_tiles[poss_draws.flatten()], 1)
poss_discards = np.expand_dims(poss_tiles[poss_discards.flatten()], 0)

poss_changes = (poss_draws - poss_discards)
poss_changes = poss_changes[poss_changes.any((-1, -2))]

new_hands = hand._data + poss_changes
new_hands = np.unique(new_hands, axis=0)

In [ ]:
new_hands = mhd.hand.Hands(*[mhd.Hand(h) for h in new_hands])

In [257]:
poss_changes

array([[[ 1., -1.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.]],

       [[ 1.,  0., -1., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.]],

       [[ 1.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.]],

       ...,

       [[ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0., -1., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  1.,  0.,  0.]],

       [[ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  1.,  0.,  0.]],

       [[ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.

In [175]:
%lprun -u 1e-3 -f hand.neighboring_hands hand.neighboring_hands(2)

Timer unit: 0.001 s

Total time: 65.8147 s
File: /home/billbrod/Documents/mahjong-hand-distance/src/mahjong_hand_distance/hand.py
Function: neighboring_hands at line 117

Line #      Hits         Time  Per Hit   % Time  Line Contents
   117                                               def neighboring_hands(self, distance: int = 1) -> Hands:
   118                                                   """Figure out how the hands that are ``distance`` number of draws away
   119                                           
   120                                                   *WARNING*: Right now this is very inefficient, so that ``distance=1`` takes 90
   121                                                   msec and ``distance=2`` takes 90 sec, and thus ``distance=3`` probably takes 25
   122                                                   hours.
   123                                           
   124                                                   """
   125       477          4.4 

In [175]:
%lprun -u 1e-3 -f hand.neighboring_hands hand.neighboring_hands(2)

Timer unit: 0.001 s

Total time: 65.8147 s
File: /home/billbrod/Documents/mahjong-hand-distance/src/mahjong_hand_distance/hand.py
Function: neighboring_hands at line 117

Line #      Hits         Time  Per Hit   % Time  Line Contents
   117                                               def neighboring_hands(self, distance: int = 1) -> Hands:
   118                                                   """Figure out how the hands that are ``distance`` number of draws away
   119                                           
   120                                                   *WARNING*: Right now this is very inefficient, so that ``distance=1`` takes 90
   121                                                   msec and ``distance=2`` takes 90 sec, and thus ``distance=3`` probably takes 25
   122                                                   hours.
   123                                           
   124                                                   """
   125       477          4.4 

In [177]:
%snakeviz  hand.neighboring_hands(1)

 
*** Profile stats marshalled to file '/tmp/tmp2ga0tpaq'.
Embedding SnakeViz in this document...
<function display at 0x7fccd8ee27a0>


In [53]:
type(hands)

list

In [54]:
len(hands)

10

In [86]:
hs = mhd.hand.Hands.concat(hands)

In [55]:
hands_cat = mhd.hand.Hands.concat(hands)

RecursionError: maximum recursion depth exceeded

In [38]:
%timeit hands = hand.neighboring_hands()

150 ms ± 13.3 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [37]:
len(hands)

476

In [ ]:
%debu

In [90]:
np.where(np.bitwise_and(mhd.tile.VALID_DATA, hand._data < 4).flatten())

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33]),)

In [3]:
hand1 = mhd.Hand(['2c', '2c', '4c', '4c', '4c', '3d', '3d', '3d', '5d', '6d', '7d', '4b', '4b', '4b'])

In [149]:
diff = np.stack([hand._data-hand1._data, hand._data-hand1._data])

In [43]:
hands = mhd.hand.Hands(hand, hand1)

In [175]:
[hand]

[[1c,2c,3c,4c,5c,6c,7c,8c,9c,1d,2d,3d,4d,5d]]

In [170]:
str(hand)

'1c,2c,3c,4c,5c,6c,7c,8c,9c,1d,2d,3d,4d,5d'

In [40]:
diffs = hand-hands

In [67]:
diffs.distance.dtype

dtype('int64')

In [39]:
hand.distance(hands)

array([ 0, 10])

In [38]:
diffs.distance

array([ 0, 10])

In [28]:
diffs[1]._data

array([[ 1, -1,  1, -2,  1,  1,  1,  1,  1],
       [ 0,  0,  0, -3,  0,  0,  0,  0,  0],
       [ 1,  1, -2,  1,  0, -1, -1,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0]])

In [19]:
np.where(diffs[0]._data)

(array([], dtype=int64), array([], dtype=int64))

In [20]:
hand-[hand1]

In [51]:
d._data

array([[[ 1., -1.,  1., -2.,  1.,  1.,  1.,  1.,  1.],
        [ 0.,  0.,  0., -3.,  0.,  0.,  0.,  0.,  0.],
        [ 1.,  1., -2.,  1.,  0., -1., -1.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]]])

In [56]:
np.abs(d._data).sum()

np.float64(20.0)

In [136]:
abs(-2)

2.0

In [121]:
diff = hand._data-hand1._data
diff = diff.astype(int)
flat_diff = diff.flatten()

In [122]:
idx = np.where(flat_diff)[0]

In [123]:
idx

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8, 12, 18, 19, 20, 21, 23, 24])

In [132]:
tiles = np.concatenate([abs(flat_diff[t]) * mhd.Tile.from_int(t) for t in idx])

In [133]:
tiles

array([1c, 2c, 3c, 4c, 4c, 5c, 6c, 7c, 8c, 9c, 4b, 4b, 4b, 1d, 2d, 3d, 3d,
       4d, 6d, 7d], dtype=object)

In [130]:
np.where(flat_diff)

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8, 12, 18, 19, 20, 21, 23, 24]),)

In [129]:
tiles[flat_diff[idx]<0]

IndexError: boolean index did not match indexed array along axis 0; size of axis is 20 but size of corresponding boolean axis is 16

In [93]:
flat_diff = diff.flatten()

In [107]:
flat_diff[idx]

array([ 1., -1.,  1., -2.,  1.,  1.,  1.,  1.,  1., -3.,  1.,  1., -2.,
        1., -1., -1.])

In [98]:
flat_diff<0

array([False,  True, False,  True, False, False, False, False, False,
       False, False, False,  True, False, False, False, False, False,
       False, False,  True, False, False,  True,  True, False, False,
       False, False, False, False, False, False, False, False, False])

In [97]:
tiles[flat_diff<0]

TypeError: only integer scalar arrays can be converted to a scalar index

In [89]:
diff

array([[ 1., -1.,  1., -2.,  1.,  1.,  1.,  1.,  1.],
       [ 0.,  0.,  0., -3.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  1., -2.,  1.,  0., -1., -1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [88]:
tiles

[1c, 2c, 3c, 4c, 5c, 6c, 7c, 8c, 9c, 4b, 1d, 2d, 3d, 4d, 6d, 7d]

In [74]:
mhd.Tile.from_int(np.where(d._data.flatten())[0])

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [57]:
np.where(d._data)

(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 2, 2, 2, 2, 2]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 3, 0, 1, 2, 3, 5, 6]))

In [52]:
d

In [16]:
hand.score()

{'han': 1,
 'fu': 40,
 'yaku': [Tanyao],
 'fu_details': [{'fu': 30, 'reason': 'base'},
  {'fu': 4, 'reason': 'closed_pon'},
  {'fu': 4, 'reason': 'closed_pon'},
  {'fu': 2, 'reason': 'open_pon'}],
 'score': {'main': 1300,
  'main_bonus': 0,
  'additional': 0,
  'additional_bonus': 0,
  'kyoutaku_bonus': 0,
  'total': 1300,
  'yaku_level': ''}}

In [12]:
res.get

In [11]:
res.fu_details