# Hoja de trabajo 02, Inteligencia Artificial
Autores:
- Mark Albrand/ 21004
- Jimena Hernández/ 21199
- Melissa Pérez/ 21385

## Task 1 - Preguntas Teóricas
Responda a cada de las siguientes preguntas de forma clara y lo más completamente posible.

#### 1. Defina el proceso de decisión de Markov (MDP) y explique sus componentes.
Un MDP modela un problema de decisión sequencial en donde el sistema evoluciona en el tiempo y es controlado por un agente. La dinámica del sistema está determinada por una función de transición de probabilidad que mapea estados y acciones a otros estados.
Los elementos de un MDP son:
- Un conjunto finito de estados (S) : {s1,...,sn}, donde st denota el estado s ∈ S al tiempo t.
- Un conjunto finito de acciones que pueden depender de cada estado, A(s).
- Una función de recompensa (R(s,a,s')) que regresa un número real indicando lo deseado de estar en un estado s! ∈ S dado que en el estado s ∈ S se realizó la acción a ∈ A(s).
- Una función de transición de estados dada como una distribución de probabilidad (P(s'|s,a)) que denota la probabilidad de llegar al estado s! ∈ S dado que se tomó la acción a ∈ A(s) en el estado s ∈ S, que también denotaremos como Φ(s, a, s!). (Sucar, 2018)

#### 2. Describa cual es la diferencia entre política, evaluación de políticas, mejora de políticas e iteración de políticas en el contexto de los PDM.
- Política (π) hace referencia al conjunto de reglas o algoritmos de mapeo que el agente sigue para elegir acciones en cada estado.
- La evaluación de políticas consiste en determinar la calidad de una política mediante la estimación del valor esperado de retorno a la misma. Tambíen, mide el desempeño en términos de su capacidad para lograr los objetivos.
- La mejora de políticas implica modificar una política para hacerla mejor y se basa generalmente en la evaluación de la política.
- La iteración de políticas es un proceso iterativo continuo que combina la evaluación con la mejora de políticas para encontrar la más óptima.

En general, las políticas establecen las reglas para el desarrollo, la evaluación determina la efectividad, la mejora busca optimizarlas y la iteración asegura que el rendimiento óptimo será siempre ajustado. (Buczyński, 2023)

#### 3. Explique el concepto de factor de descuento (gamma) en los MDP. ¿Cómo influye en la toma de decisiones?
El factor de descuento gamma controla la importancia relativa de las recompensas futuras en comparación con las recompensas inmediatas, se utiliza para modelar la preferencia del agente para obtener las recompensas. Este factor influye en la toma de decisiones al equilibrar las recompensas a corto y largo plazo. Un valor de gamma alto, favorece la toma de decisiones que maximizan la recompensa acumulada en el tiempo. Básicamente este factor es crucial para equilibrar las recompensas, planificar las acciones y evaluar las consecuencias futuras en la toma de decisiones. (Gite, 2017)

#### 4. Analice la diferencia entre los algoritmos de iteración de valores y de iteración de políticas para resolver MDP.
Ambos algoritmos tienen un efoque para encontrar la mejor política. La diferencia es que el de iteración de valores calcula iterativamente los valores de los estados hasta que convergen a sus valores óptimos. Mientras que el de iteración de políticas, encuentra la política óptima directamente al mejorar iterativamente una política hasta que no se pueda mejorar más. (Tokuç, 2023)

#### 5. ¿Cuáles son algunos desafíos o limitaciones comunes asociados con la resolución de MDP a gran escala? Discuta los enfoques potenciales para abordar estos desafíos.
Algunos desafíos para MDP a gran escala serían 
- La complejidad computacional para resolverlo aumentando el tamaño del espacio de estados y acciones
- La gran cantidad de memoria para almacenar la información 
- Explorar una gran cantidad de espacio de estados para encontrar la política óptima.

Como enfoques potenciales para abordar los desafíos se podría 
- Utilizar algoritmos que aproximan el valor de los estados o la política
- Paralelización para distribuir la computación en múltiples procesadores 
- Utilizar técnicas de muestreo para explorar el espacio de estados eficientemente.

### Referencias:
- Sucar, L. E. (2018). Procesos de decisión de Markov y aprendizaje por refuerzo. En Inteligencia Artificial (pp. 536). Alfaomega.
- Buczyński, R. (2023). Understanding Markov Decision Processes. https://python.plainenglish.io/understanding-markov-decision-processes-17e852cd9981
- Gite, S. (2017). Practical Reinforcement Learning. https://towardsdatascience.com/practical-reinforcement-learning-02-getting-started-with-q-learning-582f63e4acd9
- Tokuç. A. (2023). Value Iteration vs. Policy Iteration in Reinforcement Learning. https://www.baeldung.com/cs/ml-value-iteration-vs-policy-iteration#:~:text=In%20policy%20iteration%2C%20we%20start%20with%20a%20fixed%20policy.,iteration%20algorithm%20updates%20the%20policy.

## Task 2 - Preguntas Analíticas
Responda a cada de las siguientes preguntas de forma clara y lo más completamente posible.

#### 1. Analice críticamente los supuestos subyacentes a la propiedad de Markov en los Procesos de Decisión de Markov (MDP). Analice escenarios en los que estos supuestos puedan no ser válidos y sus implicaciones para la toma de decisiones.
Un supuesto subyacente en la propiedad de Markov es que la historia pasada del sistema no proporciona información adicional relevante para predecir el futuro siempre que se conozca el estado presente. 

Este supuesto puede no ser válido en los siguientes escenarios:
-  Cuando el entorno, las acciones y los resultados futuros dependen de la secuencia completa de eventos pasados. Por ejemplo, los juegos de estrategia donde las decisiones de un jugador pueden depender de movimientos específicos anteriores realizados por el oponente.
- Cuando el agente no tiene acceso completo del estado actual del entorno, es decir cuando cierta información está oculta, Markov no puede ser aplicable porque introduce incertidumbre sobre el estado completo.

Dados los escenarios, las siguientes serían sus implicaciones:
- Las decisiones basadas en el estado actual generan una planificación menos precisa.
- Se necesitaría implementar modelos más complejos para capturar la dependencia de información pasada o la información parcial.
- Introduce mayor incertidumbre en las predicciones del comportamiento futuro.

#### 2. Explore los desafíos de modelar la incertidumbre en los procesos de decisión de Markov (MDP) y analice estrategias para una toma de decisiones sólida en entornos inciertos.
Se identificaron 3 principales desafíos de modelar la incertidumbre en estos procesos:
- Complejidad de la incertidumbre: 
    - El desafío es que se presenta la incertidumbre de distintas maneras como transiciones de estado estocástiacs, recompensas no deterministar o la falta de información sobre el entorno.
    - Como estrategias se podría utilizar modelos de incertidumbre como modelos bayesianos o métodos de inferencia probabilística. También, utilizar un modelado estocástico para distribuir la probabilidad y representar la incertidumbre en las transiciones de estado.

- Complejidad del modelo:
    - El desafío es en entornos complejos donde el número de estados y acciones puede ser muy grande, lo que dificulta la representación y el modelado preciso.
    - Como estrategia se puede emplear la abstracción de estados para reducir la dimensionalidad del espacio. Otra puede ser la aproximación de funciones para estimar los valores o políticas parametrizadas.

- Exploración y explotación:
    - El desafío ocurre cuando el agente debe equilibrar la exploración donde adquiere información del entorno con la explotación donde aprovecha el conocimiento existente.
    - Una estrategia interesante es emplear programación robusta que permita la toma de decisiones frente a la incertidumbre donde se consideren escenarios posibles. También podrían incluirse estrategias como exploración dirigida por incertidumbre que prioriza las accioens que reducen la incertidumbre del agente sobre el entorno.

## Task 3 - Preguntas Prácticas
Desarrolle un agente básico capaz de resolver un problema simplificado del Proceso de Decisión de Markov (MDP).
Considere utilizar un ejemplo bien conocido como el entorno 'Frozen Lake'. Proporcione el código Python para el proceso de toma de decisiones del agente basándose únicamente en los principios de los procesos de decisión de Markov. Recuerde que para este tipo de problema, el ambiente es una matriz de 4x4, y las acciones, pueden ser moverse hacia arriba, abajo, derecha, izquierda. Considere que el punto inicial siempre estará en la esquina opuesta del punto de meta. Es decir, puede tener hasta 4 configuraciones diferentes. Por ejemplo, el punto inicial puede estar en la coordenada (0, 0) y el punto de meta en la coordenada en la coordenada (3, 3). Además, la posición de los hoyos debe ser determinada aleatoriamente y no debe superar el ser más de 3. Es decir, si aleatoriamente se decide que sean 2 posiciones de hoyo, las coordenadas de estas deben ser determinadas de forma aleatoria.
Asegúrese de usar “seed” para que sus resultados sean consistentes.

#### Framework
##### Estados
El conjunto de estados es el conjunto de todas las posibles posiciones en el tablero que en este caso que es un conjunto finito de 16 elementos.
Cada estado tiene dos valores posible, 0 o 1, donde 0 representa un estado congelado y 1 representa un estado con un hoyo.

##### Estado Inicial
El estado inicial es una posición (X, Y) en el tablero, en este caso (0, 0).

##### Acciones
El conjunto de acciones es el conjunto de todas las posibles acciones que el agente puede tomar en cada estado. En este caso, las acciones posibles son: "UP", "DOWN", "LEFT", "RIGHT". Estas se guardarán en un diccionario para identificar la acción con su respectiva coordenada y poder realizar operaciones con ellas.

##### T(s, a, s')
Una función de transición de estados dada como una distribución de probabilidad (P(s'|s,a)) que denota la probabilidad de llegar al estado s! ∈ S dado que se tomó la acción a ∈ A(s) en el estado s ∈ S, que también denotaremos como Φ(s, a, s!).

Para cada estado y acción, se calculará la probabilidad de llegar a un estado congelado o un hoyo. Esto se hará verificando los vecinos de la posición a la que se quiere llegar y verificando si son hoyos o estados congelados. Con esto se calculará la probabilidad de llegar a un estado congelado o un hoyo.

##### Recompensas
Una función de recompensa (R(s,a,s')) que regresa un número real indicando lo deseado de estar en un estado s! ∈ S dado que en el estado s ∈ S se realizó la acción a ∈ A(s). En este caso, la recompensa será 1 si el estado es el estado final, -1 si el estado es un hoyo y 0 en cualquier otro caso.

##### Verificación de Estado Final
Una función que verifica si el estado actual es el estado final. En este caso, se verificará si el estado actual es el estado final. El estado final es una posición (X, Y) en el tablero, en este caso (3, 3).

##### Factor de Descuento
El factor de descuento gamma controla la importancia relativa de las recompensas futuras en comparación con las recompensas inmediatas, se utiliza para modelar la preferencia del agente para obtener las recompensas. En este caso, el factor de descuento será 0.5.

### Environment

In [2]:
import numpy as np

In [32]:
class FrozenLake:
    lake = np.zeros((4, 4))
    starting_point = (0,0)
    goal_point = (3,3)
    max_holes = 3
    holes = -1
    actions = {
        "UP": (0,1),
        "DOWN": (0,-1),
        "LEFT": (-1,0),
        "RIGHT": (1,0),
        "END": (0,0)
    }

    def __init__(self):
        self.createHoles()
    
    def createHoles(self):
        counter = 0
        for i in range(4):
            for j in range(4):
                if i == 0 and j == 0:
                    continue
                if i == 3 and j == 3:
                    continue
                if np.random.rand() < 0.1 and counter < self.max_holes:
                    self.lake[i, j] = 1
                    counter += 1

        self.holes = counter
        print(self.lake)

    def get_actions(self, state: tuple[int, int]) -> list[str]:
        # dada un estado, se devuelve una lista de coordenadas de las acciones posibles
        x, y = state
        posible_actions = []

        if y > 0:
            posible_actions.append("DOWN")
        if y < 3:
            posible_actions.append("UP")
        if x > 0:
            posible_actions.append("LEFT")
        if x < 3:
            posible_actions.append("RIGHT")
            
        return posible_actions


    #Una función de transición de estados dada como una distribución de probabilidad (P(s'|s,a)) que denota la probabilidad de llegar al estado s! ∈ S dado que se tomó la acción a ∈ A(s) en el estado s ∈ S, que también denotaremos como Φ(s, a, s!).
    def transition(self, state: tuple[int, int], action: str):
        # dada un estado actual, y una acción, se devuelve la probabilidad de llegar a cada posible estad (frozen o hole)

        next_state = (state[0] + self.actions[action][0], state[1] + self.actions[action][1])
        probabilidades = {
            "frozen": 0,
            "hole": 0
        }

        if next_state[0] < 0 or next_state[0] > 3 or next_state[1] < 0 or next_state[1] > 3:
            return probabilidades
        
        # dado next_state, verificar la probabilidad de llegar a un estado congelado o un hoyo
        neighbors = 0
        holes = 0
        for key, value in self.actions.items():
            future_state = (next_state[0] + value[0], next_state[1] + value[1])
            if future_state[0] < 0 or future_state[0] > 3 or future_state[1] < 0 or future_state[1] > 3:
                continue
            if self.lake[future_state[0], future_state[1]] == 1:
                holes += 1
            
            neighbors += 1


        probabilidades["frozen"] = 1 - (holes / neighbors)
        probabilidades["hole"] = holes / neighbors
        
        return probabilidades


    def reward(self, state: tuple[int, int]) -> int:
        #print(f"state: {state}", "goal: ", self.goal_point)
        # dada una acción y un estado, se devuelve la recompensa asociada
        if state[0] < 0 or state[0] > 3 or state[1] < 0 or state[1] > 3:
            return -1
        if state == self.goal_point:
            return 1
        if self.lake[state[0], state[1]] == 1:
            return -1
        return 0

    def isEnd(self, state: tuple[int, int]) -> bool:
        return state == self.goal_point 

In [44]:
fl = FrozenLake()
print(fl.reward((3,3)))
print(fl.transition((1,1), "RIGHT"))

[[0. 0. 0. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 0. 0. 0.]]
1
{'frozen': 0.8, 'hole': 0.2}


### Políticas

In [54]:
policy = {}

# usando FL.transition crear una política, eligiendo la acción con mayor probabilidad de llegar a un estado congelado
for x in range(4):
    for y in range(4):
        if (x,y) == (3,3):
            policy[(x,y)] = "END"
            continue
        if (x,y) == (0,0):
            policy[(x,y)] = "UP"
            continue
        max_prob = 0
        best_action = []
        for action in fl.get_actions((x,y)):
            prob = fl.transition((x,y), action)["frozen"]
            if prob > max_prob:
                max_prob = prob
                best_action = [action]
            elif prob == max_prob:
                best_action.append(action)
        policy[(x,y)] = np.random.choice(best_action)
        
print(policy)

{(0, 0): 'UP', (0, 1): 'RIGHT', (0, 2): 'DOWN', (0, 3): 'DOWN', (1, 0): 'UP', (1, 1): 'LEFT', (1, 2): 'DOWN', (1, 3): 'DOWN', (2, 0): 'UP', (2, 1): 'RIGHT', (2, 2): 'RIGHT', (2, 3): 'RIGHT', (3, 0): 'UP', (3, 1): 'UP', (3, 2): 'DOWN', (3, 3): 'END'}


In [55]:
def utility(state: tuple[int, int], policy: dict[tuple[int, int], str], fl: FrozenLake, gamma: float) -> float:
    #print(f"State {state} Action {policy[state]} Reward {fl.reward(state)}")
    print(state, policy[state])

    if fl.reward(state) != 0:
        print(fl.reward(state))

    if fl.isEnd(state):
        return fl.reward(state)
    return fl.reward(state) + gamma * utility((state[0] + fl.actions[policy[state]][0], state[1] + fl.actions[policy[state]][1]), policy, fl, gamma)

print(utility((0,0), policy, fl, 0.5))

(0, 0) UP
(0, 1) RIGHT
(1, 1) LEFT
(0, 1) RIGHT
(1, 1) LEFT
(0, 1) RIGHT
(1, 1) LEFT
(0, 1) RIGHT
(1, 1) LEFT
(0, 1) RIGHT
(1, 1) LEFT
(0, 1) RIGHT
(1, 1) LEFT
(0, 1) RIGHT
(1, 1) LEFT
(0, 1) RIGHT
(1, 1) LEFT
(0, 1) RIGHT
(1, 1) LEFT
(0, 1) RIGHT
(1, 1) LEFT
(0, 1) RIGHT
(1, 1) LEFT
(0, 1) RIGHT
(1, 1) LEFT
(0, 1) RIGHT
(1, 1) LEFT
(0, 1) RIGHT
(1, 1) LEFT
(0, 1) RIGHT
(1, 1) LEFT
(0, 1) RIGHT
(1, 1) LEFT
(0, 1) RIGHT
(1, 1) LEFT
(0, 1) RIGHT
(1, 1) LEFT
(0, 1) RIGHT
(1, 1) LEFT
(0, 1) RIGHT
(1, 1) LEFT
(0, 1) RIGHT
(1, 1) LEFT
(0, 1) RIGHT
(1, 1) LEFT
(0, 1) RIGHT
(1, 1) LEFT
(0, 1) RIGHT
(1, 1) LEFT
(0, 1) RIGHT
(1, 1) LEFT
(0, 1) RIGHT
(1, 1) LEFT
(0, 1) RIGHT
(1, 1) LEFT
(0, 1) RIGHT
(1, 1) LEFT
(0, 1) RIGHT
(1, 1) LEFT
(0, 1) RIGHT
(1, 1) LEFT
(0, 1) RIGHT
(1, 1) LEFT
(0, 1) RIGHT
(1, 1) LEFT
(0, 1) RIGHT
(1, 1) LEFT
(0, 1) RIGHT
(1, 1) LEFT
(0, 1) RIGHT
(1, 1) LEFT
(0, 1) RIGHT
(1, 1) LEFT
(0, 1) RIGHT
(1, 1) LEFT
(0, 1) RIGHT
(1, 1) LEFT
(0, 1) RIGHT
(1, 1) LEFT
(0, 1) RIGHT
(1

RecursionError: maximum recursion depth exceeded

In [27]:
def policy_evaluation(policy: dict, fl: FrozenLake, gamma: float, theta: float):
    V = {}
    for x in range(4):
        for y in range(4):
            V[(x,y)] = 0

    while True:
        delta = 0
        for x in range(4):
            for y in range(4):
                v = V[(x,y)]
                new_v = 0
                for action in fl.actions:
                    fl.transition((x,y), action)
                    new_v += policy[(x,y)] * (fl.reward((x,y)) + gamma * fl.transition((x,y), action)["frozen"] * V[(x,y)])
                V[(x,y)] = new_v
                delta = max(delta, abs(v - V[(x,y)]))
        if delta < theta:
            break
    return V

print(policy_evaluation(policy, fl, 0.9, 0.1))

TypeError: can't multiply sequence by non-int of type 'float'