In [1]:
from src.Game import Game
from src.Players.Minesweeper_bot import Minesweeper_bot
from src.UI.GUI_Bot_Inputs import GUI_Bot_Inputs
from src.UI.No_UI import No_UI
from src.Grid import Grid

import numpy as np

In [2]:
grid_size = (20, 20)
mine_percent = 0.30
max_iter = 100
bot_provider = lambda : Minesweeper_bot(True)
for i in range(max_iter):
    grid = Grid(*grid_size, mine_percent)
    result = No_UI().start(
        Game(grid),
        bot_provider()
    )
    if not result:
        print('Found a losing grid')
        GUI_Bot_Inputs(delay=100).start(Game(grid), bot_provider())
        break
else:
    print('Won everytime')

Found a losing grid


In [3]:
base_mines = np.array([
        [0, 0, 1, 0, 0, 0.],
        [0, 1, 0, 0, 0, 0.],
        [0, 0, 0, 1, 0, 0.],
        [0, 1, 0, 0, 0, 0.],
        [1, 1, 0, 0, 0, 0.],
        [0, 0, 0, 0, 0, 0.],
        [0, 0, 0, 0, 0, 0.],
    ],
    dtype=bool
)
base_mines

array([[False, False,  True, False, False, False],
       [False,  True, False, False, False, False],
       [False, False, False,  True, False, False],
       [False,  True, False, False, False, False],
       [ True,  True, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]])

In [4]:
test_grid = Grid(4, 5, 0.1)
test_grid.mines = base_mines
test_grid.n_bomb = np.sum(base_mines)
test_grid.update()
game = Game(test_grid)
game.action(5, 5)
# game.action(1, 2)
# game.action(0, 1)
# Minesweeper bot is unable to decide
# GUI_User_Inputs().start(game)
bot = Minesweeper_bot()

game_result = Command_Line_UI().start(game, bot)
game_result

NameError: name 'Command_Line_UI' is not defined

In [261]:
test_grid.mines

array([[False, False,  True, False, False, False],
       [False,  True, False, False, False, False],
       [False, False, False,  True, False, False],
       [False,  True, False, False, False, False],
       [ True,  True, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]])

In [289]:
grid_size = (10, 10)
mine_percent = 0.20
max_iter = 100
for i in range(max_iter):
    grid = Grid(*grid_size, mine_percent)
    result = No_UI().start(
        Game(grid),
        Minesweeper_bot()
    )
    if not result:
        print('Found a losing grid')
        GUI_Bot_Inputs(delay=100).start(Game(grid), Minesweeper_bot())
        break
else:
    print('Won everytime')

Hey
Hey
Hey
Hey
Hey
Hey
Hey
Hey
Hey
Hey
Hey
Hey
Hey
Hey
Hey
Hey
Hey
Hey
Hey
Hey
Hey
Hey
Hey
Hey
Hey
Hey
Hey
Hey
Hey
Hey
Hey
Hey
Hey
Hey
Hey
Hey
Hey
Hey
Hey
Hey
Hey
Hey
Hey
Hey
Hey
Found a losing grid
Hey
Hey
Hey
Hey
Hey
Hey
Hey
Hey
Hey
Hey
Hey
Hey
Hey
Hey
Hey


In [278]:
GUI_User_Inputs().start(Game(grid))

Hey


False

In [237]:
grid.mines

array([[False, False,  True, False,  True, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False,  True,
        False],
       [False, False, False, False,  True, False, False, False, False,
        False],
       [False, False,  True, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False,  True,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False,  True, False, False, False, False,
        False],
       [False, False,  True, False,  True, False, False, False, False,
         True],
       [False, False, False, False, False,  True,  True, False, False,
        False],
       [ True,  True, False, False, False, False,  True, False, False,
        False]])

In [240]:
Game(grid).action(5, 5)

RecursionError: maximum recursion depth exceeded