In [ ]:
#PYTHON

In [1]:
#Write a Python program using lambda to calculate the square of a number entered by the user. 
#ANS
num = 6
square=lambda x:x**2
print(square(num))

36


In [3]:
#Use map to double all the elements in the list: [1, 2, 3, 4, 5]. 
#ANS
numbers = [1, 2, 3, 4, 5]
doubled_numbers = list(map(lambda x: x * 2, numbers))
print(doubled_numbers)

[2, 4, 6, 8, 10]


In [4]:
#Use filter to extract all even numbers from the list: [10, 15, 20, 25, 30]. 
#ANS
numbers = [10, 15, 20, 25, 30]
even_numbers = list(filter(lambda x: x % 2 == 0, numbers))
print(even_numbers)

[10, 20, 30]


In [6]:
#Write a function that takes a variable number of arguments (*args) and returns their sum. 
def sum_all(*args):
  return sum(args)

result = sum_all(1, 2, 3, 4, 5)
print(result) 

15


In [11]:
#Create a class Person with attributes name and age. Add a method greet that prints a greeting with the name. Create an object of the class and call the greet method.
#ANS
class Person:
    def __init__(self, name, age):
        self.name = name
        self.age = age
    def greet(self):
        print("Hello, my name is", self.name)
person1 = Person("saurav",30)
person1.greet()  

Hello, my name is saurav


In [14]:
# Write a program to print the first 10 natural numbers using a for loop. 
#ANS
for i in range(1, 11):
    print(i)

1
2
3
4
5
6
7
8
9
10


In [15]:
#Write a program to calculate the sum of all numbers in a list: [5, 10, 15, 20] using a for loop. 
#ANS
numbers = [5, 10, 15, 20]
total = 0
for number in numbers:
  total=total+ number
print("The sum of the numbers is:", total)

The sum of the numbers is: 50


In [17]:
# Write a Python function to check if a string is a palindrome. 
#ANS
def is_palindrome(string):
  return string == string[::-1]
string = input("Enter a string: ")
if is_palindrome(string):
  print("The string is a palindrome.")
else:
  print("The string is not a palindrome.")

Enter a string:  malayalam


The string is a palindrome.


In [30]:
# Write a function to find the maximum of three numbers entered by the user. 
#Ans
def find_max(num1, num2, num3):
  return max(num1, num2, num3)
num1 = int(input("Enter the first number: "))
num2 = int(input("Enter the second number: "))
num3 = int(input("Enter the third number:   "))
max_num=find_max(num1, num2, num3)
print("The maximum number is:", max_num)

Enter the first number:  6
Enter the second number:  7
Enter the third number:    8


RecursionError: maximum recursion depth exceeded

In [31]:
# Write a function that takes a list of numbers and returns the largest number.
#ans
def find_largest(numbers):
  largest = numbers[0]
  for num in numbers:
    if num > largest:
      largest = num
  return largest

numbers = [10, 5, 20, 15, 8]
largest_number = find_largest(numbers)
print("The largest number is:", largest_number)

The largest number is: 20


In [32]:
#Write a program to find the factorial of a number using a while loop. 
#ans
def factorial(n):
  if n < 0:
    return "Factorial is not defined for negative numbers"
  elif n == 0:
    return 1
  else:
    fact = 1
    while n > 0:
      fact *= n
      n -= 1
    return fact
      
num = int(input("Enter a non-negative integer: "))
result = factorial(num)
print("The factorial of", num, "is", result)

Enter a non-negative integer:  5


The factorial of 5 is 120


In [ ]:
#NumPy

In [34]:
#Create a NumPy array of zeros with shape (3, 4). 
#ans
import numpy as np
array = np.zeros((3, 4))#3 rows and 4 columns
print(array)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [35]:
#Create a NumPy array of ones with shape (2, 5). 
array = np.ones((2, 5))
print(array)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [36]:
#Create a NumPy matrix with the values from 1 to 10 using np.arange(). 
#ANS
matrix = np.arange(1, 11).reshape(2, 5)
print(matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [38]:
#Create a NumPy array with numbers from 0 to 1 (inclusive) with a step size of 0.1 using np.arange(). 
#Ans
array = np.arange(0, 1.1, 0.1)# 0 to 1.1 and 0.1 step size
print(array)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [41]:
#Find the minimum value in the array np.array([1, 5, 9, 3, 6]) using np.min()
#ANS 
array = np.array([1, 5, 9, 3, 6])
min_value = np.min(array)
print(min_value)

1


In [42]:
#Find the maximum value in the array np.array([1, 5, 9, 3, 6]) using np.max().
#ANS
array = np.array([1, 5, 9, 3, 6])
max_value = np.max(array)
print(max_value)

9


In [46]:
#Compute the sum of all elements in the array np.array([2, 3, 4, 5, 6]). 
#ans
array = np.array([2, 3, 4, 5, 6])
sums = np.sum(array)
print(sums)


20


In [47]:
#Perform matrix addition of two matrices A = np.array([[1, 2], [3, 4]]) and B = np.array([[5, 6], [7, 8]]).
#ANS
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
C = A + B
print(C)

[[ 6  8]
 [10 12]]


In [49]:
# Slice the first two elements from the array np.array([10, 20, 30, 40, 50]).
array = np.array([10, 20, 30, 40, 50])
sliced_array = array[0:2]
print(sliced_array)


[10 20]


In [50]:
#Use np.where() to replace all elements greater than 5 in the array [1, 2, 3, 6, 7, 8] with 10. 
#ans
array = np.array([1, 2, 3, 6, 7, 8])
array = np.where(array > 5, 10, array)
print(array)

[ 1  2  3 10 10 10]
