## Accessing Array Elements

- [Download the lecture notes](https://philchodrow.github.io/PIC16A/content/np_plt/numpy_3.ipynb). 

Often, we want to access the data contained inside an array, for the purpose of either modifying the data or using it in later computation. For 1d arrays, the simplest way to do this is very similar to how we would do so for a list: 

In [2]:
import numpy as np

In [3]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
a[5]

5

In [5]:
a[-1]

9

In [6]:
# first four elements
a[:4]

array([0, 1, 2, 3])

In [7]:
# "fancy" indexing
# passing a list lets you single out individual elements 
a[[1,7]]

array([1, 7])

An extremely useful technique is boolean indexing. The important points about boolean indexing is that boolean comparisons in `numpy` are vectorized, and generate arrays of boolean values. 

In [8]:
# More useful: boolean indexing
# passing an array of True/False lets you grab elements according to a criterion

a > 5 # > is vectorized!!

array([False, False, False, False, False, False,  True,  True,  True,
        True])

We can also compare two arrays of the same size: 

In [9]:
b = np.random.randint(0, 10, 10) # 10 random integers between 0 and 10
b

array([4, 3, 0, 6, 3, 4, 6, 6, 4, 8])

In [10]:
ix = a > 5
ix

array([False, False, False, False, False, False,  True,  True,  True,
        True])

We can then pass these boolean arrays to select only the elements of an array for which the boolean array has value True. 

In [11]:
a[ix]

array([6, 7, 8, 9])

Usually, we would write this a bit more compactly: 

In [12]:
a[a > 5]

array([6, 7, 8, 9])

We can also use the bitwise `&` and `|` operators to combine multiple conditions: 

In [13]:
# large AND even entries using bitwise & 
a[(a > 5) & (a % 2 == 0)]

array([6, 8])

In [14]:
# large OR even entries using bitwise |
a[(a > 5) | (a % 2 == 0)]

array([0, 2, 4, 6, 7, 8, 9])

## Modifying Array Entries

After having accessed array entries, it's easy to modify them: 

In [15]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
# modifying a single value
a[5] = 50

In [17]:
a

array([ 0,  1,  2,  3,  4, 50,  6,  7,  8,  9])

In [18]:
# setting multiple values using a single number
a[a > 5] = 5

In [19]:
a

array([0, 1, 2, 3, 4, 5, 5, 5, 5, 5])

In [20]:
# using an array to set multiple values
a[a == 5] = np.array([0, 1, 2, 3, 4])
a

array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4])

In [21]:
# will lead to errors if the sizes don't match
a[a == 4] = np.array([5, 5, 5])

ValueError: NumPy boolean array indexing assignment cannot assign 3 input values to the 2 output values where the mask is true

## Indexing Multidimensional Arrays

What about when we're dealing with multidimensional arrays? 

In [22]:
A = np.reshape(np.arange(15), (3, 5))
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In this case, we use commas to separate indices along different dimensions. In the case of 2d arrays, it's often convenient to think about the first dimension as representing "rows" and the second as representing "columns." 

In [23]:
A[0, 2] # zeroth row, second column

2

In [24]:
A[-1, 0] # last row, zeroth column

10

We can also extract entire rows or columns at a time. The `:` here means "everything along the dimension". 

In [25]:
A[0,:] # entire zeroth row

array([0, 1, 2, 3, 4])

In [26]:
A[:,1] # first column

array([ 1,  6, 11])

In [27]:
A[:,:] # same as A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [29]:
A[0,:]

array([0, 1, 2, 3, 4])

In [30]:
# all the odd numbers
A[A % 2 == 1] 

array([ 1,  3,  5,  7,  9, 11, 13])

In [31]:
# add 2 to all the odd numbers

A[A % 2 == 1] += 2

In [32]:
A

array([[ 0,  3,  2,  5,  4],
       [ 7,  6,  9,  8, 11],
       [10, 13, 12, 15, 14]])

Indexing gets more complex in higher dimensions, but we generally won't work with higher-dimensional arrays in this course. 