## Модули и пакеты

**Модуль** - файл с исходным кодом, имеющий расширение .py. Встроенные модули (такие как math или sys), изначально написаны на С и встроены непосредственно в интерпретатор.

**Пакет** – это каталог, который может включать другие каталоги или модули.

При импорте модуля интерпретатор выполняет весь код в нем.

Процесс поиска модуля командой import:

1. среди встроенных модулей;
1. в директории с исполняемым скриптом;
1. в директории по умолчанию дистрибутива python;
1. в PYTHONPATH.

### Импорт пакетов
При импорте пакета после обнаружения папки с требуемым именем интерпретатор выполняет модуль `__init__.py`.

`__init__.py` может включать в себя необходимые подмодули и подпакеты, может быть пустым, а с версии 3.3. его вообще может не быть.

In [ ]:
# импорт подмодуля из пакета
import numpy.random

# использование функции из пакета
print(numpy.random.rand(5))

# импорт с использованием псевдонима
import numpy.random as rn
print(rn.rand(5))

# можно импортировать имя модуля
from numpy import random
print(random.rand(5))

[0.69721508 0.31046304 0.64434998 0.94114856 0.28535243]
[0.65136308 0.04332486 0.61446948 0.87124901 0.53234227]
[0.24250033 0.06803065 0.46188116 0.58768918 0.16330105]


In [ ]:
from pkgutil import iter_modules
import numpy

# выведем все подмодули
for submodule in iter_modules(numpy.__path__):
    print(submodule.name)

__config__
_core
_distributor_init
_globals
_pyinstaller
_pytesttester
_typing
_utils
array_api
compat
conftest
core
ctypeslib
distutils
doc
dtypes
exceptions
f2py
fft
lib
linalg
ma
matlib
matrixlib
polynomial
random
testing
tests
typing
version


## Создание модулей

In [ ]:
#создадим для примера модуль и сохраним его в файл "area.py"
%%writefile area.py
pi = 3.14159

def rectangle_area(a, b):
    return a * b

def triangle_area(a, h):
    return 0.5 * a * h

def circle_area(r):
    return pi * r ** 2

Writing area.py


In [ ]:
# ипортируем наш модуль
import area

print(type(area))
print(dir(area))  # доступные атрибуты модуля

<class 'module'>
['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'circle_area', 'pi', 'rectangle_area', 'triangle_area']


In [ ]:
# обращение к константе в модуле
print(area.pi)

# вызов функций модуля
print(area.rectangle_area(3, 7))
print(area.triangle_area(2, 4))
print(area.circle_area(5))

3.14159
21
4.0
78.53975


## Создание пакетов

In [ ]:
# создание директории для пакета
!mkdir samplepackage

In [ ]:
# хорошим тоном считается выносить константы в отдельный модуль
%%writefile samplepackage/constants.py

pi = 3.14159

Writing samplepackage/constants.py


In [ ]:
# сохраним методы исходного модуля
%%writefile samplepackage/area.py
from samplepackage.constants import pi

def rectangle_area(a, b):
    return a * b

def triangle_area(a, h):
    return 0.5 * a * h

def circle_area(r):
    return pi * r ** 2

Writing samplepackage/area.py


In [ ]:
# расширим функционал нашего пакета
%%writefile samplepackage/perimeter.py
from samplepackage.constants import pi

def rectangle_perimeter(a, b):
    return 2 * (a + b)

def triangle_perimeter(a, b,c):
    return a + b + c

def circle_perimeter(r):
    return pi * 2 * r

Writing samplepackage/perimeter.py


In [ ]:
# создадим __init_.py, для того, чтобы интерпетатор понял,
# что эта директория является пакетом
# можно оставить пустым, можно не создавать вовсе
%%writefile samplepackage/__init__.py

# указываем, что будет импортировано командой from samplepackage import *
__all__ = ['constants', 'area', 'perimeter']

Writing samplepackage/__init__.py


In [ ]:
# проверим работоспособность
from samplepackage.constants import pi
from samplepackage.area import circle_area
from samplepackage.perimeter import circle_perimeter

print(pi)
print(circle_area(10))
print(circle_perimeter(10))

3.14159
314.159
62.8318


## Установка пакетов и модулей

Пакеты и модули можно установить из внешнего репозитория.
Официальным репозиторием пакетов python является [Python Package Index](https://pypi.org/).

**Pip** — система управления пакетами, которая используется для установки и управления пакетами, написанными на python.

С версии языка 3.4 pip входит в стандартный дистрибутив python.

In [ ]:
# установка пакета при помощи командной строки
# например, установим пакет для для манипуляции пространственными данными
# автоматически установится последняя версия
!pip install fiona

# можно указать определенную версию пакета
# !pip install fiona==1.8.10

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.6/56.6 kB 4.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.3/17.3 MB 81.8 MB/s eta 0:00:00


In [ ]:
# просмотр информации об установленном пакете через командную строку
!pip show fiona

Name: fiona
Version: 1.10.1
Summary: Fiona reads and writes spatial data files
Home-page: 
Author: Sean Gillies
Author-email: 
License: BSD 3-Clause
Location: /usr/local/lib/python3.10/dist-packages
Requires: attrs, certifi, click, click-plugins, cligj
Required-by: 


In [ ]:
# версию пакета можно узнать и при помощи атрибута __version__
import fiona
print(fiona.__version__)

1.10.1


In [ ]:
# вывод списка всех установленных в окружении пакетов
!pip freeze

absl-py==1.4.0
accelerate==0.34.2
aiohappyeyeballs==2.4.0
aiohttp==3.10.5
aiosignal==1.3.1
alabaster==0.7.16
albucore==0.0.16
albumentations==1.4.15
altair==4.2.2
annotated-types==0.7.0
anyio==3.7.1
argon2-cffi==23.1.0
argon2-cffi-bindings==21.2.0
array_record==0.5.1
arviz==0.19.0
astropy==6.1.3
astropy-iers-data==0.2024.9.16.0.32.21
astunparse==1.6.3
async-timeout==4.0.3
atpublic==4.1.0
attrs==24.2.0
audioread==3.0.1
autograd==1.7.0
babel==2.16.0
backcall==0.2.0
beautifulsoup4==4.12.3
bigframes==1.18.0
bigquery-magics==0.2.0
bleach==6.1.0
blinker==1.4
blis==0.7.11
blosc2==2.0.0
bokeh==3.4.3
bqplot==0.12.43
branca==0.7.2
build==1.2.2
CacheControl==0.14.0
cachetools==5.5.0
catalogue==2.0.10
certifi==2024.8.30
cffi==1.17.1
chardet==5.2.0
charset-normalizer==3.3.2
chex==0.1.86
clarabel==0.9.0
click==8.1.7
click-plugins==1.1.1
cligj==0.7.2
cloudpathlib==0.19.0
cloudpickle==2.2.1
cmake==3.30.3
cmdstanpy==1.2.4
colorcet==3.1.0
colorlover==0.3.0
colour==0.1.5
community==1.0.0b1
confection==0.

In [ ]:
# деинсталляция пакета при помощи командной строки
!pip uninstall fiona

# можно пропустить диалог с подтверждением удаления
# !pip uninstall fiona -y

Found existing installation: fiona 1.10.1
Uninstalling fiona-1.10.1:
  Would remove:
    /usr/local/bin/fio
    /usr/local/lib/python3.10/dist-packages/fiona-1.10.1.dist-info/*
    /usr/local/lib/python3.10/dist-packages/fiona.libs/libcrypto-fiona-a474b82d.so.1.1
    /usr/local/lib/python3.10/dist-packages/fiona.libs/libcurl-fiona-1d984654.so.4.8.0
    /usr/local/lib/python3.10/dist-packages/fiona.libs/libgdal-fiona-e8f6bdb0.so.35.3.9.2
    /usr/local/lib/python3.10/dist-packages/fiona.libs/libgeos-fiona-d914d573.so.3.11.2
    /usr/local/lib/python3.10/dist-packages/fiona.libs/libgeos_c-fiona-3b303efa.so.1.17.2
    /usr/local/lib/python3.10/dist-packages/fiona.libs/libjpeg-fiona-320f4797.so.9.6.0
    /usr/local/lib/python3.10/dist-packages/fiona.libs/libjson-c-fiona-b8129721.so.5.1.0
    /usr/local/lib/python3.10/dist-packages/fiona.libs/liblzma-fiona-c949e524.so.5.2.2
    /usr/local/lib/python3.10/dist-packages/fiona.libs/libnghttp2-fiona-e183d352.so.14.21.1
    /usr/local/lib/python3

## Обработка ошибок

**Исключения** — это механизм обработки ошибок во время выполнения программы. Они позволяют программе продолжить работу после обнаружения ошибки, а не завершаться аварийно.

В python есть исключения почти для всех возможных ситуаций. Они все наследуются от класса `BaseException` и имеют следующую иерархию:

**BaseException**:
- `SystemExit` - исключение, вызванное функцией sys.exit(), указывает на выход из Python.
- `KeyboardInterrupt` - вызывается при прерывании программы пользователем (обычно через сочетание клавиш Ctrl+C).
- `GeneratorExit` - вызывается, когда генератор закрывается; это не ошибка, а уведомление о закрытии.
- `Exception` - почти все встроенные исключения, с которыми сталкиваются разработчики в повседневной работе, являются производными от этого класса. Он служит базой для иерархии исключений, не связанных с системными событиями.

Иерархия класса `Exception` и его наследников:

**Exception**
- StopIteration
- StopAsyncIteration
- ArithmeticError
    - FloatingPointError
    - OverflowError
    - ZeroDivisionError
- AssertionError
- AttributeError
- BufferError
- EOFError
- ImportError
    - ModuleNotFoundError
- LookupError
    - IndexError
    - KeyError
- MemoryError
- NameError
    - UnboundLocalError
- OSError
    - lockingIOError
    - ChildProcessError
    - ConnectionError
        - BrokenPipeError
        - ConnectionAbortedError
        - ConnectionRefusedError
        - ConnectionResetError
    - FileExistsError
    - FileNotFoundError
    - InterruptedError
    - IsADirectoryError
    - NotADirectoryError
    - PermissionError
    - ProcessLookupError
    - TimeoutError
- ReferenceError
- RuntimeError
    - NotImplementedError
    - RecursionError
- SyntaxError
    - IndentationError
        - TabError
- SystemError
- TypeError
- ValueError
    - UnicodeError
        - UnicodeDecodeError
        - UnicodeEncodeError
        - UnicodeTranslateError
- Warning
    - DeprecationWarning
    - PendingDeprecationWarning
    - RuntimeWarning
    - SyntaxWarning
    - UserWarning
    - FutureWarning
    - ImportWarning
    - UnicodeWarning
    - BytesWarning
    - EncodingWarning
    - ResourceWarning

### Конструкция try...except...finally

In [ ]:
# в блоке try содержится код, который может вызвать исключение
try:
    a = 1 / 0
# в блоке except - код, который будет выполняться в случае возникновения ошибки
except:
    print("Ошибка: деление на 0!")

Ошибка: деление на 0!


In [ ]:
try:
    file = open("my_file.txt", 'w')
    file.write(1/0)
except:
    print("Ошибка при работе с файлом")
# можно добавить блок finally, который выполнится не зависимо от того, было ли
# сгенерированно исключение
finally:
    file.close()
    print("Файл в любом случае закрыт")

Ошибка при работе с файлом
Файл в любом случае закрыт


In [ ]:
try:
    a = 1 / 0
# желательно указывать тип исключения для получения информации о нём
except ZeroDivisionError as exc:
    print("Ошибка:", exc)

Ошибка: division by zero


In [ ]:
try:
    a = 1
    b = 0
    # во многих ситуациях лучшим вариантом будет предвидеть исключение
    # и самостоятельно выбросить его с помощью оператора raise
    if b == 0:
        raise ZeroDivisionError("деление на 0")
    c = a / b
except ZeroDivisionError as exc:
    print("Ошибка:", exc)

Ошибка: деление на 0


In [ ]:
# следует быть аккуратным с обработкой ошибок внутри функций,
# особенно тех, которые имеют возвращаемое значение
def division(a: int, b: int) -> int:
    try:
        if b == 0:
            raise ZeroDivisionError("деление на 0")
        return a / b
    except ZeroDivisionError as exc:
        print("Ошибка:", exc)

# здесь ожидается результат типа int, но возвращается None
res = division(5, 0) + 10
print(res)

Ошибка: деление на 0


TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

In [ ]:
# лучшим вариантом будет вынести обработку исключения за пределы функции
def division(a: int, b: int) -> int:
    # потенциальное исключение можно добавить в docstring
    """
    :raises ZeroDivisionError: division by zero.
    """
    if b == 0:
        raise ZeroDivisionError("деление на 0")
    return a / b

try:
    res = division(5, 0) + 10
    print(res)
except ZeroDivisionError as exc:
    print("Ошибка:", exc)

Ошибка: деление на 0
