In [1]:
my_string='hello'
print(my_string[1:3])

el


In [1]:
Q.9. Write a code to create the given structure using only for loop.
*
***
*****
*******
*********

SyntaxError: invalid syntax (1353591240.py, line 1)

In [34]:
a = '*'
for i in range(5):
    for j in range(0,i+1):
        print(a,end =" ")
    print('\n')

* 

* * 

* * * 

* * * * 

* * * * * 



In [51]:
a = '*'
for i in range(5):
    for j in range(0,i+1):
        print(a,end =" ")
    print('\n')

* 

* * 

* * * 

* * * * 

* * * * * 



In [51]:
for i in range(5):
    n=5

    
    for j in range(i):
        
        print('*',end=' ')
    print('\n')




* 

* * 

* * * 

* * * * 



In [355]:
range(5)
for a in range(5):
    
     
    print(' '*(5-a),'*'*(a),end='')
    for j in range(0,a+1):
        
        print('f', end='')
        
    print('\n')

      f

     *ff

    **fff

   ***ffff

  ****fffff



In [279]:
n=5
for i in range(n):
    print(' '*(n-i),end='')
    for j in range(0,i+1):
        
        print('*'*(j+1),end='')
        
    print('\n')

    

     *

    ***

   ******

  **********

 ***************



In [11]:
#Answer-9
n=5
for i in range(n):
    print(' '*(n-i),end='')
    for j in range(0,i+1):
        
        print('*'*(j+1),end='')
        
    print('\n')

     *

    ***

   ******

  **********

 ***************



In [108]:
a=0
while a in range(5):
    a=a+1
     
    print(' '*(a),'*'*(5-a),end=' ')
    print('*'*(6-a),end='')
        
    print('\n')

  **** *****

   *** ****

    ** ***

     * **

       *



In [79]:
a=0
while a in range(5):
    a=a+1
     
    print(' '*(a-1),end=' '),print('|'*(5-a),end='')
    print('|'*(6-a),end='')
    print('\n')
       
        
    

 |||||||||

  |||||||

   |||||

    |||

     |



In [110]:
'''Q.1. Create two int type variables, apply addition, subtraction, division and multiplications
and store the results in variables. Then print the data in the following format by calling the
variables:
First variable is __ & second variable is __.
Addition: __ + __ = __
Subtraction: __ - __ = __
Multiplication: __ * __ = __
Division: __ / __ = __

SyntaxError: incomplete input (4148684855.py, line 1)

In [12]:
a= int(input("First variable = "))
b= int(input('Second variable = '))
addition = a + b
print(f'Addition: {a} + {b} =', addition)

#if a>b:
substraction = a-b
print(f'Substraction: {a} - {b} =', substraction)
#else:
 #   subtraction = b-a
  #  print(f'Substraction: {b} - {a} =', substraction)
multiplication = a*b
print(f'Multiplication: {a} * {b} =', multiplication)

if b>0:
    division = a/b
    print(f'Division: {a} / {b} =', division)

else:
    print(f'Division: {a} / {b} =','denominator should not be zero')


First variable = 4
Second variable = 0
Addition: 4 + 0 = 4
Substraction: 4 - 0 = 4
Multiplication: 4 * 0 = 0
Division: 4 / 0 = denominator should not be zero


In [1]:
for i in range(0, 5):
    power_of_two = 1 << i
    print("2 raised to the power of", i, "is", power_of_two)

2 raised to the power of 0 is 1
2 raised to the power of 1 is 2
2 raised to the power of 2 is 4
2 raised to the power of 3 is 8
2 raised to the power of 4 is 16


In [13]:
v = 54 >> 98
v 

0

In [1]:
import numpy as np

In [2]:
lst=[1,2,3,4]

In [4]:
np.array(lst)

array([1, 2, 3, 4])

In [32]:
lst1=[[1,2,3,4],[1,2,3,0]]

In [33]:
arr2=np.array(lst1)

In [34]:
arr2

array([[1, 2, 3, 4],
       [1, 2, 3, 0]])

In [35]:
arr2.shape

(2, 4)

In [36]:
arr2.reshape(8,1)

array([[1],
       [2],
       [3],
       [4],
       [1],
       [2],
       [3],
       [0]])

In [37]:
type(arr2)

numpy.ndarray

# GAME

In [ ]:
a = 'apple1 mango lemon guava watermelon'


In [2]:
import random
import collections

a = 'apple mango lemon guava watermelon'
a= a.split(' ')
b= random.choice(a)

for i in b: 
         # For printing the empty spaces for letters of the word 
    print('_', end=' ') 
print() 

_ _ _ _ _ 


In [10]:
import random
user = input('Your choices are rock, paper, scissor = ').lower()
actions = ('rock', 'paper', 'scissor')
computer = random.choice(actions)
print(f'You chose {user.lower()}, computer chose {computer}')
if user in actions:
   
    
    
    if user == computer:
        print('You both chose same, its a tie')
    elif user == 'rock':
        if computer == 'scissor':
            print("Rock smashes scissor, you win")
        else:
            print("paper covers rock, computer win")
    elif user== 'scissor':
        if computer=='rock':
            print("Rock smashes scissor, computer win")
        else:
            print("scissor cuts paper, you win")
    elif user=='paper':
        if computer== 'scissor':
            print("scissor cuts paper, computer win")
        else:
            print("paper covers rock, you win")

else:
    print("Pick one of the choices")

    
      

Your choices are rock, paper, scissor = 5
You chose 5, computer chose scissor
Pick one of the choices


In [ ]:
if user == computer:
    print('You both chose same, its a tie')
elif user == 'rock':
    if computer == 'scissor':
        print("Rock smashes scissor, you win")
    else:
        print("paper covers rock, computer win")
elif user== 'scissor':
    if computer=='rock':
        print("Rock smashes scissor, computer win")
    else:
        print("scissor cuts paper, you win")
elif user=='paper':
    if computer== 'scissor':
        print("scissor cuts paper, computer win")
    else:
        print("paper covers rock, you win")

In [1]:
(dir(locals()['__builtins__']))

['ArithmeticError',
 'AssertionError',
 'AttributeError',
 'BaseException',
 'BlockingIOError',
 'BrokenPipeError',
 'BufferError',
 'BytesWarning',
 'ChildProcessError',
 'ConnectionAbortedError',
 'ConnectionError',
 'ConnectionRefusedError',
 'ConnectionResetError',
 'DeprecationWarning',
 'EOFError',
 'Ellipsis',
 'EncodingWarning',
 'EnvironmentError',
 'Exception',
 'False',
 'FileExistsError',
 'FileNotFoundError',
 'FloatingPointError',
 'FutureWarning',
 'GeneratorExit',
 'IOError',
 'ImportError',
 'ImportWarning',
 'IndentationError',
 'IndexError',
 'InterruptedError',
 'IsADirectoryError',
 'KeyError',
 'KeyboardInterrupt',
 'LookupError',
 'MemoryError',
 'ModuleNotFoundError',
 'NameError',
 'None',
 'NotADirectoryError',
 'NotImplemented',
 'NotImplementedError',
 'OSError',
 'OverflowError',
 'PendingDeprecationWarning',
 'PermissionError',
 'ProcessLookupError',
 'RecursionError',
 'ReferenceError',
 'ResourceWarning',
 'RuntimeError',
 'RuntimeWarning',
 'StopAsyncIt

In [19]:
try:
    a=2
    b=3
        c=a+b
    print(c)
except IndentationError as ie:
    print(ie)

IndentationError: unexpected indent (1254530857.py, line 4)

In [103]:
def asd(i):
    
    l[0]=[10,1]
l=[2]
asd(8)
print(l)

[[10, 1]]


In [3]:
a= int()
range(2,a,2)

range(2, 0, 2)

In [11]:
a=int(input('this is input = '))
for i in range(0,a,2):
    print(i)

this is input = 5
0
2
4


In [37]:
list.index(a,4,-2)

3

In [33]:
a=[2,3,3,4,45]