In [1]:
import numpy as np

In [2]:
np.__dict__

{'ALLOW_THREADS': 1,
 'AxisError': numpy.core._internal.AxisError,
 'BUFSIZE': 8192,
 'CLIP': 0,
 'ComplexWarning': numpy.core.numeric.ComplexWarning,
 'DataSource': numpy.lib._datasource.DataSource,
 'ERR_CALL': 3,
 'ERR_DEFAULT': 521,
 'ERR_IGNORE': 0,
 'ERR_LOG': 5,
 'ERR_PRINT': 4,
 'ERR_RAISE': 2,
 'ERR_WARN': 1,
 'FLOATING_POINT_SUPPORT': 1,
 'FPE_DIVIDEBYZERO': 1,
 'FPE_INVALID': 8,
 'FPE_OVERFLOW': 2,
 'FPE_UNDERFLOW': 4,
 'False_': False,
 'Inf': inf,
 'Infinity': inf,
 'MAXDIMS': 32,
 'MAY_SHARE_BOUNDS': 0,
 'MAY_SHARE_EXACT': -1,
 'MachAr': numpy.core.machar.MachAr,
 'ModuleDeprecationWarning': numpy._globals.ModuleDeprecationWarning,
 'NAN': nan,
 'NINF': -inf,
 'NZERO': -0.0,
 'NaN': nan,
 'PINF': inf,
 'PZERO': 0.0,
 'PackageLoader': numpy._import_tools.PackageLoader,
 'RAISE': 2,
 'RankWarning': numpy.lib.polynomial.RankWarning,
 'SHIFT_DIVIDEBYZERO': 0,
 'SHIFT_INVALID': 9,
 'SHIFT_OVERFLOW': 3,
 'SHIFT_UNDERFLOW': 6,
 'ScalarType': (int,
  float,
  complex,
  int,
  bo

In [3]:
len(np.__dict__)

613

# 유니버셜 함수

    배열의 원소별로 전부 순환문 없이 전부 곗ㄴ을 하는 함수가 유니버셜함수 이다.
    

In [7]:
print(np.ufunc)

<class 'numpy.ufunc'>


In [5]:
for i in np.__dict__ :
    
    if type(np.__dict__[i]) == np.ufunc :
        print(i)
    

bitwise_not
absolute
add
arccos
arccosh
arcsin
arcsinh
arctan
arctan2
arctanh
bitwise_and
bitwise_or
bitwise_xor
cbrt
ceil
conjugate
copysign
cos
cosh
deg2rad
degrees
divmod
equal
exp
exp2
expm1
fabs
float_power
floor
floor_divide
fmax
fmin
fmod
frexp
greater
greater_equal
heaviside
hypot
invert
isfinite
isinf
isnan
isnat
ldexp
left_shift
less
less_equal
log
log10
log1p
log2
logaddexp
logaddexp2
logical_and
logical_not
logical_or
logical_xor
maximum
minimum
modf
multiply
negative
nextafter
not_equal
positive
power
rad2deg
radians
reciprocal
remainder
right_shift
rint
sign
signbit
sin
sinh
spacing
sqrt
square
subtract
tan
tanh
true_divide
trunc
divide
conj
mod
abs


## 최대값과 최소값 

In [142]:
print(np.maximum([2, 3, 4], [1, 5, 2]))
print(np.minimum([2, 3, 4], [1, 5, 2]))

[2 5 4]
[1 3 2]


In [143]:
np.maximum(np.eye(2), [0.5, 2])

array([[ 1. ,  2. ],
       [ 0.5,  2. ]])

In [144]:
np.minimum(np.eye(2), [0.5, 2])

array([[ 0.5,  0. ],
       [ 0. ,  1. ]])

## 산술연산

In [32]:
print(type(np.add))
print(type(np.subtract))
print(type(np.multiply))
print(type(np.divide))
print(type(np.true_divide))
print(type(np.floor_divide))


<class 'numpy.ufunc'>
<class 'numpy.ufunc'>
<class 'numpy.ufunc'>
<class 'numpy.ufunc'>
<class 'numpy.ufunc'>
<class 'numpy.ufunc'>


### 덧셈과 뺄셈 

In [64]:
a = np.arange(10)
b = np.arange(10,20)

c = np.add(a,b)

print(c,type(c))

[10 12 14 16 18 20 22 24 26 28] <class 'numpy.ndarray'>


In [65]:
d = a + b
print(d,type(d))

[10 12 14 16 18 20 22 24 26 28] <class 'numpy.ndarray'>


In [66]:
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]


In [67]:
c = np.subtract(a,b)

print(c,type(c))

[-10 -10 -10 -10 -10 -10 -10 -10 -10 -10] <class 'numpy.ndarray'>


### 곱셈과 나눗셈 

In [68]:
c = np.multiply(a,b)

print(c,type(c))

[  0  11  24  39  56  75  96 119 144 171] <class 'numpy.ndarray'>


In [69]:
c = np.divide(a,b)

print(c,type(c))

[ 0.          0.09090909  0.16666667  0.23076923  0.28571429  0.33333333
  0.375       0.41176471  0.44444444  0.47368421] <class 'numpy.ndarray'>


In [70]:
c = np.true_divide(a,b)

print(c,type(c))

[ 0.          0.09090909  0.16666667  0.23076923  0.28571429  0.33333333
  0.375       0.41176471  0.44444444  0.47368421] <class 'numpy.ndarray'>


In [71]:
c = np.floor_divide(a,b)

print(c,type(c))

[0 0 0 0 0 0 0 0 0 0] <class 'numpy.ndarray'>


### 몫과 나머지 계산하기 

In [72]:
c = np.divmod(a,b) 
print(c)

(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))


In [73]:
c = np.remainder(a,b) 
print(c)

[0 1 2 3 4 5 6 7 8 9]


### 소숫점 자리수 조정하기 

In [37]:
c = np.true_divide(a,b)

print(c,type(c))

d = np.round(c,2)
print(d)

[ 0.          0.09090909  0.16666667  0.23076923  0.28571429  0.33333333
  0.375       0.41176471  0.44444444  0.47368421] <class 'numpy.ndarray'>
[ 0.    0.09  0.17  0.23  0.29  0.33  0.38  0.41  0.44  0.47]


#### 소숫점 자라 절사하기 

In [46]:
a = np.array([-1.7, -1.5, -0.2, 0.2, 1.5, 1.7, 2.0])
print(np.trunc(a))

[-1. -1. -0.  0.  1.  1.  2.]


#### 소숫점자리 반올림

In [45]:
a = np.array([-1.7, -1.5, -0.2, 0.2, 1.5, 1.7, 2.0])
print(np.ceil(a))

[-1. -1. -0.  1.  2.  2.  2.]


In [47]:
a = np.array([-1.7, -1.5, -0.2, 0.2, 1.5, 1.7, 2.0])
print(np.floor(a))

[-2. -2. -1.  0.  1.  1.  2.]


In [ ]:
positive
negative
sign

## 로그 와 지수 함수


In [53]:
a = np.array([1,2,3,4])

print(np.log(a))
print(np.log10(a))
print(np.log2(a))
print(np.log1p(a))

[ 0.          0.69314718  1.09861229  1.38629436]
[ 0.          0.30103     0.47712125  0.60205999]
[ 0.         1.         1.5849625  2.       ]
[ 0.69314718  1.09861229  1.38629436  1.60943791]


In [54]:
print(np.log1p(1e-99))

print(np.log(1 + 1e-99))

1e-99
0.0


In [56]:
print(np.exp(1e-99) - 1)
print(np.log1p(1e-99))


0.0
1e-99


## Calculates log(exp(x1) + exp(x2)).

In [57]:
prob1 = np.log(1e-50)
prob2 = np.log(2.5e-50)
prob12 = np.logaddexp(prob1, prob2)

print(prob12)

-113.876491681


## Calculates log2(2**x1 + 2**x2)

In [60]:
prob1 = np.log2(1e-50)
prob2 = np.log2(2.5e-50)
prob12 = np.logaddexp2(prob1, prob2)

print(prob12)

-164.289049822


### 지수 함수 

In [83]:
a = np.exp([1,2,3,4])
print(a)

[  2.71828183   7.3890561   20.08553692  54.59815003]


In [87]:
import math

for i in range(1,5) :
    a = math.exp(i)
    print(a)

2.718281828459045
7.38905609893065
20.085536923187668
54.598150033144236


In [121]:
print(np.square(2))
print(np.square([2,4,9]))

4
[ 4 16 81]


In [128]:
print(np.power(2,3))

print(np.float_power(2.3,3))

8
12.167


In [123]:
print(np.sqrt(2))
print(np.sqrt([2,3,5]))

1.41421356237
[ 1.41421356  1.73205081  2.23606798]


## 논리함수 

In [95]:
print(np.logical_not(3))
print(np.logical_not([True, False,False, False]))

False
[False  True  True  True]


In [88]:
print(np.logical_and(True, False))
print(np.logical_and([True, False], [False, False]))


False
[False False]


In [89]:
print(np.logical_or(True, False))
print(np.logical_or([True, False], [False, False]))

True
[ True False]


In [90]:
print(np.logical_xor(True, False))
print(np.logical_xor([True, False], [False, False]))

True
[ True False]


## 비트 연산 

In [124]:
print(np.signbit(1))

False


In [125]:
print(np.signbit(-1.2))

print(np.signbit(np.array([1, -2.3, 2.1])))


True
[False  True False]


In [103]:
print(np.bitwise_not(13))
print(np.bitwise_not([14,3]))

-14
[-15  -4]


In [104]:
np.binary_repr(-4), np.binary_repr(-14), np.binary_repr(-15)

('-100', '-1110', '-1111')

In [100]:
np.binary_repr(12), np.binary_repr(13), np.binary_repr(17)

('1100', '1101', '10001')

In [98]:
print(np.bitwise_and(13, 17))
print(np.bitwise_and([14,3], 13))

1
[12  1]


In [101]:
print(np.bitwise_or(13, 17))
print(np.bitwise_or([14,3], 13))

29
[15 15]


In [102]:
print(np.bitwise_xor(13, 17))
print(np.bitwise_xor([14,3], 13))

28
[ 3 14]


In [105]:
np.bitwise_not is np.invert

True

In [110]:
print(np.invert(np.array([13], dtype=np.uint8)))

print(np.binary_repr(242, width=8))

[242]
11110010


### 비트연산 중에 쉬프트 연산

In [111]:
print(np.left_shift(5, [1,2,3]))
print(np.left_shift([5,5,5],[1,2,3]))


[10 20 40]
[10 20 40]


In [114]:
print(np.right_shift(50, [1,2,3]))
print(np.right_shift([50,50,50],[1,2,3]))

[25 12  6]
[25 12  6]


In [118]:
print(np.binary_repr(50))
print(np.binary_repr(25))
print(np.binary_repr(12))
print(np.binary_repr(6))

110010
11001
1100
110


## 비교하기 

In [76]:
print(np.greater(10,30))
print(10 > 30)

False
False


In [77]:
print(np.greater_equal(10,30))
print(10 >= 30)

False
False


In [78]:
print(np.less(10,30))
print(10 < 30)

True
True


In [79]:
print(np.less_equal(10,30))
print(10 <= 30)

True
True


In [81]:
print(np.equal(10,30))
print(10 == 30)

False
False


In [82]:
print(np.not_equal(10,30))
print(10 != 30)

True
True


## 삼각함수 

In [ ]:
arccos
arccosh
arcsin
arcsinh
arctan
arctan2
arctanh
cos
cosh
sin
sinh
tan
tanh

deg2rad
degrees
rad2deg
radians

## is 연산 

In [129]:
np.isfinite(1)

True

In [132]:
np.isinf(np.inf)

True

In [133]:
np.isnan(np.nan)

True

In [ ]:

absolute
cbrt
conjugate
copysign
expm1
fabs
fmax
fmin
fmod
frexp
heaviside
hypot

ldexp
maximum
minimum
modf
nextafter
reciprocal
rint
spacing
conj
mod
abs