<a href="https://colab.research.google.com/github/RoyEHamlin/Code-Snippets/blob/main/QUICK_PYTHON_EXAMPLES.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### Last Updated Friday, October 16, 2020
#### Last Updated Monday, December 14, 2020
#### Last updated Monday, September 06, 2021 (DataFrame from string)
#### Downloaded from FIU and updated on Friday, September 03, 2021
#### REdownloaded onto new Family Computer on Sunday, October 02, 2022

# Imports -----------------------------------

In [ ]:
# from sklearn import datasets
# import pandas as pd
# import statsmodels.api as sm
# import matplotlib.pyplot as plt
# from mpl_toolkits.mplot3d import axes3d, Axes3D

# Objects ------------------------------------

In [ ]:
# View an object's functions
# https://www.askpython.com/python/examples/find-all-methods-of-class 2021.09.08 - 17.53
print(dir(int()))

['__abs__', '__add__', '__and__', '__bool__', '__ceil__', '__class__', '__delattr__', '__dir__', '__divmod__', '__doc__', '__eq__', '__float__', '__floor__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getnewargs__', '__gt__', '__hash__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__le__', '__lshift__', '__lt__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rlshift__', '__rmod__', '__rmul__', '__ror__', '__round__', '__rpow__', '__rrshift__', '__rshift__', '__rsub__', '__rtruediv__', '__rxor__', '__setattr__', '__sizeof__', '__str__', '__sub__', '__subclasshook__', '__truediv__', '__trunc__', '__xor__', 'as_integer_ratio', 'bit_length', 'conjugate', 'denominator', 'from_bytes', 'imag', 'numerator', 'real', 'to_bytes']


# Functions ---------------------------

## Define a Function

In [ ]:
# from Ch1, Expected Values
def flip(flips, trials):
    return np.random.randint(0, 2, size=(trials, flips))

### Common Functions

#### Print()

In [ ]:
# https://www.python-course.eu/python3_formatted_output.php
# print("The feature importances are " + str(dt.feature_importances_))  # Will not run :Decision Trees
# print("The score is %f " % dt.score(X, y))   # Will not run : Decision Trees
print("Hello World", end="\n") # new line: https://www.freecodecamp.org/news/python-new-line-and-how-to-python-print-without-a-newline/

Hello World


# Referencing, Quotes, etc...

In [ ]:
# from: https://stackoverflow.com/questions/26236564/invalid-syntax-when-using-find-elemen-by-xpath
# use triple quotes ("""sometext""")

# Primatives ------------------------------

### Unary and Binary Operators

In [ ]:
# https://www.tutorialspoint.com/python/python_basic_operators.htm
# Arithmetic Operators
1+1
1-1
# Comparison (Relational) Operators
# Assignment Operators
# Logical Operators
# Bitwise Operators
# Membership Operators
# Identity Operators

0

### Lists and Arrays

In [ ]:
# http://forums.whirlpool.net.au/archive/1199099
# https://www.pythoncentral.io/the-difference-between-a-list-and-an-array/
# https://www.geeksforgeeks.org/g-fact-41-multiple-return-values-in-python/
# http://thomas-cokelaer.info/tutorials/python/data_structures.html
anArray = [1,2,3]   # same type
alist = [1, 2, "a", 'b'] # diff types, ITERABLE
alist.append(anArray)

myset = set()
myset.add(1)

atuple = (1, 2, "a")  # note quotes
# https://www.pythonlearn.com/html-008/cfbook011.html

aDictionary = {"a":1, "b":2}

# Also : https://stackoverflow.com/questions/2225038/determine-the-type-of-an-object?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa
type([]) is list
# True
type({}) is dict
# True
type('') is str
# True
type(0) is int
# True
type({})
# <type 'dict'>
type([])
# <type 'list'>

# Sets vs Lists/Tuples
# https://www.datacamp.com/community/tutorials/sets-in-python
# Sets CANNOT have duplicates

# Sum Arrays
# https://stackoverflow.com/questions/11344827/summing-elements-in-a-list
weights = [5, 20, 20, 5, 25, 25]
sum(weights)

# Append to List/array
# https://developers.google.com/edu/python/lists
ind_prune = []
ind_prune.append(1)
ind_prune.append(3)
ind_prune
# out :: [1, 3]

# List like string to real list
# https://stackoverflow.com/questions/20250396/converting-string-that-looks-like-a-list-into-a-real-list-python
import ast
ast.literal_eval("['MI3', 'MI4']")
# out : ['MI3', 'MI4']

['MI3', 'MI4']

In [ ]:
# Cast string with commas and periods to float
# https://stackoverflow.com/questions/6633523/how-can-i-convert-a-string-with-dot-and-comma-into-a-float-in-python/6633912

### Dictionaries

In [ ]:
# https://www.pythonforbeginners.com/dictionary/python-dictionary-quick-guide
# https://python-course.eu/python-tutorial/dictionaries.php
# http://doc.pyschools.com/html/dictionary.html
# https://sparkbyexamples.com/python-tutorial/python-iterate-over-a-dictionary/
# https://www.learnpython.org/en/Dictionaries

# Access 

In [ ]:
# Sum lists, unknown number of arguments
custom_function = lambda *args: reduce(lambda x, y: x and y, args, True)

custom_function = lambda *args: all(args)
custom_function(1, 2, 3, 0)

# custom_function = lambda *args: 

False

In [ ]:
# return elements from a list as arguments
# https://stackoverflow.com/questions/3941517/converting-list-to-args-when-calling-function/3941529
a = [1, 2, 3, 4, 5]
b = [2, 2, 9, 0, 9]
c = [3, 2, 12, 0, 9]
d = [a,b,c]
print(*d)

[1, 2, 3, 4, 5] [2, 2, 9, 0, 9] [3, 2, 12, 0, 9]


In [ ]:
# index of last non-zero element in an array
# https://stackoverflow.com/questions/41346403/return-index-of-last-non-zero-element-in-list
import numpy as np
a = [0,0,1,1,1]
np.max(np.nonzero(a))

4

In [ ]:
# Iterator to List
# https://stackoverflow.com/questions/3790848/fastest-way-to-convert-an-iterator-to-a-list
aSet = set("geeks")
print(type(aSet))
for x in aSet:
    print(x)

# Method A
print([*aSet])
# Method B
list(aSet)

<class 'set'>
s
k
g
e
['s', 'k', 'g', 'e']


['s', 'k', 'g', 'e']

#####  ____ Sum terms of a list. Can also use other basic methods such as product, etc.

In [ ]:
#  sum lists by element - https://therenegadecoder.com/code/how-to-sum-elements-of-two-lists-in-python/
a = [3,0,0,1]
b = [7,0,1,0]
c = [22,1,0,1]

# Method A
# Method B
methB = [x + y + z for x, y, z in zip(a, b, c)]
print(methB)
# Method C
import operator
methC = list(map(operator.add, a, b)) # only works w/ two lists at a time. "list() used to view map object"
print(methC)
# Method D (mine)
methD = list(map(lambda pair: sum(pair), zip(a, b, c)))
print(methD)

[32, 1, 1, 2]
[10, 0, 1, 1]
[32, 1, 1, 2]


#### Print a column in a 2D List

In [ ]:
# https://www.kite.com/python/answers/how-to-extract-a-column-from-a-multidimensional-array-in-python
an_array = [[1,2,3],
            [4,5,6],
            [7,8,9]]

for x in [row[1] for row in an_array]:
    print(x)

2
5
8


In [ ]:
# multidimentional list column or row
c5train = [["19.0_01_07", 1],  
           ["20.0_01_14", 2],  
           ["20.0_02_22", 3],
           ["28.0_02_13", 3],
           ["29.0_01_11", 1]]

c5train[:][:]

[['19.0_01_07', 1],
 ['20.0_01_14', 2],
 ['20.0_02_22', 3],
 ['28.0_02_13', 3],
 ['29.0_01_11', 1]]

In [ ]:
c5train[0]  # row 0

['19.0_01_07', 1]

In [ ]:
# https://stackoverflow.com/questions/903853/how-do-you-extract-a-column-from-a-multi-dimensional-array
list(np.array(c5train).transpose()[0])

['19.0_01_07', '20.0_01_14', '20.0_02_22', '28.0_02_13', '29.0_01_11']

In [ ]:
np.asmatrix(np.array(c5train))[:,0]

matrix([['19.0_01_07'],
        ['20.0_01_14'],
        ['20.0_02_22'],
        ['28.0_02_13'],
        ['29.0_01_11']], dtype='<U10')

In [ ]:
# map(None, *[np.array(c5train)])[0]

In [ ]:
# zip method

# Data Types (General) ---------------------------------

In [ ]:
# https://docs.python.org/3/library/stdtypes.html#truth-value-testing
#    ONLY BOOL and len = 0 of types are FALSE
# All Types here https://www.kite.com/python/examples/3316/types-check-if-a-value-is-a-boolean

In [ ]:
# Get data type
a_string = "some text"
type(a_string)

str

In [ ]:
# Panda Dataframe
# below is duplicated code, except for last line
import pandas as pd
# Creating
## e.g. 1
df = pd.DataFrame({"A":[34,12,78,84,26], 
                   "B":[54,87,35,25,82], 
                   "C":[56,78,0,14,13], 
                   "D":[0,23,72,56,14], 
                   "E":[78,12,31,0,34]})
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       5 non-null      int64
 1   B       5 non-null      int64
 2   C       5 non-null      int64
 3   D       5 non-null      int64
 4   E       5 non-null      int64
dtypes: int64(5)
memory usage: 328.0 bytes


## Iterables

In [ ]:
# access the index w/i a for loop
# https://stackoverflow.com/questions/522563/accessing-the-index-in-for-loops
ints = [8, 23, 45, 12, 78]
for idx, val in enumerate(ints):
    print('item #{} = {}'.format(idx, val))

item #0 = 8
item #1 = 23
item #2 = 45
item #3 = 12
item #4 = 78


# Strings --------------------------------------

In [ ]:
# Substrings : 
# https://www.dotnetperls.com/substring-python
# https://developers.google.com/edu/python/strings

# https://stackoverflow.com/questions/11279331/what-does-the-u-symbol-mean-in-front-of-string-values
# sentence = nlp(u'The quick-brown-fox jumps over the lazy dog. The quick brown fox eats well. \
#                the quickbrownfox is dead. the dog misses the quick brownfox')
# Creates a UNICODE string, also uses the "\"
# Format float values to "n" places.
#    http://randlet.com/blog/python-significant-figures-format/
# Constants: https://docs.python.org/3/library/string.html

#### Percent sign

In [ ]:
# Printing strings using % sign
# https://www.learnpython.org/en/String_Formatting
# https://realpython.com/python-formatted-output/     *** many good examples ***
# %s - String (or any object with a string representation, like numbers)
# %d - Decimal Integers
# %f or %F - Floating point numbers
# %.<number of digits>f - Floating point numbers with a fixed amount of digits to the right of the dot.
# %x/%X - Integers in hex representation (lowercase/uppercase)
# %b - binary
# %c - single character
# %e or %E - Exponential
# %g or %G - Floating Point or Exponential
# %o - Octal
# %% - percentage

name = "John"
age = 23
print("%s is %d years old." % (name, age))

John is 23 years old.


In [ ]:
# exception A
x = 1e300 * 1e300
print("Exept A: ", x)

# exception B
print("Exept B: ",'{:g}'.format(x))

# exception C
print("Exept C: ",'{:g}'.format(x * 0))

# exception D
print("Exept D: ",'{:G}'.format(x))

# exception E
print("Exept E: ",'{:G}'.format(x * 0))

Exept A:  inf
Exept B:  inf
Exept C:  nan
Exept D:  INF
Exept E:  NAN


#### Replacement field

In [ ]:
# Replacement Field
# https://www.geeksforgeeks.org/python-format-function/
ints = [8, 23, 45, 12, 78]
for idx, val in enumerate(ints):
    print('item #{} = {}'.format(idx, val))

item #0 = 8
item #1 = 23
item #2 = 45
item #3 = 12
item #4 = 78


In [ ]:
# left, center, right alignment
print("{0:^16} was founded in {1:<4}!"
        .format("GeeksforGeeks", 2009)) 

print("{:*^20s}".format("Geeks")) 

print("It is {0:5} degrees outside !"
                        .format(40)) 

 GeeksforGeeks   was founded in 2009!
*******Geeks********
It is    40 degrees outside !


In [ ]:
# Function prints out values 
# in an unorganized manner 
def unorganized(a, b): 
    for i in range (a, b): 
        print ( i, i**2, i**3, i**4 ) 
  
# Function prints the organized set of values 
def organized(a, b): 
    for i in range (a, b): 
  
        # Using formatters to give 6  
        # spaces to each set of values 
        print("{:6d} {:6d} {:6d} {:6d}"
        .format(i, i ** 2, i ** 3, i ** 4)) 
  
# Driver Code 
n1 = int(input("Enter lower range :-\n")) 
n2 = int(input("Enter upper range :-\n")) 
  
print("------Before Using Formatters-------") 
  
# Calling function without formatters 
unorganized(n1, n2) 
  
print() 
print("-------After Using Formatters---------") 
print() 
  
# Calling function that contains 
# formatters to organize the data 
organized(n1, n2) 

Enter lower range :-
1
Enter upper range :-
6
------Before Using Formatters-------
1 1 1 1
2 4 8 16
3 9 27 81
4 16 64 256
5 25 125 625

-------After Using Formatters---------

     1      1      1      1
     2      4      8     16
     3      9     27     81
     4     16     64    256
     5     25    125    625


#### f-String Literal

In [ ]:
# https://www.geeksforgeeks.org/formatted-string-literals-f-strings-python/
name = 'Tushar'
age = 23
print(f"Hello, My name is {name} and I'm {age} years old.") 

Hello, My name is Tushar and I'm 23 years old.


# Panda DataFrames -----------------------------

##### ***** LEFT OFF HERE *****

### Creation

In [ ]:
import pandas as pd
# Creating
## e.g. 1
df = pd.DataFrame({"A":[34,12,78,84,26], 
                   "B":[54,87,35,25,82], 
                   "C":[56,78,0,14,13], 
                   "D":[0,23,72,56,14], 
                   "E":[78,12,31,0,34]})

## e.g. 2. from list of lists
dataset = [['Milk', 'Beer', 'Diapers'],
           ['Bread', 'Butter', 'Milk'],
           ['Milk', 'Diapers', 'Cookies'],
           ['Bread', 'Butter', 'Cookies'],
           ['Beer', 'Cookies', 'Diapers'],
           ['Milk', 'Diapers', 'Bread', 'Butter'],
           ['Bread', 'Butter', 'Diapers'],
           ['Beer', 'Diapers'],
           ['Milk', 'Diapers', 'Bread', 'Butter'],
           ['Beer', 'Cookies']]
df2 = pd.DataFrame(dataset)  

## e.g. 3. using 'index'
df3 = pd.DataFrame({'Name': ['Geeks', 'Peter', 'James', 'Jack', 'Lisa'], 
                    'Team': ['Boston', 'Boston', 'Boston', 'Chele', 'Barse'], 
                    'Position': ['PG', 'PG', 'UG', 'PG', 'UG'], 
                    'Number': [3, 4, 7, 11, 5], 
                    'Age': [33, 25, 34, 35, 28], 
                    'Height': ['6-2', '6-4', '5-9', '6-1', '5-8'], 
                    'Weight': [89, 79, 113, 78, 84], 
                    'College': ['MIT', 'MIT', 'MIT', 'Stanford', 'Stanford'], 
                    'Salary': [99999, 99994, 89999, 78889, 87779]}, 
                    index =['ind1', 'ind2', 'ind3', 'ind4', 'ind5']) 
print(df3, "\n") 

       Name    Team Position  Number  Age Height  Weight   College  Salary
ind1  Geeks  Boston       PG       3   33    6-2      89       MIT   99999
ind2  Peter  Boston       PG       4   25    6-4      79       MIT   99994
ind3  James  Boston       UG       7   34    5-9     113       MIT   89999
ind4   Jack   Chele       PG      11   35    6-1      78  Stanford   78889
ind5   Lisa   Barse       UG       5   28    5-8      84  Stanford   87779 



In [ ]:
# Load from File
# CSVs : https://chrisalbon.com/python/data_wrangling/pandas_dataframe_importing_csv/
# df.to_csv('pandas_dataframe_importing_csv/example.csv')
# df = pd.read_csv('pandas_dataframe_importing_csv/example.csv')
# df = pd.read_csv('pandas_dataframe_importing_csv/example.csv', header=None)
# df = pd.read_csv('pandas_dataframe_importing_csv/example.csv', names=['UID', 'First Name', 'Last Name', 'Age', 'Pre-Test Score', 'Post-Test Score'])
# UID set as index
# df = pd.read_csv('pandas_dataframe_importing_csv/example.csv', index_col='UID', names=['UID', 'First Name', 'Last Name', 'Age', 'Pre-Test Score', 'Post-Test Score'])
# First, Last as index
# df = pd.read_csv('pandas_dataframe_importing_csv/example.csv', index_col=['First Name', 'Last Name'], names=['UID', 'First Name', 'Last Name', 'Age', 'Pre-Test Score', 'Post-Test Score'])

In [ ]:
# Show ALL rows of dataframe in Jupyter notebook 2021.09.06 - 10.28
# https://stackoverflow.com/questions/46554597/how-to-display-all-rows-in-jupyter-notebook
pd.options.display.max_rows = None

In [ ]:
# Set Column Names
#    While loading CSV: https://stackoverflow.com/questions/31645466/give-column-name-when-read-csv-file-pandas


A   B   C   D   E
0  34  54  56   0  78
1  12  87  78  23  12
2  78  35   0  72  31
3  84  25  14  56   0
4  26  82  13  14  34

In [ ]:
### From String to DataFrame
# https://stackoverflow.com/questions/54102980/convert-a-tab-and-newline-delimited-string-to-pandas-dataframe/54103026
orderbook = '51,573.38 0.1196 4.0636\n51,573.34 0.2684 3.9440\n51,572.72 0.0354 3.6755\n51,572.00 0.0240 3.6401\n51,571.81 0.1222 3.6161\n51,571.78 0.0010 3.4939\n51,571.00 0.1401 3.4929\n51,570.53 0.0010 3.3528\n51,570.11 1.9615 3.3519\n51,570.00 1.3903 1.3903\nLAST TRADED PRICE\n51,569.52\nBinance\n51,640.00 3.2589 3.2589\n51,639.00 0.3067 3.5656\n51,638.00 2.9862 6.5518\n51,637.00 0.0017 6.5535\n51,636.00 0.0166 6.5701\n51,635.00 0.0266 6.5967\n51,634.50 1.8321 8.4288\n51,634.00 0.3824 8.8112\n51,633.00 4.7007 13.5119\n51,632.00 6.2184 19.7303'
from io import StringIO
import pandas as pd
ob = pd.read_csv(StringIO(orderbook), sep=' ', header=None)
ob.head()

0       1       2
0  51,573.38  0.1196  4.0636
1  51,573.34  0.2684  3.9440
2  51,572.72  0.0354  3.6755
3  51,572.00  0.0240  3.6401
4  51,571.81  0.1222  3.6161

In [ ]:
# Weighted Average of a column in Dataframe (Method 3 from link below) 2021.09.06 - 11.00
# https://towardsdatascience.com/3-ways-to-compute-a-weighted-average-in-python-4e066de7a719
btc_dataset = [[51573.38, 0.1196],
			   [51573.34, 0.2684],
			   [51572.72, 0.0354],
			   [51572.00, 0.0240],
			   [51571.81, 0.1222]]


df_btc_prices = pd.DataFrame(btc_dataset, columns=['price','size'])
print(df_btc_prices)

from numpy import average
# Column names https://www.statology.org/pandas-dataframe-header/ 2021.09.06 - 11.29)
weighted_price = round(average(df_btc_prices['price'], weights = df_btc_prices['size']),2) # Weighted Price
weighted_price

      price    size
0  51573.38  0.1196
1  51573.34  0.2684
2  51572.72  0.0354
3  51572.00  0.0240
4  51571.81  0.1222


51572.93

### Review DataFrame

#### Size

In [ ]:
# Dimentions
df2.size  #total # of cels

40

In [ ]:
df2.shape # (rows by columns, index = 0)

(10, 4)

In [ ]:
df2.ndim # Number of Dimentions

2

#### Types

In [ ]:
# Types in Dataframe
df3.dtypes

Name        object
Team        object
Position    object
Number       int64
Age          int64
Height      object
Weight       int64
College     object
Salary       int64
dtype: object

#### View Some of Data

In [ ]:
# Check some of the data
df.head()
df.head(2)
df.tail()
df.tail(3)

A   B   C   D   E
2  78  35   0  72  31
3  84  25  14  56   0
4  26  82  13  14  34

### Slicing Dataframes


In [ ]:
# loc and iloc
# loc : uses last element
# iloc : does NOT use last element
# https://www.shanelynn.ie/select-pandas-dataframe-rows-and-columns-using-iloc-loc-and-ix/
# http://www.learningthemachine.com/2017/08/20/review-pandas-loc-vs-iloc/ 
# http://pytolearn.csd.auth.gr/b4-pandas/40/moddfcols.html (editing DFs)

In [ ]:
df2.iloc[2:4, 1:]  # Rows 2 & 3 (4 dropped), and from Col 1 onward

1        2     3
2  Diapers  Cookies  None
3   Butter  Cookies  None

In [ ]:
df

A   B   C   D   E
0  34  54  56   0  78
1  12  87  78  23  12
2  78  35   0  72  31
3  84  25  14  56   0
4  26  82  13  14  34

In [ ]:
df.loc[:,'D']

0     0
1    23
2    72
3    56
4    14
Name: D, dtype: int64

In [ ]:
df.loc[:,'D'].tolist() # Panda's Dataframe Column to List (1)

[0, 23, 72, 56, 14]

In [ ]:
list(df.loc[:,'D']) # Panda's Dataframe Column to List (2)

[0, 23, 72, 56, 14]

In [ ]:
df.loc[:,'D'].to_numpy() # Pandas Dataframe to Numpy Array (1)

array([ 0, 23, 72, 56, 14], dtype=int64)

In [ ]:
df.loc[:,'D'].array # Pandas Dataframe to Numpy Array ALTERNATE (2)

<PandasArray>
[0, 23, 72, 56, 14]
Length: 5, dtype: int64

In [ ]:
df['docS'] = df['Stimulus'].apply(lambda x: nlp(x))

In [ ]:
# Conditional Testing
# df.loc[:, df.loc['50']>0]  # in all rows, show col where 50 > 0
# WORK IN PROGRESS

In [ ]:
# Return Row based on keyword wearch w/i a column
# https://www.geeksforgeeks.org/get-all-rows-in-a-pandas-dataframe-containing-given-substring/
df3.head()

Name    Team Position  Number  Age Height  Weight   College  Salary
ind1  Geeks  Boston       PG       3   33    6-2      89       MIT   99999
ind2  Peter  Boston       PG       4   25    6-4      79       MIT   99994
ind3  James  Boston       UG       7   34    5-9     113       MIT   89999
ind4   Jack   Chele       PG      11   35    6-1      78  Stanford   78889
ind5   Lisa   Barse       UG       5   28    5-8      84  Stanford   87779

In [ ]:
# return nparray of all instances of 'text' found in DataFrame
df3[df3['Position']=='PG'].index.values

array(['ind1', 'ind2', 'ind4'], dtype=object)

In [ ]:
for x in df3[df3['Position']=='PG'].index.values:
    print(x)

ind1
ind2
ind4


In [ ]:
# Access specific col within a range
print(df3)
print("\n")
for t in df3[1:4].itertuples():
    print(t.Index, t.Name, t.Age)

       Name    Team Position  Number  Age Height  Weight   College  Salary
ind1  Geeks  Boston       PG       3   33    6-2      89       MIT   99999
ind2  Peter  Boston       PG       4   25    6-4      79       MIT   99994
ind3  James  Boston       UG       7   34    5-9     113       MIT   89999
ind4   Jack   Chele       PG      11   35    6-1      78  Stanford   78889
ind5   Lisa   Barse       UG       5   28    5-8      84  Stanford   87779


ind2 Peter 25
ind3 James 34
ind4 Jack 35


In [ ]:
# Match index on multiple columns: https://thispointer.com/python-pandas-select-rows-in-dataframe-by-conditions-on-multiple-columns/  2021.09.06 - 22.14
# btc0[(btc0[0]==51572.72) & (btc0[1]==0.0354)]

In [ ]:
# Drop rows, columns, etc. on 2021.09.06 - 10.08
# https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.drop.html

In [ ]:
# Misc
# Snippets : https://gist.github.com/bsweger/e5817488d161f37dcbd2
# Itterate : https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.itertuples.html
# Subsets : https://medium.com/dunder-data/selecting-subsets-of-data-in-pandas-6fcd0170be9c
# Slicing : https://datacarpentry.org/python-ecology-lesson/03-index-slice-subset/index.html (2020.12.14)
# 6 ways to iterate : https://thispointer.com/pandas-6-different-ways-to-iterate-over-rows-in-a-dataframe-update-while-iterating-row-by-row/

In [ ]:
# https://stackoverflow.com/questions/28914078/filter-out-rows-based-on-list-of-strings-in-pandas
# remove rows with list of matching text(s) from the df

## Sets

In [ ]:
# http://www.java2s.com/Tutorial/Python/0180__Collections/lenreturnsthenumberofelements.htm
s = set(['p', 'c', 'e', 'h', 's', 'o'])
print len(s)

# Frozensets
# https://python-course.eu/sets_frozensets.php

# General
# https://www.programiz.com/python-programming/set#built

# Set to List
# https://stackoverflow.com/questions/6593979/how-to-convert-a-set-to-a-list-in-python/6594009
my_list = [1,2,3,4]
my_set = set(my_list)
my_new_list = list(my_set)
print(my_new_list)

# subset of set
# https://www.programiz.com/python-programming/methods/set/issubset
A = {1, 2, 3}
B = {1, 2, 3, 4, 5}
print(A.issubset(B))

### Numpy

In [ ]:
# Optimization : https://towardsdatascience.com/how-to-make-your-pandas-loop-71-803-times-faster-805030df4f06
# General, rows & cols, etc. : https://www.kdnuggets.com/2017/03/working-numpy-matrices.html
# Cheetsheet, PDF : chrome-extension://gfbliohnnapiefjpjlpjnehglfpaknnc/pages/pdf_viewer.html?r=https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Numpy_Python_Cheat_Sheet.pdf

In [ ]:
# Rows and Colums
nump = np.array([[ 1,  2,  3,  4,  5,  6],
                 [11, 12, 13, 14, 15, 16],
                 [21, 22, 23, 24, 25, 26]])
print("---Select Column 2---", end="\n")
print(nump[:,2])
print("---Select Row 1---", end="\n")
print(nump[1,:])
print("---Dimentions, (rows, col)---", end="\n")
print(nump.shape)

---Select Column 2---
[ 3 13 23]
---Select Row 1---
[11 12 13 14 15 16]
---Dimentions, (rows, col)---
(3, 6)


In [ ]:
# Roll
# https://www.geeksforgeeks.org/numpy-roll-python/
import numpy as np
nump = np.array([[ 1,  2,  3,  4,  5,  6],
                 [11, 12, 13, 14, 15, 16],
                 [21, 22, 23, 24, 25, 26]])

print("---original---", end="\n")
print(nump)
print("---Horizontal all, snakes backwards---", end="\n")
print(np.roll(nump, 3)) # or print(np.roll(nump, 3, axis = 1)) # rotates all rows right
print("---Vertical Roll, all columns, ortholinear---", end="\n")
print(np.roll(nump, 2, axis = 1)) # Rotate columns

---original---
[[ 1  2  3  4  5  6]
 [11 12 13 14 15 16]
 [21 22 23 24 25 26]]
---Horizontal, snakes backwards---
[[24 25 26  1  2  3]
 [ 4  5  6 11 12 13]
 [14 15 16 21 22 23]]
---Vertical Roll, all columns, ortholinear---
[[ 5  6  1  2  3  4]
 [15 16 11 12 13 14]
 [25 26 21 22 23 24]]


In [ ]:
# Roll select Rows or Columns
# https://stackoverflow.com/questions/24794666/numpy-how-to-roll-1-row-in-an-array-of-arrays
grid = np.array([['A', 'D', 'G'],
                 ['B', 'E', 'H'],
                 ['C', 'F', 'I']])

print("---original---", end="\n")
print(grid)
print("---Roll select Rows---", end="\n")
grid[0] = np.roll(grid[0], 1)
print(grid)
print("---Roll select Cols---", end="\n")
# np.roll(grid[0], 1, axis = 0)
grid[:,2] = np.roll(grid[:,2], 1, axis = 0)
print(grid)

---original---
[['A' 'D' 'G']
 ['B' 'E' 'H']
 ['C' 'F' 'I']]
---Roll select Rows---
[['G' 'A' 'D']
 ['B' 'E' 'H']
 ['C' 'F' 'I']]
---Roll select Cols---
[['G' 'A' 'I']
 ['B' 'E' 'D']
 ['C' 'F' 'H']]


In [ ]:
# Index of last non-zero value in Numpy array
# https://stackoverflow.com/questions/41346403/return-index-of-last-non-zero-element-in-list
# import numpy as np
print(np.max(np.nonzero([-2, -2, 0, 0, 0, 0, 0])))
print(np.max(np.nonzero([-2, 20, -1, 0, 3, 0, 0])))

1
4


In [ ]:
# Return np array of zeros with a single "1" at index.
# https://stackoverflow.com/questions/62704924/how-do-i-create-a-numpy-n-dimensional-array-of-zeros-with-only-a-single-element
# np.bincount([pos],None,length)
print("---1D---", end="\n")
print(np.bincount([2],None,7))
print("---2D---", end="\n")
shp = 3,4
pos = 1,2
np.bincount([np.ravel_multi_index(pos,shp)],None,np.prod(shp)).reshape(shp)

---1D---
[0 0 1 0 0 0 0]
---2D---


array([[0, 0, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 0]], dtype=int64)

In [ ]:
np.bincount([20],None,7)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
      dtype=int64)

In [ ]:
# Is array has any elements that are not zero
# https://www.geeksforgeeks.org/python-check-if-all-values-in-numpy-are-zero/
# import numpy as np
ini_array1 = np.array([1, 2, 3, 4, 5, 6, 0]) 
ini_array2 = np.array([0, 0, 0, 0, 0, 0]) 

print(np.any(ini_array1))
print(np.any(ini_array2))
print("---negates all 'zeros' to return a True---", end="\n")
print(not np.any(ini_array2))

True
False
---negates all 'zeros' to return a True---
True


In [ ]:
# repeated element in list x times
# https://stackoverflow.com/questions/3459098/create-list-of-single-item-repeated-n-times
# --- method 1 ---
[0] * 5

[0, 0, 0, 0, 0]

# Command Flow

## For Loops

In [ ]:
# Will not run, from Quiz 2
for i in range(len(X_tr_data.index)):
    w1 += X_tr_data.loc[i,'Lagrange'] * X_tr_data.loc[i,'X1'] * X_tr_data.loc[i,'y'] 
    w2 += X_tr_data.loc[i,'Lagrange'] * X_tr_data.loc[i,'X2'] * X_tr_data.loc[i,'y']

NameError: ignored

### If, thens, etc.

In [ ]:
# https://anh.cs.luc.edu/python/hands-on/3.1/handsonHtml/ifstatements.html

In [ ]:
# https://pythonexamples.org/python-if-or/
today = 'Wednesday'

if today=='Sunday' or today=='Saturday':
	print('Today is off. Rest at home.')
else:
	print('Go to work.')

Go to work.


## Linear Regression (sklearn)

In [ ]:
# Setup 
# Ch 04 : Linear Regression
from sklearn import datasets
data = datasets.load_boston()
df = pd.DataFrame(data.data, columns=data.feature_names)
target = pd.DataFrame(data.target, columns=["MEDV"])

# Code

from sklearn import linear_model

X = df.loc[:, "RM":"RM"]
y = target["MEDV"]

lm = linear_model.LinearRegression()

model = lm.fit(X, y)
predictions = lm.predict(X)

print("Linear regression score: %f " % lm.score(X, y))

print("Linear model coefficients: %f " % lm.coef_)

print("Linear model y intercept: %f " % lm.intercept_)



/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np


        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the California housing dataset (i.e.

NameError: ignored

# Packages

## SKLearn

## NLTK 

In [ ]:
# STUB
# Fast ngrams (one liner) : https://stackoverflow.com/questions/7591258/fast-n-gram-calculation

## Spacy

In [ ]:
# https://spacy.io/usage
    # had too first elevate cmd prompt to admin in order to install "en_core_web_sm" and similar.
    # https://spacy.io/usage/vectors-similarity
    # ONE LINE: token, dataframe, panda, column : https://www.reddit.com/r/learnpython/comments/78i7rh/tokenizing_using_pandas_and_spacy/
    #    df['new_col'] = df['old_col'].apply(lambda x: nlp(x)) 
    
    # Custom Sentence breaks. https://spacy.io/usage/linguistic-features#sbd-custom

## Seleneum

In [ ]:
# General: https://www.analyticsvidhya.com/blog/2020/08/web-scraping-selenium-with-python/ 2021.09.06 - 20.29
# Element key terms: https://developer.mozilla.org/en-US/docs/Web/API/Element 2021.09.06 - 20.24
# Match Elements
#      from driver: https://selenium-python.readthedocs.io/locating-elements.html 2021.09.06 - 20.25
#      from WebElement: https://www.geeksforgeeks.org/get_attribute-element-method-selenium-python/
# Regex w/ Webelements: https://www.tutorialspoint.com/how-to-use-regular-expressions-in-xpath-in-selenium-with-python 2021.09.06 - 20.28

## html5lib

In [ ]:
# https://anaconda.org/anaconda/html5lib 2021.09.08 - 19.34


# Environments

## Google Colab

### Shortcut Commands

#### Default VIM Commands

* Notes :: Shortcuts
To add or change a shortcut, click the key combination and then type the new keys. Note that 
Ctrl+M can be used as a prefix for multi-key-event shortcuts.   
🛑 = Cannot change default key
* Most Used
 * Ctrl+Space or Tab ➡  Autocomplete 🛑
 * Ctrl+/ ➡ Comment current line 🛑
 * Ctrl+Alt+M ➡ Add a comment
 * Ctrl+M Y ➡ Convert to code cell
 * Ctrl+M M ➡ Convert to text cell
 * Ctrl+M A ➡ Insert code cell above
 * Ctrl+M B ➡ Insert code cell below
 * Ctrl+M - ➡ Split at cursor
 * Ctrl+Shift+/ ➡ Show keyboard shortcuts (aka Ctrl+?)
 * Ctrl+M U ➡ Unfocus current cell
 * Shift+Tab ➡ Unindent current line 🛑
 * Ctrl+Click ➡ Toggle cell selection 🛑
 * Tab ➡ Toggle code docstring help 🛑
 * Navigation
 * Ctrl+M P ➡ Previous cell
 * Ctrl+M N ➡ Next cell
 * Ctrl+M . ➡ Restart runtime
 * Ctrl+' ➡ Toggle expand/collapse current section
 * Set shortcut ➡ Toggle header visibility
 * Ctrl+M L ➡ Toggle line numbers
 * Ctrl+M Z or Ctrl+Shift+Z ➡ Undo last cell action 🛑 

* Move
 * Ctrl+M J ➡ Move selected cells down
 * Ctrl+M K ➡ Move selected cells up
* Save
 * Ctrl+M S ➡ Save and pin revision
 * Ctrl+S ➡ Save notebook
* Run
 * Ctrl+Shift+Enter ➡ Run selection
 * Ctrl+Enter ➡ Run the focused cell
 * Ctrl+F9 ➡ Run all cells in notebook
 * Ctrl+F8 ➡ Run cells before the current
 * Ctrl+F10 ➡ Run selected cell and all cells after
 * Alt+Enter ➡ Run cell and insert new cell
 * Shift+Enter ➡ Run cell and select next cell
* Find/Replace
 * Ctrl+H ➡ Global find/replace
 * Ctrl+G ➡ Find next
 * Ctrl+Shift+G ➡ Find previous
 * Shift+Ctrl+H ➡ Replace all in current cell 🛑
* Selection
 * Ctrl+] ➡ Collapse all/selected sections
 * Shift+Down ➡ Grow selection to include next cell
 * Shift+Up ➡ Grow selection to include previous cell
* Cut/Copy/Paste
 * Ctrl+M C ➡ Copy cell or selection
 * Ctrl+Shift+X ➡ Cut cell or selection
* ???
 * Ctrl+Shift+] ➡ Focus next tab 🛑
 * Ctrl+Shift+[ ➡ Focus previous tab 🛑
 * Set shortcut ➡ Focus the last run cell


### TO SORT (Google Colab Shortcuts)



* Set shortcut ➡ Add a form
* Set shortcut ➡ Add a form field
* Set shortcut ➡ Add code cell
* Set shortcut ➡ Add section header cell
* Set shortcut ➡ Add text cell
* Set shortcut ➡ Clear all outputs
* Set shortcut ➡ Clear selected outputs
* Set shortcut ➡ Comments sidebar
* Set shortcut ➡ Connect to a custom GCE VM
* Set shortcut ➡ Connect to a hosted runtime
* Set shortcut ➡ Connect to a local runtime
* Set shortcut ➡ Connect to a runtime
* Set shortcut ➡ Copy to scratch cell
* Set shortcut ➡ Create new notebook
* Ctrl+M F ➡ Cycle form view
* Ctrl+M D ➡ Delete cell/selection
* Set shortcut ➡ Diff notebooks
* Set shortcut ➡ Disconnect and delete runtime
* Set shortcut ➡ Download .ipynb
* Set shortcut ➡ Download .py
* Set shortcut ➡ Edit form attributes
* Ctrl+[➡ Expand all/selected sections
* Set shortcut ➡ Factory reset all runtimes
* Ctrl+M I ➡ Interrupt execution
* Set shortcut ➡ Jump to cell
* Set shortcut ➡ Locate in Drive
* Set shortcut ➡ Manage sessions
* Set shortcut ➡ Merge focused cell with next cell
* Set shortcut ➡ Merge focused cell with previous cell
* Set shortcut ➡ Merge selected cells
* Set shortcut ➡ Mirror cell in tab
* Set shortcut ➡ Mount Drive
* Set shortcut ➡ Move left pane to a tab
* Set shortcut ➡ Move notebook in Drive
* Set shortcut ➡ Move notebook to trash
* Set shortcut ➡ Move tab to next pane
* Set shortcut ➡ Move tab to previous pane
* Set shortcut ➡ Open comments pane
* Set shortcut ➡ Open editor settings
* Set shortcut ➡ Open in playground mode
* Ctrl+O ➡ Open notebook
* Set shortcut ➡ Open notebook settings
* Ctrl+Alt+N ➡ Open scratch code cell
* Set shortcut ➡ Open settings
* Ctrl+P ➡ Print notebook
* Set shortcut ➡ Reconnect
* Ctrl+Shift+Y ➡ Redo cell action
* Set shortcut ➡ Restart runtime and run all cells in notebook
* Set shortcut ➡ Save a copy as a GitHub Gist
* Set shortcut ➡ Save a copy in Drive
* Set shortcut ➡ Save a copy in GitHub
* Set shortcut ➡ Save the collapsed section layout
* Ctrl+Shift+A ➡ Select all cells
* Ctrl+Shift+S ➡ Select focused cell
* Shift+Click ➡ Select multiple cells 🛑
* Set shortcut ➡ Share notebook
* Ctrl+Alt+P ➡ Show code snippets pane
* Ctrl+Shift+P ➡ Show command palette
* Set shortcut ➡ Show executed code history
* Set shortcut ➡ Show file browser
* Set shortcut ➡ Show notebook file information
* Set shortcut ➡ Show revision history
* Set shortcut ➡ Show scheduled notebooks
* Set shortcut ➡ Show table of contents
* Set shortcut ➡ Show terminal
* Set shortcut ➡ Show variable inspector
* Set shortcut ➡ Show/hide code
* Ctrl+M O ➡ Show/hide output
* Set shortcut ➡ Show/hide status bar
* Set shortcut ➡ Star/unstar notebook in Google Drive
* Set shortcut ➡ Unmount Drive
* Set shortcut ➡ Upload notebook
* Set shortcut ➡ View notebook JSON
* Set shortcut ➡ View notebook source
* Set shortcut ➡ View output fullscreen
* Set shortcut ➡ View resources
* Set shortcut ➡ View runtime logs
* Set shortcut ➡ View single tabbed layout
* Set shortcut ➡ View tabs in two columns
* Set shortcut ➡ View tabs in two rows

## Jupyter Notebook

In [ ]:
# No lines of text wrapping
# https://stackoverflow.com/questions/53482343/how-to-disable-line-wrapping-in-jupyter-notebook-output-cells
from IPython.core.display import display, HTML
display(HTML("<style>div.output_area pre {white-space: pre;}</style>"))
print(" ;klajsd;lj as;ldkjf; aslkdjf;lj laskjdf ;laskjdf;lk jasdflkjasldfj;ksjdf;jkasdfklj;asdkfj;j;asdjkf;ljksadf;kj;aslkdjf")

 ;klajsd;lj as;ldkjf; aslkdjf;lj laskjdf ;laskjdf;lk jasdflkjasldfj;ksjdf;jkasdfklj;asdkfj;j;asdjkf;ljksadf;kj;aslkdjf


In [ ]:
# Jupyter Lab/Notebook - Time Progress Bars 2021.09.06 - 23.43
# https://towardsdatascience.com/progress-bars-in-python-4b44e8a4c482
# conda install -c conda-forge ipywidgets , from https://ipywidgets.readthedocs.io/en/latest/user_install.html 2021.09.06 - 23.47
#   Requires Node.js, https://jupyterlab.readthedocs.io/en/stable/user/extensions.html
#   Also install TQDM: conda install -c conda-forge tqdm , https://github.com/tqdm/tqdm#latest-conda-release

## Command Prompt

In [ ]:
activate LAYER
jupyter notebook
jupyter lab
pip list # Display all packages and versions installed  # https://www.activestate.com/resources/quick-reads/how-to-list-installed-python-packages/ 2021.09.07 - 21.16
conda list # same as above



# TO SORT

In [ ]:
### Decision Trees
# http://adataanalyst.com/scikit-learn/decision-trees-scikit-learn/
# Weights in Decision Trees :: https://stackoverflow.com/questions/34389624/what-does-sample-weight-do-to-the-way-a-decisiontreeclassifier-works-in-skle
# Jupyter Notebook Pixie debugger
# https://medium.com/ibm-watson-data-lab/the-visual-python-debugger-for-jupyter-notebooks-youve-always-wanted-761713babc62
#     Not working on Windows : https://stackoverflow.com/questions/48825695/permission-denied-error-while-installing-pixiedust-jupyter?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa

In [ ]:
# File Operations
# Iterating over a file (by line, etc.)
# http://interactivepython.org/runestone/static/thinkcspy/Files/AlternativeFileReadingMethods.html

# Zip, Map, Lambda : https://bradmontgomery.net/blog/pythons-zip-map-and-lambda/
# Zip : https://www.saltycrane.com/blog/2007/12/iterating-through-two-lists-in-parallel/
# https://medium.com/@happymishra66/zip-in-python-48cb4f70d013

# TF-IDF
# http://www.bogotobogo.com/python/NLTK/tf_idf_with_scikit-learn_NLTK.php
# http://www.tfidf.com/

# IDEs :
# Grasshopper : https://discourse.mcneel.com/t/filter-remove-empty-lists-python/34594/5
# http://developer.rhino3d.com/guides/

In [ ]:
# Elegance
# One Line Loops : http://blog.teamtreehouse.com/python-single-line-loops
# Not all : https://stackoverflow.com/questions/31154372/what-is-the-best-way-to-check-if-a-tuple-has-any-empty-none-values-in-python
# Filter / None : https://stackoverflow.com/questions/30791880/python-map-function-lambda-involving-conditionals-if
# Filter : https://stackoverflow.com/questions/4842956/python-how-to-remove-empty-lists-from-a-list
# Pep 8 Stile Guidelines : https://www.python.org/dev/peps/pep-0008/    (originally for sequences )
#       https://www.quora.com/What-is-the-Pythonic-way-to-check-for-an-empty-set
# Regex Match: one line: https://blog.finxter.com/python-one-line-regex-match/ 2021.09.06 - 20.15
# One line if/else: 2021.09.06 - 20.22
#       https://www.pythoncentral.io/one-line-if-statement-in-python-ternary-conditional-operator/
#       https://thispointer.com/python-if-else-in-one-line-a-ternary-operator/

In [ ]:
# One Line code, removing first letter and only printing the first three.  2021.09.06 - 20.48
[d[1:] for d in ['zero','one','two','three','four','five'][0:3]]

['ero', 'ne', 'wo']

In [ ]:
# Var tracer
from IPython.core.debugger import set_trace

def add_to_life_universe_everything(x):
    answer = 42
    set_trace()
    answer += x
    
    return answer

add_to_life_universe_everything(12)

# Jupyter Notebook helpers : https://github.com/minrk/ipython_extensions

In [ ]:
# Environment 
# print(mlxtend.__version__)  # https://stackoverflow.com/questions/20180543/how-to-check-version-of-python-modules?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa


In [ ]:
# Algorithms:
#    Apriori and Association Rules : https://algobeans.com/2016/04/01/association-rules-and-the-apriori-algorithm/
#   https://rasbt.github.io/mlxtend/user_guide/frequent_patterns/association_rules/
# General :
#    https://www.springboard.com/blog/data-mining-python-tutorial/

In [ ]:
# Great Tutorials :
#   CountVectorizer and TFIDF : https://www.kaggle.com/pceccon/countvectorizer-and-tfidf-strategies

In [ ]:
#http://intelligentonlinetools.com/blog/2018/02/10/how-to-create-data-visualization-for-association-rules-in-data-mining/

C:\Users\Conda\Anaconda3\lib\site-packages\mlxtend\preprocessing\onehot.py:66: DeprecationWarning: OnehotTransactions has been deprecated and will be removed in future. Please use TransactionEncoder instead.
  warnings.warn(msg, DeprecationWarning)


   Apple   Corn   Dill   Eggs  Ice cream  Kidney Beans   Milk  Nutmeg  Onion  \
0  False  False  False   True      False          True   True    True   True   
1  False  False   True   True      False          True  False    True   True   
2   True  False  False   True      False          True   True   False  False   
3  False   True  False  False      False          True   True   False  False   
4  False   True  False   True       True          True  False   False   True   

   Unicorn  Yogurt  
0    False    True  
1    False    True  
2    False   False  
3     True    True  
4    False   False  
    support                     itemsets
0       0.8                       [Eggs]
1       1.0               [Kidney Beans]
2       0.6                       [Milk]
3       0.6                      [Onion]
4       0.6                     [Yogurt]
5       0.8         [Eggs, Kidney Beans]
6       0.6                [Eggs, Onion]
7       0.6         [Kidney Beans, Milk]
8       0.6        [Kidn

C:\Users\Conda\Anaconda3\lib\site-packages\networkx\generators\expanders.py:71: DeprecationWarning: invalid escape sequence \s
  """
C:\Users\Conda\Anaconda3\lib\site-packages\networkx\generators\geometric.py:266: DeprecationWarning: invalid escape sequence \l
  """
C:\Users\Conda\Anaconda3\lib\site-packages\networkx\generators\geometric.py:736: DeprecationWarning: invalid escape sequence \l
  """
C:\Users\Conda\Anaconda3\lib\site-packages\networkx\algorithms\centrality\current_flow_betweenness.py:319: DeprecationWarning: invalid escape sequence \l
  """
C:\Users\Conda\Anaconda3\lib\site-packages\networkx\algorithms\cluster.py:424: DeprecationWarning: invalid escape sequence \m
  """
C:\Users\Conda\Anaconda3\lib\site-packages\networkx\algorithms\reciprocity.py:47: DeprecationWarning: invalid escape sequence \i
  """
C:\Users\Conda\Anaconda3\lib\site-packages\networkx\algorithms\shortest_paths\weighted.py:1948: DeprecationWarning: invalid escape sequence \p
  """
C:\Users\Conda\Anaconda

TypeError: add_nodes_from() missing 1 required positional argument: 'nodes_for_adding'