<h1>LAB 1 - TOÁN ỨNG DỤNG VÀ THỐNG KÊ - 18CLC<h1/>

# Nội dung

* Cách đánh giá điểm thực hành
* Cài đặt và dùng JupyterLab
* Python và các thư viện tính toán khoa học
* Vector và các phép toán trên vector
* Giới thiệu ma trận
* Hệ PTTT và phép khử Gauss
* Không gian con, cơ sở và số chiều
* Trực giao hóa với thuật giải Gram-Schmidt
* Bài tập

# Cách đánh giá điểm thực hành

* Điểm thực hành chiếm 40% điểm tổng kết môn học
* Gồm 4 đồ án cá nhân, mỗi đồ án 10% điểm tổng kết
* Nội dung và yêu cầu của từng đồ án được các GVHDTH thông báo và hướng dẫn chi tiết trong các buổi Lab

# Cài đặt và dùng JupyterLab

[Anaconda](https://www.anaconda.com/) là môi trường quản lý các công cụ, thư viện, package, module Python/R cho **tính toán khoa học** (scientific computing) và **khoa học dữ liệu** (data science). Anaconda hỗ trợ hầu hết các nền tảng (Windows, macOS, Linux). Tải và cài đặt phiên bản cá nhân ([Individual Edition](https://www.anaconda.com/products/individual)) miễn phí. Lưu ý, nên dùng bản hỗ trợ Python mới nhất (Python 3.7).

[Jupyter](https://jupyter.org/) là nền tảng, dịch vụ **tính toán tương tác** (interactive computing) hỗ trợ rất nhiều ngôn ngữ (Julia, Python, R, ...). [Jupyter Notebook](https://jupyter-notebook.readthedocs.io/en/stable/), hay mới hơn là [JupyterLab](https://jupyterlab.readthedocs.io/en/latest/), là các ứng dụng Web giúp làm việc với các file notebook. Anaconda tự động cài Jupyter Notebook và JupyterLab. 

[Jupyter notebook](https://jupyterlab.readthedocs.io/en/latest/user/notebook.html) (file `.ipynb`) là tài liệu kết hợp nhiều định dạng: văn bản thô, văn bản có định dạng, biểu đồ, công thức, ... và đặc biệt là **mã thực thi** (code) có thể được viết bằng nhiều ngôn ngữ khác nhau. Jupyter notebook là tài liệu động và có tính tương tác nên rất phù hợp với các văn bản, trình bày tính toán khoa học. Jupyter notebook cũng có thể được kết xuất ra nhiều định dạng phổ biến khác nhau (PDF, HTML, LaTex, ...).

Jupyter notebook hỗ trợ định dạng văn bản [Markdown](https://www.markdownguide.org/basic-syntax/) và [HTML](https://www.w3schools.com/html/); hỗ trợ định dạng công thức Toán [LaTeX](https://en.wikibooks.org/wiki/LaTeX/Mathematics). Tham khảo nhanh tại [Learn How to Write Markdown & LaTeX in The Jupyter Notebook](https://towardsdatascience.com/write-markdown-latex-in-the-jupyter-notebook-10985edb91fd).

# Python và các thư viện tính toán khoa học

[Python](https://www.python.org/) là ngôn ngữ lập trình được dùng phổ biến cho tính toán khoa học (và nhiều mục đích khác). Tài liệu tra cứu chính thống của Python được để ở [Python documentation](https://docs.python.org/3/index.html). Có thể dùng hướng dẫn [The Python Tutorial](https://docs.python.org/3/tutorial/) để học nhanh Python. Có thể dùng sách [Bí kíp luyện Lập trình nhập môn với Python (hBook)](https://github.com/vqhBook/python) để học kĩ Python căn bản. Ngoài ra, có thể dùng một số nguồn tham khảo khác như [Python3 Tutorial](https://www.python-course.eu/python3_course.php), [Numerical Programming with Python](https://www.python-course.eu/numerical_programming_with_python.php), [GeeksforGeeks](https://www.geeksforgeeks.org/python-programming-language/), ...

Các thư viện Python phổ biến dùng trong tính toán khoa học là: [NumPy](https://numpy.org/), [SciPy](https://www.scipy.org/), [SymPy](https://www.sympy.org/en/index.html), [pandas](https://pandas.pydata.org/), [scikit-learn](https://scikit-learn.org/stable/), [Matplotlib](https://matplotlib.org/), ... Các thư viện này sẽ được giới thiệu, hướng dẫn và dùng trong các buổi Lab, đồ án.

NumPy và SciPy là các thư viện **tính toán số** (numeric computation) giúp tính xấp xỉ nhưng hiệu quả với khối lượng tính toán lớn. Có thể học nhanh NumPy tại [NumPy - the absolute basics for beginners](https://numpy.org/doc/stable/user/absolute_beginners.html).

SymPy là thư viện **tính toán ký hiệu** (symbolic computation) giúp tính chính xác và hình thức với khối lượng tính toán nhỏ. Có thể học nhanh SymPy tại [SymPy Introduction](https://docs.sympy.org/latest/tutorial/intro.html) và [SymPy Matrices](https://docs.sympy.org/latest/tutorial/matrices.html).

Tra cứu các hỗ trợ cho **đại số tuyến tính** (linear algebra) tại:

* [Linear algebra (numpy.linalg)](https://numpy.org/doc/stable/reference/routines.linalg.html#)

* [Linear algebra (scipy.linalg)](https://docs.scipy.org/doc/scipy/reference/linalg.html#module-scipy.linalg)

* [SymPy Matrices (linear algebra)](https://docs.sympy.org/latest/modules/matrices/matrices.html)

Sau đây nạp các thư viện có dùng trong Lab này:

* Module [`math`](https://docs.python.org/3/library/math.html) trong thư viện chuẩn Python hỗ trợ các hàm Toán thông dụng.

* Lớp [`fractions.Fraction`](https://docs.python.org/3/library/fractions.html) trong thư viện chuẩn Python hỗ trợ kiểu phân số dùng để tính toán chính xác.

* Các thư viện `numpy`, `scipy`, `sympy`.

* Ngoài ra, hàm `to_fraction` giúp tạo phân số (từ chuỗi, số nguyên, danh sách các số, ...) khi muốn tính toán chính xác và hàm `myprint` giúp "xuất đẹp" các danh sách (vector, tập vector, ma trận).

In [2]:
import math
from fractions import Fraction
import numpy as np
import scipy.linalg
import sympy
from sympy import Matrix

sympy.init_printing()

def to_fraction(x):
    if isinstance(x, list):
        return [to_fraction(e) for e in x]
    else:
        return Fraction(x)

def myprint(x, sep=" "):
    if isinstance(x, list) and x:
        if isinstance(x[0], list): # list of list
            m, n = len(x), len(x[0])
            widths = [max(len(str(ai[j])) for ai in x) for j in range(n)]
            rows = [sep.join(format(str(ai[j]), f">{widths[j]}") for j in range(n)) for ai in x]
            print("[" + "\n".join((" [" if i > 0 else "[") + rows[i] + "]" for i in range(m)) + "]")
        else: # list
            print("[" + sep.join(str(e) for e in x) + "]")
    else:
        print(x)

# Vector và các phép toán trên vector

Một bộ gồm $n$ số thực (n-tuple) $\boldsymbol{v} = (v_1, v_2, ..., v_n) \in \mathbb{R}^n$ được gọi là một **vector** kích thước $n$. Các số $v_1, v_2, ..., v_n \in \mathbb{R}$ được gọi là các **phần tử** (element, entry) của vector. Để phân biệt với vector, các số thực còn được gọi là **vô hướng** (scalar).

Cách đơn giản nhất để biểu diễn vector là dùng **danh sách** (list) các số. Cách hiệu quả và tiện lợi hơn là dùng **NumPy 1D array**.

In [3]:
v = [1, 2, 3, 4, 5]; w = np.array([1, 2, 3, 4, 5])
print(v, w)
print(v[0], w[-1], v[:2], w[-2:], v[1:4]) # truy cập entry, subvector

[1, 2, 3, 4, 5] [1 2 3 4 5]
1 5 [1, 2] [4 5] [2, 3, 4]


Tùy trường hợp, vector $\boldsymbol{v} = (v_1, v_2, ..., v_n) \in \mathbb{R}^n$ có thể được biểu diễn như là **vector dòng** (row vector) hay **vector cột** (column vector)
$$
\boldsymbol{v} = 
\begin{bmatrix}
v_1 & v_2 & \cdots & v_n
\end{bmatrix} \in \mathbb{R}^{1 \times n},
$$
$$
\boldsymbol{v} = 
\begin{bmatrix}
v_1 \\ v_2 \\ \vdots \\ v_n
\end{bmatrix} \in \mathbb{R}^{n \times 1}.
$$

In [4]:
v = np.array([1, 2, 3])
v_row = v.reshape(1, len(v))
v_col = v.reshape(len(v), 1)
print(v, v.shape)
print(v_row, v_row.shape)
print(v_col, v_col.shape)

[1 2 3] (3,)
[[1 2 3]] (1, 3)
[[1]
 [2]
 [3]] (3, 1)


In [5]:
Matrix([1, 2, 3]) # SymPy xem vector là vector cột (ma trận chỉ có 1 cột)

⎡1⎤
⎢ ⎥
⎢2⎥
⎢ ⎥
⎣3⎦

Vector $\boldsymbol{0} = (0, 0, ..., 0) \in \mathbb{R}^n$ được gọi là **vector không** (zero vector).

2 vector $\boldsymbol{v} = (v_1, v_2, ..., v_n), \boldsymbol{w} = (w_1, w_2, ..., w_n) \in \mathbb{R}^n$ được gọi là **bằng nhau** (equal), kí hiệu $\boldsymbol{v} = \boldsymbol{w}$ nếu $v_i = w_i, \forall i$.

In [6]:
def is_zero(x):
    "kiểm tra số thực x có là số thực 0 (rất gần 0)"
    return math.isclose(x, 0, abs_tol=1e-09)

def zero_vector(n):
    return [0 for _ in range(n)]

def is_zero_vector(v):
    return all(is_zero(vi) for vi in v)

In [7]:
v = zero_vector(3)
print(v, v == 0, v == zero_vector(3), is_zero_vector(v))
w = np.zeros(3)
print(w, w == 0, w == np.zeros(3), is_zero_vector(w))

[0, 0, 0] False True True
[0. 0. 0.] [ True  True  True] [ True  True  True] True


Cho 2 vector $\boldsymbol{v} = (v_1, v_2, ..., v_n), \boldsymbol{w} = (w_1, w_2, ..., w_n) \in \mathbb{R}^n$ và số thực $\alpha \in \mathbb{R}$, ta định nghĩa các phép toán
$$
\boldsymbol{v} + \boldsymbol{w} = (v_1 + w_1, v_2 + w_2, ..., v_n + w_n),
$$
$$
\boldsymbol{v} - \boldsymbol{w} = (v_1 - w_1, v_2 - w_2, ..., v_n - w_n),
$$
$$
\alpha \boldsymbol{v} = (\alpha v_1, \alpha v_2, ..., \alpha v_n).
$$

Cho tập các vector $\boldsymbol{v}_1, \boldsymbol{v}_2, ..., \boldsymbol{v}_k \in \mathbb{R}^n$ và các số $\alpha_1, \alpha_2, ..., \alpha_k \in \mathbb{R}$, ta nói vector
$$
\boldsymbol{w} = \alpha_1 \boldsymbol{v}_1 + \alpha_2 \boldsymbol{v}_2 + ... + \alpha_k \boldsymbol{v}_k
$$

là một **tổ hợp tuyến tính** (linear combination) của $\boldsymbol{v}_1, \boldsymbol{v}_2, ..., \boldsymbol{v}_k$ với các **hệ số** (coefficient) $\alpha_1, \alpha_2, ..., \alpha_k$.

In [8]:
def add_vector(v, w):
    return [vi + wi for vi, wi in zip(v, w)]

def sub_vector(v, w):
    return [vi - wi for vi, wi in zip(v, w)]

def mul_scalar_vector(alpha, v):
    return [alpha*vi for vi in v]

def equal_vector(v, w):
    return is_zero_vector(sub_vector(v, w))

In [9]:
v = [1, -3, 2]; w = [4, 2, 1]
print(add_vector(v, w), mul_scalar_vector(2, v))
print(equal_vector(sub_vector(v, w), add_vector(v, mul_scalar_vector(-1, w))))
v = np.array(v); w = np.array(w)
print(v + w, 2*v)
print(equal_vector(v - w, v + (-1*w)))

[5, -1, 3] [2, -6, 4]
True
[ 5 -1  3] [ 2 -6  4]
True


In [10]:
v = Matrix(v); w = Matrix(w)
print(v - w == v + (-1*w)) # SymPy dùng == để so sánh bằng vector (ma trận)
sympy.symbols("alpha")*v + sympy.symbols("beta")*w

True


⎡ α + 4⋅β  ⎤
⎢          ⎥
⎢-3⋅α + 2⋅β⎥
⎢          ⎥
⎣ 2⋅α + β  ⎦

Lưu ý, các phép toán trên NumPy array được thực hiện **theo từng phần tử** (elementwise) và số được tự động mở rộng thành vector với chiều dài phù hợp.

In [11]:
v = np.array([1, 2, 3]); w = np.array([4, 5, 6])
print(v * w, v / w, v ** w)
print(v + 3, w * 3, -v)
print(2*v < w, v + 3 == w, all(v + 3 == w))

[ 4 10 18] [0.25 0.4  0.5 ] [  1  32 729]
[4 5 6] [12 15 18] [-1 -2 -3]
[ True  True False] [ True  True  True] True


Cho 2 vector $\boldsymbol{v} = (v_1, v_2, ..., v_n), \boldsymbol{w} = (w_1, w_2, ..., w_n) \in \mathbb{R}^n$:

Ta định nghĩa **tích vô hướng** (inner product, dot product) của $\boldsymbol{v}, \boldsymbol{w}$ là
$$
\langle \boldsymbol{v}, \boldsymbol{w} \rangle = v_1w_1 + v_2w_2 + ... + v_n w_n = \sum_{i=1}^n v_i w_i,
$$

In [12]:
def inner_product(v, w):
    return sum(vi*wi for vi, wi in zip(v, w))

Ta nói $\boldsymbol{v}, \boldsymbol{w}$ **trực giao** (orthogonal, perpendicular), kí hiệu $\boldsymbol{v} \bot \boldsymbol{w}$, nếu $\langle \boldsymbol{v}, \boldsymbol{w} \rangle = 0$,

In [13]:
def orthogonal(v, w):
    return is_zero(inner_product(v, w))

Ta định nghĩa **chuẩn** (norm, length, magnitude) của $\boldsymbol{v}$ là
$$
\| \boldsymbol{v} \| = \sqrt{\langle \boldsymbol{v}, \boldsymbol{v} \rangle} = \sqrt{v_1^2 + v_2^2 + ... + v_n^2} = \sqrt{\sum_{i=1}^n v_i^2},
$$

In [14]:
def norm_square(v):
    return inner_product(v, v)

def norm(v):
    return sympy.sqrt(norm_square(v))

Ta nói $\boldsymbol{v}$ là **vector đơn vị** (unit vector) nếu $\| \boldsymbol{v} \| = 1$,

In [15]:
def is_one(v):
    return math.isclose(v, 1)

def unit_vector(v):
    return is_one(norm(v))

Ta định nghĩa **khoảng cách** (distance) giữa $\boldsymbol{v}$ và $\boldsymbol{w}$ là $\| \boldsymbol{v} - \boldsymbol{w} \|$.

In [16]:
def distance(v, w):
    return norm(sub_vector(v, w))

Trong Numpy ta dùng các hàm `inner`, `norm` và toán tử `@`

In [17]:
v = [1, 3, -2, 7]; w = [0, 7, 2, 2]
print(norm(v), float(norm(v)))
v_n = mul_scalar_vector(1/norm(v), v)
print(v_n, unit_vector(v_n))
print(inner_product(v, w), distance(v, w), float(distance(v, w)))

v = np.array(v); w = np.array(w)
print(np.inner(v, w), v @ w)
print(np.sqrt(np.inner(v, v)), np.linalg.norm(v), sum(v**2)**0.5)
print(np.linalg.norm(v - w), np.linalg.norm(w - v))

3*sqrt(7) 7.937253933193772
[sqrt(7)/21, sqrt(7)/7, -2*sqrt(7)/21, sqrt(7)/3] True
31 sqrt(58) 7.615773105863909
31 31
7.937253933193772 7.937253933193772 7.937253933193772
7.615773105863909 7.615773105863909


In [18]:
v = Matrix(v)
(v/v.norm()).T # chuyển vector cột thành vector dòng trong SymPy (xem phần dưới)

⎡√7  √7  -2⋅√7   √7⎤
⎢──  ──  ──────  ──⎥
⎣21  7     21    3 ⎦

# Giới thiệu ma trận

*(Ma trận sẽ được học kĩ trong Lab 2.)*

Một bảng chữ nhật gồm $m$ dòng, $n$ cột các số thực 
$$
A =
\begin{bmatrix}
  a_{11} & a_{12} & \cdots & a_{1n} \\
  a_{21} & a_{22} & \cdots & a_{2n} \\
  \vdots  & \vdots  & \ddots & \vdots  \\
  a_{m1} & a_{m2} & \cdots & a_{mn} 
\end{bmatrix} \in \mathbb{R}^{m \times n}
$$
được gọi là **ma trận** (matrix) có kích thước (hay có dạng) $m \times n$. Số $a_{ij}$ được gọi là **phần tử** (element, entry) ở dòng $i$, cột $j$ của ma trận $A$.

Ma trận $A \in \mathbb{R}^{m \times n}$ có thể xem như gồm $m$ vector dòng $\mathbb{R}^{1 \times n}$ với dòng $i$ là
$$
\boldsymbol{a}_{i,} = 
\begin{bmatrix}
  a_{i1} & a_{i2} & \cdots & a_{in} \\
\end{bmatrix},
$$
hay gồm $n$ vector cột $\mathbb{R}^{m \times 1}$ với cột $j$ là
$$
\boldsymbol{a}_{,j} = 
\begin{bmatrix}
  a_{1j} \\ a_{2j} \\ \vdots \\ a_{mj} 
\end{bmatrix}.
$$

Ta nói ma trận có được từ $A$ bằng cách xếp các dòng thành các cột là ma trận **chuyển vị** (transpose) của $A$, kí hiệu $A^T$, tức là
$$
A^T = 
\begin{bmatrix}
  a_{11} & a_{21} & \cdots & a_{m1} \\
  a_{12} & a_{22} & \cdots & a_{m2} \\
  \vdots  & \vdots  & \ddots & \vdots  \\
  a_{1n} & a_{2n} & \cdots & a_{mn} 
\end{bmatrix} \in \mathbb{R}^{n \times m}.
$$

Cách đơn giản nhất để biểu diễn ma trận là dùng **danh sách lồng** (nested list) các số. Cách hiệu quả và tiện lợi hơn là dùng **NumPy 2D array**.

In [19]:
def transpose(A):
    m, n = len(A), len(A[0]) # kích thước ma trận
    return [[A[i][j] for i in range(m)] for j in range(n)]

A = [[1, 2, 3], 
     [4, 5, 6]]
myprint(A)
myprint(transpose(A))

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [20]:
A = np.array(A)
print(A, A.shape)
print(A.T, A.T.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 4]
 [2 5]
 [3 6]] (3, 2)


In [21]:
A = Matrix([[sympy.symbols(f"a_{i}{j}") for j in range(1, 4)] for i in range(1, 3)])
A.T

⎡a₁₁  a₂₁⎤
⎢        ⎥
⎢a₁₂  a₂₂⎥
⎢        ⎥
⎣a₁₃  a₂₃⎦

Cho ma trận $A \in \mathbb{R}^{m \times n}$ và vector cột $\boldsymbol{v} \in \mathbb{R}^{n \times 1}$, phép nhân
$$
A\boldsymbol{v} = 
\begin{bmatrix}
  a_{11} & a_{12} & \cdots & a_{1n} \\
  a_{21} & a_{22} & \cdots & a_{2n} \\
  \vdots  & \vdots  & \ddots & \vdots  \\
  a_{m1} & a_{m2} & \cdots & a_{mn} 
\end{bmatrix}
\begin{bmatrix}
  v_1 \\ v_2 \\ \vdots \\ v_n 
\end{bmatrix} =
\begin{bmatrix}
  a_{11}v_1 + a_{12}v_2 + ... + a_{1n}v_n \\ 
  a_{21}v_1 + a_{22}v_2 + ... + a_{2n}v_n \\ \vdots \\ 
  a_{m1}v_1 + a_{m2}v_2 + ... + a_{mn}v_n \\ 
\end{bmatrix}
$$
có thể được định nghĩa như là tích vô hướng các vector dòng của $A$ với $\boldsymbol{v}$
$$
A\boldsymbol{v} = 
\begin{bmatrix}
  \langle \boldsymbol{a}_{1,}, \boldsymbol{v} \rangle \\ 
  \langle \boldsymbol{a}_{2,}, \boldsymbol{v} \rangle \\ \vdots \\ 
  \langle \boldsymbol{a}_{m,}, \boldsymbol{v} \rangle 
\end{bmatrix},
$$
hay có thể được định nghĩa như là tổ hợp tuyến tính các vector cột của $A$ với các hệ số trong $\boldsymbol{v}$
$$
A\boldsymbol{v} =
v_1\begin{bmatrix}
  a_{11} \\ a_{21} \\ \vdots \\ a_{m1} 
\end{bmatrix} + 
v_2\begin{bmatrix}
  a_{12} \\ a_{22} \\ \vdots \\ a_{m2} 
\end{bmatrix} + ... +
v_n\begin{bmatrix}
  a_{1n} \\ a_{2n} \\ \vdots \\ a_{mn} 
\end{bmatrix} =
v_1\boldsymbol{a}_{,1} + v_2\boldsymbol{a}_{,2} + ... + v_n\boldsymbol{a}_{,n}.
$$

In [22]:
def mul_matrix_vector(A, v):
    return [inner_product(ai, v) for ai in A]

def mul_matrix_vector2(A, v):
    w = [0 for _ in range(len(v))]
    for j in range(len(v)):
        w = add_vector(w, mul_scalar_vector(v[j], [ai[j] for ai in A]))
    return w

In [23]:
A = [[1, 2, 3], [4, 5, 6]]; v = [1, 1, 1]
print(mul_matrix_vector(A, v), mul_matrix_vector2(A, v))

A = np.array(A); v = np.array(v)
print(np.matmul(A, v), A @ v)

[6, 15] [6, 15]
[ 6 15] [ 6 15]


In [24]:
A = Matrix(A)
v = Matrix(sympy.symbols("alpha_1 alpha_2 alpha_3"))
A * v

⎡ α₁ + 2⋅α₂ + 3⋅α₃ ⎤
⎢                  ⎥
⎣4⋅α₁ + 5⋅α₂ + 6⋅α₃⎦

3 loại biến đổi sau trên một ma trận được gọi là **phép biến đổi sơ cấp trên dòng** (elementary row operation):

> **Loại 1.** (Row switching) Đổi hai dòng cho nhau,

> **Loại 2.** (Row multiplication) Nhân một dòng với một số khác 0,

> **Loại 3.** (Row addition) Cộng vào một dòng một bội số của dòng khác.

Cho $A, B \in \mathbb{R}^{m \times n}$, ta nói $A, B$ **tương đương dòng** (row equivalent) với nhau nếu $B$ có được từ $A$ (hay ngược lại, $A$ có được từ $B$) qua hữu hạn phép biến đổi sơ cấp trên dòng.

Một ma trận được nói là có **dạng bậc thang theo dòng** (row echelon form) nếu:

* Các dòng khác $\boldsymbol{0}$ luôn nằm trên các dòng $\boldsymbol{0}$ (nếu có),

* Trên 2 dòng khác $\boldsymbol{0}$, hệ số khác 0 đầu tiên của dòng dưới luôn nằm bên phải cột chứa hệ số khác 0 đầu tiên của dòng trên.

In [25]:
def row_switch(A, i, k):
    "di <-> dk"
    A[i], A[k] = A[k], A[i]
    
def row_mul(A, i, alpha):
    "di = anpha*di"
    A[i] = mul_scalar_vector(alpha, A[i])

def row_add(A, i, k, alpha):
    "di = di + anpha*dk"
    A[i] = add_vector(A[i], mul_scalar_vector(alpha, A[k]))
    
def is_echelon(A):
    pass # TODO: cộng điểm

A = [[1, 2, 3],
     [4, 5, 6]]

row_mul(A, 0, 4)     # d0 = 4d0
row_switch(A, 0, 1)  # d0 <-> d1
row_add(A, 1, 0, -1) # d1 = d1 - d0
myprint(A)

[[4 5 6]
 [0 3 6]]


In [26]:
A = Matrix(A)
print(A.is_echelon)

True


In [27]:
A = A.elementary_row_op("n->n+km", row=1, row2=0, k=1)     # d1 = d1 + d0
A = A.elementary_row_op("n<->m", row1=1, row2=0)           # d1 <-> d0
A = A.elementary_row_op("n->kn", row=0, k=Fraction("1/4")) # d0 = d0/4
A

⎡1  2  3⎤
⎢       ⎥
⎣4  5  6⎦

# Hệ PTTT và phép khử Gauss

## Các khái niệm cơ bản

**Hệ PTTT** (system of linear equations, linear system) gồm $m$ phương trình theo $n$ ẩn số $x_1, x_2, ..., x_n$ là hệ có dạng
$$
\begin{matrix}
  a_{11}x_1 + a_{12}x_2 + ... + a_{1n}x_n = b_1 \\ 
  a_{21}x_1 + a_{22}x_2 + ... + a_{2n}x_n = b_2 \\ 
  \vdots \\ 
  a_{m1}x_1 + a_{m2}x_2 + ... + a_{mn}x_n = b_m \\ 
\end{matrix}.
$$

Hệ PTTT trên có thể được viết lại dưới dạng ma trận
$$ A\boldsymbol{x} = \boldsymbol{b} $$
với $A \in \mathbb{R}^{m \times n}$ là **ma trận các hệ số** (coefficient matrix)
$$
A =
\begin{bmatrix}
  a_{11} & a_{12} & \cdots & a_{1n} \\
  a_{21} & a_{22} & \cdots & a_{2n} \\
  \vdots  & \vdots  & \ddots & \vdots  \\
  a_{m1} & a_{m2} & \cdots & a_{mn} 
\end{bmatrix},
$$
$\boldsymbol{x}$ là vector cột các **ẩn** (unknown) và $\boldsymbol{b}$ là vector cột các **hệ số vế phải** (right-hand side)
$$
\boldsymbol{x} =
\begin{bmatrix}
  x_{1} \\ x_{2} \\ \vdots \\ x_{n} 
\end{bmatrix}, 
\boldsymbol{b} =
\begin{bmatrix}
  b_{1} \\ b_{2} \\ \vdots \\ b_{n} 
\end{bmatrix}.
$$

Trường hợp $\boldsymbol{b} = \boldsymbol{0}$, hệ thường được gọi là hệ **thuần nhất** (homogeneous).

Với $A \in \mathbb{R}^{m \times n}, \boldsymbol{b} \in \mathbb{R}^{m \times 1}$ cho trước, ta nói $\boldsymbol{s} \in \mathbb{R}^{m \times 1}$ là vector **nghiệm** (solution) của hệ $A\boldsymbol{x} = \boldsymbol{b}$ nếu $A\boldsymbol{s} = \boldsymbol{b}$.

In [28]:
A = [[1, -1],
     [2, 1]]
b = [1, 6]
x = to_fraction(["7/3", "4/3"])
Ax = mul_matrix_vector(A, x)
myprint(Ax)
print(equal_vector(Ax, b))
y = to_fraction(["4/3", "7/3"])
Ay = mul_matrix_vector(A, y)
myprint(Ay)
print(equal_vector(Ay, b))

[1 6]
True
[-1 5]
False


Hệ PTTT $A\boldsymbol{x} = \boldsymbol{b}$ thường được giải bằng các bước:

> **Bước 1.** Lập **ma trận bổ sung** (augmented matrix) bằng cách ghép cột $\boldsymbol{b}$ sau ma trận $A$: $\bar{A} = \left[ A | \boldsymbol{b} \right]$.

> **Bước 2.** Dùng các phép biến đổi sơ cấp trên dòng để biến đổi $\bar{A}$ thành ma trận tương đương dòng có dạng bậc thang $R$.

> **Bước 3.** Giải $R$ bằng **phép thế ngược** (back-substitution) để có nghiệm.

***Mệnh đề.*** Nếu $\bar{A}, \bar{B}$ tương đương dòng thì các hệ PTTT tương ứng với ma trận bổ sung $\bar{A}, \bar{B}$ có cùng tập nghiệm.

In [29]:
def augmented_matrix(A, b):
    "Tạo ma trận bổ sung [A|b]"
    return [ai + [bi] for ai, bi in zip(A, b)]

A_bar = augmented_matrix(A, b)
myprint(A_bar)

[[1 -1 1]
 [2  1 6]]


## Phép khử Gauss

**Khử Gauss** (Gaussian elimination) là một cách biến đổi tương đương dòng đưa ma trận về dạng bậc thang. Thuật giải gồm các bước:

> **Bước 1.** Xác định cột trái nhất không chứa toàn số 0.

> **Bước 2.** Đổi chỗ hai dòng, nếu cần thiết, để đưa số hạng khác 0 nào đó ở dưới về đầu cột nhận được ở Bước 1.   
(*Đơn giản nhất, có thể chọn dòng đầu tiên có số hạng khác 0. Phức tạp hơn, chiến lược "partial pivoting" chọn dòng có số hạng có trị tuyệt đối lớn nhất.*)

> **Bước 3.** Với số hạng đầu cột nhận được từ Bước 2 là $a \neq 0$, nhân dòng chứa nó với $\frac{1}{a}$ để có **số dẫn đầu** 1 (leading 1).  
(*Bước này tùy chọn*.)

> **Bước 4.** Cộng một bội số thích hợp của dòng đầu cho từng dòng dưới để biến các số hạng bên dưới số dẫn đầu thành 0.

> **Bước 5.** Che dòng đầu đã làm xong. Lặp lại các bước cho đến khi được ma trận bậc thang.

In [30]:
def Gauss_elimination(A, leading1=True):
    R = A.copy()
    m, n = len(R), len(R[0]) # kích thước ma trận
    row = col = 0
    while row < m:
        # Bước 1
        while col < n and all(is_zero(R[i][col]) for i in range(row, m)):
            col += 1
        if col == n: # đã có dạng bậc thang
            break
        
        # Bước 2 (chọn dòng đầu tiên có số hạng khác 0)
        pivot_row = row + [not is_zero(R[i][col]) for i in range(row, m)].index(True)
        row_switch(R, row, pivot_row)
        
        # Bước 3
        if leading1:
            row_mul(R, row, 1/R[row][col])
            
        # Bước 4
        for i in range(row + 1, m):
            multiplier = R[i][col]/R[row][col]
            row_add(R, i, row, -multiplier)
    
        # Bước 5
        row += 1
    return R

In [31]:
A = [[1, 3, -2,  0, 2,  0, 0],
     [2, 6, -5, -2, 4, -3, 0],
     [0, 0,  5, 10, 0, 15, 0],
     [2, 6,  0,  8, 4, 18, 0]]

myprint(A)
myprint(Gauss_elimination(to_fraction(A), leading1=False))
myprint(Gauss_elimination(to_fraction(A)))

[[1 3 -2  0 2  0 0]
 [2 6 -5 -2 4 -3 0]
 [0 0  5 10 0 15 0]
 [2 6  0  8 4 18 0]]
[[1 3 -2  0 2  0 0]
 [0 0 -1 -2 0 -3 0]
 [0 0  0  0 0  6 0]
 [0 0  0  0 0  0 0]]
[[1 3 -2 0 2 0 0]
 [0 0  1 2 0 3 0]
 [0 0  0 0 0 1 0]
 [0 0  0 0 0 0 0]]


## Phép thế ngược

In [32]:
def back_substitution(R):
    "R là ma trận bậc thang của ma trận bổ sung của hệ phương trình Ax = b"
    m, n = len(R), len(R[0]) # kích thước ma trận R
    
    # vector nghiệm (danh sách theo thứ tự ẩn)
    sol = [None for _ in range(n - 1)]
    
    # Tìm dòng dưới cùng khác không
    row = m - 1
    while row >= 0 and all(is_zero(R[row][j]) for j in range(n)):
        row -= 1
    
    if row >= 0 and [not is_zero(R[row][j]) for j in range(n)].index(True) == n - 1:
        return None # vô nghiệm
    
    last_pcol = n - 1
    while row >= 0:
        pcol = [not is_zero(R[row][j]) for j in range(n)].index(True)
        for i in range(pcol, last_pcol): # các ẩn tự do
            sol[i] = sympy.symbols(f"x{i + 1}")
        sol[pcol] = (R[row][n - 1] - sum(R[row][j]*sol[j] for j in range(pcol + 1, n - 1)))/R[row][pcol]
        last_pcol = pcol
        row -= 1
    
    # Bổ sung các ẩn tự do từ 0 đến last_pcol - 1
    for i in range(0, last_pcol):
        sol[i] = sympy.symbols(f"x{i + 1}")
    return sol

In [33]:
myprint(back_substitution(Gauss_elimination(to_fraction(A))), sep=", ")

[-3*x2 - 4*x4 - 2*x5, x2, -2*x4, x4, x5, 0]


## Thư viện hỗ trợ

* **NumPy**, **SciPy**: các hàm [`numpy.linalg.solve`](https://numpy.org/doc/stable/reference/generated/numpy.linalg.solve.html) và [`scipy.linalg.solve`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.solve.html) có thể được dùng để giải hệ PTTT trường hợp hệ vuông ($m = n$) và có nghiệm duy nhất.

* **SymPy**: 
  - phương thức [`echelon_form`](https://docs.sympy.org/latest/modules/matrices/matrices.html#sympy.matrices.matrices.MatrixReductions.echelon_form) tìm dạng bậc thang.
  
  - phương thức [`rref`](https://docs.sympy.org/latest/modules/matrices/matrices.html#sympy.matrices.matrices.MatrixReductions.rref) tìm **dạng bậc thang rút gọn** (reduced row-echelon form, Gauss-Jordan elimination).
  
  - phương thức [`sympy.linsolve`](https://docs.sympy.org/latest/modules/solvers/solveset.html#linsolve) giải hệ PTTT.

## Ví dụ

### Ví dụ 1

Giải hệ PTTT
$$
\begin{matrix}
   x & + &  y & + & 2z & = & 9 \\
  2x & + & 4y & - & 3z & = & 1 \\ 
  3x & + & 6y & - & 5z & = & 0 \\
\end{matrix}.
$$

Hệ được viết lại dưới dạng phương trình ma trận $A\boldsymbol{x} = \boldsymbol{b}$, với
$$
A =
\begin{bmatrix}
1 & 1 &  2 \\
2 & 4 & -3 \\
3 & 6 & -5 \\ 
\end{bmatrix},
\boldsymbol{x} = 
\begin{bmatrix} x \\ y \\ z \end{bmatrix},
\boldsymbol{b} = 
\begin{bmatrix} 9 \\ 1 \\ 0 \end{bmatrix}.
$$

Lập ma trận bổ sung
$$
\bar{A} = \left[ A | \boldsymbol{b} \right] = 
\begin{bmatrix}
1 & 1 &  2 & 9 \\
2 & 4 & -3 & 1\\
3 & 6 & -5 & 0\\ 
\end{bmatrix}.
$$

Đưa $\bar{A}$ về dạng bậc thang (với số dẫn đầu 1)

In [34]:
A_bar = [[1, 1,  2, 9],
         [2, 4, -3, 1],
         [3, 6, -5, 0]]

R = Gauss_elimination(to_fraction(A_bar))
myprint(R)

[[1 1    2     9]
 [0 1 -7/2 -17/2]
 [0 0    1     3]]


Như vậy, ta có $\bar{A}$ tương đương dòng với ma trận bậc thang
$$
R = 
\begin{bmatrix}
\boxed{1} & 1 & 2 & 9 \\
0 & \boxed{1} & -\frac{7}{2} & -\frac{17}{2} \\
0 & 0 & \boxed{1} & 3 \\ 
\end{bmatrix}.
$$

Ta thấy hệ này có nghiệm duy nhất. Giải từ dưới lên bằng phép thế ngược

In [35]:
sol = back_substitution(R)
if not sol:
    print("Hệ vô nghiệm")
else:
    myprint(sol, sep=", ")

[1, 2, 3]


Như vậy hệ có nghiệm
$$
\boldsymbol{x} = 
\begin{bmatrix}
x \\ y \\ z 
\end{bmatrix} =
\begin{bmatrix}
1 \\ 2 \\ 3 
\end{bmatrix}
$$

In [36]:
A_bar = np.array(A_bar)
print(np.linalg.solve(A_bar[:, :-1], A_bar[:, -1]))

[1. 2. 3.]


### Ví dụ 2

Giải hệ PTTT
$$
\begin{matrix}
       &   &      &   & -2x_3 &   &      & + &  7x_5 & = & 12 \\
  2x_1 & + & 4x_2 & - & 10x_3 & + & 6x_4 & + & 12x_5 & = & 28 \\ 
  2x_1 & + & 4x_2 & - &  5x_3 & + & 6x_4 & - &  5x_5 & = & -1 \\
\end{matrix}.
$$

Lập ma trận bổ sung
$$
\bar{A} = \left[ A | \boldsymbol{b} \right] = 
\begin{bmatrix}
0 & 0 &  -2 & 0 &  7 & 12 \\
2 & 4 & -10 & 6 & 12 & 28 \\
2 & 4 &  -5 & 6 & -5 &  -1 \\ 
\end{bmatrix}.
$$

Đưa $\bar{A}$ về dạng bậc thang

In [37]:
A_bar = [[0, 0,  -2, 0,  7, 12],
         [2, 4, -10, 6, 12, 28],
         [2, 4,  -5, 6, -5, -1]]

R = Gauss_elimination(to_fraction(A_bar), leading1=False)
myprint(R)
myprint(Gauss_elimination(to_fraction(A_bar)))

[[2 4 -10 6  12 28]
 [0 0  -2 0   7 12]
 [0 0   0 0 1/2  1]]
[[1 2 -5 3    6 14]
 [0 0  1 0 -7/2 -6]
 [0 0  0 0    1  2]]


In [38]:
Matrix(A_bar).echelon_form()

⎡2  4  -10  6  12  28⎤
⎢                    ⎥
⎢0  0  -2   0  7   12⎥
⎢                    ⎥
⎣0  0   0   0  -2  -4⎦

Như vậy, ta có $\bar{A}$ tương đương dòng với ma trận bậc thang
$$
R = 
\begin{bmatrix}
\boxed{1} & 2 & -5 & 3 &  6 & 14 \\
0 & 0 & \boxed{1} & 0 & -\frac{7}{2} & -6 \\
0 & 0 &  0 & 0 & \boxed{1} & 2 \\ 
\end{bmatrix}.
$$

Ta thấy hệ này có vô số nghiệm. Giải từ dưới lên bằng phép thế ngược cho các ẩn cơ sở $x_1, x_3, x_5$ và các ẩn tự do $x_2, x_4$

In [39]:
sol = back_substitution(R)
if not sol:
    print("Hệ vô nghiệm")
else:
    myprint(sol, sep=", ")

[-2*x2 - 3*x4 + 7, x2, 1, x4, 2]


Như vậy, hệ có nghiệm tổng quát
$$
\boldsymbol{x} = 
\begin{bmatrix}
x_1 \\ x_2 \\ x_3 \\ x_4 \\ x_5 \\ 
\end{bmatrix} = 
\begin{bmatrix}
7 -2x_2 - 3x_4 \\ x_2 \\ 1 \\ x_4 \\ 2 \\ 
\end{bmatrix} =
\begin{bmatrix}
7 \\ 0 \\ 1 \\ 0 \\ 2 \\ 
\end{bmatrix} +
x_2 \begin{bmatrix}
-2 \\ 1 \\ 0 \\ 0 \\ 0 \\ 
\end{bmatrix} +
x_4 \begin{bmatrix}
-3 \\ 0 \\ 0 \\ 1 \\ 0 \\ 
\end{bmatrix},
x_2, x_4 \in \mathbb{R}.
$$

In [40]:
sympy.linsolve(Matrix(A_bar), [sympy.symbols(f"x_{i}") for i in range(1, 6)])

# Không gian con, cơ sở và số chiều

## Các khái niệm cơ bản

Cho $V \subset \mathbb{R}^n$, ta nói $V$ là **không gian con** (subspace) của $\mathbb{R}^n$, kí hiệu $V \le \mathbb{R}^n$ nếu:

* $\boldsymbol{0} \in V$,

* Với mọi $\boldsymbol{v}, \boldsymbol{w} \in V$, ta có $\alpha \boldsymbol{v} + \beta \boldsymbol{w} \in V, \forall \alpha, \beta \in \mathbb{R}$.

Cho họ các vector $\boldsymbol{v}_1, \boldsymbol{v}_2, ..., \boldsymbol{v}_k \in \mathbb{R}^n$, tập tất cả các tổ hợp tuyến tính của $\boldsymbol{v}_1, \boldsymbol{v}_2, ..., \boldsymbol{v}_k$ được kí hiệu là $\mathrm{Span}\{\boldsymbol{v}_1, \boldsymbol{v}_2, ..., \boldsymbol{v}_k\}$, tức là
$$
\mathrm{Span}\{\boldsymbol{v}_1, \boldsymbol{v}_2, ..., \boldsymbol{v}_k\} = \{\alpha_1 \boldsymbol{v}_1 + \alpha_2 \boldsymbol{v}_2 + ... + \alpha_k \boldsymbol{v}_k: \alpha_1, \alpha_2, ..., \alpha_k \in \mathbb{R}\} \subset \mathbb{R}^n.
$$

***Mệnh đề.*** $\mathrm{Span}\{\boldsymbol{v}_1, \boldsymbol{v}_2, ..., \boldsymbol{v}_k\} \le \mathbb{R}^n$. Ta còn nói $\mathrm{Span}\{\boldsymbol{v}_1, \boldsymbol{v}_2, ..., \boldsymbol{v}_k\}$ là không gian con **sinh bởi** (span) $\boldsymbol{v}_1, \boldsymbol{v}_2, ..., \boldsymbol{v}_k$ và $\boldsymbol{v}_1, \boldsymbol{v}_2, ..., \boldsymbol{v}_k$ là một **tập sinh** (generating set) của $\mathrm{Span}\{\boldsymbol{v}_1, \boldsymbol{v}_2, ..., \boldsymbol{v}_k\}$. 

Cho họ các vector $\boldsymbol{v}_1, \boldsymbol{v}_2, ..., \boldsymbol{v}_k \in \mathbb{R}^n$, ta nói họ là **phụ thuộc tuyến tính** (linearly dependent) nếu có vector nào đó là một tổ hợp tuyến tính của các vector còn lại; ngược lại, họ được nói là **độc lập tuyến tính** (linearly independent).

***Mệnh đề.*** Họ $\boldsymbol{v}_1, \boldsymbol{v}_2, ..., \boldsymbol{v}_k \in \mathbb{R}^n$ độc lập tuyến tính khi và chỉ khi hệ PTTT thuần nhất $A\boldsymbol{x} = \boldsymbol{0}$ có nghiệm duy nhất (là nghiệm tầm thường $\boldsymbol{0} \in \mathbb{R}^k$) với $A \in \mathbb{R}^{n \times k}$ là ma trận gồm các cột $\boldsymbol{v}_1, \boldsymbol{v}_2, ..., \boldsymbol{v}_k$.

Cho không gian con $V \le \mathbb{R}^n$ và họ hữu hạn $B \subset \mathbb{R}^n$, ta nói $B$ là một **cơ sở** (basic) của $V$ nếu $B$ là một tập sinh của $V$ và $B$ độc lập tuyến tính. Khi đó, $|B|$ (số lượng vector trong $B$) được gọi là **số chiều** (dimension) của $V$, kí hiệu $\mathrm{dim}(V)$.

Các ví dụ về không gian con:

> $\{0\}$ là không gian con tầm thường của $\mathbb{R}^n$ với số chiều là 0 và cơ sở là $\{\}$.

> $\mathbb{R}^n$ là không gian con tầm thường của $\mathbb{R}^n$ với số chiều là $n$. Tập các vector $\boldsymbol{e}_1 = (1, 0, ..., 0), \boldsymbol{e}_2 = (0, 1, 0, ..., 0), ..., \boldsymbol{e}_n = (0, ..., 0, 1)$ là một cơ sở của $\mathbb{R}^n$, gọi là **cơ sở chính tắc** (standard basic).

> Cho ma trận $A \in \mathbb{R}^{m \times n}$, ta nói:
>   * **Không gian dòng** (row space) của $A$, kí hiệu $\mathrm{Row}(A)$, là không gian con sinh bởi các dòng của $A$
>   $$\mathrm{Row}(A) = \mathrm{Span}\{\boldsymbol{a}_{1,}, \boldsymbol{a}_{2,}, ..., \boldsymbol{a}_{m,}\} \le \mathbb{R}^{n},$$
>   * **Không gian cột** (column space) của $A$, kí hiệu $\mathrm{Col}(A)$, là không gian con sinh bởi các cột của $A$
>   $$\mathrm{Col}(A) = \mathrm{Span}\{\boldsymbol{a}_{,1}, \boldsymbol{a}_{,2}, ..., \boldsymbol{a}_{,n}\} \le \mathbb{R}^{m},$$
>   * **Không gian nghiệm** (null space) của $A$, kí hiệu $\mathrm{Null}(A)$, là tập tất cả các nghiệm của hệ PTTT thuần nhất $A\boldsymbol{x} = \boldsymbol{0}$.  
>     ***Mệnh đề.*** $\mathrm{Null}(A) \le \mathbb{R}^{n}$.

> ***Mệnh đề.*** $\mathrm{Col}(A) = \mathrm{Row}(A^T)$.

> ***Mệnh đề.*** $\mathrm{dim}(\mathrm{Row}(A)) = \mathrm{dim}(\mathrm{Col}(A))$. Số chiều này còn được gọi là **hạng** (rank) của ma trận, kí hiệu, $\mathrm{rank}(A)$.

> ***Mệnh đề.*** $\mathrm{rank}(A) + \mathrm{dim}(\mathrm{Null}(A)) = n$.

> ***Mệnh đề.*** Nếu $A, B$ tương đương dòng thì $\mathrm{Row}(A) = \mathrm{Row}(B)$. Nếu $E$ là ma trận bậc thang (theo dòng) thì các dòng khác $\boldsymbol{0}$ của $E$ lập thành một cơ sở của $\mathrm{Row}(E)$.

## Thư viện hỗ trợ

* **NumPy**, **SciPy**: 

  * hàm [`numpy.linalg.matrix_rank`](https://numpy.org/doc/stable/reference/generated/numpy.linalg.matrix_rank.html) tìm hạng của ma trận.
  
  * hàm [`scipy.linalg.null_space`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.null_space.html) tìm không gian nghiệm của ma trận (trả về một cơ sở của không gian nghiệm).

* **SymPy**: 
  - phương thức [`rank`](https://docs.sympy.org/latest/modules/matrices/matrices.html#sympy.matrices.matrices.MatrixReductions.rank) tìm hạng của ma trận.
  
  - Các phương thức [`rowspace`](https://docs.sympy.org/latest/modules/matrices/matrices.html#sympy.matrices.matrices.MatrixSubspaces.rowspace), [`columnspace`](https://docs.sympy.org/latest/modules/matrices/matrices.html#sympy.matrices.matrices.MatrixSubspaces.columnspace), [`nullspace`](https://docs.sympy.org/latest/modules/matrices/matrices.html#sympy.matrices.matrices.MatrixSubspaces.nullspace) tìm các không gian dòng, cột, nghiệm của ma trận (trả về một cơ sở của không gian tương ứng).

## Ví dụ

### Ví dụ 1

Trong $\mathbb{R}^3$, cho $\boldsymbol{v}_1 = (1, 2, -3), \boldsymbol{v}_2 = (2, 5, -1), \boldsymbol{v}_3 = (1, 1, -8)$. Kiểm tra $B = \{\boldsymbol{v}_1, \boldsymbol{v}_2, \boldsymbol{v}_3\}$ có là một cơ sở của $\mathbb{R}^3$.

Nếu $\boldsymbol{v}_1, \boldsymbol{v}_2, \boldsymbol{v}_3$ độc lập tuyến tính thì $B$ là một cơ sở của $\mathbb{R}^3$ do $\mathrm{dim}(\mathbb{R}^3) = 3$.

Đặt $A$ là ma trận gồm các cột $\boldsymbol{v}_1, \boldsymbol{v}_2, \boldsymbol{v}_3$, ta có $\boldsymbol{v}_1, \boldsymbol{v}_2, \boldsymbol{v}_3$ độc lập tuyến tính khi và chỉ khi hệ PTTT $A\boldsymbol{x} = \boldsymbol{0}$ có nghiệm duy nhất.

In [41]:
v1, v2, v3 = [1, 2, -3], [2, 5, -1], [1, 1, -8]
A = transpose([v1, v2, v3])
myprint(Gauss_elimination(to_fraction(A)))

[[1 2  1]
 [0 1 -1]
 [0 0  0]]


Từ ma trận bậc thang trên, ta thấy hệ có vô số nghiệm.

In [42]:
print(scipy.linalg.null_space(A))
Matrix(A).nullspace()

[[-0.90453403]
 [ 0.30151134]
 [ 0.30151134]]


⎡⎡-3⎤⎤
⎢⎢  ⎥⎥
⎢⎢1 ⎥⎥
⎢⎢  ⎥⎥
⎣⎣1 ⎦⎦

Như vậy $\boldsymbol{v}_1, \boldsymbol{v}_2, \boldsymbol{v}_3$ không độc lập tuyến tính nên $B$ không là cơ sở của $\mathbb{R}^3$.

Ta cũng có thể dùng hạng của ma trận để kiểm tra

In [43]:
print(np.linalg.matrix_rank(A))
print(Matrix(A).rank())

2
2


Vì $\mathrm{rank}(A) = 2 < 3$ nên $\boldsymbol{v}_1, \boldsymbol{v}_2, \boldsymbol{v}_3$ không độc lập tuyến tính.

### Ví dụ 2

Trong $\mathbb{R}^4$, cho $\boldsymbol{v}_1 = (1, 2, 1, 1), \boldsymbol{v}_2 = (3, 6, 5, 7), \boldsymbol{v}_3 = (4, 8, 6, 8), \boldsymbol{v}_4 = (8, 16, 12, 20)$. Tìm một cơ sở và số chiều của không gian con sinh bởi $\boldsymbol{v}_1, \boldsymbol{v}_2, \boldsymbol{v}_3, \boldsymbol{v}_4$.

Đặt $A$ là ma trận gồm các dòng $\boldsymbol{v}_1, \boldsymbol{v}_2, \boldsymbol{v}_3, \boldsymbol{v}_4$, ta có $\mathrm{Row}(A) = \mathrm{Span}\{\boldsymbol{v}_{1}, \boldsymbol{v}_{2}, \boldsymbol{v}_{3}, \boldsymbol{v}_{4}\}$.

In [44]:
v1, v2, v3, v4 = [1, 2, 1, 1], [3, 6, 5, 7], [4, 8, 6, 8], [8, 16, 12, 20]
A = [v1, v2, v3, v4]
myprint(Gauss_elimination(to_fraction(A)))

[[1 2 1 1]
 [0 0 1 2]
 [0 0 0 1]
 [0 0 0 0]]


Như vậy $\mathrm{Span}\{\boldsymbol{v}_{1}, \boldsymbol{v}_{2}, \boldsymbol{v}_{3}, \boldsymbol{v}_{4}\}$ có số chiều là 3 và có một cơ sở là
$$
\{(1, 2, 1, 1), (0, 0, 1, 2), (0, 0, 0, 1)\}.
$$

In [45]:
Matrix(A).rowspace()

[[1  2  1  1], [0  0  2  4], [0  0  0  8]]

### Ví dụ 3

Tìm không gian nghiệm của hệ PTTT thuần nhất sau
$$
\begin{matrix}
   x_1 & + & 2x_2 & - &  3x_3 & + &  5x_4 & = & 0\\
   x_1 & + & 3x_2 & - & 13x_3 & + & 22x_4 & = & 0\\ 
  3x_1 & + & 5x_2 & + &   x_3 & - &  2x_4 & = & 0\\
  2x_1 & + & 3x_2 & + &  4x_3 & - &  7x_4 & = & 0\\
\end{matrix}.
$$

Không gian nghiệm của hệ PTTT thuần nhất trên chính là không gian nghiệm của ma trận hệ số
$$
A = 
\begin{bmatrix}
1 & 2 &  -3 & 5\\
1 & 3 & -13 & 22\\
3 & 5 &   1 & -2\\
2 & 3 &   4 & -7\\
\end{bmatrix}.
$$

In [46]:
A = [[1, 2,  -3,  5],
     [1, 3, -13, 22],
     [3, 5,   1, -2],
     [2, 3,   4, -7]]

A_bar = augmented_matrix(A, zero_vector(4))
myprint(back_substitution(Gauss_elimination(to_fraction(A_bar))), ", ")

[-17*x3 + 29*x4, 10*x3 - 17*x4, x3, x4]


Như vậy, hệ có nghiệm tổng quát
$$
\boldsymbol{x} = 
\begin{bmatrix}
x_1 \\ x_2 \\ x_3 \\ x_4
\end{bmatrix} =
\begin{bmatrix}
-17x_3 + 29x_4 \\ 10x_3 - 17x_4 \\ x_3 \\ x_4 
\end{bmatrix} =
x_3 \begin{bmatrix}
-17 \\ 10 \\ 1 \\ 0 \\ 
\end{bmatrix} +
x_4 \begin{bmatrix}
29 \\ -17 \\ 0 \\ 1 \\ 
\end{bmatrix},
x_3, x_4 \in \mathbb{R}.
$$

Như vậy $\mathrm{Null}(A)$ có số chiều là 2 và có một cơ sở là
$$
\{(-17, 10, 1, 0), (29, -17, 0, 1)\}
$$

In [47]:
Matrix(A).nullspace()

⎡⎡-17⎤  ⎡29 ⎤⎤
⎢⎢   ⎥  ⎢   ⎥⎥
⎢⎢10 ⎥  ⎢-17⎥⎥
⎢⎢   ⎥, ⎢   ⎥⎥
⎢⎢ 1 ⎥  ⎢ 0 ⎥⎥
⎢⎢   ⎥  ⎢   ⎥⎥
⎣⎣ 0 ⎦  ⎣ 1 ⎦⎦

# Trực giao hóa với thuật giải Gram-Schmidt

## Các khái niệm cơ bản

Ta nói họ (hệ, tập) các vector $\boldsymbol{v}_1, \boldsymbol{v}_2, ..., \boldsymbol{v}_k \in \mathbb{R}^n$ là **trực giao** (orthogonal) nếu chúng đôi một trực giao, tức là $\langle \boldsymbol{v}_i, \boldsymbol{v}_j \rangle = 0, \forall i \ne j.$

In [48]:
def orthogonal_set(vs):
    return all(orthogonal(vs[i], vs[j]) for i in range(len(vs)) for j in range(len(vs)) if i != j)

Ta nói họ (hệ, tập) các vector $\boldsymbol{q_1}, \boldsymbol{q}_2, ..., \boldsymbol{q}_k \in \mathbb{R}^n$ là **trực chuẩn** (orthonormal) nếu chúng là họ trực giao các vector đơn vị.

In [49]:
def orthonormal_set(vs):
    return orthogonal_set(vs) and all(unit_vector(vi) for vi in vs)

## Thuật giải Gram-Schmidt

Cho tập các vector $\boldsymbol{v}_1, \boldsymbol{v}_2, ..., \boldsymbol{v}_k \in \mathbb{R}^n$, **thuật giải Gram-Schmidt** (Gram-Schmidt algorithm) tìm họ trực giao (hoặc trực chuẩn) các vector $\boldsymbol{q}_1, \boldsymbol{q}_2, ..., \boldsymbol{q}_r \in \mathbb{R}^n$ là một cơ sở của $\mathrm{Span}\{\boldsymbol{v}_1, \boldsymbol{v}_2, ..., \boldsymbol{v}_k\}$. Thuật giải gồm các bước:

> **Bước 1.** Tạo tập $Q = \{\}$ chứa cơ sở kết quả.

> **Bước 2.** Đặt $i = 1$ và lặp lại các Bước 3-4 cho đến khi $i > k$.

> **Bước 3.** Tính 
> $$
\boldsymbol{q}_i = \boldsymbol{v}_i - \sum_{\boldsymbol{q}_j \in Q} \frac{\langle \boldsymbol{v}_i, \boldsymbol{q}_j \rangle}{\| \boldsymbol{q}_j \|^2}\boldsymbol{q}_j
$$

> **Bước 4.** Nếu $\boldsymbol{q}_i \neq 0$ thì thêm $\boldsymbol{q}_i$ vào $Q$. Tăng $i$ thêm $1$.

> **Bước 5.** **Chuẩn hóa** (normalizing) nếu cần họ trực chuẩn
> $$
\boldsymbol{q}_i = \frac{\boldsymbol{q}_i}{\| \boldsymbol{q}_i \|}, \forall \boldsymbol{q}_i \in Q
$$

> **Bước 6.** Trả về $Q$.

In [50]:
def Gram_Schmidt(vs, normalizing=False):
    # Bước 1
    Q = []
    
    # Bước 2
    for vi in vs:
        # Bước 3
        qi = vi
        for qj in Q:
            qi = sub_vector(qi, mul_scalar_vector(Fraction(inner_product(vi, qj), inner_product(qj, qj)), qj))
        
        # Bước 4
        if not is_zero_vector(qi):
            Q.append(qi)
    
    # Bước 5
    if normalizing:
        Q = [mul_scalar_vector(1/norm(qi), qi) for qi in Q]
    
    return Q

## Thư viện hỗ trợ

* **SciPy**: dùng hàm [`scipy.linalg.orth`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.orth.html) để tìm cơ sở trực chuẩn của không gian cột của một ma trận. Tuy nhiên, hàm này dùng một thuật giải khác (mà ta sẽ học sau).

* **SymPy**: dùng hàm [`sympy.Matrix.orthogonalize`](https://docs.sympy.org/latest/modules/matrices/matrices.html#sympy.matrices.matrices.MatrixSubspaces.orthogonalize) để thực hiện giải thuật Gram-Schmidt.

## Ví dụ

### Ví dụ 1

Dùng thuật giải Gram-Schmidt trực giao hóa họ 3 vector sau và cho biết họ có độc lập tuyến tính hay không?
$$
\boldsymbol{v}_1 = (-1, 1, -1, 1), \boldsymbol{v}_2 = (-1, 3, -1, 3), \boldsymbol{v}_3 = (0, 2, 0, 2)
$$

In [51]:
v1 = [-1, 1, -1, 1]
v2 = [-1, 3, -1, 3]
v3 = [0, 2, 0, 2]
vs = [v1, v2, v3]
Q = Gram_Schmidt(vs)
myprint(Q)
if len(Q) < len(vs):
    print("Hệ không độc lập tuyến tính!")

[[-1 1 -1 1]
 [ 1 1  1 1]]
Hệ không độc lập tuyến tính!


In [52]:
Q1 = Gram_Schmidt(vs, normalizing=True)
Q2 = scipy.linalg.orth(np.array(vs).T).T
myprint(Q1)
print(Q2)
print(orthonormal_set(Q1), orthonormal_set(Q2))

[[-1/2 1/2 -1/2 1/2]
 [ 1/2 1/2  1/2 1/2]]
[[-0.20490834  0.67676626 -0.20490834  0.67676626]
 [ 0.67676626  0.20490834  0.67676626  0.20490834]]
True True


In [53]:
Matrix.orthogonalize(Matrix(v1), Matrix(v2), Matrix(v3), normalize=True)

⎡⎡-1/2⎤  ⎡1/2⎤⎤
⎢⎢    ⎥  ⎢   ⎥⎥
⎢⎢1/2 ⎥  ⎢1/2⎥⎥
⎢⎢    ⎥, ⎢   ⎥⎥
⎢⎢-1/2⎥  ⎢1/2⎥⎥
⎢⎢    ⎥  ⎢   ⎥⎥
⎣⎣1/2 ⎦  ⎣1/2⎦⎦

Như vậy, họ $\boldsymbol{v}_1, \boldsymbol{v}_2, \boldsymbol{v}_3$ không độc lập tuyến tính và một cơ sở trực giao cho $\mathrm{Span}\{\boldsymbol{v}_1, \boldsymbol{v}_2, \boldsymbol{v}_3\} \le \mathbb{R}^4$ là
$$
\boldsymbol{q}_1 = (-1, 1, -1, 1), \boldsymbol{q}_2 = (1, 1, 1, 1)
$$

### Ví dụ 2

Dùng thuật giải Gram-Schmidt trực chuẩn hóa họ 3 vector sau
$$
\boldsymbol{v}_1 = (1, 1, 1), \boldsymbol{v}_2 = (0, 1, 1), \boldsymbol{v}_3 = (0, 0, 1)
$$

In [54]:
v1 = [1, 1, 1]
v2 = [0, 1, 1]
v3 = [0, 0, 1]
myprint(Gram_Schmidt([v1, v2, v3]))
myprint(Gram_Schmidt([v1, v2, v3], normalizing=True))

[[   1    1   1]
 [-2/3  1/3 1/3]
 [   0 -1/2 1/2]]
[[ sqrt(3)/3  sqrt(3)/3 sqrt(3)/3]
 [-sqrt(6)/3  sqrt(6)/6 sqrt(6)/6]
 [         0 -sqrt(2)/2 sqrt(2)/2]]


In [55]:
Matrix.orthogonalize(Matrix(v1), Matrix(v2), Matrix(v3), normalize=True)

⎡⎡√3⎤  ⎡-√6 ⎤        ⎤
⎢⎢──⎥  ⎢────⎥  ⎡ 0  ⎤⎥
⎢⎢3 ⎥  ⎢ 3  ⎥  ⎢    ⎥⎥
⎢⎢  ⎥  ⎢    ⎥  ⎢-√2 ⎥⎥
⎢⎢√3⎥  ⎢ √6 ⎥  ⎢────⎥⎥
⎢⎢──⎥, ⎢ ── ⎥, ⎢ 2  ⎥⎥
⎢⎢3 ⎥  ⎢ 6  ⎥  ⎢    ⎥⎥
⎢⎢  ⎥  ⎢    ⎥  ⎢ √2 ⎥⎥
⎢⎢√3⎥  ⎢ √6 ⎥  ⎢ ── ⎥⎥
⎢⎢──⎥  ⎢ ── ⎥  ⎣ 2  ⎦⎥
⎣⎣3 ⎦  ⎣ 6  ⎦        ⎦

Như vậy, họ $\boldsymbol{v}_1, \boldsymbol{v}_2, \boldsymbol{v}_3$ độc lập tuyến tính và một cơ sở trực chuẩn cho $\mathrm{Span}\{\boldsymbol{v}_1, \boldsymbol{v}_2, \boldsymbol{v}_3\} = \mathbb{R}^3$ là
$$
\boldsymbol{q}_1 = \frac{1}{\sqrt{3}}(1, 1, 1), \boldsymbol{q}_2 = \frac{1}{\sqrt{6}}(-2, 1, 1), \boldsymbol{q}_3 = \frac{1}{\sqrt{2}}(0, -1, 1)
$$

# Bài tập

## Bài tập tự rèn luyện

Cho $\boldsymbol{v}, \boldsymbol{w} \in \mathbb{R}^n$ khác $\boldsymbol{0}$, ta định nghĩa **góc** (angle) giữa $\boldsymbol{v}, \boldsymbol{w}$ là
$$
\mathrm{angle}(\boldsymbol{v}, \boldsymbol{w}) = \arccos \left( \frac{\langle \boldsymbol{v}, \boldsymbol{w} \rangle}{\| \boldsymbol{v} \|\| \boldsymbol{w} \|} \right).
$$

Viết hàm tính góc giữa $\boldsymbol{v}, \boldsymbol{w}$ được cho

In [56]:
def angle(v, w):
    pass # TODO

Viết hàm tính tổ hợp tuyến tính của các vector $\boldsymbol{v}_1, \boldsymbol{v}_2, ..., \boldsymbol{v}_k \in \mathbb{R}^n$ theo các hệ số $\alpha_1, \alpha_2, ..., \alpha_k \in \mathbb{R}$.

In [57]:
def linear_combination(vs, alphas):
    "vs là danh sách các vector và alphas là danh sách các hệ số tương ứng"
    pass # TODO

Từ đó viết hàm tính vector trung bình của $k$ vector $\boldsymbol{v}_1, \boldsymbol{v}_2, ..., \boldsymbol{v}_k \in \mathbb{R}^n$
$$
\mathrm{mean}\{\boldsymbol{v}_1, \boldsymbol{v}_2, ..., \boldsymbol{v}_k\} = \frac{\sum_{i=1}^k \boldsymbol{v}_i}{k}.
$$

In [58]:
def mean(vs):
    pass # TODO

Cho $\boldsymbol{v} = (v_1, v_2, .., v_n) \in \mathbb{R}^n$, ta nói vector tích lũy của $\boldsymbol{v}$, kí hiệu $\mathrm{acc}(\boldsymbol{v})$, là vector $\boldsymbol{w} = (w_1, w_2, ..., w_n) \in \mathbb{R}^n$ thỏa
$$
w_i = \sum_{j=1}^i v_j, \forall i = 1, 2, ..., n
$$
và nói vector sai phân của $\boldsymbol{v}$, kí hiệu $\mathrm{diff}(\boldsymbol{v})$, là vector $\boldsymbol{w} = (w_1, w_2, ..., w_n) \in \mathbb{R}^n$ thỏa $w_1 = v_1$ và $w_i = v_{i} - v_{i - 1}, \forall i = 2, ..., n$.

Viết các hàm tính $\mathrm{acc}(\boldsymbol{v}), \mathrm{diff}(\boldsymbol{v})$ từ $\boldsymbol{v}$ và từ đó nhận xét quan hệ giữa các vector này.

In [59]:
def acc(v):
    pass # TODO

def diff(v):
    pass # TODO

Cho $V = \{\boldsymbol{v}_1, \boldsymbol{v}_2, ..., \boldsymbol{v}_m\} \subset \mathbb{R}^n$ và $\boldsymbol{v} \in \mathbb{R}^n$, ta nói **láng giềng gần nhất** (nearest neighbor) của $\boldsymbol{v}$ trong $S$ là $\boldsymbol{w} \in S$ sao cho
$$
\| \boldsymbol{v} - \boldsymbol{w} \| \le \| \boldsymbol{v} - \boldsymbol{v}_i \|, \forall i = 1, 2, ..., m.
$$

Viết hàm tìm láng giềng gần nhất của của $\boldsymbol{v}$ trong $S$ được cho.

In [60]:
def nearest_neighbor(v, S):
    pass # TODO

Mở rộng khái niệm láng giềng gần nhất thành $k$ láng giềng gần nhất và viết hàm thực hiện.

In [61]:
def kNN(v, S, k=1):
    pass # TODO

## Cân bằng phản ứng hóa học (cộng điểm)

**Công thức hóa học** (chemical formula) của các phân tử hóa học có thể được mô tả trong Python bằng một danh sách ([`list`](https://docs.python.org/3/tutorial/datastructures.html#more-on-lists)) các bộ ([`tuple`](https://docs.python.org/3/tutorial/datastructures.html#tuples-and-sequences)). Chẳng hạn, công thức hóa học của nước $\text{H}_2\text{O}$ có thể được mô tả bởi danh sách `[("H", 2), ("O", 1)]`.

Viết hàm trả về chuỗi biểu diễn LaTeX của công thức hóa học.

In [62]:
def chemical_formula(mol):
    pass # TODO

In [63]:
from IPython.display import Latex

mol = chemical_formula([("H", 2), ("O", 1)])
# sẽ được như
mol = r"\text{H}_2\text{O}"
print(mol)
Latex("$" + mol + "$")

\text{H}_2\text{O}


<IPython.core.display.Latex object>

Mở rộng hàm trên để cho phép công thức có chứa các nhóm nguyên tử. Chẳng hạn, công thức hóa học của nhôm sunfat $\text{Al}_2(\text{S}\text{O}_4)_3$ có thể được mô tả bởi danh sách `[("Al", 2), ([("S", 1), ("O", 4)], 3)]`.

In [64]:
mol = chemical_formula([("Al", 2), ([("S", 1), ("O", 4)], 3)])
# sẽ được như
mol = r"\text{Al}_2(\text{S}\text{O}_4)_3"
print(mol)
Latex("$" + mol + "$")

\text{Al}_2(\text{S}\text{O}_4)_3


<IPython.core.display.Latex object>

Một **phản ứng hóa học** (chemical reaction) có thể được mô tả bởi 2 danh sách: danh sách các **phân tử tham gia phản ứng** (reactant) và danh sách các **phân tử sản phẩm** (product). Viết hàm cân bằng phản ứng hóa học và trả về chuỗi biểu diễn LaTeX của **phương trình hóa học** (chemical equation) đã cân bằng.

In [65]:
def balance_chemical_equation(lhs, rhs):
    "lhs là danh sách các phân tử tham gia phản ứng, rhs là danh sách các phân tử sản phẩm"
    pass # TODO

In [66]:
H2O = [("H", 2), ("O", 1)]
H2 = [("H", 2)]
O2 = [("O", 2)]

equation = balance_chemical_equation([H2O], [H2, O2])
# sẽ được như
equation = r"2\text{H}_2\text{O} \to 2\text{H}_2 + \text{O}_2"
print(equation)
Latex("$$" + equation + "$$")

2\text{H}_2\text{O} \to 2\text{H}_2 + \text{O}_2


<IPython.core.display.Latex object>

In [67]:
Al_OH3 = [("Al", 1), ([("O", 1), ("H", 1)], 3)]
H2_SO4 = [("H", 2), ([("S", 1), ("O", 4)], 1)]
Al2_SO43 = [("Al", 2), ([("S", 1), ("O", 4)], 3)]
H2O = [("H", 2), ("O", 1)]

equation = balance_chemical_equation([Al_OH3, H2_SO4], [Al2_SO43, H2O])
# sẽ được như
equation = r"2\text{Al}(\text{O}\text{H})_3 + 3\text{H}_2\text{S}\text{O}_4 \to \text{Al}_2(\text{S}\text{O}_4)_3 + 6\text{H}_2\text{O}"
print(equation)
Latex("$$" + equation + "$$")

2\text{Al}(\text{O}\text{H})_3 + 3\text{H}_2\text{S}\text{O}_4 \to \text{Al}_2(\text{S}\text{O}_4)_3 + 6\text{H}_2\text{O}


<IPython.core.display.Latex object>

In [72]:
Latex("$$\color{blue}{\large{SOLUTION - 18127208\ NGO\ THANH\ PHUONG\ THAI}}$$")

<IPython.core.display.Latex object>

In [79]:
import numpy as np
import re
from fractions import Fraction
import math
from math import gcd
from IPython.display import Latex
from functools import reduce

# Trả về chuỗi LaTeX cho nguyên tố, nhóm nguyên tố: (SO_{4})_{3} trong Fe2(SO4)3
def get_sub(atom, n):
    # Nếu atom là nguyên tố thì trả về nguyên tố đó, chẳng hạn O_{4}
    # Còn nếu atom là một nhóm nguyên tố, thì sẽ gọi đệ quy tiếp các nguyên tố bên trong, sau đó gộp vào dấu () và thêm số lượng vào (nếu số lượng bằng 0 thì k cần dấu ()), ví dụ: (SO_{4})_{3}
    if type(atom) == str:
        res = "%s" % (atom.capitalize())
    else:
        res = ""
        for (atom_i, ni) in atom:
            res += get_sub(atom_i, ni)
        if n != 1:
            res = "(%s)" % (res)
        else:
            res = "%s" % (res)
    if n != 1:
        res += ("_{%d}" % (n))
    return res


# Trả về chỗi LaTeX cho một chất: Fe_2(SO_{4})_{3} cho Fe2(SO4)3
def chemical_formula(mol):
    # Tách từng nhóm theo chất ban đầu, lấy chuỗi LaTeX bằng get_sub, sau đó gộp lại
    return ''.join([get_sub(atom, n) for (atom, n) in mol])

# Trả về ước chung lớn nhất của list: [6, 12, 8] -> 2
def gdc_list(list):
    x = reduce(gcd, list)
    if x == 0:
        return 1
    return x

# Trả về bội chung nhỏ nhất của list: [2, 5, 8] -> 40
def lcm_list(list):
    if len(list):
        lcm = list[0]
        for i in range(1, len(list)):
            lcm = lcm * list[i] // math.gcd(lcm, list[i])
        return lcm
    else:
        return 1

# Trả về list các nguyên tố trong một chất: CuSO4 -> ["cu"", "s", "o"], sử dụng cách gọi đệ quy tương tự như hàm get_sub
def get_atom(elem):
    if type(elem) == str:
        return [elem.lower()]
    res = []
    for (elem_i, ni) in elem:
        res += get_atom(elem_i)
    return res

# Trả về số lượng của một nguyên tố trong một chất: get_num("O"", Fe2(SO4)3) -> 12, cũng sử dụng đệ quy
def get_num(atom, elem):
    res = 0
    for (sub_e, n) in elem:
        if type(sub_e) == str:
            if atom.lower() == sub_e.lower():
                return n
        else:
            res += n * get_num(atom, sub_e)
            
    return res

# Trả về dạng chuỗi của hệ só phương trình, nếu hệ số là 1 thì trả về chuỗi rỗng vì ta không cần ghi
def coefficient_to_str(coefficient):
    if coefficient == 1:
        return ""
    return str(coefficient)

# Kiểm tra xem khi tất cả các giá trị trong sol sau khi thay all_x lần lượt bằng vals có dương hết không
def is_good(all_x, vals, sol):
    for i in range(len(all_x)):
        sol = [re.sub(all_x[i], str(vals[i]), str(x)) for x in sol]
    for x in sol:
        # Gọi eval để thực thi nghiệm để kiểm tra, nếu bé hơn bằng 0 thì báo False
        if eval(x) <= 0:
            return [False, sol]
    return [True, sol]

# Giải ma trận (A|B), nếu có vô số nghiệm thì trả về 1 tập nghiệm nguyên bất kì
def solve(A_bar):
    R = Gauss_elimination(to_fraction(A_bar), leading1=False)
    res = back_substitution(R)

    # Tìm tất cả mẫu số trong các nghiệm tìm được
    denominators = []
    for x in res:
        # Dùng regular expression để tìm các chuỗi có dạng /1, /2 -> /(một số nào đó)
        tmp = re.findall(r"/\d", str(x))
        if tmp:
            # tmp có dạng ["/number"] -> Lấy phần tử thứ 0, lấy chuỗi từ vị trí thứ 1, chuyển sang số nguyên -> number sau dó gộp vào denominators
            denominators.append(int(tmp[0][1:]))

    # Tìm bội chung nhỏ nhất từ các mẫu số để quy đồng
    lcm = lcm_list(denominators)

    # Tìm các ẩn tự do (x4, x3,...) trong các nghiệm tìm được
    all_x = []
    for x in res:
        all_x += re.findall("x\d", str(x))

    # Loại bỏ các ẩn tự do trùng
    all_x = list(dict.fromkeys(all_x))

    # Tạo một list (vector) 0 với kích thước bằng tổng số ẩn tự do, mỗi phần tử tương ứng sẽ được dùng để thay vào các ẩn tự do bên trên
    vals = [0] * len(all_x)

    # Thay đổi giá trị của vals bằng các số nguyên random, sao cho tất cả các nghiệm tìm được đều DƯƠNG khi thay vals vào
    while True:
        req = is_good(all_x, vals, res)
        if req[0]:
            res = req[1]
            break
        vals = np.random.randint(0, 50, len(all_x))

    # Sau khi các ẩn tự do trong res đã được thay bằng vals, gọi eval để tính giá trị, sau đó nhân với bội chung (lcm) để quy đồng cho nguyên, rồi chuyển sang số nguyên rồi cập nhận lại res
    res = [int(eval(str(x)) * lcm) for x in res]

    # Tìm ước chung nhỏ nhất từ các nghiệm mới vừa tính xong, vì sau khi nhân có thể chúng sẽ không tối giản
    gcd = gdc_list(res)

    # Sau khi tìm được gcd, ta sẽ chia lại tập nghiệm lần nữa cho tối giản
    res = [int(x / gcd) for x in res]

    # Trả về tập nghiệm cuối cùng
    return res

# Trả về chuỗi LaTeX của phản ứng sau khi đã cân bằng
def balance_chemical_equation(lhs, rhs):
    # Tìm tất cả các nguyên tố có trong phương trình (lhs tương tự rhs theo bảo toàn nguyên tố)
    all_atom = []
    for elem in lhs:
        all_atom += get_atom(elem)

    # Loại bỏ các nguyên tố trùng do các chất có thể có nguyên tố giống nhau
    all_atom = list(dict.fromkeys(all_atom))

    # Tạo ma trận A_bar = (A|B) = (left - right | 0)
    A_bar = []
    for atom in all_atom:
        left = []
        for elem in lhs:
            left.append(get_num(atom, elem))

        right = []
        for elem in rhs:
            # Chuyển sang vế trái nên đổi dấu
            right.append(-get_num(atom, elem))
        
        row = left + right
        row.append(0)

        A_bar.append(row)

    # Tìm tập nghiệm nguyên bất kì thoả mãn, đây sẽ là hệ số của cả phương trình từ trái sang phải
    res = solve(A_bar)

    # Gán chỉ số vào trước các chất
    lhs = [coefficient_to_str(x) + y for x, y in zip(res, map(chemical_formula, lhs))]
    rhs = [coefficient_to_str(x) + y for x, y in zip(res[len(lhs):], map(chemical_formula, rhs))]

    # Gộp theo vế phương trình với dấu + giữa các chất
    l = "+".join(lhs)
    r = "+".join(rhs)

    # Trả về phương trình đã được cân bằng
    return l + r" \to " + r

In [80]:
# ---------------------------------------------
# Khai báo một số chất

FeSO4 = [("fe", 1), ([("s", 1), ("o", 4)], 1)]
KMnO4 = [("k", 1), ("mn", 1), ("o", 4)]
H2O = [("H", 2), ("O", 1)]
MnO2 = [("mn", 1), ("o", 2)]
Fe2_SO4_3 = [("fe", 2), ([("s", 1), ("o", 4)], 3)]
Fe_OH3 = [("fe", 1), ([("o", 1), ("h", 1)], 3)]
K2SO4 = [("k", 2), ([("s", 1), ("o", 4)], 1)]
CuFeS2 = [("cu", 1), ("fe", 1), ("s", 2)]
O2 = [("o", 2)]
CuSO4 = [("cu", 1), ([("s", 1), ("o", 4)], 1)]
H2SO4 = [("h", 2), ([("s", 1), ("o", 4)], 1)]
Al_OH3 = [("Al", 1), ([("O", 1), ("H", 1)], 3)]
Al2_SO4_3 = [("Al", 2), ([("S", 1), ("O", 4)], 3)]

# ---------------------------------------------

In [101]:
# Phương trình 1: (Phương trình có 1 ẩn tự do)
# 2Al(OH)3 + 3H2SO4 -> Al2(SO4)3 + 6H2O

equation = balance_chemical_equation([Al_OH3, H2SO4], [Al2_SO4_3, H2O])
Latex("$" + equation + "$")

<IPython.core.display.Latex object>

In [108]:
# Phương trình 2: (Phương trình có 1 ẩn tụ do))
# 18FeSO4 + 6KMnO4 + 12H2O -> 6MnO2 + 5Fe2(SO4)3 + 8Fe(OH)3 + 3K2SO4

equation = balance_chemical_equation([FeSO4, KMnO4, H2O], [MnO2, Fe2_SO4_3, Fe_OH3, K2SO4])
Latex("$" + equation + "$")

<IPython.core.display.Latex object>

In [172]:
# Phương trình 3: (Phương trình có 2 ẩn tự do)
# 3CuFeS2 + 8Fe2(SO4)3 + 8O2 + 8H2O -> 3CuSO4 + 19FeSO4 + 8H2SO4

equation = balance_chemical_equation([CuFeS2, Fe2_SO4_3, O2, H2O], [CuSO4, FeSO4, H2SO4])
Latex("$" + equation + "$")

<IPython.core.display.Latex object>