Array

Practice Sheet (ZMD)

In [27]:
#Question 1
import numpy as np

n = 5
m = 3

array_a = np.array([1, 2, 3, 4, 5])
array_b = np.array([1, 2, 3])

joint = np.zeros(n+m, dtype = int)

for i in range(n):
    joint[i] = array_a[i]

for j in range(m):
    joint[n + j] = array_b[j]

joint = set(joint)

print(len(joint))

5


In [28]:
#Question 2
import numpy as np

n = 8
arr = np.array([1, -1, 3, 2, -7, -5, 11, 6])

shape = arr.shape
length = shape[0]

pos_index = 0
neg_index = n-1

for i in range(len(arr)):
    if arr[i] < 0:
        arr[neg_index] = arr[i]
        neg_index -= 1

for j in range(len(arr)):
    if arr[j] > 0:
        arr[pos_index] = arr[j]
        pos_index += 1

print(arr)

[ 1  3  3 -1 -7 -5 -7 -1]


In [29]:
#Question 3

def subarray(n, s, a):
    list1 = []

    start = 0
    end = 0

    sum = 0

    for i in range(len(a)):
        while sum <= s:
            sum += a[i]
            list1.append(a[i])
            if sum != s:
                continue

    start = a.index(list1[0])
    end = a.index(list1[len(list1)-1])

    return start, end

subarray(5, 12, [1,2,3,7,5])

(0, 0)

In [30]:
#Question 4
import numpy as np

def frequency(n, a, x):
    arr = np.array(a)
    
    shape = arr.shape
    length = shape[0]

    count = 0

    for i in range(length):
        if arr[i] == x:
            count += 1
        
    return count

frequency(5, [1, 1, 1, 1, 1], 1)

5

In [31]:
#Question 5
import numpy as np

def abc(n, a, k):
    arr = np.array(a)
    shape = arr.shape
    length = shape[0]

    arr = sorted(arr)

    for i in range(length):
        if i == k:
            print(arr[k-1])

abc(6, [7, 10, 4, 3, 20, 15], 3)
abc(5, [7, 10, 4, 20, 15], 4)

7
15


In [32]:
#Bubble Sort

arr = [7, 10, 4, 3, 20, 15]

for i in range(len(arr)):
    for j in range(i+1,len(arr)):
        if arr[j] < arr[i]:
            temp = arr[i]
            arr[i] = arr[j]
            arr[j] = temp

print(arr)

[3, 4, 7, 10, 15, 20]


In [33]:
#Question 6
import numpy as np

def ascendingsort(n, arr):
    for i in range(len(arr)):
        for j in range(i+1,len(arr)):
            if arr[j] < arr[i]:
                temp = arr[i]
                arr[i] = arr[j]
                arr[j] = temp

    return arr

ascendingsort(5, [0, 2, 1, 2, 0])

[0, 0, 1, 2, 2]

In [34]:
#Question 7
import numpy as np

def watertrapper(n, arr):
    arr = np.array(arr)

    shape = arr.shape
    length = shape[0]

    max = 0
    for i in range(length):
        if arr[i] > max:
            max = arr[i]

    max_2 = 0
    for j in range(length):
        if arr[j] > max_2:
            if arr[j] == max:
                pass
            else:
                max_2 = arr[j]

    trap_count = 0
    for k in range(length):
        while arr[k] < max_2:
            arr[k] += 1
            trap_count += 1

    print(trap_count)

watertrapper(4, [7,4,0,9])
watertrapper(6, [3, 0, 0, 2, 0, 4])
watertrapper(14, [3,0,2,5,2,8,0,9,7,10,0,5,1,3])

10
10
72


In [35]:
#Question 8
import numpy as np

def wavesorting(n, arr):
    arr = np.array(arr)

    shape = arr.shape
    length = shape[0]

    for i in range(length-1):
        if i%2 == 0:
            temp = arr[i]
            arr[i] = arr[i+1]
            arr[i+1] = temp

    return arr

wavesorting(5, [1,2,3,4,5])

array([2, 1, 4, 3, 5])

In [36]:
#Question 9
import numpy as np

def majority(n, arr):
    arr = np.array(arr)

    shape = arr.shape
    length = shape[0]

    max_count = 0

    for i in range(length):
        temp = arr[i]
        count = 0
        for j in range(length):
            if arr[j] == temp:
                count += 1
                if max_count < count:
                    max_count = count

    if max_count > n/2: return max_count
    
    else: return -1

majority(5, [3,1,3,3,2])
majority(3, [1,2,3])

-1

In [ ]:
#Question 10
import numpy as np

def jumper(n, arr):
    arr = np.array(arr)

    shape = arr.shape
    length = shape[0]

    jump_count = 0

    for i in range(length):
        temp = arr[i]
        jump = arr[i+temp]
        arr[temp+jump]
        jump_count += 1

    return jump_count

jumper(11, [1, 3, 5, 8, 9, 2, 6, 7, 6, 8, 9])

Quiz 1 Prep (04.10.2024)

In [148]:
#Linear Search Practice
import numpy as np
student_ids = [1002, 1503, 1801, 1090, 1250, 1423]
target_id = 1090

arr = np.array(student_ids)
length = arr.shape[0]

for i in range(length):
    if arr[i] == target_id:
        print("at index:",i,"found the desired value",arr[i])

at index: 3 found the desired value 1090


In [149]:
#binary search practice
import numpy as np

def binarysearch(price, target):
    arr = np.array(price)
    length = arr.shape[0]

    low = 0
    high = length-1

    while low <= high:
        mid = (high+low)//2

        if arr[mid] == target:
            return True
        elif arr[mid] < target:
            low = mid + 1
        else:
            high = mid - 1
    
    return -1

prices = [10, 20, 35, 50, 60, 75, 80, 95, 100]
target_price = 75
binarysearch(prices, target_price)

True

https://docs.google.com/document/d/1HOCXMA5BOnwNkGY0JJuOsOnMwQHmOAIqEvg4_9zuBec/edit?tab=t.0

In [150]:
#Task 1 (shift left)
import numpy as np

def shiftleft(source, k):
    arr = np.array(source)
    length = arr.shape[0]

    for i in range(length):
        if k+i < length:
            arr[i] = arr[k+i]

        elif k + i >= length:
            arr[i] = 0

    return arr

shiftleft([10,20,30,40,50,60], 3)

array([40, 50, 60,  0,  0,  0])

In [151]:
#Task 1
import numpy as np

def shiftleft(source, k):
    arr = np.array(source)
    length = arr.shape[0]
    
    for i in range(k):
        for j in range(0,length-1):
            arr[j] = arr[j+1]
        arr[length-1] = 0

    #return arr
    print(arr)

shiftleft([10,20,30,40,50,60], 3)

[40 50 60  0  0  0]


In [152]:
#Task 2 (rotate left)
import numpy as np

def rotateleft(source, k):
    arr = np.array(source)
    length = arr.shape[0]

    temp = np.zeros(k, dtype = int)

    for i in range(k):
        temp[i] = arr[i]

    for i in range(length):
        if k+i < length:
            arr[i] = arr[k+i]

    j = 0
    for i in range(k+1,length):
        arr[i] = temp[j]
        j += 1

    return arr
        
rotateleft([10,20,30,40,50,60,70], 3)

array([40, 50, 60, 70, 10, 20, 30])

In [153]:
#Task 2
import numpy as np

def rotateleft(source, k):
    arr = np.array(source)
    length = arr.shape[0]
    
    k = k % length

    temp = np.zeros(k, dtype=int)
    for i in range(k):
        temp[i] = arr[i]
    
    for i in range(k, length):
        arr[i - k] = arr[i]
    
    for i in range(k):
        arr[length - k + i] = temp[i]

    return arr

# Test the function
rotateleft([10, 20, 30, 40, 50, 60, 70], 3)

array([40, 50, 60, 70, 10, 20, 30])

In [154]:
#Task 3 (shift right)
import numpy as np

def shiftright(source, k):
    arr = np.array(source)
    length = arr.shape[0]

    for i in range(k,-1,-1):
        if k+i < length:
            arr[k+i] = arr[i]

    for j in range(k):
        arr[j] = 0

    #return arr
    print(arr)

shiftright([10, 20, 30, 40, 50, 60], 3)
shiftright([10, 20, 30, 40, 50, 60, 70], 3)

[ 0  0  0 10 20 30]
[ 0  0  0 10 20 30 40]


In [155]:
#Task 3
import numpy as np

def shiftright(source, k):
    arr = np.array(source)
    length = arr.shape[0]
    for i in range(k):
        for j in range(length-1,-1,-1):
            arr[j] = arr[j-1]
        arr[0] = 0
    
    #return arr
    print(arr)

shiftright([10, 20, 30, 40, 50, 60], 3)
shiftright([10, 20, 30, 40, 50, 60, 70], 3)

[ 0  0  0 10 20 30]
[ 0  0  0 10 20 30 40]


In [156]:
#Task 4 (rotate right)
import numpy as np

def rotateright(source, k):
    arr = np.array(source)
    length = arr.shape[0]
    
    k = k % length

    temp = np.zeros(k, dtype=int)
    for i in range(k):
        temp[i] = arr[length - k + i]
    
    for i in range(length - k - 1, -1, -1):
        arr[i + k] = arr[i]
    
    for i in range(k):
        arr[i] = temp[i]

    return arr

# Test the function
rotateright([10, 20, 30, 40, 50, 60, 70], 3)

array([50, 60, 70, 10, 20, 30, 40])

Random Array Practice

In [157]:
#move zeros to end without sorting (brute)

import numpy as np

def movezerostoend(source):
    arr = np.array(source)
    length = arr.shape[0]

    temp = np.zeros(arr.size, dtype = int)

    j = 0
    k = length - 1
    for i in range(length):
        if arr[i] != 0:
            temp[j] = arr[i]
            j += 1
        elif arr[i] == 0:
            temp[k] = arr[i]
            k -= 1
    
    print(temp)

movezerostoend([1,0,2,3,2,0,0,4,5,1,6,9,0,1,2,3])
movezerostoend([0,1,0,3,12])

[1 2 3 2 4 5 1 6 9 1 2 3 0 0 0 0]
[ 1  3 12  0  0]


In [158]:
#move zeros to end without sorting (optimal)
import numpy as np

def movezerostoend(source):
    arr = np.array(source)
    length = arr.shape[0]

    j = -1
    for i in range(length):
        if arr[i] == 0:
            j = i
            break

    if j == -1: return arr

    for i in range(j+1, length):
        if arr[i] != 0:
            arr[i], arr[j] = arr[j], arr[i]
            j += 1

    print(arr)

movezerostoend([1,0,2,3,2,0,0,4,5,1,6,9,0,1,2,3])
movezerostoend([0,1,0,3,12])

[1 2 3 2 4 5 1 6 9 1 2 3 0 0 0 0]
[ 1  3 12  0  0]


Linked List

Singly Linked List

set of codes to create nodes, linked list, and printing a linked list

In [159]:
#Run this cell
import numpy as np

class Node:
  def __init__(self,elem,next = None):
    self.elem,self.next = elem,next

def createList(arr):
  head = Node(arr[0])
  tail = head
  for i in range(1,len(arr)):
    newNode = Node(arr[i])
    tail.next = newNode
    tail = newNode
  return head

def printLinkedList(head):
  temp = head
  while temp != None:
    if temp.next != None:
      print(temp.elem, end = '-->')
    else:
      print(temp.elem)
    temp = temp.next
  print()

In [160]:
#Understanding and printing singly linked list (manual)
class Node:
    def __init__(self, elem, next = None):
        self.elem = elem
        self.next = next

a = Node(10)
b = Node(20)
c = Node(30)

a.next = b
b.next = c
c.next = None #not necessary

def printLL(head): #notice that we are calling the address from head, not the element
    temp = head #good practice as head is the only info we have about LL
    print(temp.elem, end = " ") #address of the node we called & .ELEM to access the value
    temp = temp.next
    print(temp.elem, end = " ")
    temp = temp.next
    print(temp.elem)

printLL(a)

10 20 30


In [38]:
#printing singly linked list (using loops)
class Node:
    def __init__(self, elem, next = None):
        self.elem = elem
        self.next = next

a = Node(10)
b = Node(20)
c = Node(30)
d = Node(40)
e = Node(50)

a.next = b
b.next = c
c.next = d
d.next = e

def printLL(head):
    temp = head

    while temp != None:
        print(temp.elem, end = " ")
        temp = temp.next

printLL(a)

10 20 30 40 50 

In [162]:
#AHU Basics
import numpy as np

arr = np.array([10, 20, 30, 40, 50, 60, 70])

class Node:
    def __init__(self, elem, next = None):
        self.elem = elem
        self.next = next

def createLL(array):
    head = Node(arr[0])
    tail = head

    for i in range(1, len(arr)):
        new_node = Node(arr[i])
        tail.next = new_node
        tail = new_node
    return head

def printLL(head):
    temp = head
    
    while temp != None:
        print(temp.elem, end = " ")
        temp = temp.next

x = createLL(arr)
#printLL(x)

def insert(head, position, new_val):
    temp = head
    count = 0
    while temp != None:
        if count == position:
            new_node = Node(new_val)
            new_node.next = temp.next
            temp.next = new_node
            return head
        count += 1
        temp = temp.next

y = insert(x, 2, 100)
#printLL(x)

def remove(head, position):
    temp = head
    count = 0
    while temp != None:
        if count == position - 1:
            x = temp.next #not mandatory
            temp.next = temp.next.next
            x.next = None #not mandatory
        count += 1
        temp = temp.next

z = remove(x, 2)
printLL(x)


10 20 100 40 50 60 70 

Reverse a Singly Linked List

In [163]:
def reverse_LL(head1):
  new_head = Node(head1.elem)
  temp = head1.next

  while temp != None:
    n = Node(temp.elem, new_head)
    new_head = n
    temp = temp.next

  return new_head

head1 = createList(np.array([0,3,2,2]))
x = reverse_LL(head1)
printLinkedList(x)

2-->2-->3-->0



Random Singly Linked List Practice

Practice (AHU)

1. count

2. min/max

3. avg

4. search

5. value given, add after its position

6. value given, remove the node with that value

In [164]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50, 60, 70])

class Node:
    def __init__(self, elem, next = None):
        self.elem = elem
        self.next = next

def createLL(array):
    head = Node(arr[0])
    tail = head
    for i in range(1, len(arr)):
        new_node = Node(arr[i])
        tail.next = new_node
        tail = new_node
    return head

def basics(head):
    temp = head
    count = 0
    sum = 0
    avg = int()
    while temp != None:
        count += 1
        sum += temp.elem
        temp = temp.next
    
    avg = sum/count

    new_temp = head

    min = float('inf')
    max = float('-inf')
    while new_temp != None:
        if new_temp.elem < min:
            min = new_temp.elem
        
        if new_temp.elem > max:
            max = new_temp.elem

        new_temp = new_temp.next

    return f"length: {count} sum: {sum} average: {avg} min: {min}, max: {max}"

def insertfor(head, value, new_data):
    temp = head
    while temp != None:
        if temp.elem == value:
            new_data = Node(new_data)
            new_data.next = temp.next
            temp.next = new_data
            break
        temp = temp.next

def removeit(head, value):
    temp = head
    while temp != None:
        if temp.next.elem == value:
            n = temp.next.next
            temp.next = n
            break #loop will collapse if I don't use break
        temp = temp.next


def printLL(head):
    temp = head
    while temp != None:
        print(temp.elem, end = " ")
        temp = temp.next

x = createLL(arr)
printLL(x)
print()
print(basics(x))
insertfor(x, 20, 100)
printLL(x)
removeit(x, 30)
print()
printLL(x)

10 20 30 40 50 60 70 
length: 7 sum: 280 average: 40.0 min: 10, max: 70
10 20 100 30 40 50 60 70 
10 20 100 40 50 60 70 

Doubly Linked List

set of codes to create doubly nodes, doubly linked list, and printing a  doubly linked list

In [165]:
#Run this cell
import numpy as np

class Node:
    def __init__(self, elem, next = None, prev = None):
        self.elem = elem
        self.next = next
        self.prev = prev

def create_DLL(arr):
    dh = Node(None)
    dh.next = dh
    dh.prev = dh
    for i in range(len(arr)):
        new_node = Node(arr[i])
        dh.prev.next = new_node
        new_node.prev = dh.prev
        new_node.next = dh
        dh.prev = new_node
    return dh

def print_DLL(dh):
    temp = dh.next
    while temp.elem != None:
        print(temp.elem, end = " -> ")
        temp = temp.next
    return

Reversing a Doubly Linked List

In [166]:
#Approach 1
def reverse_DLL(dh):
    dh1 = Node(None)
    dh1.next = dh1
    dh1.prev = dh1

    temp = dh.next
    while temp.elem != None:
        new_node = Node(temp.elem)
        new_node.next = dh1.next
        new_node.prev = dh1
        dh1.next.prev = new_node
        dh1.next = new_node
        temp = temp.next
    return dh1

p = create_DLL(np.array([10,20,30,40,50]))
p2 = reverse_DLL(p)
print_DLL(p2)

50 -> 40 -> 30 -> 20 -> 10 -> 

In [167]:
#Approach 2 (in-place swapping)
def length(dh):
    count = 1
    temp = dh.next
    while temp.elem != None:
        count += 1
        temp = temp.next
    return count

def reverse_DLL(dh):
    size = length(dh)
    a= dh.next
    b = dh.prev
    for i in range(size//2):
        a.elem, b.elem = b.elem, a.elem
        a = a.next
        b = b.prev
    return dh

p = create_DLL(np.array([10,20,30,40,50]))
p2 = reverse_DLL(p)
print_DLL(p2)

50 -> 40 -> 30 -> 20 -> 10 -> 

Random Doubly Linked List Practice

Stack

set of codes to create Stack, push, pop, peek and check if an stack is empty, and print a stack

In [174]:
#Run this cell
class Node:
  def __init__(self,elem=None,next=None):
    self.elem = elem
    self.next = next

class Stack:
  def __init__(self):
    self.__top = None

  def push(self,elem):
    nn = Node(elem,self.__top)
    self.__top = nn

  def pop(self):
    if self.__top == None:
      #print('Stack Underflow')
      return None
    e = self.__top
    self.__top = self.__top.next
    return e.elem

  def peek(self):
    if self.__top == None:
      #print('Stack Underflow')
      return None
    return self.__top.elem

  def isEmpty(self):
    return self.__top == None

def print_stack(st):
  if st.isEmpty():
    return
  p = st.pop()
  print('|',p,end=' ')
  if p<10:
    print(' |')
  else:
    print('|')
  #print('------')
  print_stack(st)
  st.push(p)

In [26]:
#Stack Implementation
class Node:
  def __init__(self,elem=None,next=None):
    self.elem = elem
    self.next = next
    
class Stack:
    def __init__(self):
        self.top = None
    
    def push(self, value):
        n = Node(value, None)
        n.next = self.top
        self.top = n
    
    def pop(self):
        if self.top == None:
            return None
        else:
            temp = self.top
            self.top = top.next
            temp.next = None
            return temp.element
        
    def peek(self):
        if self.top == None:
            return None
        else:
            return self.top.element
        
    def isEmpty(self):
        if self.top == None:
            return True
        else:
            return False

Random Stack Practice

In [ ]:
#Counting and Reversing a Stack
def length(stack):
    r_stack = Stack()
    count = 0

    while stack.isEmpty() == False:
        x = stack.pop()
        r_stack.push(x)
        count += 1
    
    print(f"Length of stack: {count}")
    return r_stack

#driver code
st = Stack()
st.push(1)
st.push(2)
st.push(3)
st.push(4)
st.push(5)
st.push(6)
st.push(7)
st.push(8)

print("Original Stack:")
print_stack(st)
print()
size_reverse = length(st)
print()
print("Reversed Stack:")
print_stack(size_reverse)

Mid Prep (24.11.2024)

Spring'24

In [ ]:
#Question 1(i)
import numpy as np
def indexfinder(arr):

        row_count = arr.shape[0]
        col_count = arr.shape[1]
        dim_count = arr.shape[2]

        count = 0
        
        for row in range(row_count):
                for col in range(col_count):
                        for dim in range(dim_count):
                                if row == 2 and col == 1 and dim == 0:
                                        return count
                                else:
                                        count += 1

arr = np.array([[[ 86, 100,  67,  23],
        [ 28,  29,  96,  19],
        [ 24,  24,  55,   4],
        [ 59,  36,  27,  63],
        [ 85,  77,  44,  47]],

       [[ 89,  15,  44,  18],
        [ 22,  27,  28,  24],
        [ 85,  52, 100,  43],
        [ 68,  83,  64,  33],
        [ 64, 100,  25,  77]],

       [[ 13,  33,   4,  27],
        [ 14,  15,  36,  35],
        [ 84,  29,  19,   2],
        [ 27, 100,  31,  80],
        [ 54,  12,   8,  97]],

       [[ 48,  48,   9,  45],
        [ 52,  86,  52,  89],
        [ 14,   4,  80,  39],
        [ 44,  19,  86,  60],
        [ 42,  39,  70,  10]]])

indexfinder(arr)

In [ ]:
#Question 1(ii)
import numpy as np
def sum_diff(matrix):
    arr = matrix

    row_count = arr.shape[0]
    col_count = arr.shape[1]

    sum1 = 0
    sum2 = 0
    sum3 = 0
    
    for col in range(col_count):
        for row in range(row_count):
            if col == 0:
                sum1 += arr[row][col]
            if col == 1:
                sum2 += arr[row][col]
            if col == 2:
                sum3 += arr[row][col]

    idx1 = sum2 - sum1
    idx2 = sum3 - sum2

    result = np.array((idx1, idx2))

    return result

matrix=np.array([[1,3,1],
                 [6,4,2],
                 [5,1,7],
                 [9,3,3],
                 [8,5,4]
                 ])
sum_diff(matrix)

In [ ]:
#Question 2
def IsSumPossible(head, n):
    temp = head

    while temp.next != None:
        first_p = temp
        second_p = temp.next

        while second_p != None:
            if first_p.elem + second_p.elem == n:
                return True
            second_p = second_p.next

        temp = temp.next

    return False

head = createList(np.array([1,2,3,4,5]))
x = IsSumPossible(head, 7)
print(x)

head = createList(np.array([1,2,4,5,6]))
y = IsSumPossible(head, 4)
print(y)

head = createList(np.array([5]))
z = IsSumPossible(head, 5)
print(z)

Summer'24

In [ ]:
#Quesion 1(i)
def indexfinder(arr):
    row_count = arr.shape[0]
    col_count = arr.shape[1]
    dim1_count = arr.shape[2]
    dim2_count = arr.shape[3]
    count = 0

    for row in range(row_count):
        for col in range(col_count):
            for dim1 in range(dim1_count):
                for dim2 in range(dim2_count):
                    if row == 2 and col == 1 and dim1 == 0 and dim2 == 4:
                        return count
                    else:
                        count += 1


arr = np.zeros((4,3,2,6), dtype = int)
indexfinder(arr)

In [ ]:
#Question 1(ii)
def rotate(arr):
    row_count = arr.shape[0]
    col_count = arr.shape[1]
    i = row_count - 1
    j = 0
    for row in range(row_count):
        for col in range(col_count):
            if col == col_count -1:
                arr[i][j], arr[row][col] = arr[row][col], arr[i][j]
            j += 1
        j =  0

    return arr

arr = np.array(
    ([1,2,3],
    [5,6,7],
    [9,10,11])
    )

rotate(arr)

In [ ]:
#Question 1(ii)
import numpy as np

def rotate(mat):
    row=mat.shape[0]
    column=mat.shape[1]

    for i in range(row-1):
         temp=mat[0][0]
         r=0
         c=0
         while c<column-1:
              mat[r][c]=mat[r][c+1]
              c+=1
         while r<row-1:
              mat[r][c]=mat[r+1][c]
              r+=1
         while c>0:
              mat[r][c]=mat[r][c-1]
              c-=1
         while r>0:
              mat[r][c]=mat[r-1][c]
              r-=1
         
         mat[1][0]=temp
         
    return mat

mat=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]) 
print(rotate(mat))

In [ ]:
#Question 2
def remove_Duplicates(head):
    temp = head

    while temp != None:
        first_p = temp
        second_p = temp.next
        while second_p != None:
            if second_p.elem == temp.elem:
                first_p.next = second_p.next
            else:
                first_p = second_p
            second_p = second_p.next
        temp = temp.next

    return head

head = createList(np.array([101,103,101,102,103,104,105,105]))
x = remove_Duplicates(head)
printLinkedList(x)

In [ ]:
#Question 3(i)
def Do_Adjacent_Swap(stack):
    count = 0
    st2 = Stack()

    while stack.isEmpty() == False:
        x = stack.pop()
        st2.push(x)     #st2.push(stack.pop())
        count += 1

    for i in range(count//2):
        x = st2.pop()
        y = st2.pop()
        st.push(y)
        st.push(x)

    if count % 2 != 0: #for odd case scenario
        st.push(st2.pop())
    
    return st

#driver code
st = Stack()
st.push(1)
st.push(2)
st.push(3)
st.push(4)
st.push(5)
st.push(6)
st.push(7)
st.push(8)
st.push(9)

print("Original Stack:")
print_stack(st)
print("Stack after operating")
op = Do_Adjacent_Swap(st)
print_stack(op)

Fall'23

In [ ]:
#Question 1(i)
import numpy as np

lst = ([[[5, 1, 5],
        [5, 3, 4],
        [7, 4, 6],
        [1, 5, 4],
        [8, 8, 5]],

       [[8, 7, 5],
        [4, 2, 8],
        [1, 9, 1],
        [2, 3, 9],
        [7, 4, 1]],

       [[9, 6, 3],
        [7, 9, 0],
        [4, 8, 2],
        [4, 4, 1],
        [6, 9, 5]],

       [[8, 5, 9],
        [8, 2, 5],
        [3, 8, 1],
        [8, 5, 9],
        [8, 6, 9]],

       [[2, 4, 2],
        [9, 8, 7],
        [2, 6, 8],
        [1, 5, 0],
        [4, 7, 8]]])

arr = np.array(lst)

count = 0

for row in range(arr.shape[0]):
    for col in range(arr.shape[1]):
        for dim in range(arr.shape[2]):
            if count == 65: #we've been told to find 65th
                print(f"multidimensional index is: ({row}, {col}, {dim})")
            count += 1

In [ ]:
#Question 1(ii)
import numpy as np

def compress_matrix(matrix):
    arr = matrix
    result = np.zeros((2,2), dtype = int)
    
    i = 0
    j = 0
    for r in range(0,arr.shape[0],2):
        for c in range(0,arr.shape[1],2):
            result[i][j] = arr[r][c] + arr[r+1][c] + arr[r][c+1] + arr[r+1][c+1]
            j += 1
        i = 1
        j = 0
    return result 


matrix=np.array([[1,2,3,4],
                 [5,6,7,8],
                 [1,3,5,2],
                 [-2,0,6,-3]
                 ])
compress_matrix(matrix)

Question 2(i)

Two disadvantages of Linked Lists compared to Arrays:
1. Higher Memory Overhead:
Linked Lists require extra memory for the pointers (or references) used to link nodes together. This additional storage can make them less memory-efficient compared to arrays, where no such overhead exists.

2. Sequential Access:
Linked Lists do not support random access, so accessing an element requires traversing the list from the beginning (or end, for a doubly linked list). This makes operations like accessing the n-th element slower (O(n)) compared to arrays, where access is O(1).

In [ ]:
#Question 2 (ii)
def pairwiseEqual(h1, h2):
    temp_1 = h1

    length = 0
    while temp_1 != None:
        length += 1
        temp_1 = temp_1.next

    position = 0

    temp_1 = h1
    temp_2 = h2

    while temp_1 != None and temp_2 != None:
        if position % 2 == 0:
                    x, y = temp_1.elem, temp_1.next.elem
                    p, q = temp_2.elem, temp_2.next.elem
                    if x+y != p+q: return False
        position += 1
        temp_1 = temp_1.next
        temp_2 = temp_2.next

    return True

h1 = createList(np.array([10,15,34,41]))
h2 = createList(np.array([15,10,34,41]))
x = pairwiseEqual(h1, h2)
print(x)
h1 = createList(np.array([10,15,34,42]))
h2 = createList(np.array([15,10,34,41]))
y = pairwiseEqual(h1, h2)
print(y)

In [ ]:
#Question 3(ii)
def conditional_reverse(stack):
    r_stack = Stack() 
    while stack.isEmpty() == False:
        x = stack.pop()
        if r_stack.isEmpty == True or x != r_stack.peek():
            r_stack.push(x)

    return r_stack

#driver code
st = Stack()
st.push(10)
st.push(10)
st.push(20)
st.push(20)
st.push(30)
st.push(10)
st.push(50)

print("Original Stack:")
print_stack(st)
print("Conditionally Reversed Stack:")
r_stack = conditional_reverse(st)
print_stack(r_stack)

Original Stack:
| 50 |
| 10 |
| 30 |
| 20 |
| 20 |
| 10 |
| 10 |
Conditionally Reversed Stack:
| 10 |
| 20 |
| 30 |
| 10 |
| 50 |


Queue

set of codes to create queue, enqueue, dequeue and print a queue

In [3]:
class Node:
    def __init__(self, elem=None, next=None):
        self.elem = elem
        self.next = next

class Queue:
    def __init__(self):
        self.__front = None
        self.__rear = None

    def enqueue(self, elem):
        nn = Node(elem)
        if self.__rear is None:  # Queue is empty
            self.__front = self.__rear = nn
        else:
            self.__rear.next = nn
            self.__rear = nn

    def dequeue(self):
        if self.__front is None:  # Queue is empty
            # print('Queue Underflow')
            return None
        e = self.__front
        self.__front = self.__front.next
        if self.__front is None:  # If queue becomes empty after dequeue
            self.__rear = None
        return e.elem

    def peek(self):
        if self.__front is None:  # Queue is empty
            # print('Queue Underflow')
            return None
        return self.__front.elem

    def isEmpty(self):
        return self.__front is None

def print_queue(q):
    if q.isEmpty():
        return
    e = q.dequeue()
    print('|', e, end=' ')
    if e < 10:
        print(' |')
    else:
        print('|')
    print_queue(q)
    q.enqueue(e)

Post-Mid

Hash Functions, Sets, & Maps

Trees, Binary Trees, Binary Search Trees

set of codes to create Binary Tree Nodes, preorder, inorder and postorder traversals, and constructing a tree from an array

In [1]:
class BTNode:
  def __init__(self, elem):
    self.elem = elem
    self.right = None
    self.left = None

def preorder(root):
  if root == None:
    return
  
  print(root.elem, end = ' ')
  preorder(root.left)
  preorder(root.right)

def inorder(root):
  if root == None:
    return

  inorder(root.left)
  print(root.elem, end = ' ')
  inorder(root.right)

def postorder(root):
  if root == None:
    return

  postorder(root.left)
  postorder(root.right)
  print(root.elem, end = ' ')

#construting a 1-index based tree
def tree_construction(arr, i = 1):
  if i>=len(arr) or arr[i] == None:
    return None
  p = BTNode(arr[i])
  p.left = tree_construction(arr, 2*i)
  p.right = tree_construction(arr, 2*i+1)
  return p

Complete Binary Tree Checker

In [ ]:
def countNodes(root):
    if root is None:
        return 0
    return 1 + countNodes(root.left) + countNodes(root.right)

def isCompleteTreeHelper(root, index, total_nodes):
    # If the node is null, it's a valid placeholder in a complete binary tree
    if root is None:
        return True
    
    # If index is greater than or equal to the total number of nodes, it's not complete
    if index >= total_nodes:
        return False
    
    # Recursively check the left and right subtrees
    return (isCompleteTreeHelper(root.left, 2 * index + 1, total_nodes) and
            isCompleteTreeHelper(root.right, 2 * index + 2, total_nodes))

def isCompleteTree(root):
    if root is None:
        return True
    
    # Count the total number of nodes in the tree
    total_nodes = countNodes(root)
    
    # Check the tree's completeness
    return isCompleteTreeHelper(root, 0, total_nodes)

class TreeNode:
    def __init__(self, val=0, left=None, right=None):
        self.val = val
        self.left = left
        self.right = right

def buildTree(values):
    """
    Helper function to build a binary tree from a list of values using level order.
    `None` represents an absent child.
    """
    if not values:
        return None
    
    nodes = [TreeNode(val) if val is not None else None for val in values]
    for i, node in enumerate(nodes):
        if node:
            if 2 * i + 1 < len(nodes):
                node.left = nodes[2 * i + 1]
            if 2 * i + 2 < len(nodes):
                node.right = nodes[2 * i + 2]
    return nodes[0]

tree_incomplete = buildTree([1, 2, 3, None, 5])
print("Is tree_incomplete a complete binary tree?:", isCompleteTree(tree_incomplete))  # Expected: False
# Larger Complete Binary Tree Example
# Tree structure:
#                 1
#              /     \
#            2         3
#          /   \     /   \
#         4     5   6     7
#        / \   /
#       8   9 10

print()

tree_large_complete = buildTree([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("Is tree_large_complete a complete binary tree?:", isCompleteTree(tree_large_complete))  # Expected: True

# Larger Incomplete Binary Tree Example
# Tree structure:
#                 1
#              /     \
#            2         3
#          /   \     /   \
#         4     5   6     7
#        /       \
#       8         9
tree_large_incomplete = buildTree([1, 2, 3, 4, 5, 6, 7, 8, None, 9])
print("Is tree_large_incomplete a complete binary tree?:", isCompleteTree(tree_large_incomplete))  # Expected: False


BST - the **REMOVE** function is very smartly written here

In [23]:
class BTNode:
  def __init__(self, elem):
    self.elem = elem
    self.right = None
    self.left = None

def ArraytoBalancedBST(arr,min,max):
      if min==max:
          return BTNode(arr[max])
      
      mid=(min+max)//2

      p=BTNode(arr[mid])

      if mid>min:
       p.left=ArraytoBalancedBST(arr,min,mid-1)

      if mid<max:
       
       p.right=ArraytoBalancedBST(arr,mid+1,max)

      return p

def insert(root, val):
  if root == None: return BTNode(val)

  if val < root.elem:
    root.left = insert(root.left, val)

  else:
    root.right = insert(root.right, val)

  return root

def findMin(root):
   while root.left != None:
      root = root.left
   return root

def remove(root, key):
   if root == None: return None

   if key < root.elem:
      root.left = remove(root.left, key)
   elif key > root.elem:
      root.right = remove(root.right, key)
   else:
      if root.left == None and root.right == None:
         return None
      elif root.left == None:
         return root.right
      elif root.right == None:
         return root.left
      else:
         succ = findMin(root.right)
         root.elem = succ.elem
         root.right = remove(root.right, succ.elem)
   return root

def get_height(root):
      if root==None:
         return 0
      
      left=get_height(root.left)
      right=get_height(root.right)

      if left>right:
           return 1 + left
      return 1 + right
  
def search(root, item):
   if root.elem == item:
      return root
   
   elif item < root.elem:
      return search(root.left, item)
   else:
      return search(root.right, item)

def is_balanced(root):     
    if root==None:
          return True

    left=is_balanced(root.left)
    right=is_balanced(root.right)
    left_height = get_height(root.left)
    right_height = get_height(root.right)
    
    checker = abs(left_height - right_height)
    
    return left and right and checker <= 1

#Predecessor
def inorder_predecessor(root, x):
    while root != None: 
        if x.elem > root.elem:
            pred = root
            root = root.right
        else:
            root = root.left

    return pred

#Successor
def inorder_successor(root, x):
    while root != None:
        if x.elem < root.elem:
            succ = root
            root = root.left
        else:
            root = root.right

    return succ


def createBST(arr):
  head = BTNode(arr[0])

  for i in range(1, len(arr)):
    insert(head, arr[i])
  return head

root = createBST([45, 34, 56, 12, 54, 38, 76, 36])

def inorder(root):
  if root != None:
    inorder(root.left)
    print(root.elem, end = " ")
    inorder(root.right)

inorder(root)
print()
remove(root, 56)
inorder(root)
print()

root = BTNode("A")
root.left = BTNode("B")
root.right = BTNode("C")
root.left.left = BTNode("D")
root.left.right = BTNode("E")
root.left.right.left = BTNode("F") 

print(f"is the tree balanced: {is_balanced(root)}")

12 34 36 38 45 54 56 76 
12 34 36 38 45 54 76 
is the tree balanced: False


In [16]:
def is_balanced(root):     
    if root==None:
          return True

    left=is_balanced(root.left)
    right=is_balanced(root.right)
    left_height = get_height(root.left)
    right_height = get_height(root.right)
    
    checker = abs(left_height - right_height)
    
    return left and right and checker <= 1

root = BTNode("A")
root.left = BTNode("B")
root.right = BTNode("C")
root.left.left = BTNode("D")
root.left.right = BTNode("E")
root.left.right.left = BTNode("F")       

is_balanced(root)

True

Random Tree Practice

In [11]:
#Book Problem 5.13 (check if Binary Tree has duplicates values)
def search(root, val):
    if root == None: return False

    return (root.elem == val) or search(root.left, val) or search(root.right, val)

def find_duplicate(root):
    val = root.elem

    if search(root, val):
        return True
    
    return find_duplicate(root.left) or find_duplicate(root.right)

root = BTNode(1)
root.left = BTNode(20)
root.right = BTNode(3)
root.right.right = BTNode(4)

duplicate = find_duplicate(root)
print(duplicate)

True


In [13]:
#Book Problem 5.14 (print nodes at K distance)
def distance_measure(root, level = 0, k = 2):
    if root == None: return

    if level == k:
        print(root.elem, end = " ")

    distance_measure(root.left, level + 1, k)
    distance_measure(root.right, level + 1, k)

root = BTNode(1)
root.left = BTNode(2)
root.right = BTNode(3)
root.left.left = BTNode(4)
root.left.right = BTNode(5)
root.right.left = BTNode(8)

printer = distance_measure(root, 0, 2)

4 5 8 

In [34]:
#Book problem 5.15 (print the ancestors)
def ancestor_print(root, key):
    if root == None: return False

    if root.elem == key:
        return True

    if (ancestor_print(root.left, key) or ancestor_print(root.right, key)):
        print(root.elem, end = " ")
        return True

    return False

root = BTNode(1)
root.left = BTNode(2)
root.right = BTNode(3)
root.left.left = BTNode(4)
root.left.right = BTNode(5)
root.left.left.left = BTNode(7)

printer = ancestor_print(root, 7)

4 2 1 

In [8]:
#Book problem 5.18 (Find minimum depth)
def min_depth(root):
    if root == None: return 0

    left = min_depth(root.left)
    right = min_depth(root.right)

    if left < right:
        return 1 + left
    return 1 + right

root = BTNode(1)
root.left = BTNode(2)
root.right = BTNode(3)
root.left.left = BTNode(4)
root.left.right = BTNode(5)
root.left.left.left = BTNode(7)

min_depth(root)

2

In [48]:
#Book problem 5.21 (Binary Expression Tree)
def binary_expression(root):
    
    if type(root.elem) == int:
        return root.elem
    
    left = binary_expression(root.left)
    right = binary_expression(root.right)

    if root.elem == "+":
        return left + right
    elif root.elem == "-":
        return left - right
    elif root.elem == "*":
        return left * right
    elif root.elem == "/":
        return left / right

root = BTNode("+")
root.left = BTNode("*")
root.right = BTNode("/")
root.right.left = BTNode(21)
root.right.right = BTNode(7)
root.left.left = BTNode("-")
root.left.right = BTNode(5)
root.left.left.left = BTNode(10)
root.left.left.right = BTNode(5)

binary_expression(root)

28.0

Heaps

In [ ]:
class MinHeap:
    def __init__(self, capacity):
        self.__capacity = capacity + 1
        self.__heap = np.zeros(self.__capacity, dtype = 'int')
        self.__size = 0
    
    def capacity(self):
        return self.__capacity
    
    def size(self):
        return self.__size

    def left_child(self, i):
        return 2 * i
    
    def right_child(self, i):
        return 2 * i + 1

    def insert(self, value):
        if self.size() >= self.capacity():
            return "limit exceeded"
        
        self.__size += 1
        self.__heap[self.size()] = value
        self.swim(self.size())

    def swim(self, index):
        if index > 1 and self.__heap[index] < self.__heap[index // 2]:
            self.__heap[index], self.__heap[index // 2] = self.__heap[index // 2], self.__heap[index]
            self.swim(index // 2)

    def sink(self, index):
        smallest = index
        left = self.left_child(index)
        right = self.right_child(index)

        if left <= self.size() and self.__heap[smallest] > self.__heap[left]:
            smallest = left
        if right <= self.size() and self.__heap[smallest] > self.__heap[right]:
            smallest = right

        if smallest != index:
            self.__heap[index], self.__heap[smallest] = self.__heap[smallest], self.__heap[index]
            self.sink(smallest)

    def extractMin(self):
        # if self._size == 0:
        #     return "Heap is empty"
        
        min_val = self.__heap[1]
        self.__heap[1] = self.__heap[self.size()]
        #self.__heap[self.size()] = 0
        self.__size -= 1
        self.sink(1)
        return min_val

    def isEmpty(self):
        if self.size() == 0:
            return True
        else:
            return False

    def top(self):
        if self.__heap[1] != None:
            return self.__heap[1]
        else:
            return "Empty Heap"
        
    def sort(self):
        min_result_array = np.zeros(self.size(), dtype = 'int')
        j = self.__size - 1

        while self.isEmpty() == False:
            min_result_array[j] = int(self.extractMin())
            j -= 1

        return min_result_array

    def print_heap(self):
        for value in range(self.__size + 1):
            print(self.__heap[value], end = " ")

In [ ]:
class MaxHeap:
    def __init__(self, capacity):
        self.__capacity = capacity + 1
        self.__heap = np.zeros(self.__capacity, dtype = 'int')
        self.__size = 0

    def capacity(self):
        return self.__capacity
    
    def size(self):
        return self.__size
    
    def left_child(self, i):
        return 2 * i
    
    def right_child(self, i):
        return 2 * i + 1

    def insert(self, value):
        if self.size() >= self.capacity():
            return "limit exceeded"
        
        self.__size += 1
        self.__heap[self.size()] = value
        self.swim(self.size())

    def swim(self, index):
        if index > 1 and self.__heap[index] > self.__heap[index // 2]:
            self.__heap[index], self.__heap[index // 2] = self.__heap[index // 2], self.__heap[index]
            self.swim(index // 2)

    def sink(self, index):
        largest = index
        left = self.left_child(index)
        right = self.right_child(index)

        if left <= self.size() and self.__heap[largest] < self.__heap[left]:
            largest = left
        if right <= self.size() and self.__heap[largest] < self.__heap[right]:
            largest = right

        if largest != index:
            self.__heap[index], self.__heap[largest] = self.__heap[largest], self.__heap[index]
            self.sink(largest)

    def extractMax(self):
        # if self._size == 0:
        #     return "Heap is empty"
        
        max_val = self.__heap[1]
        self.__heap[1] = self.__heap[self.__size]
        #self.__heap[self.size()] = 0
        self.__size -= 1
        self.sink(1)
        return max_val

    def isEmpty(self):
        if self.size() == 0:
            return True
        else:
            return False

    def top(self):
        if self.__heap[1] != None:
            return self.__heap[1]
        else:
            return "Empty Heap"
        
    def sort(self):
        max_result_array = np.zeros(self.size(), dtype = 'int')
        j = self.__size - 1

        while self.isEmpty() == False:
            max_result_array[j] = int(self.extractMax())
            j -= 1

        return max_result_array

    def print_heap(self):
        for value in range(self.__size + 1):
            print(self.__heap[value], end = " ")

Graphs

In [ ]:
#Adjacency Matrix Representation
class Adjacency_Matrix:
    def __init__(self, vertex_num):
        self.matrix = np.zeros((vertex_num, vertex_num), dtype = int)

    def add_edge(self, from_v, to_v, weight = 1):
        self.matrix[from_v][to_v] = weight
        self.matrix[to_v][from_v] = weight #this is not required if I want a DIRECTED graph

    def max_degree_matrix(self):
        max_degree = 0
        v_index = -1
        for vertex in range(len(self.matrix)):
            degree = 0
            for neighbour in range(len(self.matrix)):
                if self.matrix[vertex][neighbour] > 0:
                    degree += 1
            
            if degree > max_degree:
                max_degree = degree
                v_index = vertex

        return f"vertex: {v_index} has max degree: {max_degree}"

    def printer(self):
        return self.matrix

graph_A = Adjacency_Matrix(7)
graph_A.add_edge(0, 2)
graph_A.add_edge(0, 3)
graph_A.add_edge(0, 4)
graph_A.add_edge(0, 5)
graph_A.add_edge(0, 6)
graph_A.add_edge(1, 3)
graph_A.add_edge(1, 4)
graph_A.add_edge(1, 5)
graph_A.add_edge(1, 6)
graph_A.add_edge(2, 4)
graph_A.add_edge(2, 6)
graph_A.add_edge(3, 4)
graph_A.add_edge(3, 5)
graph_A.add_edge(3, 6)
graph_A.add_edge(4, 5)
graph_A.add_edge(4, 6)
graph_A.add_edge(5, 6)

max_degree_op = graph_A.max_degree_matrix()
print(max_degree_op)
print()

print("Adjacency Matrix Representation of the Graph I drew")
graph_A.printer()

In [ ]:
#Adjacency List Representation
class Node:
    def __init__(self, ng, w = 1, next = None):
        self.neighbour = ng
        self.w = w
        self.next = next
    
class Adjacency_List:
    def __init__(self, vertex_num):
        self.vertices = np.array([None] * vertex_num)

    def list_add_edge(self, from_v, to_v, weight = 1):
        new_node = Node(to_v, weight)
        new_node.next = self.vertices[from_v]
        self.vertices[from_v] = new_node
        return
    
    def max_degree_LL(self):
        max_degree = 0
        vertex_index = -1

        for i in range(len(self.vertices)):
              temp = self.vertices[i]
              degree = 0

              while temp != None:
                  degree += 1
                  temp = temp.next

              if degree > max_degree:
                max_degree = degree
                vertex_index = i

        return f"vertex: {vertex_index} has max degree: {max_degree}"
    
    def print_LL(self, head):
        temp = self.vertices[head]
        print(head, end = " == ")
        while temp != None:
                print(temp.neighbour, end = "-->")
                temp = temp.next
    
    def LL_printer(self, vertex_num):
         for i in range(vertex_num):
              self.print_LL(i)
              print()
    
graph_B = Adjacency_List(7)
graph_B.list_add_edge(0, 2)
graph_B.list_add_edge(0, 3)
graph_B.list_add_edge(0, 4)
graph_B.list_add_edge(0, 5)
graph_B.list_add_edge(0, 6)
graph_B.list_add_edge(1, 3)
graph_B.list_add_edge(1, 4)
graph_B.list_add_edge(1, 5)
graph_B.list_add_edge(1, 6)
graph_B.list_add_edge(2, 4)
graph_B.list_add_edge(2, 6)
graph_B.list_add_edge(3, 4)
graph_B.list_add_edge(3, 5)
graph_B.list_add_edge(3, 6)
graph_B.list_add_edge(4, 5)
graph_B.list_add_edge(4, 6)
graph_B.list_add_edge(5, 6)

#this is not required if I want a DIRECTED Graph
graph_B.list_add_edge(2, 0)
graph_B.list_add_edge(3, 0)
graph_B.list_add_edge(4, 0)
graph_B.list_add_edge(5, 0)
graph_B.list_add_edge(6, 0)
graph_B.list_add_edge(3, 1)
graph_B.list_add_edge(4, 1)
graph_B.list_add_edge(5, 1)
graph_B.list_add_edge(6, 1)
graph_B.list_add_edge(4, 2)
graph_B.list_add_edge(6, 2)
graph_B.list_add_edge(4, 3)
graph_B.list_add_edge(5, 3)
graph_B.list_add_edge(6, 3)
graph_B.list_add_edge(5, 4)
graph_B.list_add_edge(6, 4)
graph_B.list_add_edge(6, 5)

max_degree_op_LL = graph_B.max_degree_LL()
print(max_degree_op_LL)
print()

print("Adjacency List Representation of the Graph I drew")
graph_B.LL_printer(7)

Final Prep

Spring'24 Set-A

In [24]:
#Q2
class Node:
    def __init__(self, elem, next=None):
        self.elem = elem
        self.next = next

# Function to build a linked list from a list of elements
def build_linked_list(elements):
    if not elements:
        return None
    head = Node(elements[0])
    current = head
    for elem in elements[1:]:
        current.next = Node(elem)
        current = current.next
    return head

def hash(head, st):
    sum = 0
    temp = head

    while temp != None:
        data = temp.elem

        index = -1
        for i in range(len(st)):
            if st[i] == data:
                index = i
        sum += index
        temp = temp.next

    return sum % 10


# Sample driver code
if __name__ == "__main__":
    # Create a linked list for D → A → T → A
    elements = ['D', 'A', 'T', 'A']
    head = build_linked_list(elements)
    
    # Test string
    st = "SADA"

    # Calculate hash
    hash_value = hash(head, st)

    print(f"Hash value: {hash_value}")


Hash value: 7


In [ ]:
#Q3
class BTNode:
  def __init__(self, elem):
    self.elem = elem
    self.right = None
    self.left = None

def sumoftree(root):
  if root != None:
    return root.elem + sumoftree(root.left) + sumoftree(root.right)
  return 0


def sumTree(root):
  if root == None: return True

  if root.left == None and root.right == None: return True

  if sumoftree(root.left) + sumoftree(root.right) == root.elem:
    return sumTree(root.left) and sumTree(root.right)
  return False

root = BTNode(26)
root.left = BTNode(10)
root.right = BTNode(3)
root.left.left = BTNode(4)
root.left.right = BTNode(6)
root.right.right = BTNode(3)

sumTree(root)

True

In [1]:
import heapq

class MaxHeap:
    def __init__(self):
        self.heap = []  # MaxHeap represented as a negative MinHeap
    
    def MaxInsert(self, val):
        heapq.heappush(self.heap, -val)  # Use negative values for max heap behavior
    
    def MaxDelete(self):
        if len(self.heap) == 0:
            raise IndexError("The MaxHeap is empty.")
        return -heapq.heappop(self.heap)  # Return positive value for max heap behavior

class MinHeap:
    def __init__(self):
        self.heap = []
    
    def MinInsert(self, val):
        heapq.heappush(self.heap, val)  # Standard MinHeap
    
    def MinDelete(self):
        if len(self.heap) == 0:
            raise IndexError("The MinHeap is empty.")
        return heapq.heappop(self.heap)  # Return smallest value
    
def heapSum(arr, k):
    max = MaxHeap()
    min = MinHeap()

    for i in range(len(arr)):
        max.insert(arr[i])
        min.insert(arr[i])

    for i in range(k):
        largest = max.MaxDelete()
        smallest = min.MinDelete()

        sum = largest - smallest

        max.MaxInsert(sum)
        min.MinInsert(sum)


arr = [3, 2, 1, 5, 4]
k = 2
heapSum(arr, k)



Summer'24 Set-A

In [2]:
#Q3
class BTNode:
    def __init__(self, val):
        self.val = val
        self.left = None
        self.right = None

def path_finder(root, key, i):
    if root == None:
        return False
    
    if i >= len(key) or root.val != key[i]:
        return False

    if root.left == None and root.right == None and i == len(key) - 1:
        return True

    return path_finder(root.left, key, i + 1) or path_finder(root.right, key, i + 1)

def is_valid(root, key):
    return path_finder(root, key, 0)

def is_valid1(root, key):
    i = 0
    flag = True

    while root != None:
        i += 1
        if i > len(key) - 1:
            if root.left != None or root.right != None:
                flag = False
            break

        else:
            if root.left.val == key[i]:
                root = root.left
            elif root.right.val == key[i]:
                root = root.right
            else:
                flag = False
                break
    return flag

root = BTNode("C")
root.left = BTNode("S")
root.right = BTNode("R")
root.left.left = BTNode("T")
root.left.right = BTNode("E")
root.right.left = BTNode("M")
root.right.right = BTNode("P")
root.right.right.right = BTNode("D")

print(is_valid(root,"CSE"))
print(is_valid(root,"CRA"))
print(is_valid(root,"CRP"))
print()
print(is_valid1(root,"CSE"))
print(is_valid1(root,"CRA"))
print(is_valid1(root,"CRP"))

True
False
False
True
False

True
False
False


Fall'24 Set-B

In [ ]:
#Q5
def fact_checker(root, compare):
    temp = root

    while temp != None:
        if temp.elem == compare:
            return True
        temp = temp.next

    return False

def is_complete(network):
    count = 0
    for i in range(len(network)):
        count += 1

    checker = np.zeros(count, dtype = int)

    for i in range(len(network)):
        checker[i] = network[i]

    for i in range(len(network)):
        for j in range(len(checker)):
            check = fact_checker(network[i], checker[j])
            if check == False:
                return False
    return True