In [1]:
import pandas as pd
import numpy as np
import pickle
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

career = pd.read_csv('dataset9000.data', header = None)
X = np.array(career.iloc[:, 0:17]) #X is skills
print(X)

y = np.array(career.iloc[:, 17]) #Y is Roles
print(y)

##  attribute to return the column labels of the given Dataframe
career.columns = ["Database Fundamentals","Computer Architecture","Distributed Computing Systems",
"Cyber Security","Networking","Development","Programming Skills","Project Management",
"Computer Forensics Fundamentals","Technical Communication","AI ML","Software Engineering","Business Analysis",
"Communication skills","Data Science","Troubleshooting skills","Graphics Designing","Roles"]


career.dropna(how ='all', inplace = True)
#print("career.dropna(how ='all', inplace = True)",career.dropna(how ='all', inplace = True))

career.head()

## splitting the data into training and test sets
from sklearn.metrics import classification_report
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size = 0.3, random_state = 524)
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics
scores = {}
knn = KNeighborsClassifier(n_neighbors=800)

knn.fit(X_train, y_train)
print('X_train',X_train)
print('y_train',y_train)
y_pred = knn.predict(X_test)
print('y_pred',y_pred)
scores[5] = metrics.accuracy_score(y_test, y_pred)
print('Accuracy=',scores[5]*100)
print(classification_report(y_test,y_pred))

pickle.dump(knn, open('careerlast.pkl','wb'))
print('test file created')




[[9 1 1 ... 1 1 1]
 [9 2 1 ... 1 1 1]
 [9 3 1 ... 1 1 1]
 ...
 [1 1 1 ... 6 6 9]
 [1 1 1 ... 7 7 9]
 [1 1 1 ... 7 5 9]]
['Database Administrator' 'Database Administrator'
 'Database Administrator' ... 'Graphics Designer' 'Graphics Designer'
 'Graphics Designer']
X_train [[6 6 6 ... 6 6 6]
 [2 2 9 ... 2 2 2]
 [3 3 3 ... 3 3 9]
 ...
 [3 3 3 ... 3 3 3]
 [1 1 1 ... 1 1 1]
 [2 9 2 ... 2 6 6]]
y_train ['Project Manager' 'Application Support Engineer' 'Graphics Designer' ...
 'Software Developer' 'AI ML Specialist' 'Hardware Engineer']
y_pred ['API Integration Specialist' 'Hardware Engineer'
 'Customer Service Executive' ... 'Business Analyst' 'Technical Writer'
 'Data Scientist']
Accuracy= 94.73493100944081
                                 precision    recall  f1-score   support

               AI ML Specialist       0.90      0.98      0.94       154
     API Integration Specialist       0.98      0.93      0.95       175
   Application Support Engineer       0.93      0.97      0.95       