In [2]:
import numpy as np

In [3]:
data = [2,3,5,7,8,9]

mean = np.mean(data)
print("The mean is : {}".format(mean))

The mean is : 5.666666666666667


In [9]:
#Mean using random data

data2 = np.random.randint(0,100,14)
print(data2)
mean2 = np.mean(data2)
print("Mean is : {}".format(mean2))

[54 58 38 29 67 22 65 35 27 22 60 99 58 88]
Mean is : 51.57142857142857


In [20]:
#Weighted average

data = np.array([5,4,6,7, 30, 23])
weights = np.array([0.1,0.1,0.1,0.1,0.1, 0.1])

weighted_avg = np.average(data, weights = weights)
print("weighted average is {}:".format(weighted_avg))

weighted average is 12.5:


ModuleNotFoundError: No module named 'scipy'

In [30]:
import sys
!{sys.executable} -m pip install scipy


You should consider upgrading via the 'c:\users\asus\appdata\local\programs\python\python39\python.exe -m pip install --upgrade pip' command.


In [33]:
#Trimmed Mean
#from scipy.stats import trim_mean
data2 = np.random.randint(0,100,10)

#calculate trimmed mean

trimmed_mean_value = trim_mean(data2,proportiontocut= 0.1)
print("The trimmed mean is: ",trimmed_mean_value)


ModuleNotFoundError: No module named 'scipy'

In [ ]:
data3 = np.random.randint(1, 1000,11)

In [51]:
# Trimmed Mean Manually


data_sorted = np.sort(data3)
print(data_sorted)
#To remove 0.1 i.e 10% of 10 which is 1
to_remove =int(np.ceil( 0.1 * len(data_sorted) ))
print("Average before trimmed", np.average(data_sorted))
#print(to_remove)


[ 75  90 164 262 298 358 420 699 781 877 914]
Average before trimmed 448.90909090909093


In [69]:
data_trimmed = data_sorted[int(to_remove): -int(to_remove)]
data_avg = np.average(data_trimmed)
print(data_trimmed)
print("Average after trimmed: ", data_avg)

[164 262 298 358 420 699 781]
Average after trimmed:  426.0


In [60]:
data4 = np.random.randint(1, 10, 50)

In [68]:
#Mode is the dataset or the value with the highest frequency

print("The data is :" ,data4)
#print("The mode is :", np.mode(data4))

unique_nums, frequency = np.unique(data4, return_counts = True)
print("All the unique numbers are: ", unique_nums)
print("The most repeated value is repeated {} times.".format(np.max(frequency)))
max_freq_index= np.argmax(frequency)
print("That value is:", unique_nums[max_freq_index])
#print(max_freq_index)

The data is : [7 6 7 3 8 9 6 8 3 6 7 1 7 6 6 1 7 4 1 8 7 8 4 1 4 5 7 6 1 1 8 9 9 5 6 6 4
 6 4 8 8 2 8 4 8 1 8 5 3 4]
All the unique numbers are:  [1 2 3 4 5 6 7 8 9]
The most repeated value is repeated 10 times.
That value is: 8


In [75]:
data5 = np.random.randint(1, 100, 10)

In [82]:
#Standard Deviation
print(data5)
datalen = len(data5)
print("The length of data is:", datalen)
mean5 = np.mean(data5)
print("The mean is :", mean5)
sum = 0
for data in data5:
    sum += (data-mean5)**2
std_dev = np.sqrt(sum/datalen)
print("The standard deviation is: ", std_dev)

[95 58 34 85  8 40 39 69 78 74]
The length of data is: 10
The mean is : 58.0
The standard deviation is:  25.760434778939583


In [81]:
print("The standatad deviation by numpy is : ", np.std(data5))

The standatad deviation by numpy is :  25.760434778939583


In [101]:
#Quartiles

data5_sorted = np.sort(data5) 
print("The sorted data is : ", data5_sorted)
q1_index = int(np.floor((datalen+1)/4))
print("Index where q1 lies is : " , q1_index)
q1 = data5_sorted[int(q1_index)]
print("The first quartile value is : ", q1)

q3_index = np.floor(3*(datalen+1)/4)
print("Index where q3 lies is :", int(q3_index))
q3 = data5_sorted[int(q3_index)]
print("The third quartile value is : ", q3)

The sorted data is :  [ 8 34 39 40 58 69 74 78 85 95]
Index where q1 lies is :  2
The first quartile value is :  39
Index where q3 lies is : 8
The third quartile value is :  85


ModuleNotFoundError: No module named 'matplotlib'

In [103]:
!pip install matplotlib

     ---------------------------------------- 7.9/7.9 MB 5.6 MB/s eta 0:00:00
     ---------------------------------------- 2.6/2.6 MB 7.1 MB/s eta 0:00:00
     ---------------------------------------- 2.2/2.2 MB 7.0 MB/s eta 0:00:00
     ---------------------------------------- 56.2/56.2 KB ? eta 0:00:00
     -------------------------------------- 182.8/182.8 KB 5.6 MB/s eta 0:00:00


You should consider upgrading via the 'C:\users\asus\appdata\local\programs\python\python39\python.exe -m pip install --upgrade pip' command.


In [ ]:
import matplotlib.pyplot as plt

ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.9 from "c:\users\asus\appdata\local\programs\python\python39\python.exe"
  * The NumPy version is: "1.22.3"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: DLL load failed while importing _multiarray_umath: The specified module could not be found.
