In [16]:
a = [1, 2, 3, 4, "list", "python", 55, 67]
print(a[0:4])
print(a[4:6])
print(a[1:])
print(a[:6])
print(a[1:6:2])
print(a[-1])

a.clear()
print(a)

a.insert(0, 1)
a.insert(1, 2)
a.insert(2, 3)
a.insert(3, 4)
a.insert(4, 9)
a.insert(5, 8)
a.insert(6, 7)
print(a)

a.remove(2)

print(a)

a.pop(1)
print(a)

a.append(2)
print(a)

a.reverse()
print(a)

a.sort()
print(a)

a.sort(reverse=True)
print(a)

a.pop()
print(a)

a.extend([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(a)

print(min(a))
print(max(a))
print(sum(a))
print(len(a))
print(a.count(2))
print(a.index(2))
# 1 is the element, 1 is the starting index, 10 is the ending index
print(a.index(2, 5, 10))


[1, 2, 3, 4]
['list', 'python']
[2, 3, 4, 'list', 'python', 55, 67]
[1, 2, 3, 4, 'list', 'python']
[2, 4, 'python']
67
[]
[1, 2, 3, 4, 9, 8, 7]
[1, 3, 4, 9, 8, 7]
[1, 4, 9, 8, 7]
[1, 4, 9, 8, 7, 2]
[2, 7, 8, 9, 4, 1]
[1, 2, 4, 7, 8, 9]
[9, 8, 7, 4, 2, 1]
[9, 8, 7, 4, 2]
[9, 8, 7, 4, 2, 1, 2, 3, 4, 5, 6, 7, 8, 9]
1
9
75
14
2
4
6


In [17]:
tup = (2, 5, 6, 7, 5)
print(tup)

print(tup[1])

print(tup.count(5))

# elements cannot be added to a tuple but two tuples can be concatenated

print(tup)

tup1 = (1, 2, 3, 4, 5)

tup3 = tup+tup1
print(tup3)


(2, 5, 6, 7, 5)
5
2
(2, 5, 6, 7, 5)
(2, 5, 6, 7, 5, 1, 2, 3, 4, 5)


In [18]:
data = {1: 'Navin', 2: 'Kiran', 3: 'Harsh', 4: 'Rahul'}
print(data)

print(data[1])

print(data.get(1))

print(data.get(5))

print(data.get(5, 'Not Found'))

print(data.keys())

print(data.values())

print(data.items())

a = [1, 2, 3, 4, 5]
b = ["navin", "kiran", "harsh", "rahul", "kirrr"]
c = dict(zip(a, b))

print(c)

c[3] = [1, 2, 3, 4, 5]

print(c)


c[3] = {1: 'Navin', 2: 'Kiran', 3: 'Harsh', 4: 'Rahul'}

print(c)


a = {'rahul': 'samsung', 'harsh': 'iphone', 'kiran': 'realme'}
print(a)


{1: 'Navin', 2: 'Kiran', 3: 'Harsh', 4: 'Rahul'}
Navin
Navin
None
Not Found
dict_keys([1, 2, 3, 4])
dict_values(['Navin', 'Kiran', 'Harsh', 'Rahul'])
dict_items([(1, 'Navin'), (2, 'Kiran'), (3, 'Harsh'), (4, 'Rahul')])
{1: 'navin', 2: 'kiran', 3: 'harsh', 4: 'rahul', 5: 'kirrr'}
{1: 'navin', 2: 'kiran', 3: [1, 2, 3, 4, 5], 4: 'rahul', 5: 'kirrr'}
{1: 'navin', 2: 'kiran', 3: {1: 'Navin', 2: 'Kiran', 3: 'Harsh', 4: 'Rahul'}, 4: 'rahul', 5: 'kirrr'}
{'rahul': 'samsung', 'harsh': 'iphone', 'kiran': 'realme'}


In [19]:
a = 5
print(id(a))

b = 5
print(id(b))

c = a
print(id(c))

# if the number or a string is same then the id will be same
# if data is not tagged to any variable then it will be deleted by garbage collector


140711921640360
140711921640360
140711921640360


In [20]:
num = 2.5
print(type(num))

num = 2+3j
print(type(num))

num = 2
print(type(num))

num = True
print(type(num))

num = 6.7
print(type(num))

a = int(num)
print(a)
print(type(a))

c = complex(num, a)
print(c)
print(type(c))

a = (1, 2)
print(type(a))

a = [1, 2]
print(type(a))

a = {1, 2}
print(type(a))

a = {1: 2}
print(type(a))

a = "string"
print(type(a))

print(list(range(10)))
print(list(range(1, 10)))
print(list(range(1, 10, 2)))


<class 'float'>
<class 'complex'>
<class 'int'>
<class 'bool'>
<class 'float'>
6
<class 'int'>
(6.7+6j)
<class 'complex'>
<class 'tuple'>
<class 'list'>
<class 'set'>
<class 'dict'>
<class 'str'>
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[1, 2, 3, 4, 5, 6, 7, 8, 9]
[1, 3, 5, 7, 9]


In [21]:
a = 5
b = 9
if (a < b and a == 5):
    print("a is greater than b")
if (a > b or a == 5):
    print("a is greater than b")
if (not (a > b or a == 5)):
    print("a is greater than b")


a is greater than b
a is greater than b


In [22]:
a = 5
print(bin(a))
print(0b10111)

print(hex(a))
print(0x10111)

print(oct(a))
print(0o10111)

print(0b10111 + 0x10111 + 0o10111)
print(0b10111 + 0x10111 + 0o10111 + 5)


0b101
23
0x5
65809
0o5
4169
70001
70006


In [23]:
a = 5
b = 7

temp = a
a = b
b = temp

print("a: {} , b: {}".format(a, b))

a, b = b, a

print("a: {} , b: {}".format(a, b))

a = a+b
b = a-b
a = a-b

print("a: {} , b: {}".format(a, b))

a = a ^ b
b = a ^ b
a = a ^ b

print("a: {} , b: {}".format(a, b))


a: 7 , b: 5
a: 5 , b: 7
a: 7 , b: 5
a: 5 , b: 7


In [24]:
a = 3
print(~a)

b = 5
print(a & b)
print(a | b)
print(a ^ b)
print(a >> 2)  # right shift
print(a << 2)  # left shift


-4
1
7
6
0
12


In [25]:
import math as m

print(m.sqrt(25))
print(m.floor(2.9))
print(m.ceil(2.9))
print(m.pi)
print(m.e)
print(m.sin(m.radians(90)))
print(m.cos(m.radians(90)))
print(m.tan(m.radians(90)))
print(m.log(10, m.e))
print(m.log10(10))
print(m.log2(10))
print(m.pow(2, 3))
print(m.factorial(5))
print(m.gcd(2, 4))
print(m.degrees(90))
print(m.radians(90))
print(m.inf)
print(m.nan)
print(m.floor(2.9))
print(m.fabs(-2.9))
print(m.fmod(2, 3))  # remainder
print(m.copysign(2, -3))
print(m.isfinite(2))
print(m.isinf(2))
print(m.isnan(2))
print(m.modf(2.9))
print(m.frexp(2.9))
print(m.ldexp(2.9, 2))
print(m.exp(2.9))
print(m.expm1(2.9))
print(m.hypot(2, 3))
print(m.acos(0.5))
print(m.asin(0.5))


5.0
2
3
3.141592653589793
2.718281828459045
1.0
6.123233995736766e-17
1.633123935319537e+16
2.302585092994046
1.0
3.321928094887362
8.0
120
2
5156.620156177409
1.5707963267948966
inf
nan
2
2.9
2.0
-2.0
True
False
False
(0.8999999999999999, 2.0)
(0.725, 2)
11.6
18.17414536944306
17.17414536944306
3.605551275463989
1.0471975511965979
0.5235987755982989


In [26]:
print(eval(input("enter an expression:")))


17


In [27]:
a = "youtube this is cool man"
print(a[0:6])
print(a[6:12])
print(a[1:])
print(a[:6])


youtub
e this
outube this is cool man
youtub


In [28]:
a = {6, 7, 4, 3, 5, 8, 3}
print(a)


{3, 4, 5, 6, 7, 8}


In [29]:
a = 5
if a == 5:
    print("a is equal to 5")
elif a == 6:
    print("a is equal to 6")
else:
    print("a is not equal to 5 or 6")


for i in range(1, 10, 2):
    print(i, end=" ")

i = 0
print()

while i < 10:
    print(i, end=" ")
    i += 1

print()

for i in range(10):
    if i == 5:
        print("this is 5", end=" ")
        continue
        print("this is cool")
    elif i == 6:
        pass
    elif i == 7:
        print("this is 7", end=" ")
        pass
        print("this is cool", end=" ")
    elif i == 8:
        print("this is 8 now its time to end the loop", end=" ")
        break
    else:
        print(i, end=" ")

a = 5
b = int(a)
c = float(a)

print()


a is equal to 5
1 3 5 7 9 
0 1 2 3 4 5 6 7 8 9 
0 1 2 3 4 this is 5 this is 7 this is cool this is 8 now its time to end the loop 


In [30]:
import sys
i = 0
print(sys.getrecursionlimit())
sys.setrecursionlimit(2000)


def printh():
    global i
    i += 1
    print("Hello {}", i)
    printh()


printh()


2000
Hello {} 1
Hello {} 2
Hello {} 3
Hello {} 4
Hello {} 5
Hello {} 6
Hello {} 7
Hello {} 8
Hello {} 9
Hello {} 10
Hello {} 11
Hello {} 12
Hello {} 13
Hello {} 14
Hello {} 15
Hello {} 16
Hello {} 17
Hello {} 18
Hello {} 19
Hello {} 20
Hello {} 21
Hello {} 22
Hello {} 23
Hello {} 24
Hello {} 25
Hello {} 26
Hello {} 27
Hello {} 28
Hello {} 29
Hello {} 30
Hello {} 31
Hello {} 32
Hello {} 33
Hello {} 34
Hello {} 35
Hello {} 36
Hello {} 37
Hello {} 38
Hello {} 39
Hello {} 40
Hello {} 41
Hello {} 42
Hello {} 43
Hello {} 44
Hello {} 45
Hello {} 46
Hello {} 47
Hello {} 48
Hello {} 49
Hello {} 50
Hello {} 51
Hello {} 52
Hello {} 53
Hello {} 54
Hello {} 55
Hello {} 56
Hello {} 57
Hello {} 58
Hello {} 59
Hello {} 60
Hello {} 61
Hello {} 62
Hello {} 63
Hello {} 64
Hello {} 65
Hello {} 66
Hello {} 67
Hello {} 68
Hello {} 69
Hello {} 70
Hello {} 71
Hello {} 72
Hello {} 73
Hello {} 74
Hello {} 75
Hello {} 76
Hello {} 77
Hello {} 78
Hello {} 79
Hello {} 80
Hello {} 81
Hello {} 82
Hello {} 83
Hello {}

RecursionError: maximum recursion depth exceeded while calling a Python object

In [32]:
a = 10
b = 6
c = 9


def functionn():
    b = 8
    print(b)
    global a
    a = 15
    b = 11


functionn()
print(a)
print(b)
print(c)


8
15
6
9


In [33]:
def change(a):
    x = a
    print("id of x", id(x))
    x = 15
    print("id of x", id(x))


a = 10
print("id of a", id(a))
change(a)
print(a)


def listchange(a):
    print("id of a", id(a))
    a[1] = 15
    print("id of a", id(a))


a = [10, 20, 30]
print("id of a", id(a))
listchange(a)
print(a)


id of a 140711921640520
id of x 140711921640520
id of x 140711921640680
10
id of a 2892133138624
id of a 2892133138624
id of a 2892133138624
[10, 15, 30]


In [34]:
a = ['navin', 'kiran', 'harsh', 'navin']
b = ['python', 'java', 'c', 'python']

c = zip(a, b)
print(c)


c = list(zip(a, b))
print(c)

c = tuple(zip(a, b))
print(c)

c = set(zip(a, b))
print(c)

c = dict(zip(a, b))
print(c)


[('navin', 'python'), ('kiran', 'java'), ('harsh', 'c'), ('navin', 'python')]
(('navin', 'python'), ('kiran', 'java'), ('harsh', 'c'), ('navin', 'python'))
{('navin', 'python'), ('harsh', 'c'), ('kiran', 'java')}
{'navin': 'python', 'kiran': 'java', 'harsh': 'c'}


In [38]:
import array as arr
from numpy import *  # from numpy import *
vals = arr.array('i', [1, 2, 3, 4, 5, 6])
print(vals)
vals.reverse()
print(vals)
print(vals.buffer_info())  # (address, size)
print(vals.typecode)
print(vals[0])

a = linspace(0, 15, 16)
print(a)
a = logspace(0, 15, 16)
print(a)
a = 2.5432234
print(a)
print('%.2f' % a)

arr = ones(5, int)
print(arr)

a = arr+5
print(a)

print(a+arr)

print(sin(a))
print(cos(a))
print(log(a))
print(sqrt(a))

print(concatenate([a, arr]))

# shallow copy and deep copy

# shallow copy
print("ARRAY", arr)
arr1 = arr.view()
arr2 = arr.copy()
arr[1] = 7


print("shadow copy", arr1)
print("deep copy", arr2)


arr = zeros(5, int)
print(arr)

# multi dimensional array
arr = array([[1, 2, 3], [4, 5, 6]])
print(arr)

print(arr.dtype)
print(arr.ndim)
print(arr.shape)
print(arr.size)

arr = arr.flatten()
print(arr)

arr = arr.reshape(3, 2)
print(arr)

m = matrix(arr)
print(m)

m = matrix('1 2 3; 4 5 6; 7 8 9')
print(m)

print(diagonal(m))

m1 = matrix('1 2 3; 4 5 6; 7 8 9')
m2 = matrix('1 2 3; 4 5 6; 7 8 9')
m3 = m1+m2
print(m3)

m3 = m1*m2
print(m3)

m3 = m1-m2
print(m3)

m3 = m1/m2
print(m3)

m3 = m1 % m2
print(m3)


a = array('i', [])
n = int(input("Enter the length of the array: "))


print(a)


array('i', [1, 2, 3, 4, 5, 6])
array('i', [6, 5, 4, 3, 2, 1])
(2892374253296, 6)
i
6
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15.]
[1.e+00 1.e+01 1.e+02 1.e+03 1.e+04 1.e+05 1.e+06 1.e+07 1.e+08 1.e+09
 1.e+10 1.e+11 1.e+12 1.e+13 1.e+14 1.e+15]
2.5432234
2.54
[1 1 1 1 1]
[6 6 6 6 6]
[7 7 7 7 7]
[-0.2794155 -0.2794155 -0.2794155 -0.2794155 -0.2794155]
[0.96017029 0.96017029 0.96017029 0.96017029 0.96017029]
[1.79175947 1.79175947 1.79175947 1.79175947 1.79175947]
[2.44948974 2.44948974 2.44948974 2.44948974 2.44948974]
[6 6 6 6 6 1 1 1 1 1]
ARRAY [1 1 1 1 1]
shadow copy [1 7 1 1 1]
deep copy [1 1 1 1 1]
[0 0 0 0 0]
[[1 2 3]
 [4 5 6]]
int32
2
(2, 3)
6
[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [3 4]
 [5 6]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 5 9]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
()


In [ ]:
import sys

x = int(sys.argv[1])
y = int(sys.argv[2])
print(x+y)


In [40]:
def farg(*args):
    for i in args:
        print(i)


def fkwarg(**kwargs):
    for key, value in kwargs.items():
        print("{}:{}".format(key, value))


def fargkwarg(*args, **kwargs):
    for i in args:
        print(i)
    for key, value in kwargs.items():
        print("{}:{}".format(key, value))


farg(1, 2, 3, 4, 5)
fkwarg(name="Navin", age=28, mob=1234567890)
fargkwarg(1, 2, 3, 4, 5, name="Navin", age=28, mob=1234567890)


1
2
3
4
5
name:Navin
age:28
mob:1234567890
1
2
3
4
5
name:Navin
age:28
mob:1234567890


In [41]:
print(list(filter(lambda x: any(x == p*p for p in range(2, x)),
      [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 25])))


[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 25]


In [42]:
def div(a, b):
    return a/b


def smart_div(func):
    def inner(a, b):
        if a < b:
            a, b = b, a
        return func(a, b)
    return inner


div = smart_div(div)
print(div(2, 4))


2.0


In [43]:
#inside the my modole.py file

def even(a):
    return list(filter(lambda x: x % 2 == 0, a))


def odd(a):
    return list(filter(lambda x: x % 2 != 0, a))


def perfectsquare(a):
    return list(filter(lambda x: any(x == p*p for p in range(2, x)), a))


In [44]:
from my_module import *

a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 25]
print(even(a))
print(odd(a))
print(perfectsquare(a))


[2, 4, 6, 8, 10, 12, 14, 16]
[1, 3, 5, 7, 9, 11, 13, 15, 25]
[4, 9, 16, 25]


In [45]:
#code inside the __main__ folder and this is the module.py file

def greet():
    print("hello")
    print("good morning")
    print("this is a cool stuff")


if __name__ == "__main__":
    greet()


hello
good morning
this is a cool stuff


In [46]:
from module import *

print("this is the code.py file")


this is the code.py file


In [47]:
class printing():

    def config(self):
        print("I am printing")


ob = printing()
ob.config()
printing.config(ob)


class Computer:

    fans = 2

    def __init__(self, cpu, ram):
        self.cpu = cpu
        self.ram = ram

    def config(self):
        print("Config is ", self.cpu, self.ram)

    def compare(self, other):
        if self.cpu == other.cpu and self.ram == other.ram:
            return True
        else:
            return False


com1 = Computer('i5', 16)
com2 = Computer('Ryzen 3', 8)


com1.config()
com2.config()

com1.cpu = 'i7'
com1.config()


if com1.compare(com2):
    print("They are same")
else:
    print("They are different")


print(com1.fans, com2.fans)

Computer.fans = 3

print(com1.fans, com2.fans)

com1.fans = 4

print(com1.fans, com2.fans)


I am printing
I am printing
Config is  i5 16
Config is  Ryzen 3 8
Config is  i7 16
They are different
2 2
3 3
4 3


In [48]:
class students:

    school = "ABC School"

    def __init__(self, m1, m2, m3):
        self.m1 = m1
        self.m2 = m2
        self.m3 = m3

    def avg(self):
        return (self.m1 + self.m2 + self.m3) / 3

    @classmethod
    def getSchool(cls):   # cls is class variable
        cls.school = "XYZ School"
        return cls.school

    @staticmethod
    def info():
        print("This is students class... in abc module")


s1 = students(34, 67, 32)
s2 = students(89, 32, 12)

print(s1.avg())
print(s2.avg())
print(s1.school)

print(students.getSchool())

print(s1.school)

students.info()
s1.info()


44.333333333333336
44.333333333333336
ABC School
XYZ School
XYZ School
This is students class... in abc module
This is students class... in abc module


In [49]:
class students:

    def __init__(self, name, rollno):
        self.name = name
        self.rollno = rollno
        self.lap = self.laptop()

    def show(self):
        print(self.name, self.rollno)
        self.lap.show()

    class laptop:

        def __init__(self):
            self.brand = 'HP'
            self.cpu = 'i5'
            self.ram = 8

        def show(self):
            print(self.brand, self.cpu, self.ram)


s1 = students('Rahul', 2)
s2 = students('Rohit', 3)

s1.show()

print(s1.lap.brand, s1.lap.cpu, s1.lap.ram, s1.name, s1.rollno)


Rahul 2
HP i5 8
HP i5 8 Rahul 2


In [50]:
class a:

    def a(self):
        print("This is a")

    def b(self):
        print("This is b")


class b(a):

    def c(self):
        print("This is c")

    def d(self):
        print("This is d")


class c(b):

    def e(self):
        print("This is e")

    def f(self):
        print("This is f")


ob = c()
ob.a()
ob.b()
ob.c()
ob.d()
ob.e()
ob.f()


This is a
This is b
This is c
This is d
This is e
This is f


In [51]:
class a:

    def __init__(self):
        print("in a init")

    def a(self):
        print("This is a")


class b(a):

    def __init__(self):
        print("in b init")

    def b(self):
        print("This is b")


class c(b):

    def __init__(self):
        super().__init__()
        print("in c init")

    def c(self):
        print("This is c")


ob = c()


in b init
in c init


In [52]:
class a:

    def __init__(self):
        print("in a init")

    def b(self):
        print("This is b")


class b:

    def __init__(self):
        print("in b init")

    def b(self):
        print("This is b")


class c(a, b):

    def __init__(self):
        super().__init__()
        print("in c init")

    def c(self):
        print("This is c")


ob = c()


in a init
in c init


In [53]:
class vscode:

    def execute(self):
        print("Compiling")
        print("Running")


class laptop:

    def code(self, ide):
        ide.execute()


ide = vscode()
lap = laptop()
lap.code(ide)


Compiling
Running


In [54]:
# not supported in python but we can do it by using default arguments

class Student:

    def __init__(self, m1, m2):
        self.m1 = m1
        self.m2 = m2

    def sum(self, a=None, b=None, c=None):

        s = 0

        if a != None and b != None and c != None:
            s = a+b+c
        elif a != None and b != None:
            s = a+b
        elif a != None:
            s = a
        else:
            s = 0

        return s


s1 = Student(58, 69)

print(s1.sum(5, 9, 6))
print(s1.sum(5, 9))
print(s1.sum(5))
print(s1.sum())


20
14
5
0


In [56]:
class a:
    def show(self):
        print("in a show")


class b:
    def show(self):
        print("in b show")


class c(a, b):
    pass


ob = c()
ob.show()


class d:
    def show(self):
        print("in d show")


class e(d):

    def show(self):
        print("in e show")


ob = e()
ob.show()


in a show
in e show


In [57]:
from abc import ABC, abstractmethod


class AbstractClassExample(ABC):
    def __init__(self, value):
        self.value = value
        super().__init__()

    @abstractmethod
    def do_something(self):
        pass


class DoAdd42(AbstractClassExample):
    def do_something(self):
        return self.value + 42


class DoMul42(AbstractClassExample):
    def do_something(self):
        return self.value * 42


# x = AbstractClassExample(10)
# x.do_something()
x = DoAdd42(10)
y = DoMul42(10)
print(x.do_something())
print(y.do_something())


52
420


In [58]:
nums = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

a = iter(nums)

print(a.__next__())
print(a.__next__())
print(a.__next__())
print(a.__next__())


class syed:

    def move(self, a):
        a = iter(a)
        return a.__next__()

    def loop(self, array, first, last):
        if first <= last:
            print(array[first])
            first += 1
            self.loop(array, first, last)


print("inside a class work")
ob = syed()
print(ob.move(nums))

ob.loop(nums, 0, 9)


1
2
3
4
inside a class work
1
1
2
3
4
5
6
7
8
9
10


In [59]:
a = 5
b = 0

try:
    print(a/b)
except Exception as e:
    print("you can't divide a number by zero and the error is : ", e)

finally:
    print("resource closed")


try:
    a = int(input("enter a number"))

except Exception as e:
    print("invalid input and the error is : ", e)


you can't divide a number by zero and the error is :  division by zero
resource closed
invalid input and the error is :  invalid literal for int() with base 10: 'a'


In [60]:
f = open("data.txt", "r")
# even here in case of read there is a pointer which keeps moving line by line
print(f.read())
print("lets explore something different")
f.close()
f = open("data.txt", "r")
print(f.readline())
print(f.readline())
print(f.readline())

print(f.readline(4))
f.close()

print("lets explore something different\n")

f = open("data.txt", "w")
f.write("this is a new line\n this is the second line\n this is the third line\n this is the fourth line\n")
f.close()

print("lets explore something different\n")

f = open("data.txt", "r")
print(f.read())
f.close()

print("lets explore something different\n")

f = open("data.txt", "a")
f.write("this is the fifth line\n")
f.close()

print("lets explore something different\n")

f = open("data.txt", "r")
print(f.read())
f.close()

# print("lets explore something different\n")


this is a new line
 this is the second line
 this is the third line
 this is the fourth line
this is the fifth line

lets explore something different
this is a new line

 this is the second line

 this is the third line

 thi
lets explore something different

lets explore something different

this is a new line
 this is the second line
 this is the third line
 this is the fourth line

lets explore something different

lets explore something different

this is a new line
 this is the second line
 this is the third line
 this is the fourth line
this is the fifth line



In [61]:
def topten():
    n = 1
    while n <= 10:
        sq = n * n
        yield sq
        n += 1


values = topten()
# to check if values is a iterator or not

if hasattr(values, '__iter__'):
    print("yes it is a iterator")

for i in topten():
    print(i)

    # or

for i in values:
    print(i)


def moveon():

    yield 2
    yield 3
    yield 4
    yield 5


print("move on")
for i in moveon():
    print(i)


yes it is a iterator
1
4
9
16
25
36
49
64
81
100
1
4
9
16
25
36
49
64
81
100
move on
2
3
4
5


In [62]:
class student:

    def marks(self, m1, m2):
        self.m1 = m1
        self.m2 = m2

    def __add__(self, other):
        m1 = self.m1 + other.m1
        m2 = self.m2 + other.m2
        s3 = student()
        s3.marks(m1, m2)
        return s3

    def __gt__(self, other):
        r1 = self.m1 + self.m2
        r2 = other.m1 + other.m2
        if r1 > r2:
            return True
        else:
            return False

    def __str__(self):
        return "{} {}".format(self.m1, self.m2)


a = student()
b = student()
a.marks(10, 20)
b.marks(20, 30)

c = a+b
print(c)
print(c.m1)
print(c.m2)

if a > b:
    print("a wins")
else:
    print("b wins")


print(c)


30 50
30
50
b wins
30 50


In [ ]:
# compile time error
# run time error
# logical error


In [63]:
from threading import *
from time import sleep


class wow1():

    def print(self):
        for i in range(100):
            print("wow1")
            sleep(0.1)


class wow2():

    def print(self):
        for i in range(100):
            print("wow2")
            sleep(0.1)


ob1 = wow1()
ob2 = wow2()

t1 = Thread(target=ob1.print)
t2 = Thread(target=ob2.print)

t1.start()
sleep(0.05)
t2.start()

t1.join()
t2.join()

print("bye")


wow1
wow2
wow1
wow2
wow1
wow2
wow1
wow2
wow1
wow2
wow1
wow2
wow1
wow2
wow1
wow2
wow1
wow2
wow1
wow2
wow1
wow2
wow1
wow2
wow1
wow2
wow1
wow2
wow1
wow2
wow1
wow2
wow1
wow2
wow1
wow2
wow1
wow2
wow1
wow2
wow1
wow2
wow1
wow2
wow1
wow2
wow1
wow2
wow1
wow2
wow1
wow2
wow1
wow2
wow1
wow2
wow1
wow2
wow1
wow2
wow1
wow2
wow1
wow2
wow1
wow2
wow1
wow2
wow1
wow2
wow1
wow2
wow1
wow2
wow1
wow2
wow1
wow2
wow1
wow2
wow1
wow2
wow1
wow2
wow1
wow2
wow1
wow2
wow1
wow2
wow1
wow2
wow1
wow2
wow1
wow2
wow1
wow2
wow1
wow2
wow1
wow2
wow1
wow2
wow1
wow2
wow1
wow2
wow1
wow2
wow1
wow2
wow1
wow2
wow1
wow2
wow1
wow2
wow1
wow2
wow1
wow2
wow1
wow2
wow1
wow2
wow1
wow2
wow1
wow2
wow1
wow2
wow1
wow2
wow1
wow2
wow1
wow2
wow1
wow2
wow1
wow2
wow1
wow2
wow1
wow2
wow1
wow2
wow1
wow2
wow1
wow2
wow1
wow2
wow1
wow2
wow1
wow2
wow1
wow2
wow1
wow2
wow1
wow2
wow1
wow2
wow1
wow2
wow1
wow2
wow1
wow2
wow1
wow2
wow1
wow2
wow1
wow2
wow1
wow2
wow1
wow2
wow1
wow2
wow1
wow2
wow1
wow2
wow1
wow2
wow1
wow2
wow1
wow2
wow1
wow2
wow1
wow2
wow1
wow2


In [64]:

a = 10
b = 20
c = 30
print(lambda a, b, c: a + b + c)


<function <lambda> at 0x000002A16EF47E20>
