# Numpy -  večdimenzionalna polja in ostala ekipa

<h2>Uvod</h2>

Knjižnica `numpy` je pogosto uporabljana za numerično računanje v jeziku Python. Vsebuje učinkovite implementacije podatkovnih struktur kot so vektorji, matrike in polja. Večina računsko zahtevnih operacij je implementirana v nižje nivojskih jezikih (Fortran, C).

Začnimo z uvozom knjižnice:

In [93]:
from numpy import *

Vse podatkovne strukture izhajajo iz istega podatkovnega tipa, polje oz. `array`.


## Polja

Polja lahko ustvarimo na različne načine:
* s pretvorbo Pythonovih seznamov ali terk,
* z uporabo funkcij, ki ustvarijo polja kot so `arange`, `linspace`, itd.,
* z branjem podatkov iz datotek.

### Od seznamov do polj

Konstruktor uporabimo neposredno tako, da mu podamo seznam.

In [94]:
# vektor; eno-dimenzionalna podatkovna struktura
v = array([1, 2, 3, 4])

v

array([1, 2, 3, 4])

In [95]:
# matrika; dvo-dimenzionalna struktura, ustvarjena iz "seznama seznamov"
M = array([[1, 2], [3, 4]])

M

array([[1, 2],
       [3, 4]])

Ne glede na obliko sta `v` in `M` objekta tipa `ndarray`.

In [96]:
type(v), type(M)

(numpy.ndarray, numpy.ndarray)

Razlika je seveda v njunih dimenzijah. `v` je vektor s štirimi elementi, `M` pa `2 x 2` matrika.

In [97]:
v.shape

(4,)

In [98]:
M.shape

(2, 2)

Podobno lahko dobimo število elementov v celotnem seznamu.

In [99]:
M.size

4

<font color="green"><b>Naredi sam/-a.</b></font> Nič nas ne omejuje, da sestavimo polja poljubnih dimenzij. Poizkusi sestaviti seznam-seznamov-seznamov(-seznamov, ...)
in preveri, kakšne so njegove dimenzije!

In [100]:
# Sestavi poljubno-dimenzionalne strukture 
# X = 

Struktura  `numpy.ndarray` še vedno izgleda kot seznam-seznamov(-seznamov, ...). V čem je razlika?

Nekaj hitrih dejstev:

* Pythonovi seznami lahko vsebujejo poljuben tip objektov, ki se znotraj seznama lahko tudi razlikujejo (dinamično tipiziranje). Ne podpirajo matematičnih operacij, kot so matrično množenje. Implementacija takih opracij nad seznamom bi bila zaradi dinamičnega tipiziranja zelo neučinkovita.
* Polja so **statično tipizirana** in **homogena**. Podatkovni tip elementov je določen ob nastanku.
* Posledično po polja pomnilniško učinkovita, saj zasedajo zvezen prostor v pomnilniku.

Ugotovimo, kakšnega tipa so elementi v trenutnem polju:

In [101]:
M.dtype

dtype('int64')

Vstavljanje podatkov poljubnih tipov v polje lahko vodi do težav. Poizkusi.

In [102]:
M[0,0] = "hello"

ValueError: invalid literal for int() with base 10: 'hello'

Nastavimo tpodatkovni tip ob ustvarjanju polja, npr. kompleksna števila ...

In [ ]:
M = array([[1, 2, 3], [1, 4, 9]], dtype=complex)

M

... ali pa med izvanjanjem spremenimo tip.

In [ ]:
M = M.astype(float)
M

Uporabni podatkovni tipi: `int`, `float`, `complex`, `bool`, `object`, 

ter eksplicitno podane velikosti v bitih: `int64`, `int16`, `float128`, `complex128`.

## Uporaba polj

<p>Preden si ogledamo ostale načine ustvarjanja polja, si oglejmo njihovo uporabo.</p>

### Naslavljanje

Elemente naslavljamo z uporabo oglatih oklepajev, podobno kot pri seznamih.

In [ ]:
# v je vektor; naslavljamo ga po njegovi edini dimenziji
v[0]

In [ ]:
# matriko M naslavljamo z dvema podatkoma - naslov je sedaj terka 
M[1,1]

Naslavljanje po eni dimenziji vrne najprej vrstice.

In [ ]:
M[1]

Z uporabo `:` povemo, da bi radi vse elemente v pripadajoči dimenziji. Pomisli, kako bi dostop do celotnega prvega stolpca implementirali s seznami. Da, kar nekaj `for` zank. 

In [ ]:
M[1,:] # Vrstica

In [ ]:
M[:,1] #  Stolpec, precej enostavno.

Posamezne elemente spreminjamo s prireditvenimi stavki ...

In [ ]:
M[0,0] = 9

In [ ]:
M

In [ ]:
# ... ali pa nastavimo elemente po celotni dimenziji.
M[1,:] = 0
M[:,2] = -1

In [ ]:
M

### Rezanje

Rezanje naslovov je pogost koncept. Poljubno pod-polje dobimo na način `M[od:do:korak]`:

In [ ]:
A = array([1,2,3,4,5])
A

In [ ]:
A[1:3]

... kar nam omogoča tudi spreminjanje pod-polj

In [ ]:
A[1:3] = [-2,-3]

A

Katerikoli od parametrov rezanja je lahko tudi izpuščen.

In [103]:
A[::] # Privzete vrednosti parametrov od:do:korak.

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

In [ ]:
A[::2] # korak velikosti 2

In [ ]:
A[:3] # prvi trije elementi

In [ ]:
A[3:] # elementi od tretjega naprej

Negativni naslovi se nanašajo na <i>konec</i> polja:

In [ ]:
A = array([1,2,3,4,5])

In [ ]:
A[-1]

In [ ]:
A[-3:] # zadnji trije elementi

Rezanje deluje tudi pri več dimenzionalnih poljih.

In [ ]:
A = array([[n+m*10 for n in range(5)] for m in range(5)])

A

In [ ]:
# pod-polje izvirnega polja A
A[1:4, 1:4]

In [ ]:
# elemente lahko preskakujemo
A[::2, ::2]

### Naslavljanje polja s pomočjo druge strukture

Polje naslavljamo tudi s pomočjo drugih polj ali seznamov (ang. <i>Fancy indexing</i>).

In [ ]:
row_indices = [1, 2, 3]
A[row_indices]

In [ ]:
col_indices = [1, 2, -1]
A[row_indices, col_indices]

Uporabljamo tudi <i>maske</i>. Le-te so strukture s podatki tipa `bool`, ki nakazujejo, ali bo element na pripadajočem mestu izbran ali ne.

In [ ]:
B = array([n for n in range(5)])
B

In [ ]:
row_mask = array([True, False, True, False, False])
B[row_mask]

In [ ]:
# se drugace
row_mask = array([1,0,1,0,0], dtype=bool)
B[row_mask]

Princip je uporaben za pogojno naslavljanje elementov glede na njihovo vsebino.

In [ ]:
x = array([0, 4, 2, 2, 3, 7, 10, 12, 15, 28])
x

In [ ]:
mask = (5 < x) * (x < 12.3)

mask

In [ ]:
x[mask]

<font color="green"><b>Naredi sam/-a.</b></font> Sedaj združimo vse načine naslavljanja. Preizkusi kombinacije vseh do sedaj omenjenih načinov naslavlanja naenkrat. Hkrati naslavljaj npr. vrstice z rezanjem, stolpce pa s pogojnim naslavljanjem. Ustvari več kot dvo-dimenzionalne strukture. Preveri, ali razumeš rezultat vsakega od naslavljanj.

In [ ]:
# Preizkusi več načinov naslavljnja hkrati.
A[A[:, 0]>10, 0:2 ]
# ...
# ...

### Funkcije za ustvarjanje polj

Numpy vsebuje funkcije za ustvarjanje pogostih tipov polj. Oglejmo si nekaj primerov.

#### Razpon `arange`

In [ ]:
x = arange(0, 10, 1) # od, do, korak

x

In [ ]:
x = arange(-1, 1, 0.1)

x

#### Razpona `linspace` in `logspace`

In [ ]:
# Pozor: zacetna in koncna tocka sta tudi vkljuceni
linspace(0, 10, 25) # od, do, stevilo med sabo enako oddaljenih tock

In [ ]:
logspace(0, 10, 11, base=e) # Poiskusi tudi z drugo osnovo (bazo): 2, 3, 10

#### Naključni podatki, modul `numpy.random`

In [ ]:
from numpy import random

In [ ]:
# enakomerno (uniformno) porazdeljene vrednosti v intervalu [0,1]
random.rand(5,5)

In [ ]:
# normalno porazdeljene vrednosti s sredino 0 in odklonom 1.
random.randn(5,5)

#### Diagonalna matrika `diag`

In [ ]:
diag([1,2,3])

In [ ]:
# diagonala je odmaknjena od glavne diagonale za k mest
diag([1,2,3], k=1) 

#### ničle in enice -  `zeros`, `ones`

In [ ]:
zeros((3,3))

In [ ]:
ones((3,3))

## Osnovne računske operacije

Ključno pri uporabi iterpretiranih jezikov je, da kar najbolj izkoriščamo vektorske operacije. Izogibajmo se odvečni uporabi zank. Karseda veliko operacij implementiramo kot operacije med matrikami in vektorji, npr. vektorsko ali matrično množenje.

### Operacije polja s skalarjem

Uporabimo običajne aritmetične operacije za množenje, seštevanje in deljenje s skalarjem.

In [ ]:
v1 = arange(0, 5)

In [ ]:
v1 * 2

In [ ]:
v1 + 2

In [ ]:
A * 2, A + 2

###  Operacije polje-polje (po elementih)

Operacije med več polji se privzeto obravnavajo po elementih.

In [ ]:
A * A # mnozenje po elementih

In [ ]:
v1 * v1

Pozor; dimenzije polj se morajo ujemati.

In [ ]:
A.shape, v1.shape

In [ ]:
A * v1

## Iteracija po elementih polja

Skušamo se držati načela, da se izogibamo uporabi zank preko elementov polja. Razlog je počasna implementacija zanki v intepretiranih jezikih, kot sta MATLAB in Python.
Včasih pa se zankam ne moremo izogniti. Zanka `for` je smiselna rešitev.  

In [ ]:
v = array([1,2,3,4])

for element in v:
    print(element)

In [ ]:
M = array([[1,2], [3,4]])

for row in M:
    print("row", row)
    
    for element in row:
        print(element)

Na mestu je tudi uporaba generatorja `enumerate` kadar želimo iteracijo po elementih in morebitno spreminjanje njihovih vrednosti.

In [ ]:
for i, row in enumerate(M):
    print("row index", i, "row", row)
    
    for j, element in enumerate(row):
        print("col index", j, "element", element)
       
        # Kvadriramo vsakega od elementov 
        M[i, j] = element ** 2

In [ ]:
# Vsak element smo kvadrirali
M

## Dodatni viri

* http://numpy.scipy.org
* http://scipy.org/Tentative_NumPy_Tutorial
* http://scipy.org/NumPy_for_Matlab_Users