<div style="background-color: lightgray; padding: 18px;">
    <h1> Learning Python | Day 14
    
</div>

### Features:
Numpy
- Reshape and Stacking
- Data Types
- Indexing and Slicing
- Advanced Indexing | Boolean Mask
- Arithmetic Operations

<div style="background-color: lightgreen; padding: 10px;">
    <h2> Reshape
</div>

Reshaping of ``ndarrays``:

Reshaping means changing the shape of an array.

The shape of an array is the **number of elements** in **each** dimension.

By reshaping we can add or remove dimensions or change number of elements in each dimension.

---
__Note:__ *Can We Reshape Into any Shape?*

Yes, as long as the elements required for reshaping are **equal** in both shapes.

We can reshape an 8 elements 1D array into 4 elements in 2 rows 2D array but we cannot reshape it into a 3 elements 3 rows 2D array as that would require 3x3 = 9 elemen

Source: https://www.w3schools.com/python/numpy/numpy_array_reshape.aspts.

In [3]:
import numpy as np
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before.shape)

(2, 4)


In [4]:
after = before.reshape((8))  # The new array must have the same number of elements
print(after)

[1 2 3 4 5 6 7 8]


In [5]:
after = before.reshape((8, 1)) 
print(after)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [6]:
after = before.reshape(2, 2, 2)
print(after)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


<div style="background-color: lightgreen; padding: 10px;">
    <h2> Stacking
</div>

Stacking ``ndarrays``

Another way to obtain arrays with different dimensions or shapes is to ``concatenate`` and ``stack`` arrays. 

Important points:
- ``stack()`` is used for joining multiple NumPy arrays. Unlike, ``concatenate()``, it joins arrays along a new axis. It returns a NumPy array.
- to join 2 arrays, they must have the same shape and dimensions. (e.g. both (2,3)–> 2 rows,3 columns)
- ``stack()`` creates a new array which has 1 more dimension than the input arrays. If we stack 2 1-D arrays, the resultant array will have 2 dimensions.

```
Syntax:  numpy.stack(arrays, axis=0, out=None)
```

Sources:
- https://www.geeksforgeeks.org/numpy-stack-in-python/
- https://www.geeksforgeeks.org/numpy-vstack-in-python/
- https://www.geeksforgeeks.org/numpy-hstack-in-python/?ref=lbp
- https://www.w3schools.com/python/numpy/numpy_array_join.asp

In [1]:
import numpy as np

# Example 1 : stacking two 1d arrays
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

# Stacking 2 1-d arrays
np.stack((v1, v2))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [2]:
# stack 2 1-d arrays column-wise
np.stack((v1, v2),axis=1)

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [4]:
# Example 2 : stacking two 2d arrays

x=np.array([[1,2,3],
            [4,5,6]])
 
y=np.array([[7,8,9],
            [10,11,12]])

np.stack((x,y),axis=0)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [5]:
np.stack((x,y),axis=2)

array([[[ 1,  7],
        [ 2,  8],
        [ 3,  9]],

       [[ 4, 10],
        [ 5, 11],
        [ 6, 12]]])

---
We can also stack one array on top of another (vertical stacking) using the `np.vstack` function

*or*

attempt to place them side by side (horizontal stacking) using the `np.hstack` function.

In [6]:
import numpy as np

# Example 1 : stacking two 1d arrays
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

# Stacking 2 1-d arrays ~ vertical:
np.vstack((v1, v2, v2, v2))

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [7]:
# Stacking 2 1-d arrays ~ horizontal:
np.hstack((v1, v2, v2, v2))

array([1, 2, 3, 4, 5, 6, 7, 8, 5, 6, 7, 8, 5, 6, 7, 8])

<div style="background-color: lightgreen; padding: 10px;">
    <h2> Data Types
</div>

NumPy has some extra ``data types``, in comparison with Python, and refer to data types with one character, like ``i`` for integers, ``u`` for unsigned integers etc.



Below is a list of all data types in NumPy and the characters used to represent them:

- `i` - integer
- `b` - boolean
- `u` - unsigned integer
- `f` - float
- `c` - complex float
- `m` - timedelta
- `M` - datetime
- `O` - object
- `S` - string
- `U` - unicode string
- `V` - fixed chunk of memory for other type (void)

Sources:
- https://www.w3schools.com/python/numpy/numpy_data_types.asp
- https://www.geeksforgeeks.org/numpy-data-types/
- https://numpy.org/doc/stable/user/basics.types.html
- https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html

In [8]:
# Checking the datatype of an array:

import numpy as np

arr = np.array([1, 2, 3, 4])
print(arr.dtype)

arr = np.array(['apple', 'banana', 'cherry'])
print(arr.dtype)

int32
<U6


---
A NumPy array has the ``dtype`` property, which gives us the type of the elements it contains.

It's worth remembering, as mentioned in the introduction:

- All elements in an ``ndarray`` have the **same** data type.

You may attempt to store data of different types, but NumPy will enforce type coercion to maintain this property.

In [35]:
vector = np.array([1., 2., 3, 4, 5, 6, 7])
vector.dtype

dtype('float64')

In [36]:
vector2 = np.array([1.3, 2.6, 3.4, 'AVOCADO', 5.1, 6, 7.99])
vector2.dtype

dtype('<U32')

---
To pass this parameter explicitly, simply use a second argument in the ``np.array`` function. 

For these arrays, we say that data consistency is **strong**. This means that if we create a vector of integers, for example, then all elements we place in our vector will **necessarily** be transformed into integers, as shown in the following example:

In [39]:
vector3 = np.array([1.3, 2.6, 3.4, 4.4, 5.1, 6, 7.99], dtype = np.float64)
vector3.dtype

dtype('float64')

In [42]:
vector4 = np.array([1.3, 2.6, 3.4, 4.4, 5.1, 6, 7.99], dtype = np.int32)
print(vector4, vector4.dtype)

[1 2 3 4 5 6 7] int32


In [43]:
# A non integer string like 'a' can not be converted to integer (will raise an error):

arr = np.array(['a', '2', '3'], dtype='i')

ValueError: invalid literal for int() with base 10: 'a'

---
It's worth mentioning: the default value of *dtype* depends on the installed Python. If the installed Python is 64-bit, the default will be 64-bit memory `int` or `float` types (`int64` or `float64`). If your Python is 32-bit, the default will be `int32` and `float32`.

This difference affects the precision of calculations. The more memory space used (the higher the number of bits), the higher the precisioion.

Some examples of NumPy data types (and probably the most common ones) are:

* `np.int32`
* `np.int64`
* `np.float32`
* `np.float64`

As an example, we can create another array, `a16`, with the integer type of 16 bits.

In [2]:
import numpy as np
a16 = np.array([1, 2, 3], dtype=np.int16)
a16

array([1, 2, 3], dtype=int16)

In [3]:
# To find out the space that each element individually occupies in memory, we can access the ~itemsize attribute.

a16.itemsize # it means, in bytes (2 bytes = 2 * 8 = 16 bits)

2

In [5]:
# To find out the number of elements:
a16.size

3

In [7]:
# So, the number of bytes can be represented by:

a16.size * a16.itemsize

6

In [9]:
# Or simply:
a16.nbytes

6

---
Converting data type on existing ``ndarray``:

The best way to change the data type of an existing array, is to make a copy of the array with the astype() method.

The ``astype()`` function creates a copy of the array, and allows you to specify the ``data type`` as a parameter.

The data type can be specified using a string, like '``f``' for float, '``i``' for integer etc. or you can use the data type directly like ``float`` for float and ``int`` for integer.

In [10]:
a = np.array([1.0, 2.0, 3.0])
a.dtype

dtype('float64')

In [12]:
b = a.astype('int32')
print(b.dtype)
print(b)

int32
[1 2 3]


In [13]:
a

array([1., 2., 3.])

<div style="background-color: lightgreen; padding: 10px;">
    <h2> Index and Slicing
</div>

``Array indexing`` is the same as accessing an array element.

You can access an array element by referring to its index number.

The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.

Sources:
- https://www.w3schools.com/python/numpy/numpy_array_indexing.asp
- https://www.w3schools.com/python/numpy/numpy_array_slicing.asp

In [14]:
# To get the first element:

import numpy as np

arr = np.array([1, 2, 3, 4])
print(arr[0])

1


In [16]:
# Access 2-D arrays:

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('2nd element on 1st row: ', arr[0, 1])

2nd element on 1st row:  2


In [17]:
# Access 3-D arrays:

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[0, 1, 2])

6


Example Explained:

``arr[0, 1, 2]`` prints the value 6.

And this is why:

- The first number represents the first dimension, which contains two arrays:
``[[1, 2, 3], [4, 5, 6]]``
and:
``[[7, 8, 9], [10, 11, 12]]``

- Since we selected 0, we are left with the first array:
``[[1, 2, 3], [4, 5, 6]]``

- The second number represents the second dimension, which also contains two arrays:
``[1, 2, 3]``
and:
``[4, 5, 6]``

- Since we selected 1, we are left with the second array:
``[4, 5, 6]``

- The third number represents the third dimension, which contains three values:
``4
5
6``
- Since we selected 2, we end up with the third value:
6

In [19]:
# It's also possible to use the same notation as in python:

arr[0][1][2]

6

---
``Slicing arrays``

Slicing in python means taking elements from one given index to another given index.

We pass slice instead of index like this: ``[start:end]``.

We can also define the step, like this: ``[start:end:step]``.

If we don't pass ``start`` its considered ``0``

If we don't pass ``end`` its considered length of array in that dimension

If we don't pass ``step`` its considered ``1``

In [26]:
# Slicing 1-D Arrays

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


In [22]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 10, 10])

print(arr[4:])
print(arr[:4])

[ 5  6  7  8  9 10 10 10]
[1 2 3 4]


In [25]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 8, 8, 9, 10])

print(arr[-3:-1])

[8 9]


In [28]:
# Slicing 2-D Arrays

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[7 8 9]


In [34]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[:, 2])

[3 8]


In [35]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


<div style="background-color: lightgreen; padding: 10px;">
    <h2> Advanced Indexing | Boolean Mask
</div>

``NumPy Advanced indexing`` returns a copy of data rather than a view of it. Advanced indexing is of two types ``integer`` and ``boolean``.

Advanced indexing in the NumPy array allows you to access and manipulate complex patterns of the data.

Advanced indexing is triggered when obj is : 

- an ``ndarray`` of type integer or Boolean;
- or a ``tuple`` with at least one sequence object;
- is a ``non tuple`` sequence object;

**Types of Advanced Indexing**
  
There are two types of Advanced Indexing in NumPy array indexing:

- Purely integer indexing;
- Boolean integer indexing;

Sources:
- https://www.geeksforgeeks.org/numpy-slicing-and-indexing/

---
**Purely integer array indexing**

Purely integer array indexing allows us to access elements from an ndarray (N-dimensional array) using integers.

When integers are used for indexing. Each element of the first dimension is paired with the element of the second dimension. So the index of the elements in this case are ``(0,0),(1,0),(2,1)`` and the corresponding elements are selected.

Example: Using purely integer array indexing

In [9]:
# Python program showing advanced indexing 
import numpy as np 

a = np.array([[1 ,2 ],[3 ,4 ],[5 ,6 ]]) 

print(a)

[[1 2]
 [3 4]
 [5 6]]


In [11]:
print(a[[0 ,1 ,2 ],[0 ,0 ,1]]) # positions: (0,0),(1,0),(2,1)

[1 3 6]


---
**Boolean Indexing**

This indexing has some ``boolean expressions`` as the index.

Those elements are returned which satisfy that Boolean expression. It is used for filtering the desired element values.

In [20]:
# Example 1: Using boolean indexing on NumPy array to find numbers greater than 50

import numpy as np 
  
a = np.array([10, 40, 80, 50, 100]) 
mask = a>50

print(mask)

print(a[mask])
print(a[a>50])

[False False  True False  True]
[ 80 100]
[ 80 100]


In [21]:
# Example 2: Using boolean indexing on NumPy array to find numbers whose sum row is 10#

 
b = np.array([[5, 5],[4, 5],[16, 4]]) 
sumrow = b.sum(-1) 

print(b[sumrow%10==0])

[[ 5  5]
 [16  4]]


<div style="background-color: lightgreen; padding: 10px;">
    <h2> Arithmetic Operations
</div>

``NumPy objects`` can be easily converted to other types of objects like the Pandas data frame and the tensorflow tensor. 

Python list can be used for array computing, but it is much slower than NumPy. NumPy achieves its fast implementation using vectorization. 

One of the important features of NumPy arrays is that a developer can perform the **same mathematical operation** on every element with a single command.

Let us understand ``arithmetic operations`` using NumPy.

Sources:
- https://www.geeksforgeeks.org/numpy-arithmetic-operations/

In [28]:
# Addition

import numpy as np
 
# Defining both the matrices
a = np.array([5, 72, 13, 100])
b = np.array([2, 5, 10, 30])
 
# Performing addition using arithmetic operator
add_ans = a+b
print(add_ans)
 
# Performing addition using numpy function
add_ans = np.add(a, b)
print(add_ans)
 
# this would work
c = np.array([1, 2, 3, 4])
add_ans = a+b+c
print(add_ans)
 
# IMPORTANT: here NumPy only considers the first two arrays (a and b) and ignores the third one (c).
add_ans = np.add(a, b, c)
print(add_ans)

[  7  77  23 130]
[  7  77  23 130]
[  8  79  26 134]
[  7  77  23 130]


In [29]:
# Subtraction

import numpy as np
 
# Defining both the matrices
a = np.array([5, 72, 13, 100])
b = np.array([2, 5, 10, 30])
 
# Performing subtraction using arithmetic operator
sub_ans = a-b
print(sub_ans)
 
# Performing subtraction using numpy function
sub_ans = np.subtract(a, b)
print(sub_ans)

[ 3 67  3 70]
[ 3 67  3 70]


In [36]:
# Multiplication
 
import numpy as np
 
# Defining both the matrices
a = np.array([5, 72, 13, 100])
b = np.array([2, 5, 10, 30])
 
# Performing multiplication using arithmetic operator
mul_ans = a*b
print(mul_ans)
 
# Performing multiplication using numpy function
mul_ans = np.multiply(a, b)
print(mul_ans)

[  10  360  130 3000]
[  10  360  130 3000]


In [33]:
# Division

import numpy as np
 
# Defining both the matrices
a = np.array([5, 72, 13, 100])
b = np.array([2, 5, 10, 30])
 
# Performing division using arithmetic operators
div_ans = a/b
print(div_ans)
 
# Performing division using numpy functions
div_ans = np.divide(a, b)
print(div_ans)

[ 2.5        14.4         1.3         3.33333333]
[ 2.5        14.4         1.3         3.33333333]


In [37]:
# Some aggregation and statistical functions

# Getting mean of all numbers in 'a'
mean_a = np.mean(a)
print(mean_a)
 
# Getting average of all numbers in 'b'
mean_b = np.average(b)
print(mean_b)
 
# Getting sum of all numbers in 'a'
sum_a = np.sum(a)
print(sum_a)
 
# Getting variance of all number in 'b'
var_b = np.var(b)
print(var_b)

47.5
11.75
190
119.1875


<div style="background-color: lightgreen; padding: 10px;">
    <h2> Exercices
</div>

**Ex1:** 
Imagine that you are a data scientist analyzing the performance of two sales teams over the course of a year. For each team, use an ndarray with 6 positions to represent the total sales over each of the 6 two-month periods in a year. Fill both arrays with the values you want. Then, calculate the average sales per period and indicate, for each team, in which periods the average sale was exceeded.

In [2]:
import numpy as np
vendas1 = np.array([1000, 1500, 2000, 2400, 5000, 1700])
vendas2 = np.array([2100, 3500, 1000, 1700, 3000, 2700])

# Primeira abordagem - média do grupo:
media1 = vendas1.sum(0) / vendas1.size
media2 = vendas2.sum(0) / vendas2.size

print(media1)
print(media2)

2266.6666666666665
2333.3333333333335


In [3]:
# Segunda abordagem, média por bimestre:

medias = (vendas1 + vendas2) / 2
print(medias)

a = vendas1 >= medias
b = vendas2 >= medias
print(a)
print(b)

[1550. 2500. 1500. 2050. 4000. 2200.]
[False False  True  True  True False]
[ True  True False False False  True]


In [4]:
time_a = vendas1[a]
time_a


array([2100, 3500, 2700])

In [5]:
time_b = vendas2[b]
time_b

array([2100, 3500, 2700])

**Ex2:** You work for a company and have received expense reports separated by quarter. Consider 3 types of expenses: `personal`, `supplies`, and `miscellaneous`. For each type, use an ndarray to store the 4 quarterly expense values that were recorded over the past year. After that, use ndarrays to find the total expenses for each quarter and then organize all expenses into a single data structure by stacking the ndarrays.

In [6]:
import numpy as np

pessoal = np.array([2000, 4000, 4500, 6000])
insumos = np.array([2500, 5000, 7500, 10000])
diversos = np.array([0, 1500, 800, 1200])

totais = pessoal + insumos + diversos
totais

array([ 4500, 10500, 12800, 17200])

In [7]:
resultante = np.vstack((pessoal, insumos, diversos))
resultante

array([[ 2000,  4000,  4500,  6000],
       [ 2500,  5000,  7500, 10000],
       [    0,  1500,   800,  1200]])

**Ex3:** Using the expenses saved in ndarrays in the previous exercise, use the ndarrays to find the total expenses for each semester, not each quarter.

In [8]:
print(sum(resultante[:,:2]))
print(sum(resultante[:,2:]))

[ 4500 10500]
[12800 17200]


In [9]:
p_semestre = sum(sum(resultante[:,:2]))
s_semestre = sum(sum(resultante[:,2:]))

print(p_semestre, s_semestre)

15000 30000


**Ex4:** Consider the following NumPy array `arr`:

```python
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])
```

Perform the following slicing operations:

- Extract the second row of the array `arr`.
- Get the last column of the array `arr`.
- Create a submatrix consisting of the first two rows and the first two columns of `arr`.
- Select the elements 6, 7, 10, and 11 from `arr`.

In [11]:
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

arr[1, :]

array([5, 6, 7, 8])

In [12]:
arr[:,-1]

array([ 4,  8, 12])

In [13]:
arr[0:2,0:2]

array([[1, 2],
       [5, 6]])

In [14]:
arr[1:3,1:3]

array([[ 6,  7],
       [10, 11]])

**Ex5:** For the same matrix `arr` from the previous exercise, create a boolean matrix with the same shape as `arr` where True represents values greater than 6. Afterward, use the boolean matrix to create a new ndarray containing only the values greater than 6.

In [15]:
mask_boolean = arr > 6
mask_boolean

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [16]:
new = arr[mask_boolean]
new

array([ 7,  8,  9, 10, 11, 12])