# NUMPY TUTORIAL

In [1]:
print("Hello")

Hello


In [2]:
print("Bharat")

Bharat


** ARRAY CREATION **

In [1]:
import numpy as np

# Create a NumPy array
arr = np.array([10, 20, 30, 40, 50])

# Print the entire array
print(arr)

# Print elements from index 0 to 1
print(arr[0:2])

# Print elements from index 3 to the end of the array
print(arr[3:])

# Print the element at index 0
print(arr[0])

# Print the element at index 0 with a step of 4 (effectively printing only the element at index 0)
print(arr[0:1:4])

[10 20 30 40 50]
[10 20]
[40 50]
10
[10]


In [4]:
type(arr)

numpy.ndarray

In [4]:
arr1 = np.array([[10,20,30,50],[40,50,60,90]])
print(arr1)
print(arr1[1:])
print(arr1[0:2,0:2])
print(arr1[0,1:3])
print(arr1[1,0:3])

[[10 20 30 50]
 [40 50 60 90]]
[[40 50 60 90]]
[[10 20]
 [40 50]]
[20 30]
[40 50 60]


In [3]:
arr2 = np.array([[10,20,30],[40,50,60],[10,40,70,80]])
print(arr2)
# Since these lists have different lengths, NumPy cannot create a proper 2D array, which leads to an error 

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

** ATTRIBUTES **

In [5]:
a = np.array([[10,20,70,30],[40,50,80,60],[10,40,70,90]])
print(np.shape(a))
print(np.size(a))
print(np.ndim(a))
print(a.dtype)
print(len(a))
b = a.astype(str)
print(b)
c = np.array(a)
print(c)
d = np.array([[10,20,70,30],[40,50.5,80,"60"]])
print(d.astype(int))
# NumPy cannot directly convert a string to an integer, 
# especially when the array contains mixed data types like floats and strings.

(3, 4)
12
2
int32
3
[['10' '20' '70' '30']
 ['40' '50' '80' '60']
 ['10' '40' '70' '90']]
[[10 20 70 30]
 [40 50 80 60]
 [10 40 70 90]]


ValueError: invalid literal for int() with base 10: '50.5'

In [75]:
# MATHEMATICAL_FUNCTIONS

a1 = np.array([10,20,30,40,50])
a2 = np.array([90,70,20,60,40])
print(a1+a2)
print(np.add(a1,a2))
print(a1-a2)
print(np.subtract(a2,a1))
print(a1*a2)
print(np.multiply(a1,a2))
print(a1/a2)
print(np.divide(a1,a2))

a3 = np.array([[10,20],[40,50]])
a4 = np.array([[90,70],[20,60]])
print(a3+a4)
print(a3-a4)
print(a3*a4)
print(a3/a4)

a5 = np.array([[10,20],[40,50]])
a6 = np.array([2])
print(np.power(a5,a6))

a7 = np.array([4,64,81,16,25])
print(np.sqrt(a7))

[100  90  50 100  90]
[100  90  50 100  90]
[-80 -50  10 -20  10]
[ 80  50 -10  20 -10]
[ 900 1400  600 2400 2000]
[ 900 1400  600 2400 2000]
[0.11111111 0.28571429 1.5        0.66666667 1.25      ]
[0.11111111 0.28571429 1.5        0.66666667 1.25      ]
[[100  90]
 [ 60 110]]
[[-80 -50]
 [ 20 -10]]
[[ 900 1400]
 [ 800 3000]]
[[0.11111111 0.28571429]
 [2.         0.83333333]]
[[ 100  400]
 [1600 2500]]
[2. 8. 9. 4. 5.]


In [19]:
import numpy as np
rng = np.arange(10)
print(rng)

[0 1 2 3 4 5 6 7 8 9]


In [32]:
import numpy as np
x = np.array([1,32,654,25,78,2])
print(x.argmax())
print(x.argmin())
print(x.argsort())

2
2
0
[0 5 3 1 4 2]


In [58]:
y = np.array([[1,2,3],[4,5,6],[7,1,0]])
print(y)
print()
print(y.argmin())
print(y.argmax())
print()
print(y.argmax(axis=0))
print()
print(y.argmax(axis=1))
print()
print(y.argsort(axis = 0))
print()
print(y.argsort(axis = 1))

[[1 2 3]
 [4 5 6]
 [7 1 0]]

8
6

[2 1 1]

[2 2 0]

[[0 2 2]
 [1 0 0]
 [2 1 1]]

[[0 1 2]
 [0 1 2]
 [2 1 0]]
