In [2]:
import numpy as np
from matplotlib.pyplot import plot
%matplotlib inline
from time import time
from random import random
import mpmath

In [2]:
from random import randint as rnd
pmove, level = int(input(" > ")), 125
cmove = rnd(0, level-1)
print(cmove)
if cmove-pmove == 0: print("Tie")
elif ((cmove-pmove)%level)>(level/2): print("Player wins")
elif ((cmove-pmove)%level)<(level/2): print("Computer wins")
else: print("Equal and opposite cancel! Mirror tie")

 > '


ValueError: invalid literal for int() with base 10: "'"

In [8]:
m = np.matrix([[2,0],[0,1]])

In [3]:
def eigenValues(matrix):
    a,b,c,d = matrix.A1
    e1 = ((a+d)+(4*c*b+(a-d)**2)**0.5)/2
    e2 = ((a+d)-(4*c*b+(a-d)**2)**0.5)/2
    return e1, e2

In [4]:
def power(matrix, power):
    e1, e2 = eigenValues(matrix)
    e1, e2 = mpmath.mpc(e1), mpmath.mpc(e2)
    return ((e2*e1**power-e1*e2**power)/(e2-e1)*np.matrix([[1,0],[0,1]])
            + (e2**power - e1**power)/(e2-e1)*matrix)

In [5]:
def root(matrix, n=2):
    return power(matrix, 1/n)

In [13]:
a = power(m,complex(2,0))

matrix([[mpc(real='4.0', imag='0.0'), mpc(real='0.0', imag='0.0')],
        [mpc(real='0.0', imag='0.0'), mpc(real='1.0', imag='0.0')]], dtype=object)

In [17]:
power(a, 10000)

matrix([[mpc(real='1.0', imag='0.0'),
         mpc(real='1.9999999999976288', imag='-4.105360897100979e-13')],
        [mpc(real='2.9999999999964433', imag='-6.1586528452576264e-13'),
         mpc(real='3.999999999996362', imag='0.0')]], dtype=object)

In [24]:
V = np.array([1,1])

In [38]:
V*a**10000

matrix([[mpc(real='3.9999999999962816', imag='-1.0233341951604302e-12'),
         mpc(real='5.9999999999960414', imag='2.9309887850104133e-13')]], dtype=object)

In [23]:
def eToMatrix(M, order):
    total = np.matrix([[1.,0.],[0.,1.]]) + M
    for i in range(2,2**order):
        total = total + (M**i)/np.math.factorial(i) 
    return total

In [19]:
a = eToMatrix(b, 8)

In [20]:
a

matrix([[51.89526846386442, 111.95271291729414],
        [74.65271974914342, 163.15845668345213]], dtype=object)

In [16]:
b = np.matrix([[1,3],[2,4]])

In [7]:
I = np.matrix([[1.,0.],[0.,1.]])

In [85]:
power(np.matrix([[4,0],[0,1]]),complex(0,1))

matrix([[mpc(real='0.18345697474330169', imag='0.98302774041124374'),
         mpc(real='0.0', imag='0.0')],
        [mpc(real='0.0', imag='0.0'), mpc(real='1.0', imag='0.0')]], dtype=object)

In [191]:
def ln(Q, order):
    norm = abs(np.linalg.det(Q))**.5*2
    M = Q/norm - 1
    total = np.matrix([[0,0],[0,0]])
    for i in range(1,2**order):
        total = total + (-1)**(i+1) * (M**i)/i
    return total + np.log(norm)

In [201]:
a = ln(20*I,10)

In [202]:
a

matrix([[ -2.03435173e+177,  -2.03435173e+177],
        [ -2.03435173e+177,  -2.03435173e+177]])

In [203]:
eToMatrix(a,6)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: RuntimeWarning: invalid value encountered in add
  after removing the cwd from sys.path.


matrix([[nan, nan],
        [nan, nan]], dtype=object)