In [21]:
import math
e_const=math.e
pi_const=math.pi
import statistics
from fractions import Fraction
from decimal import Decimal
import numpy as np

def add(x, y):
    last_result=x+y
    return last_result

def subtract(x, y):
    last_result= x - y
    return last_result

def multiply(x, y):
    last_result= x * y
    return last_result

def divide(x, y):
    if y == 0:
        return "Error: Cannot divide by zero"
    else:
        last_result= x / y
        return last_result

def power(x, y):
    last_result= x ** y
    return last_result

def square_root(x,y):
    last_result= x**(1/2)
    return last_result

def variable_root(x,y):
    last_result= x**(1/y)
    return last_result

def sin(x):
    last_result= math.sin(math.radians(x))
    return last_result

def cos(x):
    last_result= math.cos(math.radians(x))
    return last_result

def tan(x):
    last_result= math.tan(math.radians(x))
    return last_result

def sinh(x):
    last_result= math.sinh(math.radians(x))
    return last_result

def cosh(x):
    last_result= math.cosh(math.radians(x))
    return last_result

def tanh(x):
    last_result= math.tanh(math.radians(x))
    return last_result

def logarithm(x):
    last_result= math.log10(x)
    return last_result

def logarithm_base2(x):
    last_result= math.log2(x)
    return last_result

def ln(x):
    last_result= math.log(x)
    return last_result

def exponential(x):
    last_result= e_const**x
    return last_result

def mean(*x):
    last_result= statistics.mean(x)
    return last_result

def variance(*x):
    last_result= statistics.variance(x)
    return last_result

def standard_deviation(*x):
    last_result= statistics.stdev(x)
    return last_result

def decimal_value(x,y):
    last_result= Decimal(x/y)
    return last_result

def fraction_value(x):
    last_result= Fraction(x)
    return last_result

def factorial(x):
    last_result=1
    for i in range (1,x+1,1):
        last_result*=i
    return last_result

def permutation(x,y):
    z=x-y
    last_result= factorial(x)/factorial(z)
    return last_result

def combination(x,y):
    z=x-y
    last_result= factorial(x)/(factorial(y)*factorial(z))
    return last_result

def meters_to_feet(meters):
    last_result= meters * 3.28084
    return last_result

def feet_to_meters(feet):
    last_result= feet / 3.28084
    return last_result

def kilograms_to_pounds(kilograms):
    last_result= kilograms * 2.20462
    return last_result

def pounds_to_kilograms(pounds):
    last_result= pounds / 2.20462
    return last_result

def liters_to_gallons(liters):
    last_result= liters * 0.264172
    return last_result

def gallons_to_liters(gallons):
    last_result= gallons / 0.264172
    return last_result

def solve_linear_eqn(a, b):
    if a == 0:
        raise ValueError("Coefficient 'a' cannot be zero.")
    return -b / a

def solve_quadratic_eqn(a, b, c):
    discriminant = b**2 - 4*a*c
    if discriminant > 0:
        root1 = (-b + math.sqrt(discriminant)) / (2*a)
        root2 = (-b - math.sqrt(discriminant)) / (2*a)
        return root1, root2
    elif discriminant == 0:
        root = -b / (2*a)
        return root,
    else:
        realPart = -b / (2*a)
        imaginaryPart = math.sqrt(-discriminant) / (2*a)
        return (realPart + imaginaryPart*1j, realPart - imaginaryPart*1j)
def find_polynomial_eqn(a,b,c):
    coefficients=[a,b,c]
    roots = np.roots(coefficients)
    return roots

def matrix_addition(matrix1,matrix2):
    return np.add(matrix1, matrix2)

def matrix_subtraction(matrix1,matrix2):
    return np.subtract(matrix1, matrix2)

def matrix_multiplication(matrix1,matrix2):
    return np.dot(matrix1, matrix2)

def matrix_det(matrix):
    return np.linalg.det(matrix)

def matrix_inv(matrix):
    try:
     result=np.linalg.inv(matrix)
    except np.linalg.LinAlgError:
     result='error'
    return result

def matrix_transpose(matrix):
    return np.transpose(matrix)

def show_operations():
    print("Available operations:")
    print("1. Addition (+)")
    print("2. Subtraction (-)")
    print("3. Multiplication (*)")
    print("4. Division (/)")
    print("5. Power (^)")
    print("6. Square Root (sqrt)")
    print("7. Variable Root (root)")
    print("8. Sine (sin)")
    print("9. Cosine (cos)")
    print("10. Tangent (tan)")
    print("11. Hyperbolic Sine (sinh)")
    print("12. Hyperbolic Cosine (cosh)")
    print("13. Hyperbolic Tangent (tanh)")
    print("14. Logarithm (log10)")
    print("15. Logarithm Base 2 (log2)")
    print("16. Natural Logarithm (ln)")
    print("17. Exponential (exp)")
    print("18. Mean (mean)")
    print("19. Variance (variance)")
    print("20. Standard Deviation (stdev)")
    print("21. Decimal Value (decimal)")
    print("22. Fraction Value (fraction)")
    print("23. Factorial (factorial)")
    print("24. Permutation (perm)")
    print("25. Combination (comb)")
    print("26. Meters to Feet (m2ft)")
    print("27. Feet to Meters (ft2m)")
    print("28. Kilograms to Pounds (kg2lb)")
    print("29. Pounds to Kilograms (lb2kg)")
    print("30. Liters to Gallons (L2G)")
    print("31. Gallons to Liters (G2L)")
    print("32. Solve Linear Equation (linear)")
    print("33. Solve Quadratic Equation (quadratic)")
    print("34. Find Polynomial Roots (polynomial)")
    print("35. Matrix Addition (mat_add)")
    print("36. Matrix Subtraction (mat_sub)")
    print("37. Matrix Multiplication (mat_mul)")
    print("38. Matrix Determinant (mat_det)")
    print("39. Matrix Inverse (mat_inv)")
    print("40. Matrix Transpose (mat_trans)")
    print("41. Store to Memory (M)")
    print("42. Recall Memory (MR)")
    print("43. Add to Memory (M+)")
    print("44. Subtract from Memory (M-)")
    print("45. Clear Memory (MC)")
    print("46. Exit (end)")

def calculator():
    show_operations()

    memory = 0  
    last_result=0
    while True:
        choice = input("Enter your choice: ").strip().lower()

        if choice == 'end':
            print("Goodbye!")
            break
        elif choice in ['+', '-', '*', '/', '^']:
            x = float(input("Enter first number: "))
            y = float(input("Enter second number: "))
            if choice == '+':
                print(f"Result: {add(x, y)}")
                last_result=add(x, y)
            elif choice == '-':
                print(f"Result: {subtract(x, y)}")
                last_result=subtract(x, y)
            elif choice == '*':
                print(f"Result: {multiply(x, y)}")
                last_result=multiply(x, y)
            elif choice == '/':
                print(f"Result: {divide(x, y)}")
                last_result=divide(x, y)
            elif choice == '^':
                print(f"Result: {power(x, y)}")
                last_result=power(x, y)
        elif choice == 'sqrt':
            x = float(input("Enter number: "))
            print(f"Result: {square_root(x)}")
            last_result=square_root(x)
        elif choice == 'root':
            x = float(input("Enter base: "))
            y = float(input("Enter root: "))
            print(f"Result: {variable_root(x, y)}")
            last_result=variable_root(x, y)
        elif choice == 'sin':
            x = float(input("Enter angle (degrees): "))
            print(f"Result: {sin(x)}")
            last_result=sin(x)
        elif choice == 'cos':
            x = float(input("Enter angle (degrees): "))
            print(f"Result: {cos(x)}")
            last_result=cos(x)
        elif choice == 'tan':
            x = float(input("Enter angle (degrees): "))
            print(f"Result: {tan(x)}")
            last_result=tan(x)
        elif choice == 'sinh':
            x = float(input("Enter angle (degrees): "))
            print(f"Result: {sinh(x)}")
            last_result=sinh(x)
        elif choice == 'cosh':
            x = float(input("Enter angle (degrees): "))
            print(f"Result: {cosh(x)}")
            last_result=cosh(x)
        elif choice == 'tanh':
            x = float(input("Enter angle (degrees): "))
            print(f"Result: {tanh(x)}")
            last_result=tanh(x)
        elif choice == 'log10':
            x = float(input("Enter number: "))
            print(f"Result: {logarithm(x)}")
            last_result=logarithm(x)
        elif choice == 'log2':
            x = float(input("Enter number: "))
            print(f"Result: {logarithm_base2(x)}")
            last_result=logarithm_base2(x)
        elif choice == 'ln':
            x = float(input("Enter number: "))
            print(f"Result: {ln(x)}")
            last_result=ln(x)
        elif choice == 'exp':
            x = float(input("Enter exponent: "))
            print(f"Result: {exponential(x)}")
            last_result=exponential(x)
        elif choice == 'mean':
            nums = list(map(float, input("Enter numbers separated by spaces: ").split()))
            print(f"Result: {mean(*nums)}")
            last_result=mean(*nums)
        elif choice == 'variance':
            nums = list(map(float, input("Enter numbers separated by spaces: ").split()))
            print(f"Result: {variance(*nums)}")
            last_result=variance(*nums)
        elif choice == 'stdev':
            nums = list(map(float, input("Enter numbers separated by spaces: ").split()))
            print(f"Result: {standard_deviation(*nums)}")
            last_result=standard_deviation(*nums)
        elif choice == 'decimal':
            x = input("Enter number: ")
            print(f"Result: {decimal_value(x)}")
            last_result=decimal_value(x)
        elif choice == 'fraction':
            x = input("Enter number: ")
            print(f"Result: {fraction_value(x)}")
            last_result=fraction_value(x)
        elif choice == 'factorial':
            x = int(input("Enter number: "))
            print(f"Result: {factorial(x)}")
            last_result=factorial(x)
        elif choice == 'perm':
            x = int(input("Enter n: "))
            y = int(input("Enter r: "))
            print(f"Result: {permutation(x, y)}")
            last_result=permutation(x, y)
        elif choice == 'comb':
            x = int(input("Enter n: "))
            y = int(input("Enter r: "))
            print(f"Result: {combination(x, y)}")
            last_result=combination(x, y)
        elif choice == 'm2ft':
            meters = float(input("Enter meters: "))
            print(f"Result: {meters_to_feet(meters)}")
            last_result=meters_to_feet(meters)
        elif choice == 'ft2m':
            feet = float(input("Enter feet: "))
            print(f"Result: {feet_to_meters(feet)}")
            last_result=feet_to_meters(feet)
        elif choice == 'kg2lb':
            kilograms = float(input("Enter kilograms: "))
            print(f"Result: {kilograms_to_pounds(kilograms)}")
            last_result=kilograms_to_pounds(kilograms)
        elif choice == 'lb2kg':
            pounds = float(input("Enter pounds: "))
            print(f"Result: {pounds_to_kilograms(pounds)}")
            last_result=pounds_to_kilograms(pounds)
        elif choice == 'l2g':
            liters = float(input("Enter liters: "))
            print(f"Result: {liters_to_gallons(liters)}")
            last_result=liters_to_gallons(liters)
        elif choice == 'g2l':
            gallons = float(input("Enter gallons: "))
            print(f"Result: {gallons_to_liters(gallons)}")
            last_result=gallons_to_liters(gallons)
        elif choice == 'linear':
            a = float(input("Enter coefficient a: "))
            b = float(input("Enter coefficient b: "))
            print(f"Result: {solve_linear_eqn(a, b)}")
        elif choice == 'quadratic':
            a = float(input("Enter coefficient a: "))
            b = float(input("Enter coefficient b: "))
            c = float(input("Enter coefficient c: "))
            print(f"Result: {solve_quadratic_eqn(a, b, c)}")
        elif choice == 'polynomial':
            a = float(input("Enter coefficient a: "))
            b = float(input("Enter coefficient b: "))
            c = float(input("Enter coefficient c: "))
            print(f"Roots: {find_polynomial_eqn(a, b, c)}")
        elif choice == 'mat_add':
            matrix1 = np.array(eval(input("Enter first matrix (as list of lists): ")))
            matrix2 = np.array(eval(input("Enter second matrix (as list of lists): ")))
            print(f"Result: {matrix_addition(matrix1, matrix2)}")
        elif choice == 'mat_sub':
            matrix1 = np.array(eval(input("Enter first matrix (as list of lists): ")))
            matrix2 = np.array(eval(input("Enter second matrix (as list of lists): ")))
            print(f"Result: {matrix_subtraction(matrix1, matrix2)}")
        elif choice == 'mat_mul':
            matrix1 = np.array(eval(input("Enter first matrix (as list of lists): ")))
            matrix2 = np.array(eval(input("Enter second matrix (as list of lists): ")))
            print(f"Result: {matrix_multiplication(matrix1, matrix2)}")
        elif choice == 'mat_det':
            matrix = np.array(eval(input("Enter matrix (as list of lists): ")))
            print(f"Result: {matrix_det(matrix)}")
        elif choice == 'mat_inv':
            matrix = np.array(eval(input("Enter matrix (as list of lists): ")))
            print(f"Result: {matrix_inv(matrix)}")
        elif choice == 'mat_trans':
            matrix = np.array(eval(input("Enter matrix (as list of lists): ")))
            print(f"Result: {matrix_transpose(matrix)}")
        elif choice == 'store to memory':
            memory = last_result
            print(f"Stored {memory} in memory.")
        elif choice == 'recall memory':
            print(f"Recalled memory: {memory}")
        elif choice == 'add to memory':
            memory += last_result
            print(f"Added {last_result} to memory. New memory: {memory}")
        elif choice == 'subtract from memory':
            memory -= last_result
            print(f"Subtracted {last_result} from memory. New memory: {memory}")
        elif choice == 'clear memory':
            memory = 0
            print("Memory cleared.")
        else:
            print("Invalid choice. Please select a valid operation or 'end' to quit.")

In [22]:
add(x=int(input()),y=int(input()))

ValueError: invalid literal for int() with base 10: ''

In [ ]:
subtract(x=int(input()),y=int(input()))

1

In [ ]:
multiply(x=int(input()),y=int(input()))

6

In [ ]:
divide(x=int(input()),y=int(input()))

1.25

In [ ]:
power(x=int(input()),y=int(input()))

64

In [ ]:
square_root(x=int(input()),y=1/2)

2.23606797749979

In [ ]:
variable_root(x=int(input()),y=int(input()))

1.1769039562428527

In [ ]:
sin(x=int(input()))

0.20791169081775934

In [ ]:
cos(x=int(input()))

0.9702957262759965

In [ ]:
tan(x=int(input()))

0.03492076949174773

In [ ]:
sinh(x=int(input()))

0.3010785658797934

In [ ]:
cosh(x=int(input()))

1.0074724144482754

In [ ]:
tanh(x=int(input()))

0.3042161928867445

In [ ]:
logarithm(x=int(input()))

0.9542425094393249

In [ ]:
logarithm_base2(x=int(input()))

3.169925001442312

In [ ]:

ln(x=int(input())) 


1.6094379124341003

In [ ]:
exponential(x=int(input()))

403.428793492735

In [ ]:
mean(1,2,3,4,5,8)

3.8333333333333335

In [ ]:
variance(1,2,3,4,5,8)

6.166666666666667

In [ ]:
standard_deviation(1,2,3,4,5,6,7,8)

2.449489742783178

In [ ]:
fraction_value(x=float(input()))

Fraction(3, 1)

In [ ]:
decimal_value(x=int(input()),y=int(input()))

Decimal('1.5')

In [ ]:
factorial(x=int(input()))

1

In [ ]:
permutation(x=int(input()),y=int(input()))

120.0

In [ ]:
combination(x=int(input()),y=int(input()))

0.2

In [ ]:
meters_to_feet(meters=int(input()))


13.12336

In [ ]:
feet_to_meters(13.12336)

4.0

In [ ]:
kilograms_to_pounds(kilograms=float(input()))

11.0231

In [ ]:
pounds_to_kilograms(11.0231)

5.0

In [ ]:
liters_to_gallons(liters=float(input()))

1.056688

In [ ]:
gallons_to_liters(1.056688)

4.0

In [ ]:
solve_linear_eqn(a=int(input()),b=int(input()))

-1.25

In [ ]:
solve_quadratic_eqn(a=int(input()),b=int(input()),c=int(input()))

((-0.5+0.5j), (-0.5-0.5j))

In [ ]:
solve_quadratic_eqn(a=int(input()),b=int(input()),c=int(input()))

((-0.6+0.4898979485566356j), (-0.6-0.4898979485566356j))

In [ ]:
find_polynomial_eqn(a=int(input()),b=int(input()),c=int(input()))

array([-0.75+1.19895788j, -0.75-1.19895788j])

In [ ]:
find_polynomial_eqn(a=int(input()),b=int(input()),c=int(input()))

array([-12.29669331,  -0.20330669])

In [ ]:
matrix1=[[1,2],[1,3]]
matrix2=[[1,4],[1,5]]
matrix_addition(matrix1,matrix2)

array([[2, 6],
       [2, 8]])

In [ ]:
matrix_subtraction(matrix1,matrix2)

array([[ 0, -2],
       [ 0, -2]])

In [ ]:
matrix3=[3,3,3]
matrix4=[[2],[2],[2]]
matrix_multiplication(matrix3,matrix4)

array([18])

In [ ]:
matrix_det(matrix1)

1.0

In [ ]:
matrix_inv(matrix1)

array([[ 3., -2.],
       [-1.,  1.]])

In [ ]:
matrix_transpose(matrix1)

array([[1, 1],
       [2, 3]])

In [ ]:
calculator()

Available operations:
1. Addition (+)
2. Subtraction (-)
3. Multiplication (*)
4. Division (/)
5. Power (^)
6. Square Root (sqrt)
7. Variable Root (root)
8. Sine (sin)
9. Cosine (cos)
10. Tangent (tan)
11. Hyperbolic Sine (sinh)
12. Hyperbolic Cosine (cosh)
13. Hyperbolic Tangent (tanh)
14. Logarithm (log10)
15. Logarithm Base 2 (log2)
16. Natural Logarithm (ln)
17. Exponential (exp)
18. Mean (mean)
19. Variance (variance)
20. Standard Deviation (stdev)
21. Decimal Value (decimal)
22. Fraction Value (fraction)
23. Factorial (factorial)
24. Permutation (perm)
25. Combination (comb)
26. Meters to Feet (m2ft)
27. Feet to Meters (ft2m)
28. Kilograms to Pounds (kg2lb)
29. Pounds to Kilograms (lb2kg)
30. Liters to Gallons (L2G)
31. Gallons to Liters (G2L)
32. Solve Linear Equation (linear)
33. Solve Quadratic Equation (quadratic)
34. Find Polynomial Roots (polynomial)
35. Matrix Addition (mat_add)
36. Matrix Subtraction (mat_sub)
37. Matrix Multiplication (mat_mul)
38. Matrix Determinant (ma

In [ ]:
from tkinter import *
import math
import tkinter.messagebox

In [ ]:
root = Tk()

# sets the name on the top of the gui
root.title("Scientific Calculator") 

# sets the background color of the calculator 
# as white
root.configure(background = 'black') 

# fixed the width and height of the gui,
# hence can't be expanded/stretched
root.resizable(width=False, height=False)

# sets the geometry
root.geometry("480x568+450+90") 

# holds the buttons in the calculator,
# act as a container for numbers and operators
calc = Frame(root)

# create a grid like pattern of the frame 
# i.e buttons
calc.grid()


In [ ]:
class Calc():
	def __init__(self):
		self.total = 0
		self.current = ''
		self.input_value = True
		self.check_sum = False
		self.op = ''
		self.result = False

	def numberEnter(self, num):
		self.result = False
		firstnum = txtDisplay.get()
		secondnum = str(num)
		if self.input_value:
			self.current = secondnum
			self.input_value = False
		else:
			if secondnum == '.':
				if secondnum in firstnum:
					return
			self.current = firstnum+secondnum
		self.display(self.current)

	def sum_of_total(self):
		self.result = True
		self.current = float(self.current)
		if self.check_sum == True:
			self.valid_function()
		else:
			self.total = float(txtDisplay.get())

	def display(self, value):
		txtDisplay.delete(0, END)
		txtDisplay.insert(0, value)

	def valid_function(self):
		if self.op == "add":
			self.total += self.current
		if self.op == "sub":
			self.total -= self.current
		if self.op == "multi":
			self.total *= self.current
		if self.op == "divide":
			self.total /= self.current
		if self.op == "mod":
			self.total %= self.current
		self.input_value = True
		self.check_sum = False
		self.display(self.total)

	def operation(self, op):
		self.current = float(self.current)
		if self.check_sum:
			self.valid_function()
		elif not self.result:
			self.total = self.current
			self.input_value = True
		self.check_sum = True
		self.op = op
		self.result = False

	def Clear_Entry(self):
		self.result = False
		self.current = "0"
		self.display(0)
		self.input_value = True

	def All_Clear_Entry(self):
		self.Clear_Entry()
		self.total = 0

	def pi(self):
		self.result = False
		self.current = math.pi
		self.display(self.current)

	def tau(self):
		self.result = False
		self.current = math.tau
		self.display(self.current)

	def e(self):
		self.result = False
		self.current = math.e
		self.display(self.current)

	def mathPM(self):
		self.result = False
		self.current = -(float(txtDisplay.get()))
		self.display(self.current)

	def squared(self):
		self.result = False
		self.current = math.sqrt(float(txtDisplay.get()))
		self.display(self.current)

	def cos(self):
		self.result = False
		self.current = math.cos(math.radians(float(txtDisplay.get())))
		self.display(self.current)

	def cosh(self):
		self.result = False
		self.current = math.cosh(math.radians(float(txtDisplay.get())))
		self.display(self.current)

	def tan(self):
		self.result = False
		self.current = math.tan(math.radians(float(txtDisplay.get())))
		self.display(self.current)

	def tanh(self):
		self.result = False
		self.current = math.tanh(math.radians(float(txtDisplay.get())))
		self.display(self.current)

	def sin(self):
		self.result = False
		self.current = math.sin(math.radians(float(txtDisplay.get())))
		self.display(self.current)

	def sinh(self):
		self.result = False
		self.current = math.sinh(math.radians(float(txtDisplay.get())))
		self.display(self.current)

	def log(self):
		self.result = False
		self.current = math.log(float(txtDisplay.get()))
		self.display(self.current)

	def exp(self):
		self.result = False
		self.current = math.exp(float(txtDisplay.get()))
		self.display(self.current)

	def acosh(self):
		self.result = False
		self.current = math.acosh(float(txtDisplay.get()))
		self.display(self.current)

	def asinh(self):
		self.result = False
		self.current = math.asinh(float(txtDisplay.get()))
		self.display(self.current)

	def expm1(self):
		self.result = False
		self.current = math.expm1(float(txtDisplay.get()))
		self.display(self.current)

	def lgamma(self):
		self.result = False
		self.current = math.lgamma(float(txtDisplay.get()))
		self.display(self.current)

	def degrees(self):
		self.result = False
		self.current = math.degrees(float(txtDisplay.get()))
		self.display(self.current)

	def log2(self):
		self.result = False
		self.current = math.log2(float(txtDisplay.get()))
		self.display(self.current)

	def log10(self):
		self.result = False
		self.current = math.log10(float(txtDisplay.get()))
		self.display(self.current)

	def log1p(self):
		self.result = False
		self.current = math.log1p(float(txtDisplay.get()))
		self.display(self.current)


added_value = Calc()


In [ ]:
txtDisplay = Entry(calc,
				font=('Helvetica', 20,
						'bold'),
				bg='black',
				fg='white',
				bd=30,
				width=28,
				justify=RIGHT)

txtDisplay.grid(row=0,
				column=0,
				columnspan=4,
				pady=1)

txtDisplay.insert(0, "0")


In [ ]:
# store all the numbers in a variable
numberpad = "789456123"

# here i will count the rows for placing buttons
# in grid
i = 0

# create an empty list to store
# each button with its particular specifications
btn = []

# j is in that range to place
# the button in that particular row
for j in range(2, 5):

		# k is in this range to place the
	# button in that particular column
	for k in range(3):
		btn.append(Button(calc,
						width=6,
						height=2,
						bg='black',
						fg='white',
						font=('Helvetica', 20, 'bold'),
						bd=4, text=numberpad[i]))

		# set buttons in row & column and
		# separate them with a padding of 1 unit
		btn[i].grid(row=j, column=k, pady=1)

		# put that number as a symbol on that button
		btn[i]["command"] = lambda x=numberpad[i]: added_value.numberEnter(x)
		i += 1


In [ ]:
btnClear = Button(calc, text=chr(67),
				width=6, height=2,
				bg='powder blue',
				font=('Helvetica', 20, 'bold'),
				bd=4,
				command=added_value.Clear_Entry).grid(
	row=1, column=0, pady=1)

btnAllClear = Button(calc, text=chr(67)+chr(69),
					width=6, height=2,
					bg='powder blue',
					font=('Helvetica',
						20, 'bold'), bd=4,
					command=added_value.All_Clear_Entry).grid(
	row=1, column=1, pady=1)

btnsq = Button(calc, text="\u221A", width=6,
			height=2, bg='powder blue',
			font=('Helvetica', 20, 'bold'),
			bd=4, command=added_value.squared).grid(
	row=1, column=2, pady=1)

btnAdd = Button(calc, text="+", width=6,
				height=2, bg='powder blue',
				font=('Helvetica', 20, 'bold'),
				bd=4, command=lambda: added_value.operation("add")
				).grid(row=1, column=3, pady=1)

btnSub = Button(calc, text="-", width=6,
				height=2, bg='powder blue',
				font=('Helvetica', 20, 'bold'),
				bd=4,
				command=lambda: added_value.operation("sub")
				).grid(row=2, column=3, pady=1)

btnMul = Button(calc, text="x", width=6, height=2,
				bg='powder blue',
				font=('Helvetica', 20, 'bold'),
				bd=4, command=lambda: added_value.operation("multi")
				).grid(row=3, column=3, pady=1)

btnDiv = Button(calc, text="/", width=6,
				height=2, bg='powder blue',
				font=('Helvetica', 20, 'bold'),
				bd=4, command=lambda: added_value.operation("divide")
				).grid(row=4, column=3, pady=1)

btnZero = Button(calc, text="0", width=6,
				height=2, bg='black', fg='white',
				font=('Helvetica', 20, 'bold'),
				bd=4, command=lambda: added_value.numberEnter(0)
				).grid(row=5, column=0, pady=1)

btnDot = Button(calc, text=".", width=6,
				height=2, bg='powder blue',
				font=('Helvetica', 20, 'bold'),
				bd=4, command=lambda: added_value.numberEnter(".")
				).grid(row=5, column=1, pady=1)
btnPM = Button(calc, text=chr(177), width=6,
			height=2, bg='powder blue',
			font=('Helvetica', 20, 'bold'),
			bd=4, command=added_value.mathPM
			).grid(row=5, column=2, pady=1)

btnEquals = Button(calc, text="=", width=6,
				height=2, bg='powder blue',
				font=('Helvetica', 20, 'bold'),
				bd=4, command=added_value.sum_of_total
				).grid(row=5, column=3, pady=1)
# ROW 1 :

btnPi = Button(calc, text="pi", width=6,
			height=2, bg='black', fg='white',
			font=('Helvetica', 20, 'bold'),
			bd=4, command=added_value.pi
			).grid(row=1, column=4, pady=1)

btnCos = Button(calc, text="Cos", width=6,
				height=2, bg='black', fg='white',
				font=('Helvetica', 20, 'bold'),
				bd=4, command=added_value.cos
				).grid(row=1, column=5, pady=1)

btntan = Button(calc, text="tan", width=6,
				height=2, bg='black', fg='white',
				font=('Helvetica', 20, 'bold'),
				bd=4, command=added_value.tan
				).grid(row=1, column=6, pady=1)

btnsin = Button(calc, text="sin", width=6,
				height=2, bg='black', fg='white',
				font=('Helvetica', 20, 'bold'),
				bd=4, command=added_value.sin
				).grid(row=1, column=7, pady=1)

# ROW 2 :

btn2Pi = Button(calc, text="2pi", width=6,
				height=2, bg='black', fg='white',
				font=('Helvetica', 20, 'bold'),
				bd=4, command=added_value.tau
				).grid(row=2, column=4, pady=1)

btnCosh = Button(calc, text="Cosh", width=6,
				height=2, bg='black', fg='white',
				font=('Helvetica', 20, 'bold'),
				bd=4, command=added_value.cosh
				).grid(row=2, column=5, pady=1)

btntanh = Button(calc, text="tanh", width=6,
				height=2, bg='black', fg='white',
				font=('Helvetica', 20, 'bold'),
				bd=4, command=added_value.tanh
				).grid(row=2, column=6, pady=1)

btnsinh = Button(calc, text="sinh", width=6,
				height=2, bg='black', fg='white',
				font=('Helvetica', 20, 'bold'),
				bd=4, command=added_value.sinh
				).grid(row=2, column=7, pady=1)

# ROW 3 :

btnlog = Button(calc, text="log", width=6,
				height=2, bg='black', fg='white',
				font=('Helvetica', 20, 'bold'),
				bd=4, command=added_value.log
				).grid(row=3, column=4, pady=1)

btnExp = Button(calc, text="exp", width=6,
				height=2, bg='black', fg='white',
				font=('Helvetica', 20, 'bold'),
				bd=4, command=added_value.exp
				).grid(row=3, column=5, pady=1)

btnMod = Button(calc, text="Mod", width=6,
				height=2, bg='black', fg='white',
				font=('Helvetica', 20, 'bold'),
				bd=4, command=lambda: added_value.operation("mod")
				).grid(row=3, column=6, pady=1)

btnE = Button(calc, text="e", width=6,
			height=2, bg='black', fg='white',
			font=('Helvetica', 20, 'bold'),
			bd=4, command=added_value.e
			).grid(row=3, column=7, pady=1)

# ROW 4 :

btnlog10 = Button(calc, text="log10", width=6,
				height=2, bg='black', fg='white',
				font=('Helvetica', 20, 'bold'),
				bd=4, command=added_value.log10
				).grid(row=4, column=4, pady=1)

btncos = Button(calc, text="log1p", width=6,
				height=2, bg='black', fg='white',
				font=('Helvetica', 20, 'bold'),
				bd=4, command=added_value.log1p
				).grid(row=4, column=5, pady=1)

btnexpm1 = Button(calc, text="expm1", width=6,
				height=2, bg='black', fg='white',
				font=('Helvetica', 20, 'bold'),
				bd=4, command=added_value.expm1
				).grid(row=4, column=6, pady=1)

btngamma = Button(calc, text="gamma", width=6,
				height=2, bg='black', fg='white',
				font=('Helvetica', 20, 'bold'),
				bd=4, command=added_value.lgamma
				).grid(row=4, column=7, pady=1)
# ROW 5 :

btnlog2 = Button(calc, text="log2", width=6,
				height=2, bg='black', fg='white',
				font=('Helvetica', 20, 'bold'),
				bd=4, command=added_value.log2
				).grid(row=5, column=4, pady=1)

btndeg = Button(calc, text="deg", width=6,
				height=2, bg='black', fg='white',
				font=('Helvetica', 20, 'bold'),
				bd=4, command=added_value.degrees
				).grid(row=5, column=5, pady=1)

btnacosh = Button(calc, text="acosh", width=6,
				height=2, bg='black', fg='white',
				font=('Helvetica', 20, 'bold'),
				bd=4, command=added_value.acosh
				).grid(row=5, column=6, pady=1)

btnasinh = Button(calc, text="asinh", width=6,
				height=2, bg='black', fg='white',
				font=('Helvetica', 20, 'bold'),
				bd=4, command=added_value.asinh
				).grid(row=5, column=7, pady=1)

lblDisplay = Label(calc, text="Scientific Calculator",
				font=('Helvetica', 30, 'bold'),
				bg='black', fg='white', justify=CENTER)
lblDisplay.grid(row=0, column=4, columnspan=4)


In [28]:
# use askyesno function to
# stop/continue the program execution 
def iExit(): 
	iExit = tkinter.messagebox.askyesno("Scientific Calculator",
										"Do you want to exit ?")
	if iExit>0:
		root.destroy()
		return

def Scientific():
	root.resizable(width=False, height=False)
	root.geometry("944x568+0+0")


def Standard():
	root.resizable(width=False, height=False)
	root.geometry("480x568+0+0")

menubar = Menu(calc)

# ManuBar 1 :

filemenu = Menu(menubar, tearoff = 0)
menubar.add_cascade(label = 'File', menu = filemenu)
filemenu.add_command(label = "Standard", command = Standard)
filemenu.add_command(label = "Scientific", command = Scientific)
filemenu.add_separator()
filemenu.add_command(label = "Exit", command = iExit)

# ManuBar 2 :

editmenu = Menu(menubar, tearoff = 0)
menubar.add_cascade(label = 'Edit', menu = editmenu)
editmenu.add_command(label = "Cut")
editmenu.add_command(label = "Copy")
editmenu.add_separator()
editmenu.add_command(label = "Paste")

root.config(menu=menubar)

root.mainloop()


TclError: can't invoke "menu" command: application has been destroyed