# Lecture 03의 데모

### Lecture 03의 데모에 대한 코드

참고자료: https://github.com/data-8/materials-sp22/blob/main/lec/lec04.ipynb

In [40]:
import os
from google.colab import drive

drive.mount('/content/gdrive')

%cd /content/gdrive/MyDrive/ITEC419-fa22/lec

Mounted at /content/gdrive
/content/gdrive/MyDrive/ITEC419-fa22/lec


In [38]:
from datascience import *
import numpy as np

## Numbers ##

In [ ]:
10*3

In [4]:
10/3

3.3333333333333335

In [5]:
10**3

1000

In [6]:
10**0.5

3.1622776601683795

In [8]:
# float(실수)형을 int(정수)형으로 변경가능하다.
int(10/4)

2

In [10]:
# int(정수)형을 float(실수)형으로 변경가능하다.
float(3)

3.0

## Strings ##

In [11]:
'Flavor'

'Flavor'

In [12]:
"Flavor"

'Flavor'

In [14]:
'straw' 'berry' # concatenation - colab에서만 되는듯

'strawberry'

In [15]:
'straw' + 'berry' # concatenation

'strawberry'

In [17]:
'Chirs' + ' ' + 'Paul'

'Chirs Paul'

In [19]:
x = 'straw'
y = 'berry'
x+y # 변수에 string 대입해서 concatenate 연산 가능

'strawberry'

In [20]:
x y # 앞에서는 중간에 공백만으로 됐는데 변수로해서 넣으면 안됨!!

SyntaxError: ignored

In [21]:
# 여기서는 단순한 곱하기가 아님
'ha' * 10

'hahahahahahahahahaha'

In [22]:
# 소수는 안됨!
'lo' * 5.5

TypeError: ignored

In [23]:
# String과 int형은 더해지지 않는다.
# 여기서는 숫자의 더하기로 기능한게 아니라 concatenate로 기능한것
# 구분 잘해야함
'ha' + 10

TypeError: ignored

In [24]:
# concatenate 기능을 하니까 뒤에 숫자를 string 변화시키면됨
'ha' + str(10)

'ha10'

In [26]:
# 문자를 다시 정수형으로 변환 가능
int('3')

3

In [28]:
int('3r') # 문자포함은 안됨

ValueError: ignored

In [29]:
# 실수형 string 들어있는걸 정수형으로 바꾸면 안됨
int('3.0')

ValueError: ignored

In [30]:
dot_oh =  '.0'
float('3'+dot_oh)

3.0

## Types ##

In [31]:
type(10)

int

In [32]:
a=10

In [34]:
# 변수에 담겨있는 것의 타입기준으로 나옴
type(a)

int

In [35]:
type('abc')

str

In [36]:
type(4.5)

float

In [41]:
type(Table.read_table('nba_salaries.csv'))

datascience.tables.Table

In [43]:
type(True)

bool

In [44]:
type(-5)

int

In [45]:
type(abs)

builtin_function_or_method

## Arrays ##

In [47]:
# numpy 모듈 안에 존재하는 array
# python에는 튜플, 리스트, 딕셔너리가 존재 Array는 없다.
# array를 만드는 함수 make_array()
first_four = make_array(1, 2, 3, 4)

In [48]:
first_four

array([1, 2, 3, 4])

In [49]:
type(first_four)

numpy.ndarray

In [50]:
first_four*2

array([2, 4, 6, 8])

In [51]:
first_four**2

array([ 1,  4,  9, 16])

In [52]:
first_four - 1

array([0, 1, 2, 3])

In [53]:
# 위에서 연산했다고 first_four가 바뀌는건 아님!
first_four

array([1, 2, 3, 4])

In [54]:
next_four = make_array(5,6,7,8)

In [56]:
# 항목 개수가 안맞으면 오류 생김
first_four + next_four

array([ 6,  8, 10, 12])

In [58]:
# 하지만 둘 중의 하나가 사이즈가1이면 자동으로 broadcast됨
test = make_array(1)
first_four+test

array([2, 3, 4, 5])

In [59]:
str_array = make_array('ha','he','ho')

In [61]:
# str 각각에 대해 4번 나올걸 기대했지만 그렇게는 안됨
str_array*4

UFuncTypeError: ignored

In [62]:
str_array +2

UFuncTypeError: ignored

In [63]:
str_array + 'test'

UFuncTypeError: ignored

In [64]:
# 인덱스를 활용하여 항목에 직접 접근 가능
next_four.item(0)

5

In [66]:
# array의 합 구하기: sum 함수 이용
sum(next_four)
np.sum(next_four)

26

In [69]:
# 그냥 average는 안됨
np.average(next_four)

6.5

In [70]:
# array 길이 반환
len(next_four)

4

## Columns of Tables are Arrays ##

In [72]:
nba = Table.read_table('nba_salaries.csv').where('season', 2020).drop('season')
nba.show(5)

In [73]:
warriors = nba.where('team', 'Golden State Warriors')
warriors.show(5)

In [75]:
warriors.select('salary')

salary
40231758
32742000
18539130
4464226
2177483
1964760
1897800
898310
898310
842327
... (3 rows omitted)

In [76]:
type(warriors.select('salary'))

datascience.tables.Table

In [78]:
# 위의 select문을 사용한 것과 차이를 확인
warriors.column('salary')

array([40231758, 32742000, 18539130,  4464226,  2177483,  1964760,
        1897800,   898310,   898310,   842327,   654469,   350189,   350189])

In [79]:
np.average(warriors.column('salary'))

8154688.538461538

In [80]:
suns = nba.where('team', 'Phoenix Suns')

In [82]:
# 테이블 행의 개수
suns.num_rows

19

In [83]:
# 테이블 열의 개수
suns.num_columns

5