# Working with NumPy arrays

In [1]:
import numpy as np
np.random.seed(1234567890)

In [2]:
x1 = np.random.randint(0,10, size=(3,4))

In [3]:
print(x1)

[[2 6 3 1]
 [9 9 4 0]
 [9 6 4 0]]


In [4]:
x1.ndim

2

In [5]:
x1.shape

(3, 4)

In [7]:
nRow, nCol = x1.shape
print("I have", nRow, "rows")
print("I have", nCol, "columns")

I have 3 rows
I have 4 columns


In [8]:
x1.size

12

In [10]:
x1.dtype

dtype('int64')

In [11]:
x1.astype(np.float).dtype

dtype('float64')

In [12]:
x1.dtype

dtype('int64')

In [13]:
x1.nbytes

96

In [14]:
x1.itemsize

8

## Surgery on the array

In [15]:
x2 = np.random.randint(5, size=10)
print(x2)

[3 3 1 4 0 3 1 2 3 1]


In [16]:
x2[1]

3

In [17]:
x2[2]

1

In [18]:
x2[0]

3

In [19]:
x2[-1]

1

In [20]:
x1

array([[2, 6, 3, 1],
       [9, 9, 4, 0],
       [9, 6, 4, 0]])

In [21]:
x1[0]

array([2, 6, 3, 1])

In [22]:
x1[0,0]

2

In [24]:
x1[:,0]

array([2, 9, 9])

In [25]:
x1[0,0]

2

In [28]:
x1[0,0] = 3.74
print(x1)

[[3 6 3 1]
 [9 9 4 0]
 [9 6 4 0]]


In [30]:
x1[0,0] = 'hello'

ValueError: invalid literal for int() with base 10: 'hello'

In [31]:
# slices of arrays
x2[:5] 

array([3, 3, 1, 4, 0])

In [32]:
x2[2:5]

array([1, 4, 0])

In [34]:
x2[1::2]

array([3, 4, 3, 2, 1])

In [35]:
# slices in 2d
x1

array([[3, 6, 3, 1],
       [9, 9, 4, 0],
       [9, 6, 4, 0]])

In [39]:
x1[1:,:]

array([[9, 9, 4, 0],
       [9, 6, 4, 0]])

In [41]:
x1[0,:]

array([3, 6, 3, 1])

In [42]:
x1[:,0]

array([3, 9, 9])

## no copy views of arrays

In [43]:
x1

array([[3, 6, 3, 1],
       [9, 9, 4, 0],
       [9, 6, 4, 0]])

In [44]:
x2 = x1[:,1:]
print(x2)

[[6 3 1]
 [9 4 0]
 [6 4 0]]


In [45]:
x2[-1,-1] = -99
print(x2)

[[  6   3   1]
 [  9   4   0]
 [  6   4 -99]]


In [47]:
x3 = x1[:,1:].copy()
x3[-1,-1] = 100
print(x3)

[[  6   3   1]
 [  9   4   0]
 [  6   4 100]]


In [48]:
print(x1)

[[  3   6   3   1]
 [  9   9   4   0]
 [  9   6   4 -99]]


In [49]:
x = np.arange(1,10)
print(x)

[1 2 3 4 5 6 7 8 9]


In [50]:
x.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [52]:
x.reshape(3,4)

ValueError: cannot reshape array of size 9 into shape (3,4)

In [53]:
y1 = np.arange(1,4)
y2 = np.arange(4,8)

In [54]:
print(y1)

[1 2 3]


In [55]:
print(y2)

[4 5 6 7]


In [56]:
np.concatenate([y1, y2])

array([1, 2, 3, 4, 5, 6, 7])

In [60]:
np.concatenate([y1,y2], axis=1)

AxisError: axis 1 is out of bounds for array of dimension 1

## Compute on arrays

In [61]:
x1 = np.arange(1,5)
x2 = np.ones(4)

In [62]:
print(x1)

[1 2 3 4]


In [63]:
print(x2)

[ 1.  1.  1.  1.]


In [64]:
x1 + x2

array([ 2.,  3.,  4.,  5.])

In [65]:
x1 - x2

array([ 0.,  1.,  2.,  3.])

In [66]:
x1 * x2

array([ 1.,  2.,  3.,  4.])

In [67]:
x1 / 2

array([ 0.5,  1. ,  1.5,  2. ])

In [68]:
x1 // 2

array([0, 1, 1, 2])

In [69]:
x1**2

array([ 1,  4,  9, 16])

In [70]:
x1 % 2

array([1, 0, 1, 0])

In [71]:
(x1 + 5)*x2

array([ 6.,  7.,  8.,  9.])

In [72]:
x1 + x2

array([ 2.,  3.,  4.,  5.])

In [73]:
np.add(x1, x2)

array([ 2.,  3.,  4.,  5.])

In [74]:
np.multiply(x1,10)

array([10, 20, 30, 40])

In [76]:
y1 = np.multiply(x1,10)
print(y1)

[10 20 30 40]


In [77]:
x1

array([1, 2, 3, 4])

In [78]:
np.multiply(x1,10, out=y2)
print(y2)

[10 20 30 40]


In [79]:
# why does lachlan like the out option?

big_array = np.random.randint(1,100, size = 1000000)

In [81]:
%%timeit
y1 = np.multiply(big_array, 10)

The slowest run took 6.18 times longer than the fastest. This could mean that an intermediate result is being cached.
1000 loops, best of 3: 998 µs per loop


In [86]:
y3 = np.zeros(big_array.size)


In [87]:
%%timeit
np.multiply(big_array, 10, out=y3)

The slowest run took 5.01 times longer than the fastest. This could mean that an intermediate result is being cached.
100 loops, best of 3: 1.88 ms per loop


In [88]:
## other useful stuff
x = np.arange(1,4)
print(x)

[1 2 3]


In [91]:
np.add.reduce(x)

6

In [92]:
np.add.accumulate(x)

array([1, 3, 6])

In [93]:
np.multiply.reduce(x)

6

In [94]:
np.multiply.accumulate(x)

array([1, 2, 6])