<a href="https://colab.research.google.com/github/diego40g/data_science_python/blob/numpy/29_especialMAtrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
A=np.zeros(shape=(2,2))
print(A)

[[0. 0.]
 [0. 0.]]


In [3]:
B=np.zeros(shape=(3,5))
print(B)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [4]:
C=np.ones(shape=(5,5))
print(C)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [5]:
I2=np.eye(2)
print(I2)

[[1. 0.]
 [0. 1.]]


In [6]:
I3=np.eye(3)
print(I3)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [7]:
I6=np.eye(6)
print(I6)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
