
<a href="https://colab.research.google.com/github/EbnerLautaro/Redes-Neuronales/blob/main/redes_neuronales_2024_guia_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Familiarizandose con **Numpy**

Referencias:
* https://www.datacamp.com/cheat-sheet/numpy-cheat-sheet-data-analysis-in-python
* https://towardsdatascience.com/a-cheat-sheet-on-generating-random-numbers-in-numpy-5fe95ec2286

## **Ejercicio 1)** Importando librerías

Importe las librerías `numpy` para operar con arrays, `scipy` para operar con algebra lineal y `matplotlib.pyplot` para graficar.

In [74]:
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt


## **Ejercicio 2)** Creando arrays



**1)** Cree un array de enteros `a` a partir de la lista `[1,2,3]`.


In [75]:
a = np.array([1, 2, 3])


**2)** Cree un array bidimensional de flotantes `b` a partir de la lista de listas `[[1.5,2,3],[4,5,6]]`.

In [76]:
b = np.array([[1.5, 2, 3], [4, 5, 6]], dtype=np.float32)


**3)** Cree un array tridimensional de flotantes `c` a partir de la lista de listas `[[[1.5,2,3],[4,5,6]],[[3,2,1],[4,5,6]]]`.

In [77]:
c = np.array([[[[1.5, 2, 3], [4, 5, 6]], [[3, 2, 1], [4, 5, 6]]]], dtype=np.float32)


## **Ejercicio 3)** Inicializando arrays



**1)** Utilice `np.zeros` para crear un array bidimensional de flotantes incializados a `0.0`, y de dimensiones de tamaños `(3,4)`.



In [78]:
# 3.1)
a = np.zeros((3, 4), dtype=np.float32)


**2)** Utilice `np.ones` para crear un array tridimensional de enteros inicializados a `1`, y de dimensiones `(2,3,4)`.



In [79]:
# 3.2)
np.ones((2, 3, 4), dtype=np.int32)


array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int32)

**3)** Utilice `np.arange` para crear un array `d` de valores enteros equiespaciados de a `5` entre `10` y `25`.



In [80]:
# 3.3)
d = np.arange(start=10, stop=26, step=5)


**4)** Utilice `np.linspace` para crear un array de `9` valores flotantes equiespaciados entre `0.0` y `9.0`.



In [81]:
# 3.4)
np.linspace(start=0.0, stop=9.0, num=9)


array([0.   , 1.125, 2.25 , 3.375, 4.5  , 5.625, 6.75 , 7.875, 9.   ])

**5)** Utilice `np.full` para crear un array bidimensional llamado `e` de entradas iguales a `7`, y de dimesiones `(2,2)`.



In [82]:
# 3.5)
e = np.full((2, 2), 7)


**6)** Utilice `np.eye` para crear una matriz identidad llamada `f` de dimensiones 2x2.



In [83]:
# 3.6)
f = np.eye(N=2, M=2)


**7)** Utilice `np.random.random` para crear un array bidimensional de dimensiones 2x2 inicializado con valores aleatorios uniformemente sorteados del intervalo $[0,1]$.



In [84]:
# 3.7)
np.random.random((2, 2))


array([[0.53508355, 0.00542317],
       [0.85738391, 0.82367701]])

**8)** Utilice `np.empty` para crear un array bidimensional sin inicializar y de dimensiones `(3,2)`.


In [85]:
# 3.8)
np.empty((3, 2))


array([[2.00000047e+00, 5.12000123e+02],
       [8.19200197e+03, 2.00000047e+00],
       [5.12000123e+02, 8.19200197e+03]])

## **Ejercicio 4)** Inspeccionando arrays

Considere los arrays de los ejercicios 2) y 3).



**1)** Utilizando `.shape`, determine cuales son las dimensiones del array `a`.



In [86]:
# 4.1)
a.shape


(3, 4)

**2)** Utilizando la función `len()`, determine el *largo* del array `a`.



In [87]:
# 4.2)
len(a)


3

**3)** Utilizando `.ndim`, determine el número de dimensiones del array `b`.



In [88]:
# 4.3)
b.ndim


2

**4)** Utilizando `.size`, determine el número de entradas que tienen `e`.



In [89]:
# 4.4)
e.size


4

**5)** Utilizando `.dtype`, determine el tipo de los datos contenidos por el array `b`.



In [90]:
# 4.5)
b.dtype


dtype('float32')

**6)** Utilizando `.dtype.name`, determine el nombre del tipo de los datos contenidos por el array `b`.



In [91]:
# 4.6)
b.dtype.name


'float32'

**7)** Utilizando `.astype`, convierta el array `b` a un array de tipo `int`.



In [92]:
# 4.7)
b.astype(int)


array([[1, 2, 3],
       [4, 5, 6]])

## **Ejercicio 5)** Tipos de datos

**1)** Cree un array que contenga elementos de tipo `np.int64`.

In [93]:
np.array([], dtype=np.int64)


array([], dtype=int64)

**2)** Cree un array que contenga elementos de tipo `np.float32`.

In [94]:
np.array([], dtype=np.float32)


array([], dtype=float32)

**3)** Cree un array que contenga elementos de tipo `np.complex128`.

In [95]:
np.array([], dtype=np.complex128)


array([], dtype=complex128)

**4)** Cree un array que contenga elementos de tipo `np.bool`.

In [96]:
np.array([], dtype=np.bool)


array([], dtype=bool)

**5)** Cree un array que contenga elementos de tipo `np.object`.

In [97]:
np.array([], dtype=np.object_)


array([], dtype=object)

**6)** Cree un array que contenga elementos de tipo `np.string_`.

In [98]:
np.array([], dtype=np.str_)


array([], dtype='<U1')

**7)** Cree un array que contenga elementos de tipo `np.unicode_`.

In [99]:
np.array([], dtype=np.str_)


array([], dtype='<U1')

## **Ejercicio 6)** Operando sobre arrays

Considere los arrays de los ejercicios 2) y 3).

**Ayuda:** use https://numpy.org/doc/stable/reference/generated/numpy.dot.html

In [100]:
# no tengo idea a que arrays se refiere

a = np.array([1, 2, 3])
b = np.array([[1.5, 2, 3], [4, 5, 6]], dtype=np.float32)


**1)** Calcule la resta `a-b` de los arrays `a` y `b` y almacene el resultado en un array `g`.

In [101]:
g = a - b
g, type(g)


(array([[-0.5,  0. ,  0. ],
        [-3. , -3. , -3. ]]),
 numpy.ndarray)


**2)** Notar que `a` y `b` poseen diferentes dimensiones (i.e., `a.shape` es distinto de `b.shape`) y, sin embargo, en el inciso anterior numpy computa la suma `a+b`. Explique lo que ocurre.


In [102]:
print(f"{a+b = }")
print("\nnotar que se retorna la union de lo siguiente: \n")
print(f"{a+b[0] = }")
print(f"{a+b[1] = }")


a+b = array([[2.5, 4. , 6. ],
       [5. , 7. , 9. ]])

notar que se retorna la union de lo siguiente: 

a+b[0] = array([2.5, 4. , 6. ])
a+b[1] = array([5., 7., 9.])


**3)** Compare el anterior resultado con el uso de `np.substract`.

In [103]:
# es lo mismo
np.subtract(a, b)


array([[-0.5,  0. ,  0. ],
       [-3. , -3. , -3. ]])

**4)** Calcule la suma `a-b` de los arrays `a` y `b`.

In [104]:
a + b


array([[2.5, 4. , 6. ],
       [5. , 7. , 9. ]])

**5)** Compare el anterior resultado con el uso de `np.add`.

In [105]:
# es lo mismo
np.add(a, b)


array([[2.5, 4. , 6. ],
       [5. , 7. , 9. ]])

**6)** Calcule la división punto a punto  `a/b` de `a` y `b`.

In [106]:
a / b


array([[0.66666667, 1.        , 1.        ],
       [0.25      , 0.4       , 0.5       ]])

**7)** Compare el anterior resultado con el uso de `np.divide`.

In [107]:
np.divide(a, b)


array([[0.66666667, 1.        , 1.        ],
       [0.25      , 0.4       , 0.5       ]])

**8)** Calcule la multiplicación punto a punto  `a*b` de `a` y `b`.

In [108]:
a * b


array([[ 1.5,  4. ,  9. ],
       [ 4. , 10. , 18. ]])

**9)** Compare el anterior resultado con el uso de `np.multiply`.


In [109]:
np.multiply(a, b)


array([[ 1.5,  4. ,  9. ],
       [ 4. , 10. , 18. ]])


**10)** Calcule la exponencial punto a punto  `np.exp(b)` de `b`.

In [110]:
# calcula la exponencial de todos los elementos de b, es decir e^b[i][j]
np.exp(b)


array([[  4.481689 ,   7.3890557,  20.085537 ],
       [ 54.59815  , 148.41316  , 403.42877  ]], dtype=float32)


**11)** Calcule la raíz cuadrada punto a punto  `np.sqrt(b)` de `b`.

In [111]:
# idem anterior
np.sqrt(b)


array([[1.2247449, 1.4142135, 1.7320508],
       [2.       , 2.236068 , 2.4494898]], dtype=float32)


**12)** Calcule el seno punto a punto  `np.sin(a)` de `a`.

In [112]:
np.sin(a)


array([0.84147098, 0.90929743, 0.14112001])


**13)** Calcule el coseno punto a punto  `np.cos(b)` de `b`.

In [113]:
np.cos(b)


array([[ 0.0707372 , -0.4161468 , -0.9899925 ],
       [-0.6536436 ,  0.28366217,  0.96017027]], dtype=float32)


**14)** Calcule el logaritmo natural punto a punto  `np.log(a)` de `a`.

In [114]:
np.log(a)


array([0.        , 0.69314718, 1.09861229])


**15)** Calcule el producto punto `e.dot(f)` entre `e` y `f`.

In [115]:
print(f"{e = }\n")
print(f"{f = }\n")

print(f"{e.dot(f) = }\n")


e = array([[7, 7],
       [7, 7]])

f = array([[1., 0.],
       [0., 1.]])

e.dot(f) = array([[7., 7.],
       [7., 7.]])




**16)** Compare el anterior resultado con el uso de `np.dot`.

In [116]:
# es lo mismo, lo que hace es popular automaticamente el primer argumento
np.dot(e, f)


array([[7., 7.],
       [7., 7.]])


**17)** Explique las diferentes opciones que puede adoptar el producto punto de numpy según el número de dimensiones que tengan sus factores.

## **Ejercicio 7)** Comparando arrays


**1)** Use `==` para realizar una compación punto a punto de los arrays `a` y `b`.

In [117]:
a == b


array([[False,  True,  True],
       [False, False, False]])

**2)** Use `<` para realizar una comparación punto a punto del array `b` con el escalar `2`.

In [118]:
b < 2


array([[ True, False, False],
       [False, False, False]])

**3)** Use `np.array_equal(a,b)` para determinar si `a` y `b` son iguales como arrays.

In [119]:
np.array_equal(a, b)


False

## **Ejercicio 8)** *Copiando* arrays


**1)** Use `.view()` para crear una vista llamada `h` del array `a`.

In [120]:
h = a.view()



**2)** Use `.copy()` para crear una copia del array `a`.

In [121]:
a.copy()


array([1, 2, 3])

## **Ejercicio 9)** Ordenado



**1)** Use `.sort()` para ordenar los elementos de `a`.


In [122]:
a.sort()
a


array([1, 2, 3])


**2)** Ordene los elementos de `c` a lo largo del eje `0`. Explique.

In [123]:
c.sort()
c


array([[[[1.5, 2. , 3. ],
         [4. , 5. , 6. ]],

        [[1. , 2. , 3. ],
         [4. , 5. , 6. ]]]], dtype=float32)

## **Ejercicio 10)** Indexado y *slicing* (rebanado) de arrays



**1)** Seleccione el segundo elemento de `a`.


In [124]:
a[2]


np.int64(3)

**2)** Seleccione el elemento en la fila 1 y columna 2 de `b`.
Si `n` y `m` son enteros, luego `[n:m]` indica el rango de índices que van desde `n` hasta `m-1`.



In [125]:
b[1][2]


np.float32(6.0)

**3)** Seleccione el rango `[0:2]` de elementos de `a`.



In [126]:
a[0:2]


array([1, 2])

**4)** Seleccione los elementos de `b` en el rango `[0:2]` de filas y la columna `1`.



In [127]:
b[0:2][1]


array([4., 5., 6.], dtype=float32)


**5)** Seleccione todos los elementos de `b` que esten en el rango de filas `[0:1]` y el rango completo de columnas.


In [128]:
b[0:1]


array([[1.5, 2. , 3. ]], dtype=float32)

**6)** Uso de *elipsis*. Seleccione los elementos de `c` indexados por `[1,...]`. Es esto lo mismo que lo indexado por `[1,:,:]`?

Si `n`, `m` y `s` son enteros, luego `[n:m:s]` indica el rango de índices que van desde `n` hasta `m-1` saltando de a `s` elementos.


In [171]:
c[0] == c[0::]
# list[start:stop:step]


array([[[[ True,  True,  True],
         [ True,  True,  True]],

        [[ True,  True,  True],
         [ True,  True,  True]]]])

**7)** Utilice lo mencionado anteriormente para acceder a los elementos de `a` de forma invertida.



In [170]:
a[::-1]


array([3, 2, 1])

**8)** Seleccione los elementos de `a` que sean menores que dos.



In [172]:
a[a < 2]


array([1])

**9)** Seleccione los elementos de `b` indicados por la lista de índices `[(1,0),(0,1),(1,2),(0,0)]` utilizando, correspondientemente, una lista de indices fila y una lista de índices columna.

In [187]:
indices_filas = [1, 0, 1, 0]
indices_columnas = [0, 1, 2, 0]
b[indices_filas, indices_columnas]


array([4. , 2. , 6. , 1.5], dtype=float32)

**10)** Utilizando una lista de indices fila, seleccione las filas `1,0,1,0` de `b`, y luego, para cada selección anterior, utilice una lista de índices columna para seleccionar las columnas `0,1,2,0`.

In [188]:
indices_filas = [1, 0, 1, 0]
indices_columnas = [0, 1, 2, 0]
b[indices_filas][:, indices_columnas]


array([[4. , 5. , 6. , 4. ],
       [1.5, 2. , 3. , 1.5],
       [4. , 5. , 6. , 4. ],
       [1.5, 2. , 3. , 1.5]], dtype=float32)

## **Ejercicio 11)** transposición

**1)** Use `np.transpose()` para calcular la traspuesta del array `b`, y asignarlo a una variable `i`.



In [191]:
i = np.transpose(b)


**2)** Use `.T` para acceder a `i` de forma traspuesta. Es esta forma traspuesta igual a `b`?

In [193]:
i.T == b


array([[ True,  True,  True],
       [ True,  True,  True]])

## **Ejercicio 12)** Redimensionado

**1)** Use `.ravel()` para *achatar* el array `b`.



In [197]:
b.ravel()


array([1.5, 2. , 3. , 4. , 5. , 6. ], dtype=float32)

**2)** Use `.reshape()` para redimensionar el array `g` de manera que adquiera dimensiones especificadas por la tupla `(3,-2)`.




In [209]:
g.reshape(3, -2)


array([[-0.5,  0. ],
       [ 0. , -3. ],
       [-3. , -3. ]])

**3)** Que indica aquí el signo negativo del segundo índice?

In [210]:
g.reshape(3, -2) == g.reshape(3, 2)


array([[ True,  True],
       [ True,  True],
       [ True,  True]])

## **Ejercicio 13)** Agregando y quitando elementos

**1)** Use `np.resize()` para crear a partir del array `h` un nuevo array de tamaño y dimensiones diferentes indicadas por `(2,6)`.



In [219]:
np.resize(h, (2, 6))


**2)** Use `np.append()` para crear un nuevo array que agrege los elementos de `g` al final de los elementos de `h`. Notar que `h` y `g` tienen diferentes dimensiones. Cómo resuelve `numpy` esta cuestión?



In [220]:
np.append(h, g)
# los agrega al final


array([ 1. ,  2. ,  3. , -0.5,  0. ,  0. , -3. , -3. , -3. ])

**3)** Use `np.insert()` para crear una copia de `a` en donde se inserta el número `5` en la posición indexada por `1`.



In [224]:
np.insert(a, 1, 5)


array([1, 5, 2, 3])

**4)** Use `np.delete()` para eliminar los elementos de `a` indicados por la lista de índices `[1]`.

In [225]:
np.delete(a, [1])


array([1, 3])

## **Ejercicio 14)** Combinando arrays


**a)** Use `np.concatenate()` para concatenar los arrays `a` y `d`.



In [228]:
np.concatenate((a, d))


array([ 1,  2,  3, 10, 15, 20, 25])

**b)** Use `np.vstack()` para apilar verticalmente los arrays `a` y `b`.



In [234]:
np.vstack((a, b))


array([[1. , 2. , 3. ],
       [1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

**c)** Use `np.row_stack()` para apilar verticalmente los arrays `e` y `f`.



**d)** Use `np.hstack()` para apilar horizontalmente los arrays `e` y `f`.



**e)** Use `np.column_stack()` para apilar horizontalmente los arrays `a` y `d`.

## **Ejercicio 15)** *Separando* arrays



**a)** Use `np.hsplit()` para separar horizontalmente el array `a` en 3 partes.



**b)** Use `np.vsplit()` para separar verticalmente el array `c` en 2 partes.



**c)** Cree el array `z` dado por

        [[1, 2, 3, 4],
        [2, 0, 0, 2],
        [3, 1, 1, 0]]

y sepárelo en dos partes a lo largo del eje `1`.

## **Ejercicio 16)** Generando números aleatorios

**1)** Use `np.random.random()` para generar un número aleatorio de tipo float64 a partir de la distribución uniforme en $[0,1]$.



**2)** Use `np.random.random()` para crear un array de 10 números aleatorios de tipo float64 generados a partir de la distribución uniforme en $[0,1]$.



**3)** Use `np.random.random()` para crear un array dos dimensional de dimensiones `(3,4)` conteniendo números aleatorios de tipo float64 generados a partir de la distribución uniforme en $[0,1]$.



**4)** Use `np.random.randn()` para generar un número aleatorio de tipo float64 a partir de la distribución normal centrada en $\mu=0$ y de varianza $\sigma^2=1$.



**5)** Use `np.random.randn()` para generar un número aleatorio de tipo float64 a partir de la distribución normal centrada en $\mu=5$ y de varianza $\sigma^2=9$.



**6)** Use `np.random.randn()` para generar un array de dimensiones `(3,2,3)` conteniendo números aleatorios de tipo float64 generados a partir de la distribución normal centrada en $\mu=-1$ y de varianza $\sigma^2=2$.



**7)** Use `np.random.randint()` para generar un número aleatorio de tipo int64 a partir de la distribución uniforme en $\{0,1,2,3\}$.



**8)** Use `np.random.randint()` para generar un número aleatorio de tipo int64 a partir de la distribución uniforme en $\{10,11,12,13,14,15\}$.



**9)** Use `np.random.randint()` para generar un array de dimensiones `(3,2,3)` conteniendo números aleatorios de tipo int64 generados a partir de la distribución uniforme en $\{0,1\}$.



**10)** Use `np.random.choice()` para seleccionar uniformemente al azar un elemento de la lista `["perro","gato","loro","caballo","vaca"]`.



**11)** Use `np.random.choice()` para crear un array de dimensiones `(3,3)` con selecciones generadas uniformemente al azar de los elementos de la lista `["perro","gato","loro","caballo","vaca"]`.



**12)** Use `np.random.choice()` para crear un array de dimensiones `(3,3,3)` con selecciones generadas al azar de los elementos de la lista `["perro","gato","loro","caballo","vaca"]` de acuerdo a la correspondiente lista de probabilidades `[8/16,4/16,2/16,1/16,1/16]`.



**13)** Use `np.random.permutation()` generar una permutación, seleccionada uniformemente al azar una de las `n!` permutaciones que existen de un conjunto de `n` elementos, de una la lista de números entre `0` y `n-1` para `n=10` denominada `lista_n`.

**14)** Repita lo anterior usando `np.random.shuffle()` para aleatorizar la lista `lista_n` *in situ*.