# Numpy hands-on


# Problem statement:

numpy library package from python is one of the most  useful while conduction any statistical analysis in data science. 
Familiarize yourself with the nitty gritties of the variour modules that it comes with.


# Tasks to be performed:
    
1. Create a array with numpy.array module and with a date type integer and float

In [2]:
import numpy as np

In [2]:
arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [3]:
arr1.dtype

dtype('int32')

In [5]:
arr2 = np.array([1,2,3,4,5], dtype = 'float')
arr2

array([1., 2., 3., 4., 5.])

In [6]:
arr2.dtype

dtype('float64')

# 2. Create numpy arrays that have zero, one, two, three, Four dimensions respectively.
# Also,
# print the shape and dimensions of the numpy arrays created above.

In [5]:
#zero
ze = np.array(5)   #scaler
ze

array(5)

In [6]:
ze.ndim

0

In [7]:
# one d
oned = np.array([2,3,4,5])
oned

array([2, 3, 4, 5])

In [8]:
oned.ndim

1

In [11]:
#two
twod = np.array([[1,2,3,4],[5,6,7,8]])
twod

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [10]:
twod.ndim

2

In [12]:
#three d
threed = np.array([[[1,2,3,4],[1,2,3,4]]])
threed

array([[[1, 2, 3, 4],
        [1, 2, 3, 4]]])

In [16]:
threed.shape

(1, 2, 4)

In [13]:

threed.ndim

3

In [14]:
fourd = np.array([[[[1,2,3,4],[1,2,3,4],[1,2,3,4]]]])
fourd

array([[[[1, 2, 3, 4],
         [1, 2, 3, 4],
         [1, 2, 3, 4]]]])

In [15]:
fourd.ndim

4

In [17]:
fourd.shape

(1, 1, 3, 4)

# 3. Create a 2x3, 3x3, and 4x4 identity matrix using numpy

In [9]:
identity_matrix = np.eye(3,3)
identity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
# another way
identity_matrix = np.eye(3)  # correct way
identity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
ii = np.identity(2)
ii

array([[1., 0.],
       [0., 1.]])

In [13]:
ii = np.identity(3,dtype='int')
ii

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [14]:
it = np.identity(4,dtype='int')
it

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

# 4. Create a numpy array with shape 2x5 that has all the elements as zero.

In [15]:
a1 = np.zeros([2,5])
a1

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
a1 = np.zeros([2,5],dtype='int')
a1

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

# 5. Create a numpy array that has the shape 3x5 and all the elements are 5

In [17]:
a2 = np.full((3,5), 5, dtype = int)
a2

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

# 6. Create a numpy array with random intergers in the range 0-100, and sample size should be 25

In [21]:
rr = np.random.randint(0,101,size=25)
rr

array([22, 18, 99,  9, 87, 83, 81,  5, 77, 68, 90, 88, 34, 91, 30, 88, 98,
       57, 97, 76, 68, 64, 32, 90, 14])

In [19]:
len(rr)

25

# 7. Create a numpy array with a shape 3x3 that has all elements as 1

In [23]:
s = np.ones((2,3), dtype='int')
s

array([[1, 1, 1],
       [1, 1, 1]])

# 8. Create a numpy array in the shape 2x3 with random integers in the range 0-100.

# Reshape the array in the shape 3x2 and print the updated shape of the resultant array.

In [27]:
Rs = np.random.randint(0,101,(2,3))
Rs

array([[13, 88, 16],
       [59, 42, 32]])

In [28]:
rss = Rs.reshape(3,2)
rss

array([[13, 88],
       [16, 59],
       [42, 32]])

# 9. 1.Create a random array, with the range 0-1000, with a size 50 and step 
2. Perform thefollowing operations on the same.


a. Print the first ten elements of the array.
b. Print the last ten elements of the array
c. Print the elements from the indexes 10-25
d. Print the element at the index 22
e. Print the array using negative indexing.
f. Print the last ten elements of the array, using negative indexing.

In [34]:
np.random.seed()       # to save the random number
arr1 = np.random.randint(0,1001,size=50)
arr1

array([955, 739, 252, 597, 385, 497, 363, 847, 308, 265, 599,  84, 331,
       853, 394, 552, 457,  51, 858,  99, 839, 711,  64, 443, 567, 671,
       826, 912, 626, 619, 940, 913, 656, 541, 874, 640, 542, 150, 189,
       522, 114, 604, 233, 625, 277, 213, 276, 623, 916, 949])

In [33]:
len(arr1)

50

In [37]:
#a
arr1[:10]

array([955, 739, 252, 597, 385, 497, 363, 847, 308, 265])

In [38]:
#b
arr1[40:]

array([114, 604, 233, 625, 277, 213, 276, 623, 916, 949])

In [39]:
#c
arr1[10:26]

array([599,  84, 331, 853, 394, 552, 457,  51, 858,  99, 839, 711,  64,
       443, 567, 671])

In [40]:
#d
arr1[22]

64

In [43]:
#e
arr1[-50:]

array([955, 739, 252, 597, 385, 497, 363, 847, 308, 265, 599,  84, 331,
       853, 394, 552, 457,  51, 858,  99, 839, 711,  64, 443, 567, 671,
       826, 912, 626, 619, 940, 913, 656, 541, 874, 640, 542, 150, 189,
       522, 114, 604, 233, 625, 277, 213, 276, 623, 916, 949])

In [45]:
#f
arr1[-30:-6]

array([839, 711,  64, 443, 567, 671, 826, 912, 626, 619, 940, 913, 656,
       541, 874, 640, 542, 150, 189, 522, 114, 604, 233, 625])

## 10. Given a numpy array that has values = [1,2,3,4,5]. Perform the following operations.
a. Insert the element 6 at the end of the array.
b. Insert the element 10 at the beginning of the array.
c. Insert the element 30, before 4.
d. Update the element 5 as 50.
e. Delete the element 50 in the updated array.
f. Create a function to search for the element 30.
g. Sort the array in ascending order.

In [46]:
a1 = np.array([1,2,3,4,5])
a1

array([1, 2, 3, 4, 5])

In [48]:
#a
a1 = np.append(a1,6)
a1

array([1, 2, 3, 4, 5, 6])

In [49]:
#b
a1 = np.insert(a1, 0, 10)
a1

array([10,  1,  2,  3,  4,  5,  6])

In [50]:
#c
a1 = np.insert(a1, 4, 30)
a1

array([10,  1,  2,  3, 30,  4,  5,  6])

In [51]:
#d
a1[6]=50

In [52]:
a1

array([10,  1,  2,  3, 30,  4, 50,  6])

In [53]:
#e
a1 = np.delete(a1,6)

In [54]:
a1

array([10,  1,  2,  3, 30,  4,  6])

In [55]:
#f
def find_30(a1):
    for i in range(len(a1)):
        if a1[i]==30:
            print(i)

In [56]:
find_30(a1)

4


In [58]:
np.where(a1==30)

(array([4], dtype=int64),)

In [59]:
#g
np.sort(a1)

array([ 1,  2,  3,  4,  6, 10, 30])

In [60]:
np.sort(a1)[::-1]

array([30, 10,  6,  4,  3,  2,  1])