# **CLASS 24: NUMPY + DATA VISUALIZATION: 13 AUGUST 2022**

NUMPY: NUMERICAL PYTHON
We are going to use Numpy in Machine Learning, Deep Learning and Computer Vision because Computer understands numbers. There are lot of functions (2000+ converted from MATLAB) inside numpy but majorly we will use 10-20 functions only.

In [1]:
import numpy as np

In [2]:
l = [1,2,3,4,5,6]

In [3]:
a1 = np.array(l) #1 Dimension

In [4]:
l1 = [4,5,6,7,"sudh",34.565,True]  #Converted everything into string automatically. String occupies higher space than boolean,integer or float values. 
#U32 is internal representation of numpy array: 32 bits, 16 bits, 64 bits etc.
np.array(l1)

array(['4', '5', '6', '7', 'sudh', '34.565', 'True'], dtype='<U32')

In [5]:
a2 = np.array([[1,2,3],[4,5,6]]) #2 Dimensional Array:  

In [6]:
a3 = np.array([[[1,2,3],[4,5,6],[7,8,9]]]) 

In [7]:
#Dimensions of Array: How much axes is needed for data to be represented: When we perform data manipulation/computation, these dimensions will become important (Matrix Multiplication etc)
print(a1.ndim) #One Axis needed to represent this entire data point
print(a2.ndim) #Two Axes needed to represent this entire data point
print(a3.ndim) #Three Axes needed to represent this entire data point

1
2
3


In [8]:
#Size always tells us number of elements in the array
print(a1.size)
print(a2.size)
print(a3.size)

6
6
9


In [9]:
#Shape gives rows and columns
print(a1.shape) 
print(a2.shape) #2 Rows and 3 Columns
print(a3.shape) #3 Rows and 3 Columns   #We read as we have 3 cross 3 and have one such matrice (z Axis Depth,Rows,Columns)

(6,)
(2, 3)
(1, 3, 3)


In [10]:
#Generating Random Numbers between 2 and 4
print(np.random.randint(2,5))
#Generating Random Numbers between 2 and 49
print(np.random.randint(2,50))
#Generating Multiple Random Numbers
print(np.random.randint(2,50,(3,4))) #3 Rows and 4 Columns
#Generating Multiple Random Numbers
print(np.random.randint(2,50,(2,3,4))) #3 Rows and 4 Columns and 2 such matrices
#Images are actually 3D Arrays

4
18
[[18 44 32 42]
 [ 3 15 17 45]
 [22  3 17 41]]
[[[10 19 28 13]
  [42  9  7 41]
  [11 42 22 13]]

 [[34 13 39 17]
  [36  9 29  8]
  [ 7 43 48 48]]]


In [11]:
#Decimals also: Random Function is used for Data Normalization
np.random.rand(2,3)

array([[0.42241536, 0.10727608, 0.95272458],
       [0.9213096 , 0.14611128, 0.91763219]])

In [12]:
#Normal Distribtuion 
a4 = np.random.randn(4,4)

In [13]:
#Changing Shape of Data (In Images, we crop the image)
#a4.reshape(3,4) #Error because this will accomodate 12 dataset points but we have 16 dataset points
b1 = a4.reshape(2,8) #2 rows and 8 columns
b2 = a4.reshape(8,2) #8 rows and 2 columns
b3 = a4.reshape(1,16) #1 row and 16 columns
b4 = a4.reshape(16,1) #16 columns and 1 row

print(b1)
print(b2)
print(b3)
print(b4)
      


[[ 4.99246327e-01  1.25963244e-01  3.14997957e+00 -8.50899753e-01
  -6.05251587e-01 -1.34775902e+00 -5.83584254e-01 -7.57769014e-01]
 [-3.79479337e-01  8.74568929e-01 -1.17371048e-01 -6.51601623e-01
   1.05962110e+00 -1.49936376e+00 -1.76574632e-03  9.76555282e-01]]
[[ 4.99246327e-01  1.25963244e-01]
 [ 3.14997957e+00 -8.50899753e-01]
 [-6.05251587e-01 -1.34775902e+00]
 [-5.83584254e-01 -7.57769014e-01]
 [-3.79479337e-01  8.74568929e-01]
 [-1.17371048e-01 -6.51601623e-01]
 [ 1.05962110e+00 -1.49936376e+00]
 [-1.76574632e-03  9.76555282e-01]]
[[ 4.99246327e-01  1.25963244e-01  3.14997957e+00 -8.50899753e-01
  -6.05251587e-01 -1.34775902e+00 -5.83584254e-01 -7.57769014e-01
  -3.79479337e-01  8.74568929e-01 -1.17371048e-01 -6.51601623e-01
   1.05962110e+00 -1.49936376e+00 -1.76574632e-03  9.76555282e-01]]
[[ 4.99246327e-01]
 [ 1.25963244e-01]
 [ 3.14997957e+00]
 [-8.50899753e-01]
 [-6.05251587e-01]
 [-1.34775902e+00]
 [-5.83584254e-01]
 [-7.57769014e-01]
 [-3.79479337e-01]
 [ 8.74568929e-

In [14]:
 a4.reshape(2,-1) #Since 2 is a factor of 16, -1 or any negative number means that it will automatically detect the other factor which is 8 in this case

array([[ 4.99246327e-01,  1.25963244e-01,  3.14997957e+00,
        -8.50899753e-01, -6.05251587e-01, -1.34775902e+00,
        -5.83584254e-01, -7.57769014e-01],
       [-3.79479337e-01,  8.74568929e-01, -1.17371048e-01,
        -6.51601623e-01,  1.05962110e+00, -1.49936376e+00,
        -1.76574632e-03,  9.76555282e-01]])

In [15]:
#3 Dimensions
a4.reshape(2,2,4)

array([[[ 4.99246327e-01,  1.25963244e-01,  3.14997957e+00,
         -8.50899753e-01],
        [-6.05251587e-01, -1.34775902e+00, -5.83584254e-01,
         -7.57769014e-01]],

       [[-3.79479337e-01,  8.74568929e-01, -1.17371048e-01,
         -6.51601623e-01],
        [ 1.05962110e+00, -1.49936376e+00, -1.76574632e-03,
          9.76555282e-01]]])

In [16]:
a4.reshape(1,1,1,1,1,1,1,2,2,4)

array([[[[[[[[[[ 4.99246327e-01,  1.25963244e-01,
                 3.14997957e+00, -8.50899753e-01],
               [-6.05251587e-01, -1.34775902e+00,
                -5.83584254e-01, -7.57769014e-01]],

              [[-3.79479337e-01,  8.74568929e-01,
                -1.17371048e-01, -6.51601623e-01],
               [ 1.05962110e+00, -1.49936376e+00,
                -1.76574632e-03,  9.76555282e-01]]]]]]]]]])

In [17]:
#Slicing Exact similar to list
print(a1)
print(a1[0])     
print(a1[2:6])
print(a1[2:6:2])

[1 2 3 4 5 6]
1
[3 4 5 6]
[3 5]


In [18]:
print(a2)
print(a2[0])
print(a2[:,1:])
print(a2[:,[1,2]]) #Same thing as above
print(a2[[0,1],[1,2]]) #Same thing as above

[[1 2 3]
 [4 5 6]]
[1 2 3]
[[2 3]
 [5 6]]
[[2 3]
 [5 6]]
[2 6]


In [19]:
a5 = np.random.randint(2,90,(6,5))
a5

array([[ 7, 30, 59, 42, 60],
       [40,  3, 68, 73, 53],
       [47, 79, 82, 18, 64],
       [59,  9, 69, 14, 45],
       [49, 36, 76, 31, 27],
       [64, 63, 67, 31, 58]])

In [20]:
#Similar to Pandas Dataframe, we can write filter condition
a5[a5>40]

array([59, 42, 60, 68, 73, 53, 47, 79, 82, 64, 59, 69, 45, 49, 76, 64, 63,
       67, 58])

In [21]:
#Updating data
a5[0,1] = 100 #11 Replaced by 100
a5

array([[  7, 100,  59,  42,  60],
       [ 40,   3,  68,  73,  53],
       [ 47,  79,  82,  18,  64],
       [ 59,   9,  69,  14,  45],
       [ 49,  36,  76,  31,  27],
       [ 64,  63,  67,  31,  58]])

In [22]:
a6 = np.random.randint(0,3,(3,3))
a7 = np.random.randint(0,3,(3,3))
print(a6)
print(a7)

[[0 1 2]
 [1 0 1]
 [1 2 2]]
[[2 1 1]
 [2 2 1]
 [2 1 2]]


In [23]:
#Element Wise Multiplication and not Matrix Multiplication
print(a6*a7)

[[0 1 2]
 [2 0 1]
 [2 2 4]]


In [24]:
#Matrix Multiplication
print(a6@a7)

[[ 6  4  5]
 [ 4  2  3]
 [10  7  7]]


In [25]:
#Array Operations
print(a6+100)
print(a6*2)
print(a6*0)
print(a6/0)  #No Errors

[[100 101 102]
 [101 100 101]
 [101 102 102]]
[[0 2 4]
 [2 0 2]
 [2 4 4]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[nan inf inf]
 [inf nan inf]
 [inf inf inf]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: RuntimeWarning: divide by zero encountered in true_divide
  """
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: RuntimeWarning: invalid value encountered in true_divide
  """


In [26]:
print(a6**3) #Power

[[0 1 8]
 [1 0 1]
 [1 8 8]]


In [27]:
a8 = np.zeros((4,4))
a8

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [28]:
a9 = np.ones((4,5))
a9

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [29]:
a9+10

array([[11., 11., 11., 11., 11.],
       [11., 11., 11., 11., 11.],
       [11., 11., 11., 11., 11.],
       [11., 11., 11., 11., 11.]])

In [30]:
print(a9)
print(a9 + np.array([1,2,3,4,5])) #Doing row by row operation. Also called as Broadcasting operation

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[2. 3. 4. 5. 6.]
 [2. 3. 4. 5. 6.]
 [2. 3. 4. 5. 6.]
 [2. 3. 4. 5. 6.]]


In [31]:
#How to do column wise Boradcasting operation: We will have to transpose first and then add
#np.array([1,2,3,4]).T + a9   #Error because for transpose we need 2 dimesnsions. Hence we will give 2 brackets to convert into 2d
np.array([[1,2,3,4]]).T + a9 

array([[2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5.]])

In [32]:
#Understanding Transpose
print(a6)
print(a6.T)

[[0 1 2]
 [1 0 1]
 [1 2 2]]
[[0 1 1]
 [1 0 2]
 [2 1 2]]


In [33]:
print(a5)
print(np.sqrt(a5))
print(np.exp(a5))
print(np.log10(a5))

[[  7 100  59  42  60]
 [ 40   3  68  73  53]
 [ 47  79  82  18  64]
 [ 59   9  69  14  45]
 [ 49  36  76  31  27]
 [ 64  63  67  31  58]]
[[ 2.64575131 10.          7.68114575  6.4807407   7.74596669]
 [ 6.32455532  1.73205081  8.24621125  8.54400375  7.28010989]
 [ 6.8556546   8.88819442  9.05538514  4.24264069  8.        ]
 [ 7.68114575  3.          8.30662386  3.74165739  6.70820393]
 [ 7.          6.          8.71779789  5.56776436  5.19615242]
 [ 8.          7.93725393  8.18535277  5.56776436  7.61577311]]
[[1.09663316e+03 2.68811714e+43 4.20121040e+25 1.73927494e+18
  1.14200739e+26]
 [2.35385267e+17 2.00855369e+01 3.40427605e+29 5.05239363e+31
  1.04137594e+23]
 [2.58131289e+20 2.03828107e+34 4.09399696e+35 6.56599691e+07
  6.23514908e+27]
 [4.20121040e+25 8.10308393e+03 9.25378173e+29 1.20260428e+06
  3.49342711e+19]
 [1.90734657e+21 4.31123155e+15 1.01480039e+33 2.90488497e+13
  5.32048241e+11]
 [6.23514908e+27 2.29378316e+27 1.25236317e+29 2.90488497e+13
  1.54553894e+25]]
[

In [34]:
print(list(range(10)))
print(list(range(0,10,2)))
#print(list(range(0,10,2.5))) #Error because jump size cannot be float

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 2, 4, 6, 8]


In [35]:
#Arange same as range but it also takes jump size as float
print(np.arange(10))
print(np.arange(1.8,10.7,2.5)) 

[0 1 2 3 4 5 6 7 8 9]
[1.8 4.3 6.8 9.3]


In [36]:
#In between certain range, we want to generate numbers
print(np.linspace(2,3,num=50)) #Considers Linear Space
print(np.linspace(2,3,num=50,retstep=True)) #Jumpsize will also be returned

[2.         2.02040816 2.04081633 2.06122449 2.08163265 2.10204082
 2.12244898 2.14285714 2.16326531 2.18367347 2.20408163 2.2244898
 2.24489796 2.26530612 2.28571429 2.30612245 2.32653061 2.34693878
 2.36734694 2.3877551  2.40816327 2.42857143 2.44897959 2.46938776
 2.48979592 2.51020408 2.53061224 2.55102041 2.57142857 2.59183673
 2.6122449  2.63265306 2.65306122 2.67346939 2.69387755 2.71428571
 2.73469388 2.75510204 2.7755102  2.79591837 2.81632653 2.83673469
 2.85714286 2.87755102 2.89795918 2.91836735 2.93877551 2.95918367
 2.97959184 3.        ]
(array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
       2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
       2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
       2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
       2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
       2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
       2.6122449 , 2.63265306, 2.65306

In [37]:
np.logspace(2,4,num=4,base=10) #Considers Logarithmic Base

array([  100.        ,   464.15888336,  2154.43469003, 10000.        ])

In [38]:
#Identity Matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## **DATA VISUALIZATION LIBRARY**

MATPLOTLIB: Helps in EDA: Helps us in identifying Trends in data

Other Libraries that we will discuss are: Plotly and Seaborn

For Dashboarding purposes, PowerBI and Tableau is widely used but for basic EDA, we use these above libraries

Line Plot, Bar Plot, 3D Plot, Histogram, Scatter Plot etc.

In [5]:
#pip install cufflinks
!pip install chart_studio

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 64 kB 2.0 MB/s 
  Created wheel for retrying: filename=retrying-1.3.3-py3-none-any.whl size=11447 sha256=1efbd14df29f6959b71d74adb3b9dfabab900bf362b51c47443417bb86f908b5
  Stored in directory: /root/.cache/pip/wheels/f9/8d/8d/f6af3f7f9eea3553bc2fe6d53e4b287dad18b06a861ac56ddf
Successfully built retrying


In [2]:
import matplotlib as plt
import cufflinks as cf
import numpy as np
import pandas as pd
import seaborn as sns

In [3]:
cf.go_offline #Since we are using offline mode

<function cufflinks.offline.go_offline>

In [ ]:
df = pd.DataFrame(np.random.randn(100,3),columns=['A','B','C'])
df.iplot() #Graph Plot showing Fluctuation: y axis contains value in the column and x axis is the index

In [ ]:
df1 = pd.DataFrame(np.random.randint(3,100,(100,1)))
df1.iplot() #Graph Plot showing Fluctuation

In [ ]:
df.iplot(x='A',y='B',mode = 'markers') #Marker mode means representation in dots 
#We can use the above code to compare both columns using graph

In [9]:
df2 = sns.load_dataset('titanic')

In [10]:
df2.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [ ]:
#Age is dependent on fare or not?
df2.iplot(x='age',y='fare',mode='markers') #This tells us that when age increasing, fare is not increasing. Hence no relation between them

In [ ]:
#Relation between Passenger Class and Age
df2.iplot(x='age',y='pclass',mode='markers') #No obvious relation. 

In [ ]:
#Relation between Passenger Class and fare
df2.iplot(x='fare',y='pclass',mode='markers') #We can see relation

In [12]:
df2.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [ ]:
#Bar Plot
df2.iplot(kind='bar', x = 'sex', y='survived')