In [11]:
!onnxsim ./full.onnx ./full_opt.onnx 5

Your model contains "Tile" ops or/and "ConstantOfShape" ops. Folding these ops 
can make the simplified model much larger. If it is not expected, please specify
"--no-large-tensor" (which will lose some optimization chances)
Simplifying...
Checking 0/5...
Checking 1/5...
Checking 2/5...
Checking 3/5...
Checking 4/5...
Finish! Here is the difference:
┏━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━┓
┃                   ┃ Original Model ┃ Simplified Model ┃
┡━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━┩
│ Add               │ 78             │ 38               │
│ ArgMin            │ 1              │ 1                │
│ Cast              │ 96             │ 1                │
│ Ceil              │ 20             │ 0                │
│ Clip              │ 20             │ 0                │
│ Concat            │ 33             │ 1                │
│ Constant          │ 638            │ 279              │
│ ConstantOfShape   │ 10             │ 0                │
│ Conv    

In [1]:
!mnnconvert -f ONNX --modelFile ./full_static_opt.onnx --optimizeLevel 1 --optimizePrefer 2 --fp16 --weightQuantBits 8 --weightQuantAsymmetric --bizCode full_static_opt --alignDenormalizedValue 1 --detectSparseSpeedUp 1 --saveStaticModel --MNNModel ./full_static_opt.mnn

hw.cpufamily: 458787763 , size = 4
The device support i8sdot:1, support fp16:1, support i8mm: 0
Start to Convert Other Model Format To MNN Model..., target version: 2.8
[11:07:06] :46: ONNX Model ir version: 8
[11:07:06] :47: ONNX Model opset version: 17
Start to Optimize the MNN Net...
inputTensors : [ image, ]
outputTensors: [ embeddings, ]
gen Static Model ... 
Converted Success!


In [27]:
!mnnconvert -f ONNX --modelFile ./full_opt.onnx --optimizeLevel 1 --optimizePrefer 2 --fp16 --weightQuantBits 8 --weightQuantAsymmetric --bizCode full_opt --alignDenormalizedValue 1 --detectSparseSpeedUp 1 --saveStaticModel --MNNModel ./full_opt.mnn

hw.cpufamily: 458787763 , size = 4
The device support i8sdot:1, support fp16:1, support i8mm: 0
Start to Convert Other Model Format To MNN Model..., target version: 2.8
[15:21:01] :46: ONNX Model ir version: 8
[15:21:01] :47: ONNX Model opset version: 17
Start to Optimize the MNN Net...
The Convolution use shared weight, may increase the model size
inputTensors : [ query_images, support_images, ]
outputTensors: [ predictions, ]
gen Static Model ... 
Converted Success!


In [10]:
!mnnconvert -f ONNX --modelFile ./full_dynamic_opt.onnx --optimizeLevel 1 --optimizePrefer 2 --fp16 --weightQuantBits 8 --weightQuantAsymmetric --bizCode full_dynamic_opt --alignDenormalizedValue 1 --detectSparseSpeedUp 1 --MNNModel ./full_dynamic_opt.mnn

hw.cpufamily: 458787763 , size = 4
The device support i8sdot:1, support fp16:1, support i8mm: 0
Start to Convert Other Model Format To MNN Model..., target version: 2.8
[23:39:28] :46: ONNX Model ir version: 8
[23:39:28] :47: ONNX Model opset version: 17
[23:39:28] :133: Check it out ==> /Resize_output_0 has empty input, the index is 1
[23:39:28] :133: Check it out ==> /Resize_output_0 has empty input, the index is 2
Start to Optimize the MNN Net...
inputTensors : [ image, ]
outputTensors: [ embeddings, ]
Converted Success!


In [3]:
!mnnconvert -f ONNX --modelFile /Users/arif/Downloads/yolov6lite_l.onnx --optimizeLevel 1 --optimizePrefer 2 --fp16 --weightQuantBits 8 --weightQuantAsymmetric --bizCode yolov6lite_l_opt --alignDenormalizedValue 1 --detectSparseSpeedUp 1 --MNNModel ./yolov6lite_l_opt.mnn

hw.cpufamily: 458787763 , size = 4
The device support i8sdot:1, support fp16:1, support i8mm: 0
Start to Convert Other Model Format To MNN Model..., target version: 2.8
[12:52:20] :46: ONNX Model ir version: 8
[12:52:20] :47: ONNX Model opset version: 17
[12:52:20] :133: Check it out ==> /Resize_output_0 has empty input, the index is 1
[12:52:20] :133: Check it out ==> /Resize_output_0 has empty input, the index is 2
[12:52:20] :133: Check it out ==> /model/neck/upsample0/Resize_output_0 has empty input, the index is 1
[12:52:20] :133: Check it out ==> /model/neck/upsample0/Resize_output_0 has empty input, the index is 2
[12:52:20] :133: Check it out ==> /model/neck/upsample1/Resize_output_0 has empty input, the index is 1
[12:52:20] :133: Check it out ==> /model/neck/upsample1/Resize_output_0 has empty input, the index is 2
Start to Optimize the MNN Net...
inputTensors : [ images, ]
outputTensors: [ det_box, ]
Converted Success!


In [5]:
!mnnconvert -f ONNX --modelFile /Users/arif/Downloads/yolov6n.onnx --optimizeLevel 1 --optimizePrefer 2 --fp16 --weightQuantBits 8 --weightQuantAsymmetric --bizCode yolov6n_opt --alignDenormalizedValue 1 --detectSparseSpeedUp 1 --MNNModel ./yolov6n_opt.mnn

hw.cpufamily: 458787763 , size = 4
The device support i8sdot:1, support fp16:1, support i8mm: 0
Start to Convert Other Model Format To MNN Model..., target version: 2.8
[14:46:36] :46: ONNX Model ir version: 8
[14:46:36] :47: ONNX Model opset version: 17
[14:46:36] :133: Check it out ==> /Resize_output_0 has empty input, the index is 1
[14:46:36] :133: Check it out ==> /Resize_output_0 has empty input, the index is 2
Start to Optimize the MNN Net...
inputTensors : [ images, ]
outputTensors: [ det_box, ]
Converted Success!


In [2]:
!mnnconvert -f ONNX --modelFile ./support_proto/ZProto_opt.onnx --optimizeLevel 1 --optimizePrefer 2 --fp16 --weightQuantBits 8 --weightQuantAsymmetric --bizCode ZProto_opt --alignDenormalizedValue 1 --detectSparseSpeedUp 1 --MNNModel ./support_proto/ZProto_opt.mnn

hw.cpufamily: 458787763 , size = 4
The device support i8sdot:1, support fp16:1, support i8mm: 0
Start to Convert Other Model Format To MNN Model..., target version: 2.8
[11:07:17] :46: ONNX Model ir version: 8
[11:07:17] :47: ONNX Model opset version: 17
Start to Optimize the MNN Net...
inputTensors : [ z_support, support_labels, ]
outputTensors: [ z_proto, ]
Converted Success!


In [23]:
!mnnconvert -f ONNX --modelFile ./support_proto/yolov6l6.onnx --optimizeLevel 1 --optimizePrefer 2 --bizCode yolov6l6_opt --alignDenormalizedValue 1 --detectSparseSpeedUp 1 --MNNModel ./support_proto/yolov6l6_opt.mnn

hw.cpufamily: 458787763 , size = 4
The device support i8sdot:1, support fp16:1, support i8mm: 0
Start to Convert Other Model Format To MNN Model..., target version: 2.8
[19:09:35] :46: ONNX Model ir version: 8
[19:09:35] :47: ONNX Model opset version: 17
[19:09:35] :133: Check it out ==> /Resize_output_0 has empty input, the index is 1
[19:09:35] :133: Check it out ==> /Resize_output_0 has empty input, the index is 2
Start to Optimize the MNN Net...
The Convolution use shared weight, may increase the model size
Shape of NonMaxSupression's input is unknown. Please confirm version of MNN engine is new enough and use V3 Module API to run it correctly
inputTensors : [ images, ]
outputTensors: [ det_box, ]
Converted Success!


In [17]:
!mnnconvert -f ONNX --modelFile ./MinEuclid.onnx --optimizeLevel 1 --optimizePrefer 2 --fp16 --weightQuantBits 8 --weightQuantAsymmetric --bizCode MinEuclid --alignDenormalizedValue 1 --detectSparseSpeedUp 1 --saveStaticModel --MNNModel ./MinEuclid.mnn

hw.cpufamily: 458787763 , size = 4
The device support i8sdot:1, support fp16:1, support i8mm: 0
Start to Convert Other Model Format To MNN Model..., target version: 2.8
[00:30:03] :46: ONNX Model ir version: 8
[00:30:03] :47: ONNX Model opset version: 17
Start to Optimize the MNN Net...
inputTensors : [ z_query, z_proto, ]
outputTensors: [ dists, prediction, ]
gen Static Model ... 
Converted Success!


In [4]:
!mnnconvert -f ONNX --modelFile ./ProdStatic_opt.onnx --optimizeLevel 1 --optimizePrefer 2 --fp16 --weightQuantBits 8 --weightQuantAsymmetric --bizCode ProdStatic_opt --alignDenormalizedValue 1 --detectSparseSpeedUp 1 --saveStaticModel --batch 2 --MNNModel ./ProdStatic_opt.mnn

hw.cpufamily: 458787763 , size = 4
The device support i8sdot:1, support fp16:1, support i8mm: 0
Start to Convert Other Model Format To MNN Model..., target version: 2.8
[14:38:10] :46: ONNX Model ir version: 8
[14:38:10] :47: ONNX Model opset version: 17
Start to Optimize the MNN Net...
inputTensors : [ query_image, z_proto, ]
outputTensors: [ dists, predictions, ]
gen Static Model ... 
Converted Success!


In [12]:
!mnnconvert -f ONNX --modelFile models/ProdStatic_opt_o.onnx --optimizeLevel 1 --optimizePrefer 2 --fp16 --weightQuantBits 8 --weightQuantAsymmetric --bizCode ProdStatic_opt_o --alignDenormalizedValue 1 --detectSparseSpeedUp 1 --batch 2 --MNNModel ./ProdStatic_opt_o.mnn

hw.cpufamily: 458787763 , size = 4
The device support i8sdot:1, support fp16:1, support i8mm: 0
Start to Convert Other Model Format To MNN Model..., target version: 2.8
[21:19:16] :46: ONNX Model ir version: 8
[21:19:16] :47: ONNX Model opset version: 17
Start to Optimize the MNN Net...
Unsupported data type!Unsupported data type!Unsupported data type!Unsupported data type!Reshape error: 1 -> 0
Reshape error: 1 -> 0
Reshape error: 1 -> 0
Reshape error: 1 -> 0
Reshape error: 1 -> 0
Reshape error: 1 -> 0
Reshape error: 1 -> 0
Reshape error: 1 -> 0
Reshape error: 1 -> 0
Reshape error: 1 -> 0
Reshape error: 1 -> 0
Reshape error: 1 -> 0
Reshape error: 1 -> 0
Reshape error: 1 -> 0
Reshape error: 1 -> 0
Reshape error: 1 -> 0
Reshape error: 1 -> 0
Reshape error: 1 -> 0
Reshape error: 1 -> 0
Reshape error: 1 -> 0
Reshape error: 1 -> 0
Reshape error: 1 -> 0
Unsupported data type!Reshape error: 1 -> 0
Reshape error: 1 -> 0
Reshape error: 1 -> 0
Reshape error: 1 -> 0
Reshape error: 1 -> 0
Reshape 

In [7]:
!mnnconvert -h

hw.cpufamily: 458787763 , size = 4
The device support i8sdot:1, support fp16:1, support i8mm: 0

Usage:
  MNNConvert [OPTION...]

  -h, --help                    Convert Other Model Format To MNN Model

  -v, --version                 show current version
  -f, --framework arg           model type, ex:
                                [TF,CAFFE,ONNX,TFLITE,MNN,JSON]
      --modelFile arg           tensorflow Pb or caffeModel, ex:
                                *.pb,*caffemodel
      --batch arg               if model input's batch is not set, set as the
                                batch size you set
      --keepInputFormat         keep input dimension format or not, default:
                                false
      --optimizeLevel arg       graph optimize option, 0: don't run
                                optimize(only support for MNN source), 1: use graph
                                optimize only for every input case is right, 2:
                                normally r

In [1]:
!mnnconvert -f ONNX --modelFile ./od_tf.onnx --optimizeLevel 1 --optimizePrefer 2 --fp16 --weightQuantBits 8 --weightQuantAsymmetric --bizCode od_tf --alignDenormalizedValue 1 --detectSparseSpeedUp 1 --MNNModel ./od_tf.mnn

hw.cpufamily: 458787763 , size = 4
The device support i8sdot:1, support fp16:1, support i8mm: 0
Start to Convert Other Model Format To MNN Model..., target version: 2.8
[18:00:21] :46: ONNX Model ir version: 8
[18:00:21] :47: ONNX Model opset version: 18
Start to Optimize the MNN Net...
The Convolution use shared weight, may increase the model size
Shape of NonMaxSupression's input is unknown. Please confirm version of MNN engine is new enough and use V3 Module API to run it correctly
inputTensors : [ images, ]
outputTensors: [ output_0, output_1, output_2, output_3, ]
Converted Success!


bazel-bin/tensorflow/tools/graph_transforms/summarize_graph --in_graph="/Users/arif/Documents/Pet_Feeder/Software/AI/cat_feeder_project/od_tf2/efficientdet-d5_frozen.pb"

python3 -m cProfile -s time "/Users/arif/Documents/Pet_Feeder/Software/AI/cat_feeder_project/cv_bb_prod_final_rpi.py"

python3 ./deploy/ONNX/export_onnx.py \
--weights /Users/arif/Downloads/yolov6l6.pt \
    --img 1600 \
    --batch 1 \
    --end2end \
    --ort \
--inplace --simplify --topk-all 10 --conf-thres 0.4 --with-preprocess

In [ ]:
python3 ./deploy/ONNX/export_onnx.py \
--weights /Users/arif/Downloads/yolov6lite_l.pt \
    --img 320 \
    --batch 1 \
    --end2end \
    --ort \
--inplace --simplify --topk-all 10 --conf-thres 0.4 --with-preprocess

In [ ]:
python3 ./export.py --weights /Users/arif/Downloads/yolov7.pt --grid --end2end --simplify\
        --topk-all 100 --iou-thres 0.65 --conf-thres 0.35 --img-size 640 640 --max-wh 640

In [19]:
from torch.utils.data import DataLoader
from torchvision.datasets import OxfordIIITPet
from tqdm import tqdm

from easyfsl.samplers import TaskSampler

import MNN.nn as nn
import MNN.cv as cv2
import MNN.numpy as np
import MNN.expr as expr

In [16]:
def preprocess_mnn(image):
    # mean = np.asarray([0.485, 0.456, 0.406], dtype=np.float32)
    # std = np.asarray([0.229, 0.224, 0.225], dtype=np.float32)

    # image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    # print("image cvt", image.dtype, image.shape, image.mean(), image.std())
    # image = cv2.resize(image, (640, 640), interpolation=cv2.INTER_CUBIC)
    # print("image rsz", image.dtype, image.shape, image.mean(), image.std())

    # w = h = 300
    # y, x = (image.shape[0] - h) // 2, (image.shape[1] - w) // 2
    # image = image[y:y + h, x:x + w]

    # image = image.astype(np.float32)
    image = expr.cast(image)
    # image = image.astype(np.float32) / 255.0
    # print("image 255", image.dtype, image.shape, image.mean(), image.std())
    # image = (image - mean) / std
    # print("image norm", image.dtype, image.shape, image.mean(), image.std())
    image = expr.expand_dims(image, 0)
    image = expr.convert(image, expr.NC4HW4)
    return image


image = cv2.imread("CatDataset/support/jico/lp_image.jpeg", cv2.IMREAD_COLOR)
# image = cv2.imread("CatDataset/support/jico/lp_image.jpeg", cv2.IMREAD_GRAYSCALE)
# image = cv2.imread("/Users/arif/Downloads/beignets-task-guide.png", cv2.IMREAD_GRAYSCALE)
print("image", image.dtype, image.shape, image.mean(), image.std())
image = preprocess_mnn(image)

print("image", image.dtype, image.shape, image.mean(), image.std())

# inputTensors = []
inputTensors = ["images"]
# outputTensors = [ '/end2end/TopK_output_0', 'det_boxes', 'det_classes', 'num_dets']
# outputTensors = [ 'det_boxes', 'det_classes', 'det_scores', 'num_dets']
# outputTensors = [ 'num_dets', 'det_boxes', 'det_scores', 'det_classes']
outputTensors = ["det_box_score"]
outputTensors = []
# , runtime_manager=rt
net = nn.load_module_from_file("./yolov6n_opt.mnn", inputTensors, outputTensors)
# net = nn.load_module_from_file('./full_dynamic_opt.mnn', ['image'], ['embeddings'])
r = net.forward(image)
print(r)

image dtype.uint8 [959, 884, 3] 84.82652282714844 46.131614685058594
image dtype.float [1, 3, 959, 884] 84.84130859375 46.14801025390625
array([  10,   32, 1549, 1544], dtype=int32)


In [14]:
len(r[0])

1536

In [12]:
# def pad_to_square(image, color=(114, 114, 114)):
#     """Pad an image to a square shape with the specified color.

#     Args:
#         image (numpy.ndarray): The input image.
#         color (tuple): The color for padding (B, G, R).

#     Returns:
#         numpy.ndarray: The padded image.
#     """
#     # Get the image height and width
#     h, w = image.shape[:2]

#     # Determine the size for the square (the max of height and width)
#     square_size = max(h, w)

#     # Calculate the padding for height and width
#     top_pad = (square_size - h) // 2
#     bottom_pad = square_size - h - top_pad
#     left_pad = (square_size - w) // 2
#     right_pad = square_size - w - left_pad

#     # Pad the image
#     padded_image = cv2.copyMakeBorder(
#         image,
#         top_pad,
#         bottom_pad,
#         left_pad,
#         right_pad,
#         cv2.BORDER_CONSTANT,
#         value=color,
#     )

#     return padded_image


def preprocess_mnn(image):
    # mean = np.asarray([0.485, 0.456, 0.406], dtype=np.float32)
    # std = np.asarray([0.229, 0.224, 0.225], dtype=np.float32)

    # image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    # print("image cvt", image.dtype, image.shape, image.mean(), image.std())
    # image = cv2.resize(image, (1280, 1280), interpolation=cv2.INTER_CUBIC)
    # print("image rsz", image.dtype, image.shape, image.mean(), image.std())

    # w = h = 300
    # y, x = (image.shape[0] - h) // 2, (image.shape[1] - w) // 2
    # image = image[y:y + h, x:x + w]

    # image = image.astype(np.float32)
    # image = expr.cast(image)
    # image = image.astype(np.float32) / 255.0
    # print("image 255", image.dtype, image.shape, image.mean(), image.std())
    # image = (image - mean) / std
    # print("image norm", image.dtype, image.shape, image.mean(), image.std())
    image = expr.expand_dims(image, 0)
    image = expr.convert(image, expr.NC4HW4)
    return image


image = cv2.imread("CatDataset/support/jico/lp_image.jpeg", cv2.IMREAD_COLOR)
# image = cv2.imread("CatDataset/support/jico/lp_image.jpeg", cv2.IMREAD_GRAYSCALE)
# image = cv2.imread("/Users/arif/Downloads/beignets-task-guide.png", cv2.IMREAD_GRAYSCALE)
print("image", image.dtype, image.shape, image.mean(), image.std())
image = preprocess_mnn(image)

print("image", image.dtype, image.shape, image.mean(), image.std())

inputTensors = []
# inputTensors = [ 'images' ]
# outputTensors = [ '/end2end/TopK_output_0', 'det_boxes', 'det_classes', 'num_dets']
# outputTensors = [ 'det_boxes', 'det_classes', 'det_scores', 'num_dets']
# outputTensors = [ 'num_dets', 'det_boxes', 'det_scores', 'det_classes']
# outputTensors = [ 'det_box_score']
outputTensors = ["output_2"]
# , runtime_manager=rt
net = nn.load_module_from_file("./od_tf.mnn", inputTensors, outputTensors)
# net = nn.load_module_from_file('./full_dynamic_opt.mnn', ['image'], ['embeddings'])
r = net.forward(image)
print(r)

image dtype.uint8 [959, 884, 3] 84.82652282714844 46.131614685058594
image dtype.uint8 [1, 3, 959, 884] 84.84130859375 46.14801025390625
array([[37., 37., 37., 37., 77., 77., 37., 34., 37., 37.]], dtype=float32)


In [49]:
python3 ./deploy/ONNX/export_onnx.py \
--weights /Users/arif/Downloads/yolov6n.pt \
    --img 1152 \
    --batch 1 \
    --end2end \
    --ort \
--inplace --simplify --topk-all 10 --conf-thres 0.5 --with-preprocess

array([[1]], dtype=int32)

In [82]:
postprocess(r)

array([[[  4.7543335,   3.0682983,   0.       ],
        [ 14.586975 ,   6.470459 ,   0.       ],
        [639.354    , 636.8819   ,   0.       ],
        [637.2987   , 636.2532   ,   0.       ]]], dtype=float32)

In [3]:
# def unique_vars(var_array):
#     # print("var_array", var_array)
#     unique_set = {var_array[i] for i in range(len(var_array))}
#     return unique_set

# Data

In [20]:
test_set = OxfordIIITPet(
    root="/Users/arif/Downloads/data",
    split="trainval",
    target_types="category",
    download=False,
)

# test_set = OxfordIIITPet(
#     root="/Users/arif/Downloads/data",
#     split= "test",
#     target_types = "category",
#     download=False,
# )

# Model Init

In [21]:
# # 配置执行后端，线程数，精度等信息；key-vlaue请查看API介绍
config = {}
config["precision"] = "low"  # 当硬件支持（armv8.2）时使用fp16推理
config["backend"] = 0  # CPU
config["numThread"] = 8  # 线程数
# config['memory_mode'] = 'high'
# config['power_mode'] = 'high'

rt = nn.create_runtime_manager((config,))
# 加载模型创建_Module
inputTensors = [
    "query_images",
    "support_images",
]
outputTensors = ["predictions"]

net = nn.load_module_from_file(
    "./full_static_in_opt.mnn", inputTensors, outputTensors, runtime_manager=rt
)
# inputTensors = [
#     "query_images",
#     "support_images",
#     "support_labels",
# ]
# outputTensors = ["predictions"]

# net = nn.load_module_from_file(
#     "./full_opt.mnn", inputTensors, outputTensors, runtime_manager=rt
# )

MNN use low precision


In [22]:
def preprocess(image):
    # image = cv.resize(image, (260, 260), mean=[0.485, 0.456, 0.406], norm=[0.229, 0.224, 0.225])
    # input_var = np.expand_dims(image, 0)
    input_var = expr.convert(image, expr.NC4HW4)
    return input_var


def postprocess(output_var):
    output_var = expr.convert(output_var, expr.NHWC)
    return output_var

In [23]:
# def calculate_mean_for_label(z_support, support_labels, label):
#     # Select the elements of z_support corresponding to the current label and calculate their mean
#     return np.mean(z_support[support_labels[support_labels == label]], axis=0)
#     # return z_support[np.nonzero(support_labels == label)].mean(0)

# def fsl_model(support_net, query_net, support_images, support_labels, query_images):
#     # print(support_labels.shape, support_labels)
#     support_images = preprocess(support_images)
#     query_images = preprocess(query_images)
#     # print(support_images.shape, query_images.shape)
#     print("support_images", support_images.mean(), support_images.std())
#     print("query_images", query_images.mean(), query_images.std())

#     z_support = support_net.forward(support_images)
#     z_query = query_net.forward(query_images)
#     print(z_support.shape, z_query.shape)
#     print("z_support", z_support.mean(), z_support.std())
#     print("z_query", z_query.mean(), z_query.std())

#     z_support = postprocess(z_support)
#     z_query = postprocess(z_query)
#     # print(z_support.shape, z_query.shape)

#     # Infer the number of different classes from the labels of the support set
#     # n_way = len(np2.unique(support_labels))
#     n_way = len(unique_vars(support_labels))
#     # print(n_way)

#     z_proto = Parallel(n_jobs=1)(delayed(calculate_mean_for_label)(z_support, support_labels, label) for label in range(n_way))
#     z_proto = np.stack(z_proto)
#     # z_proto = np.stack(
#     #     [
#     #         # z_support[np.nonzero(support_labels == label)].mean(0)
#     #         np.mean(z_support[np.nonzero(support_labels == label)], 0)
#     #         for label in range(n_way)
#     #     ]
#     # )
#     print("z_proto", z_proto.mean(), z_proto.std())
#     print("z_proto", z_proto)
#     # print(z_proto.shape)
#     # Compute the euclidean distance from queries to prototypes
#     # dists = cdist(z_query, z_proto)
#     print(z_query.shape, z_proto.shape)
#     dists = np.linalg.norm(z_query[:, np.newaxis] - z_proto, axis=2)
#     # dists = np.sqrt(np.sum((z_query[:, np.newaxis, :] - z_proto[np.newaxis, :, :]) ** 2, axis=2))
#     print(dists.shape)
#     # return z_support, z_proto
#     print("dists", dists.mean(), dists.std())
#     print("dists", dists)
#     # print(dists.shape)

#     # And here is the super complicated operation to transform those distances into classification scores!
#     scores = -dists
#     print("scores", scores.mean(), scores.std())
#     print("scores", scores)
#     # print(scores.shape, scores)
#     return scores

In [24]:
N_WAY = 4  # Number of classes in a task
N_SHOT = 8  # Number of images per class in the support set
N_QUERY = 30  # Number of images per class in the query set
N_EVALUATION_TASKS = 10

# The sampler needs a dataset with a "get_labels" method. Check the code if you have any doubt!
test_set.get_labels = lambda: test_set._labels
test_sampler = TaskSampler(
    test_set, n_way=N_WAY, n_shot=N_SHOT, n_query=N_QUERY, n_tasks=N_EVALUATION_TASKS
)

test_loader = DataLoader(
    test_set,
    batch_sampler=test_sampler,
    num_workers=0,
    pin_memory=False,
    collate_fn=test_sampler.episodic_collate_fn,
)

In [25]:
(
    example_support_images,
    example_support_labels,
    example_query_images,
    example_query_labels,
    example_class_ids,
) = next(iter(test_loader))

In [27]:
def evaluate_on_one_task(
    support_images, support_labels, query_images, query_labels, n_way
):
    print(support_labels)
    support_images = preprocess(support_images)
    query_images = preprocess(query_images)
    # [ x.149, x.1, onnx::Cast_1, ]
    predictions = net.forward([query_images, support_images])[0]
    # predictions = net.forward([query_images, support_images, support_labels])[0] OLDD
    # print("predictions", predictions)
    # print("query_labels", query_labels)
    accuracy = np.sum(predictions == query_labels) / len(query_labels)

    return accuracy * 100


def evaluate(data_loader):
    mean_accuracy = 0
    for episode_index, (
        support_images,
        support_labels,
        query_images,
        query_labels,
        class_ids,
    ) in tqdm(enumerate(data_loader), total=len(data_loader)):
        accuracy = evaluate_on_one_task(
            support_images, support_labels, query_images, query_labels, len(class_ids)
        )
        # break
        mean_accuracy += accuracy

    print(f"Model tested on {len(data_loader)} tasks.")
    print(f"Accuracy: {mean_accuracy / len(data_loader):.2f}%")
    # return mean_accuracy / len(data_loader)


evaluate(test_loader)

  0%|          | 0/10 [00:00<?, ?it/s]

array([2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 3, 3, 3, 3, 3, 3, 3, 3], dtype=int32)


 20%|██        | 2/10 [00:46<02:58, 22.36s/it]

array([2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 3, 3, 3, 3, 3, 3, 3, 3], dtype=int32)
array([2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 3, 3, 3, 3, 3, 3, 3, 3], dtype=int32)


 30%|███       | 3/10 [00:55<01:52, 16.08s/it]

array([1, 1, 1, 1, 1, 1, 1, 1, 3, 3, 3, 3, 3, 3, 3, 3, 2, 2, 2, 2, 2, 2,
       2, 2, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)


 40%|████      | 4/10 [01:04<01:19, 13.19s/it]

array([0, 0, 0, 0, 0, 0, 0, 0, 3, 3, 3, 3, 3, 3, 3, 3, 2, 2, 2, 2, 2, 2,
       2, 2, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int32)


 50%|█████     | 5/10 [01:13<00:59, 11.94s/it]

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2,
       2, 2, 3, 3, 3, 3, 3, 3, 3, 3], dtype=int32)


 60%|██████    | 6/10 [01:29<00:52, 13.18s/it]

array([2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)


 70%|███████   | 7/10 [01:40<00:38, 12.67s/it]

array([2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int32)


 80%|████████  | 8/10 [01:49<00:22, 11.48s/it]

array([0, 0, 0, 0, 0, 0, 0, 0, 3, 3, 3, 3, 3, 3, 3, 3, 2, 2, 2, 2, 2, 2,
       2, 2, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int32)


 90%|█████████ | 9/10 [02:01<00:11, 11.51s/it]

array([0, 0, 0, 0, 0, 0, 0, 0, 3, 3, 3, 3, 3, 3, 3, 3, 2, 2, 2, 2, 2, 2,
       2, 2, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int32)


100%|██████████| 10/10 [02:17<00:00, 13.73s/it]

Model tested on 10 tasks.
Accuracy: 37.58%
