In [1]:
def gcd(a):
    for i in range(a):
        if a == 0:
            return 0
        elif a % i == 0:
            return gcd(a/i) + a/i

gcd(32)

ZeroDivisionError: integer division or modulo by zero

In [88]:
import numpy as np

#a = np.matrix([[2,3,4],[4,5,2],[2,4,6]])

a = np.matrix([400,20,5])
b = np.matrix([300,20,3])

b.T*a

matrix([[120000,   6000,   1500],
        [  8000,    400,    100],
        [  1200,     60,     15]])

In [100]:
sum(sum(b.T*a)[0])

matrix([[129200,   6460,   1615]])

In [99]:
(b.T*a).flatten()

matrix([[120000,   6000,   1500,   8000,    400,    100,   1200,     60,
             15]])

NameError: name 'math' is not defined

In [104]:
np.base_repr(52432423439204032948039284092384092384,4994)

ValueError: Bases greater than 36 not handled in base_repr.

In [38]:
import numpy as np
from numpy.linalg import inv

a = np.matrix([1,2,3])
b = np.matrix([100,10,1])

b_prime = np.matrix([[64,32,16,8,4,2,1]])

a

matrix([[1, 2, 3]])

In [53]:
a = np.matrix([2,3])
b = np.matrix([10,1])

c_prime = np.matrix([1,0,1,1,1])
b_prime = np.matrix([16,8,4,2,1])



#print(a*b.T == c_prime*b_prime.T)
a[0]

matrix([[2, 3]])

In [80]:
1*10+2*5+3*1

23

In [25]:
#4*2+3*4+2*2
2*2 + 4*4 +2*2

24

In [9]:
# A is a column vector. 
a = sp.Matrix([sp.Symbol("YIntercept"),sp.Symbol("Slope")]).T
# x is a row vector
xData = sp.Matrix([1,sp.Symbol("X")])
(a * xData)

NameError: name 'sp' is not defined

In [ ]:

# A A | 2 0 0 0 | 3 0 0 0 | A A A
# A B | 1 1 0 0 | 2 1 0 0 | A A B
# A C | 1 0 1 0 | 2 0 1 0 | A A C
# A D | 1 0 0 1 | 2 0 0 1 | A A D
# B B | 0 2 0 0 | 1 2 0 0 | A B B
# B C | 0 1 1 0 | 1 1 1 0 | A B C
# B D | 0 1 0 1 | 1 1 0 1 | A B D
# C C | 0 0 2 0           | A C C
# C D | 0 0 1 1             A C D
#                           A D D
# D D | 0 0 0 2             B B B 

def fkn(arry):
    out = []
    while len(arry) > 0:
        ls = []
        for a in arry:
            ls.append(a)
        out.append(ls)
        arry.pop(0)
    return out

def asn(prim,fst):
    out = []
    for elm in fst:
        ls = []
        for fsti in range(len(elm)):
            ls.append(prim[0])
        out.append(list(zip(ls,elm)))
        prim.pop(0)
    return out

def tz(r):
    out = []
    for i in r[:]:
        out.append((i,r))
    return out

    
a = ["A","B","C","D"]
l = list(a)
#asn(list(a),fkn(asn(list(a),fkn(list(a)))))
asn(list(a),fkn(list(a)))
#uniqueX(combX(3,['A',"B","C","D"]))

In [ ]:
# First we start with a dot product of a row vector * a column vector. 
htm = sp.Matrix(["H","T"])
r = htm * htm.T
display(r)

# Now we will flatten this matrix and repeat.
r = sp.Matrix(sp.flatten(r)) * htm.T
display(r)

# One more to show what's going on. 2^4 = 16
r = sp.Matrix(sp.flatten(r)) * htm.T
display(r)

Let's consider factorizing 1 into 3 factors. We can start with the uniform factor 1/3:
$$ 1 = \frac{1}{3}+\frac{1}{3}+\frac{1}{3} $$
Now let's define our precision value to be 0.1 = 1/10. In order to get another valid factorization of 1 with respect to our precision value, we can deduct the precision value from one factor and add it to another. 
$$ 1 = \frac{1}{3}+(\frac{1}{3}-\frac{1}{10})+(\frac{1}{3}+\frac{1}{10}) $$
We can keep doing this untill we get:
$$ 1 = \frac{1}{3}+(\frac{1}{3}-\frac{2}{10})+(\frac{1}{3}+\frac{2}{10}) $$
Because deducting 3/10 from our middle term would give us less than 1/10 ( violating our precision ). The problem isn't as simple as it seems, because the following is also a valid fractional factorization: 
$$ 1 = (\frac{1}{3}+\frac{1}{10})+(\frac{1}{3}-\frac{2}{10})+(\frac{1}{3}+\frac{1}{10}) $$

It actually occurs to me that we are defining a type of geometric object. I.e. a circle is defined as such: 
$$ x^2 * y^2 = 1 $$
We can calculate points on this circle with the parametric equations: 
$$ x = cx + r * cos(a)\\y = cy + r * sin(a) $$
Where cx,cy is the orgin point, r being the radius, and a is the angle in radians ( which we adjust to calculate points along the curcumfrence )

In [ ]:
# For a circle in the origin, with a radius of 1.
points = []
for i in range(361):
    points.append([np.cos(np.radians(i)),np.sin(np.radians(i))])

# Does every point satisfy the equation above? Yes
for i in points:
    #print(i[0]**2+i[1]**2)
    pass

In [ ]:
 for i in idx:
        ys.append(t)
        zs.append(val - t )
        
    #for i in zip(ys,idx):
       # zs.append(val - (i[0]+i[1]))
    
    return list(zip(idx,ys,zs))


for i in summandsPermute(1,3):
    print("{0:8f} + {1:8f} + {2:8f} = {3}".format(i[0],i[1],i[2],i[0]+i[1]+i[2]))

In [ ]:
def summandsPermute(val,nTerms,precision=10):
    
    outLs = []
    idx = np.linspace(0,val,precision)
    
    # Remove edge cases. 
    idx = idx[1:-1]
    
    cycleVal = nTerms
    cycleCounter = 0
    for i in range(nTerms):
        outLs.append(list(cycleDown(idx,cycleCounter)))
        cycleCounter+=cycleVal
        
    
    return list(zip(*outLs))

result = summandsPermute(1,3)
for i in result:
    print(i)
    
print(len(result))

In [ ]:
    for i in range(nTerms):
        cycleGroup.append(list(idx))
    
    cycleIndex = nTerms - 1
    
    for i in range(200):
        grp = list(zip(*cycleGroup))
        res = sum(grp[0])
        if(str(res) == "1.0"):
            print(grp[0])
            cycleColumn(cycleGroup,cycleIndex)
            cycleIndex = roundDec(cycleIndex,nTerms)
            
        cycleColumn(cycleGroup,cycleIndex)
        
    