In [1]:
import pandas as pd
import numpy as np

In [2]:
raw_data = pd.read_csv('data_set.csv')
raw_data

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0      842302         M        17.99         10.38          122.80     1001.0   
1      842517         M        20.57         17.77          132.90     1326.0   
2    84300903         M        19.69         21.25          130.00     1203.0   
3    84348301         M        11.42         20.38           77.58      386.1   
4    84358402         M        20.29         14.34          135.10     1297.0   
..        ...       ...          ...           ...             ...        ...   
564    926424         M        21.56         22.39          142.00     1479.0   
565    926682         M        20.13         28.25          131.20     1261.0   
566    926954         M        16.60         28.08          108.30      858.1   
567    927241         M        20.60         29.33          140.10     1265.0   
568     92751         B         7.76         24.54           47.92      181.0   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0            0.11840           0.27760         0.30010              0.14710   
1            0.08474           0.07864         0.08690              0.07017   
2            0.10960           0.15990         0.19740              0.12790   
3            0.14250           0.28390         0.24140              0.10520   
4            0.10030           0.13280         0.19800              0.10430   
..               ...               ...             ...                  ...   
564          0.11100           0.11590         0.24390              0.13890   
565          0.09780           0.10340         0.14400              0.09791   
566          0.08455           0.10230         0.09251              0.05302   
567          0.11780           0.27700         0.35140              0.15200   
568          0.05263           0.04362         0.00000              0.00000   

     ...  radius_worst  texture_worst  perimeter_worst  area_worst  \
0    ...        25.380          17.33           184.60      2019.0   
1    ...        24.990          23.41           158.80      1956.0   
2    ...        23.570          25.53           152.50      1709.0   
3    ...        14.910          26.50            98.87       567.7   
4    ...        22.540          16.67           152.20      1575.0   
..   ...           ...            ...              ...         ...   
564  ...        25.450          26.40           166.10      2027.0   
565  ...        23.690          38.25           155.00      1731.0   
566  ...        18.980          34.12           126.70      1124.0   
567  ...        25.740          39.42           184.60      1821.0   
568  ...         9.456          30.37            59.16       268.6   

     smoothness_worst  compactness_worst  concavity_worst  \
0             0.16220            0.66560           0.7119   
1             0.12380            0.18660           0.2416   
2             0.14440            0.42450           0.4504   
3             0.20980            0.86630           0.6869   
4             0.13740            0.20500           0.4000   
..                ...                ...              ...   
564           0.14100            0.21130           0.4107   
565           0.11660            0.19220           0.3215   
566           0.11390            0.30940           0.3403   
567           0.16500            0.86810           0.9387   
568           0.08996            0.06444           0.0000   

     concave points_worst  symmetry_worst  fractal_dimension_worst  
0                  0.2654          0.4601                  0.11890  
1                  0.1860          0.2750                  0.08902  
2                  0.2430          0.3613                  0.08758  
3                  0.2575          0.6638                  0.17300  
4                  0.1625          0.2364                  0.07678  
..                    ...             ...                      ...  
564                0.2216       

## Dataset without feature engineering (Orignal_Dataset) for PM 1

In [3]:
dataset1 = raw_data.drop('id', axis=1)
for column in dataset1.columns[1:]:
    dataset1[column] = dataset1[column].fillna(dataset1[column].mean())

dataset1.diagnosis.replace(['M', 'B'], [1, -1], inplace=True)
dataset1

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0            1        17.99         10.38          122.80     1001.0   
1            1        20.57         17.77          132.90     1326.0   
2            1        19.69         21.25          130.00     1203.0   
3            1        11.42         20.38           77.58      386.1   
4            1        20.29         14.34          135.10     1297.0   
..         ...          ...           ...             ...        ...   
564          1        21.56         22.39          142.00     1479.0   
565          1        20.13         28.25          131.20     1261.0   
566          1        16.60         28.08          108.30      858.1   
567          1        20.60         29.33          140.10     1265.0   
568         -1         7.76         24.54           47.92      181.0   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0            0.11840           0.27760         0.30010              0.14710   
1            0.08474           0.07864         0.08690              0.07017   
2            0.10960           0.15990         0.19740              0.12790   
3            0.14250           0.28390         0.24140              0.10520   
4            0.10030           0.13280         0.19800              0.10430   
..               ...               ...             ...                  ...   
564          0.11100           0.11590         0.24390              0.13890   
565          0.09780           0.10340         0.14400              0.09791   
566          0.08455           0.10230         0.09251              0.05302   
567          0.11780           0.27700         0.35140              0.15200   
568          0.05263           0.04362         0.00000              0.00000   

     symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0           0.2419  ...        25.380          17.33           184.60   
1           0.1812  ...        24.990          23.41           158.80   
2           0.2069  ...        23.570          25.53           152.50   
3           0.2597  ...        14.910          26.50            98.87   
4           0.1809  ...        22.540          16.67           152.20   
..             ...  ...           ...            ...              ...   
564         0.1726  ...        25.450          26.40           166.10   
565         0.1752  ...        23.690          38.25           155.00   
566         0.1590  ...        18.980          34.12           126.70   
567         0.2397  ...        25.740          39.42           184.60   
568         0.1587  ...         9.456          30.37            59.16   

     area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0        2019.0           0.16220            0.66560           0.7119   
1        1956.0           0.12380            0.18660           0.2416   
2        1709.0           0.14440            0.42450           0.4504   
3         567.7           0.20980            0.86630           0.6869   
4        1575.0           0.13740            0.20500           0.4000   
..          ...               ...                ...              ...   
564      2027.0           0.14100            0.21130           0.4107   
565      1731.0           0.11660            0.19220           0.3215   
566      1124.0           0.11390            0.30940           0.3403   
567      1821.0           0.16500            0.86810           0.9387   
568       268.6           0.08996            0.06444           0.0000   

     concave points_worst  symmetry_worst  fractal_dimension_worst  
0                  0.2654          0.4601                  0.11890  
1                  0.1860          0.2750                  0.08902  
2                  0.2430          0.3613                  0.08758  
3                  0.2575          0.6638                  0.17300  
4                  0.1625          0.2364                  0.07678  
..                    .

## Dataset with feature engineering (Featured_Dataset) for PM 3

In [51]:
dataset3 = raw_data.drop('id', axis='columns')

for column in dataset3.columns[1:]:
    dataset3[column] = (dataset3[column] - dataset3[column].mean())/dataset3[column].std()
    
dataset3.diagnosis.replace(['M', 'B'], [1, -1], inplace=True)
dataset3.fillna(0, inplace=True)
dataset3

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0            1     1.101451     -2.071512        1.267272   0.983510   
1            1     1.835017     -0.353322        1.683156   1.907030   
2            1     1.584809      0.455786        1.563744   1.557513   
3            1    -0.766584      0.253509       -0.594733  -0.763792   
4            1     1.755405     -1.150804        1.773744   1.824624   
..         ...          ...           ...             ...        ...   
564          1     2.116502      0.720838        2.057863   2.341795   
565          1     1.709913      2.083301        1.613156   1.722326   
566          1     0.706235      2.043775        0.670212   0.577445   
567          1     1.843547      2.334403        1.979627   1.733693   
568         -1    -1.807224      1.220718       -1.816030  -1.346604   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0           1.567087          3.280628        2.648503             2.530249   
1          -0.826235         -0.486643       -0.025395             0.547662   
2           0.941382          1.052000        1.360467             2.035440   
3           3.280667          3.399917        1.912303             1.450431   
4           0.280125          0.538866        1.367992             1.427237   
..               ...               ...             ...                  ...   
564         1.040926          0.218868        1.943657             2.318924   
565         0.102368         -0.017817        0.690738             1.262558   
566        -0.839745         -0.038646        0.044965             0.105684   
567         1.524426          3.269267        3.291893             2.656528   
568        -3.109349         -1.149741       -1.115271            -1.260710   

     symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         2.215566  ...      1.885031      -1.358098         2.301575   
1         0.001391  ...      1.804340      -0.368879         1.533776   
2         0.938859  ...      1.510541      -0.023953         1.346291   
3         2.864862  ...     -0.281217       0.133866        -0.249720   
4        -0.009552  ...      1.297434      -1.465481         1.337363   
..             ...  ...           ...            ...              ...   
564      -0.312314  ...      1.899514       0.117596         1.751022   
565      -0.217473  ...      1.535369       2.045599         1.420690   
566      -0.808406  ...      0.560868       1.373645         0.578492   
567       2.135315  ...      1.959515       2.235958         2.301575   
568      -0.819349  ...     -1.409652       0.763518        -1.431475   

     area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      1.995136          1.306537           2.614365         2.105518   
1      1.884646         -0.375282          -0.430066        -0.147838   
2      1.451453          0.526944           1.081980         0.852589   
3     -0.550176          3.391291           3.889975         1.985735   
4      1.216442          0.220362          -0.313119         0.611107   
..          ...               ...                ...              ...   
564    2.009167          0.378033          -0.273077         0.662374   
565    1.490037         -0.690623          -0.394473         0.234988   
566    0.425471         -0.808876           0.350427         0.325065   
567    1.647881          1.429169           3.901415         3.192188   
568   -1.074743         -1.857384          -1.206491        -1.305420   

     concave points_worst  symmetry_worst  fractal_dimension_worst  
0                2.294058        2.748204                 1.935312  
1                1.086129       -0.243675                 0.280943  
2                1.953282        1.151242                 0.201214  
3                2.173873        6.040726                 4.930672  
4                0.728618       -0.867590                -0.396751  
..                    .

## Dataset formed by rearranging the features of Orignal_Dataset for PM 4

In [52]:
diagnosis = dataset1.diagnosis
dataset4 = dataset1.sample(frac=1, axis=1)
dataset4.drop('diagnosis', axis=1, inplace=True)
dataset4.insert(0, 'diagnosis', diagnosis)
dataset4

diagnosis  concave points_mean  fractal_dimension_mean  perimeter_se  \
0            1              0.14710                 0.07871         8.589   
1            1              0.07017                 0.05667         3.398   
2            1              0.12790                 0.05999         4.585   
3            1              0.10520                 0.09744         3.445   
4            1              0.10430                 0.05883         5.438   
..         ...                  ...                     ...           ...   
564          1              0.13890                 0.05623         7.673   
565          1              0.09791                 0.05533         5.203   
566          1              0.05302                 0.05648         3.425   
567          1              0.15200                 0.07016         5.772   
568         -1              0.00000                 0.05884         2.548   

     symmetry_se  smoothness_se  area_worst  texture_mean  symmetry_worst  \
0        0.03003       0.006399      2019.0         10.38          0.4601   
1        0.01389       0.005225      1956.0         17.77          0.2750   
2        0.02250       0.006150      1709.0         21.25          0.3613   
3        0.05963       0.009110       567.7         20.38          0.6638   
4        0.01756       0.011490      1575.0         14.34          0.2364   
..           ...            ...         ...           ...             ...   
564      0.01114       0.010300      2027.0         22.39          0.2060   
565      0.01898       0.005769      1731.0         28.25          0.2572   
566      0.01318       0.005903      1124.0         28.08          0.2218   
567      0.02324       0.006522      1821.0         29.33          0.4087   
568      0.02676       0.007189       268.6         24.54          0.2871   

     perimeter_worst  ...  compactness_se  area_mean  concavity_se  \
0             184.60  ...         0.04904     1001.0       0.05373   
1             158.80  ...         0.01308     1326.0       0.01860   
2             152.50  ...         0.04006     1203.0       0.03832   
3              98.87  ...         0.07458      386.1       0.05661   
4             152.20  ...         0.02461     1297.0       0.05688   
..               ...  ...             ...        ...           ...   
564           166.10  ...         0.02891     1479.0       0.05198   
565           155.00  ...         0.02423     1261.0       0.03950   
566           126.70  ...         0.03731      858.1       0.04730   
567           184.60  ...         0.06158     1265.0       0.07117   
568            59.16  ...         0.00466      181.0       0.00000   

     compactness_mean  fractal_dimension_se  concavity_worst  radius_mean  \
0             0.27760              0.006193           0.7119        17.99   
1             0.07864              0.003532           0.2416        20.57   
2             0.15990              0.004571           0.4504        19.69   
3             0.28390              0.009208           0.6869        11.42   
4             0.13280              0.005115           0.4000        20.29   
..                ...                   ...              ...          ...   
564           0.11590              0.004239           0.4107        21.56   
565           0.10340              0.002498           0.3215        20.13   
566           0.10230              0.003892           0.3403        16.60   
567           0.27700              0.006185           0.9387        20.60   
568           0.04362              0.002783           0.0000         7.76   

     compactness_worst  texture_se  texture_worst  
0              0.66560      0.9053          17.33  
1              0.18660      0.7339          23.41  
2              0.42450      0.7869          25.53  
3              0.86630      1.1560          26.50  
4              0.20500      0.7813          16.67  
..                 ...         ...            ...  
564            0.21130   

## Activating Function for Perceptron

In [53]:
def func(x):
    if x>=0:
        return 1
    else:
        return -1

## Perceptron Algorithm

In [89]:
def train_perceptron(training_set):
    w = np.zeros(31)
    for i in range(2000):
        for training_example in training_set:
            x = np.append(training_example[1:], 1)
            y = training_example[0]
            if y*func(w.dot(x))<0:
                w = w + y*x  
    return w

## Evaluation

In [90]:
def evaluate_perceptron(testing_set, w):
    c_mat = np.zeros((2, 2))
    for testing_example in testing_set:
        x = np.append(testing_example[1:], 1)
        y = testing_example[0]
        if y==1 and func(w.dot(x))==1:
            c_mat[1][1]+=1
            
        elif y==1 and func(w.dot(x))==-1:
            c_mat[1][0]+=1
            
        elif y==-1 and func(w.dot(x))==-1: 
            c_mat[0][0]+=1
            
        else:
            c_mat[0][1]+=1
            
    return c_mat

## Evaluation Metrics

In [91]:
def accuracy(c_mat):
    return (c_mat[0][0]+c_mat[1][1])/(c_mat[0][0] + c_mat[0][1] + c_mat[1][0] + c_mat[1][1])*100

def precision(c_mat):
    return (c_mat[0][0])/(c_mat[1][0] + c_mat[0][0])*100

def recall(c_mat):
    return (c_mat[1][1])/(c_mat[1][0] + c_mat[1][1])*100

## Spilting the Dataset into Training Data and Testing Data

In [92]:
training_data = dataset1.sample(frac=2/3)
training_data

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
353          1        15.08         25.74           98.00      716.6   
37          -1        13.03         18.42           82.61      523.8   
339          1        23.51         24.27          155.10     1747.0   
251         -1        11.50         18.45           73.28      407.4   
241         -1        12.42         15.04           78.61      476.5   
..         ...          ...           ...             ...        ...   
96          -1        12.18         17.84           77.79      451.1   
512          1        13.40         20.52           88.64      556.7   
393          1        21.61         22.28          144.40     1407.0   
310         -1        11.70         19.11           74.33      418.7   
154         -1        13.15         15.34           85.31      538.9   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
353          0.10240           0.09769         0.12350              0.06553   
37           0.08983           0.03766         0.02562              0.02923   
339          0.10690           0.12830         0.23080              0.14100   
251          0.09345           0.05991         0.02638              0.02069   
241          0.07926           0.03393         0.01053              0.01108   
..               ...               ...             ...                  ...   
96           0.10450           0.07057         0.02490              0.02941   
512          0.11060           0.14690         0.14450              0.08172   
393          0.11670           0.20870         0.28100              0.15620   
310          0.08814           0.05253         0.01583              0.01148   
154          0.09384           0.08498         0.09293              0.03483   

     symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
353         0.1647  ...         18.51          33.22           121.20   
37          0.1467  ...         13.30          22.81            84.46   
339         0.1797  ...         30.67          30.73           202.40   
251         0.1834  ...         12.97          22.46            83.12   
241         0.1546  ...         13.20          20.37            83.85   
..             ...  ...           ...            ...              ...   
96          0.1900  ...         12.83          20.92            82.14   
512         0.2116  ...         16.41          29.66           113.30   
393         0.2162  ...         26.23          28.74           172.00   
310         0.1936  ...         12.61          26.55            80.92   
154         0.1822  ...         14.77          20.50            97.67   

     area_worst  smoothness_worst  compactness_worst  concavity_worst  \
353      1050.0           0.16600            0.23560          0.40290   
37        545.9           0.09701            0.04619          0.04833   
339      2906.0           0.15150            0.26780          0.48190   
251       508.9           0.11830            0.10490          0.08105   
241       543.4           0.10370            0.07776          0.06243   
..          ...               ...                ...              ...   
96        495.2           0.11400            0.09358          0.04980   
512       844.4           0.15740            0.38560          0.51060   
393      2081.0           0.15020            0.57170          0.70530   
310       483.1           0.12230            0.10870          0.07915   
154       677.3           0.14780            0.22560          0.30090   

     concave points_worst  symmetry_worst  fractal_dimension_worst  
353               0.15260          0.2654                  0.09438  
37                0.05013          0.1987                  0.06169  
339               0.20890          0.2593                  0.07738  
251               0.06544          0.2740                  0.06487  
241               0.04052          0.2901                  0.06783  
..                    .

In [93]:
testing_data = dataset1.drop(training_data.index)
testing_data

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0            1       17.990         10.38          122.80     1001.0   
2            1       19.690         21.25          130.00     1203.0   
3            1       11.420         20.38           77.58      386.1   
9            1       12.460         24.04           83.97      475.9   
11           1       15.780         17.89          103.60      781.0   
..         ...          ...           ...             ...        ...   
557         -1        9.423         27.88           59.26      271.3   
563          1       20.920         25.09          143.00     1347.0   
565          1       20.130         28.25          131.20     1261.0   
567          1       20.600         29.33          140.10     1265.0   
568         -1        7.760         24.54           47.92      181.0   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0            0.11840           0.27760         0.30010              0.14710   
2            0.10960           0.15990         0.19740              0.12790   
3            0.14250           0.28390         0.24140              0.10520   
9            0.11860           0.23960         0.22730              0.08543   
11           0.09710           0.12920         0.09954              0.06606   
..               ...               ...             ...                  ...   
557          0.08123           0.04971         0.00000              0.00000   
563          0.10990           0.22360         0.31740              0.14740   
565          0.09780           0.10340         0.14400              0.09791   
567          0.11780           0.27700         0.35140              0.15200   
568          0.05263           0.04362         0.00000              0.00000   

     symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0           0.2419  ...        25.380          17.33           184.60   
2           0.2069  ...        23.570          25.53           152.50   
3           0.2597  ...        14.910          26.50            98.87   
9           0.2030  ...        15.090          40.68            97.65   
11          0.1842  ...        20.420          27.28           136.50   
..             ...  ...           ...            ...              ...   
557         0.1742  ...        10.490          34.24            66.50   
563         0.2149  ...        24.290          29.41           179.10   
565         0.1752  ...        23.690          38.25           155.00   
567         0.2397  ...        25.740          39.42           184.60   
568         0.1587  ...         9.456          30.37            59.16   

     area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0        2019.0           0.16220            0.66560           0.7119   
2        1709.0           0.14440            0.42450           0.4504   
3         567.7           0.20980            0.86630           0.6869   
9         711.4           0.18530            1.05800           1.1050   
11       1299.0           0.13960            0.56090           0.3965   
..          ...               ...                ...              ...   
557       330.6           0.10730            0.07158           0.0000   
563      1819.0           0.14070            0.41860           0.6599   
565      1731.0           0.11660            0.19220           0.3215   
567      1821.0           0.16500            0.86810           0.9387   
568       268.6           0.08996            0.06444           0.0000   

     concave points_worst  symmetry_worst  fractal_dimension_worst  
0                  0.2654          0.4601                  0.11890  
2                  0.2430          0.3613                  0.08758  
3                  0.2575          0.6638                  0.17300  
9                  0.2210          0.4366                  0.20750  
11                 0.1810          0.3792                  0.10480  
..                    .

## Training Perceptron using the above mentioned algorithm

In [94]:
training_set = training_data.to_numpy()
w1 = train_perceptron(training_set)
w1

array([-2.36443310e+04, -2.29676000e+03, -7.64903600e+04,  1.99900000e+02,
        3.39503310e+02,  2.09586851e+03,  3.18018472e+03,  1.26737593e+03,
        2.14596100e+02,  7.98697900e+01, -6.74193900e+02, -5.12945630e+03,
        4.37387000e+03,  2.32526470e+04,  3.35205140e+01,  5.28176475e+02,
        7.87052250e+02,  1.25271069e+02,  9.39257720e+01,  3.53912612e+01,
       -2.51265570e+04,  4.06978300e+04,  4.98327000e+03,  6.49540000e+03,
        8.49875170e+02,  8.14613482e+03,  1.03070375e+04,  2.55563854e+03,
        1.91011440e+03,  7.19221370e+02, -3.16800000e+03])

## Evaluating the Model on Testing Data

In [96]:
testing_set = testing_data.to_numpy()
n = evaluate_perceptron(testing_set, w1)
print(n)
print(f"Accuracy: {accuracy(n)}")
print(f"Precision: {precision(n)}")
print(f"Recall: {recall(n)}")

[[112.   5.]
 [  7.  66.]]
Accuracy: 93.6842105263158
Precision: 94.11764705882352
Recall: 90.41095890410958


In [97]:
training_set = dataset1.to_numpy()
testing_set = dataset1.to_numpy()

w = train_perceptron(training_set)
c_mat = evaluate_perceptron(testing_set, w)

print(c_mat)
print(f"Accuracy: {accuracy(c_mat)}")
print(f"Precision: {precision(c_mat)}")
print(f"Recall: {recall(c_mat)}")

[[342.  15.]
 [ 24. 188.]]
Accuracy: 93.14586994727593
Precision: 93.44262295081968
Recall: 88.67924528301887


## Perceptron Model 1

In [79]:
accuracy_list = np.zeros(10)
precision_list = np.zeros(10)
recall_list = np.zeros(10)
training_sets = []
w = np.zeros(31)
for i in range(10):
    
    training_data = dataset1.sample(frac=2/3)
    testing_data = dataset1.drop(training_data.index)
    training_sets.append(training_data)
    training_set = training_data.to_numpy()
    testing_set = testing_data.to_numpy()
    
    w = train_perceptron(training_set)
    c_mat = evaluate_perceptron(testing_set, w)
    
    print(f"Model No.{i+1}")
    print(f"Confusion Matrix:\n{c_mat}")
    print(f"Accuracy = {accuracy(c_mat)}")
    print(f"Precision = {precision(c_mat)}")
    print(f"Recall = {recall(c_mat)}")
    
    accuracy_list[i] =  accuracy(c_mat)
    precision_list[i] = precision(c_mat)
    recall_list[i] =  recall(c_mat)
    print("\n")
    
print(f"Accuracy:\n Mean = {accuracy_list.mean()}  Standard Deviation = {accuracy_list.std()}")
print(f"Precision:\n Mean = {precision_list.mean()}  Standard Deviation = {precision_list.std()}")
print(f"Recall:\n Mean = {recall_list.mean()}  Standard Deviation = {recall_list.std()}")

Model No.1
Confusion Matrix:
[[115.   3.]
 [ 12.  60.]]
Accuracy = 92.10526315789474
Precision = 90.5511811023622
Recall = 83.33333333333334


Model No.2
Confusion Matrix:
[[119.   1.]
 [ 10.  60.]]
Accuracy = 94.21052631578948
Precision = 92.24806201550388
Recall = 85.71428571428571


Model No.3
Confusion Matrix:
[[102.  17.]
 [  3.  68.]]
Accuracy = 89.47368421052632
Precision = 97.14285714285714
Recall = 95.77464788732394


Model No.4
Confusion Matrix:
[[112.   5.]
 [ 12.  61.]]
Accuracy = 91.05263157894737
Precision = 90.32258064516128
Recall = 83.56164383561644


Model No.5
Confusion Matrix:
[[110.   2.]
 [ 15.  63.]]
Accuracy = 91.05263157894737
Precision = 88.0
Recall = 80.76923076923077


Model No.6
Confusion Matrix:
[[116.   0.]
 [ 16.  58.]]
Accuracy = 91.57894736842105
Precision = 87.87878787878788
Recall = 78.37837837837837


Model No.7
Confusion Matrix:
[[109.   6.]
 [  8.  67.]]
Accuracy = 92.63157894736842
Precision = 93.16239316239316
Recall = 89.33333333333333


Model 

## Perceptron Model 2

In [80]:
accuracy_list = np.zeros(10)
precision_list = np.zeros(10)
recall_list = np.zeros(10)
w = np.zeros(31)
for i in range(10):
    
    training_data = training_sets[i].sample(frac=1)
    testing_data = dataset1.drop(training_data.index)
    training_set = training_data.to_numpy()
    testing_set = testing_data.to_numpy()
    
    w = train_perceptron(training_set)
    c_mat = evaluate_perceptron(testing_set, w)
    
    print(f"Model No.{i+1}")
    print(f"Confusion Matrix:\n{c_mat}")
    print(f"Accuracy = {accuracy(c_mat)}")
    print(f"Precision = {precision(c_mat)}")
    print(f"Recall = {recall(c_mat)}")
    
    accuracy_list[i] =  accuracy(c_mat)
    precision_list[i] = precision(c_mat)
    recall_list[i] =  recall(c_mat)
    print("\n")
    
print(f"Accuracy:\n Mean = {accuracy_list.mean()}  Standard Deviation = {accuracy_list.std()}")
print(f"Precision:\n Mean = {precision_list.mean()}  Standard Deviation = {precision_list.std()}")
print(f"Recall:\n Mean = {recall_list.mean()}  Standard Deviation = {recall_list.std()}")

Model No.1
Confusion Matrix:
[[115.   3.]
 [ 10.  62.]]
Accuracy = 93.15789473684211
Precision = 92.0
Recall = 86.11111111111111


Model No.2
Confusion Matrix:
[[98. 22.]
 [ 2. 68.]]
Accuracy = 87.36842105263159
Precision = 98.0
Recall = 97.14285714285714


Model No.3
Confusion Matrix:
[[117.   2.]
 [ 12.  59.]]
Accuracy = 92.63157894736842
Precision = 90.69767441860465
Recall = 83.09859154929578


Model No.4
Confusion Matrix:
[[108.   9.]
 [ 12.  61.]]
Accuracy = 88.94736842105263
Precision = 90.0
Recall = 83.56164383561644


Model No.5
Confusion Matrix:
[[112.   0.]
 [ 28.  50.]]
Accuracy = 85.26315789473684
Precision = 80.0
Recall = 64.1025641025641


Model No.6
Confusion Matrix:
[[110.   6.]
 [  9.  65.]]
Accuracy = 92.10526315789474
Precision = 92.43697478991596
Recall = 87.83783783783784


Model No.7
Confusion Matrix:
[[114.   1.]
 [ 21.  54.]]
Accuracy = 88.42105263157895
Precision = 84.44444444444444
Recall = 72.0


Model No.8
Confusion Matrix:
[[112.  11.]
 [  8.  59.]]
Accura

## Perceptron Model 3

In [2]:
accuracy_list = np.zeros(10)
precision_list = np.zeros(10)
recall_list = np.zeros(10)
w = np.zeros(31)
for i in range(10):
    
    training_data = dataset3.sample(frac=2/3)
    testing_data = dataset3.drop(training_data.index)
    training_set = training_data.to_numpy()
    testing_set = testing_data.to_numpy()
    
    w = train_perceptron(training_set)
    c_mat = evaluate_perceptron(testing_set, w)
    
    print(f"Model No.{i+1}")
    print(f"Confusion Matrix:\n{c_mat}")
    print(f"Accuracy = {accuracy(c_mat)}")
    print(f"Precision = {precision(c_mat)}")
    print(f"Recall = {recall(c_mat)}")
    
    accuracy_list[i] =  accuracy(c_mat)
    precision_list[i] = precision(c_mat)
    recall_list[i] =  recall(c_mat)
    print("\n")
    
print(f"Accuracy:\n Mean = {accuracy_list.mean()}  Standard Deviation = {accuracy_list.std()}")
print(f"Precision:\n Mean = {precision_list.mean()}  Standard Deviation = {precision_list.std()}")
print(f"Recall:\n Mean = {recall_list.mean()}  Standard Deviation = {recall_list.std()}")

NameError: name 'np' is not defined

## Perceptron Model 4

In [84]:
accuracy_list = np.zeros(10)
precision_list = np.zeros(10)
recall_list = np.zeros(10)
w = np.zeros(31)
for i in range(10):
    
    training_data = dataset4.sample(frac=2/3)
    testing_data = dataset4.drop(training_data.index)
    training_set = training_data.to_numpy()
    testing_set = testing_data.to_numpy()
    
    w = train_perceptron(training_set)
    c_mat = evaluate_perceptron(testing_set, w)
    
    print(f"Model No.{i+1}")
    print(f"Confusion Matrix:\n{c_mat}")
    print(f"Accuracy = {accuracy(c_mat)}")
    print(f"Precision = {precision(c_mat)}")
    print(f"Recall = {recall(c_mat)}")
    
    accuracy_list[i] =  accuracy(c_mat)
    precision_list[i] = precision(c_mat)
    recall_list[i] =  recall(c_mat)
    print("\n")
    
print(f"Accuracy:\n Mean = {accuracy_list.mean()}  Standard Deviation = {accuracy_list.std()}")
print(f"Precision:\n Mean = {precision_list.mean()}  Standard Deviation = {precision_list.std()}")
print(f"Recall:\n Mean = {recall_list.mean()}  Standard Deviation = {recall_list.std()}")

Model No.1
Confusion Matrix:
[[110.   2.]
 [ 14.  64.]]
Accuracy = 91.57894736842105
Precision = 88.70967741935483
Recall = 82.05128205128204


Model No.2
Confusion Matrix:
[[116.   0.]
 [ 19.  55.]]
Accuracy = 90.0
Precision = 85.92592592592592
Recall = 74.32432432432432


Model No.3
Confusion Matrix:
[[123.   4.]
 [ 11.  52.]]
Accuracy = 92.10526315789474
Precision = 91.7910447761194
Recall = 82.53968253968253


Model No.4
Confusion Matrix:
[[85. 35.]
 [ 0. 70.]]
Accuracy = 81.57894736842105
Precision = 100.0
Recall = 100.0


Model No.5
Confusion Matrix:
[[117.   3.]
 [ 16.  54.]]
Accuracy = 90.0
Precision = 87.96992481203007
Recall = 77.14285714285715


Model No.6
Confusion Matrix:
[[106.  22.]
 [  4.  58.]]
Accuracy = 86.31578947368422
Precision = 96.36363636363636
Recall = 93.54838709677419


Model No.7
Confusion Matrix:
[[96. 31.]
 [ 1. 62.]]
Accuracy = 83.15789473684211
Precision = 98.96907216494846
Recall = 98.4126984126984


Model No.8
Confusion Matrix:
[[118.   2.]
 [ 10.  60

Observation:
1. There is no substantial difference in results after changing the order of tuples in   training data as PM1 and PM3 has similar evaluation metrics.

2. Results improve substantially in PM3 as compared to PM1, PM2 and PM4 due to normalizations.

3. There is no substatial difference in results after chaniging the order of features in taining data as PM1 and PM4 has similar evaluation metrics.