In [1]:
import numpy as np

In [2]:
%precision 3

'%.3f'

In [3]:
data = np.array([9,2,3,7,8,4])

In [4]:
data.dtype

dtype('int64')

In [5]:
print(data.ndim)
print(data.size)

1
6


In [6]:
data*2

array([18,  4,  6, 14, 16,  8])

In [7]:
data**2

array([81,  4,  9, 49, 64, 16])

In [8]:
print('そのまま；', data)

そのまま； [9 2 3 7 8 4]


In [9]:
data.sort()
print('ソート後；', data)

ソート後； [2 3 4 7 8 9]


In [10]:
data[::-1].sort()
print(data)

[9 8 7 4 3 2]


In [11]:
data.max()

9

In [12]:
data.min()

2

In [13]:
data.sum()

33

In [14]:
data.cumsum()

array([ 9, 17, 24, 28, 31, 33])

In [15]:
data.cumsum() / data.sum()

array([0.273, 0.515, 0.727, 0.848, 0.939, 1.   ])

In [16]:
import numpy.random as random

In [17]:
ramdom.seed(0)
# 正規分布（平均0、分散1)の乱数を10個発生
rdn_data = random.randn(10)
print(rdn_data)

NameError: name 'ramdom' is not defined

In [18]:
random.seed(0)
rdn_data = random.randn(10)
print(rdn_data)

[ 1.764  0.4    0.979  2.241  1.868 -0.977  0.95  -0.151 -0.103  0.411]


In [19]:
print(random.choice(data,3))

[9 8 2]


In [20]:
print(random.choice(data,5, replace=False))

[7 4 3 2 9]


In [21]:
random.choice(data,3)

array([9, 4, 2])

In [23]:
N = 10**6

# Python版
normal_data = [random.random() for _ in range(N)]

# Numpy版
numpy_random_data = np.array(normal_data)

# calc time
%time sum(normal_data)
%time np.sum(numpy_random_data)

CPU times: user 5.83 ms, sys: 20 µs, total: 5.85 ms
Wall time: 5.87 ms
CPU times: user 740 µs, sys: 45 µs, total: 785 µs
Wall time: 575 µs


499894.278

In [24]:
np.array(9)

array(9)

In [25]:
np.arrange(9)

AttributeError: module 'numpy' has no attribute 'arrange'

In [26]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [27]:
array1 = np.arange(9).reshape(3,3)
print(array1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [29]:
array2 = np.arange(12).reshape(4,3)
print(array2)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [31]:
array1[0,:]

array([0, 1, 2])

In [33]:
print(array1[:,0])

[0 3 6]


In [34]:
array2 = np.arange(9,18).reshape(3,3)

In [35]:
print(array2)

[[ 9 10 11]
 [12 13 14]
 [15 16 17]]


In [37]:
#行列の積
np.dot(array1,array2)

array([[ 42,  45,  48],
       [150, 162, 174],
       [258, 279, 300]])

In [38]:
array1*array2

array([[  0,  10,  22],
       [ 36,  52,  70],
       [ 90, 112, 136]])

In [40]:
array3 = np.ones((5,5), dtype=np.int64)

In [41]:
array3*3

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [42]:
np.dot(array3, array3)

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [43]:
array3

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [44]:
array3 = array3*3

In [45]:
array3

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [46]:
np.dot(array3, array3)

array([[45, 45, 45, 45, 45],
       [45, 45, 45, 45, 45],
       [45, 45, 45, 45, 45],
       [45, 45, 45, 45, 45],
       [45, 45, 45, 45, 45]])