![](../storage/banners/40_assumptions.png)

##### Нечто, не напрямую связанное с НИР

In [8]:
import numpy as np

a = np.array([[0, 1],
              [-1, 0]])

_, v, _ = np.linalg.svd(a)
print(f"Сингулярные числа: {v}")

w, v = np.linalg.eig(a)
print(f"Собственные числа: {w}")

Сингулярные числа: [1. 1.]
Собственные числа: [0.+1.j 0.-1.j]


##### Быстродействие

`clip`: своё лучше для обычных чисел

In [43]:
from __init__ import *
import numpy as np
import time

n = int(1e6)

# Моя функция
def clip(a: float, bot: float, top: float) -> float:
    if a < bot:
        return bot
    if a > top:
        return top
    return a

t0 = time.time()
for _ in range(n):
    tmp = clip(-1, 0, 2)
print(f"my-clip: {time.time() - t0} секунд")

t0 = time.time()
for _ in range(n):
    tmp = np.clip(-1, 0, 2)
print(f"np.clip: {time.time() - t0} секунд")

my-clip: 0.14356112480163574 секунд
np.clip: 3.1530544757843018 секунд


In [ ]:
# import numpy as np
# s0 = dir(np)

In [ ]:
# s = dir(quaternion.np)
# for i in s0:
#     s.remove(i)
# s

**Инициализация**

In [18]:
import numpy as np
import quaternion

for q in [np.quaternion(1, 0, 0, 0),
          np.quaternion(1, 2, 3, 4),
          np.quaternion(5, 0, 0),
          np.quaternion(5),
          np.quaternion()]:
    print(f"q = {q}")

q = np.quaternion(1, 2, 3, 4)

q = quaternion(1, 0, 0, 0)
q = quaternion(1, 2, 3, 4)
q = quaternion(0, 5, 0, 0)
q = quaternion(5, 0, 0, 0)
q = quaternion(0, 0, 0, 0)


In [28]:
a = np.array([0, 0, 0.5])

q1 = quaternion.from_vector_part(a)
q2 = quaternion.from_euler_angles(a)

q3 = np.quaternion(np.sqrt(1 - np.linalg.norm(a)**2), *a)

print(f"Кватернион из вектора: {q1}")
print(f"Кватернион единичный из вектора: {q3}")
print(f"Кватернион из углов Эйлера: {q2}")

Кватернион из вектора: quaternion(0, 0, 0, 0.5)
Кватернион единичный из вектора: quaternion(0.866025403784439, 0, 0, 0.5)
Кватернион из углов Эйлера: quaternion(0.968912421710645, 0, 0, 0.247403959254523)


**Преобразования типов**

In [66]:
a = quaternion.as_float_array(q)
b = quaternion.np.array(q)
c = quaternion.np.asarray(q)
d = q.components

print(f"Как numpy-массив: {a}")
print(type(a))
print(f"Как numpy-массив: {b}")
print(type(b))
print(f"Как numpy-массив: {c}")
print(type(c))
print(f"Как numpy-массив: {d}")
print(type(d))

Как numpy-массив: [1. 2. 3. 4.]
<class 'numpy.ndarray'>
Как numpy-массив: quaternion(1, 2, 3, 4)
<class 'numpy.ndarray'>
Как numpy-массив: quaternion(1, 2, 3, 4)
<class 'numpy.ndarray'>
Как numpy-массив: [1. 2. 3. 4.]
<class 'numpy.ndarray'>


In [132]:
a = np.array([4, 5, 6, 7])

anw1 = np.append(a, q)
anw2 = np.append(a, q.components)

print(f"Плохой пример: {anw1}")
print(f"Хороший пример: {anw2}")

Плохой пример: [quaternion(4, 0, 0, 0) quaternion(5, 0, 0, 0) quaternion(6, 0, 0, 0)
 quaternion(7, 0, 0, 0) quaternion(1, 2, 3, 4)]
Хороший пример: [4. 5. 6. 7. 1. 2. 3. 4.]


**Преобразовани математические**

In [101]:
a = q.real
b = q.vec
w = q.w
x = q.x
y = q.y
z = q.z

print(f"Скалярная часть: {a}")
print(type(a))
print(f"Векторная часть: {b}")
print(type(b))
print(f"Составлющие: {w} {x} {y} {z}")
print(type(w), type(x), type(y), type(z))

Скалярная часть: 1.0
<class 'float'>
Векторная часть: [2. 3. 4.]
<class 'numpy.ndarray'>
Составлющие: 1.0 2.0 3.0 4.0
<class 'float'> <class 'float'> <class 'float'> <class 'float'>


In [103]:
a = quaternion.np.normalized(q)
b = q.normalized()

print(f"Нормированный кватернион: {a} | {b}")
print(type(a), type(b))

Нормированный кватернион: quaternion(0.182574185835055, 0.365148371670111, 0.547722557505166, 0.730296743340221) | quaternion(0.182574185835055, 0.365148371670111, 0.547722557505166, 0.730296743340221)
<class 'quaternion.quaternion'> <class 'quaternion.quaternion'>


In [99]:
a = quaternion.np.abs(q)
b = quaternion.np.absolute(q)
d = q.abs()

c = quaternion.np.norm(q)

print(f"Модуль: {a} | {b} | {d}")
print(type(a), type(b), type(d), '\n')

print(f"Норма: {c} (√c = {np.sqrt(c)})")
print(type(c))

Модуль: 5.477225575051661 | 5.477225575051661 | 5.477225575051661
<class 'numpy.float64'> <class 'numpy.float64'> <class 'float'> 

Норма: 30.0 (√c = 5.477225575051661)
<class 'numpy.float64'>


In [27]:
a = quaternion.np.angle_of_rotor(q)
b = q.angle()

print(f"Угол поворота: {a} | {b}")
print(type(a), type(b))

Угол поворота: 4.389231563842282 | 4.389231563842282
<class 'numpy.float64'> <class 'float'>


In [96]:
a = q.conj()
b = q.conjugate()

с = q.inverse()
d = q.reciprocal()

print(f"Сопряженный: {a} | {b}")
print(type(a), type(b), '\n')

print(f"Обратный: {с} | {d}")
print(type(с), type(d))

Сопряженный: quaternion(1, -2, -3, -4) | quaternion(1, -2, -3, -4)
<class 'quaternion.quaternion'> <class 'quaternion.quaternion'> 

Обратный: quaternion(0.0333333333333333, -0.0666666666666667, -0.1, -0.133333333333333) | quaternion(0.0333333333333333, -0.0666666666666667, -0.1, -0.133333333333333)
<class 'quaternion.quaternion'> <class 'quaternion.quaternion'>


In [125]:
A = quaternion.as_rotation_matrix(q)
B = quaternion.as_rotation_matrix(q.normalized())

print(f"Матрица поворота из кватерниона A: \n{A}")
print(f"Матрица поворота из кватерниона B: \n{B}")

Матрица поворота из кватерниона A: 
[[-0.66666667  0.13333333  0.73333333]
 [ 0.66666667 -0.33333333  0.66666667]
 [ 0.33333333  0.93333333  0.13333333]]
Матрица поворота из кватерниона B: 
[[-0.66666667  0.13333333  0.73333333]
 [ 0.66666667 -0.33333333  0.66666667]
 [ 0.33333333  0.93333333  0.13333333]]


##### Проверка <u>элементарных функций</u>

In [5]:
from __init__ import *
a = kf.get_vars("a", 3, numb=False)
kf.get_antisymmetric_matrix(a)

Matrix([
[   0, -a_z,  a_y],
[ a_z,    0, -a_x],
[-a_y,  a_x,    0]])

##### Проверка математики <u>вращения</u>

###### Умножение кватернионов

In [3]:
from __init__ import *
from sympy import *

q1 = kf.get_vars("q^1", 4, numb=False)
q2 = kf.get_vars("q^2", 4, numb=False)
q1v = Matrix(q1[1:4])
q2v = Matrix(q2[1:4])

print("Скалярная часть:")
q1[0]*q2[0] - q1v.dot(q2v)

Скалярная часть:


q^1_0*q^2_0 - q^1_x*q^2_x - q^1_y*q^2_y - q^1_z*q^2_z

In [4]:
print("Векторная часть:")
q1v*q2[0] + q2v*q1[0] + q1v.cross(q2v)

Векторная часть:


Matrix([
[q^1_0*q^2_x + q^1_x*q^2_0 + q^1_y*q^2_z - q^1_z*q^2_y],
[q^1_0*q^2_y - q^1_x*q^2_z + q^1_y*q^2_0 + q^1_z*q^2_x],
[q^1_0*q^2_z + q^1_x*q^2_y - q^1_y*q^2_x + q^1_z*q^2_0]])

###### Проверка угла поворота

$$\cos\alpha = \frac{1}{2} [ tr(S) - 1]$$ 

In [2]:
from __init__ import *
import numpy as np
import quaternion

q = np.quaternion(*np.random.uniform(-1, 1, 4)).normalized()
S = quaternion.as_rotation_matrix(q)

cos_alpha = kf.clip((np.trace(S) - 1) / 2, -1, 1)
print(f"Косинус по формуле: {cos_alpha}")
print(f"Косинус из модуля: {np.cos(quaternion.np.angle_of_rotor(quaternion.from_rotation_matrix(S)))}")

Косинус по формуле: 0.5884554447041483
Косинус из модуля: 0.5884554447041487


In [9]:
phi = var('varphi')
r = kf.get_vars(name='r', n=3, numb=False)

for q in [kf.vec2quat(kf.get_vars(name='q', n=3, numb=False)),
          kf.get_q_Rodrigue_Hamilton(phi=phi, r=r, symbol=True)]:
    print(f"При кватернионе")
    display(q.T)
    M = kf.quart2dcm(q)
    cos_s = kf.matrix2angle(M)
    print(f"косинус:")
    display(cos_s.simplify())

При кватернионе


Matrix([[sqrt(-q_x**2 - q_y**2 - q_z**2 + 1), q_x, q_y, q_z]])

косинус:


-2*q_x**2 - 2*q_y**2 - 2*q_z**2 + 1

При кватернионе


Matrix([[cos(varphi/2), r_x*sin(varphi/2)/sqrt(r_x**2 + r_y**2 + r_z**2), r_y*sin(varphi/2)/sqrt(r_x**2 + r_y**2 + r_z**2), r_z*sin(varphi/2)/sqrt(r_x**2 + r_y**2 + r_z**2)]])

косинус:


cos(varphi)

###### Сравнение старого и нового кода

<u>Старый код</u>

In [3]:
from __init__ import *
import numpy as np
import quaternion

def vec2quat_old(v) -> list:
    if len(v) != 3:
        raise ValueError(f"Подаётся вектор длинны {len(v)}, требуется длинна 3!")
    if np.linalg.norm(v) > 1:
        return [0] + list(np.array(v)/np.linalg.norm(v))
    else:
        return [np.sqrt(1 - np.linalg.norm(v)**2), v[0], v[1], v[2]]

def q_dot_old(L1, L2):
    return np.array([L1[0] * L2[0] - L1[1] * L2[1] - L1[2] * L2[2] - L1[3] * L2[3],
                     L1[0] * L2[1] + L1[1] * L2[0] + L1[2] * L2[3] - L1[3] * L2[2],
                     L1[0] * L2[2] + L1[2] * L2[0] + L1[3] * L2[1] - L1[1] * L2[3],
                     L1[0] * L2[3] + L1[3] * L2[0] + L1[1] * L2[2] - L1[2] * L2[1]])

def quart2dcm_old(L) -> np.ndarray:
    w, x, y, z = L
    A = np.eye(3)
    A[0][0] = 1 - 2 * y ** 2 - 2 * z ** 2
    A[0][1] = 2 * x * y + 2 * z * w
    A[0][2] = 2 * x * z - 2 * y * w
    A[1][0] = 2 * x * y - 2 * z * w
    A[1][1] = 1 - 2 * x ** 2 - 2 * z ** 2
    A[1][2] = 2 * y * z + 2 * x * w
    A[2][0] = 2 * x * z + 2 * y * w
    A[2][1] = 2 * y * z - 2 * x * w
    A[2][2] = 1 - 2 * x ** 2 - 2 * y ** 2
    return A

def check_quat(q1, q2, q_dot, quart2dcm, vec2quat):
    print(f"λ₁ = {q1}")
    if isinstance(q1, list | np.ndarray):
        print(f"q3->q4: {vec2quat(q1[1:4])}")
        if isinstance(vec2quat(q1[1:4]), list | np.ndarray):
            print(f"модуль {vec2quat(q1[1:4])} = {np.linalg.norm(vec2quat(q1[1:4]))})")
    if isinstance(q1, quaternion.quaternion):
        q_new = vec2quat(q1.vec)
        print(f"q3->q4: {q_new}")
        print(f"модуль {q_new} = {q_new.abs()})")
    print(f"λ₂ = {q2}")
    print(f"λ₁∘λ₂ = {q_dot(q1, q2)}\n")

    A = quart2dcm(q1)
    print(f"A(λ₁) = \n{A} (type(A)={type(A)}) \nДетерминант {np.linalg.det(A)}, \nAA.T=\n{np.round(A @ A.T).astype(np.int64)}")

qs = [np.random.rand(4) for _ in range(2)]
for i in range(2):
    qs[i] /= np.linalg.norm(qs[i])

check_quat(qs[0], qs[1], q_dot_old, quart2dcm_old, vec2quat_old)

λ₁ = [0.59379408 0.54259116 0.42124688 0.41899223]
q3->q4: [0.5937940769627631, 0.5425911603820692, 0.4212468812216982, 0.4189922336991132]
модуль [0.5937940769627631, 0.5425911603820692, 0.4212468812216982, 0.4189922336991132] = 1.0)
λ₂ = [0.14235516 0.08436462 0.80418151 0.57088503]
λ₁∘λ₂ = [-0.53920119  0.03087359  0.26307584  0.7994373 ]

A(λ₁) = 
[[ 0.29399315  0.95471988 -0.04558484]
 [-0.04046055  0.06008068  0.99737318]
 [ 0.95495077 -0.29137649  0.0562918 ]] (type(A)=<class 'numpy.ndarray'>) 
Детерминант 1.0000000000000007, 
AA.T=
[[1 0 0]
 [0 1 0]
 [0 0 1]]


<u>Новый код</u>

In [4]:
for i in range(2):
    qs[i] = np.quaternion(*qs[i])

In [5]:
import numpy as np
import quaternion

def vec2quat(v):
    """Перевод вектора кватерниона в кватернион"""
    if isinstance(v, np.ndarray):
        return np.quaternion(np.sqrt(1 - np.linalg.norm(v)**2), *v)
    else:
        from sympy import Matrix, sqrt
        return Matrix([sqrt(1 - v.dot(v)), v[0], v[1], v[2]])

def q_dot(q1, q2):
    """Умножение кватернионов длины 4"""
    if isinstance(q1, quaternion.quaternion):
        return q1 * q2
    else:
        from sympy import Matrix
        q1v = Matrix(q1[1:4])
        q2v = Matrix(q2[1:4])
        scalar = q1[0]*q2[0] - q1v.dot(q2v)
        vector = q1v*q2[0] + q2v*q1[0] + q1v.cross(q2v)
        return Matrix([scalar, vector[0], vector[1], vector[2]])

def quart2dcm(q):
    """Матрицу поворота из кватерниона поворота"""
    if isinstance(q, quaternion.quaternion):
        return quaternion.as_rotation_matrix(q)
    else:
        from sympy import Matrix, sqrt
        w, x, y, z = q
        return Matrix([[1 - 2*y**2 - 2*z**2, 2*x*y + 2*z*w, 2*x*z - 2*y*w],
                       [2*x*y - 2*z*w, 1 - 2*x**2 - 2*z**2, 2*y*z + 2*x*w],
                       [2*x*z + 2*y*w, 2*y*z - 2*x*w, 1 - 2*x**2 - 2*y**2]]).T

check_quat(qs[0], qs[1], q_dot, quart2dcm, vec2quat)

λ₁ = quaternion(0.593794076962763, 0.542591160382069, 0.421246881221698, 0.418992233699113)
q3->q4: quaternion(0.593794076962763, 0.542591160382069, 0.421246881221698, 0.418992233699113)
модуль quaternion(0.593794076962763, 0.542591160382069, 0.421246881221698, 0.418992233699113) = 1.0)
λ₂ = quaternion(0.142355162244286, 0.0843646240423645, 0.804181513135995, 0.570885025134566)
λ₁∘λ₂ = quaternion(-0.539201193299804, 0.0308735946157745, 0.263075841464506, 0.799437299565957)

A(λ₁) = 
[[ 0.29399315 -0.04046055  0.95495077]
 [ 0.95471988  0.06008068 -0.29137649]
 [-0.04558484  0.99737318  0.0562918 ]] (type(A)=<class 'numpy.ndarray'>) 
Детерминант 1.0000000000000007, 
AA.T=
[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [ ]:
# Копия старых результатов
"""
λ₁ = [0.59379408 0.54259116 0.42124688 0.41899223]
q3->q4: [0.5937940769627631, 0.5425911603820692, 0.4212468812216982, 0.4189922336991132]
модуль [0.5937940769627631, 0.5425911603820692, 0.4212468812216982, 0.4189922336991132] = 1.0)
λ₂ = [0.14235516 0.08436462 0.80418151 0.57088503]
λ₁∘λ₂ = [-0.53920119  0.03087359  0.26307584  0.7994373 ]

A(λ₁) = 
[[ 0.29399315  0.95471988 -0.04558484]
 [-0.04046055  0.06008068  0.99737318]
 [ 0.95495077 -0.29137649  0.0562918 ]] (type(A)=<class 'numpy.ndarray'>) 
Детерминант 1.0000000000000007, 
AA.T=
[[1 0 0]
 [0 1 0]
 [0 0 1]]
"""
None

*ТАК а почему матрица транспонированная-то была?*

<u>Проверка матрицы из кватернионов</u><br>
Поворот на $90^\circ$ вокруг оси $Oz$: 
$$\lambda = [\cos\frac{\varphi}{2}, 0, 0, \sin\frac{\varphi}{2}]$$
$$x\to y, \hskip20px y \to -x$$

In [39]:
import numpy as np
import quaternion

q1 = np.quaternion(1, 0, 0, 1).normalized()
A = quart2dcm(q1)
A = np.round(A).astype(np.int64)
print(f"A: \n{A}\n")

a = np.array([1, 0, 0])
print(f"x->y: {a} -> {A @ a}")

a = np.array([0, 1, 0])
print(f"y->-x: {a} -> {A @ a}")

A: 
[[ 0 -1  0]
 [ 1  0  0]
 [ 0  0  1]]

x->y: [1 0 0] -> [0 1 0]
y->-x: [0 1 0] -> [-1  0  0]


##### Проверка работоспособности <u>символьного полиморфизма</u>

In [12]:
from __init__ import *
from sympy import *
import numpy as np
import quaternion

vrs = kf.Variables()
kf.IF_TEST_PRINT = False

r_n = vrs.spread('r', 'FemtoSat')
v_n = vrs.spread('v', 'FemtoSat')
w_n, mu_n, t_n = vrs.W_ORB, vrs.MU, 0
print(f"Численные параметры: r={r_n}, v={v_n}, t={t_n}")

r_s = kf.get_vars(name='r', n=3, numb=False)
v_s = kf.get_vars(name='v', n=3, numb=False)
J = kf.get_vars("J", 3, numb=False)
w1 = [kf.get_vars(name='w', n=3, numb=False)]
q_s = kf.vec2quat(kf.get_vars(name='q', n=3, numb=False))
w_s, mu_s, rho, t_s = symbols("omega_0 mu rho t")
print(f"Символьные параметры:")
display(r_s.T, v_s.T)

Параметры не могут быть загружены! Нет файла: kiamformation/data/config_choose.csv
Численные параметры: r=[-90.27996318  69.30782261 -26.11009638], v=[-0.07727089 -0.04603508  0.07598842], t=0
Символьные параметры:


Matrix([[r_x, r_y, r_z]])

Matrix([[v_x, v_y, v_z]])

###### Движение ХКУ

In [3]:
kf.my_print(f"Константы С движения ХКУ:", bold=True)
C_n = kf.get_c_hkw(r=r_n, v=v_n, w=w_n)
C_s = kf.get_c_hkw(r=r_s, v=v_s, w=w_s)
print(C_n)
display(C_s)

kf.my_print(f"\nРадиус-вектор из констант C: (для t=t / для t=0)", bold=True)
print(kf.r_hkw(C=C_n, w=w_n, t=t_n))
r_anw = kf.r_hkw(C=C_s, w=w_s, t=t_s)
display(r_anw)
display(r_anw.subs(t_s, 0))

kf.my_print(f"\nСкорость-вектор из констант C: (для t=t / для t=0)", bold=True)
print(kf.v_hkw(C=C_n, w=w_n, t=t_n))
v_anw = kf.v_hkw(C=C_s, w=w_s, t=t_s)
display(v_anw)
tmp = v_anw.subs(t_s, 0)
tmp.simplify()
display(tmp)

Константы С движения ХКУ:
[-216.93427702360907, 10.285586992149572, 347.72737356096366, 47.433847399923856, 30.995302724983866, -76.6593313002907]


Matrix([
[   2*r_z + v_x/omega_0],
[           v_z/omega_0],
[-3*r_z - 2*v_x/omega_0],
[   r_x - 2*v_z/omega_0],
[           v_y/omega_0],
[                   r_y]])


Радиус-вектор из констант C: (для t=t / для t=0)
[ 68.00502138 -76.6593313  -86.14118049]


Matrix([
[omega_0*t*(-6*r_z - 3*v_x/omega_0) + r_x - (-6*r_z - 4*v_x/omega_0)*sin(omega_0*t) + 2*v_z*cos(omega_0*t)/omega_0 - 2*v_z/omega_0],
[                                                                                  r_y*cos(omega_0*t) + v_y*sin(omega_0*t)/omega_0],
[                                     4*r_z + (-3*r_z - 2*v_x/omega_0)*cos(omega_0*t) + 2*v_x/omega_0 + v_z*sin(omega_0*t)/omega_0]])

Matrix([
[r_x],
[r_y],
[r_z]])


Скорость-вектор из констант C: (для t=t / для t=0)
[-0.05059594  0.03512137  0.0116548 ]


Matrix([
[omega_0*(-6*r_z - 3*v_x/omega_0) - 2*omega_0*(-3*r_z - 2*v_x/omega_0)*cos(omega_0*t) - 2*v_z*sin(omega_0*t)],
[                                                           -omega_0*r_y*sin(omega_0*t) + v_y*cos(omega_0*t)],
[                                       omega_0*(-3*r_z - 2*v_x/omega_0)*sin(omega_0*t) + v_z*cos(omega_0*t)]])

Matrix([
[v_x],
[v_y],
[v_z]])

###### Поступательное движение

In [1]:
vrs = kf.Variables()
o = kf.Objects(vrs)

print(f"На высоте {round(vrs.HEIGHT // 1e3)} км плотность ρ={kf.get_atm_params(v=vrs, h=vrs.HEIGHT)[0]} кг/м³")
for drag in [False, True]:
    vrs.DYNAMIC_MODEL['aero drag'] = drag
    tmp = kf.translate_rhs(vrs=vrs, obj=o.f, i=0, rv=np.append(r_n, v_n), w=w_n, mu=mu_n)
    v_g_n, a_g_n = tmp[[0, 1, 2]], tmp[[3, 4, 5]]
    kf.my_print(f"Скорость в ОСК {'с торможением' if drag else 'без торможения'}:", bold=True, end='')
    print(v_g_n)
    kf.my_print(f"Ускорение в ОСК {'с торможением' if drag else 'без торможения'}:", bold=True, end='')
    print(a_g_n)

o.f.c_resist, vrs.V_ORB, o.f.mass = var('C v_0 m')
o.f.size = kf.get_vars(name='s', n=2)
o.f.q = [q_s]
o.f.r = [r_n]
o.f.v = [v_n]

for drag in [False, True]:
    vrs.DYNAMIC_MODEL['aero drag'] = drag
    v_g_s, a_g_s = kf.translate_rhs(vrs=vrs, obj=o.f, i=0, rv=(r_s, v_s), w=w_s, mu=mu_s, rho=rho)
    kf.my_print(f"Скорость в ОСК {'с торможением' if drag else 'без торможения'}:", bold=True, end='')
    display(v_g_s)
    kf.my_print(f"Ускорение в ОСК {'с торможением' if drag else 'без торможения'}:", bold=True)
    display(a_g_s)

NameError: name 'kf' is not defined

###### Вращательное движение

In [4]:
vrs = kf.Variables()
o = kf.Objects(vrs)

obj = o.f

tmp = kf.attitude_rhs(v=vrs, obj=obj, t=0, i=0, qw=np.append(quaternion.as_float_array(obj.q[0]), obj.w_irf[0]))  # attitude_rhs(v: Variables, obj: Apparatus, t: float, i: int, qw)
dq_n, dw_n = tmp[[0, 1, 2, 3]], tmp[[4, 5, 6]]
kf.my_print(f"Угловое ускорение:", bold=True)
print(dw_n)


Параметры не могут быть загружены! Нет файла: kiamformation/data/config_choose.csv
Матрицы Ф:(6, 6), Q:(3, 3), P:(6, 6), D:(6, 3)
Угловое ускорение:
[4.00703393e-09 6.19202035e-08 0.00000000e+00]


###### Математика

In [4]:
a = np.arange(1, 10).reshape(3, 3)
m = Matrix(a)

i, j = 1, 2

print(f"Минор матрицы: {kf.matrix_minor(a, i, j)} = {kf.matrix_minor(m, i, j)}")

Минор матрицы: -6.0 = -6


###### Измерения

In [ ]:
from common_func import *
o, num_params, t, ω, μ, ρ, r_orb, v_orb = init_symbol_params()

o.v.NAVIGATION_ANGLES = True
r_c, v_c, q_c, ω_c = get_state_vector(func=kf.get_func, obj='c')
o.c.r_orf, o.c.v_orf, o.c.q, o.c.w_irf = r_c, v_c, q_c, ω_c

r = kf.get_vars(name='r', n=3, numb=False)
v = kf.get_vars(name='v', n=3, numb=False)
q3 = kf.get_vars(name='q', n=3, numb=False) 
q4 = kf.vec2quat(q3)
w = kf.get_vars(name='w', n=3, numb=False)

kf.my_print(f"Полуволновой диполь:")
display(kf.local_dipole(v=o.v, r=r, ind='x'))

o.v.GAIN_MODEL_C_N = 2
o.v.GAIN_MODEL_F_N = 2
o.v.init_choice_params()
o.c.gain_mode = o.v.GAIN_MODEL_C
o.f.gain_mode = o.v.GAIN_MODEL_F
o.v.MULTI_ANTENNA_TAKE = True
o.v.MULTI_ANTENNA_SEND = True

x_m = kf.sympy_append(r, q3, v, w)
z_model, notes = kf.measure_antennas_power(c=o.c, f=o.f, v=o.v, p=o.p, j=len(x_m), estimated_params=x_m, t=t_s)
print(f"Модельные измерения:")
display(z_model)

In [4]:
o.v.GAIN_MODEL_F

'2 antennas'

In [5]:
kf.sympy_norm(r)

sqrt(r_x**2 + r_y**2 + r_z**2)

###### Навигация

In [15]:
o = kf.init()

for i in range(2):
    o.v.dT = var('dt')
    o.f.J = diag(J[0], J[1], J[2])
    display(o.f.J)
    
    kf.my_print([f"Оценка орбитального{['', ' и углового'][i]} движения"], color='m', bold=True)

    kf.my_print(f"Матрица линеаризованной динамики Ф:", bold=True)
    display(o.p.k.get_Phi(w=w1, w0=w_s))

    # Поправки на угловое движение
    o.v.NAVIGATION_ANGLES = True
    o.init_classes()

Параметры не могут быть загружены! Нет файла: kiamformation/data/config_choose.csv
Матрицы Ф:(6, 6), Q:(3, 3), P:(6, 6), D:(6, 3)


Matrix([
[J_x,   0,   0],
[  0, J_y,   0],
[  0,   0, J_z]])

['Оценка орбитального движения']
Матрица линеаризованной динамики Ф:


Matrix([
[1.0,              0,               0,           dt,   0,             0],
[  0,            1.0,               0,            0,  dt,             0],
[  0,              0,             1.0,            0,   0,            dt],
[  0,              0,               0,          1.0,   0, -2*dt*omega_0],
[  0, -dt*omega_0**2,               0,            0, 1.0,             0],
[  0,              0, 3*dt*omega_0**2, 2*dt*omega_0,   0,           1.0]])

Матрицы Ф:(12, 12), Q:(6, 6), P:(12, 12), D:(12, 6)


Matrix([
[J_x,   0,   0],
[  0, J_y,   0],
[  0,   0, J_z]])

['Оценка орбитального и углового движения']
Матрица линеаризованной динамики Ф:


Matrix([
[1.0,              0,               0,   0,   0,   0,           dt,   0,             0,                        0,                       0,                        0],
[  0,            1.0,               0,   0,   0,   0,            0,  dt,             0,                        0,                       0,                        0],
[  0,              0,             1.0,   0,   0,   0,            0,   0,            dt,                        0,                       0,                        0],
[  0,              0,               0, 1.0,   0,   0,            0,   0,             0,                   0.5*dt,                       0,                        0],
[  0,              0,               0,   0, 1.0,   0,            0,   0,             0,                        0,                  0.5*dt,                        0],
[  0,              0,               0,   0,   0, 1.0,            0,   0,             0,                        0,                       0,                   0.5*

Матрицы Ф:(12, 12), Q:(6, 6), P:(12, 12), D:(12, 6)


##### Проверка соответствия <u>символьного и численного</u> матана

In [11]:
from sympy import *
import numpy as np
import quaternion

q1 = np.array([1, 2, 3, 4])
q2 = np.array([1, 2, 3, 4])

q1_n = np.quaternion(*q1).normalized()
q2_n = np.quaternion(*q2).normalized()
print(f"Численные кватернионы:\nq1 = {q1_n}\nq2 = {q2_n}\n")

q1_s = Matrix(q1 / np.linalg.norm(q1))
q2_s = Matrix(q2 / np.linalg.norm(q2))
print(f"Символьные кватернионы:\nq1 = {q1_s}\nq2 = {q2_s}")



Численные кватернионы:
q1 = quaternion(0.182574185835055, 0.365148371670111, 0.547722557505166, 0.730296743340221)
q2 = quaternion(0.182574185835055, 0.365148371670111, 0.547722557505166, 0.730296743340221)

Символьные кватернионы:
q1 = Matrix([[0.182574185835055], [0.365148371670111], [0.547722557505166], [0.730296743340221]])
q2 = Matrix([[0.182574185835055], [0.365148371670111], [0.547722557505166], [0.730296743340221]])


##### Проверка <u>динамики</u>

###### Тензор инерции

In [6]:
# Предположение - тело равномерно распределено ... а потом смещение ЦМ ... потом ...
# Новое предположение - тензор инерции ДИАНОГАЛЬНЫЙ!
m, xx, yy, zz = var("m xx yy zz", real=True, constant=True)  # Масса и размеры
J_3d = m*(xx**2 + yy**2)/12
J_2d = m*(xx**2)/12

print(f"По нормали к поверхности чипсата:")
display(J_3d)
print(f"В плоскости поверхности чипсата:")
display(J_2d)

По нормали к поверхности чипсата:


m*(xx**2 + yy**2)/12

В плоскости поверхности чипсата:


m*xx**2/12

###### Направление угловой скорости поворота ОСК в ИСК

In [8]:
from common_func import *
e, i = var("e i")
U_1, S_1 = get_U_S(A=A, w_0=w_0, t=t, ECCENTRICITY=e, INCLINATION=i)
w_0_vec_irf = U_1.T @ Matrix([0, 1, 0])

print(f"При наклонении {i} и эксцентриситете {e} будет следующий вид матрицы U:")
display(U_1)
print(f"При этом, направление угловой скорости вращения в ИСК:")
display(w_0_vec_irf)

NameError: name 'A' is not defined