In [14]:
result

array([ 23, 999,  21, 999,  31, 999, 999, 999, 999, 999])

In [4]:
np.load("../original_data/average_death_rates.npy")

# 1-4

array([1.0000e-04, 1.0000e-04, 1.0000e-04, 2.0000e-04, 2.4000e-04,
       2.8000e-04, 3.8000e-04, 5.0000e-04, 8.2000e-04, 1.4000e-03,
       2.3800e-03, 3.9600e-03, 6.2400e-03, 9.7800e-03, 1.6720e-02,
       2.9260e-02, 5.1780e-02, 1.1042e-01])

In [2]:
import os
import pandas as pd

# Get the current working directory
current_dir = os.getcwd()

# Get the parent directory
parent_dir = os.path.dirname(current_dir)

# Get the parent's parent directory
parents_parent_dir = os.path.dirname(parent_dir)

# Construct the path to the CSV file
csv_path = os.path.join('aggregated_ASFR.csv')

# Read the CSV file
ASFR = pd.read_csv(csv_path)

# Display the first few rows of the dataframe to verify
print(ASFR.head())


         V1        V2        V3        V4        V5        V6        V7  \
0  0.000275  0.000530  0.000983  0.001752  0.002999  0.004935  0.007804   
1  0.000276  0.000535  0.000997  0.001784  0.003069  0.005073  0.008057   
2  0.000231  0.000449  0.000841  0.001512  0.002612  0.004336  0.006918   
3  0.000216  0.000422  0.000793  0.001432  0.002486  0.004146  0.006645   
4  0.000192  0.000378  0.000714  0.001295  0.002258  0.003782  0.006089   

         V8        V9       V10  ...       V26       V27       V28       V29  \
0  0.011857  0.017311  0.024285  ...  0.024164  0.017213  0.011783  0.007750   
1  0.012298  0.018037  0.025420  ...  0.027205  0.019468  0.013387  0.008846   
2  0.010606  0.015625  0.022119  ...  0.025413  0.018267  0.012617  0.008374   
3  0.010233  0.015143  0.021533  ...  0.026586  0.019196  0.013318  0.008879   
4  0.009419  0.014001  0.019999  ...  0.026528  0.019240  0.013409  0.008980   

        V30       V31       V32       V33       V34       V35  
0  0

In [3]:
# Initialize the output matrix of size 50x11
import numpy as np
output_matrix = np.zeros((50, 11))

# Populate the output matrix based on the rules specified
for age in range(50):  # Age from 0 to 49
    for year_offset in range(11):  # Year from 2024 to 2034 (0 to 10 offset from 2024)
        asfr_row = year_offset + 1  # Row in ASFR matrix (corresponding to 2024+offset)
        asfr_col = age + year_offset - 15  # Column in ASFR matrix (age+offset-15)
        
        # Check if the indices are within the valid range of the ASFR matrix
        if 1 <= asfr_row < 28 and 0 <= asfr_col < 35:
            output_matrix[age, year_offset] = ASFR.iloc[asfr_row, asfr_col]

# The output matrix is now populated
print(output_matrix)


[[0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00

In [5]:
print( os.getcwd())

c:\Users\Haolong\Documents\GitHub\zika_project(reformatted)\original_data


In [4]:
np.save('FRBY.npy', output_matrix)

In [11]:
FR_matrix[25,]

array([0.03442487, 0.03932692, 0.04874138, 0.05587568, 0.06341026,
       0.06962226, 0.07417742, 0.07654831, 0.07640995, 0.07398883,
       0.06578068])

In [24]:
# generate a random matrix, 
# 
# and childbearing_females[:,5] = childbearing_females[:,2] + np.randint(0,15)
childbearing_females = np.array(
      [
            [1,0,25,0,0,30],
            [2,0,25,0,0,999]
      ]
)

FR_matrix = np.load("FRBY.npy") 
female_indices = childbearing_females[:,0]
ages_of_add = childbearing_females[:,2] # the 2nd col from 0 
ages_of_death = childbearing_females[:,5]

num_year = 10
# our output is  
output_matrix = np.zeros((len(female_indices), num_year+1))
# construct prob matrix
for i, age in enumerate(ages_of_add):
        output_matrix[i, :] = FR_matrix[age, :]

num_year = 10 
random_matrix = np.random.rand( len(female_indices), num_year+1)
birth_matrix = (random_matrix <output_matrix ).astype(np.int32)

print(birth_matrix)



endpoints = np.minimum(ages_of_death - ages_of_add, 11)
col_indices = np.arange(num_year +1 )
mask = col_indices >= endpoints[:, None]
birth_matrix[mask] = 0

print(birth_matrix)

birth_years = []
for row in birth_matrix:
    nonzero_indices = list(np.nonzero(row)[0])
    birth_years.append(nonzero_indices)





[[1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1]]
[[1 1 1 1 1 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1 1 1 1]]


In [ ]:
       0 - index
        1 - yearOfAdd
        2 - AgeOfAdd (age + 1)
        3 - age
        4 - gender (1 for male, 2 for female)
        5 - deathAge

In [26]:
[1,2,3] +5

TypeError: can only concatenate list (not "int") to list

In [ ]:
    # List: Generally more memory-efficient for small collections of elements.
    new_born_list = []

In [ ]:
# cannot expect to solve all the problems in one step 

In [25]:
birth_years

[[0, 1, 2, 3, 4], [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]]

In [29]:
np.load("average_death_rates.npy")

array([1.0000e-04, 1.0000e-04, 1.0000e-04, 2.0000e-04, 2.4000e-04,
       2.8000e-04, 3.8000e-04, 5.0000e-04, 8.2000e-04, 1.4000e-03,
       2.3800e-03, 3.9600e-03, 6.2400e-03, 9.7800e-03, 1.6720e-02,
       2.9260e-02, 5.1780e-02, 1.1042e-01])

In [30]:
age = np.array([range(10)])
cat = age // 5

In [33]:
death_rate

NameError: name 'death_rate' is not defined

In [34]:
random_matrix

array([[4.42859853e-01, 3.29348751e-02, 5.98623145e-01, 5.61208800e-01,
        6.40573770e-01, 1.80492052e-01, 9.13730232e-01, 8.56246018e-01,
        3.30953373e-01, 1.93694342e-01],
       [1.19341423e-01, 7.81980512e-02, 4.48404308e-01, 4.26619274e-01,
        4.97306654e-01, 8.44595535e-01, 4.65999274e-01, 3.65162261e-01,
        3.86538192e-01, 5.32188586e-01],
       [6.84575656e-01, 7.12808740e-01, 2.62621625e-02, 5.48639634e-01,
        3.34054308e-01, 7.85062089e-02, 9.81560068e-01, 2.98274784e-02,
        2.38927591e-01, 2.96768511e-01],
       [1.55839554e-01, 3.40862275e-01, 6.84092290e-01, 6.86110833e-01,
        3.27502653e-01, 9.16977664e-02, 9.77798745e-01, 2.06829160e-01,
        6.95066956e-01, 3.26209883e-01],
       [5.93159863e-01, 9.41912354e-01, 9.92441443e-01, 3.35263616e-01,
        7.95055318e-01, 6.19181489e-01, 8.34120522e-02, 7.79731178e-02,
        7.05902460e-01, 2.86022083e-01],
       [9.21946140e-01, 1.74961952e-02, 8.69828779e-01, 1.26559988e-01,
   

In [38]:
np.all(np.array([0,0,0]))==0

True

In [39]:
import numpy as np

def process_comparison_matrix(comparison_matrix):
    """
    Processes the comparison_matrix as per the specified requirements.

    Returns:
    - A 1-D array where each element corresponds to a row in the comparison_matrix.
      If the sum of the row is 0, the element is set to 999. Otherwise, it's set to
      the index of the first non-zero element in the row.
    """
    # Check if the sum of each row is zero
    row_sums = np.sum(comparison_matrix, axis=1)
    
    # Find rows where the sum is zero
    zero_sum_indices = np.where(row_sums == 0)[0]
    
    # Initialize the result array with 999 for rows with zero sum
    result = np.full_like(row_sums, fill_value=999)
    
    # For rows with non-zero sum, find the index of the first non-zero element
    non_zero_sum_indices = np.where(row_sums != 0)[0]
    first_nonzero_indices = np.argmax(comparison_matrix[non_zero_sum_indices] != 0, axis=1)
    
    # Update the result array with the computed indices
    result[non_zero_sum_indices] = first_nonzero_indices
    
    return result

# Example usage:
comparison_matrix = np.random.randint(0, 2, size=(20, 4))
result_array = process_comparison_matrix(comparison_matrix)
print(result_array)


[  1   3   0   3   0 999   2   0   3   1   3   1   1   1   1   0   0   2
   1   0]


In [43]:
comparison_matrix = np.random.randint(0, 2, size=(20, 0))

In [41]:
row_sums = np.sum(comparison_matrix, axis=1)

In [42]:
row_sums

array([3, 1, 2, 1, 2, 0, 1, 2, 1, 1, 1, 2, 1, 1, 2, 3, 3, 2, 1, 2])

In [35]:
import numpy as np

def compare_random_matrix(random_matrix):
    """
    Compares every row in random_matrix with death_rate.

    Returns:
    - A binary matrix where each element is 1 if the corresponding element in random_matrix
      is less than the corresponding element in death_rate, and 0 otherwise.
    """
    # Get death rates
    death_rate = (np.array([range(0.1,1.0)]))  # Assuming getDeathRates returns a numpy array

    # Compare every row in random_matrix with death_rate
    comparison_matrix = (random_matrix < death_rate).astype(int)

    return comparison_matrix

# Example usage:
random_matrix = np.random.rand(50, 10)
comparison_matrix = compare_random_matrix(random_matrix)
print(comparison_matrix)


TypeError: 'float' object cannot be interpreted as an integer

In [31]:
cat

array([[0, 0, 0, 0, 0, 1, 1, 1, 1, 1]], dtype=int32)

####
    for row in childbearing_females:
        female_index = row[0]
        ages_of_add = row[2]
        age_of_death = row[5]

        prg_dates_vec = GetPregnancyDates(year_of_add, age_of_add,age_of_death)
        
        for date in prg_dates_vec:

            prg_dates_dic[ female_index ] = prg_dates_vec

            prg_dates_dic_by_dates[date].append(cur_index)
            mother_infant_dic[female_index].append(cur_index)

            year = date // 365 + year_0
            infant_vec = (cur_index, year, 0, 0, getGender(), getDeathAge(year, 0))
            new_born_list.append(infant_vec)
            cur_index += 1

    infant_array = np.array(new_born_list)



In [8]:
row = np.array([1,2,0])
np.nonzero(row)[0]

array([0, 1], dtype=int64)

In [ ]:
# p = 0.2 
# need to be inside 0.2

In [16]:
import numpy as np

# Example matrix of size 10x10 (you can replace this with your actual matrix)
matrix = np.random.randint(10,10)

# Extract columns 0, 2, and 5
extracted_columns = matrix[:, [0, 2, 5]]

# Print the original matrix and the extracted columns for comparison
print("Original Matrix:\n", matrix)
print("\nExtracted Columns (0, 2, 5):\n", extracted_columns)



ValueError: low >= high

In [9]:
output_matrix[14,]

array([0.        , 0.00023067, 0.00042186, 0.00071374, 0.00119325,
       0.00193261, 0.00303663, 0.00462504, 0.00682018, 0.0097396 ,
       0.01277319])

In [10]:
output_matrix[16,]

array([0.0005349 , 0.00084059, 0.00143233, 0.00225775, 0.00351784,
       0.00530876, 0.00777253, 0.01102928, 0.01515008, 0.0201596 ,
       0.02463452])

In [6]:
ASFR

V1        V2        V3        V4        V5        V6        V7  \
0   0.000275  0.000530  0.000983  0.001752  0.002999  0.004935  0.007804   
1   0.000276  0.000535  0.000997  0.001784  0.003069  0.005073  0.008057   
2   0.000231  0.000449  0.000841  0.001512  0.002612  0.004336  0.006918   
3   0.000216  0.000422  0.000793  0.001432  0.002486  0.004146  0.006645   
4   0.000192  0.000378  0.000714  0.001295  0.002258  0.003782  0.006089   
5   0.000175  0.000345  0.000655  0.001193  0.002090  0.003518  0.005690   
6   0.000159  0.000315  0.000600  0.001098  0.001933  0.003268  0.005309   
7   0.000144  0.000287  0.000550  0.001011  0.001788  0.003037  0.004956   
8   0.000131  0.000262  0.000504  0.000931  0.001654  0.002821  0.004625   
9   0.000119  0.000239  0.000462  0.000857  0.001528  0.002618  0.004310   
10  0.000108  0.000217  0.000422  0.000786  0.001409  0.002425  0.004012   
11  0.000092  0.000187  0.000365  0.000684  0.001231  0.002128  0.003537   
12  0.000088  0.000180  0.000353  0.000664  0.001200  0.002084  0.003479   
13  0.000088  0.000180  0.000355  0.000671  0.001218  0.002125  0.003563   
14  0.000073  0.000151  0.000298  0.000566  0.001032  0.001809  0.003046   
15  0.000068  0.000141  0.000280  0.000533  0.000976  0.001719  0.002907   
16  0.000061  0.000125  0.000250  0.000479  0.000882  0.001559  0.002649   
17  0.000055  0.000114  0.000228  0.000440  0.000813  0.001443  0.002464   
18  0.000050  0.000104  0.000209  0.000403  0.000748  0.001335  0.002289   
19  0.000045  0.000094  0.000191  0.000370  0.000690  0.001236  0.002129   
20  0.000041  0.000086  0.000174  0.000339  0.000635  0.001143  0.001977   
21  0.000037  0.000078  0.000158  0.000310  0.000583  0.001055  0.001833   
22  0.000033  0.000070  0.000144  0.000284  0.000536  0.000974  0.001700   
23  0.000028  0.000061  0.000125  0.000246  0.000468  0.000853  0.001495   
24  0.000027  0.000058  0.000119  0.000237  0.000452  0.000828  0.001459   
25  0.000027  0.000057  0.000119  0.000238  0.000455  0.000838  0.001482   
26  0.000022  0.000048  0.000100  0.000201  0.000386  0.000713  0.001267   
27  0.000021  0.000045  0.000093  0.000188  0.000363  0.000674  0.001203   

          V8        V9       V10  ...       V26       V27       V28       V29  \
0   0.011857  0.017311  0.024285  ...  0.024164  0.017213  0.011783  0.007750   
1   0.012298  0.018037  0.025420  ...  0.027205  0.019468  0.013387  0.008846   
2   0.010606  0.015625  0.022119  ...  0.025413  0.018267  0.012617  0.008374   
3   0.010233  0.015143  0.021533  ...  0.026586  0.019196  0.013318  0.008879   
4   0.009419  0.014001  0.019999  ...  0.026528  0.019240  0.013409  0.008980   
5   0.008842  0.013205  0.018949  ...  0.027076  0.019729  0.013813  0.009294   
6   0.008288  0.012433  0.017923  ...  0.027534  0.020153  0.014175  0.009580   
7   0.007773  0.011713  0.016962  ...  0.028025  0.020607  0.014560  0.009885   
8   0.007286  0.011029  0.016043  ...  0.028476  0.021032  0.014927  0.010180   
9   0.006820  0.010370  0.015150  ...  0.028849  0.021402  0.015256  0.010450   
10  0.006377  0.009740  0.014294  ...  0.029275  0.021816  0.015623  0.010750   
11  0.005647  0.008664  0.012773  ...  0.028124  0.021054  0.015145  0.010469   
12  0.005580  0.008600  0.012736  ...  0.030131  0.022657  0.016372  0.011368   
13  0.005739  0.008885  0.013218  ...  0.033591  0.025373  0.018416  0.012845   
14  0.004930  0.007665  0.011454  ...  0.031258  0.023716  0.017291  0.012113   
15  0.004726  0.007381  0.011078  ...  0.032466  0.024743  0.018119  0.012751   
16  0.004325  0.006786  0.010231  ...  0.032223  0.024668  0.018147  0.012827   
17  0.004041  0.006370  0.009647  ...  0.032670  0.025124  0.018566  0.013184   
18  0.003772  0.005972  0.009085  ...  0.033057  0.025536  0.018955  0.013520   
19  0.003524  0.005604  0.008563  ...  0.033434  0.025941  0.019341  0.013856   
20  0.003287  0.005250  0.008058  ...  0.033772  0.026320  0.019710  0.014184   
21  0.003060  0.004909 

In [2]:
import pandas as pd



# ASFR size: 28 *35  the rows stand for 2023 to 2050; columns stand for age 15 to 49 
#  each entity stand for fertilty rate of age (col+15) in year (2023+ row); row, col from 0 

# we wish to construct a np matrix; with 50 rows  stand for year 0 to 49 
# with 11 columns stand for 2024 to 2034; 
# each row stands for a woman of age a, will go through what fertility from 2024 to 2034
# for values not suitable in the ASFR set it to 0
# example, for the row 15, its value should be ASFR[1,0],ASFR[2,1]...ASFR[12,11]
# for row 14, stand for age 14, should be 0,ASFR[2,0],SFR[3,1] ...
# construct such matrix and store to np matrix






FileNotFoundError: [Errno 2] No such file or directory: '../original_data/aggregated_ASFR.csv'