In [1]:
pwd

'/Users/jbaafi'

In [2]:
cd Documents/

/Users/jbaafi/Documents


In [3]:
ls

neural network exercises/


In [4]:
cd neural\ network\ exercises

/Users/jbaafi/Documents/neural network exercises


In [45]:
import numpy as np
import pandas as pd
a = np.random.randn(4, 3) # a.shape = (4, 3)
a

array([[-1.06945832,  2.57221348,  0.66301493],
       [ 0.23496136,  0.8780266 ,  0.5033122 ],
       [ 1.32725059,  0.12793124,  3.51013897],
       [-0.15959451,  0.42788632,  0.24705597]])

In [2]:
b = np.random.randn(3, 2) # b.shape = (3, 2)
b

array([[ 0.60007193, -0.64639418],
       [-1.53679694,  0.48447482],
       [ 0.27159717,  0.48576765]])

In [5]:
# a.shape = (3,4)
# b.shape = (4,1)
a = np.random.randn(3, 4)
b = np.random.randn(4, 1)

for i in range(3):
  for j in range(4):
    c[i][j] = a[i][j] * b[j]

NameError: name 'c' is not defined

In [11]:
c = a*b
c

ValueError: operands could not be broadcast together with shapes (4,3) (3,2) 

In [6]:
d = np.random.randn(3, 3)
d

array([[ 0.79110463,  0.05523984,  0.94925944],
       [-0.4750612 , -0.05390706, -0.17910285],
       [ 0.26528989,  0.94986386,  1.0823292 ]])

In [7]:
e = np.random.randn(3, 3,)
e

array([[ 0.08674388, -1.33306918,  1.98125019],
       [ 0.05307521, -0.00479774,  0.0455946 ],
       [-1.66965714,  0.86279033,  0.57161717]])

In [9]:
f = d+e
f

array([[ 0.87784851, -1.27782934,  2.93050963],
       [-0.42198599, -0.0587048 , -0.13350825],
       [-1.40436726,  1.81265418,  1.65394636]])

In [29]:
def sigmoid(x):
    
    s = 1 / (1 + math.exp(-x))
    return s

In [30]:
sigmoid(3)

0.9525741268224334

In [51]:
def sigmoid_derivative(x):
    
    s = 1 / (1 + np.exp(-x))
    ds = s*(1-s)
    
    return ds

In [52]:
x = np.array([1, 2, 3])
sigmoid_derivative(x)

array([0.19661193, 0.10499359, 0.04517666])