Analisis sinistros viales- Laboratorio 4

Juan Sebastian Cortes Chia
Jhonatan Rios Tapiero
Santiago Guerrero Chamorro


En este cuaderno de jupyter se realiza un flujo de trabajo para predecir la severidad de siniestros viales, a partir de una base de datos de la Secretaría Distrital.

### Importar librerías

In [20]:
import numpy as np
import pandas as pd

### Cargar datos

In [21]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [22]:
# dataini = pd.read_csv('historico_siniestros_bogota_d.c_-.csv')
dataini = pd.read_csv('/content/drive/MyDrive/flights/historico_siniestros_bogota_d.c_-.csv')

In [23]:
dataini.head()

X         Y  OBJECTID  FORMULARIO  CODIGO_ACCIDENTE  \
0 -74.090924  4.693807         1  A000640275           4484660   
1 -74.121000  4.603000         2  A001233353          10533499   
2 -74.042000  4.682000         4  A001232786          10533629   
3 -74.166937  4.587187         7  A000200705           4412699   
4 -74.092901  4.607648         8  A000402862           4447845   

     FECHA_OCURRENCIA_ACC  ANO_OCURRENCIA_ACC                   DIRECCION  \
0  2017/06/12 00:00:00+00                2017  AV AVENIDA BOYACA-CL 79 02   
1  2020/11/19 00:00:00+00                2020           CL 26 S- KR 50 02   
2  2020/11/10 00:00:00+00                2020            KR 9 - CL 100 02   
3  2015/05/11 00:00:00+00                2015           CL 63A-KR 72 S 02   
4  2016/06/08 00:00:00+00                2016               KR 27-CL 9 14   

      GRAVEDAD CLASE_ACC       LOCALIDAD          FECHA_HORA_ACC   LATITUD  \
0   SOLO DANOS    CHOQUE        ENGATIVA  2017/06/12 05:30:00+00  4.693807   
1  CON HERIDOS      OTRO   PUENTE ARANDA  2020/11/19 02:05:00+00  4.603000   
2   SOLO DANOS    CHOQUE         USAQUEN  2020/11/10 13:30:00+00  4.682000   
3   SOLO DANOS    CHOQUE  CIUDAD BOLIVAR  2015/05/11 10:50:00+00  4.587187   
4   SOLO DANOS    CHOQUE    LOS MARTIRES  2016/06/08 21:30:00+00  4.607648   

    LONGITUD         CIV  PK_CALZADA  
0 -74.090924  10006772.0    221236.0  
1 -74.121000  16004560.0         NaN  
2 -74.042000  30001107.0         NaN  
3 -74.166937  19001483.0    136166.0  
4 -74.092901  14000548.0    239719.0

In [24]:
data = dataini

data = data.drop(['X','Y','OBJECTID','FORMULARIO','CODIGO_ACCIDENTE','FECHA_OCURRENCIA_ACC','ANO_OCURRENCIA_ACC','DIRECCION','CIV','PK_CALZADA', ], axis=1)
data.head()

GRAVEDAD CLASE_ACC       LOCALIDAD          FECHA_HORA_ACC   LATITUD  \
0   SOLO DANOS    CHOQUE        ENGATIVA  2017/06/12 05:30:00+00  4.693807   
1  CON HERIDOS      OTRO   PUENTE ARANDA  2020/11/19 02:05:00+00  4.603000   
2   SOLO DANOS    CHOQUE         USAQUEN  2020/11/10 13:30:00+00  4.682000   
3   SOLO DANOS    CHOQUE  CIUDAD BOLIVAR  2015/05/11 10:50:00+00  4.587187   
4   SOLO DANOS    CHOQUE    LOS MARTIRES  2016/06/08 21:30:00+00  4.607648   

    LONGITUD  
0 -74.090924  
1 -74.121000  
2 -74.042000  
3 -74.166937  
4 -74.092901

In [25]:
# df['year'], df['month'] = df['date'].dt.year, df['date'].dt.month
# data['AÑO'] = data['FECHA_OCURRENCIA_ACC'].
data['AÑO'] = pd.DatetimeIndex(data['FECHA_HORA_ACC']).year

In [26]:
data['MES'] = pd.DatetimeIndex(data['FECHA_HORA_ACC']).month

In [27]:
data['DIA'] = pd.DatetimeIndex(data['FECHA_HORA_ACC']).day

In [28]:
# data['HORA'] = pd.DatetimeIndex(data['FECHA_HORA_ACC']).time #HH:MM:SS
data['HORA'] = pd.DatetimeIndex(data['FECHA_HORA_ACC']).hour #HH

In [29]:
data.head()

GRAVEDAD CLASE_ACC       LOCALIDAD          FECHA_HORA_ACC   LATITUD  \
0   SOLO DANOS    CHOQUE        ENGATIVA  2017/06/12 05:30:00+00  4.693807   
1  CON HERIDOS      OTRO   PUENTE ARANDA  2020/11/19 02:05:00+00  4.603000   
2   SOLO DANOS    CHOQUE         USAQUEN  2020/11/10 13:30:00+00  4.682000   
3   SOLO DANOS    CHOQUE  CIUDAD BOLIVAR  2015/05/11 10:50:00+00  4.587187   
4   SOLO DANOS    CHOQUE    LOS MARTIRES  2016/06/08 21:30:00+00  4.607648   

    LONGITUD   AÑO  MES  DIA  HORA  
0 -74.090924  2017    6   12     5  
1 -74.121000  2020   11   19     2  
2 -74.042000  2020   11   10    13  
3 -74.166937  2015    5   11    10  
4 -74.092901  2016    6    8    21

In [30]:
data = data.drop('FECHA_HORA_ACC',axis=1)
data.head()

GRAVEDAD CLASE_ACC       LOCALIDAD   LATITUD   LONGITUD   AÑO  MES  DIA  \
0   SOLO DANOS    CHOQUE        ENGATIVA  4.693807 -74.090924  2017    6   12   
1  CON HERIDOS      OTRO   PUENTE ARANDA  4.603000 -74.121000  2020   11   19   
2   SOLO DANOS    CHOQUE         USAQUEN  4.682000 -74.042000  2020   11   10   
3   SOLO DANOS    CHOQUE  CIUDAD BOLIVAR  4.587187 -74.166937  2015    5   11   
4   SOLO DANOS    CHOQUE    LOS MARTIRES  4.607648 -74.092901  2016    6    8   

   HORA  
0     5  
1     2  
2    13  
3    10  
4    21

In [31]:
data.shape

(199146, 9)

In [32]:
data = pd.get_dummies(data, columns=['CLASE_ACC','LOCALIDAD'])
data.head()

GRAVEDAD   LATITUD   LONGITUD   AÑO  MES  DIA  HORA  \
0   SOLO DANOS  4.693807 -74.090924  2017    6   12     5   
1  CON HERIDOS  4.603000 -74.121000  2020   11   19     2   
2   SOLO DANOS  4.682000 -74.042000  2020   11   10    13   
3   SOLO DANOS  4.587187 -74.166937  2015    5   11    10   
4   SOLO DANOS  4.607648 -74.092901  2016    6    8    21   

   CLASE_ACC_ATROPELLO  CLASE_ACC_AUTOLESION  CLASE_ACC_CAIDA DE OCUPANTE  \
0                False                 False                        False   
1                False                 False                        False   
2                False                 False                        False   
3                False                 False                        False   
4                False                 False                        False   

   ...  LOCALIDAD_PUENTE ARANDA  LOCALIDAD_RAFAEL URIBE URIBE  \
0  ...                    False                         False   
1  ...                     True                         False   
2  ...                    False                         False   
3  ...                    False                         False   
4  ...                    False                         False   

   LOCALIDAD_SAN CRISTOBAL  LOCALIDAD_SANTA FE  LOCALIDAD_SUBA  \
0                    False               False           False   
1                    False               False           False   
2                    False               False           False   
3                    False               False           False   
4                    False               False           False   

   LOCALIDAD_SUMAPAZ  LOCALIDAD_TEUSAQUILLO  LOCALIDAD_TUNJUELITO  \
0              False                  False                 False   
1              False                  False                 False   
2              False                  False                 False   
3              False                  False                 False   
4              False                  False                 False   

   LOCALIDAD_USAQUEN  LOCALIDAD_USME  
0              False           False  
1              False           False  
2               True           False  
3              False           False  
4              False           False  

[5 rows x 34 columns]

In [33]:
data.shape

(199146, 34)

In [34]:
data.dtypes

GRAVEDAD                         object
LATITUD                         float64
LONGITUD                        float64
AÑO                               int32
MES                               int32
DIA                               int32
HORA                              int32
CLASE_ACC_ATROPELLO                bool
CLASE_ACC_AUTOLESION               bool
CLASE_ACC_CAIDA DE OCUPANTE        bool
CLASE_ACC_CHOQUE                   bool
CLASE_ACC_INCENDIO                 bool
CLASE_ACC_OTRO                     bool
CLASE_ACC_VOLCAMIENTO              bool
LOCALIDAD_ANTONIO NARINO           bool
LOCALIDAD_BARRIOS UNIDOS           bool
LOCALIDAD_BOSA                     bool
LOCALIDAD_CANDELARIA               bool
LOCALIDAD_CHAPINERO                bool
LOCALIDAD_CIUDAD BOLIVAR           bool
LOCALIDAD_ENGATIVA                 bool
LOCALIDAD_FONTIBON                 bool
LOCALIDAD_KENNEDY                  bool
LOCALIDAD_LOS MARTIRES             bool
LOCALIDAD_PUENTE ARANDA            bool


In [35]:
data['GRAVEDAD']

0          SOLO DANOS
1         CON HERIDOS
2          SOLO DANOS
3          SOLO DANOS
4          SOLO DANOS
             ...     
199141     SOLO DANOS
199142    CON HERIDOS
199143    CON HERIDOS
199144    CON HERIDOS
199145    CON HERIDOS
Name: GRAVEDAD, Length: 199146, dtype: object

In [36]:
data['GRAVEDAD'] = pd.Categorical(data['GRAVEDAD'])
categories = data.GRAVEDAD.cat.categories
codes = data.GRAVEDAD.cat.codes

In [37]:
categories

Index(['CON HERIDOS', 'CON MUERTOS', 'SOLO DANOS'], dtype='object')

In [38]:
data['GRAVEDAD'] = data.GRAVEDAD.cat.codes
data.dtypes

GRAVEDAD                           int8
LATITUD                         float64
LONGITUD                        float64
AÑO                               int32
MES                               int32
DIA                               int32
HORA                              int32
CLASE_ACC_ATROPELLO                bool
CLASE_ACC_AUTOLESION               bool
CLASE_ACC_CAIDA DE OCUPANTE        bool
CLASE_ACC_CHOQUE                   bool
CLASE_ACC_INCENDIO                 bool
CLASE_ACC_OTRO                     bool
CLASE_ACC_VOLCAMIENTO              bool
LOCALIDAD_ANTONIO NARINO           bool
LOCALIDAD_BARRIOS UNIDOS           bool
LOCALIDAD_BOSA                     bool
LOCALIDAD_CANDELARIA               bool
LOCALIDAD_CHAPINERO                bool
LOCALIDAD_CIUDAD BOLIVAR           bool
LOCALIDAD_ENGATIVA                 bool
LOCALIDAD_FONTIBON                 bool
LOCALIDAD_KENNEDY                  bool
LOCALIDAD_LOS MARTIRES             bool
LOCALIDAD_PUENTE ARANDA            bool


In [39]:
data['GRAVEDAD'].head()

0    2
1    0
2    2
3    2
4    2
Name: GRAVEDAD, dtype: int8

In [40]:
X = data.drop('GRAVEDAD', axis=1)
X.shape

(199146, 33)

In [41]:
Y=pd.DataFrame()
Y['GRAVEDAD'] = data['GRAVEDAD']
Y.shape

(199146, 1)

In [42]:
print(data['GRAVEDAD'].value_counts(normalize=True).mul(100).round(1).astype(str)+'%')

GRAVEDAD
2    64.4%
0    34.0%
1     1.6%
Name: proportion, dtype: object


### Transformación datos: media cero y varianza unitaria

In [43]:
from sklearn.preprocessing import StandardScaler

In [44]:
# Media cero y varianza unitaria
sc = StandardScaler()
Xsc = sc.fit(X)
Xt = Xsc.transform(X)
Xt.shape


(199146, 33)

### Partición conjuntos de datos: Entrenamiento, prueba y validación

In [45]:
from sklearn.model_selection import train_test_split as split

In [46]:
## # Definir función para particionar el conjunto de datos

X_train, X_test, y_train, y_test = split(Xt,Y,
                                         test_size=0.30,
                                         random_state=42,
                                         stratify=Y)

# X_train, X_valid, y_train, y_valid = split(X_train, y_train,
#                                            test_size=0.2,
#                                            stratify=y_train)

## Modelos Supervisados

### Árboles de decisión

In [47]:
# import xgboost as xgb
from sklearn import metrics
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

In [48]:
#Definición del modelo
arbol1 = DecisionTreeClassifier()

#Entrenamiento y evaluación del modelo
arbol1 = arbol1.fit(X_train,y_train)

# Calcular métricas de desempeño
y_pred = arbol1.predict(X_test)
print("\n", metrics.classification_report(y_test, y_pred, digits=2))

# Visualizar matriz de confusión
# Y_pred13 = np_utils.to_categorical(y_pred13)
# cm = matriz_confusion(Y_test, y_pred, 'si', 'Matriz de confusión clasificador AD')


               precision    recall  f1-score   support

           0       0.53      0.55      0.54     20310
           1       0.06      0.07      0.07       972
           2       0.76      0.75      0.75     38462

    accuracy                           0.67     59744
   macro avg       0.45      0.45      0.45     59744
weighted avg       0.67      0.67      0.67     59744



### Random Forests

In [53]:
from sklearn.ensemble import RandomForestClassifier

In [54]:
#Definición del modelo
rfc = RandomForestClassifier(n_estimators=200)

#Entrenamiento y evaluación del modelo
rfc.fit(X_train, y_train)

# Calcular métricas de desempeño
y_pred2 = rfc.predict(X_test)
print("\n", metrics.classification_report(y_test, y_pred2, digits=2))

<ipython-input-54-86e86c52e873>:5: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rfc.fit(X_train, y_train)



               precision    recall  f1-score   support

           0       0.79      0.45      0.57     20310
           1       0.12      0.00      0.00       972
           2       0.76      0.95      0.84     38462

    accuracy                           0.76     59744
   macro avg       0.56      0.47      0.47     59744
weighted avg       0.76      0.76      0.74     59744



### Redes Neuronales Artificiales

In [59]:
from tensorflow.keras import models
from tensorflow.keras import layers
from tensorflow.keras import optimizers
from tensorflow.keras import regularizers
from tensorflow.keras import utils as np_utils

In [64]:
# Ejemplo de definición de X y y
import numpy as np

# Generar datos de ejemplo
X = np.random.rand(1000, 20)  # 1000 muestras, cada una con 20 características
y = np.random.randint(3, size=1000)  # 1000 etiquetas, con 3 clases (0, 1, 2)

# Dividir y transformar los datos como se muestra arriba
X_train, X_temp, y_train, y_temp = train_test_split(X, y, test_size=0.4, random_state=42)
X_valid, X_test, y_valid, y_test = train_test_split(X_temp, y_temp, test_size=0.5, random_state=42)

Y_train = np_utils.to_categorical(y_train)
Y_test = np_utils.to_categorical(y_test)
Y_valid = np_utils.to_categorical(y_valid)


In [65]:
# Definir función para construir RNA
def construrna():
    #Contruir RNA
    model = models.Sequential()
    model.add(layers.Dense(8, activation='tanh'))
    model.add(layers.Dense(8,  activation='tanh'))
    model.add(layers.Dense(4, activation='sigmoid'))

# compile the keras (tensorflow) flow graph
    model.compile(optimizer=optimizers.RMSprop(learning_rate=0.001),
                  loss='categorical_crossentropy',
                  metrics=['accuracy'])
    return model

In [73]:
# Definir función para entrenar RNA
def trainrna(model, epochs, batch_size, X_train, Y_train, X_valid, Y_valid):
    history = model.fit(X_train, Y_train, validation_data=(X_valid, Y_valid), epochs=epochs, batch_size=batch_size)
    return history

In [67]:
# Métricas de desempeño
def metricas_rna(model_rna, X_test, Y_test):

#     # Exactitud
#     test_loss, test_acc = model.evaluate(X_test, Y_test)# testeo de la red con los de prueba
#     print('\nExactitud evaluación:',test_acc)
    Y_pred = model_rna.predict_classes(X_test, batch_size=32, verbose=1)
    Y_pred = np_utils.to_categorical(Y_pred)

    # Mostrar la precisión, recall, F1-score
    print("\n", metrics.classification_report(Y_test, Y_pred, digits=3))

    return Y_pred

In [68]:
# Construir la red neuronal
model_rna = construrna()

In [69]:
print(X_train.shape)
print(X_valid.shape)
print(y_train.shape)
print(y_valid.shape)

(600, 20)
(200, 20)
(600,)
(200,)


In [70]:
#Reshaping labels as 2d-tensor (the first dimension will be the batch dimension and the second the scalar label):
# Our vectorized labels
#Y_train = np.asarray(y_train).astype('float32').reshape((-1,1))
#Y_test = np.asarray(y_test).astype('float32').reshape((-1,1))
#Y_valid = np.asarray(y_valid).astype('float32').reshape((-1,1))

In [74]:
# Entrenar la red neuronal
history_rna = trainrna(model_rna, 5, 32, X_train, Y_train, X_valid, Y_valid)


Epoch 1/5
11/19 [================>.............] - ETA: 0s

ValueError: Unexpected result of `train_function` (Empty logs). This could be due to issues in input pipeline that resulted in an empty dataset. Otherwise, please use `Model.compile(..., run_eagerly=True)`, or `tf.config.run_functions_eagerly(True)` for more information of where went wrong, or file a issue/bug to `tf.keras`.

In [75]:
predict_x=model_rna.predict(X_test)
classes_x=np.argmax(predict_x,axis=1)

7/7 [==============================] - 0s 3ms/step


In [76]:
print(predict_x)
print(classes_x)

[[0.6372552  0.4676763  0.46336392 0.37644598]
 [0.5613745  0.68854535 0.6223304  0.40522066]
 [0.5918489  0.5814112  0.62595147 0.38907704]
 [0.6331404  0.574308   0.4820105  0.4009212 ]
 [0.54342765 0.5457862  0.4345155  0.5032813 ]
 [0.6702313  0.4898838  0.39976284 0.4049653 ]
 [0.61903113 0.5240782  0.39710957 0.39203262]
 [0.6298875  0.5566199  0.47287735 0.36539394]
 [0.58229023 0.6050086  0.40221184 0.41580966]
 [0.63111866 0.4992156  0.46544048 0.40569144]
 [0.6539431  0.4969846  0.57755697 0.41075766]
 [0.5373569  0.5543147  0.5501682  0.48848638]
 [0.6238837  0.5841953  0.5455782  0.3414076 ]
 [0.5504725  0.5359063  0.5439775  0.5126202 ]
 [0.6514745  0.48179236 0.41677397 0.39342332]
 [0.55747914 0.5937859  0.49074775 0.46205628]
 [0.6765983  0.3894508  0.3796932  0.4005966 ]
 [0.51396465 0.69679904 0.58938384 0.48631915]
 [0.6639514  0.43312025 0.40380707 0.37611023]
 [0.59172845 0.5888953  0.466382   0.41858602]
 [0.61761475 0.542924   0.60544217 0.38767594]
 [0.5853239  

In [77]:
#y_pred3 = model_rna.predict_classes(X_test, batch_size=32, verbose=1)
#y_pred3 = np_utils.to_categorical(y_pred3)
#print("\n", metrics.classification_report(y_test, Y_pred3, digits=2))

In [78]:
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score, roc_curve, auc

In [79]:
accuracy_score(y_test, classes_x)

0.3

In [80]:
print(f1_score(y_test, classes_x, average="macro"))
#print(precision_score(y_test, classes_x, average="macro"))
print(recall_score(y_test, classes_x, average="macro"))

0.19650011446886448
0.2175849177305745


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [90]:
from sklearn.metrics import precision_recall_fscore_support as score

precision, recall, fscore, support = score(y_test, classes_x)

print('precision: {}'.format(precision))
print('recall: {}'.format(recall))
print('fscore: {}'.format(fscore))
print('support: {}'.format(support))

precision: [0.32142857 0.30434783 0.21428571 0.        ]
recall: [0.46753247 0.3559322  0.046875   0.        ]
fscore: [0.38095238 0.328125   0.07692308 0.        ]
support: [77 59 64  0]


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [82]:
from sklearn.metrics import confusion_matrix

In [83]:
y_test_arg=np.argmax(y_test,axis=1)
y_pred3 = np.argmax(model_rna.predict(X_test),axis=1)
print('Confusion Matrix')
print(confusion_matrix(y_test_arg, y_pred3))

AxisError: axis 1 is out of bounds for array of dimension 1

In [84]:
fpr, tpr, thresholds = roc_curve(y_test_arg, classes_x, pos_label=2)
auc(fpr, tpr)

NameError: name 'y_test_arg' is not defined

### Xgboost

In [85]:
from sklearn.model_selection import cross_val_score, KFold
import xgboost as xgb

In [86]:
#Definición del modelo
xg_class = xgb.XGBClassifier(objective ='multi:softprob', colsample_bytree = 1, learning_rate = 0.1,
                max_depth = 5, alpha = 10, n_estimators = 100)

In [87]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y_train = le.fit_transform(y_train)

In [91]:
#Entrenamiento del modelo
xg_class.fit(X_train, y_train,
             eval_set=[(X_train, y_train), (X_test, y_test)],
             eval_metric='mlogloss',
             verbose=False)

/usr/local/lib/python3.10/dist-packages/xgboost/sklearn.py:889: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(


XGBClassifier(alpha=10, base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None, colsample_bytree=1,
              device=None, early_stopping_rounds=None, enable_categorical=False,
              eval_metric=None, feature_types=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.1, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=5, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=100, n_jobs=None,
              num_parallel_tree=None, ...)

In [92]:
#Entrenamiento y validación cruzada mediante k-fold
scores = cross_val_score(xg_class, X_train, y_train, cv=5)
print("Mean cross-validation score: %.2f" % scores.mean())

# Calcular métricas de desempeño
y_pred4 = xg_class.predict(X_test)
print("\n", metrics.classification_report(y_test, y_pred4, digits=2))

Mean cross-validation score: 0.37

               precision    recall  f1-score   support

           0       0.44      0.25      0.32        77
           1       0.34      0.29      0.31        59
           2       0.36      0.59      0.44        64

    accuracy                           0.37       200
   macro avg       0.38      0.38      0.36       200
weighted avg       0.38      0.37      0.36       200

