ML model for the project to deploy in the github

In [27]:
#warining
from warnings import filterwarnings
filterwarnings('ignore')

#uploading the dataset
import pandas as pd

#plotting the charts
import matplotlib.pyplot  as plt
import seaborn as sns

#preprocssing the data
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler,LabelEncoder

#to pickel
import pickle

#split
from sklearn.model_selection import train_test_split

#model
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier

#hyperparameter tuning
from sklearn.model_selection import GridSearchCV
import numpy as np

#evaluation of data
from sklearn.metrics import accuracy_score,confusion_matrix,multilabel_confusion_matrix,classification_report


In [28]:

df= pd.read_csv('Iris.csv')
df

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

EDA

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             150 non-null    int64  
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB


In [30]:
df.isna().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [31]:
df.nunique()

Id               150
SepalLengthCm     35
SepalWidthCm      23
PetalLengthCm     43
PetalWidthCm      22
Species            3
dtype: int64

In [32]:
df.describe(include='all')

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
count   150.000000     150.000000    150.000000     150.000000    150.000000   
unique         NaN            NaN           NaN            NaN           NaN   
top            NaN            NaN           NaN            NaN           NaN   
freq           NaN            NaN           NaN            NaN           NaN   
mean     75.500000       5.843333      3.054000       3.758667      1.198667   
std      43.445368       0.828066      0.433594       1.764420      0.763161   
min       1.000000       4.300000      2.000000       1.000000      0.100000   
25%      38.250000       5.100000      2.800000       1.600000      0.300000   
50%      75.500000       5.800000      3.000000       4.350000      1.300000   
75%     112.750000       6.400000      3.300000       5.100000      1.800000   
max     150.000000       7.900000      4.400000       6.900000      2.500000   

                Species  
count               150  
unique                3  
top     Iris-versicolor  
freq                 50  
mean                NaN  
std                 NaN  
min                 NaN  
25%                 NaN  
50%                 NaN  
75%                 NaN  
max                 NaN

In [33]:
df.corr()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  \
Id             1.000000       0.716676     -0.397729       0.882747   
SepalLengthCm  0.716676       1.000000     -0.109369       0.871754   
SepalWidthCm  -0.397729      -0.109369      1.000000      -0.420516   
PetalLengthCm  0.882747       0.871754     -0.420516       1.000000   
PetalWidthCm   0.899759       0.817954     -0.356544       0.962757   

               PetalWidthCm  
Id                 0.899759  
SepalLengthCm      0.817954  
SepalWidthCm      -0.356544  
PetalLengthCm      0.962757  
PetalWidthCm       1.000000

In [34]:
#plotting

Define x and y

In [35]:
x=df.drop(['Species','Id'],axis=1)
y=df['Species']

In [36]:
x

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0              5.1           3.5            1.4           0.2
1              4.9           3.0            1.4           0.2
2              4.7           3.2            1.3           0.2
3              4.6           3.1            1.5           0.2
4              5.0           3.6            1.4           0.2
..             ...           ...            ...           ...
145            6.7           3.0            5.2           2.3
146            6.3           2.5            5.0           1.9
147            6.5           3.0            5.2           2.0
148            6.2           3.4            5.4           2.3
149            5.9           3.0            5.1           1.8

[150 rows x 4 columns]

In [37]:
y

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...      
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: Species, Length: 150, dtype: object

Preprocssing the data

In [38]:
ss=StandardScaler()
num_pip = Pipeline(steps=[('sclar',StandardScaler())])
x1=pd.DataFrame(num_pip.fit_transform(x), columns=num_pip.get_feature_names_out())
x1

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0        -0.900681      1.032057      -1.341272     -1.312977
1        -1.143017     -0.124958      -1.341272     -1.312977
2        -1.385353      0.337848      -1.398138     -1.312977
3        -1.506521      0.106445      -1.284407     -1.312977
4        -1.021849      1.263460      -1.341272     -1.312977
..             ...           ...            ...           ...
145       1.038005     -0.124958       0.819624      1.447956
146       0.553333     -1.281972       0.705893      0.922064
147       0.795669     -0.124958       0.819624      1.053537
148       0.432165      0.800654       0.933356      1.447956
149       0.068662     -0.124958       0.762759      0.790591

[150 rows x 4 columns]

In [39]:
col=num_pip.get_feature_names_out()
col

array(['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm'],
      dtype=object)

In [40]:
le= LabelEncoder()
y1 = le.fit_transform(y)
y1

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [41]:
with open('pipe.pkl','wb') as file:
    pickle.dump(num_pip,file)

In [42]:
with open('Label_1.pkl','wb') as file1:
    pickle.dump(y1,file1)

Split

In [43]:
x_train,x_test,y_train,y_test=train_test_split(x,y1,test_size=0.2,random_state=23)

In [44]:
x_train

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
9              4.9           3.1            1.5           0.1
59             5.2           2.7            3.9           1.4
16             5.4           3.9            1.3           0.4
122            7.7           2.8            6.7           2.0
7              5.0           3.4            1.5           0.2
..             ...           ...            ...           ...
39             5.1           3.4            1.5           0.2
91             6.1           3.0            4.6           1.4
31             5.4           3.4            1.5           0.4
40             5.0           3.5            1.3           0.3
83             6.0           2.7            5.1           1.6

[120 rows x 4 columns]

In [45]:
y_train

array([0, 1, 0, 2, 0, 0, 1, 1, 1, 2, 2, 0, 1, 0, 1, 2, 2, 2, 0, 1, 2, 2,
       0, 2, 1, 1, 2, 1, 0, 2, 1, 0, 1, 0, 2, 1, 1, 2, 2, 1, 0, 0, 2, 0,
       0, 2, 2, 1, 0, 1, 2, 1, 2, 2, 1, 0, 1, 2, 2, 1, 0, 1, 1, 1, 2, 1,
       1, 2, 2, 2, 0, 2, 1, 0, 2, 2, 0, 1, 1, 2, 0, 0, 1, 0, 1, 1, 0, 2,
       1, 1, 0, 2, 1, 2, 2, 1, 0, 0, 2, 2, 1, 0, 2, 1, 2, 1, 0, 0, 0, 2,
       0, 0, 2, 0, 1, 0, 1, 0, 0, 1])

Model

In [46]:
sv=SVC()
kn=KNeighborsClassifier()

hyperparameter tunning

In [47]:
grid={
    'C': np.arange(0,2,0.1),
    'kernel' : ['linear','poly','rbf','sigmoid'],
    'degree' : range(1,10)
}

grid1={
    'n_neighbors' : [2,3,4,5,6,7,8,9]
}

In [48]:
gs= GridSearchCV(sv,param_grid=grid,cv=3)
gs1= GridSearchCV(kn,param_grid=grid1,cv=3)
gs1

GridSearchCV(cv=3, estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': [2, 3, 4, 5, 6, 7, 8, 9]})

In [49]:
gs1.fit(x_train,y_train)

GridSearchCV(cv=3, estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': [2, 3, 4, 5, 6, 7, 8, 9]})

In [50]:
gs1.best_params_

{'n_neighbors': 7}

In [51]:
kn1=gs1.best_estimator_
kn1

KNeighborsClassifier(n_neighbors=7)

In [52]:
with open('kn1.pkl','wb') as file2:
    pickle.dump(sv1,file2)

NameError: name 'sv1' is not defined

Evalution on data

In [ ]:
#training data
y_pred_train=kn1.predict(x_train)
y_pred_train

array([0, 1, 0, 2, 0, 0, 1, 1, 1, 2, 2, 0, 1, 0, 1, 2, 2, 2, 0, 1, 2, 2,
       0, 2, 1, 1, 2, 1, 0, 2, 1, 0, 1, 0, 2, 1, 1, 2, 2, 1, 0, 0, 2, 0,
       0, 2, 2, 1, 0, 1, 2, 1, 2, 2, 1, 0, 1, 2, 2, 1, 0, 1, 1, 1, 2, 2,
       1, 2, 2, 2, 0, 2, 1, 0, 2, 2, 0, 1, 1, 2, 0, 0, 1, 0, 1, 1, 0, 2,
       1, 1, 0, 2, 1, 2, 2, 1, 0, 0, 2, 2, 1, 0, 2, 1, 2, 1, 0, 0, 0, 2,
       0, 0, 2, 0, 1, 0, 1, 0, 0, 2])

In [ ]:
acc=accuracy_score(y_pred_train,y_train)
print('accuracy_score',acc)
print('-'*20)

cnf=confusion_matrix(y_pred_train,y_train)
print('confusion_matrix\n', cnf)
print('-'*20)

mcnf=multilabel_confusion_matrix(y_pred_train,y_train)
print('multilabel_confusion_matrix\n',mcnf)
print('-'*20)

clr=classification_report(y_pred_train,y_train)
print('classification_report',clr)

accuracy_score 0.9833333333333333
--------------------
confusion_matrix
 [[38  0  0]
 [ 0 40  0]
 [ 0  2 40]]
--------------------
multilabel_confusion_matrix
 [[[82  0]
  [ 0 38]]

 [[78  2]
  [ 0 40]]

 [[78  0]
  [ 2 40]]]
--------------------
classification_report               precision    recall  f1-score   support

           0       1.00      1.00      1.00        38
           1       0.95      1.00      0.98        40
           2       1.00      0.95      0.98        42

    accuracy                           0.98       120
   macro avg       0.98      0.98      0.98       120
weighted avg       0.98      0.98      0.98       120



In [ ]:
#testing data
y_pred_test= kn1.predict(x_test)
y_pred_test

array([2, 2, 1, 0, 2, 1, 0, 2, 0, 1, 1, 0, 2, 0, 0, 2, 1, 1, 2, 0, 2, 0,
       0, 0, 2, 0, 0, 2, 1, 1])

In [ ]:
acc1=accuracy_score(y_pred_test,y_test)
print('accuracy_score',acc1)
print('-'*20)

cnf1=confusion_matrix(y_pred_test,y_test)
print('confusion_matrix\n', cnf1)
print('-'*20)

mcnf1=multilabel_confusion_matrix(y_pred_test,y_test)
print('multilabel_confusion_matrix\n',mcnf1)
print('-'*20)

clr1=classification_report(y_pred_test,y_test)
print('classification_report',clr1)

accuracy_score 1.0
--------------------
confusion_matrix
 [[12  0  0]
 [ 0  8  0]
 [ 0  0 10]]
--------------------
multilabel_confusion_matrix
 [[[18  0]
  [ 0 12]]

 [[22  0]
  [ 0  8]]

 [[20  0]
  [ 0 10]]]
--------------------
classification_report               precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      1.00      1.00         8
           2       1.00      1.00      1.00        10

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



In [ ]:
y_label = le.inverse_transform(y_pred_test)
y_label

array(['Iris-virginica', 'Iris-virginica', 'Iris-versicolor',
       'Iris-setosa', 'Iris-virginica', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-setosa', 'Iris-virginica', 'Iris-setosa',
       'Iris-setosa', 'Iris-virginica', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-virginica', 'Iris-setosa',
       'Iris-virginica', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-virginica', 'Iris-setosa', 'Iris-setosa', 'Iris-virginica',
       'Iris-versicolor', 'Iris-versicolor'], dtype=object)

In [ ]:
df.columns

Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')

# Unseen data

In [ ]:
#model = KNeighborsClassifier(probability=True)

def prediction_time(Label_1,model,pipe):
    #input of the columns data
    SepalLengthCm=float(input('Enter the Sepal L '))
    SepalWidthCm=float(input('Enter the Sepal W'))
    PetalLengthCm=float(input('Enter the Petal L'))
    PetalWidthCm=float(input('Enter the Petal W'))

    #input to dataframe
    x3= pd.DataFrame([SepalLengthCm, SepalWidthCm, PetalLengthCm, PetalWidthCm]).T
    x3.columns = ['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm']
    print('Dataframe\n',x3)

    #pipeline
    x_pred=pd.DataFrame(pipe.transform(x3))
    x_pred.columns=x3.columns
    print('preprocessing\n',x_pred)

    #model
    y_pred=model.predict(x_pred)
    label=Label_1.inverse_transform(y_pred)[0]

    #probability
    prob = model.predict_proba(x_pred).max()
    print('Probability= ',prob)

    prediction=f'{label}'
    print(prediction)

    return label


In [ ]:
prediction_time(le,kn1,num_pip) 

Dataframe
    SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0            1.0           2.0            3.0           4.0
preprocessing
    SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0      -5.868564     -2.438987      -0.431421      3.682996
Probability=  1.0
Iris-setosa


'Iris-setosa'