In [1]:
from numpy import vstack,array

In [3]:
from numpy.random import rand  

In [5]:
from scipy.cluster.vq import kmeans,vq,whiten  

In [7]:
data1 = vstack((rand(100,3) + array([.5,.5,.5]),rand(100,3))) 

In [9]:
data1

array([[8.87079572e-01, 8.03889406e-01, 7.36595124e-01],
       [8.32107636e-01, 8.46855540e-01, 6.95859356e-01],
       [8.49927352e-01, 9.24579094e-01, 8.23120582e-01],
       [1.18091282e+00, 1.43450706e+00, 1.31295229e+00],
       [8.25902036e-01, 1.09827621e+00, 5.31135953e-01],
       [5.14290424e-01, 8.04084697e-01, 1.05303652e+00],
       [9.57382317e-01, 7.48962054e-01, 8.75267837e-01],
       [8.69640588e-01, 1.05392680e+00, 8.88019213e-01],
       [5.46807902e-01, 1.21510183e+00, 1.30588883e+00],
       [1.20175645e+00, 1.27945322e+00, 7.88181205e-01],
       [1.08799906e+00, 8.04215794e-01, 5.60795207e-01],
       [1.39662442e+00, 8.52685381e-01, 6.52963764e-01],
       [5.31597748e-01, 6.86986838e-01, 7.06781237e-01],
       [9.33387043e-01, 1.48607979e+00, 8.54611806e-01],
       [1.45963691e+00, 1.06531096e+00, 8.55914542e-01],
       [7.35280095e-01, 1.37946953e+00, 1.36243948e+00],
       [7.33306024e-01, 5.03414654e-01, 1.35842946e+00],
       [9.43996049e-01, 9.86920

In [13]:
data1=whiten(data1)

In [15]:
centroids,_ = kmeans(data1,3)

In [17]:
print(centroids)

[[2.8994472  3.0718607  2.78205187]
 [1.15748535 1.21841221 0.89122161]
 [2.20978459 1.72499291 1.9893003 ]]


NameError: name 'scipy' is not defined

In [40]:
from scipy.constants import pi

In [38]:
print(scipy.constants.pi)

NameError: name 'scipy' is not defined

In [35]:
print("sciPy - pi Value = %.18f"%scipy.constants.pi)  

NameError: name 'scipy' is not defined

In [42]:
print(pi)

3.141592653589793


In [44]:
from math import pi 

In [46]:
print(math.pi)

NameError: name 'math' is not defined

In [48]:
from scipy.fftpack import fft

In [50]:
import numpy as np

In [52]:
x = np.array([4.0, 2.0, 1.0, -3.0, 1.5])

In [54]:
y=fft(x)
print(y)

[5.5       -0.j         6.69959347-2.82666927j 0.55040653+3.51033344j
 0.55040653-3.51033344j 6.69959347+2.82666927j]
