<font size = 5.5> Essential Functionality <br> <br> <font size = 4.5> Reindex...-->Reindexing <br> <br> An important method on pandas objects is ***reindex***, which means to create a new object with values rearranged according to the new index

In [2]:
import pandas as pd
import numpy as np

<font size = 5.5> Rearranging of index....

In [7]:
obj = pd.Series([45,23,87,56], index =["d","c","b","a"])
obj

d    45
c    23
b    87
a    56
dtype: int64

In [8]:
obj2  = obj.reindex(["a","b","c","d"])        ### A new object is created for Reindexing.........
obj2

a    56
b    87
c    23
d    45
dtype: int64

In [9]:
obj1 = pd.Series([44,55,77,99], index = ["d","a","c","e"])
obj1

d    44
a    55
c    77
e    99
dtype: int64

In [11]:
obj1.index = index = ["a","b","c","e"]
obj1

a    44
b    55
c    77
e    99
dtype: int64

In [3]:
df4 = pd.DataFrame({"Name":["Aj","SS","Tavi","Nomi"],"Age":[40,35,5,1],"Height":[170,165,75,50],"Weight":[75,56,12,7]}, index = ["A","B","C","D"])
df4

Name  Age  Height  Weight
A    Aj   40     170      75
B    SS   35     165      56
C  Tavi    5      75      12
D  Nomi    1      50       7

In [4]:
df4.reindex(["B","D","C","A"])

Name  Age  Height  Weight
B    SS   35     165      56
D  Nomi    1      50       7
C  Tavi    5      75      12
A    Aj   40     170      75

In [5]:
df4.index = index = ["a","b","c","e"]
df4

Name  Age  Height  Weight
a    Aj   40     170      75
b    SS   35     165      56
c  Tavi    5      75      12
e  Nomi    1      50       7

<font size = 4.5> Changing of index.......A Series can be altered in place by assignment....

In [3]:
obj = pd.Series([45,23,87,56], index =["d","c","b","a"])
obj

d    45
c    23
b    87
a    56
dtype: int64

In [4]:
obj.index = ["a","b","c","d"]
obj

a    45
b    23
c    87
d    56
dtype: int64

<font size = 5.5> Good Example..... of Reindexing!

In [12]:
obj11 = pd.Series([45,23,87,56], index =["d","c","b","a"])
obj11

d    45
c    23
b    87
a    56
dtype: int64

In [13]:
obj11.index = index = ["aa","bb","cc","dd"]
obj11

aa    45
bb    23
cc    87
dd    56
dtype: int64

In [3]:
df = pd.DataFrame({0:[1,2,3,4,5],1:[6,7,8,9,10]})
df

0   1
0  1   6
1  2   7
2  3   8
3  4   9
4  5  10

In [4]:
df.index = [1,0]

ValueError: Length mismatch: Expected axis has 5 elements, new values have 2 elements

In [6]:
df.index[1,0]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

<font size = 5.5> Giving name to a Series.......

In [14]:
obj = pd.Series([45,23,87,56], index =["d","c","b","a"])
obj

d    45
c    23
b    87
a    56
dtype: int64

In [15]:
obj.name = "ABC"
obj

d    45
c    23
b    87
a    56
Name: ABC, dtype: int64

In [6]:
x = pd.DataFrame([[1,2,3,4,5],[11,22,33,44,55]])
x

0   1   2   3   4
0   1   2   3   4   5
1  11  22  33  44  55

In [5]:
x = pd.DataFrame([[1,2,3,4,5],[11,22,33,44,55,66]])
x

0   1   2   3   4     5
0   1   2   3   4   5   NaN
1  11  22  33  44  55  66.0

In [8]:
dict_df = pd.DataFrame({"a":[1,2,3,4,5],"b":[6,7,8,9,10]})
dict_df

a   b
0  1   6
1  2   7
2  3   8
3  4   9
4  5  10

<font size = 5.5> With DataFrame, reindex can alter the index(row), columns, or Both

In [7]:
import numpy as np
df = pd.DataFrame(np.arange(9).reshape((3,3)),index=["a","c","b"],columns=["Y","Z","X"])
df

Y  Z  X
a  0  1  2
c  3  4  5
b  6  7  8

In [8]:
df = df.reindex(index = ["a","b","c"],columns["X","Y","Z"])
df

SyntaxError: positional argument follows keyword argument (2675648333.py, line 1)

In [9]:
df = df.reindex(index = ["a","b","c"],columns = ["X","Y","Z"])
df

X  Y  Z
a  2  0  1
b  8  6  7
c  5  3  4

In [10]:
df = pd.DataFrame(np.arange(9).resize((3,3)),index=["a","c","b"],columns=["Y","Z","X"])
df

Y    Z    X
a  NaN  NaN  NaN
c  NaN  NaN  NaN
b  NaN  NaN  NaN

In [11]:
xx = (np.arange(9).reshape((3,3)))
xx

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [12]:
xx = (np.arange(9).resize((3,3)))
print(xx)

None


<Font size = 4.5> New Example........ Important...

In [13]:
import numpy as np
import pandas as pd
xx = (np.arange(9).resize((3,4)))
print(xx)

None


In [14]:
import numpy as np
x1 = np.arange(9)
x1

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [15]:
x1 = x1.reshape((3,3))
x1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [16]:
z = np.arange(9).resize((3,4))
z

In [17]:
x1 = np.arange(9)
x1.resize((3,4))
x1

array([[0, 1, 2, 3],
       [4, 5, 6, 7],
       [8, 0, 0, 0]])

In [18]:
x1.resize((3,4))
x1

array([[0, 1, 2, 3],
       [4, 5, 6, 7],
       [8, 0, 0, 0]])

In [19]:
x = np.resize(3,4)
x

array([3, 3, 3, 3])

<font size = 5.5> 27_OCT_2023

<Font size = 5.5> Indexing, Selection and Filtering <br> <Font size = 4.5> Indexing with Series... <br><br> Series indexing works similar to NumPy array indexing, except you can use the Serie's index values (Labels) instead of only integers.

In [19]:
ser1  = pd.Series([1,2,3,4,5])
print(ser1)
ser1.name = "xyz"
ser1[0]

0    1
1    2
2    3
3    4
4    5
dtype: int64


1

In [6]:
ser1  = pd.Series([1,2,3,4,5])
ser1.name = "xyz"
print(ser1)
print()
ser1[0]

0    1
1    2
2    3
3    4
4    5
Name: xyz, dtype: int64



1

In [21]:
ser2  = pd.Series([5,6,7,8,9], index = ["a","b","c","d","e"])
print(ser2)
print()
ser2["c"]

a    5
b    6
c    7
d    8
e    9
dtype: int64



7

In [22]:
ser2[3]               ### Numerical indexing also works....... 

8

In [29]:
ser2[["a","c","e"]]    ### Selecting a set of values......       

a    5
c    7
e    9
dtype: int64

In [30]:
ser2[[0,2,4]]         ### Selecting a set of values......

a    5
c    7
e    9
dtype: int64

In [23]:
ser2  = pd.Series([5,6,7,8,9], index = ["a","b","c","d","e"])
print(ser2)
print()
ser2["c"]

a    5
b    6
c    7
d    8
e    9
dtype: int64



7

In [31]:
ser2[1::2]           ### Striding.......

b    6
d    8
dtype: int64

<font size = 5.5>  .loc[ ] --- Label Based indexing....... <br> <br> .iloc[ ]   --- Integer Based indexing...

<font size = 5> While you can select data by label this way, the preferred way to select index values is with the special *loc* operator

In [24]:
obj1 = pd.Series([1,2,3,4], index = [2,0,1,3])
obj2 = pd.Series([1,2,3,4], index = ["a","b","c","d"])
print(obj1)

2    1
0    2
1    3
3    4
dtype: int64


In [34]:
obj1[0]             ### Preferance to Label....

2

In [33]:
print(obj2)

a    1
b    2
c    3
d    4
dtype: int64


In [35]:
obj2[0]

1

<font size = 4.5> .loc operator is used to select data by label

In [36]:
obj2.loc[[0,1,2]]   #### Error because [0,1,2] are not labels of obj2....

KeyError: "None of [Int64Index([0, 1, 2], dtype='int64')] are in the [index]"

In [37]:
obj2.loc[["a","b"]]

a    1
b    2
dtype: int64

<font size = 4.5> .iloc operator indexes only works with integers and not by labels........

In [38]:
print(obj1)

2    1
0    2
1    3
3    4
dtype: int64


In [39]:
obj1.iloc[0]     ### working with Integer Indexing....

1

In [40]:
obj1.loc[0]     ### Working with Labels....

2

In [ ]:
obj1.loc["a"]   ### Error as "a" is a string......

In [42]:
print(obj2)

a    1
b    2
c    3
d    4
dtype: int64


In [43]:
obj2.iloc[2]

3

In [45]:
obj2.loc["c"]

3

In [46]:
obj2.loc[["a":"c"]]

SyntaxError: invalid syntax (3373857767.py, line 1)

<font size = 5.5> start and stop value is incuded here......

In [47]:
obj2.loc["a":"c"]

a    1
b    2
c    3
dtype: int64

In [48]:
obj2.loc["b":"d"]

b    2
c    3
d    4
dtype: int64

In [50]:
print(obj2)

a    1
b    2
c    3
d    4
dtype: int64


In [49]:
obj2.iloc[1:3]

b    2
c    3
dtype: int64

In [51]:
obj2.iloc[0::2]

a    1
c    3
dtype: int64

In [52]:
obj2.iloc[::-1]

d    4
c    3
b    2
a    1
dtype: int64

In [53]:
obj2.loc[::-1]

d    4
c    3
b    2
a    1
dtype: int64

In [54]:
obj2.loc["a":"c":-1]

Series([], dtype: int64)

In [55]:
obj2.loc["d":"a":-1]

d    4
c    3
b    2
a    1
dtype: int64

<font size= 4.5> ***Indexing with DataFrame.*** 30_OCT_2023

In [1]:
import pandas as pd

In [7]:
x = pd.DataFrame([[1,2,3,4],[4,5,6,3],[7,8,9,2],[10,11,1,1],[3,2,4,3]],index=["A","B","C","D","E"],columns=["Haldwani","Delhi","Ramnagar","New Delhi"])
x

Haldwani  Delhi  Ramnagar  New Delhi
A         1      2         3          4
B         4      5         6          3
C         7      8         9          2
D        10     11         1          1
E         3      2         4          3

In [3]:
x.Haldwani           ### Output is Series Data Type..........

A     1
B     4
C     7
D    10
E     3
Name: Haldwani, dtype: int64

In [4]:
x["Delhi"]           ### Output is Series Data Type..........

A     2
B     5
C     8
D    11
E     2
Name: Delhi, dtype: int64

In [5]:
df = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9],[10,11,1]],index=["A","B","C","D"],columns=["Haldwani","Delhi","Ramnagar",])
df

Haldwani  Delhi  Ramnagar
A         1      2         3
B         4      5         6
C         7      8         9
D        10     11         1

In [6]:
df["Haldwani":"Ramnagar"]       ### Only column Headings are output.........

Empty DataFrame
Columns: [Haldwani, Delhi, Ramnagar]
Index: []

In [7]:
df["Ramnagar"]                 ### Selecting a column.

A    3
B    6
C    9
D    1
Name: Ramnagar, dtype: int64

In [11]:
df11 = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9],[10,11,1]],index=["A","B","C","D"],columns=["Haldwani","Delhi","Ram Nagar",])
df11

Haldwani  Delhi  Ram Nagar
A         1      2          3
B         4      5          6
C         7      8          9
D        10     11          1

In [12]:
df11.Ram Nagar      #### This will not work....

SyntaxError: invalid syntax (1339633950.py, line 1)

In [10]:
df[:2]                       ### Slicing with rows.

Haldwani  Delhi  Ramnagar
A         1      2         3
B         4      5         6

In [11]:
df["Haldwani"]>2            ### Gives a boolean array(Boolean series).

A    False
B     True
C     True
D     True
Name: Haldwani, dtype: bool

In [12]:
df[df["Haldwani"]>2]       ### Selecting Data with a boolean array.

Haldwani  Delhi  Ramnagar
B         4      5         6
C         7      8         9
D        10     11         1

In [13]:
df[B]

NameError: name 'B' is not defined

In [14]:
df["B"]                  ### KeyError........

KeyError: 'B'

In [17]:
df<=5                    ### Boolean DataFrame

Haldwani  Delhi  Ramnagar
A      True   True      True
B      True   True     False
C     False  False     False
D     False  False      True

In [18]:
df>=5                    ### Boolean DataFrame

Haldwani  Delhi  Ramnagar
A     False  False     False
B     False   True      True
C      True   True      True
D      True   True     False

In [19]:
df[df["Haldwani"]>5]       ### Selecting Data with a Boolean array.

Haldwani  Delhi  Ramnagar
C         7      8         9
D        10     11         1

In [21]:
df[df["Delhi"]>9]       ### Selecting Data with a Boolean array.

Haldwani  Delhi  Ramnagar
D        10     11         1

In [22]:
# Indexing with a Boolean DataFrame                     # NaN - Not a number
df[df<2]

Haldwani  Delhi  Ramnagar
A       1.0    NaN       NaN
B       NaN    NaN       NaN
C       NaN    NaN       NaN
D       NaN    NaN       1.0

In [23]:
df

Haldwani  Delhi  Ramnagar
A         1      2         3
B         4      5         6
C         7      8         9
D        10     11         1

In [24]:
df[df<2] = 4
df

Haldwani  Delhi  Ramnagar
A         4      2         3
B         4      5         6
C         7      8         9
D        10     11         4

In [9]:
x = pd.Series([1,2,3,4])
x

0    1
1    2
2    3
3    4
dtype: int64

In [8]:
x = pd.Series([1,2,3,4])
x.name = "Demo"
x

0    1
1    2
2    3
3    4
Name: Demo, dtype: int64

<font size = 5.5> 31_OCT_2023

| S.No.     |   Name    |    Age  |
|-----------|-----------|---------|
|1.         | Aj        |40       |
|2.         | SS        |35       |

|Type                    |Notes            |
|------------------------|-----------------|
|df[column]              |Select single column or sequence of columns from the DataFrame|
|df[slice]               | Slice rows|
|df[Boolean array]       | Filter rows|
|df[Boolean DataFrame]   | Set values based on some criterion|
|df.loc[rows]            | Select single row or subset of rows from the DataFrame by label|
|df.loc[:,cols]          | Select single column or subset of columns by label|
|df.loc[rows,cols]       | Select both row(s) and column(s) by label|
|df.iloc[rows]           | Select single row or subset of rows from the DataFrame by integer position |
|df.iloc[:,cols]         | Select single column or subset of columns by integer position |
|df.iloc[rows,cols]      | Select row(s) and column(s) by integer position |

In [3]:
df = pd.DataFrame({"a":[1,2,3,4,5],"b":[6,7,8,9,10],"c":[11,22,33,44,55]}, index = ["r1","r2","r3","r4","r5"])
df

a   b   c
r1  1   6  11
r2  2   7  22
r3  3   8  33
r4  4   9  44
r5  5  10  55

In [4]:
df.loc["r1"]       ### Prints row r1

a     1
b     6
c    11
Name: r1, dtype: int64

In [5]:
df.loc[["r2"]]    ### Prints row r2 as DataFrame

a  b   c
r2  2  7  22

In [6]:
df.loc[["r1","r4","r2"]]  ### Prints rows r1,r4,r2 as DataFrame

a  b   c
r1  1  6  11
r4  4  9  44
r2  2  7  22

In [7]:
df.loc[["r1","r4","r2"],["a","c"]]        ###   Prints r1,r4,r2  and a,c

a   c
r1  1  11
r4  4  44
r2  2  22

In [9]:
df.loc["r1":"r3","a":"b"]          ### Both positions are inclusive.........IMPortant

a  b
r1  1  6
r2  2  7
r3  3  8

In [10]:
df = pd.DataFrame({"a":[1,2,3,4,5],"b":[6,7,8,9,10],"c":[11,22,33,44,55]}, index = ["r1","r2","r3","r4","r5"])
df

a   b   c
r1  1   6  11
r2  2   7  22
r3  3   8  33
r4  4   9  44
r5  5  10  55

In [11]:
df.iloc[1:3,0:3]

a  b   c
r2  2  7  22
r3  3  8  33

In [12]:
df.iloc[[1,2],1]           ### Prints as Series Data Type......

r2    7
r3    8
Name: b, dtype: int64

In [13]:
df.iloc[[1,2],[0,1]]      ### Prints as DataFrame..........

a  b
r2  2  7
r3  3  8

In [14]:
df.iloc[[0]]             ### Prints as DataFrame..........

a  b   c
r1  1  6  11

In [16]:
df = pd.DataFrame({"a":[1,2,3,4,5],"b":[6,7,8,9,10],"c":[11,22,33,44,55]}, index = ["r1","r2","r3","r4","r5"])
df

a   b   c
r1  1   6  11
r2  2   7  22
r3  3   8  33
r4  4   9  44
r5  5  10  55

In [15]:
df.iloc[-1]

a     5
b    10
c    55
Name: r5, dtype: int64

In [19]:
df.iloc[-1,-3]

5

In [45]:
df1 = pd.DataFrame({"Soap":[120,100,300,100],"AC":[40000,20000,10000,44000],"Fridge":[50000,5000,15000,20000],"Braed":[100,300,400,200],"TV":[40000,15000,20000,30000]}, index = ["r1","r2","r3","r4"])
df1

Soap     AC  Fridge  Braed     TV
r1   120  40000   50000    100  40000
r2   100  20000    5000    300  15000
r3   300  10000   15000    400  20000
r4   100  44000   20000    200  30000

In [25]:
df2 = pd.DataFrame({"Soap":[120],"AC":[40000],"Fridge":[50000],"Braed":[100],"TV":[30000]}, index = ["Products"])
df2

Soap     AC  Fridge  Braed     TV
Products   120  40000   50000    100  30000

In [48]:
df1>=40000

Soap     AC  Fridge  Braed     TV
r1  False   True    True  False   True
r2  False  False   False  False  False
r3  False  False   False  False  False
r4  False   True   False  False  False

In [47]:
df1(>=40000)

SyntaxError: invalid syntax (2916035368.py, line 1)

In [25]:
df3 = pd.DataFrame({"Products":["Soap","Tv","Fridge","Sweets","Eggs"],"Price":[120,4000,5000,100,300]}, index = ["A1","A2","A3","A4","A5"])
df3

Products  Price
A1     Soap    120
A2       Tv   4000
A3   Fridge   5000
A4   Sweets    100
A5     Eggs    300

In [27]:
df3[df3["Price"]>1000]

Products  Price
A2       Tv   4000
A3   Fridge   5000

In [28]:
df3[df3["Price"]>100]

Products  Price
A1     Soap    120
A2       Tv   4000
A3   Fridge   5000
A5     Eggs    300

In [26]:
df3[df3["Price"]>1000],df3[df3["Price"]>100]

(   Products  Price
 A2       Tv   4000
 A3   Fridge   5000,
    Products  Price
 A1     Soap    120
 A2       Tv   4000
 A3   Fridge   5000
 A5     Eggs    300)

<Font size =4.5>ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all(),a.zip().

In [29]:
df3 = pd.DataFrame({"Products":["Soap","Tv","Fridge","Sweets","Eggs"],"Price":[120,4000,5000,100,300]}, index = ["A1","A2","A3","A4","A5"])
df3

Products  Price
A1     Soap    120
A2       Tv   4000
A3   Fridge   5000
A4   Sweets    100
A5     Eggs    300

<Font size = 5.5> 01_NOV_2023

In [30]:
df4 = pd.DataFrame({"Name":["Aj","SS","Tavi","Nomi"],"Age":[40,35,5,1],"Height":[170,165,75,50],"Weight":[75,56,12,7]}, index = ["A","B","C","D"])
df4

Name  Age  Height  Weight
A    Aj   40     170      75
B    SS   35     165      56
C  Tavi    5      75      12
D  Nomi    1      50       7

In [32]:
df4>=30

TypeError: '>=' not supported between instances of 'str' and 'int'

In [49]:
df3[df3["Price"] in ["Price"] if 1000<"Price">100]

SyntaxError: expected 'else' after 'if' expression (1841387172.py, line 1)

In [34]:
df3[df3["Price"]<1000and>100] 

SyntaxError: invalid syntax (1372864469.py, line 1)

In [51]:
df3[df3 if 1000>["Price"]>100: print(df3)] 

SyntaxError: invalid syntax (1157034920.py, line 1)

In [42]:
df3[df3 if ["Price"]: <1000 and 100>] 

SyntaxError: invalid syntax (2388141249.py, line 1)

In [40]:
df3[df3["Price"]==(100>["Price"]<1000)] 

TypeError: '>' not supported between instances of 'int' and 'list'

In [36]:
df3[df3["Price"]==(100>"Price"<1000)] 

TypeError: '>' not supported between instances of 'int' and 'str'

In [39]:
df3[df3[100<["Price"]>1000]]

TypeError: '<' not supported between instances of 'int' and 'list'

In [33]:
df3[df3["Price"]<1000 and >100] 

SyntaxError: invalid syntax (3636686404.py, line 1)

In [30]:
df3[df3[100<["Price"]>1000]]

TypeError: '<' not supported between instances of 'int' and 'list'

In [32]:
df3[df3["Price"]<1000] and df3[df3["Price"]>100]

ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [31]:
df3[df3["Price"]<1000 and ["Price"]>100]

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [29]:
df3[df3(100<["Price"]>1000)]

TypeError: '<' not supported between instances of 'int' and 'list'

In [31]:
df3.[Price>1000]

SyntaxError: invalid syntax (1493457175.py, line 1)

In [32]:
df3.loc[Price>1000]

NameError: name 'Price' is not defined