# AMATH 581
## Practice Quiz 1
Date: 5th October 2022

### Attempt 1

In [1]:
import numpy

Q1. Select all commands that will create a vector of the cube of (e.g., the cube of 3 is 27) 10 evenly spaced points in the interval [-5,5]?

In [2]:
a = numpy.arange(-5, 5+10/9, 10/9)
b = a**3 

In [3]:
a

array([-5.        , -3.88888889, -2.77777778, -1.66666667, -0.55555556,
        0.55555556,  1.66666667,  2.77777778,  3.88888889,  5.        ])

In [4]:
b

array([-125.        ,  -58.81344307,  -21.43347051,   -4.62962963,
         -0.17146776,    0.17146776,    4.62962963,   21.43347051,
         58.81344307,  125.        ])

In [6]:
a1 = numpy.arange(-50, 50, 10)/9
b1 = a1^3 

TypeError: ufunc 'bitwise_xor' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [10]:
a2 = numpy.arange(-5, 5, 10)
b2 = a2**3 

In [11]:
a2

array([-5])

In [12]:
b2

array([-125])

In [16]:
a3 = numpy.linspace(-5, 5, 10)
b3 = a3**3 

In [17]:
a3

array([-5.        , -3.88888889, -2.77777778, -1.66666667, -0.55555556,
        0.55555556,  1.66666667,  2.77777778,  3.88888889,  5.        ])

In [18]:
b3

array([-125.        ,  -58.81344307,  -21.43347051,   -4.62962963,
         -0.17146776,    0.17146776,    4.62962963,   21.43347051,
         58.81344307,  125.        ])

In [22]:
a = numpy.linspace(-5, 5, 10)
b = a^3 

TypeError: ufunc 'bitwise_xor' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [24]:
a5 = numpy.linspace(10, -5, 5)
b5 = a5**3 

In [25]:
a5

array([10.  ,  6.25,  2.5 , -1.25, -5.  ])

In [26]:
b5

array([1000.      ,  244.140625,   15.625   ,   -1.953125, -125.      ])

In [28]:
a6 = numpy.arange(-5, 5)
b6= a6^3 

In [29]:
a6

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4])

In [30]:
b6

array([-8, -1, -2, -3, -4,  3,  2,  1,  0,  7])

In [31]:
a = numpy.arange(-5, 5)
b = a^3 
b

array([-8, -1, -2, -3, -4,  3,  2,  1,  0,  7])

In [33]:
a7 = numpy.linspace(-5, 5)
b7 = a7^3 
b7

TypeError: ufunc 'bitwise_xor' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

Q4. Select all code samples that will generate an error or an infinite loop.

In [35]:
a = numpy.ones(10)
for j in a:
   a = [a, j]

print(a)

[[[[[[[[[[array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]), 1.0], 1.0], 1.0], 1.0], 1.0], 1.0], 1.0], 1.0], 1.0], 1.0]


In [36]:
a = numpy.ones(10)
for j in a:
    a[2] = a[0]

print(a)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [37]:
a = numpy.ones(10)
for j in a:
    a[-9] = 1
print(a)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [38]:
a = 5
while numpy.abs(a) < 10: 
   a -= 2

print(a)

-11


In [39]:
a = numpy.ones(10)
for j in a:
   a(len(a)-1)=1

print(a)

SyntaxError: cannot assign to function call (1896523737.py, line 3)

In [40]:
a = numpy.ones(1, 10)
for j in a:
     a[19] = a[10]
        
print(a)

TypeError: Cannot interpret '10' as a data type

In [41]:
a = 5
while a < 10:
   a -= 2

print(a)

KeyboardInterrupt: 

Q3. Select all code samples that will create a vector with 10 random elements.

In [2]:
import numpy 


In [3]:
a=numpy.zeros(10)
for i in numpy.random.rand(1, 10):
   a[i]=numpy.random.rand()

IndexError: arrays used as indices must be of integer (or boolean) type

In [5]:
a=numpy.zeros(10)
for i in [0, 0, 1, 1, 2, 2, 3, 3, 4, 4]:
   a[i]=numpy.random.rand()

print(a)

[0.46004951 0.00148286 0.56204794 0.67111503 0.36355717 0.
 0.         0.         0.         0.        ]


In [8]:
a=numpy.zeros(10)
for i in numpy.random.rand(1, 10):
   a[-1]=numpy.random.rand()
print(a)

[0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.35556112]


In [9]:
a=numpy.zeros(10)
for ind, rand in enumerate(numpy.random.rand(10)):
   a[ind]=rand

print(a)

[0.24421043 0.39748016 0.70200168 0.01579836 0.9430289  0.37079375
 0.29252629 0.02680313 0.87201925 0.08458451]


In [10]:
a=numpy.zeros(10)
for i in range(10):
   a[i]=numpy.random.rand()
print(a)

[0.10295649 0.67225043 0.32638344 0.09270918 0.23680716 0.15267546
 0.02271669 0.82233419 0.52305435 0.21159494]


In [11]:
a=numpy.zeros(10)
for i in [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]:
   a[i]=numpy.random.rand()
print(a)

IndexError: index 10 is out of bounds for axis 0 with size 10

In [12]:
a=numpy.random.rand(10)
print(a)

[0.14404836 0.5885652  0.92106704 0.81337741 0.12063982 0.71288598
 0.77084346 0.91801747 0.02917129 0.03322208]


In [13]:
a=numpy.zeros(10)
for i in [9, 8, 7, 6, 5, 4, 3, 2, 1, 0]:
   a[i]=numpy.random.rand()
print(a)

[0.49465525 0.5403486  0.55260729 0.43524242 0.57231229 0.67069543
 0.37618716 0.79243888 0.21436243 0.91559177]


Q2. Mark all answers that correctly use a function handle/anonymous function to compute absolute value with the function myabs


In [22]:
import math
pi=math.pi

In [23]:
def myabs(funh, num):
   return numpy.abs(funh(num))

In [24]:
cos = lambda x: numpy.cos(x)
myabs(cos(numpy.pi))

TypeError: myabs() missing 1 required positional argument: 'num'

In [25]:
cos = lambda x: numpy.cos(x)
myabs(cos, pi)

1.0

In [26]:
cos = lambda x: numpy.cos(x)
myabs(cos, numpy.pi)

1.0

In [27]:
cos = lambda x: numpy.cos(x)
myabs(cos(x), numpy.pi)

NameError: name 'x' is not defined

In [28]:
cos = lambda x: numpy.cos(x)
myabs(cos, pi, 3*pi)

TypeError: myabs() takes 2 positional arguments but 3 were given

In [29]:
abs = lambda x: numpy.abs(x)
myabs(abs, numpy.pi)

3.141592653589793

In [30]:
cos = lambda x: numpy.cos(x)
myabs(cos, [numpy.pi, 3*numpy.pi])

array([1., 1.])

In [32]:
cos = lambda x: numpy.cos(x)
myabs(cos, 3*pi)

1.0

First Attempt 1: 3.67/4.00

### Attempt 2

Q1. Select all commands that will create a vector of the cube of (e.g., the cube of 3 is 27) 10 evenly spaced points in the interval [-5,5]?

In [34]:
a = numpy.linspace(-5, 5, 10)
b = a^3 

TypeError: ufunc 'bitwise_xor' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [35]:
a = numpy.linspace(-5, 5)
b = a^3 

TypeError: ufunc 'bitwise_xor' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [38]:
a = numpy.linspace(-5, 5, 10)
b = a**3 
a
b

array([-125.        ,  -58.81344307,  -21.43347051,   -4.62962963,
         -0.17146776,    0.17146776,    4.62962963,   21.43347051,
         58.81344307,  125.        ])

In [40]:
a = numpy.arange(-5, 5, 10)
b = a**3 
b

array([-125])

In [42]:
a = numpy.arange(-5, 5)
b = a^3 
b

array([-8, -1, -2, -3, -4,  3,  2,  1,  0,  7])

In [44]:
a = numpy.linspace(10, -5, 5)
b = a**3 
b

array([1000.      ,  244.140625,   15.625   ,   -1.953125, -125.      ])

In [45]:
a = numpy.arange(-50, 50, 10)/9
b = a^3 
b

TypeError: ufunc 'bitwise_xor' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [47]:
a = numpy.arange(-5, 5+10/9, 10/9)
b = a**3 
b

array([-125.        ,  -58.81344307,  -21.43347051,   -4.62962963,
         -0.17146776,    0.17146776,    4.62962963,   21.43347051,
         58.81344307,  125.        ])

Q2.Mark all answers that correctly use a function handle/anonymous function to compute absolute value with the function myabs

In [49]:
def myabs(funh, num):
   return numpy.abs(funh(num))

In [50]:
cos = lambda x: numpy.cos(x)
myabs(cos, numpy.pi)

1.0

In [51]:
abs = lambda x: numpy.abs(x)
myabs(abs, numpy.pi)

3.141592653589793

In [52]:

cos = lambda x: numpy.cos(x)
myabs(cos, pi, 3*pi)

TypeError: myabs() takes 2 positional arguments but 3 were given

In [53]:
cos = lambda x: numpy.cos(x)
myabs(cos, [numpy.pi, 3*numpy.pi])

array([1., 1.])

In [54]:
cos = lambda x: numpy.cos(x)
myabs(cos(numpy.pi))

TypeError: myabs() missing 1 required positional argument: 'num'

In [55]:
cos = lambda x: numpy.cos(x)
myabs(cos, pi)

1.0

In [56]:
cos = lambda x: numpy.cos(x)
myabs(cos(x), numpy.pi)

NameError: name 'x' is not defined

Q3. Select all code samples that will create a vector with 10 random elements.

In [58]:
a=numpy.zeros(10)
for i in [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]:
   a[i]=numpy.random.rand()
a

IndexError: index 10 is out of bounds for axis 0 with size 10

In [59]:
a=numpy.zeros(10)
for i in [9, 8, 7, 6, 5, 4, 3, 2, 1, 0]:
   a[i]=numpy.random.rand()
a

array([0.21221435, 0.08037695, 0.37726663, 0.16904366, 0.84120471,
       0.4807773 , 0.2420889 , 0.6288901 , 0.54840114, 0.08604057])

In [61]:
a=numpy.zeros(10)
for i in numpy.random.rand(1, 10):
   a[-1]=numpy.random.rand()
a

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.42334974])

In [63]:
a=numpy.zeros(10)
for i in [0, 0, 1, 1, 2, 2, 3, 3, 4, 4]:
   a[i]=numpy.random.rand()
a

array([0.96661411, 0.56427965, 0.6641884 , 0.68714813, 0.90547741,
       0.        , 0.        , 0.        , 0.        , 0.        ])

In [64]:
a=numpy.random.rand(10)
a

array([0.1433425 , 0.72802243, 0.90229361, 0.53566439, 0.83567916,
       0.53204303, 0.66907543, 0.4661584 , 0.44321927, 0.70792745])

In [65]:
a=numpy.zeros(10)
for ind, rand in enumerate(numpy.random.rand(10)):
   a[ind]=rand
a

array([0.70144135, 0.32557739, 0.10901154, 0.6059806 , 0.64499321,
       0.21821402, 0.00239595, 0.56587209, 0.91074937, 0.2828337 ])

In [66]:
a=numpy.zeros(10)
for i in numpy.random.rand(1, 10):
   a[i]=numpy.random.rand()
a

IndexError: arrays used as indices must be of integer (or boolean) type

In [68]:
a=numpy.zeros(10)
for i in range(10):
   a[i]=numpy.random.rand()
a

array([0.57337631, 0.12238967, 0.59197315, 0.22394535, 0.36827582,
       0.90512037, 0.32409439, 0.88124246, 0.5584536 , 0.05917601])

Q4. Select all code samples that will generate an error or an infinite loop.

In [69]:
a = numpy.ones(10)
for j in a:
    a[2] = a[0]
a

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [71]:
a = 5
while numpy.abs(a) < 10: 
   a -= 2
a

-11

In [72]:
a = numpy.ones(1, 10)
for j in a:
     a[19] = a[10]
a

TypeError: Cannot interpret '10' as a data type

In [74]:
a = numpy.ones(10)
for j in a:
   a(len(a)-1)=1
a

SyntaxError: cannot assign to function call (2401836473.py, line 3)

In [76]:
a = numpy.ones(10)
for j in a:
    a[-9] = 1
a

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [77]:
a = numpy.ones(10)
for j in a:
   a = [a, j]
a

[[[[[[[[[[array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]), 1.0], 1.0], 1.0],
       1.0],
      1.0],
     1.0],
    1.0],
   1.0],
  1.0],
 1.0]

In [ ]:
a = 5
while a < 10:
   a -= 2
a