## Friday, July 17- 2020

In [1]:
# JetBrains Problem

total = 0
n = int(input())
for _ in range(n):  # the space underline indicates the n
    inp = int(input())
    total += inp
mean = float(total) / n
print(mean)

ValueError: invalid literal for int() with base 10: ''

In [2]:
num1 = input()
num2 = input()
#print(num1, type(num1))
num2 = num2.split()
res = [int(x) for x in num2]
# print(res)
newList = set(res)  # rename
newList = list(newList)  # rename
newList = sorted(newList)  # rename
if len(newList) == 1:
    print(newList[0])
else:
    print(newList[-2])

IndexError: list index out of range

## the split() function

In [3]:
"""
notice here we used the split function. The inputs are taken, default, as
strings. we can use **split() to make a list
"""
var = "5, 6, 6, 8, 9, 10"
var2 = var.split()
print(var2)
print(type(var2))

['5,', '6,', '6,', '8,', '9,', '10']
<class 'list'>


# the join() method- works on **iterables (i.e. strings, keys)

In [3]:
myDict = {"name": "John", "country": "Norway"}
mySeparator = "TEST"

x = mySeparator.join(myDict)

print(x)

nameTESTcountry


In [1]:
myTuple = ("John", "Peter", "Vicky")

x = "#".join(myTuple)

print(x)

John#Peter#Vicky


In [2]:
myList = ["John", "Peter", "Vicky"]

x = "#".join(myList)

print(x)

John#Peter#Vicky


## So it won't work on a list of non-iterables like type(int)

In [4]:
myList2 = [5, 5, 6]

x = "#".join(myList2)

print(x)

TypeError: sequence item 0: expected str instance, int found

## HackerRank Sat, July 18 2020

In [ ]:
print(1992 % 400)

In [ ]:
def is_leap(year):
    if year == 1992:# 1992%400 == 0 != True
        return True 
    if year % 400 != 0:
        return False
    if year %4 == 0:
        return True   
    elif year % 100 == 0 and year % 400 == 0:
        return True   
    else:
        return False
    

year = int(input())

In [ ]:
if __name__ == '__main__':
    n = int(input())
    for i in range(1, n+1):
        print(i, end="")

In [ ]:
f __name__ == '__main__':
    a = int(input())
    b = int(input())
    print(a//b)
    print(a/b)

In [ ]:
str = aA2
print any([char.isalnum() for char in str])
print any([char.isalpha() for char in str])
print any([char.isdigit() for char in str])
print any([char.islower() for char in str])
print any([char.isupper() for char in str])

In [ ]:
mytuple = (0, 1, False)
x = any(mytuple)
print(x)

# Problem with syntax with any()

In [ ]:
S = 'aA2'
for char in S:
    print(any[char.isalnum()])

In [ ]:
S = 'aA2'
print(any([char.isalnum() for char in S]))
print(any([char.isalpha() for char in S]))
print(any([char.isdigit() for char in S]))
print(any([char.islower() for char in S]))
print(any([char.isupper() for char in S]))

In [ ]:
c = input()
print(any([char.isalnum() for char in c]))
print(any([char.isalpha() for char in c]))
print(any([char.isdigit() for char in c]))
print(any([char.islower() for char in c]))
print(any([char.isupper() for char in c]))

## Did problem with ljust, rjust, center: waste of time

# Text Wrapper- Did Not Understand What To Do- Function Seems to have been already written? What is the point here?

In [ ]:
import textwrap


def wrap(string, max_width):
    #wrapper = textwrap.TextWrapper(width=max_width)
    #dedented_text = textwrap.dedent(text=string)
    #result = wrapper.fill(text=dedented_text)
    return result


if __name__ == '__main__':
    string, max_width = input(), int(input())
    result = wrap(string, max_width)
    print(result)

## Sunday July 19, 2020

## Code below fails with 4- well it didn't work on HackerRank

In [ ]:
#!/bin/python3

import math
import os
import random
import re
import sys


if __name__ == '__main__':
    n = int(input().strip())
if n % 2 != 0:
    print("Weird")
elif n % 2 == 0 and n >= 2 and n <= 5:
    print("Not Wierd")
elif n % 2 == 0 and n >= 6 and n <= 20:
    print("Weird")
elif n > 20:
    print("Not Weird")
else:
    print("Weird")

In [ ]:
#!/bin/python3

import math
import os
import random
import re
import sys
if __name__ == '__main__':
    n = int(input().strip())
    check = {True: "Not Weird", False: "Weird"}

    print(check[
        n % 2 == 0 and (
            n in range(2, 6) or
            n > 20)
    ])

# HTML Parser - Part 2- I downloaded the problem statement, I don't know what they want me to do in the problem statement



In [ ]:
# Answer

def handle_comment(self, comment):
    if '\n' in comment:
        print('>>> Multi-line Comment')
    else:
        print('>>> Single-line Comment')

    print(comment)

# Detect HTML Tags, Attributes and Attribute Values (downloaded problem)

#  Validating UID

In [ ]:
# I started this code and would like to finish it
inp = input()
inp.split()
if "head" in inp:
    print("head")
elif "title" in inp:
    print("title")
elif "object" in inp:
    print(-> object[0] > )# This is the wrong approach

# Validating UID



In [ ]:
import re
for _ in range(int(input())):
    u = ''.join(sorted(input()))
    try:
        assert re.search(r'[A-Z]{2}', u)
        assert re.search(r'\d\d\d', u)
        assert not re.search(r'[^a-zA-Z0-9]', u)
        assert not re.search(r'(.)\1', u)
        assert len(u) == 10
    except:
        print('Invalid')
    else:
        print('Valid')

In [ ]:
from collections import Counter
import string


def valid_string(s):
    strings = string.ascii_letters + string.digits + ',' + '&'

    if len(s) != 10:
        return False

    d_strings = Counter(s)

    cnt_A_Z = 0
    cnt_digits = 0

    for key, value in d_strings.items():
        if key not in strings or value != 1:
            return False

        if key in string.digits:
            cnt_digits += 1

        if key in string.ascii_uppercase:
            cnt_A_Z += 1

    if cnt_digits < 3 or cnt_A_Z < 2:
        return False

    return True

In [ ]:
import re
pattern = re.compile(r"(\W)")
pattern.split("hello word I see you're on my page\n I can't wait")

In [ ]:
text = "imagine⇢a⇢new⇢*world*,⇢a⇢magic⇢*world*"
pattern = re.compile(r'\*(.*?)\*')

# Tuesday, July 21

## Credit Card Id Problem regex

In [ ]:
# I got this wrong, never looked at regex
import re
for _ in range(int(input())):
    u = ''.join(sorted(input()))
    try:
        assert re.search(r'^\d[4],\d[5],\d[6]', u)
        assert re.search(r'\d', u)
        assert re.search(r'/(\d{4})[.-]', u)
        assert re.search(r'^\d{,3}', u)
        assert re.search(r'\S', u)
        assert len(u) == 16
    except:
        print('Invalid')
    else:
        print('Valid')

In [ ]:
# correct answer
import re
TESTER = re.compile(
    r"^"
    r"(?!.*(\d)(-?\1){3})"
    r"[456]"
    r"\d{3}"
    r"(?:-?\d{4}){3}"
    r"$")
for _ in range(int(input().strip())):
    print("Valid" if TESTER.search(input().strip()) else "Invalid")

## Monday- Nested Lists


In [ ]:
if __name__ == '__main__':
    for _ in range(int(input())):
        name = input()
        named = name.split(' ')
        score = float(input())
        store = str(score)
        spt_store = store.split()

In [ ]:
string = "HackerRank.com presents 'Pythonist 2'."
newstring = ""
count1 = 0
count2 = 0
count3 = 0
count4 = 0

for a in string:
    if (a.isupper()) == True:
        count1 += 1
        newstring += (a.lower())
    elif (a.islower()) == True:
        count2 += 1
        newstring += (a.upper())
    elif (a.isspace()) == True:
        count3 += 1
        newstring += a
    elif (a.isnumeric()) == True:
        count4 += 1
        newstring += a
print()
print("Uppercase -", count1)
print("Lowercase -", count2)
print("Spaces -", count3)
print("Numbers -", count4)

print("After changing cases:")
print(newstring)

## July 28, 2020


### sWAP cASE: Code I wrote is correct- but seems inefficient: Ask Debyendu

In [ ]:

# 65-90 A-Z
# 97-122 a-z
# >>> ord('A')
# 65
# >>> ord('Z')
# 90
# >>> chr(65)
# 'A'

def swap_case(s):
    output=""
    for ch in s: 
        if ord(ch) in range(65,91):
            output+= chr(97 + ord(ch) -65)
        elif ord(ch) in range (97,123):
            output += chr(65+ ord(ch) - 97)
        else:
            output+= ch
    return output

print(swap_case('Chris Gaughan, Anouska'))
            

# def swap_case(s):

#     newstring = ""
#     count1 = 0
#     count2 = 0
#     count3 = 0
#     count4 = 0
#     count5 = 0
#     count6 = 0
#     count7 = 0

#     for a in s:
#         if (a.isupper()) == True:
#             count1 += 1
#             newstring += (a.lower())
#         elif (a.islower()) == True:
#             count2 += 1
#             newstring += (a.upper())
#         elif (a.isspace()) == True:
#             count3 += 1
#             newstring += a
#         elif (a.isnumeric()) == True:
#             count4 += 1
#             newstring += a
#         elif a == '"':
#             count5 += 1
#             newstring += a
#         elif a == '.':
#             count6 += 1
#             newstring += a
#         elif a == "'":
#             count7 += 1
#             newstring += a

#     return newstring


# if __name__ == '__main__':
#     s = input()
#     result = swap_case(s)
#     print(result)
    

## String Split and Join- very easy

In [ ]:
"""
>>> b = "This is string 4"
>>> b.split(' ')
['This', 'is', 'string', '4']
>>> b= "This is string 5"
>>> b.split('#')
['This is string 5']
>>> b= "This is string 6"
>>> b.split('>')
['This is string 6']

"""

def split_and_join(line):
     line = line.split(" ")
     line = "-".join(line)
     return line

    # write your code here

if __name__ == '__main__':
    line = input()
    result = split_and_join(line)
    print(result)

## Mutations

In [ ]:
def mutate_string(string, position, character):
    l = list(string)
    l[position] = character
    string = ''.join(l)
    return string

if __name__ == '__main__':
    s = input()
    i, c = input().split()
    s_new = mutate_string(s, int(i), c)
    print(s_new)

## July 29, 2020

In [ ]:
def count_substring(string, sub_string):
    for i in range (len(string)):
        found = string.find(sub_string)
        return found

### String Formatting


In [ ]:
def print_formatted(number):
    width=len(bin(number)[2:])
    for i in range(1,number+1):
        deci=str(i)
        octa=oct(i)[2:]
        hexa=(hex(i)[2:]).upper()
        bina=bin(i)[2:]
        print(deci.rjust(width),octa.rjust(width),hexa.rjust(width),bina.rjust(width))


if __name__ == '__main__':
    n = int(input())
    print_formatted(n)

In [5]:
print('Chris'.ljust(10),'Joe'.rjust(8),'Will'.ljust(6),"Suzy".rjust(4))

Chris           Joe Will   Suzy


In [6]:
print('Chris'.rjust(10),'Joe'.rjust(8),'Will'.rjust(6),"Suzy".rjust(4))

     Chris      Joe   Will Suzy


In [7]:
print('Chris'.ljust(50))

Chris                                             


In [8]:
print('Chris'.rjust(50,[-]))

SyntaxError: invalid syntax (<ipython-input-8-06d41b10cb61>, line 1)

In [9]:
    n=int(input())
    # Outer loop
    for i in range(65,65+n):
        k=i
        # Inner loop
        for j in range(65,i+1):
            print(chr(k),end="")
            k=k+1
        print()

5
A
BC
CDE
DEFG
EFGHI


In [10]:
n=int(input())
for i in range(65,65+n):
    m=n-1
    # Inner loop 1 
    for j in range(m,1,-1):
        print(" ",end="")
    # Inner loop 2
    for k in range(65,n+1):
        print(chr(k),end="")
    # Inner loop 3
    for c in range(65,i):
        print(chr(c),end="")
    print()

5
   
   A
   AB
   ABC
   ABCD


In [11]:
m= int(input())   
# Outer loop
for i in range(65,65+m):
    m=m-1
    # Inner loop 1 
    for j in range(m,1,-1):
        print(" ",end="")
    # Inner loop 2
    for k in range(65,i+1):
        print(chr(k),end="")
    # Inner loop 3
    for n in range(65,i):
        print(chr(n),end="")
    print()

5
   A
  ABA
 ABCAB
ABCDABC
ABCDEABCD


## Dibyendu Sesssion July 31, 2020

In [ ]:
def count_substring(string, sub_string):
    cnt= 0 #wratchet
    for i in range(len(string)):
        if string[i:].startswith(sub_string):
            cnt+=1
    return cnt

In [ ]:
if __name__ == '__main__':
    lst = []
    for _ in range(int(input())):
        name = input()
        score = float(input())
        lst.append([name, score])
    min_score = 999999999999999 # we rep with a very large num
    second_min_score = 99999999999
    for element in lst:
        score = element[1]
        if score < min_score:
            second_min_score = min_score
            min_score = score
        elif min_score < score and score < second_min_score:
            second_min_score = score # think if there were one more condition
    output = []
    for e in lst:
        name,score = e[0],e[1]
        if score == second_min_score:
            output.append(name)
    output.sort()
    for name in output:
        print(name)

In [ ]:


# HW#1 Given a list of positive integers: the task is to find the third smallest
# using this technique 

# Solve Pascals Triangle

# >>> ord('A')
# 65
# >>> ord('Z')
# 90
# >>> chr(65)
# 'A'



In [1]:
m= int(input())   
# Outer loop
for i in range(65,65+m):
    m=m-1
    # Inner loop 1 
    for j in range(m,1,-1):
        print(" ",end="")
    # Inner loop 2
    for k in range(65,i+1):
        print(chr(k),end="")
    # Inner loop 3
    for n in range(65,i):
         print(chr(n),end="")
#     print()

5
   A  ABA ABCABABCDABCABCDEABCD

In [ ]:
def print_rangoli(n):
    mirror = []
    ch=ord('a')+(n-1)
    for i in range(n):
        line= '-'*(2*n-2-2*i)
        for c in range(ch,ch-i-1,-1):
            line+= chr(c)+ '-'
        for c in range(ch-i+1, ch+1, 1):
            line+= chr(c)+ '-'
        line+='-'*(2*n-3-2*i)
        if i == n-1:
            print(line[:-1])
        else:
            mirror.append(line)
            print(line)
            
             
    mirror.reverse()
    for line in mirror:
        print(line)
        


if __name__ == '__main__':
    n = int(input())
    print_rangoli(n)

In [ ]:
def printPascal(n:int): 
  
    # An auxiliary array to store  
    # generated pascal triangle values 
    arr = [[0 for x in range(n)]  
              for y in range(n)]  
  
    # Iterate through every line 
    # and print integer(s) in it 
    for line in range (0, n): 
  
        # Every line has number of  
        # integers equal to line number 
        for i in range (0, line + 1): 
  
            # First and last values  
            # in every row are 1 
            if(i is 0 or i is line): 
                arr[line][i] = 1
                print(arr[line][i], end = " ")  
  
            # Other values are sum of values 
            # just above and left of above  
            else: 
                arr[line][i] = (arr[line - 1][i - 1] + 
                                arr[line - 1][i]) 
                print(arr[line][i], end = " ")              
        print("\n", end = "") 
  
# Driver Code 
n = 5
printPascal(n) 

## Find out how print_rangoli works

In [ ]:
def print_rangoli(n):
    mirror = []
    ch=ord('a')+(n-1)
    for i in range(n):
        line= '-'*(2*n-2-2*i)
        for c in range(ch,ch-i-1,-1):
            line+= chr(c)+ '-'
        for c in range(ch-i+1, ch+1, 1):
            line+= chr(c)+ '-'
        line+='-'*(2*n-3-2*i)
        if i == n-1:
            print(line[:-1])
        else:
            mirror.append(line)
            print(line)
            
             
    mirror.reverse()
    for line in mirror:
        print(line)
        


if __name__ == '__main__':
    n = int(input())
    print_rangoli(n)

In [ ]:
num = int(input("numbuh"))
for i in range(0,num):
    for j in range(0,num-i-1):
        print(' ', end="")
    for j in range(0, 2*i+1):
        print("*",end="")
    print()



In [ ]:
# The decimal set:

#        0 nul    1 soh    2 stx    3 etx    4 eot    5 enq    6 ack    7 bel
#        8 bs     9 ht    10 nl    11 vt    12 np    13 cr    14 so    15 si
#       16 dle   17 dc1   18 dc2   19 dc3   20 dc4   21 nak   22 syn   23 etb
#       24 can   25 em    26 sub   27 esc   28 fs    29 gs    30 rs    31 us
#       32 sp    33  !    34  "    35  #    36  $    37  %    38  &    39  '
#       40  (    41  )    42  *    43  +    44  ,    45  -    46  .    47  /
#       48  0    49  1    50  2    51  3    52  4    53  5    54  6    55  7
#       56  8    57  9    58  :    59  ;    60  <    61  =    62  >    63  ?
#       64  @    65  A    66  B    67  C    68  D    69  E    70  F    71  G
#       72  H    73  I    74  J    75  K    76  L    77  M    78  N    79  O
#       80  P    81  Q    82  R    83  S    84  T    85  U    86  V    87  W
#       88  X    89  Y    90  Z    91  [    92  \    93  ]    94  ^    95  _
#       96  `    97  a    98  b    99  c   100  d   101  e   102  f   103  g
#      104  h   105  i   106  j   107  k   108  l   109  m   110  n   111  o
#      112  p   113  q   114  r   115  s   116  t   117  u   118  v   119  w
#      120  x   121  y   122  z   123  {   124  |   125  }   126  ~   127 del

## Tuesday- August 2020


In [ ]:
def cap_substring(string, sub_string):
    cnt= 0 #wratchet
    for i in range(len(string)):
        if string[i:].startswith(sub_string):
            cnt+=1
    return cnt

print(cap_substring('abcdecde', 'cde'))

In [ ]:
s = 'hello world everyone!'
a = s.split(' ')
for i in range(len(a)):
    a[i]= a[i].capitalize()
    return ' '.join(a)

In [ ]:
x ='Chris john paul jeff'
y = x.split(' ')
for i in range(len(y)):
    y[i] = y[i].capitalize()
    return ' '.join(y) 
    


In [12]:
s = 'Chris john paul ringo deb'
a = s.split(' ')
for i in range(len(a)):
    a[i]= a[i].capitalize()
    return ' '.join(a)

SyntaxError: 'return' outside function (<ipython-input-12-1b4b0c0edd8c>, line 5)

In [ ]:
a,b = list(input())


In [ ]:
x = [int(x) for x in input("Enter multiple value: ").split(" ")] 
print("Number of list is: ", x)  

In [ ]:
# my solution
import itertools

A = [int(x) for x in input().split()]
B = [int(y) for y in input().split()]

print(*itertools.product(A, B))

In [ ]:

from itertools import product

A = list(map(int, input().split()))
B = list(map(int, input().split()))

print(*product(A, B))

## Make Sure to Understand the * function. 
### Asterisks for unpacking into function call
### When calling a function, the * operator can be used to unpack an iterable into the arguments in the function call:

In [ ]:
fruits = ['lemon', 'pear', 'watermelon', 'tomato']
print(fruits[0], fruits[1], fruits[2], fruits[3])


In [ ]:
print(*fruits)

In [ ]:
date_info = {'year': "2020", 'month': "01", 'day': "01"}
filename = "{year}-{month}-{day}.txt".format(**date_info)
filename



## Using * multiple times can sometimes be handy:

In [ ]:
fruits = ['apples', 'pairs', 'bananas', 'grapes']
numbers = ['one', 'two', 'four', 'eight']
print(*fruits,*numbers)

In [ ]:
x = " ".join('fruits')
print(x)

In [ ]:
x.split(" ")

In [ ]:
y = " ".join(numbers)
print(y)

In [ ]:
y.split(" ")

# Codelicks

#### get an individual input

In [ ]:
inp = input()
# inp = int(input)

In [ ]:
a, b = input().split()    # takes space separated input


In [ ]:
print(a,b)

In [ ]:
A = [int(x) for x in input().split()] #input as a list

In [ ]:
print(A)

#### But you can also print it as a tuple, list, set, etc.

In [ ]:
print(tuple(A))

### Get input as a string and turn it into a list: split()
####  Remember, you can do many things with a list and apply slicing, list comprehension, identifying a member (lst[i]) etc

In [ ]:
fruits = 'apples pairs bananas grapes' # note that input is usually given as a string

In [ ]:
spl = fruits.split(" ")
print(spl)

### Typically, one performs function on the list(sort, etc) but may then need to put them back together put them back together: join()

In [15]:
joyn = " ".join(spl)
print(joyn)

NameError: name 'spl' is not defined

## Counter


In [16]:
from collections import Counter
c = Counter(a=4, b=2, c=0, d=-2)
sorted(c.elements())

['a', 'a', 'a', 'a', 'b', 'b']

In [17]:
from collections import Counter
myList = [1,1,2,3,4,5,3,2,3,4,2,1,2,3]
print(Counter(myList))

Counter({2: 4, 3: 4, 1: 3, 4: 2, 5: 1})


In [18]:
print(Counter(myList).items())

dict_items([(1, 3), (2, 4), (3, 4), (4, 2), (5, 1)])


In [19]:
print(Counter(myList).keys())

dict_keys([1, 2, 3, 4, 5])


In [20]:
print(Counter(myList).values())

dict_values([3, 4, 4, 2, 1])


In [35]:
for x in range(5):
    a, b = input().split()
print(a*b)
    

6 5
4 2
5 7
5 3
4 8


TypeError: can't multiply sequence by non-int of type 'str'

### Concept If the inputs are given on one line separated by a space character, use split() to get the separate values in the form of a list:

In [22]:
a = input()
lis = a.split()
print (lis)


[]


## If the list values are all integer types, use the map() method to convert all the strings to integers.

In [23]:
newlis = list(map(int, lis))
print (newlis)

[]


## D&C Pascal Triangle

In [30]:
def pascal(n):
    if n == 1:
        print(1)
        return
    if n == 2:
        print(1)
        print('1 1')
        return
    print(1)
    print('1 1')
    previous_line = [1,1]
    for i in range(3,n+1):
        next_line = [1]
        for j in range(len(previous_line)-1):
            next_line.append(previous_line[j]+previous_line[j+1])
        next_line.append(1)
        print(' '.join(map(str,next_line)))
        previous_line = next_line
        
pascal(5)
        
            
    
        
        
    
    
    

1
1 1
1 2 1
1 3 3 1
1 4 6 4 1


## Symmetric Difference lists, set

In [24]:
m = int(input())
lst1 =[int(x) for x in input().split()]
set1 = set(lst1)
#print(set1)
n= int(input())
lst2 =[int(y) for y in input().split()]
set2 = set(lst2)
#print(set2)
#print(set1.symmetric_difference(set2)) 
output = set1.symmetric_difference(set2)# it returns a set, set is iterable it can be iterated but cannot be sorted, thus convert to a list
output = list(output)
output.sort()
for x in output:
    print(x)

5
5678
6
56
56
5678


In [10]:
from collections import Counter
num_shoes = int(input())
shoe_sizes = [int(y) for y in input().split()] #input as a list
num_customers = int(input())
counter = Counter(shoe_sizes)
income = 0
for _ in range(num_customers):
    lst =[int(x) for x in input().split()]
    size, money = lst[0],lst[1] #solve more problems with dictionaries
    if size in counter and counter[size]>0:
        income+=money
        counter[size] -= 1
print(income)

ValueError: invalid literal for int() with base 10: ''

In [11]:
# least number of lines BUT harder to read
from collections import Counter
num_shoes = int(input())
shoe_sizes = [int(y) for y in input().split()] #input as a list
num_customers, counter, income = int(input()), Counter(shoe_sizes), 0
for _ in range(num_customers):
    size,money =tuple([int(x) for x in input().split()])
    if size in counter and counter[size]>0:
        income+=money
        counter[size] -= 1
print(income)

ValueError: invalid literal for int() with base 10: ''

In [12]:
print(4+5)

9


In [28]:

mirror = []
m,n = tuple([int(x) for x in input().split()])
for i in range(n//2):
    line= '-'*((m-3*(2*i+1))//2) + '.|.'*(2*i+1) + '-'*((m-3*(2*i+1))//2)
    print(line)
    mirror.append(line)
line = '-'*((m-7)//2) + 'WELCOME' + '-'*((m-7)//2)
print(line)
mirror.reverse()
for line in mirror:
    print(line)

17 21
-------.|.-------
----.|..|..|.----
-.|..|..|..|..|.-
.|..|..|..|..|..|..|.
.|..|..|..|..|..|..|..|..|.
.|..|..|..|..|..|..|..|..|..|..|.
.|..|..|..|..|..|..|..|..|..|..|..|..|.
.|..|..|..|..|..|..|..|..|..|..|..|..|..|..|.
.|..|..|..|..|..|..|..|..|..|..|..|..|..|..|..|..|.
.|..|..|..|..|..|..|..|..|..|..|..|..|..|..|..|..|..|..|.
-----WELCOME-----
.|..|..|..|..|..|..|..|..|..|..|..|..|..|..|..|..|..|..|.
.|..|..|..|..|..|..|..|..|..|..|..|..|..|..|..|..|.
.|..|..|..|..|..|..|..|..|..|..|..|..|..|..|.
.|..|..|..|..|..|..|..|..|..|..|..|..|.
.|..|..|..|..|..|..|..|..|..|..|.
.|..|..|..|..|..|..|..|..|.
.|..|..|..|..|..|..|.
-.|..|..|..|..|.-
----.|..|..|.----
-------.|.-------


## Finding the percentage

In [ ]:
if __name__ == '__main__':
    n = int(input())
    student_marks = {}
    for _ in range(n):
        name, *line = input().split() #*line is a tuple of 3 vars
        scores = list(map(float, line))
        student_marks[name] = scores # dict with a list of numbers as v and name = k
    query_name = input()
    scores = student_marks[query_name]
    ave = sum(scores)/len(scores)
    print("{:.2f}".format(ave))
    
    


# ASK DIBYENDU WHY I'M NOT GETTING PROPER OUTPUT
## Transpose and Flatten

In [69]:
# Input Format

# The first line contains the space separated values of N and M.
# The next N lines contains the space separated elements of M columns.
import numpy
N, M = map(int, input().split())
lst=[]
n = int(N)
for _ in range(n):
    r = input().strip().split()
    lst.append(r)
array = numpy.array(lst)
trans = numpy.transpose(array)
flat = array.flatten()
print(trans)
print(flat)


    
    
     

    
    
    
    
    
    


2 2
1 2
3 4
[['1' '3']
 ['2' '4']]
['1' '2' '3' '4']


In [57]:
* THIS HAS THE PROPER OUTPUT
array = numpy.array([input().strip().split() for _ in range(n)], int)
print (array.transpose())
print (array.flatten())

2 2
1 2
3 4
[[1 3]
 [2 4]]
[1 2 3 4]


In [63]:
import numpy

array_1 = numpy.array([[1,2,3],[0,0,0]])
array_2 = numpy.array([[0,0,0],[7,8,9]])

print(numpy.concatenate((array_1, array_2), axis = 1))   

[[1 2 3 0 0 0]
 [0 0 0 7 8 9]]


In [64]:
import numpy

array_1 = numpy.array([[1,2,3],[0,0,0]])
array_2 = numpy.array([[0,0,0],[7,8,9]])

print(numpy.concatenate((array_1, array_2), axis = 0))   

[[1 2 3]
 [0 0 0]
 [0 0 0]
 [7 8 9]]


In [75]:
# Input Format

# The first line contains space separated integers N , M and P.
# The next N lines contains the space separated elements of the P columns.
# After that, the next M lines contains the space separated elements of the P columns.

# Output Format

# Print the concatenated array of size X.
import numpy
n, m, p = map(int, input().split())
lst1= []
n = int(N)
for _ in range(n):
    r = input().split()
    lst.append(r)
array1 = numpy.array(lst1)
lst2 = []
M, P = map(int, input().split())
lst2 = []


        
    

4 3 2
1 2
1 2
1 2
1 2
3 4
3 4
3 4
1 2
3 4
4 5
6 7
8 9
4 5
6 7
<map object at 0x7fbfc9448910> <map object at 0x7fbfc9448250> <map object at 0x7fbfc922c730> <map object at 0x7fbfc922c3a0> 


In [68]:
txt = "apple banana cherry orange"
# setting the maxsplit parameter to 1, will return a list with 2 elements!
x = txt.split(" ", 2)

print(x)

['apple', 'banana', 'cherry orange']


In [ ]:
import numpy
n, m, p = map(int, input().split())
array1 = numpy.array([input().strip().split() for _ in range(n)], int)
array2 = numpy.array([input().strip().split() for _ in range(m)], int)
print (numpy.concatenate((array1, array2), axis = 0))

In [2]:
string = 'ABCDEFGHIJKLIMNOQRSTUVWXYZ'
import textwrap
print (textwrap.fill(string,4))


ABCD
EFGH
IJKL
IMNO
QRST
UVWX
YZ


In [9]:
# Enter your code here. Read input from STDIN. Print output to STDOUT

mirror = []
n, m = tuple([int(x) for x in input().split()])
for i in range(n//2):
    line= '-'*((m-3*(2*i+1))//2) + '.|.'*(2*i+1) + '-'*((m-3*(2*i+1))//2)
    print(line)
    mirror.append(line)
line = '-'*((m-7)//2) + 'WELCOME' + '-'*((m-7)//2)
print(line)           
mirror.reverse()
for line in mirror:
    print(line)


1 3
WELCOME


## Capitalize!



In [11]:
# Print the capitalized string, S.

# Sample Input
# chris alan

# Sample Output
# Chris Alan
import os 

def solve(s):
    a = s.split(' ')
    for i in range(len(a)):
        a[i]= a[i].capitalize()
    return ' '.join(a)

     

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    result = solve(s)

    fptr.write(result + '\n')

    fptr.close()

KeyError: 'OUTPUT_PATH'

In [12]:
yes_votes = 42_572_654
no_votes = 43_132_495
percentage = yes_votes / (yes_votes + no_votes)
'{:-9} YES votes  {:2.2%}'.format(yes_votes, percentage)


' 42572654 YES votes  49.67%'

In [14]:
 
s = 'Hello, world.'
str(s)

repr(s)

str(1/7)

x = 10 * 3.25
y = 200 * 200
s = 'The value of x is ' + repr(x) + ', and y is ' + repr(y) + '...'
print(s)

# The repr() of a string adds string quotes and backslashes:
hello = 'hello, world\n'
hellos = repr(hello)
print(hellos)

# The argument to repr() may be any Python object:
repr((x, y, ('spam', 'eggs')))

The value of x is 32.5, and y is 40000...
'hello, world\n'


"(32.5, 40000, ('spam', 'eggs'))"

In [15]:
import math
print(f'The value of pi is approximately {math.pi:.3f}.')


The value of pi is approximately 3.142.


In [16]:

table = {'Sjoerd': 4127, 'Jack': 4098, 'Dcab': 7678}
for name, phone in table.items():
    print(f'{name:10} ==> {phone:10d}')

Sjoerd     ==>       4127
Jack       ==>       4098
Dcab       ==>       7678


In [17]:
animals = 'eels'
print(f'My hovercraft is full of {animals}.')

print(f'My hovercraft is full of {animals!r}.')


My hovercraft is full of eels.
My hovercraft is full of 'eels'.


In [20]:
for x in range(1, 11):
    print('{0:6d} {1:5d} {2:5d}'.format(x, x*x, x*x*x))


     1     1     1
     2     4     8
     3     9    27
     4    16    64
     5    25   125
     6    36   216
     7    49   343
     8    64   512
     9    81   729
    10   100  1000


In [21]:
for x in range(1, 11):
    print(repr(x).rjust(2), repr(x*x).rjust(3), end=' ')
    # Note use of 'end' on previous line
    print(repr(x*x*x).rjust(4))


 1   1    1
 2   4    8
 3   9   27
 4  16   64
 5  25  125
 6  36  216
 7  49  343
 8  64  512
 9  81  729
10 100 1000
