# Lecture 02

# Expressions

In [142]:
2 + 3

5

In [2]:
2 * 3

6

In [3]:
2 * * 3

SyntaxError: invalid syntax (<ipython-input-3-0f343c0fc354>, line 1)

In [ ]:
2 ** 3

In [ ]:
2 ** 4

In [ ]:
2 / 3

In [ ]:
2 / 0

In [ ]:
1 + 2 * 3 * 4 * 5 / 6 ** 3 + 7 + 8 - 9 + 10

In [ ]:
1 + 2 * (3 * 4 * 5 / 6) ** 3 + 7 + 8 - 9 + 10

## Example: Slopes

In [4]:
(25050 - 3262)/(1963 - 1939)

907.8333333333334

In [5]:
(62799 - 25050)/(1976 - 1963)

2903.769230769231

## Numbers

ints vs. floats

In [6]:
2

2

In [7]:
2.0

2.0

In [8]:
2 / 1

2.0

In [9]:
1 + 1

2

In [10]:
5 / 7000

0.0007142857142857143

Scientific notation is used when lots of digits

In [11]:
5 / 7000000

7.142857142857143e-07

In [12]:
7.14e-07

7.14e-07

In [13]:
0.000000000000000123456789

1.23456789e-16

In [14]:
0.000000000000000123456789 ** 30

0.0

In [15]:
10000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000

10000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000

In [16]:
10000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000.2

inf

Be careful about numerical precision!

In [17]:
0.666666666666666666123456789

0.6666666666666666

In [18]:
0.6666666666666666 - 0.6666666666666666123456789

0.0

In [19]:
2 ** 0.5

1.4142135623730951

In [20]:
(2 ** 0.5) * (2 ** 0.5)

2.0000000000000004

In [21]:
(2 ** 0.5) * (2 ** 0.5) - 2

4.440892098500626e-16

### Discussion Question

ranke in order from least to greatest

In [22]:
3 * 10 ** 10

30000000000

In [23]:
10 * 3 ** 10

590490

In [24]:
(10 * 3) ** 10

590490000000000

In [25]:
10 / 3 / 10

0.33333333333333337

In [26]:
10 / (3 / 10)

33.333333333333336

## Names

In [27]:
more_than_1 = 2 + 3

In [28]:
more_than_1

5

In [29]:
more_than_1 * 2

10

In [30]:
more_than_1

5

Only the last line prints when putting multiple lines in a cell:

In [31]:
more_than_1
7+7

14

In [32]:
x = 4
y = x + 1
y

5

Setting `x` doesn't change y:

In [33]:
x = 3
x

3

In [34]:
y

5

## Growth

In [35]:
fed_budget_2010 = 3176000000000
fed_budget_2020 = 6100000000000
fed_budget_2020 / fed_budget_2010

1.920654911838791

In [36]:
fed_budget_2010 = 3.17
fed_budget_2020 = 6.1
fed_budget_2020 / fed_budget_2010

1.9242902208201893

In [37]:
g = (fed_budget_2020 / fed_budget_2010) ** (1/10) - 1
g

0.06764545914176923

In [38]:
(1 + g) ** 10 * fed_budget_2010

6.099999999999994

# Data Types

In [39]:
abs(-12)

12

Don't worry about learning all the functions.

In [40]:
round(5 - 1.3333)

4

In [41]:
round(5 - 1.3333, 2)

3.67

In [42]:
max(2, 2 + 3, 4)

5

In [43]:
import math
math.sqrt(9)

3.0

In [44]:
9 ** 0.5

3.0

Introduce shortcuts

In [45]:
math.sin(math.pi / 2)

1.0

`math.log` and how to read optional arguments.

In [46]:
math.log(1000)

6.907755278982137

In [47]:
math.pow(math.e, 6.907755278982137)

999.9999999999994

# Discussion Question!

## which of the following commands results in an error?

In [48]:
x = 3
y = -2.0

In [49]:
abs (x, y)

TypeError: abs() takes exactly one argument (2 given)

In [52]:
math.pow(x,abs(y))

9.0

In [53]:
round(x,max(abs(y ** 2))))

SyntaxError: invalid syntax (<ipython-input-53-5d3a174deeb8>, line 1)

In [54]:
math.pow(x, math.pow(y, x))

0.00015241579027587258

## Strings

In [55]:
"data " + "science"

'data science'

In [56]:
'it's an error'

SyntaxError: invalid syntax (<ipython-input-56-b0f7c520dae9>, line 1)

In [57]:
"it's ok"

"it's ok"

In [58]:
"la"*3

'lalala'

In [59]:
"Cause the players gonna "+"play " * 5

'Cause the players gonna play play play play play '

In [60]:
"And the haters gonna "+ "hate " * 5

'And the haters gonna hate hate hate hate hate '

In [61]:
"Baby, I'm just gonna " + "shake " * 5

"Baby, I'm just gonna shake shake shake shake shake "

In [62]:
"I shake it off" * 2

'I shake it offI shake it off'

In [63]:
'data'.count('a')

2

In [64]:
'Mahdi is kinda cool'.replace('kinda', 'very')

'Mahdi is very cool'

## Types

In [65]:
3

3

In [66]:
3.0

3.0

In [67]:
type(3)

int

In [68]:
type(3.0)

float

In [69]:
type("three")

str

In [70]:
type("3")

str

In [71]:
3 + 3

6

In [72]:
"3" + "3"

'33'

In [73]:
3 + "3"

TypeError: unsupported operand type(s) for +: 'int' and 'str'

^ Type error

In [74]:
int('3' + '4') + 5

39

In [75]:
fraction = ".123456789"
fraction + fraction

'.123456789.123456789'

In [76]:
3 > 2

True

In [77]:
type(3 > 2)

bool

 # Arrays

In [78]:
richie = 40
david = 10
daf = 8
angel = 12
Mahdi = 0

Everyone meets each other

In [79]:
richie = richie + 4
david = david + 4
daf = daf + 4
angel = angel + 4
Mahdi = Mahdi + 4

In [80]:
mahdi

NameError: name 'mahdi' is not defined

This is a pain!

In [81]:
make_array ([40, 10, 8, 12, 0])

NameError: name 'make_array' is not defined

In [82]:
from datascience import *

In [83]:
friendship = make_array ([40, 10, 8, 12, 0])
friendship

array([[40, 10,  8, 12,  0]])

In [84]:
friendship + 4

array([[44, 14, 12, 16,  4]])

### Slids

In [85]:
baseline_high = 14.48
highs = make_array(baseline_high - 0.880, #1850
                   baseline_high - 0.093, #1900
                   baseline_high + 0.105, #1950
                   baseline_high + 0.684  #2000
                  ) 
highs

array([13.6  , 14.387, 14.585, 15.164])

In [86]:
(9/5) * highs + 32

array([56.48  , 57.8966, 58.253 , 59.2952])

In [87]:
baseline_low = 3.00
lows = make_array(baseline_low - 0.872, 
                  baseline_low - 0.629,
                  baseline_low - 0.126, 
                  baseline_low + 0.728)
lows

array([2.128, 2.371, 2.874, 3.728])

In [88]:
highs - lows

array([11.472, 12.016, 11.711, 11.436])

## Ranges

In [89]:
np.arange(5)

NameError: name 'np' is not defined

### Leibniz formula for π

$$\pi = 4 \cdot \left(\frac{1}{1} - \frac{1}{3} + \frac{1}{5} - \frac{1}{7} + \frac{1}{9} - \frac{1}{11} + \dots\right)$$

In [90]:
import numpy as np

In [91]:
a = np.arange(1, 12, 4)
a

array([1, 5, 9])

In [92]:
4 * sum(1/a - 1/(a+2))

2.9760461760461765

# Tables

In [93]:
import numpy as np
np.set_printoptions(threshold=50)

In [94]:
from datascience import *

In [95]:
Table()

In [96]:
Table().with_columns('Petals', make_array(8, 34, 5))

Petals
8
34
5

In [97]:
Table().with_columns(
    'Petals', make_array(8, 34, 5),
    'Name', make_array('lotus', 'sunflower', 'rose')
)

Petals | Name
8      | lotus
34     | sunflower
5      | rose

In [98]:
flowers = Table().with_columns(
    'Petals', make_array(8, 34, 5),
    'Name', make_array('lotus', 'sunflower', 'rose')
)

flowers.with_column(
    'Color', make_array('pink', 'yellow', 'red')
)

Petals | Name      | Color
8      | lotus     | pink
34     | sunflower | yellow
5      | rose      | red

In [99]:
flowers

Petals | Name
8      | lotus
34     | sunflower
5      | rose

## Mutation

##### example

In [100]:
flowers = flowers.with_column(
    'Color', make_array('pink', 'yellow', 'red')
)

In [101]:
flowers

Petals | Name      | Color
8      | lotus     | pink
34     | sunflower | yellow
5      | rose      | red

## Minard's Map

In [102]:
minard = Table.read_table('minard.csv') 
minard

Longitude | Latitude | City        | Direction | Survivors
24        | 54.9     | Kaunas      | Advance   | 340000
30.2      | 55.2     | Vitebsk     | Advance   | 175000
32        | 54.8     | Smolensk    | Advance   | 145000
37.6      | 55.8     | Moscow      | Advance   | 100000
34.3      | 55.2     | Vyazma      | Retreat   | 55000
32        | 54.6     | Smolensk    | Retreat   | 24000
30.4      | 54.4     | Orsha       | Retreat   | 20000
26.8      | 54.3     | Maladyechna | Retreat   | 12000
24.1      | 54.4     | Kaunas      | Retreat   | 4000

In [103]:
minard.num_columns

5

In [104]:
minard.labels

('Longitude', 'Latitude', 'City', 'Direction', 'Survivors')

In [105]:
minard.relabeled('City', 'City Name')

Longitude | Latitude | City Name   | Direction | Survivors
24        | 54.9     | Kaunas      | Advance   | 340000
30.2      | 55.2     | Vitebsk     | Advance   | 175000
32        | 54.8     | Smolensk    | Advance   | 145000
37.6      | 55.8     | Moscow      | Advance   | 100000
34.3      | 55.2     | Vyazma      | Retreat   | 55000
32        | 54.6     | Smolensk    | Retreat   | 24000
30.4      | 54.4     | Orsha       | Retreat   | 20000
26.8      | 54.3     | Maladyechna | Retreat   | 12000
24.1      | 54.4     | Kaunas      | Retreat   | 4000

In [106]:
minard = minard.relabeled('City', 'City Name')
minard

Longitude | Latitude | City Name   | Direction | Survivors
24        | 54.9     | Kaunas      | Advance   | 340000
30.2      | 55.2     | Vitebsk     | Advance   | 175000
32        | 54.8     | Smolensk    | Advance   | 145000
37.6      | 55.8     | Moscow      | Advance   | 100000
34.3      | 55.2     | Vyazma      | Retreat   | 55000
32        | 54.6     | Smolensk    | Retreat   | 24000
30.4      | 54.4     | Orsha       | Retreat   | 20000
26.8      | 54.3     | Maladyechna | Retreat   | 12000
24.1      | 54.4     | Kaunas      | Retreat   | 4000

In [107]:
minard.column('Survivors')

array([340000, 175000, 145000, 100000,  55000,  24000,  20000,  12000,
         4000])

Let's add a column:

In [108]:
initial = minard.column('Survivors').item(0)
minard = minard.with_column(
    'Percent Surviving', minard.column('Survivors')/initial
)
minard

Longitude | Latitude | City Name   | Direction | Survivors | Percent Surviving
24        | 54.9     | Kaunas      | Advance   | 340000    | 1
30.2      | 55.2     | Vitebsk     | Advance   | 175000    | 0.514706
32        | 54.8     | Smolensk    | Advance   | 145000    | 0.426471
37.6      | 55.8     | Moscow      | Advance   | 100000    | 0.294118
34.3      | 55.2     | Vyazma      | Retreat   | 55000     | 0.161765
32        | 54.6     | Smolensk    | Retreat   | 24000     | 0.0705882
30.4      | 54.4     | Orsha       | Retreat   | 20000     | 0.0588235
26.8      | 54.3     | Maladyechna | Retreat   | 12000     | 0.0352941
24.1      | 54.4     | Kaunas      | Retreat   | 4000      | 0.0117647

In [109]:
minard.set_format('Percent Surviving', PercentFormatter)

Longitude | Latitude | City Name   | Direction | Survivors | Percent Surviving
24        | 54.9     | Kaunas      | Advance   | 340000    | 100.00%
30.2      | 55.2     | Vitebsk     | Advance   | 175000    | 51.47%
32        | 54.8     | Smolensk    | Advance   | 145000    | 42.65%
37.6      | 55.8     | Moscow      | Advance   | 100000    | 29.41%
34.3      | 55.2     | Vyazma      | Retreat   | 55000     | 16.18%
32        | 54.6     | Smolensk    | Retreat   | 24000     | 7.06%
30.4      | 54.4     | Orsha       | Retreat   | 20000     | 5.88%
26.8      | 54.3     | Maladyechna | Retreat   | 12000     | 3.53%
24.1      | 54.4     | Kaunas      | Retreat   | 4000      | 1.18%

In [110]:
minard.select('Longitude', 'Direction')

Longitude | Direction
24        | Advance
30.2      | Advance
32        | Advance
37.6      | Advance
34.3      | Retreat
32        | Retreat
30.4      | Retreat
26.8      | Retreat
24.1      | Retreat

Discussion question: Why does this error?

In [111]:
minard.select(0, 3).select(3)

IndexError: tuple index out of range

In [112]:
minard.select(0, 3).select(1)

Direction
Advance
Advance
Advance
Advance
Retreat
Retreat
Retreat
Retreat
Retreat

In [113]:
minard.column('Survivors') + 1

array([340001, 175001, 145001, 100001,  55001,  24001,  20001,  12001,
         4001])

In [114]:
minard.select('Survivors') + 1

TypeError: unsupported operand type(s) for +: 'Table' and 'int'

In [115]:
minard.drop('Longitude', 'Latitude', 'Direction')

City Name   | Survivors | Percent Surviving
Kaunas      | 340000    | 100.00%
Vitebsk     | 175000    | 51.47%
Smolensk    | 145000    | 42.65%
Moscow      | 100000    | 29.41%
Vyazma      | 55000     | 16.18%
Smolensk    | 24000     | 7.06%
Orsha       | 20000     | 5.88%
Maladyechna | 12000     | 3.53%
Kaunas      | 4000      | 1.18%

## Sort

In [116]:
nba = Table.read_table('nba_salaries.csv')
nba

PLAYER           | POSITION | TEAM          | '15-'16 SALARY
Paul Millsap     | PF       | Atlanta Hawks | 18.6717
Al Horford       | C        | Atlanta Hawks | 12
Tiago Splitter   | C        | Atlanta Hawks | 9.75625
Jeff Teague      | PG       | Atlanta Hawks | 8
Kyle Korver      | SG       | Atlanta Hawks | 5.74648
Thabo Sefolosha  | SF       | Atlanta Hawks | 4
Mike Scott       | PF       | Atlanta Hawks | 3.33333
Kent Bazemore    | SF       | Atlanta Hawks | 2
Dennis Schroder  | PG       | Atlanta Hawks | 1.7634
Tim Hardaway Jr. | SG       | Atlanta Hawks | 1.30452
... (407 rows omitted)

In [117]:
nba.show(3)

So how do I find the player who made the most money?

In [118]:
nba.sort(3)

PLAYER                 | POSITION | TEAM                 | '15-'16 SALARY
Thanasis Antetokounmpo | SF       | New York Knicks      | 0.030888
Jordan McRae           | SG       | Phoenix Suns         | 0.049709
Cory Jefferson         | PF       | Phoenix Suns         | 0.049709
Elliot Williams        | SG       | Memphis Grizzlies    | 0.055722
Orlando Johnson        | SG       | Phoenix Suns         | 0.055722
Phil Pressey           | PG       | Phoenix Suns         | 0.055722
Keith Appling          | PG       | Orlando Magic        | 0.061776
Sean Kilpatrick        | SG       | Denver Nuggets       | 0.099418
Erick Green            | PG       | Utah Jazz            | 0.099418
Jeff Ayres             | PF       | Los Angeles Clippers | 0.111444
... (407 rows omitted)

In [119]:
nba.sort(3, descending=True)

PLAYER          | POSITION | TEAM                  | '15-'16 SALARY
Kobe Bryant     | SF       | Los Angeles Lakers    | 25
Joe Johnson     | SF       | Brooklyn Nets         | 24.8949
LeBron James    | SF       | Cleveland Cavaliers   | 22.9705
Carmelo Anthony | SF       | New York Knicks       | 22.875
Dwight Howard   | C        | Houston Rockets       | 22.3594
Chris Bosh      | PF       | Miami Heat            | 22.1927
Chris Paul      | PG       | Los Angeles Clippers  | 21.4687
Kevin Durant    | SF       | Oklahoma City Thunder | 20.1586
Derrick Rose    | PG       | Chicago Bulls         | 20.0931
Dwyane Wade     | SG       | Miami Heat            | 20
... (407 rows omitted)

In [120]:
help(nba.sort)

Help on method sort in module datascience.tables:

sort(column_or_label, descending=False, distinct=False) method of datascience.tables.Table instance
    Return a Table of rows sorted according to the values in a column.
    
    Args:
        ``column_or_label``: the column whose values are used for sorting.
    
        ``descending``: if True, sorting will be in descending, rather than
            ascending order.
    
        ``distinct``: if True, repeated values in ``column_or_label`` will
            be omitted.
    
    Returns:
        An instance of ``Table`` containing rows sorted based on the values
        in ``column_or_label``.
    
    >>> marbles = Table().with_columns(
    ...    "Color", make_array("Red", "Green", "Blue", "Red", "Green", "Green"),
    ...    "Shape", make_array("Round", "Rectangular", "Rectangular", "Round", "Rectangular", "Round"),
    ...    "Amount", make_array(4, 6, 12, 7, 9, 2),
    ...    "Price", make_array(1.30, 1.30, 2.00, 1.75, 1.40, 1.00)

In [121]:
nba.sort(3, descending=True).sort(1)

PLAYER           | POSITION | TEAM                  | '15-'16 SALARY
Dwight Howard    | C        | Houston Rockets       | 22.3594
Marc Gasol       | C        | Memphis Grizzlies     | 19.688
Enes Kanter      | C        | Oklahoma City Thunder | 16.4075
DeMarcus Cousins | C        | Sacramento Kings      | 15.852
Roy Hibbert      | C        | Los Angeles Lakers    | 15.5922
Tristan Thompson | C        | Cleveland Cavaliers   | 14.2609
Andrew Bogut     | C        | Golden State Warriors | 13.8
Al Jefferson     | C        | Charlotte Hornets     | 13.5
Joakim Noah      | C        | Chicago Bulls         | 13.4
Nene Hilario     | C        | Washington Wizards    | 13
... (407 rows omitted)

In [122]:
nba.sort(3, descending=True).sort(1, distinct=True)

PLAYER        | POSITION | TEAM                 | '15-'16 SALARY
Dwight Howard | C        | Houston Rockets      | 22.3594
Chris Bosh    | PF       | Miami Heat           | 22.1927
Chris Paul    | PG       | Los Angeles Clippers | 21.4687
Kobe Bryant   | SF       | Los Angeles Lakers   | 25
Dwyane Wade   | SG       | Miami Heat           | 20

Discussion question: What is wrong with ths following line?

In [123]:
nba.sort(3, descending=True).select('PLAYER').sort('PLAYER', descending=True)

PLAYER
Zoran Dragic
Zaza Pachulia
Zach Randolph
Zach LaVine
Wilson Chandler
Willie Cauley-Stein
Will Barton
Wesley Johnson
Wayne Ellington
Walter Tavares
... (407 rows omitted)

## Lists

Arrays all need the same type of thing.

In [124]:
make_array(2, 'three')

array(['2', 'three'], dtype='<U21')

Lists don't care.

In [125]:
[2, 'three']

[2, 'three']

In [126]:
type([2, 'three'])

list

In [127]:
row = ['Mahdi Zareei', 'PG', 'Tec Data Scientists', 0.0]
nba.with_row(row).sort(3)

PLAYER                 | POSITION | TEAM                | '15-'16 SALARY
Mahdi Zareei           | PG       | Tec Data Scientists | 0
Thanasis Antetokounmpo | SF       | New York Knicks     | 0.030888
Jordan McRae           | SG       | Phoenix Suns        | 0.049709
Cory Jefferson         | PF       | Phoenix Suns        | 0.049709
Elliot Williams        | SG       | Memphis Grizzlies   | 0.055722
Orlando Johnson        | SG       | Phoenix Suns        | 0.055722
Phil Pressey           | PG       | Phoenix Suns        | 0.055722
Keith Appling          | PG       | Orlando Magic       | 0.061776
Sean Kilpatrick        | SG       | Denver Nuggets      | 0.099418
Erick Green            | PG       | Utah Jazz           | 0.099418
... (408 rows omitted)

## Take

In [128]:
nba.take(0)

PLAYER       | POSITION | TEAM          | '15-'16 SALARY
Paul Millsap | PF       | Atlanta Hawks | 18.6717

In [129]:
nba.take(make_array(0, 1, 2))

PLAYER         | POSITION | TEAM          | '15-'16 SALARY
Paul Millsap   | PF       | Atlanta Hawks | 18.6717
Al Horford     | C        | Atlanta Hawks | 12
Tiago Splitter | C        | Atlanta Hawks | 9.75625

In [130]:
nba.sort(3, descending=True).take(make_array(0, 1, 2))

PLAYER       | POSITION | TEAM                | '15-'16 SALARY
Kobe Bryant  | SF       | Los Angeles Lakers  | 25
Joe Johnson  | SF       | Brooklyn Nets       | 24.8949
LeBron James | SF       | Cleveland Cavaliers | 22.9705

In [131]:
rich = nba.sort(3, descending=True).take(make_array(0, 1, 2))
rich.sort(2)

PLAYER       | POSITION | TEAM                | '15-'16 SALARY
Joe Johnson  | SF       | Brooklyn Nets       | 24.8949
LeBron James | SF       | Cleveland Cavaliers | 22.9705
Kobe Bryant  | SF       | Los Angeles Lakers  | 25

In [132]:
nba

PLAYER           | POSITION | TEAM          | '15-'16 SALARY
Paul Millsap     | PF       | Atlanta Hawks | 18.6717
Al Horford       | C        | Atlanta Hawks | 12
Tiago Splitter   | C        | Atlanta Hawks | 9.75625
Jeff Teague      | PG       | Atlanta Hawks | 8
Kyle Korver      | SG       | Atlanta Hawks | 5.74648
Thabo Sefolosha  | SF       | Atlanta Hawks | 4
Mike Scott       | PF       | Atlanta Hawks | 3.33333
Kent Bazemore    | SF       | Atlanta Hawks | 2
Dennis Schroder  | PG       | Atlanta Hawks | 1.7634
Tim Hardaway Jr. | SG       | Atlanta Hawks | 1.30452
... (407 rows omitted)

In [133]:
np.arange(8, 15)

array([ 8,  9, 10, 11, 12, 13, 14])

In [134]:
nba.take(np.arange(8, 15))

PLAYER           | POSITION | TEAM           | '15-'16 SALARY
Dennis Schroder  | PG       | Atlanta Hawks  | 1.7634
Tim Hardaway Jr. | SG       | Atlanta Hawks  | 1.30452
Walter Tavares   | C        | Atlanta Hawks  | 1
Jason Richardson | SG       | Atlanta Hawks  | 0.947276
Lamar Patterson  | SG       | Atlanta Hawks  | 0.525093
Terran Petteway  | SG       | Atlanta Hawks  | 0.525093
Avery Bradley    | PG       | Boston Celtics | 7.73034

## Where

In [135]:
salary = 3
nba.sort(salary)

PLAYER                 | POSITION | TEAM                 | '15-'16 SALARY
Thanasis Antetokounmpo | SF       | New York Knicks      | 0.030888
Jordan McRae           | SG       | Phoenix Suns         | 0.049709
Cory Jefferson         | PF       | Phoenix Suns         | 0.049709
Elliot Williams        | SG       | Memphis Grizzlies    | 0.055722
Orlando Johnson        | SG       | Phoenix Suns         | 0.055722
Phil Pressey           | PG       | Phoenix Suns         | 0.055722
Keith Appling          | PG       | Orlando Magic        | 0.061776
Sean Kilpatrick        | SG       | Denver Nuggets       | 0.099418
Erick Green            | PG       | Utah Jazz            | 0.099418
Jeff Ayres             | PF       | Los Angeles Clippers | 0.111444
... (407 rows omitted)

In [136]:
nba.where(salary, are.above(10))

PLAYER         | POSITION | TEAM              | '15-'16 SALARY
Paul Millsap   | PF       | Atlanta Hawks     | 18.6717
Al Horford     | C        | Atlanta Hawks     | 12
Joe Johnson    | SF       | Brooklyn Nets     | 24.8949
Thaddeus Young | PF       | Brooklyn Nets     | 11.236
Al Jefferson   | C        | Charlotte Hornets | 13.5
Nicolas Batum  | SG       | Charlotte Hornets | 13.1253
Kemba Walker   | PG       | Charlotte Hornets | 12
Derrick Rose   | PG       | Chicago Bulls     | 20.0931
Jimmy Butler   | SG       | Chicago Bulls     | 16.4075
Joakim Noah    | C        | Chicago Bulls     | 13.4
... (59 rows omitted)

In [137]:
nba.where(salary, are.above(10)).sort(salary)

PLAYER          | POSITION | TEAM                 | '15-'16 SALARY
DeMar DeRozan   | SG       | Toronto Raptors      | 10.05
Gerald Wallace  | SF       | Philadelphia 76ers   | 10.1059
Luol Deng       | SF       | Miami Heat           | 10.1516
Monta Ellis     | SG       | Indiana Pacers       | 10.3
Wilson Chandler | SF       | Denver Nuggets       | 10.4494
Brendan Haywood | C        | Cleveland Cavaliers  | 10.5225
Jrue Holiday    | PG       | New Orleans Pelicans | 10.5955
Tyreke Evans    | SG       | New Orleans Pelicans | 10.7346
Marcin Gortat   | C        | Washington Wizards   | 11.2174
Thaddeus Young  | PF       | Brooklyn Nets        | 11.236
... (59 rows omitted)

In [138]:
nba.where('TEAM', 'Golden State Warriors')

PLAYER            | POSITION | TEAM                  | '15-'16 SALARY
Klay Thompson     | SG       | Golden State Warriors | 15.501
Draymond Green    | PF       | Golden State Warriors | 14.2609
Andrew Bogut      | C        | Golden State Warriors | 13.8
Andre Iguodala    | SF       | Golden State Warriors | 11.7105
Stephen Curry     | PG       | Golden State Warriors | 11.3708
Jason Thompson    | PF       | Golden State Warriors | 7.00847
Shaun Livingston  | PG       | Golden State Warriors | 5.54373
Harrison Barnes   | SF       | Golden State Warriors | 3.8734
Marreese Speights | C        | Golden State Warriors | 3.815
Leandro Barbosa   | SG       | Golden State Warriors | 2.5
... (4 rows omitted)

In [139]:
nba.where('TEAM', are.containing('Los Angeles')).sort(salary)

PLAYER          | POSITION | TEAM                 | '15-'16 SALARY
Jeff Ayres      | PF       | Los Angeles Clippers | 0.111444
Anthony Brown   | SF       | Los Angeles Lakers   | 0.7
Pablo Prigioni  | PG       | Los Angeles Clippers | 0.947726
Robert Sacre    | C        | Los Angeles Lakers   | 0.981348
Jordan Hamilton | SG       | Los Angeles Clippers | 1.01542
Lester Hudson   | SG       | Los Angeles Clippers | 1.01542
Cole Aldrich    | C        | Los Angeles Clippers | 1.1006
Wesley Johnson  | SF       | Los Angeles Clippers | 1.1006
Larry Nance Jr. | PF       | Los Angeles Lakers   | 1.1556
C.J. Wilcox     | SG       | Los Angeles Clippers | 1.15968
... (14 rows omitted)

In [140]:
nba.where(salary, are.between(3, 4))

PLAYER           | POSITION | TEAM                  | '15-'16 SALARY
Mike Scott       | PF       | Atlanta Hawks         | 3.33333
Marcus Smart     | PG       | Boston Celtics        | 3.43104
Evan Turner      | SG       | Boston Celtics        | 3.42551
Bojan Bogdanovic | SG       | Brooklyn Nets         | 3.42551
Jeremy Lamb      | SG       | Charlotte Hornets     | 3.03436
Raymond Felton   | PG       | Dallas Mavericks      | 3.95031
Will Barton      | SF       | Denver Nuggets        | 3.53333
Emmanuel Mudiay  | PG       | Denver Nuggets        | 3.10224
Andre Drummond   | C        | Detroit Pistons       | 3.27209
Harrison Barnes  | SF       | Golden State Warriors | 3.8734
... (26 rows omitted)

In [141]:
nba.where('PLAYER', are.equal_to('Stephen Curry'))

PLAYER        | POSITION | TEAM                  | '15-'16 SALARY
Stephen Curry | PG       | Golden State Warriors | 11.3708