In [1]:
import numpy as np
L = np.random.random(100)

In [2]:
L

array([0.08273076, 0.68764139, 0.44719977, 0.36252818, 0.8085634 ,
       0.92798173, 0.3831528 , 0.89631957, 0.96745206, 0.69218953,
       0.32923396, 0.22265377, 0.98176129, 0.36856048, 0.72916419,
       0.63888662, 0.42480369, 0.62329952, 0.4321357 , 0.36046506,
       0.15738935, 0.80474137, 0.85424677, 0.8628455 , 0.30609466,
       0.25609823, 0.14877468, 0.01729889, 0.3078127 , 0.31720428,
       0.33652549, 0.43402727, 0.6825307 , 0.16681365, 0.54668906,
       0.0348594 , 0.01615363, 0.81569325, 0.22411291, 0.74782643,
       0.83945584, 0.59820065, 0.00567822, 0.88085635, 0.12476604,
       0.18073582, 0.82545406, 0.39306217, 0.24902267, 0.08098445,
       0.71804997, 0.16654317, 0.90346893, 0.52410857, 0.84250452,
       0.09617799, 0.00181545, 0.17953607, 0.31861366, 0.02209695,
       0.70160983, 0.40145679, 0.92444282, 0.20663842, 0.61828444,
       0.60127095, 0.61818133, 0.12842016, 0.72763267, 0.2389517 ,
       0.02817744, 0.17367848, 0.39290422, 0.32886055, 0.94110

In [3]:
L.reshape(20, 5)

array([[0.08273076, 0.68764139, 0.44719977, 0.36252818, 0.8085634 ],
       [0.92798173, 0.3831528 , 0.89631957, 0.96745206, 0.69218953],
       [0.32923396, 0.22265377, 0.98176129, 0.36856048, 0.72916419],
       [0.63888662, 0.42480369, 0.62329952, 0.4321357 , 0.36046506],
       [0.15738935, 0.80474137, 0.85424677, 0.8628455 , 0.30609466],
       [0.25609823, 0.14877468, 0.01729889, 0.3078127 , 0.31720428],
       [0.33652549, 0.43402727, 0.6825307 , 0.16681365, 0.54668906],
       [0.0348594 , 0.01615363, 0.81569325, 0.22411291, 0.74782643],
       [0.83945584, 0.59820065, 0.00567822, 0.88085635, 0.12476604],
       [0.18073582, 0.82545406, 0.39306217, 0.24902267, 0.08098445],
       [0.71804997, 0.16654317, 0.90346893, 0.52410857, 0.84250452],
       [0.09617799, 0.00181545, 0.17953607, 0.31861366, 0.02209695],
       [0.70160983, 0.40145679, 0.92444282, 0.20663842, 0.61828444],
       [0.60127095, 0.61818133, 0.12842016, 0.72763267, 0.2389517 ],
       [0.02817744, 0.17367848, 0.

In [4]:
X=L.reshape(20, 5)

In [5]:
X

array([[0.08273076, 0.68764139, 0.44719977, 0.36252818, 0.8085634 ],
       [0.92798173, 0.3831528 , 0.89631957, 0.96745206, 0.69218953],
       [0.32923396, 0.22265377, 0.98176129, 0.36856048, 0.72916419],
       [0.63888662, 0.42480369, 0.62329952, 0.4321357 , 0.36046506],
       [0.15738935, 0.80474137, 0.85424677, 0.8628455 , 0.30609466],
       [0.25609823, 0.14877468, 0.01729889, 0.3078127 , 0.31720428],
       [0.33652549, 0.43402727, 0.6825307 , 0.16681365, 0.54668906],
       [0.0348594 , 0.01615363, 0.81569325, 0.22411291, 0.74782643],
       [0.83945584, 0.59820065, 0.00567822, 0.88085635, 0.12476604],
       [0.18073582, 0.82545406, 0.39306217, 0.24902267, 0.08098445],
       [0.71804997, 0.16654317, 0.90346893, 0.52410857, 0.84250452],
       [0.09617799, 0.00181545, 0.17953607, 0.31861366, 0.02209695],
       [0.70160983, 0.40145679, 0.92444282, 0.20663842, 0.61828444],
       [0.60127095, 0.61818133, 0.12842016, 0.72763267, 0.2389517 ],
       [0.02817744, 0.17367848, 0.

In [6]:
sum(L)

47.573798125811194

In [7]:
np.sum(L)

47.57379812581121

In [11]:
big_array=np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

92.1 ms ± 6.41 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
944 µs ± 74.6 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [12]:
np.min(L)

0.001815452853417443

In [13]:
np.max(L)

0.9849215548608882

In [14]:
np.average(L)

0.47573798125811206

In [15]:
L

array([0.08273076, 0.68764139, 0.44719977, 0.36252818, 0.8085634 ,
       0.92798173, 0.3831528 , 0.89631957, 0.96745206, 0.69218953,
       0.32923396, 0.22265377, 0.98176129, 0.36856048, 0.72916419,
       0.63888662, 0.42480369, 0.62329952, 0.4321357 , 0.36046506,
       0.15738935, 0.80474137, 0.85424677, 0.8628455 , 0.30609466,
       0.25609823, 0.14877468, 0.01729889, 0.3078127 , 0.31720428,
       0.33652549, 0.43402727, 0.6825307 , 0.16681365, 0.54668906,
       0.0348594 , 0.01615363, 0.81569325, 0.22411291, 0.74782643,
       0.83945584, 0.59820065, 0.00567822, 0.88085635, 0.12476604,
       0.18073582, 0.82545406, 0.39306217, 0.24902267, 0.08098445,
       0.71804997, 0.16654317, 0.90346893, 0.52410857, 0.84250452,
       0.09617799, 0.00181545, 0.17953607, 0.31861366, 0.02209695,
       0.70160983, 0.40145679, 0.92444282, 0.20663842, 0.61828444,
       0.60127095, 0.61818133, 0.12842016, 0.72763267, 0.2389517 ,
       0.02817744, 0.17367848, 0.39290422, 0.32886055, 0.94110

In [18]:
X= np.arange(16).reshape(4, -1)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [19]:
np.product(X+1)


2004189184

In [20]:
np.mean(X)

7.5

In [21]:
for percent in [0, 25, 50, 75, 100]:
    print(np.percentile(big_array, q=percent))

2.04266284775656e-07
0.24989378283472136
0.49993255102475737
0.7503103683537804
0.9999975227905505


In [22]:
np.var(big_array)

0.08341059235464768

In [23]:
np.std(bit_array)

0.28875870090283406

In [24]:
x = np.random.normal(0, 1, size=1000000)

In [25]:
x

array([-1.75397665,  0.20892546, -1.09629469, ..., -1.51941904,
        0.57404508,  0.01446485])

In [26]:
np.mean(x)

-0.00045990725793377206

In [27]:
np.std(x)

1.000077107205281

In [28]:
np.min(x)

-4.646766907960408

In [29]:
np.argmin(x)

601475

In [30]:
x[601475]

-4.646766907960408

In [31]:
x = np.arange(16)

In [32]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [33]:
np.mean(x)


7.5

In [34]:
np.random.shuffle(x)

In [35]:
x

array([ 8,  6,  4, 11, 14, 15,  9, 12,  2,  3, 13,  5, 10,  1,  0,  7])

In [36]:
np.sort(x)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [37]:
x

array([ 8,  6,  4, 11, 14, 15,  9, 12,  2,  3, 13,  5, 10,  1,  0,  7])

In [38]:
x.sort()

In [39]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [40]:
np.arange(16)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [41]:
X= np.arange(16)

In [42]:
X


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [43]:
ind = [3, 5, 8]

In [44]:
X[ind]


array([3, 5, 8])

In [45]:
ind = np.array([[0, 2], [1, 3]])

In [46]:
X[ind]

array([[0, 2],
       [1, 3]])

In [47]:
ind = np.array([[10, 2], [1, 3]])

In [48]:
X[ind]

array([[10,  2],
       [ 1,  3]])

In [49]:
X = X+1


In [50]:
X

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [51]:
X[ind]

array([[11,  3],
       [ 2,  4]])

In [52]:
X=np.arange(16).reshape(4, -1)

In [53]:
col = [True, False, True, True]


In [54]:
X[1:3, col]

array([[ 4,  6,  7],
       [ 8, 10, 11]])

In [55]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [56]:
x = np.arange(16)


In [57]:
x


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [58]:
x< 3

array([ True,  True,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [59]:
x/2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5])

In [60]:
x+2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17])

In [61]:
x > 3


array([False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [62]:
x < = 3

SyntaxError: invalid syntax (1149633277.py, line 1)

In [63]:
x <= 3

array([ True,  True,  True,  True, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [64]:
x == 3

array([False, False, False,  True, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [65]:
x * 2 == 24 - 4*x

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False])

In [66]:
x


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [67]:
x <= 3

array([ True,  True,  True,  True, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [68]:
np.any(x == 0)


True

In [69]:
np.any(x != 0)

True

In [70]:
np.any(x = 100)

TypeError: any() got an unexpected keyword argument 'x'

In [71]:
np.any(x == 100)


False

In [72]:
np.all(x >=0)


True

In [73]:
np.all(x > 0)



False

In [74]:
np.sum(x % 2 == 0)

8

In [75]:
np.sum(x % 3 == 0)

6

In [76]:
x %3 == 0

array([ True, False, False,  True, False, False,  True, False, False,
        True, False, False,  True, False, False,  True])

In [77]:
x>3&x<10

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [78]:
(x>3)&(x<10)

array([False, False, False, False,  True,  True,  True,  True,  True,
        True, False, False, False, False, False, False])

In [80]:
(x>3)|(x<10)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [81]:
np.sum(~(x==0))

15

In [82]:
x[x < 5]

array([0, 1, 2, 3, 4])

In [83]:
x [ x %2 ==0]

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [85]:
x[x[:,3]%3==0, :]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [86]:
x = np.arange(16).reshape(4, 4)

In [87]:
x[x[:,3]%3==0, :]

array([[ 0,  1,  2,  3],
       [12, 13, 14, 15]])

In [88]:
import matplotlib as mpl

In [89]:
mpl.__version__

'3.8.0'