In [62]:
import numpy as np

a1 = np.array([1, 4, 3])
print(a1)

a2 = np.array([[1, 2, 3], [4, 5, 6]])
print(a2.ndim)

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(arr[0:-1])
print(arr[3:8:2])
print(arr.shape)

arr2 = np.array([[1,2],[3,4]])
arr3 = np.array([[5,6],[7,8]])
print(np.concatenate((arr2, arr3), axis=1))

print(np.sort(a1))

np.random.seed(35)

random_numbers = np.random.randint(1, 100, 10)
print(random_numbers)

a = np.array([1, 2, 3])
b = np.array([4,5,6])
result = np.dot(a, b)
print(result) 


[1 4 3]
2
[1 2 3 4 5 6 7 8]
[4 6 8]
(9,)
[[1 2 5 6]
 [3 4 7 8]]
[1 3 4]
[74 16 56 34 64 65 12 12 57 73]
32


In [63]:
import numpy as np

# Creating the array
arr1 = np.array([1, 2,3,4,5,6,7,8,9,10])
print(arr1)

array_sum = np.sum(arr1)
print(array_sum)
array_mean = np.mean(arr1)
print(array_mean)
array_std = np.std(arr1)
print(array_std)

[ 1  2  3  4  5  6  7  8  9 10]
55
5.5
2.8722813232690143
