# **NumPy Array Slicing and Array Sorting**


# 1. NumPy array slicing
NumPy array slicing is a powerful technique for extracting subsets of elements from an array. Slicing allows you to create new arrays from an existing array by specifying a range of indices.

This feature is useful for data manipulation, analysis, and processing. Here, we will explore how to perform slicing on one-dimensional, two-dimensional, and three-dimensional arrays.

**1. Slicing One-Dimensional Arrays**
In a **one-dimensional NumPy array**, slicing is performed using the syntax array[start:stop:step], where:

**start** is the index where the slice starts (inclusive).

**stop** is the index where the slice ends (exclusive).

**step** specifies the stride between elements.
    
**Example 1: Basic Slicing**

In [5]:
import numpy as np

# Creating a one-dimensional array
arr = np.array([10, 20, 30, 40, 50, 60, 70])

# Slicing the array to get elements from index 1 to 4
sliced_arr = arr[1:5]

print("Original array:", arr)
print("Sliced array:", sliced_arr)


Original array: [10 20 30 40 50 60 70]
Sliced array: [20 30 40 50]


**Explanation:**

In this example, the slicing starts at index 1 and stops before index 5, resulting in the sub-array [20, 30, 40, 50].


**Example 2: Slicing with a Step**

In [11]:
# Slicing the array to get every second element from index 0 to 6
step_slice = arr[0:7:2]

print("Sliced array with step:", step_slice)


Sliced array with step: [10 30 50 70]


**Explanation:**

The slice includes elements from index 0 to 6 with a step of 2, resulting in [10, 30, 50, 70].


**2. Slicing Two-Dimensional Arrays**
    
In two-dimensional arrays, slicing can be used to extract rows and columns. The syntax is array[start:stop, start:stop], where the first part selects rows and the second part selects columns.



**Example 1: Slicing Rows and Columns**

In [15]:
# Creating a two-dimensional array
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])

# Slicing to get a sub-matrix
sub_matrix = matrix[0:2, 1:3]

print("Original matrix:\n", matrix)
print("Sliced sub-matrix:\n", sub_matrix)


Original matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Sliced sub-matrix:
 [[2 3]
 [6 7]]


The slice selects rows from index 0 to 2 (excluding 2) and columns from index 1 to 3 (excluding 3), resulting in the sub-matrix [[2, 3], [6, 7]].


**Example 2: Selecting Entire Rows or Columns**

In [20]:
# Slicing to get the entire second row
row_slice = matrix[1, :]

# Slicing to get the entire third column
col_slice = matrix[:, 2]

print("Second row:", row_slice)
print("Third column:", col_slice)


Second row: [5 6 7 8]
Third column: [ 3  7 11]


**Explanation:**

matrix[1, :] selects the entire second row.

matrix[:, 2] selects the entire third column.



**3. Slicing Three-Dimensional Arrays**
    
Slicing three-dimensional arrays follows the syntax array.

***[start:stop, start:stop, start:stop]***
, allowing selection across multiple dimensions.

**Example: Slicing a 3D Array**

In [28]:
# Creating a three-dimensional array
cube = np.array([[[1, 2, 3], [4, 5, 6]],
                 [[7, 8, 9], [10, 11, 12]],
                 [[13, 14, 15], [16, 17, 18]]])

# Slicing to get a sub-cube
sub_cube = cube[1:, :, 1:]

print("Original 3D array:\n", cube)
print("Sliced sub-cube:\n", sub_cube)


Original 3D array:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]
Sliced sub-cube:
 [[[ 8  9]
  [11 12]]

 [[14 15]
  [17 18]]]


**Explanation:**

The slice cube[1:, :, 1:] selects from the second "layer" to the end, all rows, and columns starting from the second column, resulting in a smaller 3D array.


**Summary**
  
**One-Dimensional Slicing:** Uses simple start, stop, and step syntax to access a range of elements.

**Two-Dimensional Slicing:** Allows for row and column selection, useful for matrices.

**Three-Dimensional Slicing:** Extends the slicing logic to three dimensions, handling more complex data structures.

Understanding these slicing techniques is crucial for efficiently working with large datasets and performing data manipulation and analysis using NumPy.

# 2. Sorting OF Array

**NumPy Sorting Arrays**

NumPy is a Python library used for scientific computing, particularly for working with arrays. It provides various functions for sorting arrays, which can be useful in many applications. Sorting an array is the process of arranging its elements in a specific order.

NumPy provides several functions for sorting arrays: 

np.sort(), 

np.argsort(),

np.lexsort(), 

and  np.partition().

**1. numpy.sort() Function**

The numpy.sort() function is used to sort elements in a NumPy array. By default, it sorts the array in ascending order, but it can also sort in descending order by modifying the result after sorting. This function returns a sorted copy of the input array, leaving the original array unchanged.

**Syntax:**

***numpy.sort(a, axis=-1, kind='quicksort', order=None)***

**Explanation**
  
a: Input array to be sorted.

axis: Axis along which to sort. If not specified, the default is -1 (sorts along the last axis).

kind: Sorting algorithm to use ('quicksort', 'mergesort', 'heapsort', etc.).

order: When dealing with structured arrays, specify the field to sort by.


**Example 1:** Sorting a 1D Array in Ascending Order

In [21]:
import numpy as np

arr = np.array([3, 1, 4, 2, 5])
sorted_array = np.sort(arr)
print(sorted_array)


[1 2 3 4 5]


**Example 2:** Sorting a 2D Array by Columns

In [24]:
import numpy as np

arr = np.array([[3, 2, 4], [1, 4, 3], [2, 1, 0]])
sorted_array = np.sort(arr, axis=0)
print(sorted_array)


[[1 1 0]
 [2 2 3]
 [3 4 4]]


**Example 3:** Sorting a Structured Array Based on a Specific Field



In [33]:
import numpy as np

arr = np.array([('John', 25), ('Jane', 30), ('Bob', 20)],
               dtype=[('name', 'U10'), ('age', int)])
sorted_array = np.sort(arr, order='age')
print(sorted_array)


[('Bob', 20) ('John', 25) ('Jane', 30)]


**Example 4:** Sorting a 3D Array Along a Specific Axis



In [36]:
import numpy as np

arr = np.array([[[2, 1, 4], [4, 3, 1]], [[6, 5, 4], [8, 7, 9]]])
sorted_array = np.sort(arr, axis=0)
print(sorted_array)


[[[2 1 4]
  [4 3 1]]

 [[6 5 4]
  [8 7 9]]]


**Example 5:** Sorting a Boolean Array in Descending Order



In [43]:
import numpy as np

arr = np.array([True, False, True, False])
sorted_array = np.sort(arr)[::-1]
print(sorted_array)


[ True  True False False]


**Example 6:** Sorting Each Row of a 2D Array



In [46]:
import numpy as np

arr = np.array([[3, 2, 4], [1, 4, 3], [2, 1, 0]])
sorted_array = np.sort(arr, axis=1)
print(sorted_array)


[[2 3 4]
 [1 3 4]
 [0 1 2]]


**2. numpy.argsort() Function**
The numpy.argsort() function is used to perform an indirect sort. It returns the indices that would sort an array, which can then be used to rearrange the array elements in sorted order.




**Syntax:**


***numpy.argsort(a, axis=-1, kind='quicksort', order=None)***


**Explanatio**
  
a: Input array to be sorted.

axis: Axis along which to sort. Default is -1.

kind: Sorting algorithm to use ('quicksort', 'mergesort', 'heapsort', etc.).

order: Specifies the field to sort by for structured arrays.


**Example 1: Sorting a 1D Array and Returning Indices**

In [59]:
import numpy as np

arr = np.array([3, 1, 4, 2, 5])
sorted_indices = np.argsort(arr)
print(sorted_indices)


[1 3 0 2 4]


**Example 2: Sorting a 2D Array by a Specific Column and Returning Indices**



In [62]:
import numpy as np

arr = np.array([[3, 2], [1, 4], [2, 1]])
sorted_indices = np.argsort(arr[:, 1])
print(sorted_indices)


[2 0 1]


**Example 3: Sorting a 3D Array Along a Specific Axis and Returning Indices**

In [65]:
import numpy as np

arr = np.array([[[2, 1], [4, 3]], [[6, 5], [8, 7]]])
sorted_indices = np.argsort(arr[:, :, 0], axis=1)
print(sorted_indices)


[[0 1]
 [0 1]]


**Example 4: Sorting a Boolean Array in Descending Order and Returning Indices**



In [87]:
import numpy as np

arr = np.array([True, False, True, False])
sorted_indices = np.argsort(arr)[::-1]
print(sorted_indices)


[2 0 3 1]


**3. numpy.lexsort() Function**

The numpy.lexsort() function performs an indirect sort using a sequence of keys.

It sorts primarily by the last key, then by the second-last key, and so on.


    
**Syntax:**

***numpy.lexsort(keys, axis=-1)***


keys: Sequence of arrays to be sorted by.

axis: Axis along which to sort. Default is -1.


**Example: Sorting Using Multiple Keys**

In [89]:
import numpy as np

a = np.array([3, 1, 2])
b = np.array([2, 3, 1])
ind = np.lexsort((a, b))
print(ind)


[2 0 1]


**4. numpy.partition() Function**
    
The numpy.partition() function is used to partition an array into a specific order, but not necessarily fully sorted. 

    It rearranges the elements so that the k-th smallest element is in its sorted position, and all smaller elements are moved before it, while all larger elements are moved after it.



**Syntax:**

***numpy.partition(a, kth, axis=-1, kind='introselect', order=None)***

a: Input array.

kth: Element index to partition by.

axis: Axis along which to partition. Default is -1.

kind: Selection algorithm to use.

order: Used when dealing with structured arrays.


**Example: Partitioning an Array**

In [99]:
import numpy as np

arr = np.array([3, 1, 4, 2, 5])
partitioned_array = np.partition(arr, 2)
print(partitioned_array)


[1 2 3 4 5]


# Summary
NumPy provides powerful functions for sorting arrays:

**numpy.sort():** Sorts an array and returns a sorted copy.

**numpy.argsort():** Returns the indices that would sort an array.

**numpy.lexsort():** Sorts using multiple keys.

**numpy.partition():** Partitions an array based on a specified element.

These functions are widely used in data analysis and scientific computing, enabling efficient manipulation and organization of data.