In [1]:
import numpy as np

In [3]:
li=list(range(1,10)) # 1차원 배열 생성
print(li)

# list 를 이용해서 ndarray 생성
ar=np.array(li)
print(ar)

matrix=np.array(li).reshape((3,3)) # 3행 3열의 매트릭스로 변경. 
print(matrix)

[1, 2, 3, 4, 5, 6, 7, 8, 9]
[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [44]:
'''
matrix 형태
[[1 2 3]
 [4 5 6]
 [7 8 9]]
 '''
print(matrix)
# 인덱싱 - 데이터 1개 가져오기
data1= ar[0]
print(data1)

data2=matrix[0,0]
data3=matrix[0][0]

print(data2)
print(data3)

# 2차원 배열에서 행 하나 찾아오기
row=matrix[0][:] 
row1=matrix[0]
row2=matrix[0,:]
print(row1)
print(row)
print(row2)
print("-----------")
# 2차원 배열에서 열 하나 찾아오기
column=matrix[:][0]
col1=matrix[:,0]
print(column)
print(col1)
col2=matrix[:][0]
print(col2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
1
1
[1 2 3]
[1 2 3]
[1 2 3]
-----------
[1 2 3]
[1 4 7]
[1 2 3]


* 일반 인덱싱 한 데이터는 파이썬의 기본 데이터와 동일하게 동작한다.
* 파이썬의 scala data 는 일반적으로 immutable하다.
* scalar data는 다른 변수에 대입할 떄 값을 복사해서 대입한다. 
    * 복사한 값을 바꾼다 해도 서로 영향을 주지 않는다.
* 파이썬의 vector data 는 다른 변수에 대입할 때 참조를 복사해서 대입한다. 


In [13]:
a=10
b=a
b=20
print(a)

ax=[1,2,3]
bx=ax
bx[0]=100
print(ax)


# 예상 - 10, [100,2,3]

10
[100, 2, 3]


* row 는 scalar data 가 아니고 벡터데이터이다. 
* 벡터 데이터를 다른곳에 대입하면 참조가 복사된다.
* 복사본을 수정하면 원본도 영향을 받는다.
* scalar data - primitive, vector data - imprimitive

# 파이썬의 데이터 복제
* copy 모듈의 copy 와 deepcopy 모듈을 사용
* 얕은 복사는 한번은 복제하지만 재귀적으로 수행하지 않음. - copy
* 깊은 복사는 재귀적으로 복제를 수행 - deepcopy

In [21]:
import copy

li=[1,2,3]

c=li.copy() # 얕은 복사
c[0]=100 # 1차원 배열의 경우 원본에 영향을 주지 않는다.
print(li)

m=[[1,2,3],[4,5,6]]
z=m.copy()
z[0][1]=200
print(m) # 2차원 배열의 경우 완전히 새로 만들어지는것이 아니다. 



# deepcopy

m=[[1,2,3],[4,5,6]]
z=copy.deepcopy(m)
z[0][1]=200
print(m) # 2차원 이상의 배열을 완전 복제를 하려면 deepcopy 를 사용해야 한다. 


[1, 2, 3]
[[1, 200, 3], [4, 5, 6]]
[[1, 2, 3], [4, 5, 6]]


### 슬라이싱

In [37]:
li=[1,2,3,4,5]
c=li[0:3]
# c와 li는 앞 3개의 데이터가 동일하지만 다른 공간의 데이터
print(c)
c[0]=100 # c 의 값을 변경해도 li에 영향이 없다. 
print(li)

ar=np.array(li)
d=ar[0:3]
# ar의 참조를 복사. 
print(d)
d[0]=100 # d 의 값을 수정하면 원본에 영향을 주게 된다. 
print(ar)



[1, 2, 3]
[1, 2, 3, 4, 5]
[1 2 3]
[100   2   3   4   5]


## Fancy indexing

* 인덱싱을 할 때 list 를 이용하는것.

In [45]:
ar=np.array([1,2,3,4,5])
f=ar[[0,2]]

print(ar)
f[0]=1004
print(ar)

[1 2 3 4 5]
[1 2 3 4 5]


## boolean indexing
* and or : 데이터를 가지고 연산을 수행
    * 파이썬은 데이터가 없는 데이터 묶음, 0,None 을 False 로 간주 - Falsy
* &,| : 비트 단위로 연산을 수행

In [55]:
ar=np.array([1,2,3,4,5,6,7])

result=ar[[True,True,True,True,False,False,False]]
print(result)

br=np.array([100,20,30,40,50,60,90])
result=ar[br>=70]
print(result)

# result1=ar[(br>=70) or (br<60)]


[1 2 3 4]
[1 7]


## ndarray 의 연산

In [63]:
ar=np.array([1,2,3,4,5])
br=np.array([23,5,6,7,87])
print(ar+br)
print(ar+2)

cr=np.array(range(1,11))
print(cr)
print(ar+cr.reshape(2,5))
cr=cr.reshape((2,5))
print(ar+cr)

[24  7  9 11 92]
[3 4 5 6 7]
[ 1  2  3  4  5  6  7  8  9 10]
[[ 2  4  6  8 10]
 [ 7  9 11 13 15]]
[[ 2  4  6  8 10]
 [ 7  9 11 13 15]]


### 논리 연산

In [69]:
ar=np.array([1,2,3,4,500])
br=np.array([23,5,False,7,0])

print(ar>br)
print(np.not_equal(ar,br))
print(np.greater(ar,br))
print(np.logical_xor(ar,br))

[False False  True False  True]
[ True  True  True  True  True]
[False False  True False  True]
[False False  True False  True]


In [70]:
ar+=br
print(ar)

[ 24   7   3  11 500]


In [73]:
print(24 in ar)
print([7,4] in ar)

True
False


/var/folders/jv/jrhq9b3j1r71dg847_hrmn_m0000gn/T/ipykernel_3487/1481110758.py:2: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  print([7,4] in ar)


### 벡터화된 함수 적용

In [79]:
# 매개변수에 100을 더해서 리턴하는 함수

def vectorizing(x):
    return x+100
ar=np.array([1,2,3,4,5])
# print(vectorizing(ar))

# 배열에 벡터화 된 함수를 적용
vector_v=np.vectorize(vectorizing)
print(vector_v(ar))

print(np.vectorize(lambda i:i+100)(ar))

[101 102 103 104 105]
[101 102 103 104 105]


### Transpose

In [83]:
matrix=np.array(range(1,11)).reshape((5,2))
print(matrix)

print(matrix.transpose())
print(matrix.T)
print(np.transpose(matrix))

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
[[ 1  3  5  7  9]
 [ 2  4  6  8 10]]
[[ 1  3  5  7  9]
 [ 2  4  6  8 10]]
[[ 1  3  5  7  9]
 [ 2  4  6  8 10]]


## permutation

In [92]:
cards=np.array(range(1,49))
print(cards)
print("----cards-------")
result=np.random.permutation(cards)
print(cards)
print(result)
print('----permutation------')
print(np.random.shuffle(cards))
print(cards)
print('----shuffle------')


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]
----cards-------
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]
[13 34  4 36 12 41  7 10 33 15 26 28 21 23 25 37 42 22 24  3 46 35 19 20
 29 47  2 43 18 44 16 17 31  9 48  6  1 39 38 11 45  5  8 27 14 32 30 40]
----permutation------
None
[ 8 11 13 14  7 25 10  5 31 28 36 32 12 21 29  6 46 24  3 19 33 17 22 26
 41 18  2 20 30 38 15 42 27 45 40 35 37 48 34 44 47  4 43  1 16  9 23 39]
----shuffle------


## 기본통계함수

In [102]:
matrix=np.array(range(10,61,10))
matrix=matrix.reshape((3,2))
print(matrix)
print(matrix.sum())
print(matrix.std(ddof=1)) # 표준편차에 자요도 1 적용. 
print(np.percentile(matrix,75)) #75 퍼센트에 해당하는 값 추출

# 행단위와 열단위 합계
print(matrix.sum(axis=0)) # 열단위 합
print(matrix.sum(axis=1)) # 행단위 합
print(matrix.sum(axis=1,keepdims=True)) # 행단위 합, 모양을 행단위 합으로 추출. 

[[10 20]
 [30 40]
 [50 60]]
210
18.708286933869708
47.5
[ 90 120]
[ 30  70 110]
[[ 30]
 [ 70]
 [110]]


In [123]:
print(np.argmax(matrix))
matrix=matrix.reshape((2,3))
print(np.diff(matrix,n=2))

5
[[0]
 [0]]


### sort

In [131]:
help(np.sort)

Help on function sort in module numpy:

sort(a, axis=-1, kind=None, order=None)
    Return a sorted copy of an array.
    
    Parameters
    ----------
    a : array_like
        Array to be sorted.
    axis : int or None, optional
        Axis along which to sort. If None, the array is flattened before
        sorting. The default is -1, which sorts along the last axis.
    kind : {'quicksort', 'mergesort', 'heapsort', 'stable'}, optional
        Sorting algorithm. The default is 'quicksort'. Note that both 'stable'
        and 'mergesort' use timsort or radix sort under the covers and, in general,
        the actual implementation will vary with data type. The 'mergesort' option
        is retained for backwards compatibility.
    
        .. versionchanged:: 1.15.0.
           The 'stable' option was added.
    
    order : str or list of str, optional
        When `a` is an array with fields defined, this argument specifies
        which fields to compare first, second, etc.  A si

In [138]:
ar=np.array([20,30,10,24,11])
result=np.sort(ar) # 데이터를 정렬
print(result)
print(ar)

# 2차원 배열에서 행에서의 정렬
br=np.array([[10,60,80],[20,50,30],[15,32,29]])
result1=np.sort(br,axis=1)
print('------------------')
print(br)
print('------------------')
print(result1)

[10 11 20 24 30]
[20 30 10 24 11]
------------------
[[10 60 80]
 [20 50 30]
 [15 32 29]]
------------------
[[10 60 80]
 [20 30 50]
 [15 29 32]]


In [156]:
matrix=np.array(range(1,51))
matrix=matrix.reshape((10,5))
print(matrix)
print('----------------')
sp=np.split(matrix,[7,10])
print(sp[0])
print('----------------')
print(sp[1])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]
 [36 37 38 39 40]
 [41 42 43 44 45]
 [46 47 48 49 50]]
----------------
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]]
----------------
[[36 37 38 39 40]
 [41 42 43 44 45]
 [46 47 48 49 50]]


In [167]:
# 강사님 code
x=range(1,51)
ar=np.array(x)
matrix=ar.reshape((10,5))

print(matrix.shape)
# train=int(matrix.shape[0]*0.7)
# test=int(matrix.shape[0])
cnt=matrix.shape[0]



sp1=np.split(matrix,[int(cnt*0.7),int(cnt)])
print(sp1)
train_set=sp1[0]
test_set=sp1[1]
print(train_set)

(10, 5)
[array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]]), array([[36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]]), array([], shape=(0, 5), dtype=int64)]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]]


In [141]:
help(np.split)

Help on function split in module numpy:

split(ary, indices_or_sections, axis=0)
    Split an array into multiple sub-arrays as views into `ary`.
    
    Parameters
    ----------
    ary : ndarray
        Array to be divided into sub-arrays.
    indices_or_sections : int or 1-D array
        If `indices_or_sections` is an integer, N, the array will be divided
        into N equal arrays along `axis`.  If such a split is not possible,
        an error is raised.
    
        If `indices_or_sections` is a 1-D array of sorted integers, the entries
        indicate where along `axis` the array is split.  For example,
        ``[2, 3]`` would, for ``axis=0``, result in
    
          - ary[:2]
          - ary[2:3]
          - ary[3:]
    
        If an index exceeds the dimension of the array along `axis`,
        an empty sub-array is returned correspondingly.
    axis : int, optional
        The axis along which to split, default is 0.
    
    Returns
    -------
    sub-arrays : list 

In [168]:
matrix=np.array(range(1,61))
matrix=matrix.reshape((10,6))
print(matrix)
print('----------------')
sp=np.split(matrix,[7,10])
print(sp[0])
print('----------------')
print(sp[1])

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]
 [37 38 39 40 41 42]
 [43 44 45 46 47 48]
 [49 50 51 52 53 54]
 [55 56 57 58 59 60]]
----------------
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]
 [37 38 39 40 41 42]]
----------------
[[43 44 45 46 47 48]
 [49 50 51 52 53 54]
 [55 56 57 58 59 60]]
