<a href="https://colab.research.google.com/github/jonialon/intro-ml-python/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'last_expr_or_assign' # "all"

# NumPy Array Basics

## Array Creation — from list

In [ ]:
a = np.array([1, 2, 3, 4]) # from list

array([1, 2, 3, 4])

In [ ]:
b = np.array([(1, 2, 3, 4), (0, 0, 0, 0)]) # 2D matrix from list of tuples

array([[1, 2, 3, 4],
       [0, 0, 0, 0]])

In [ ]:
c = np.arange(10, 30, 5)

array([10, 15, 20, 25])

In [ ]:
d = np.arange(15).reshape(3, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

## Array Creation — zeros

In [ ]:
e = np.zeros(4)

array([0., 0., 0., 0.])

In [ ]:
e.shape

(4,)

In [ ]:
e.ndim # number of dimensions

1

In [ ]:
type(e)

numpy.ndarray

In [ ]:
e.dtype

dtype('float64')

## Array Creation — ones

In [ ]:
f = np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
f.shape

(2, 3)

In [ ]:
f.ndim # number of dimensions

2

In [ ]:
type(f)

numpy.ndarray

In [ ]:
f.dtype

dtype('float64')

## Array Creation — arange and linspace

In [ ]:
x = np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [ ]:
theta = np.linspace(0, np.pi, 3)

array([0.        , 1.57079633, 3.14159265])

## Array Attributes

**ndim** — number of dimensions  
**shape** — size of each dimension  
**size** — total size of the array (number of elements)  
**dtype** — data type of the array  
**itemsize** — size of each array element in bytes  
**nbytes** — total size of the array in bytes = **size** * **itemsize**  


## Array Indexing: Accessing Single Elements

In [ ]:
x1 = np.array([5, 0, 3, 3, 7, 9])

array([5, 0, 3, 3, 7, 9])

In [ ]:
x1[0]

5

In [ ]:
x1[4]

7

In [ ]:
x1[-1]

9

In [ ]:
x1[-2]

7

In [ ]:
x2 = np.array(
    [[3, 5, 2, 4],
     [7, 6, 8, 8],
     [1, 6, 7, 7]])

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [ ]:
x2[0, 0]

3

In [ ]:
x2[2, 0]

1

In [ ]:
x2[2, -1]

7

In [ ]:
x2[0, 0] = 12
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

## Array Slicing  

```
x[start : stop : step ]
```

default start — 0  
default end — len(x) - 1  
default step — 1

In [ ]:
x = np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x[:5]  # first five elements

array([0, 1, 2, 3, 4])

In [ ]:
x[5:]  # elements after index 5

array([5, 6, 7, 8, 9])

In [ ]:
x[4:7]  # middle sub-array

array([4, 5, 6])

In [ ]:
x[::2]  # every other element

array([0, 2, 4, 6, 8])

In [ ]:
x[1::2]  # every other element, starting at index 1

array([1, 3, 5, 7, 9])

In [ ]:
x[::-1]  # all elements, reversed

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [ ]:
x[5::-2]  # reversed every other from index 5

array([5, 3, 1])

## Multi-dimensional subarrays

In [ ]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [ ]:
x2[:2, :3]  # two rows, three columns

array([[12,  5,  2],
       [ 7,  6,  8]])

In [ ]:
x2[:3, ::2]  # all rows, every other column

array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

In [ ]:
x2[::-1, ::-1] # reverse subarray dimensions together

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

## Subarrays as no-copy views

In [ ]:
x2
print(x2)

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [ ]:
x2_sub = x2[:2, :2]
print(x2_sub)

[[12  5]
 [ 7  6]]


In [ ]:
x2_sub[0, 0] = 99
print(x2_sub)

[[99  5]
 [ 7  6]]


In [ ]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


## Creating copies of arrays

In [ ]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[99  5]
 [ 7  6]]


In [ ]:
x2_sub_copy[0, 0] = 42
print(x2_sub_copy)

[[42  5]
 [ 7  6]]


In [ ]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


## Reshaping of Arrays

In [ ]:
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
x = np.array([1, 2, 3])

# row vector via reshape
x.reshape((1, 3))

array([[1, 2, 3]])

In [ ]:
# row vector via newaxis
x[np.newaxis, :]

array([[1, 2, 3]])

In [ ]:
# column vector via reshape
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [ ]:
# column vector via newaxis
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

## Array Concatenation and Splitting

```
np.concatenate, np.hstack, np.vstack
np.split, np.hsplit, np.vsplit
```

In [ ]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [ ]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# concatenate along the first axis
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [ ]:
# concatenate along the second axis (zero-indexed)
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [ ]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])

# vertically stack the arrays
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [ ]:
# horizontally stack the arrays
y = np.array([[99],
              [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

# Universal Functions  

- NumPy provides an easy and flexible interface to optimized computation with arrays of data.
- The key to making NumPy fast is to use vectorized operations, generally implemented through NumPy's universal functions (ufuncs).
- Python loops are slow! (because of dynamic type checking)  
Vectorized operations are fast!

In [ ]:
import numpy as np
np.random.seed(0)

def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output

values = np.random.randint(1, 10, size=5)
compute_reciprocals(values)

array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ])

In [ ]:
big_array = np.random.randint(1, 100, size=1000000)
%timeit compute_reciprocals(big_array)

3.23 s ± 1.45 s per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [ ]:
1.0 / values

array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ])

In [ ]:
%timeit (1.0 / big_array)

1.92 ms ± 121 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


Operator | Equivalent ufunc | Description
---------|------------------|------------
+	| np.add | Addition (e.g., 1 + 1 = 2)
-	| np.subtract	| Subtraction (e.g., 3 - 2 = 1)
-	| np.negative	| Unary negation (e.g., -2)
*	| np.multiply	| Multiplication (e.g., 2 * 3 = 6)
/	| np.divide	| Division (e.g., 3 / 2 = 1.5)
// | np.floor_divide | Floor division (e.g., 3 // 2 = 1)
** | np.power | Exponentiation (e.g., 2 ** 3 = 8)
%	| np.mod | Modulus/remainder (e.g., 9 % 4 = 1)

- NumPy Absolute value  
```np.abs (or np.absolute) # also works for complex numbers```
- Trigonometric Functions  
```np.sin, np.cos, np.tan, np.arcsin, np.argcos, np.arctan```
- Exponents and logarithms  
```np.exp, np.exp2, np.power, np.log, np.log2, np.log10```

# Aggregations

In [ ]:
big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

125 ms ± 33.6 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
377 µs ± 14.2 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


Minimum, Maximum, and Sum  
```min(big_array), max(big_array), sum(big_array) # slow```  
```np.min(big_array), np.max(big_array), np.sum(big_array) # fast```  
``` big_array.min(), big_array.max(), big_array.sum() # fast ```

|Function name    |   NaN-safe version| Description                                   |
|-----------------|-------------------|-----------------------------------------------|
| `np.sum`        | `np.nansum`       | Compute sum of elements                       |
| `np.prod`       | `np.nanprod`      | Compute product of elements                   |
| `np.mean`       | `np.nanmean`      | Compute mean of elements                      |
| `np.std`        | `np.nanstd`       | Compute standard deviation                    |
| `np.var`        | `np.nanvar`       | Compute variance                              |
| `np.min`        | `np.nanmin`       | Find minimum value                            |
| `np.max`        | `np.nanmax`       | Find maximum value                            |
| `np.argmin`     | `np.nanargmin`    | Find index of minimum value                   |
| `np.argmax`     | `np.nanargmax`    | Find index of maximum value                   |
| `np.median`     | `np.nanmedian`    | Compute median of elements                    |
| `np.percentile` | `np.nanpercentile`| Compute rank-based statistics of elements     |
| `np.any`        | N/A               | Evaluate whether any elements are true        |
| `np.all`        | N/A               | Evaluate whether all elements are true        |

# Broadcasting  

- Another means of vectorizing operations
- Broadcasting is simply a set of rules for applying binary ufuncs (addition, subtraction, multiplication, etc.) on arrays of different sizes.


## Broadcasting Rules  

1. If the two arrays differ in their number of dimensions, the shape of the one with fewer dimensions is padded with ones on its leading (left) side.
2. If the shape of the two arrays does not match in any dimension, the array with shape equal to 1 in that dimension is stretched to match the other shape.
3. If in any dimension the sizes disagree and neither is equal to 1, an error is raised.

- NumPy compares the shapes of the 2 arrays element-wise. It starts with the trailing dimensions. Two dimensions are compatible when
  - they are equal, or
  - one of them is 1
- If these conditions are not met, a **ValueError: operands could not be broadcast together** exception is thrown, indicating that the arrays have incompatible shapes.
- The size of the resulting array is the maximum size along each dimension of the input arrays.

In [ ]:
M = np.ones((2, 3))
a = np.arange(3)
print(M)
print(a)
print(M + a)

[[1. 1. 1.]
 [1. 1. 1.]]
[0 1 2]
[[1. 2. 3.]
 [1. 2. 3.]]


In [ ]:
a = np.arange(3).reshape((3, 1))
b = np.arange(3)
print(a)
print(b)
print(a + b)

[[0]
 [1]
 [2]]
[0 1 2]
[[0 1 2]
 [1 2 3]
 [2 3 4]]


# Comparisons, Masks, and Boolean Logic  

- Examine and manipulate values within NumPy arrays
- Element-wise comparisons over arrays
- Extract, modify, count, or otherwise manipulate values in an array based on some criterion
  - count all values greater than a certain value
  - remove all outliers that are above some threshold

## Comparisons

| Operator    | Equivalent ufunc  | Operator   | Equivalent ufunc |
|-------------|-------------------|------------|------------------|
|`==`         |`np.equal`         |`!=`        |`np.not_equal`    |
|`<`          |`np.less`          |`<=`        |`np.less_equal`   |
|`>`          |`np.greater`       |`>=`        |`np.greater_equal`|

In [ ]:
x = np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [ ]:
x < 3  # less than

array([ True,  True, False, False, False])

In [ ]:
x > 3  # greater than

array([False, False, False,  True,  True])

In [ ]:
x <= 3  # less than or equal

array([ True,  True,  True, False, False])

In [ ]:
x >= 3  # greater than or equal

array([False, False,  True,  True,  True])

In [ ]:
x != 3  # not equal

array([ True,  True, False,  True,  True])

In [ ]:
x == 3  # equal

array([False, False,  True, False, False])

## Working with Boolean Arrays

In [ ]:
x = np.array(
    [[9, 4, 0, 3],
     [8, 6, 3, 1],
     [3, 7, 4, 0]])
x

array([[9, 4, 0, 3],
       [8, 6, 3, 1],
       [3, 7, 4, 0]])

In [ ]:
x < 6

array([[False,  True,  True,  True],
       [False, False,  True,  True],
       [ True, False,  True,  True]])

In [ ]:
# how many values less than 6?
np.count_nonzero(x < 6)

8

In [ ]:
np.sum(x < 6)

8

In [ ]:
# how many values less than 6 in each row?
np.sum(x < 6, axis=1)

array([3, 2, 3])

In [ ]:
# are there any values greater than 8?
np.any(x > 8)

True

In [ ]:
# are there any values less than zero?
np.any(x < 0)

False

In [ ]:
# are all values less than 10?
np.all(x < 10)

True

In [ ]:
# are all values equal to 6?
np.all(x == 6)

False

In [ ]:
# are all values in each row less than 8?
np.all(x < 8, axis=1)

array([False, False,  True])

# Fancy Indexing

In [ ]:
x = np.array([51, 92, 14, 71, 60, 20, 82, 86, 74, 74])

array([51, 92, 14, 71, 60, 20, 82, 86, 74, 74])

Suppose we want to access three different elements. We could do it like this:

In [ ]:
[x[3], x[7], x[2]]

[71, 86, 14]

Alternatively, we can pass a single list or array of indices to obtain the same result:

In [ ]:
ind = [3, 7, 4]
x[ind]

array([71, 86, 60])

When using arrays of indices, the shape of the result reflects the shape of the index arrays rather than the shape of the array being indexed:

In [ ]:
ind = np.array([[3, 7],
                [4, 5]])
x[ind]

array([[71, 86],
       [60, 20]])

Fancy indexing also works in multiple dimensions. Consider the following array:

In [ ]:
X = np.arange(12).reshape((3, 4))
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

Like with standard indexing, the first index refers to the row, and the second to the column:

In [ ]:
row = np.array([0, 1, 2])
col = np.array([2, 1, 3])
X[row, col]

array([ 2,  5, 11])

Notice that the first value in the result is `X[0, 2]`, the second is `X[1, 1]`, and the third is `X[2, 3]`.
The pairing of indices in fancy indexing follows all the broadcasting rules that were mentioned in Broadcasting section.
So, for example, if we combine a column vector and a row vector within the indices, we get a two-dimensional result:

In [ ]:
X[row[:, np.newaxis], col]

array([[ 2,  1,  3],
       [ 6,  5,  7],
       [10,  9, 11]])

Here, each row value is matched with each column vector, exactly as we saw in broadcasting of arithmetic operations.
For example:

In [ ]:
row[:, np.newaxis] * col

array([[0, 0, 0],
       [2, 1, 3],
       [4, 2, 6]])

It is always important to remember with fancy indexing that the return value reflects the *broadcasted shape of the indices*, rather than the shape of the array being indexed.

# Sorting Arrays

## Fast Sorting in NumPy: np.sort and np.argsort

The `np.sort` function is analogous to Python's built-in `sorted` function, and will efficiently return a sorted copy of an array:

In [ ]:
import numpy as np

x = np.array([2, 1, 4, 3, 5])
np.sort(x)

array([1, 2, 3, 4, 5])

Similarly to the `sort` method of Python lists, you can also sort an array in-place using the array `sort` method:

In [ ]:
x.sort()
print(x)

[1 2 3 4 5]


A related function is `argsort`, which instead returns the *indices* of the sorted elements:

In [ ]:
x = np.array([2, 1, 4, 3, 5])
i = np.argsort(x)
print(i)

[1 0 3 2 4]


The first element of this result gives the index of the smallest element, the second value gives the index of the second smallest, and so on.
These indices can then be used (via fancy indexing) to construct the sorted array if desired:

In [ ]:
x[i]

array([1, 2, 3, 4, 5])

You'll see an application of `argsort` later in this chapter.

### Sorting Along Rows or Columns

A useful feature of NumPy's sorting algorithms is the ability to sort along specific rows or columns of a multidimensional array using the `axis` argument. For example:

In [ ]:
rng = np.random.default_rng(seed=42)
X = rng.integers(0, 10, (4, 6))
print(X)

[[0 7 6 4 4 8]
 [0 6 2 0 5 9]
 [7 7 7 7 5 1]
 [8 4 5 3 1 9]]


In [ ]:
# sort each column of X
np.sort(X, axis=0)

array([[0, 4, 2, 0, 1, 1],
       [0, 6, 5, 3, 4, 8],
       [7, 7, 6, 4, 5, 9],
       [8, 7, 7, 7, 5, 9]])

In [ ]:
# sort each row of X
np.sort(X, axis=1)

array([[0, 4, 4, 6, 7, 8],
       [0, 0, 2, 5, 6, 9],
       [1, 5, 7, 7, 7, 7],
       [1, 3, 4, 5, 8, 9]])

Keep in mind that this treats each row or column as an independent array, and any relationships between the row or column values will be lost!

# Basic Linear Algebra

## Scalar (inner, dot) Product ```np.dot```

In [ ]:
array1 = np.array([1, 3, 5])
array2 = np.array([2, 4, 6])

# use of dot() to perform array multiplication
result = np.dot(array1, array2)

print(result)

44


## Outer Product ```np.outer```

In [ ]:
array1 = np.array([1, 3, 5])
array2 = np.array([2, 4, 6])

# outer() to perform outer multiplication
result = np.outer(array1, array2)

print(result)

[[ 2  4  6]
 [ 6 12 18]
 [10 20 30]]


## Matrix Determinant ```np.linalg.det```

In [ ]:
# define a square matrix
array1 = np.array([[1, 3],
                  [5, 7]])

# compute the determinant of array1
result = np.linalg.det(array1)


print(result)

-7.999999999999998


## Solve Linear System Ax=b ```np.linalg.solve```

In [ ]:
# define the coefficient matrix A
A = np.array([[2, 4],
             [6, 8]])

# define the constant vector b
b = np.array([5, 6])

# solve the system of linear equations Ax = b
x = np.linalg.solve(A, b)

print(x)

[-2.    2.25]


## Matrix Inverse ```np.linalg.inv```

In [ ]:
# define a 2x2 matrix
array1 = np.array([[2, 4],
                  [6, 8]])

# compute the inverse of the matrix
result = np.linalg.inv(array1)

print(result)

[[-1.    0.5 ]
 [ 0.75 -0.25]]


## Matrix Trace ```np.trace```

In [ ]:
# define a 3x3 matrix
array1 = np.array([[6, 3, 5],
                   [9, 2, 1],
                   [7, 8, 4]])

# compute the trace of the matrix
result = np.trace(array1)

print(result)

12


## Matrix Transpose

In [ ]:
# define a 3x3 matrix
array1 = np.array([[6, 3, 5],
                   [9, 2, 1],
                   [7, 8, 4]])

# compute the trace of the matrix
result = array1.T # or array1.transpose()

print(result)

[[6 9 7]
 [3 2 8]
 [5 1 4]]


## Matrix Multiplication

In [ ]:
a = np.array([[1, 2],
              [3, 4]])
b = np.array([[1, 2],
              [1, 2]])
print(a @ b) # same as np.matmul(a, b)

[[ 3  6]
 [ 7 14]]
