
# 5  Numpy functions and their Usage


### Detailed explanation

Write a short introduction about Numpy and list the chosen functions. 

- argmax
- sort
- average
- transpose
- split

The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.

In [1]:
!pip install jovian --upgrade -q

In [2]:
import jovian

<IPython.core.display.Javascript object>

In [3]:
jovian.commit(project='numpy-array-operations')

<IPython.core.display.Javascript object>

[jovian] Updating notebook "jayashreemallipudi3/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/jayashreemallipudi3/numpy-array-operations


'https://jovian.ai/jayashreemallipudi3/numpy-array-operations'

Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [4]:
import numpy as np

In [ ]:
# List of functions explained 
function1 = np.argmax
function2 = np.sort
function3 = np.average
function4 = np.transpose
function5 = np.split

## Function 1 - np.argmax 

This function returns the maximum element indices based on axis.

In [46]:
# Example 1 - working
arr1=np.random.randint(16,size=(4,4))
print(arr1)
print(np.argmax(arr1))

[[ 1  6 12 13]
 [13  5  0  4]
 [11 10  5  0]
 [ 1  9  7  6]]
3


Explanation about example
argmax returns indices of maximum element.

In [57]:
# Example 2 -working sort
prob=np.random.rand(4,4)
print(prob)
print(np.argmax(prob,axis=0))
print(np.argmax(prob,axis=1))

[[0.57753095 0.84995965 0.23614245 0.8725152 ]
 [0.29165751 0.060839   0.15813323 0.52923348]
 [0.12625635 0.07084457 0.71222193 0.11301533]
 [0.2303861  0.12119381 0.43109111 0.44414143]]
[0 0 2 0]
[3 3 2 3]


Explanation about example
argmax returns indices of maximum element in a particular axis
if specified 0->maximum indices by column,1->maximum indices by row,if not specifies returns the maximum of entire array.

In [49]:
# Example 3 - breaking (to illustrate when it breaks)
#mean

arr1 = [[5, 6, 7], 
        [8, 9, 10]]

np.argmax(arr1, axis=2)

AxisError: axis 2 is out of bounds for array of dimension 2

Explanation about example (why it breaks and how to fix it)
This example failed due to axis value it can only be 0 ,1,-1 
not 2 so changing axis value fixes the error

Some closing comments about when to use this function.
when ever need to find maximum index,could be maximum probablity of some use case

In [58]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "jayashreemallipudi3/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/jayashreemallipudi3/numpy-array-operations


'https://jovian.ai/jayashreemallipudi3/numpy-array-operations'

## Function 2 - sort

Add some explanations
to sort elements in an ordered sequence

In [ ]:
# Example 1 - working
a = np.array([[12, 15], [10, 1]])
print(np.sort(a,kind='mergesort'))

Explanation about example
np.sort returns a copy of a sorted array
using kind we can use different sorting algorithms(eg:quicksort,mergesort,heapsort)

In [59]:
# Example 2 - working
arr1 = np.sort(a, axis = 0) #along  axis 0 sorts contents along each column
print(arr1)
print(np.sort(a, axis = -1))  #along  last axis  sorts contents along each row

[[10  1]
 [12 15]]
[[12 15]
 [ 1 10]]


Explanation about example
Axis along which to sort. If None, the array is flattened before sorting. The default is -1, which sorts along the last axis

In [96]:
# Example 3 - breaking (to illustrate when it breaks)
dtype = [('name', 'S10'), ('height', float), ('age', int)]
values = [('Arthur', 1.6, 41), ('Lancelot', 1.9, 38),
          ('Galahad', 1.4, 38)]
a = np.array(values) 
np.sort(a,order=['name'])

ValueError: Cannot specify order when the array has no fields.

Explanation about example (why it breaks and how to fix it)
In the example in order to sort using order parameter we need to have fields so adding dtype in above example into np.array
will resolve this
a=np.array(values,dtype)

Some closing comments about when to use this function.

In [97]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "jayashreemallipudi3/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/jayashreemallipudi3/numpy-array-operations


'https://jovian.ai/jayashreemallipudi3/numpy-array-operations'

## Function 3 - average

Add some explanations
average function calculates weighted average along specified axis

In [101]:
# Example 1 - working
data = np.arange(1, 11)
np.average(data, weights=np.arange(10, 0, -1))

[10  9  8  7  6  5  4  3  2  1]


4.0

Explanation about example,
In the above example First pass the parameters data and its corresponding weights to find weighted average

In [106]:
# Example 2 - working
data = np.arange(8).reshape((4,2))
print(data)
np.average(data, axis=1, weights=[1./4, 3./4])

[[0 1]
 [2 3]
 [4 5]
 [6 7]]


array([0.75, 2.75, 4.75, 6.75])

Explanation about example
using axis since array and its associated weights differ

In [110]:
# Example 3 - breaking (to illustrate when it breaks)
data = np.arange(6).reshape((3,2))
print(data)
np.average(data, weights=[1./4, 3./4])

[[0 1]
 [2 3]
 [4 5]]


TypeError: Axis must be specified when shapes of a and weights differ.

Explanation about example (why it breaks and how to fix it)
In this scenario axis must be specified because with out it function will not get which sense of direction to work


Some closing comments about when to use this function.

In [111]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "jayashreemallipudi3/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/jayashreemallipudi3/numpy-array-operations


'https://jovian.ai/jayashreemallipudi3/numpy-array-operations'

## Function 4 - Transpose

Add some explanations
This function helps to return transpose of matrix(switches rows and columns of array)

In [113]:
# Example 1 - working
x=np.array([[1,2,3],[4,5,6]])
np.transpose(x)

array([[1, 4],
       [2, 5],
       [3, 6]])

Explanation about example
we got the  3x2 matrix which is transpose of 2x3 

In [116]:
# Example 2 - working
x = np.ones((1, 2, 3))
np.transpose(x, (1, 0, 2)).shape

(1, 2, 3)


(2, 1, 3)

Explanation about example
Here in  transpose function second argument is axes(tuple) which helps to permute the axes in a given order 

In [118]:
# Example 3 - breaking (to illustrate when it breaks)
x = np.ones((1, 2, 3))
np.transpose(x, (1, 0, 2,3)).shape

ValueError: axes don't match array

Explanation about example (why it breaks and how to fix it),
The second argument doesnot have right number of axes so the function doesnot get how to reshape
Here reducing axis tuple fixes the issue.

Some closing comments about when to use this function.

In [119]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "jayashreemallipudi3/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/jayashreemallipudi3/numpy-array-operations


'https://jovian.ai/jayashreemallipudi3/numpy-array-operations'

## Function 5 - Split

Splitting an array into multiple sub arrays


In [125]:
# Example 1 - working
x = np.arange(20.0)
np.split(x, 2)

[array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19.])]

Explanation about example
This function helps to split the array into 2 sub arrays 

In [128]:
# Example 2 - working
x = np.arange(8.0)
np.split(x, [3, 5, 6,10])

[array([0., 1., 2.]),
 array([3., 4.]),
 array([5.]),
 array([6., 7.]),
 array([], dtype=float64)]

Explanation about example

In This example second argument the entries indicate where along axis array can split
As we can see if the array dont have 10 element split returns empty array

In [131]:
# Example 3 - breaking (to illustrate when it breaks)
x=np.arange(7)
np.split(x,3)

ValueError: array split does not result in an equal division

Explanation about example (why it breaks and how to fix it)

Here array needs to be split into  3 equal arrays but our array size doen't match
so changing either array size or spilt size resolves the error

Some closing comments about when to use this function.

In [132]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "jayashreemallipudi3/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/jayashreemallipudi3/numpy-array-operations


'https://jovian.ai/jayashreemallipudi3/numpy-array-operations'

## Conclusion

This notebook has gone over some basic examples of how to use five NumPy functions, as well as some frequent problems that can occur when using these functions for the first time. Even if some of the functions aren't widely used in Data Analysis, they might be incredibly useful in solving specific situations.


## Reference Links
Provide links to your references and other interesting articles about Numpy arrays:
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>