# Practical_6: Numpy

---

### Exercise 1:
Create a NumPy array of integers from 1 to 10.

```python
# Exercise 1
```

---

In [1]:
import numpy as np

In [3]:
num_array=np.arange(11)
print(num_array)

[ 0  1  2  3  4  5  6  7  8  9 10]


### Exercise 2:
Create a 3x3 NumPy array filled with zeros.

```python
# Exercise 2
```

---

In [18]:
Num=np.zeros([3,3])

print(Num)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


### Exercise 3:
Create a NumPy array of 10 evenly spaced numbers between 0 and 5.

```python
# Exercise 3
```

---

In [236]:
equally_space=np.linspace(1, 5, num=10)

print(equally_space)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


[0 1 2 3 4 5 6 7 8 9]


In [24]:
help(np.arange(0,10))

Help on ndarray object:

class ndarray(builtins.object)
 |  ndarray(shape, dtype=float, buffer=None, offset=0,
 |          strides=None, order=None)
 |  
 |  An array object represents a multidimensional, homogeneous array
 |  of fixed-size items.  An associated data-type object describes the
 |  format of each element in the array (its byte-order, how many bytes it
 |  occupies in memory, whether it is an integer, a floating point number,
 |  or something else, etc.)
 |  
 |  Arrays should be constructed using `array`, `zeros` or `empty` (refer
 |  to the See Also section below).  The parameters given here refer to
 |  a low-level method (`ndarray(...)`) for instantiating an array.
 |  
 |  For more information, refer to the `numpy` module and examine the
 |  methods and attributes of an array.
 |  
 |  Parameters
 |  ----------
 |  (for the __new__ method; see Notes below)
 |  
 |  shape : tuple of ints
 |      Shape of created array.
 |  dtype : data-type, optional
 |      Any objec

### Exercise 4:
Create a 5x5 identity matrix using NumPy.

```python
# Exercise 4
```

---

In [26]:
identity=np.eye(5,5)

print(identity)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


### Exercise 5:
Create a 4x4 matrix with random values between 0 and 1.

```python
# Exercise 5
```

---

In [31]:
Mat=np.random.rand(4,4)

print(Mat)

[[0.34464869 0.28040712 0.3991308  0.27502826]
 [0.38577699 0.64131925 0.11337926 0.2519841 ]
 [0.54114296 0.61755324 0.5258112  0.26972116]
 [0.46084088 0.00927918 0.96867995 0.54772874]]


### Exercise 6:
Find the shape of a NumPy array.

```python
# Exercise 6
```

---

In [34]:
# the shape of a numpy array
a=np.array([1,2,3,45,5,6,7,8,9])

print(a)

# The shape is given us 
print(a.shape)

[ 1  2  3 45  5  6  7  8  9]
(9,)


### Exercise 7:
Reshape a 1D NumPy array of 16 elements into a 4x4 matrix.

```python
# Exercise 7
```

---

In [36]:
b=np.array([1,2,3,4,5,6,67,8,9,12,3,45,67,0,34,7])

# reshaping 

b.reshape(4,4)

array([[ 1,  2,  3,  4],
       [ 5,  6, 67,  8],
       [ 9, 12,  3, 45],
       [67,  0, 34,  7]])

### Exercise 8:
Find the data type of the elements in a NumPy array.

```python
# Exercise 8
```

---

In [238]:
b=np.array([1,2,3,4,5,6,67,8,9,12,3,45,67,0,34,7])


print(b.dtype)


int64


### Exercise 9:
Create a NumPy array of integers from 1 to 100 and find all even numbers in the array.

```python
# Exercise 9
```

---

In [42]:

# assignment 
x= np.arange(1,100)


# function for creating the even numbers
b=x[x%2==0]

print(b)

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94 96
 98]


### Exercise 10:
Generate a 6x6 matrix of random integers between 10 and 50.

```python
# Exercise 10
```

---

In [56]:
generate_matrix=np.random.randint(10,50, size=(6, 6))

#a=np.matrix(generate_matrix)
print(generate_matrix)


#print(a)

[[28 18 13 16 20 10]
 [26 45 47 26 20 29]
 [49 47 12 13 13 42]
 [42 15 17 38 15 44]
 [42 35 25 23 48 34]
 [34 15 28 47 30 43]]


In [47]:
help(np.random.randint)

Help on built-in function randint:

randint(...) method of numpy.random.mtrand.RandomState instance
    randint(low, high=None, size=None, dtype=int)
    
    Return random integers from `low` (inclusive) to `high` (exclusive).
    
    Return random integers from the "discrete uniform" distribution of
    the specified dtype in the "half-open" interval [`low`, `high`). If
    `high` is None (the default), then results are from [0, `low`).
    
    .. note::
        New code should use the ``integers`` method of a ``default_rng()``
        instance instead; please see the :ref:`random-quick-start`.
    
    Parameters
    ----------
    low : int or array-like of ints
        Lowest (signed) integers to be drawn from the distribution (unless
        ``high=None``, in which case this parameter is one above the
        *highest* such integer).
    high : int or array-like of ints, optional
        If provided, one above the largest (signed) integer to be drawn
        from the distributi

In [49]:
help(np.random.rand)

Help on built-in function rand:

rand(...) method of numpy.random.mtrand.RandomState instance
    rand(d0, d1, ..., dn)
    
    Random values in a given shape.
    
    .. note::
        This is a convenience function for users porting code from Matlab,
        and wraps `random_sample`. That function takes a
        tuple to specify the size of the output, which is consistent with
        other NumPy functions like `numpy.zeros` and `numpy.ones`.
    
    Create an array of the given shape and populate it with
    random samples from a uniform distribution
    over ``[0, 1)``.
    
    Parameters
    ----------
    d0, d1, ..., dn : int, optional
        The dimensions of the returned array, must be non-negative.
        If no argument is given a single Python float is returned.
    
    Returns
    -------
    out : ndarray, shape ``(d0, d1, ..., dn)``
        Random values.
    
    See Also
    --------
    random
    
    Examples
    --------
    >>> np.random.rand(3,2)
    arra

In [52]:
help(np.matrix)

Help on class matrix in module numpy:

class matrix(ndarray)
 |  matrix(data, dtype=None, copy=True)
 |  
 |  matrix(data, dtype=None, copy=True)
 |  
 |  .. note:: It is no longer recommended to use this class, even for linear
 |            algebra. Instead use regular arrays. The class may be removed
 |            in the future.
 |  
 |  Returns a matrix from an array-like object, or from a string of data.
 |  A matrix is a specialized 2-D array that retains its 2-D nature
 |  through operations.  It has certain special operators, such as ``*``
 |  (matrix multiplication) and ``**`` (matrix power).
 |  
 |  Parameters
 |  ----------
 |  data : array_like or string
 |     If `data` is a string, it is interpreted as a matrix with commas
 |     or spaces separating columns, and semicolons separating rows.
 |  dtype : data-type
 |     Data-type of the output matrix.
 |  copy : bool
 |     If `data` is already an `ndarray`, then this flag determines
 |     whether the data is copied (the 

### Exercise 11:
Slice a 2D NumPy array to extract a submatrix.

```python
# Exercise 11
```

---

In [65]:
sli=np.array([[12,4,5],[2,7,8]])

print(sli)
print("-----------------")
sli[:1]

[[12  4  5]
 [ 2  7  8]]
-----------------


array([[12,  4,  5]])

In [66]:
sli[1:]

array([[2, 7, 8]])

### Exercise 12:
Calculate the sum of all elements in a NumPy array.

```python
# Exercise 12
```

---

In [78]:
sum_s=np.random.randint(1,10, size=(6, 6))

print(sum_s)
np.sum(sum_s)

[[6 7 3 5 1 9]
 [4 2 6 5 3 7]
 [5 3 4 3 5 1]
 [6 2 5 3 4 5]
 [1 1 7 4 8 4]
 [7 7 7 8 2 7]]


167

### Exercise 13:
Calculate the mean, median, and standard deviation of a NumPy array.

```python
# Exercise 13
```

---

In [81]:
me_midi_st_s=np.random.randint(1,10, size=(3, 3))

# the mean
print(np.mean(me_midi_st_s))
print("---------------")

print(np.median(me_midi_st_s))
print("---------------")
print(np.std(me_midi_st_s))
print("---------------")

4.666666666666667
---------------
4.0
---------------
2.0548046676563256
---------------


### Exercise 14:
Find the maximum and minimum values in a NumPy array.

```python
# Exercise 14
```

---

In [94]:
n_arr=np.random.randint(1,50, size=(4,4))


print(np.max(n_arr))
print("=============")
print(np.min(n_arr))

49
4


In [93]:
n_arr

array([[40, 30,  7, 42],
       [21, 39, 48,  4],
       [13, 35, 28, 35],
       [43, 20, 42, 35]])

### Exercise 15:
Create a NumPy array of 20 random integers and find the index of the maximum value.

```python
# Exercise 15
```

---

In [98]:
Crea_r=np.random.randint(1,20, size=(20))
print(Crea_r)

[ 6  6 13  9 18  6 17 17  7  8  1 15 13 18  5 16  9 17 19  5]


In [239]:
#finding the minimum value of the row
print(np.min(Crea_r, axis=0))




1


### Exercise 16:
Create a NumPy array and reverse its elements.

```python
# Exercise 16
```

---

In [135]:
Crea_r=np.random.randint(1,20, size=(20))

print(Crea_r)
print("=======================")
print(np.flip(Crea_r, axis=None))

[ 1 10 15 11 14 15  3  3  7  8  9 13 18  5 18  6 15 10  6  1]
[ 1  6 10 15  6 18  5 18 13  9  8  7  3  3 15 14 11 15 10  1]


### Exercise 17:
Create a 3x3 matrix and multiply it element-wise by another 3x3 matrix.

```python
# Exercise 17
```

---

In [110]:
Tre=np.random.randint(1,10, size=(3,3))
bre=np.random.randint(10,20, size=(3,3))
print(Tre)
print(bre)
print(Tre*bre)

[[4 8 5]
 [3 1 4]
 [9 3 8]]
[[15 16 15]
 [18 18 19]
 [10 14 10]]
[[ 60 128  75]
 [ 54  18  76]
 [ 90  42  80]]


### Exercise 18:
Create a diagonal matrix from a given 1D array.

```python
# Exercise 18
```

---

In [127]:
Dia=np.random.randint(10,20, size=(4))

print(Dia)

#help(np.eye)
np.eye(3, k=1)

[14 11 15 12]


array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

### Exercise 19:
Perform matrix multiplication on two 2D NumPy arrays.

```python
# Exercise 19
```

---

In [131]:
#help(np.matrix)

In [136]:
help(np.multiply)

Help on ufunc:

multiply = <ufunc 'multiply'>
    multiply(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Multiply arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        Input arrays to be multiplied.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        El

### Exercise 20:
Flatten a 2D NumPy array into a 1D array.

```python
# Exercise 20
```

---

In [137]:
help(np.identity)

Help on function identity in module numpy:

identity(n, dtype=None)
    Return the identity array.
    
    The identity array is a square array with ones on
    the main diagonal.
    
    Parameters
    ----------
    n : int
        Number of rows (and columns) in `n` x `n` output.
    dtype : data-type, optional
        Data-type of the output.  Defaults to ``float``.
    
    Returns
    -------
    out : ndarray
        `n` x `n` array with its main diagonal set to one,
        and all other elements 0.
    
    Examples
    --------
    >>> np.identity(3)
    array([[1.,  0.,  0.],
           [0.,  1.,  0.],
           [0.,  0.,  1.]])



In [244]:
y=np.random.randint(1,10, size=(2,2))

print(y)
#print(np.flatiter(y))
#help(np.flip)

np.flatnonzero(y)
y.flatten()

[[3 4]
 [8 2]]


array([3, 4, 8, 2])

### Exercise 21:
Stack two NumPy arrays vertically.

```python
# Exercise 21
```

---

In [146]:
# The arrays are 

x=np.random.randint(1,20, size=(2,1))

y=np.random.randint(1,20, size=(2,1))


print(x)
print("==============")
print(y)
print("==============")
print(np.vstack((x,y)))

[[ 7]
 [17]]
[[13]
 [11]]
[[ 7]
 [17]
 [13]
 [11]]


In [144]:
x

array([[11],
       [11]])

### Exercise 22:
Stack two NumPy arrays horizontally.

```python
# Exercise 22
```

---

In [147]:
#stacking arrays horizontally
a=np.random.randint(1,20, size=(2,1))

b=np.random.randint(1,20, size=(2,1))


print(a)
print("==============")
print(b)
print("==============")
print(np.hstack((a,b)))

[[10]
 [ 1]]
[[ 8]
 [11]]
[[10  8]
 [ 1 11]]


### Exercise 23:
Split a NumPy array into multiple sub-arrays.

```python
# Exercise 23
```

---

In [158]:
x = np.arange(9.0)

print(x)
print("=======================")

print(np.split(x, 3))

[0. 1. 2. 3. 4. 5. 6. 7. 8.]
[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7., 8.])]


In [155]:
help(np.split)

Help on function split in module numpy:

split(ary, indices_or_sections, axis=0)
    Split an array into multiple sub-arrays as views into `ary`.
    
    Parameters
    ----------
    ary : ndarray
        Array to be divided into sub-arrays.
    indices_or_sections : int or 1-D array
        If `indices_or_sections` is an integer, N, the array will be divided
        into N equal arrays along `axis`.  If such a split is not possible,
        an error is raised.
    
        If `indices_or_sections` is a 1-D array of sorted integers, the entries
        indicate where along `axis` the array is split.  For example,
        ``[2, 3]`` would, for ``axis=0``, result in
    
          - ary[:2]
          - ary[2:3]
          - ary[3:]
    
        If an index exceeds the dimension of the array along `axis`,
        an empty sub-array is returned correspondingly.
    axis : int, optional
        The axis along which to split, default is 0.
    
    Returns
    -------
    sub-arrays : list 

In [148]:
#help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}, optional
        Specify the memory layout of the array. If object is not an array, the
        newly c

### Exercise 24:
Generate a random NumPy array and round each element to two decimal places.

```python
# Exercise 24
```

---

In [161]:
ran=np.random.rand(2,10)
print(ran)

print(np.round(ran))


[[0.09160235 0.51247479 0.8952165  0.68795196 0.49114406 0.82816733
  0.0855914  0.1807121  0.62700046 0.22834301]
 [0.74932756 0.72255535 0.39621911 0.871173   0.12195454 0.03484848
  0.42524393 0.85145717 0.96406324 0.70783879]]
[[0. 1. 1. 1. 0. 1. 0. 0. 1. 0.]
 [1. 1. 0. 1. 0. 0. 0. 1. 1. 1.]]


### Exercise 25:
Find the unique elements of a NumPy array.

```python
# Exercise 25
```

---

In [166]:
# finding unique 
ran_1=np.random.randint(2,10, size=(4,4))

print(ran_1)

np.unique(ran_1)

[[4 8 6 2]
 [6 8 6 7]
 [3 3 9 8]
 [2 8 9 9]]


array([2, 3, 4, 6, 7, 8, 9])

In [165]:
help(np.unique)

Help on function unique in module numpy:

unique(ar, return_index=False, return_inverse=False, return_counts=False, axis=None)
    Find the unique elements of an array.
    
    Returns the sorted unique elements of an array. There are three optional
    outputs in addition to the unique elements:
    
    * the indices of the input array that give the unique values
    * the indices of the unique array that reconstruct the input array
    * the number of times each unique value comes up in the input array
    
    Parameters
    ----------
    ar : array_like
        Input array. Unless `axis` is specified, this will be flattened if it
        is not already 1-D.
    return_index : bool, optional
        If True, also return the indices of `ar` (along the specified axis,
        if provided, or in the flattened array) that result in the unique array.
    return_inverse : bool, optional
        If True, also return the indices of the unique array (for the specified
        axis, if pro

### Exercise 26:
Replace all elements in a NumPy array that are less than a specific value with that value.

```python
# Exercise 26
```

---

In [168]:
ran_2=np.random.randint(2,10, size=(4,4))

print(ran_2)

#the condition
np.


[[3 7 5 5]
 [2 2 8 6]
 [5 4 5 6]
 [9 5 6 6]]


### Exercise 27:
Find the cumulative sum of the elements in a NumPy array.

```python
# Exercise 27
```

---

In [172]:
sum_2=np.random.randint(2,10, size=(4,4))

print(sum_2)

print(np.cumsum(sum_2))


[[6 4 5 7]
 [4 7 4 4]
 [8 7 2 8]
 [5 3 8 6]]
[ 6 10 15 22 26 33 37 41 49 56 58 66 71 74 82 88]


### Exercise 28:
Create a NumPy array and find the number of non-zero elements in it.

```python
# Exercise 28
```

---

In [175]:
ran_non_zero=np.random.randint(2,10, size=(4,4))


a=print(np.nonzero(ran_non_zero))

# using the function count non zero
np.count_nonzero(ran_non_zero)

(array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3]), array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3]))


16

### Exercise 29:
Create a NumPy array of random integers and sort it in ascending order.

```python
# Exercise 29
```

---

In [179]:
ass_order=np.random.randint(1,5, size=(3,3))
print(ass_order)

print(np.sort(ass_order, axis=None))

[[1 4 4]
 [2 2 1]
 [4 4 1]]
[1 1 1 2 2 4 4 4 4]


In [177]:
help(np.sort)

Help on function sort in module numpy:

sort(a, axis=-1, kind=None, order=None)
    Return a sorted copy of an array.
    
    Parameters
    ----------
    a : array_like
        Array to be sorted.
    axis : int or None, optional
        Axis along which to sort. If None, the array is flattened before
        sorting. The default is -1, which sorts along the last axis.
    kind : {'quicksort', 'mergesort', 'heapsort', 'stable'}, optional
        Sorting algorithm. The default is 'quicksort'. Note that both 'stable'
        and 'mergesort' use timsort or radix sort under the covers and, in general,
        the actual implementation will vary with data type. The 'mergesort' option
        is retained for backwards compatibility.
    
        .. versionchanged:: 1.15.0.
           The 'stable' option was added.
    
    order : str or list of str, optional
        When `a` is an array with fields defined, this argument specifies
        which fields to compare first, second, etc.  A si

### Exercise 30:
Find the row-wise and column-wise sum of a 3x3 matrix.

```python
# Exercise 30
```

---

In [181]:
b=np.random.randint(1,15, size=(3,3))
b1=np.random.randint(16,25, size=(3,3))

print(b)
print(b1)
print(b+b1)
print(np.add(b,b1))

[[12 12  1]
 [ 6 13 14]
 [ 8  3 12]]
[[22 20 20]
 [20 19 22]
 [16 21 19]]
[[34 32 21]
 [26 32 36]
 [24 24 31]]
[[34 32 21]
 [26 32 36]
 [24 24 31]]


### Exercise 31:
Generate a 2D NumPy array with random values and normalize it (scale the values between 0 and 1).

```python
# Exercise 31
```

---

In [246]:

#np.linalg.norm(matrix, 'fro')


### Exercise 32:
Create two NumPy arrays and find the dot product.

```python
# Exercise 32
```

---

In [202]:
b4=np.random.randint(2,9, size=(2,1))

b5=np.random.randint(2,9, size=(2,1))


z=np.hstack(b4)
y=np.hstack(b5)

print(np.dot(z,y))
print("========================")
#print(np.dot(b4,b5))

v = np.array([9,10])
w = np.array([11, 12])
print(v)

print(np.dot(v,w))

44
[ 9 10]
219


### Exercise 33:
Find the trace of a square NumPy matrix.

```python
# Exercise 33
```

---

In [205]:
a = np.matrix('1 2; 3 4')
#b = np.matrix('1 2; 3 4')
np.trace(a)

5

### Exercise 34:
Create a 2D array and swap two rows.

```python
# Exercise 34
```

---

In [211]:
array_2_dimensional=np.array([[1,3], [6,7]])

f=array_2_dimensional[:,[1,0]] = array_2_dimensional[:,[0,1]]
print(array_2_dimensional)
print(f)

[[3 1]
 [7 6]]
[[1 3]
 [6 7]]


In [216]:
temp = np.copy(array_2_dimensional[0])
array_2_dimensional[0] = array_2_dimensional[1]
array_2_dimensional[1] = temp

print(temp)


[7 6]


### Exercise 35:
Create a 1D NumPy array and convert it into a column vector.

```python
# Exercise 35
```

---

In [218]:
a=np.array([1,2,3,4,6])

print(a)
print(np.vstack(a))

[1 2 3 4 6]
[[1]
 [2]
 [3]
 [4]
 [6]]


### Exercise 36:
Find the determinant of a 3x3 matrix.

```python
# Exercise 36
```

---

In [221]:
matr=np.matrix('1 2 3; 5 6 8; 9 12 45')

det = np.linalg.det(matr)

print(det)

-114.00000000000003


### Exercise 37:
Find the eigenvalues and eigenvectors of a 2x2 matrix.

```python
# Exercise 37
```

---

In [248]:
b7=np.matrix('2 4; 5 6')
print(b7)



print(np.linalg.eig(b7))
print(np.linalg.eigh(b7))

[[2 4]
 [5 6]]
(array([-0.89897949,  8.89897949]), matrix([[-0.8097086 , -0.50158596],
        [ 0.58683216, -0.86510781]]))
(array([-1.38516481,  9.38516481]), matrix([[-0.82806723,  0.56062881],
        [ 0.56062881,  0.82806723]]))


### Exercise 38:
Solve a system of linear equations using NumPy.

```python
# Exercise 38
```

---

{−x1+3x2=7,3x1+2x2=1,

In [228]:
A=np.matrix('-1 3;3 2')
print(A)

#the array part is 

B = np.array([7, 1], dtype=np.dtype(float))

print(B)
# solve the system of the linear equation using le function
print("===========================")
print(np.linalg.solve(A,B))

[[-1  3]
 [ 3  2]]
[7. 1.]
[-1.  2.]


### Exercise 39:
Add Gaussian noise to a NumPy array.

```python
# Exercise 39
```

---

### Exercise 40:
Create a 4x4 matrix and extract the diagonal elements.

```python
# Exercise 40
```

---

In [233]:
Diag_gonal=np.random.randint(1,10, size=(4,4))



print(Diag_gonal)
print("===================================")

print(np.diag(Diag_gonal))
#help(np.diag)

[[1 2 9 1]
 [7 1 9 5]
 [3 2 1 2]
 [8 4 8 1]]
[1 1 1 1]


### Exercise 41:
Generate a NumPy array of 100 random values and clip the values to a range between 10 and 50.

```python
# Exercise 41
```

---

### Exercise 42:
Create a 2D NumPy array and replace all negative values with zero.

```python
# Exercise 42
```

---

### Exercise 43:
Find the inner and outer products of two NumPy arrays.

```python
# Exercise 43
```

---

### Exercise 44:
Calculate the pairwise distances between points in a NumPy array.

```python
# Exercise 44
```

---

### Exercise 45:
Create a structured NumPy array with fields for `name`, `age`, and `height`.

```python
# Exercise 45
```

---

### Exercise 46:
Create a 5x5 matrix of random integers and count the occurrences of each unique value.

```python
# Exercise 46
```

---

### Exercise 47:
Generate a random 3x3 NumPy array and subtract the mean of each row from the corresponding row.

```python
# Exercise 47
```

---

### Exercise 48:
Create a NumPy array of random integers and check if any of the values are greater than 50.

```python
# Exercise 48
```

---

### Exercise 49:
Calculate the moving average of a 1D NumPy array.

```python
# Exercise 49
```

---

### Exercise 50:
Find the Pearson correlation coefficient between two NumPy arrays.

```python
# Exercise 50
```

---

### Exercise 51:
Convert a NumPy array of radians to degrees.

```python
# Exercise 51
```

---

### Exercise 52:
Create a random NumPy array and compute its variance and standard deviation.

```python
# Exercise 52
```

---

### Exercise 53:
Create a 2D NumPy array and find the indices of the maximum values along each axis.

```python
# Exercise 53
```

---

### Exercise 54:
Compute the inverse of a 2x2 NumPy matrix.

```python
# Exercise 54
```

---

### Exercise 55:
Create a NumPy array of 10 random values and standardize it (mean 0, variance 1).

```python
# Exercise 55
```

---

### Exercise 56:
Perform element-wise addition and subtraction on two NumPy arrays.

```python
# Exercise 56
```

---

### Exercise 57:
Create a NumPy array of random values and find the maximum element's index.

```python
# Exercise 57
```

---

### Exercise 58:
Create a 3x3 NumPy array and rotate it by 90 degrees.

```python
# Exercise 58
```

---

### Exercise 59:
Compute the Frobenius norm of a matrix.

```python
# Exercise 59
```

---

### Exercise 60:
Create a 3D NumPy array and slice out a subarray.

```python
# Exercise 60
```

---