In [1]:
import numpy as np 

In [3]:
arr = np.array([1, 2, 3, 4, 5])


In [4]:
arr

array([1, 2, 3, 4, 5])

In [5]:
print(np.__version__)

2.0.1


In [4]:
list(range(0,11))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [8]:
# diffrence btwn list and array (list is heterogenous while array is homogenous) 

In [4]:
a2 = [x for x in range (0,11)]

In [11]:
a2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [12]:
a3 = [str(r) for r in a2]
a3

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10']

In [16]:
a4 = [str(s**2) for s in a2]

In [17]:
a4

['0', '1', '4', '9', '16', '25', '36', '49', '64', '81', '100']

In [18]:
import array

In [20]:
help (array)

Help on built-in module array:

NAME
    array

DESCRIPTION
    This module defines an object type which can efficiently represent
    an array of basic values: characters, integers, floating point
    numbers.  Arrays are sequence types and behave very much like lists,
    except that the type of objects stored in them is constrained.

CLASSES
    builtins.object
        array

    ArrayType = class array(builtins.object)
     |  array(typecode [, initializer]) -> array
     |
     |  Return a new array whose items are restricted by typecode, and
     |  initialized from the optional initializer value, which must be a list,
     |  string or iterable over elements of the appropriate type.
     |
     |  Arrays represent basic values and behave very much like lists, except
     |  the type of objects stored in them is constrained. The type is specified
     |  at object creation time by using a type code, which is a single character.
     |  The following type codes are defined:
     |

In [21]:
arr = array.array('i',a2)
arr

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [22]:
np.array(a2)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
np.array([s+3 for s in range(0,11)])

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [25]:
np.array([3,4,5,6,7],dtype = 'float')

array([3., 4., 5., 6., 7.])

In [26]:
np.array([3,4,5,6,7],dtype = str)

array(['3', '4', '5', '6', '7'], dtype='<U1')

In [28]:
a5 = [[1,2,3],[4,5,6]]
a5

[[1, 2, 3], [4, 5, 6]]

In [29]:
a6 = [[[1,2,3],[4,5,6],[7,8,9]]]
a6

[[[1, 2, 3], [4, 5, 6], [7, 8, 9]]]

In [40]:
arr = np.array([[1, 2, 3], [4, 5, 6],[7,8,9]])


In [41]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
a7 = [range(i,i+3,1+2) for i in [1,3]]

In [7]:
a7


[range(1, 4, 3), range(3, 6, 3)]

In [8]:
c = np.array(a7)
c

array([[1],
       [3]])

In [33]:
a7 = [x for x in[range(i,i+3) for i in [1,4,7,10]]]

In [34]:
c = np.array(a7)
c.ndim



2

In [77]:
np.array(a7)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [78]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [79]:
np.zeros((3,4),dtype = int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [80]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [81]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [82]:
np.ones((3,4),dtype = int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [84]:
np.ones((10,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [98]:
a = np.ones((10,10),dtype = int)

In [99]:
a

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [100]:
a.ndim

2

In [104]:
a[2:1]

array([], shape=(0, 10), dtype=int64)

In [105]:
a[1:8]

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [102]:
a[2:1:2]

array([], shape=(0, 10), dtype=int64)

In [106]:
a[1:9,1:9]=0

In [107]:
a

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [108]:
a[2:8,2:8]=1
a

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [111]:
a[3:7,3:7] = 0
a

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 1, 0, 0, 0, 0, 1, 0, 1],
       [1, 0, 1, 0, 0, 0, 0, 1, 0, 1],
       [1, 0, 1, 0, 0, 0, 0, 1, 0, 1],
       [1, 0, 1, 0, 0, 0, 0, 1, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [112]:
a[4:6,4:6] = 1

In [113]:
a

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 1, 0, 0, 0, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 0, 0, 0, 1, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [117]:
b = np.ones((3,3))
b[0:4,0:4] = 3.14
b

array([[3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14]])

In [118]:
# indentity matrix

In [8]:
import numpy as np

In [9]:
t = np.eye(4)

In [10]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [126]:
np.t?

Object `np.t` not found.


In [127]:
# python list
'''list comphresion
array module (import lib array)
numpy array:
zeros,ones,full,eye,arange,reshape,indexing'''

'list comphresion\narray module (import lib array)\nnumpy array:\nzeros,ones,full,eye,arange,reshape,indexing'

In [16]:
a = np.ones((6,6))*64

In [17]:
a

array([[64., 64., 64., 64., 64., 64.],
       [64., 64., 64., 64., 64., 64.],
       [64., 64., 64., 64., 64., 64.],
       [64., 64., 64., 64., 64., 64.],
       [64., 64., 64., 64., 64., 64.],
       [64., 64., 64., 64., 64., 64.]])

In [18]:
b = np.full?

Signature:
np.full(
    shape,
    fill_value,
    dtype=None,
    order='C',
    *,
    device=None,
    like=None,
)
Docstring:
Return a new array of given shape and type, filled with `fill_value`.

Parameters
----------
shape : int or sequence of ints
    Shape of the new array, e.g., ``(2, 3)`` or ``2``.
fill_value : scalar or array_like
    Fill value.
dtype : data-type, optional
    The desired data-type for the array  The default, None, means
     ``np.array(fill_value).dtype``.
order : {'C', 'F'}, optional
    Whether to store multidimensional data in C- or Fortran-contiguous
    (row- or column-wise) order in memory.
device : str, optional
    The device on which to place the created array. Default: None.
    For Array-API interoperability only, so must be ``"cpu"`` if passed.

    .. versionadded:: 2.0.0
like : array_like, optional
    Reference object to allow the creation of arrays which are not
    NumPy arrays. If an array-like passed in as ``like`` supports
    the ``__a

In [20]:
np.full((6,6),(64))

array([[64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64]])

In [21]:
# Linsapce - Linearly spaced elements


In [26]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [25]:
np.linspace?

Signature:      
np.linspace(
    start,
    stop,
    num=50,
    endpoint=True,
    retstep=False,
    dtype=None,
    axis=0,
    *,
    device=None,
)
Call signature:  np.linspace(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function linspace at 0x000002477E434220>
File:            c:\users\rudra\appdata\local\programs\python\python312\lib\site-packages\numpy\_core\function_base.py
Docstring:      
Return evenly spaced numbers over a specified interval.

Returns `num` evenly spaced samples, calculated over the
interval [`start`, `stop`].

The endpoint of the interval can optionally be excluded.

.. versionchanged:: 1.16.0
    Non-scalar `start` and `stop` are now supported.

.. versionchanged:: 1.20.0
    Values are rounded towards ``-inf`` instead of ``0`` when an
    integer ``dtype`` is specified. The old behavior can
    still be obtained with ``np.linspace(start, stop, num).astype(int)``

Parameters
----------
start : array_like
    The starting

In [27]:
np.linspace(15,20,20)

array([15.        , 15.26315789, 15.52631579, 15.78947368, 16.05263158,
       16.31578947, 16.57894737, 16.84210526, 17.10526316, 17.36842105,
       17.63157895, 17.89473684, 18.15789474, 18.42105263, 18.68421053,
       18.94736842, 19.21052632, 19.47368421, 19.73684211, 20.        ])

In [28]:
np.random?

Type:        module
String form: <module 'numpy.random' from 'C:\\Users\\Rudra\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\numpy\\random\\__init__.py'>
File:        c:\users\rudra\appdata\local\programs\python\python312\lib\site-packages\numpy\random\__init__.py
Docstring:  
Random Number Generation

Use ``default_rng()`` to create a `Generator` and call its methods.

=============== =========================================================
Generator
--------------- ---------------------------------------------------------
Generator       Class implementing all of the random number distributions
default_rng     Default constructor for ``Generator``
=============== =========================================================

============================================= ===
BitGenerator Streams that work with Generator
--------------------------------------------- ---
MT19937
PCG64
PCG64DXSM
Philox
SFC64
============================================= ===

============

In [30]:
np.random.random(3)

array([0.56312354, 0.61451156, 0.0587485 ])

In [31]:
np.random.random((3,3))

array([[0.76748283, 0.56258218, 0.32446374],
       [0.31402283, 0.77153375, 0.51369991],
       [0.58987271, 0.65944564, 0.15653876]])

In [32]:
np.random.normal?

Signature: np.random.normal(loc=0.0, scale=1.0, size=None)
Docstring:
normal(loc=0.0, scale=1.0, size=None)

Draw random samples from a normal (Gaussian) distribution.

The probability density function of the normal distribution, first
derived by De Moivre and 200 years later by both Gauss and Laplace
independently [2]_, is often called the bell curve because of
its characteristic shape (see the example below).

The normal distributions occurs often in nature.  For example, it
describes the commonly occurring distribution of samples influenced
by a large number of tiny, random disturbances, each with its own
unique distribution [2]_.

.. note::
    New code should use the `~numpy.random.Generator.normal`
    method of a `~numpy.random.Generator` instance instead;
    please see the :ref:`random-quick-start`.

Parameters
----------
loc : float or array_like of floats
    Mean ("centre") of the distribution.
scale : float or array_like of floats
    Standard deviation (spread or "width")

In [33]:
#values wiht mean zero and with std 1
np.random.normal(0,2,10)


array([ 0.20481413,  1.84489601, -2.06484006, -0.36867965, -3.54840892,
       -4.54481026,  4.29625094,  2.43857539, -5.37547324,  1.22771497])

In [34]:
np.random.normal(0,1,(3,3))

array([[ 1.26256123,  2.17072852, -1.63235704],
       [ 0.20418912, -0.40862395,  2.88864123],
       [-0.13692283,  0.14990795, -0.56310898]])

In [37]:
np.random.seed(11)
np.random.random(2)

array([0.18026969, 0.01947524])

In [38]:
np.random.randint?


Signature: np.random.randint(low, high=None, size=None, dtype=<class 'int'>)
Docstring:
randint(low, high=None, size=None, dtype=int)

Return random integers from `low` (inclusive) to `high` (exclusive).

Return random integers from the "discrete uniform" distribution of
the specified dtype in the "half-open" interval [`low`, `high`). If
`high` is None (the default), then results are from [0, `low`).

.. note::
    New code should use the `~numpy.random.Generator.integers`
    method of a `~numpy.random.Generator` instance instead;
    please see the :ref:`random-quick-start`.

Parameters
----------
low : int or array-like of ints
    Lowest (signed) integers to be drawn from the distribution (unless
    ``high=None``, in which case this parameter is one above the
    *highest* such integer).
high : int or array-like of ints, optional
    If provided, one above the largest (signed) integer to be drawn
    from the distribution (see above for behavior if ``high=None``).
    If array-lik

In [39]:
np.random.randint(50,100,30)

array([67, 63, 62, 83, 57, 68, 74, 95, 78, 98, 82, 95, 94, 54, 84, 62, 51,
       60, 87, 89, 70, 67, 77, 74, 67, 53, 56, 93, 50, 65], dtype=int32)

In [40]:
np.random.randn?

Signature: np.random.randn(*args)
Docstring:
randn(d0, d1, ..., dn)

Return a sample (or samples) from the "standard normal" distribution.

.. note::
    This is a convenience function for users porting code from Matlab,
    and wraps `standard_normal`. That function takes a
    tuple to specify the size of the output, which is consistent with
    other NumPy functions like `numpy.zeros` and `numpy.ones`.

.. note::
    New code should use the
    `~numpy.random.Generator.standard_normal`
    method of a `~numpy.random.Generator` instance instead;
    please see the :ref:`random-quick-start`.

If positive int_like arguments are provided, `randn` generates an array
of shape ``(d0, d1, ..., dn)``, filled
with random floats sampled from a univariate "normal" (Gaussian)
distribution of mean 0 and variance 1. A single float randomly sampled
from the distribution is returned if no argument is provided.

Parameters
----------
d0, d1, ..., dn : int, optional
    The dimensions of the returned 

In [42]:
np.random.randn()

1.055372883024652

In [43]:
# operation on numpy

In [48]:

arre = np.random.randint(0,100,20)
arre

array([31,  4, 28, 13, 57, 65, 90, 85, 20, 17, 81, 62,  4, 74, 39, 35, 21,
       67, 35, 81], dtype=int32)

In [49]:
# ndim is used to check the number of dimension
# ndim.size number of elements in an array 


In [50]:
arre.ndim

1

In [51]:
arre.size

20

In [52]:
arre.shape

(20,)

In [53]:
arre.dtype

dtype('int32')

# array indexing

In [54]:
arr1 = np.random.randint(0,40,10)
arr1

array([ 6,  1, 39, 36,  8,  5, 37, 27, 29, 21], dtype=int32)

In [55]:
arr1[0]

np.int32(6)

In [56]:
arr1[-1]

np.int32(21)

In [57]:
arr1[0:4]

array([ 6,  1, 39, 36], dtype=int32)

# numpy assgniment 1

In [3]:
import numpy as np

In [4]:
arr = np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
arr = np.ones(10)
arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
arr = np.arange(10,51)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [7]:
arr = np.arange(10,51)
arr[0:50:2]

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [8]:
np.array(range(10,51,2))

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [9]:
np.array(range(0,9)).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [10]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
np.random.random(2)

array([0.85746565, 0.76797416])

In [12]:
np.random.randn(25)

array([ 0.21408593,  0.83792783,  0.71683799, -1.25939415, -1.6799457 ,
        0.93439541,  0.33221835,  0.83110497, -0.44887604,  0.4932262 ,
       -1.8157151 , -0.56675672, -1.29541462,  0.59058394, -0.94437171,
        2.39531085,  1.42373177,  0.14462693, -0.68382612, -0.56000426,
        0.15702569,  0.87091468, -0.21596464,  0.29786943, -0.5061153 ])

In [17]:
np.linspace(0,1,100)

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [37]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [19]:
arr=np.array(range(1,26)).reshape(5,5)

In [20]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [21]:
arr[2:5,1:5]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [22]:
arr[3,4]

np.int64(20)

In [23]:
arr[0:3,1].reshape(3,1)

array([[ 2],
       [ 7],
       [12]])

In [24]:
arr[4]

array([21, 22, 23, 24, 25])

In [25]:
arr[3:5]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [26]:
np.sum(arr)

np.int64(325)

In [27]:
np.sum(arr,axis=0)

array([55, 60, 65, 70, 75])

In [28]:
np.max(arr,axis=1)

array([ 5, 10, 15, 20, 25])

In [29]:
np.min(arr,axis=1)

array([ 1,  6, 11, 16, 21])

In [30]:
np.std(arr,axis=1)

array([1.41421356, 1.41421356, 1.41421356, 1.41421356, 1.41421356])

In [31]:
np.var(arr,axis=1)

array([2., 2., 2., 2., 2.])

In [43]:
array=np.full((6,6),np.nan)

In [44]:
array

array([[nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan]])

In [47]:
array[1:-1,1:-1]=1

In [48]:
array

array([[nan, nan, nan, nan, nan, nan],
       [nan,  1.,  1.,  1.,  1., nan],
       [nan,  1.,  1.,  1.,  1., nan],
       [nan,  1.,  1.,  1.,  1., nan],
       [nan,  1.,  1.,  1.,  1., nan],
       [nan, nan, nan, nan, nan, nan]])

# numpy assignment 2

In [6]:
import numpy as np

In [58]:
a = np.array([1,2,3])

In [59]:
a

array([1, 2, 3])

In [11]:
b = np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
c = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
c

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [12]:
b.ndim


2

In [63]:
c.dtype

dtype('int64')

In [65]:
a.shape

(3,)

In [66]:
b.shape

(2, 3)

In [67]:
c.shape

(1, 3, 3)

In [68]:
a.ndim

1

In [69]:
b.ndim

2

In [70]:
c.ndim

3

In [71]:
np.ones((12))

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [76]:
np.zeros((12))

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [85]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [38]:
Maths = np.random.randint(30,100,20)

In [39]:
Maths

array([70, 61, 70, 96, 87, 72, 89, 96, 86, 84, 76, 63, 88, 44, 35, 56, 52,
       38, 95, 68], dtype=int32)

In [15]:
Maths.sort?

Docstring:
a.sort(axis=-1, kind=None, order=None)

Sort an array in-place. Refer to `numpy.sort` for full documentation.

Parameters
----------
axis : int, optional
    Axis along which to sort. Default is -1, which means sort along the
    last axis.
kind : {'quicksort', 'mergesort', 'heapsort', 'stable'}, optional
    Sorting algorithm. The default is 'quicksort'. Note that both 'stable'
    and 'mergesort' use timsort under the covers and, in general, the
    actual implementation will vary with datatype. The 'mergesort' option
    is retained for backwards compatibility.

    .. versionchanged:: 1.15.0
       The 'stable' option was added.

order : str or list of str, optional
    When `a` is an array with fields defined, this argument specifies
    which fields to compare first, second, etc.  A single field can
    be specified as a string, and not all fields need be specified,
    but unspecified fields will still be used, in the order in which
    they come up in the dtype, to b

In [40]:
Maths.sort()
Maths


array([35, 38, 44, 52, 56, 61, 63, 68, 70, 70, 72, 76, 84, 86, 87, 88, 89,
       95, 96, 96], dtype=int32)

In [41]:
des = np.sort(Maths)[::-1]
des

array([96, 96, 95, 89, 88, 87, 86, 84, 76, 72, 70, 70, 68, 63, 61, 56, 52,
       44, 38, 35], dtype=int32)

In [44]:
import copy

In [45]:
import numpy as np

In [46]:
dcv = copy.deepcopy(des)
dcv

array([96, 96, 95, 89, 88, 87, 86, 84, 76, 72, 70, 70, 68, 63, 61, 56, 52,
       44, 38, 35], dtype=int32)

In [50]:
im = np.eye((5),dtype=int)
im

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [51]:
im.flatten()

array([1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1])

In [62]:
err = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])


In [63]:
nrr =  np.array([10, 11, 12])


In [64]:
err = np.vstack((err, nrr))
err

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [66]:
np.vsplit(err,2)

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12]])]

In [69]:
np.hsplit(err,3)

[array([[ 1],
        [ 4],
        [ 7],
        [10]]),
 array([[ 2],
        [ 5],
        [ 8],
        [11]]),
 array([[ 3],
        [ 6],
        [ 9],
        [12]])]

In [71]:
im = np.eye((4),dtype = int)
im

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [73]:
x = im + 4
x

array([[5, 4, 4, 4],
       [4, 5, 4, 4],
       [4, 4, 5, 4],
       [4, 4, 4, 5]])

In [74]:
arr = np.array([2.345, -1.789, 5.678, -3.123])


In [77]:
cv = np.ceil(arr)
fv = np.floor(arr)
rv = np.round(arr, decimals=2)
cv


array([ 3., -1.,  6., -3.])

In [78]:
fv

array([ 2., -2.,  5., -4.])

In [79]:
rv

array([ 2.35, -1.79,  5.68, -3.12])

In [81]:
matrix = np.random.rand(5, 5)


In [82]:
mv = np.min(matrix, axis=0)
mav = np.max(matrix, axis=0)
var = np.var(matrix, axis=0)
sd = np.std(matrix, axis=0)


In [83]:
mv

array([0.04088684, 0.12635146, 0.00994717, 0.04386958, 0.04814226])

In [84]:
mav

array([0.60324803, 0.81538552, 0.91958828, 0.76773082, 0.96482668])

In [85]:
var

array([0.03529414, 0.06719317, 0.11209929, 0.07723279, 0.10954851])

In [86]:
sd

array([0.18786733, 0.25921645, 0.33481233, 0.27790787, 0.33098113])

In [93]:
vector = np.zeros((10),dtype = int)

In [94]:
vector[5] = 200
vector

array([  0,   0,   0,   0,   0, 200,   0,   0,   0,   0])

In [97]:
seq = np.arange(100, 151)
print(seq)

[100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150]


In [98]:
rev = seq[::-1]
rev

array([150, 149, 148, 147, 146, 145, 144, 143, 142, 141, 140, 139, 138,
       137, 136, 135, 134, 133, 132, 131, 130, 129, 128, 127, 126, 125,
       124, 123, 122, 121, 120, 119, 118, 117, 116, 115, 114, 113, 112,
       111, 110, 109, 108, 107, 106, 105, 104, 103, 102, 101, 100])

In [99]:
a = np.arange(0,25)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [100]:
ab = a.reshape(5,5)
ab

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [101]:
l = [1,0,2,0,0,4,0,8]

In [104]:
l[0]

1

In [105]:
l[2]

2

In [106]:
l[5]

4

In [108]:
l[7]

8

In [109]:
tw = np.ones((10,10),dtype = int)
tw

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [111]:
tw[1:9,1:9]=0

In [112]:
tw

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [128]:
tt = np.ones((8,8),dtype = int)
tt

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])

In [133]:
tt[1::2, ::2] = 0
tt[::2, 1::2] = 0

In [134]:
tt

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

In [138]:
x1 = np.random.randint(1,10, size=(3,3))
x2 = np.random.randint(1,10, size=(3,3))                             

In [139]:
add = x1+x2

In [140]:
add

array([[ 9, 12,  7],
       [ 7, 12,  6],
       [ 9,  8,  8]], dtype=int32)

In [141]:
sub = x2-x1
sub

array([[ 5, -6, -1],
       [-3, -2, -4],
       [ 5,  4, -2]], dtype=int32)

In [142]:
mul = np.dot(x1,x2)
mul

array([[60, 75, 27],
       [84, 80, 37],
       [53, 46, 23]], dtype=int32)

# after assginment

In [35]:
c = [2,3,4,5,6,7]
c[2:6:2]

[4, 6]

In [36]:
c[::2]

[2, 4, 6]

In [38]:
import random

In [3]:
a2 = np.random.randint(0,18,(4,4))

In [4]:
a2

array([[16,  8, 12, 15],
       [13, 11,  6,  9],
       [11, 10,  8, 16],
       [15, 17,  1, 12]], dtype=int32)

In [5]:
a2[0,1]

np.int32(8)

In [6]:
a2[0,1:4]

array([ 8, 12, 15], dtype=int32)

In [7]:
a2[0:3,1]

array([ 8, 11, 10], dtype=int32)

In [8]:
a2[0:3,1:3]

array([[ 8, 12],
       [11,  6],
       [10,  8]], dtype=int32)

In [9]:
a2[::,::-2]

array([[15,  8],
       [ 9, 11],
       [16, 10],
       [12, 17]], dtype=int32)

In [10]:
import numpy as np


In [11]:
a2

array([[16,  8, 12, 15],
       [13, 11,  6,  9],
       [11, 10,  8, 16],
       [15, 17,  1, 12]], dtype=int32)

# shallow copy and deep copy 

In [35]:
a3 = a2[2:,2:]
a3

array([[ 8, 16],
       [ 1, 12]], dtype=int32)

In [36]:
a3[1,1]=19

In [37]:
a3

array([[ 8, 16],
       [ 1, 19]], dtype=int32)

In [38]:
a2

array([[16,  8, 12, 15],
       [13, 11,  6,  9],
       [11, 10,  8, 16],
       [15, 17,  1, 19]], dtype=int32)

In [41]:
a2[3,3]=20
a2

array([[16,  8, 12, 15],
       [13, 11,  6,  9],
       [11, 10,  8, 16],
       [15, 17,  1, 20]], dtype=int32)

In [42]:
a3

array([[ 8, 16],
       [ 1, 20]], dtype=int32)

In [46]:
a2[:2,:2]

array([[16,  8],
       [13, 11]], dtype=int32)

In [49]:
ad = a2[:2,:2].copy()

In [50]:
ad

array([[16,  8],
       [13, 11]], dtype=int32)

In [54]:
ad[1,1]

np.int32(11)

In [55]:
a2[1,1]=8989

In [56]:
ad

array([[16,  8],
       [13, 11]], dtype=int32)

In [57]:
a2

array([[  16,    8,   12,   15],
       [  13, 8989,    6,    9],
       [  11,   10,    8,   16],
       [  15,   17,    1,   20]], dtype=int32)

In [62]:
arr = np.array([1,2,3])

In [64]:
arr.reshape(3,1).copy()

array([[1],
       [2],
       [3]])

In [69]:
err = np.array([1,2,3,4])
err

array([1, 2, 3, 4])

In [68]:
td = err.reshape(2,2)
td

array([[1, 2],
       [3, 4]])

In [81]:
yu = od.ravel()



In [82]:
yu.ndim

1

In [86]:
od.ravel?

Docstring:
a.ravel([order])

Return a flattened array.

Refer to `numpy.ravel` for full documentation.

See Also
--------
numpy.ravel : equivalent function

ndarray.flat : a flat iterator on the array.
Type:      builtin_function_or_method

In [90]:
od.flatten()

array([1, 2, 3, 4])

In [91]:
od[:,np.newaxis]

array([[[1, 2, 3, 4]]])

# concatenation , joining of two arrays

In [93]:
np.concatenate?

Call signature:  np.concatenate(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <built-in function concatenate>
Docstring:      
concatenate(
    (a1, a2, ...), 
    axis=0, 
    out=None, 
    dtype=None, 
    casting="same_kind"
)

Join a sequence of arrays along an existing axis.

Parameters
----------
a1, a2, ... : sequence of array_like
    The arrays must have the same shape, except in the dimension
    corresponding to `axis` (the first, by default).
axis : int, optional
    The axis along which the arrays will be joined.  If axis is None,
    arrays are flattened before use.  Default is 0.
out : ndarray, optional
    If provided, the destination to place the result. The shape must be
    correct, matching that of what concatenate would have returned if no
    out argument were specified.
dtype : str or dtype
    If provided, the destination array will have this dtype. Cannot be
    provided together with `out`.

    .. versionadded:: 1.20.0

casting 

In [94]:
od

array([[1, 2, 3, 4]])

In [95]:
a2

array([[  16,    8,   12,   15],
       [  13, 8989,    6,    9],
       [  11,   10,    8,   16],
       [  15,   17,    1,   20]], dtype=int32)

In [96]:
a3

array([[ 8, 16],
       [ 1, 20]], dtype=int32)

In [106]:
np.concatenate([a3,a3]) 

array([[ 8, 16],
       [ 1, 20],
       [ 8, 16],
       [ 1, 20]], dtype=int32)

In [107]:
np.concatenate([a3,a3],axis = 1) #axis is used to specify the row/coloumn

array([[ 8, 16,  8, 16],
       [ 1, 20,  1, 20]], dtype=int32)

In [105]:
op = np.array([1,1,1,1])
op

array([1, 1, 1, 1])

In [2]:
import numpy as np

In [3]:
np.vstack?

Signature:       np.vstack(tup, *, dtype=None, casting='same_kind')
Call signature:  np.vstack(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function vstack at 0x000002F84C5A22A0>
File:            c:\users\rudra\appdata\local\programs\python\python312\lib\site-packages\numpy\_core\shape_base.py
Docstring:      
Stack arrays in sequence vertically (row wise).

This is equivalent to concatenation along the first axis after 1-D arrays
of shape `(N,)` have been reshaped to `(1,N)`. Rebuilds arrays divided by
`vsplit`.

This function makes most sense for arrays with up to 3 dimensions. For
instance, for pixel-data with a height (first axis), width (second axis),
and r/g/b channels (third axis). The functions `concatenate`, `stack` and
`block` provide more general stacking and concatenation operations.

Parameters
----------
tup : sequence of ndarrays
    The arrays must have the same shape along all but the first axis.
    1-D arrays must have the same length.

In [9]:
x = np.array([1,2,3])

In [10]:
y=np.array([[4,5,6],[7,8,9]])

In [11]:
np.vstack([x,y])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
np.hstack((x,[4]))

array([1, 2, 3, 4])

In [13]:
ar=np.array(range(1,5)).reshape(2,2)

In [14]:
np.hstack((y,ar))

array([[4, 5, 6, 1, 2],
       [7, 8, 9, 3, 4]])

In [15]:
np.split?

Signature:       np.split(ary, indices_or_sections, axis=0)
Call signature:  np.split(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function split at 0x000002F84C6EB880>
File:            c:\users\rudra\appdata\local\programs\python\python312\lib\site-packages\numpy\lib\_shape_base_impl.py
Docstring:      
Split an array into multiple sub-arrays as views into `ary`.

Parameters
----------
ary : ndarray
    Array to be divided into sub-arrays.
indices_or_sections : int or 1-D array
    If `indices_or_sections` is an integer, N, the array will be divided
    into N equal arrays along `axis`.  If such a split is not possible,
    an error is raised.

    If `indices_or_sections` is a 1-D array of sorted integers, the entries
    indicate where along `axis` the array is split.  For example,
    ``[2, 3]`` would, for ``axis=0``, result in

    - ary[:2]
    - ary[2:3]
    - ary[3:]

    If an index exceeds the dimension of the array along `axis`,
    an empty s

In [16]:
np.vsplit?

Signature:       np.vsplit(ary, indices_or_sections)
Call signature:  np.vsplit(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function vsplit at 0x000002F84C6EBA60>
File:            c:\users\rudra\appdata\local\programs\python\python312\lib\site-packages\numpy\lib\_shape_base_impl.py
Docstring:      
Split an array into multiple sub-arrays vertically (row-wise).

Please refer to the ``split`` documentation.  ``vsplit`` is equivalent
to ``split`` with `axis=0` (default), the array is always split along the
first axis regardless of the array dimension.

See Also
--------
split : Split an array into multiple sub-arrays of equal size.

Examples
--------
>>> x = np.arange(16.0).reshape(4, 4)
>>> x
array([[ 0.,   1.,   2.,   3.],
       [ 4.,   5.,   6.,   7.],
       [ 8.,   9.,  10.,  11.],
       [12.,  13.,  14.,  15.]])
>>> np.vsplit(x, 2)
[array([[0., 1., 2., 3.],
        [4., 5., 6., 7.]]),
 array([[ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]])]
>>

In [17]:
np.hsplit?

Signature:       np.hsplit(ary, indices_or_sections)
Call signature:  np.hsplit(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function hsplit at 0x000002F84C6EB9C0>
File:            c:\users\rudra\appdata\local\programs\python\python312\lib\site-packages\numpy\lib\_shape_base_impl.py
Docstring:      
Split an array into multiple sub-arrays horizontally (column-wise).

Please refer to the `split` documentation.  `hsplit` is equivalent
to `split` with ``axis=1``, the array is always split along the second
axis except for 1-D arrays, where it is split at ``axis=0``.

See Also
--------
split : Split an array into multiple sub-arrays of equal size.

Examples
--------
>>> x = np.arange(16.0).reshape(4, 4)
>>> x
array([[ 0.,   1.,   2.,   3.],
       [ 4.,   5.,   6.,   7.],
       [ 8.,   9.,  10.,  11.],
       [12.,  13.,  14.,  15.]])
>>> np.hsplit(x, 2)
[array([[  0.,   1.],
       [  4.,   5.],
       [  8.,   9.],
       [12.,  13.]]),
 array([[  2.,   3.

In [18]:
a=np.array(range(1,6))

In [19]:
np.split(a,5) # (a,5,axis) axis=1 verticalyy split axis=0 horizontaly split


[array([1]), array([2]), array([3]), array([4]), array([5])]

In [20]:
np.split(a,6) #not working because


ValueError: array split does not result in an equal division

In [21]:
np.split(a,[2,4]) # :2 3:4 5:


[array([1, 2]), array([3, 4]), array([5])]

In [23]:
np.vsplit(ar,[2,3])


[array([[1, 2],
        [3, 4]]),
 array([], shape=(0, 2), dtype=int64),
 array([], shape=(0, 2), dtype=int64)]

In [24]:
np.hsplit(ar,[2,3])


[array([[1, 2],
        [3, 4]]),
 array([], shape=(2, 0), dtype=int64),
 array([], shape=(2, 0), dtype=int64)]

In [25]:
np.split(ar,5,axis=1)


ValueError: array split does not result in an equal division

In [ ]:
#universel function = sum mean standard devition sin cos


In [28]:
np.sum(ar,axis=0)


array([4, 6])

In [29]:
np.sum(ar,axis=1)


array([3, 7])

In [30]:
np.min(ar)


np.int64(1)

In [31]:
np.min(ar)


np.int64(1)

In [32]:
np.max(ar)


np.int64(4)

In [33]:
np.argmin(a) # dimention of min num.


np.int64(0)

In [34]:
i=-4


In [35]:
np.absolute(i)


np.int64(4)

In [36]:
np.abs(i)


np.int64(4)

In [37]:
#np.std() np.var()
#np.prod()  # factorial