In [ ]:
# # 주피터노트북 셀 스타일 조절
# from IPython.core.display import display, HTML
# # display(HTML("<style>.container { font-weight: bold !important; }</style>"))
# display(HTML("<style>.container { width: 100% !important; }</style>"))

# # 경고메시지 숨기기
# import warning
# warnings.filterwarnings(action='ignore')

## Numpy 개요
```Numeric + Python = Numpy
수학 및 과학 연산을 위한 파이썬 패키지
배열이나 행렬 계산에 용이한 메서드를 제공
한글로 넘파이로 주로 통칭, 넘피/늄파이라고 부르기도 함
관련 사이트 : http://www.numpy.org
일반 List에 비해 빠르고, 메모리 효율적

반복문 없이 데이터 배열에 대한 처리를 지원함
선형대수와 관련된 다양한 기능을 제공함
Reference Site
cs231 : http://cs231n.github.io/python-numpy-tutorial/#numpy
https://docs.scipy.org/doc/numpy-dev/user/quickstart.html
데이터사이언스스쿨(파이썬버전) - https://goo.gl/3hsjbS
설치 및 임포트
넘파이는 외부 라이브러리이므로 설치 필요.(아나콘다는 사전 설치됨)
pip install numpy
```

In [2]:
import numpy as np
np.__version__

'1.26.4'

## 넘파이 배열 이해하기

## ndim(dimention, rank)
몇 차원인지 반환

In [5]:
a = np.array(0)
a, a.ndim, type(a)
#ndim은 차원을 의미하는 것, 값이 1개라 스칼라인 0으로 표기

(array(0), 0, numpy.ndarray)

In [6]:
a = np.array([2,4,6])
a, a.ndim, type(a)
# ndim은 차원을 의미하는 것, 값이 3개라 벡터인 1로 표기

(array([2, 4, 6]), 1, numpy.ndarray)

In [7]:
a = [[1,2,3],[4,5,6]]
a

[[1, 2, 3], [4, 5, 6]]

In [8]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a, a.ndim, type(a)

(array([[1, 2, 3],
        [4, 5, 6]]),
 2,
 numpy.ndarray)

In [9]:
a = np.array([[[1, 2, 3], [4, 5, 6]],[[1, 2, 3], [4, 5, 6]]])
a, a.ndim, type(a)

(array([[[1, 2, 3],
         [4, 5, 6]],
 
        [[1, 2, 3],
         [4, 5, 6]]]),
 3,
 numpy.ndarray)

In [10]:
a.shape

(2, 2, 3)

In [11]:
a.shape?

Type:        tuple
String form: (2, 2, 3)
Length:      3
Docstring:  
Built-in immutable sequence.

If no argument is given, the constructor returns an empty tuple.
If iterable is specified the tuple is initialized from iterable's items.

If the argument is a tuple, the return value is the same object.

In [ ]:
2행3열이 2개가 있다는 뜻

## shape
행렬의 차원으로, 몇행 몇열인지 반환

In [14]:
a = np.array(3)
a,a.shape # 행렬이 아니라서 아무것도 안나옴

(array(3), ())

In [15]:
a = np.array([1,3,5,7,9])
a,a.shape

(array([1, 3, 5, 7, 9]), (5,))

In [16]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a, a.shape

(array([[1, 2, 3],
        [4, 5, 6]]),
 (2, 3))

In [17]:
a = np.array([[[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]], [[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]])
a, a.shape # 2개의 3행 4열

(array([[[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],
 
        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]]]),
 (2, 3, 4))

In [18]:
a.ndim

3

## 넘파이 배열
* 리스트를 넘파이 배열로 생성 np.array(리스트)
* 
관련 속성 : ndim 차원 반환 int , size 전체 길이 반환 int, shape 구조 반환 tuple

In [19]:
# 1차원 리스트 객체(이터러블)
myList = [10, 56, 77, 23, 44]
print(myList, type(myList), len(myList))

[10, 56, 77, 23, 44] <class 'list'> 5


In [20]:
myArr = np.array(myList)
print(myArr, type(myArr), len(myArr))
print(f'차원={myArr.ndim}, 구조={myArr.shape}, size={myArr.size}, 길이={len(myArr)}')

[10 56 77 23 44] <class 'numpy.ndarray'> 5
차원=1, 구조=(5,), size=5, 길이=5


In [21]:
# 2차원 리스트 객체(이터러블)
myList2 = [[1,2,3 ],[10,20,30],[100,200,300]]
myList2, len(myList2)

([[1, 2, 3], [10, 20, 30], [100, 200, 300]], 3)

In [22]:
myArr2 = np.array(myList2)
print(myArr2, type(myArr2), len(myArr2))
print(f'차원= {myArr2.ndim}, 구조 = {myArr2.shape}, size = {myArr2.size}, 길이={len(myArr2)}' )

[[  1   2   3]
 [ 10  20  30]
 [100 200 300]] <class 'numpy.ndarray'> 3
차원= 2, 구조 = (3, 3), size = 9, 길이=3


In [ ]:
size = 요소의 개수
길이 = 행의 갯수

In [23]:
# 2차원 리스트에서 각 행의 수가 다를 경우?
myList21 = [ [1,2,3,4],[10,20,30,40,50],[100,200,]]
print(myList21, type(myList21), len(myList21))

[[1, 2, 3, 4], [10, 20, 30, 40, 50], [100, 200]] <class 'list'> 3


In [24]:
# 길이가 달라 에러 리턴
myArr21 = np.array(myList21)
print(myArr21, type(myArr21), len(myArr21))
print(f'차원= {myArr21.ndim}, 구조 = {myArr21.shape}, size = {myArr21.size}')

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

In [ ]:
broadcasting은 행렬 연산에만 적용됨, array를 만들때는 적용이 안됨(만들 땐 잘 만들어야 함, 연산만 구조가 달라도 가능)

## 넘파이 배열과 리스트와의 차이점
- 배열간의 연산 가능 "브로드캐스팅", 요소별 연산(element-wise)
- 넘파이 메서드 사용 가능 : 평균, 상관계수, 분산, 표준편차 등
- 리스트는 자료형 혼합 가능, 넘파이배열은 하나의 자료형만 가능

In [26]:
# 리스트의 산술연산자 +, * 
listA = [10, 30, 50]
listB = [1, 2, 3]
print(listA + listB) # 리스트의 + 연산자는 조인역할
print(listA + 2) # 불가

[10, 30, 50, 1, 2, 3]


TypeError: can only concatenate list (not "int") to list

In [27]:
print(listA * 2) # 해당 리스트의 반복
print(listA * listB) # 불가

[10, 30, 50, 10, 30, 50]


TypeError: can't multiply sequence by non-int of type 'list'

In [28]:
# 넘파이의 산술연산
arrA = np.array([1, 2, 3])
print(arrA + 2)
print(arrA * 2)

[3 4 5]
[2 4 6]


In [29]:
arrB = np.array([4, 5, 6])
print(arrA + arrB)
print(arrA * arrB)
print(arrA / arrB)
print(arrA // arrB) # 몫
print(arrA % arrB) # 나머지

[5 7 9]
[ 4 10 18]
[0.25 0.4  0.5 ]
[0 0 0]
[1 2 3]


## dtype
```

https://numpy.org/doc/stable/reference/arrays.dtypes.html
데이터 U유형은 각 유니코드 문자를 32비트 정수(예: 4바이트)로 저장합니다. (유니코드 스트링 dtype 인수로 지정할 자료형은 다음 표에 보인것과 같은 “dtype 접두사”로 시작하는 문자열이고 이 글자 뒤에 오는 숫자는 바이트 수 혹은 글자 수를 의미한다.
예를 들어 f8은 8바이트(64비트) 부동소수점 실수를 뜻하고 U4 는 4글자 유니코드 문자열을 . 숫자를 생략하면 운영체제에 따라 알맞은 크기를 지정한다.
```뜻한다

In [30]:
# 자료형 테스트
myList_c = ['안녕', 100, 3.14, True, False] # 리스트는 혼합된 형 그대로 유지
print(myList_c)

['안녕', 100, 3.14, True, False]


In [35]:
myArr_c = np.array(myList_c) # 넘파이배열은 '문자열'로 통일 자동형변환 바이트 단위라서 문자열이 제일큼, 문자열로 통일
print(myArr_c, type(myArr_c), myArr_c.dtype) #문자열 없으면 소수점으로 통일됨
#유니코드 32로 표기됨
#외우지 말라고 하심..ㅎ

['안녕' '100' '3.14' 'True' 'False'] <class 'numpy.ndarray'> <U32


In [33]:
# 정수와 실수가 혼합된 넘파이 배열
myArr_d = np.array([100, 3.14, 23.5, 0])
print(myArr_d, type(myArr_d), myArr_d.dtype) # 정수와 실수 혼합시, 더 큰 실수형으로 통일 자동형변환

[100.     3.14  23.5    0.  ] <class 'numpy.ndarray'> float64


## Inf와 NaN
넘파이에서는 무한대를 표현하기 위한 np.inf(infinity)와 정의할 수 없는 숫자를 나타내는 np.nan(not a number)을 사용할 수 있다.   
다음 예와 같이 1을 0으로 나누려고 하거나 0에 대한 로그 값을 계산하면 무한대인 np.inf이 나온다.   
0을 0으로 나누려고 시도하면 np.nan이 나온다.

In [36]:
np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])

C:\Users\ChoiMinsoo\AppData\Local\Temp\ipykernel_20092\2068585620.py:1: RuntimeWarning: divide by zero encountered in divide
  np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])
C:\Users\ChoiMinsoo\AppData\Local\Temp\ipykernel_20092\2068585620.py:1: RuntimeWarning: invalid value encountered in divide
  np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])


array([  0.,  inf, -inf,  nan])

In [37]:
np.log(0) # 로그

C:\Users\ChoiMinsoo\AppData\Local\Temp\ipykernel_20092\2933082444.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(0)


-inf

In [38]:
np.exp(-np.inf) #지수

0.0

## 기술 통계

In [39]:
x = np.array([18,   5,  10,  23,  19,  -8,  10,   0,   0,   5,   2,  15,   8,
              2,   5,   4,  15,  -1,   4,  -7, -24,   7,   9,  -6,  23, -13])

In [44]:
#평균
x.mean() 43분 두개 차이 설명..!

SyntaxError: invalid syntax (2979147689.py, line 2)

In [43]:
#평균
np.mean(x)

4.8076923076923075

In [42]:
# 분산
np.var(x)

115.23224852071006

In [45]:
# 표준 편차
np.std(x) 

10.734628476137871

In [46]:
#최대 
np.max(x)

23

In [47]:
#최소
np.min(x)

-24

In [49]:
#중앙값
np.median(x)

5.0

## 사분위수
```
사분위수(quartile)는 데이터를 가장 작은 수부터 가장 큰 수까지 크기가 커지는 순서대로 정렬하였을 때 1/4, 2/4, 3/4 위치에 있는 수를 말한다.
각각 1사분위수, 2사분위수, 3사분위수라고 한다.
1/4의 위치란 전체 데이터의 수가 만약 100개이면 25번째 순서, 즉 하위 25%를 말한다. 따라서 2사분위수는 중앙값과 같다.

때로는 위치를 1/100 단위로 나눈 백분위수(percentile)을 사용하기도 한다. 1사분위수는 25% 백분위수와 같다.
```

In [ ]:
박스플롯

In [50]:
# 최소값
np.percentile(x, 0) #데이터를 놓고 0에 대한 위치를 알려줘

-24.0

In [51]:
np.percentile(x, 25) # 1사분위수

0.0

In [52]:
np.percentile(x, 50) #2사분위수(중앙값)

5.0

In [53]:
np.percentile(x, 75) #3사분위수

10.0

In [54]:
np.percentile(x, 100) #최대값

23.0

## 넘파이 함수로 배열 만들기
```
np.ones(n) , np.ones((x, y))
np.zeros(n) , np.zeros((x, y))
np.empty(n) , np.empty((x, y))
np.aranges(start, end step)

reshape(x, y) # 차원 확대
flatten(x, y) # 차원 축소
```

In [56]:
# 1로 메모리 초기화, 넘파이 함수로 배열을 만들때에는 디폴트가 실수형
print(np.ones(10), np.ones(10).dtype)  # 10개의 요소를 1로 채워줘 (default가 실수로 채워짐)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] float64


In [57]:
print(np.ones((2,4)), np.ones((2,4)).dtype)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]] float64


In [58]:
np.ones?

Signature: np.ones(shape, dtype=None, order='C', *, like=None)
Docstring:
Return a new array of given shape and type, filled with ones.

Parameters
----------
shape : int or sequence of ints
    Shape of the new array, e.g., ``(2, 3)`` or ``2``.
dtype : data-type, optional
    The desired data-type for the array, e.g., `numpy.int8`.  Default is
    `numpy.float64`.
order : {'C', 'F'}, optional, default: C
    Whether to store multi-dimensional data in row-major
    (C-style) or column-major (Fortran-style) order in
    memory.
like : array_like, optional
    Reference object to allow the creation of arrays which are not
    NumPy arrays. If an array-like passed in as ``like`` supports
    the ``__array_function__`` protocol, the result will be defined
    by it. In this case, it ensures the creation of an array object
    compatible with that passed in via this argument.

    .. versionadded:: 1.20.0

Returns
-------
out : ndarray
    Array of ones with the given shape, dtype, and orde

In [ ]:
연산하다가 원하는 특징을 유지해야할 때  <- ones를 사용함

In [59]:
print(np.ones(10, dtype = int), np.ones(10, dtype = int).dtype) #dtype을 int로 지정하면 int로 저장됨 !

[1 1 1 1 1 1 1 1 1 1] int32


In [60]:
# 0으로 메모리 초기화
print(np.zeros(10), np.zeros(10).dtype)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] float64


In [61]:
np.empty?

Docstring:
empty(shape, dtype=float, order='C', *, like=None)

Return a new array of given shape and type, without initializing entries.

Parameters
----------
shape : int or tuple of int
    Shape of the empty array, e.g., ``(2, 3)`` or ``2``.
dtype : data-type, optional
    Desired output data-type for the array, e.g, `numpy.int8`. Default is
    `numpy.float64`.
order : {'C', 'F'}, optional, default: 'C'
    Whether to store multi-dimensional data in row-major
    (C-style) or column-major (Fortran-style) order in
    memory.
like : array_like, optional
    Reference object to allow the creation of arrays which are not
    NumPy arrays. If an array-like passed in as ``like`` supports
    the ``__array_function__`` protocol, the result will be defined
    by it. In this case, it ensures the creation of an array object
    compatible with that passed in via this argument.

    .. versionadded:: 1.20.0

Returns
-------
out : ndarray
    Array of uninitialized (arbitrary) data of the gi

In [63]:
print(np.zeros((3,3)), np.zeros((3,3)).dtype)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] float64


In [64]:
# 메모리가 비어있음 -> 메모리가 초기화 되지 않는다.
print(np.empty(10), np.empty(10).dtype)
print(np.empty((3,3)), np.empty((3,3)).dtype)
print(np.empty((3,3)))
print(np.empty((3,3), dtype=int))  # 기존 메모리에 있던 값을 출력한다.(정확히 알수 없음)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] float64
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] float64
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[         0          0 -937010848]
 [     32762          1          0]
 [        -1         -1          0]]


In [ ]:
empty -> 메로리를 초기화해주는 개념
그냥 저런 기능이 있다, 정도로만

In [65]:
# 리스트+레인지
print( list(range(1,21)), type(list(range(1,21))) )

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20] <class 'list'>


In [67]:
# 1~20으로 구성된 4행 5열의 넘파이 배열print(np.array(list(range(1,21))), type(list(range(1,21))))
print(np.arange(20), type(np.arange(20)))
print(np.arange(1, 20), type(np.arange(1, 20)))
print(np.arange(1, 20, 2), type(np.arange(1, 20,2)))

#배열에서 사용하는 range라 np.arrange라고 사용해야 함!

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19] <class 'numpy.ndarray'>
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19] <class 'numpy.ndarray'>
[ 1  3  5  7  9 11 13 15 17 19] <class 'numpy.ndarray'>


In [68]:
# 0~49까지 구성된 넘파이 배열
arr = np.arange(50)
print(arr, len(arr), arr.size)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49] 50 50


In [69]:
# linspace 명령이나 logspace 명령은 선형 구간 혹은 로그 구간을 지정한 구간의 수만큼 분할한다.
np.linspace(0, 100, 5)  # 시작, 끝(포함), 갯수 0에서 100까지 수를 5개로 나눠서 표시함

array([  0.,  25.,  50.,  75., 100.])

In [71]:
np.linspace?

Signature:      
np.linspace(
    start,
    stop,
    num=50,
    endpoint=True,
    retstep=False,
    dtype=None,
    axis=0,
)
Call signature:  np.linspace(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function linspace at 0x000001E7936BCD60>
File:            c:\users\choiminsoo\anaconda3\lib\site-packages\numpy\core\function_base.py
Docstring:      
Return evenly spaced numbers over a specified interval.

Returns `num` evenly spaced samples, calculated over the
interval [`start`, `stop`].

The endpoint of the interval can optionally be excluded.

.. versionchanged:: 1.16.0
    Non-scalar `start` and `stop` are now supported.

.. versionchanged:: 1.20.0
    Values are rounded towards ``-inf`` instead of ``0`` when an
    integer ``dtype`` is specified. The old behavior can
    still be obtained with ``np.linspace(start, stop, num).astype(int)``

Parameters
----------
start : array_like
    The starting value of the sequence.
stop : array_like
    The 

In [72]:
np.logspace?

Signature:      
np.logspace(
    start,
    stop,
    num=50,
    endpoint=True,
    base=10.0,
    dtype=None,
    axis=0,
)
Call signature:  np.logspace(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function logspace at 0x000001E7936BCF40>
File:            c:\users\choiminsoo\anaconda3\lib\site-packages\numpy\core\function_base.py
Docstring:      
Return numbers spaced evenly on a log scale.

In linear space, the sequence starts at ``base ** start``
(`base` to the power of `start`) and ends with ``base ** stop``
(see `endpoint` below).

.. versionchanged:: 1.16.0
    Non-scalar `start` and `stop` are now supported.

.. versionchanged:: 1.25.0
    Non-scalar 'base` is now supported

Parameters
----------
start : array_like
    ``base ** start`` is the starting value of the sequence.
stop : array_like
    ``base ** stop`` is the final value of the sequence, unless `endpoint`
    is False.  In that case, ``num + 1`` values are spaced over the
    interval

In [70]:
np.logspace(0.1, 1, 10)

array([ 1.25892541,  1.58489319,  1.99526231,  2.51188643,  3.16227766,
        3.98107171,  5.01187234,  6.30957344,  7.94328235, 10.        ])

## reshape 구조의 재배열
reshape함수는 np.reshape(변경할 배열, 차원) 또는 배열.reshape(차원)으로 사용 할 수 있으며,   
현재의 배열의 차원(1차원,2차원,3차원)을 변경하여 행렬을 반환하거나 하는 경우에 많이 이용되는 함수이다.

In [73]:
# 0~49까지 구성된 넘파이 배열
arr = np.arange(50)
print(arr, len(arr), arr.size)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49] 50 50


In [74]:
arr, arr.ndim, arr.shape

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
        34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]),
 1,
 (50,))

In [75]:
arr = arr.reshape(10,5) #10행 5열로 바꿔줘
arr, arr.ndim, arr.shape

(array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]]),
 2,
 (10, 5))

In [76]:
arr2 = arr.reshape(5,10) #5행 10열로 바꿔줘
arr2, arr2.ndim, arr2.shape

(array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]]),
 2,
 (5, 10))

In [77]:
arr2 = arr.reshape(4,10) 
arr2, arr2.ndim, arr2.shape #안맞으면 에러가 남

ValueError: cannot reshape array of size 50 into shape (4,10)

In [78]:
# 2차원 -> 1차원
# 넘파이배열.flatten()
arr3 = arr2.flatten()
arr3, arr3.shape, arr3.ndim

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
        34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]),
 (50,),
 1)

In [79]:
# 1~100 사이의 짝수로 된 넘파이 배열 생성
np.arange(2,101,2)

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [80]:
print(np.arange(2,101,2).reshape(5,10))

[[  2   4   6   8  10  12  14  16  18  20]
 [ 22  24  26  28  30  32  34  36  38  40]
 [ 42  44  46  48  50  52  54  56  58  60]
 [ 62  64  66  68  70  72  74  76  78  80]
 [ 82  84  86  88  90  92  94  96  98 100]]


In [81]:
np.arange(1, 31)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [82]:
# 2차원인데 1개 칼럼의 모형을 만들어보자
# reshape(-1, n) : 2차원 n개의 컬럼으로 구성, -1을 넣으면 자동으로 사이즈를 맞춰준다. -1,n이든 n,-1이든
arr4 = np.arange(1, 31).reshape(-1, 1) #1열로, 행은 알아서
arr4, arr4.ndim, arr4.shape

(array([[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23],
        [24],
        [25],
        [26],
        [27],
        [28],
        [29],
        [30]]),
 2,
 (30, 1))

In [ ]:
30행 1열이라서 2차원

In [86]:
# 4개 칼럼으로 배열 모형을 만들자
np.arange(1, 21).reshape(5, 4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [89]:
# -1 사용해서 5열인 모형
np.arange(1, 21).reshape(-1, 5)  # 사이즈는 반드시 맞아야 함, 5열을 알아서 배치해줘~
#20개라서 7열로 맞춰달라 해도 안됨 -> arragy 는 immutable하기 떄문

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [88]:
a = np.arange(12)
a, a.shape

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]), (12,))

In [93]:
a.shape = -1, 1
a, a.shape

(array([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11]]),
 (12, 1))

In [94]:
# flatten
a.shape = -1
a, a.shape

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]), (12,))

## 넘파이배열의 자료형 형변환
- 배열명2 = 배열명1.astype(자료형)
- 자료형 = np.float64, np.int32

In [95]:
matrix1 = np.arange(1, 10)
matrix1, matrix1.dtype

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]), dtype('int32'))

In [96]:
# 정수형, 3행 3열
matrix = np.arange(1, 10).reshape(3,3)
matrix, matrix.dtype

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 dtype('int32'))

In [97]:
# 실수형, 3행 3열
matrix = np.arange(1, 10, dtype=float).reshape(3,3)
matrix, matrix.dtype

(array([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]]),
 dtype('float64'))

In [99]:
# 문자열형, 3행 3열 -> 불가
matrix = np.arange(1, 10, dtype='str').reshape(3,3)
matrix, matrix.dtype
#문자열로는 적용 불가

TypeError: arange() not supported for inputs with DType <class 'numpy.dtypes.StrDType'>.

In [102]:
# 정수형 => 문자열
matrix.astype('<U5') #유니코드로 지정해주면 문자열로 바뀜(str은 먹히지 않음)

array([['1.0', '2.0', '3.0'],
       ['4.0', '5.0', '6.0'],
       ['7.0', '8.0', '9.0']], dtype='<U5')

In [103]:
# 논리형으로 구성된 넘파이 배열 생성
matrix2 = np.array([True, False, True, True])
matrix2, matrix2.dtype

(array([ True, False,  True,  True]), dtype('bool'))

In [105]:
# 불린 -> 정수
matrix2.astype(int) # T는 1 F는0

array([1, 0, 1, 1])

In [107]:
# 불린형 -> 문자열
matrix2.astype('<U5') # 문자열로 T F 작성됨

array(['True', 'False', 'True', 'True'], dtype='<U5')

In [108]:
# 문자열 숫자 => 정수 , 실수
matrix3 = np.array(['3.14', '5.5', '0.78'])
matrix3, matrix3.dtype

(array(['3.14', '5.5', '0.78'], dtype='<U4'), dtype('<U4'))

In [109]:
print(matrix3.astype(float))

print(matrix3.astype(int)) # 불가 -> 실수라서 정수 변환은 안됨
print(matrix3.astype(bool)) # 불가 -> 실수라서 T F 변환은 안됨

[3.14 5.5  0.78]


ValueError: invalid literal for int() with base 10: '3.14'

In [110]:
matrix4 = np.array(['3', '5', '7'])
matrix4.astype(int)  # 가능, 값이 유효하기 때문

array([3, 5, 7])

In [ ]:
숫자 -> 문자는 가능
문자 -> 숫자는 제약이 있음(실제 해당 숫자 형에 맞아야함)


## 넘파이 배열의 인덱싱
넘파이배열[index] 넘파이배열[i, j], 넘파이배열[i][j] : i행 j 열

### 1D array

In [111]:
a = np.array([1, 3, 5, 7, 9])
a, a.ndim, a.shape, a.size

(array([1, 3, 5, 7, 9]), 1, (5,), 5)

In [112]:
a[0]

1

In [113]:
a[4]

9

In [114]:
a[-1]

9

In [118]:
a[[0,2,4]]

array([1, 5, 9])

In [119]:
# 행렬 구조로 인덱싱도 가능하다
b = np.array( [[1,3], [4,2]] )
b

array([[1, 3],
       [4, 2]])

In [120]:
# 넘파이배열1을 넘파이배열2로 인덱싱하는 경우. 넘파이배열2는 인덱스 번호로 인식
a[b]

array([[3, 7],
       [9, 5]])

In [121]:
print(a)
a[2] = 0
print(a)

[1 3 5 7 9]
[1 3 0 7 9]


In [122]:
a[1] += 2
a

array([1, 5, 0, 7, 9])

In [123]:
a [0] += 6
a

array([7, 5, 0, 7, 9])

### 2D array

In [156]:
a = np.arange(15).reshape(3, 5)
a, a.ndim, a.shape, a.size

(array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]]),
 2,
 (3, 5),
 15)

In [125]:
#인덱싱 값이 1개인 경우엔 행을 인덱싱함
a[0]

array([0, 1, 2, 3, 4])

In [126]:
a[1]

array([5, 6, 7, 8, 9])

In [128]:
#인덱싱값이 2개 들어가면 행/열 인덱싱
a[0,1]

1

In [131]:
a[1,3]

8

In [132]:
a[2,4]

14

In [137]:
a[-1,-1]

14

In [138]:
a[-1,4]

14

In [158]:
a[-1][-1] # 행 먼저 인덱싱하고 그 다음에 열 인덱싱 해도 됨

14

In [151]:
#값 변경
a = np.arange(15).reshape(3, -1)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [152]:
# 2행의 값 다 바꾸고 싶을 때
a[1] = [1,3,5,7,9]
a

array([[ 0,  1,  2,  3,  4],
       [ 1,  3,  5,  7,  9],
       [10, 11, 12, 13, 14]])

In [154]:
# 다 같은 값으로 변환
a[-1] = 10
a

array([[ 0,  1,  2,  3,  4],
       [ 1,  3,  5,  7,  9],
       [10, 10, 10, 10, 10]])

In [155]:
# 인덱싱별로 값을 더함
a[0] += [1,2,3,4,5]
a

array([[ 1,  3,  5,  7,  9],
       [ 1,  3,  5,  7,  9],
       [10, 10, 10, 10, 10]])

## 넘파이배열 슬라이싱
```
1차원
넘파이배열[:end]
넘파이배열[start:]
넘파이배열[start:end]
넘파이배열[start:end:step]

2차원

넘파이배열[행, 열] = [start:end:step, start2:end2:step2]
```

## 1D array

In [159]:
a = np.array([1, 3, 5, 7, 9])
a, a.ndim, a.shape, a.size

(array([1, 3, 5, 7, 9]), 1, (5,), 5)

In [160]:
a[:]

array([1, 3, 5, 7, 9])

In [162]:
 a[1:]

array([3, 5, 7, 9])

In [163]:
a[-1:]

array([9])

In [165]:
a[1:4]

array([3, 5, 7])

In [166]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [170]:
#홀수
a[1::2]

array([1, 3, 5, 7, 9])

In [ ]:
# 거꾸로 나열

In [169]:
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

### 2D array

In [3]:
a = np.arange(10, 25).reshape(3, 5)
a, a.ndim, a.shape, a.size

(array([[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]]),
 2,
 (3, 5),
 15)

In [12]:
a[:]

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [174]:
a[1:]

array([[15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [175]:
a[:-3] #인덱스를 벗어나서 나오지 않음

array([], shape=(0, 5), dtype=int32)

In [176]:
a[1:-1]

array([[15, 16, 17, 18, 19]])

In [177]:
a[:,:] #행의 범위, 열의 범위

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [180]:
a[:, 1:] #(높이인 행은 전체 필요, 열은 인덱스 두번째꺼부터)

array([[11, 12, 13, 14],
       [16, 17, 18, 19],
       [21, 22, 23, 24]])

In [181]:
a[:, -1:]

array([[14],
       [19],
       [24]])

In [197]:
a[1:,2]

array([17, 22])

In [189]:
a[:2, 1:4]

array([[11, 12, 13],
       [16, 17, 18]])

In [192]:
a[1, 2]

17

In [193]:
a[1][2]

17

In [ ]:
24.06.28

In [ ]:
# 행 뒤집기

In [8]:
a = np.arange(10, 25).reshape(3, 5)
a[::-1,:]

array([[20, 21, 22, 23, 24],
       [15, 16, 17, 18, 19],
       [10, 11, 12, 13, 14]])

In [9]:
# 열 뒤집기
a[:,::-1]

array([[14, 13, 12, 11, 10],
       [19, 18, 17, 16, 15],
       [24, 23, 22, 21, 20]])

## 전치 행렬

In [ ]:
가로가 세로로 옮겨지도록

In [15]:
# 3행 2열
matrix_d = np.arange(1,7).reshape(3,2)
matrix_d

array([[1, 2],
       [3, 4],
       [5, 6]])

In [18]:
# 2행 3열로 변환
print(matrix_d.T)   # .T 하면 행과 열을 서로 바꿔주는 것(전치 행렬, 행과 열만 바꿔주는 것)

[[1 3 5]
 [2 4 6]]


In [19]:
# reshape과 transpose은 값이 다름을 유의(***reshape는 flatten이 선행됨***)
print(matrix_d.reshape(2,3))

[[1 2 3]
 [4 5 6]]


## 난수로 구성된 넘파이 배열

In [20]:
np.random?

Type:        module
String form: <module 'numpy.random' from 'C:\\Users\\ChoiMinsoo\\anaconda3\\Lib\\site-packages\\numpy\\random\\__init__.py'>
File:        c:\users\choiminsoo\anaconda3\lib\site-packages\numpy\random\__init__.py
Docstring:  
Random Number Generation

Use ``default_rng()`` to create a `Generator` and call its methods.

=============== =========================================================
Generator
--------------- ---------------------------------------------------------
Generator       Class implementing all of the random number distributions
default_rng     Default constructor for ``Generator``
=============== =========================================================

============================================= ===
BitGenerator Streams that work with Generator
--------------------------------------------- ---
MT19937
PCG64
PCG64DXSM
Philox
SFC64
============================================= ===

============================================= ===
Getting entropy 

In [202]:
# 1~10 사이의 숫자중에서 10개 출력
np.random.randint(1, 10, 10) #1 에서 10 까지중에 10개 추출

array([4, 6, 7, 1, 9, 7, 7, 1, 2, 9])

In [25]:
np.random.randint(1, 49, 6) # 로또 ㅋㅋㅋ

array([ 5, 10,  9,  8,  8, 43])

In [28]:
# 2행 5열로 츨력
np.random.randint(1, 10, (2,5)) #행렬 구조로 추출이 가능하다

array([[9, 3, 9, 1, 7],
       [5, 6, 5, 4, 8]])

## 섞기

np.random.shuffle(넘파이배열) 원본에 바로 적용

In [29]:
np.random.shuffle?

Docstring:
shuffle(x)

Modify a sequence in-place by shuffling its contents.

This function only shuffles the array along the first axis of a
multi-dimensional array. The order of sub-arrays is changed but
their contents remains the same.

.. note::
    New code should use the `~numpy.random.Generator.shuffle`
    method of a `~numpy.random.Generator` instance instead;
    please see the :ref:`random-quick-start`.

Parameters
----------
x : ndarray or MutableSequence
    The array, list or mutable sequence to be shuffled.

Returns
-------
None

See Also
--------
random.Generator.shuffle: which should be used for new code.

Examples
--------
>>> arr = np.arange(10)
>>> np.random.shuffle(arr)
>>> arr
[1 7 5 2 9 4 3 6 0 8] # random

Multi-dimensional arrays are only shuffled along the first axis:

>>> arr = np.arange(9).reshape((3, 3))
>>> np.random.shuffle(arr)
>>> arr
array([[3, 4, 5], # random
       [6, 7, 8],
       [0, 1, 2]])
Type:      builtin_function_or_method

In [ ]:
# in-place -> 원본값 바꾼다는 뜻

In [31]:
# 10개 무작위 값 만들기
matrix_e = np.arange(1,11)
matrix_e
#원본이 바뀜!!

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Quiz : 1~45까지 구성된 숫자 중에서 6개를 뽑아서 로또 번호를 생성하라

In [32]:
num= np.arange(1,46)
np.random.shuffle(num)
num[:6]

array([17, 29,  8,  5, 39, 12])

In [41]:
np.random.randint(1,46,6)

array([29, 28, 10, 20, 35,  4])

## 실수 난수
np.random.randn(n)   
 np.random.randn(i, j)

In [42]:
np.random.randn?

Docstring:
randn(d0, d1, ..., dn)

Return a sample (or samples) from the "standard normal" distribution.

.. note::
    This is a convenience function for users porting code from Matlab,
    and wraps `standard_normal`. That function takes a
    tuple to specify the size of the output, which is consistent with
    other NumPy functions like `numpy.zeros` and `numpy.ones`.

.. note::
    New code should use the
    `~numpy.random.Generator.standard_normal`
    method of a `~numpy.random.Generator` instance instead;
    please see the :ref:`random-quick-start`.

If positive int_like arguments are provided, `randn` generates an array
of shape ``(d0, d1, ..., dn)``, filled
with random floats sampled from a univariate "normal" (Gaussian)
distribution of mean 0 and variance 1. A single float randomly sampled
from the distribution is returned if no argument is provided.

Parameters
----------
d0, d1, ..., dn : int, optional
    The dimensions of the returned array, must be non-negative.
    I

In [43]:
matrix1 = np.random.randn(10) # 표준정규분포 0 ~ 분산1
matrix1

#실수의 난수를 10개 뽑아줘

array([-1.57703109, -0.60474431,  0.4734251 ,  0.62948357, -1.06981585,
        0.4098568 , -1.04999909,  0.89007209,  0.08440244,  1.27467654])

In [44]:
matrix2 = np.random.randn(4, 4)
matrix2

array([[ 1.02538943, -0.68015778, -0.46042026, -0.8596088 ],
       [ 0.06131602,  0.13210523,  0.07063187, -1.87795883],
       [-0.4776328 ,  2.18789514, -1.73510168, -0.95811448],
       [ 0.74760054,  0.39926148, -1.06946151,  2.04422132]])

In [50]:
np.random.choice?
#이런게 있다

Docstring:
choice(a, size=None, replace=True, p=None)

Generates a random sample from a given 1-D array

.. versionadded:: 1.7.0

.. note::
    New code should use the `~numpy.random.Generator.choice`
    method of a `~numpy.random.Generator` instance instead;
    please see the :ref:`random-quick-start`.

Parameters
----------
a : 1-D array-like or int
    If an ndarray, a random sample is generated from its elements.
    If an int, the random sample is generated as if it were ``np.arange(a)``
size : int or tuple of ints, optional
    Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
    ``m * n * k`` samples are drawn.  Default is None, in which case a
    single value is returned.
replace : boolean, optional
    Whether the sample is with or without replacement. Default is True,
    meaning that a value of ``a`` can be selected multiple times.
p : 1-D array-like, optional
    The probabilities associated with each entry in a.
    If not given, the sample assumes a unif

## 집계함수에서의 축
```
2차원에서의 집계합수(sum, mean)
axis = 0, 1
np.sum(넘파이배열, axis=0/1)
np.mean(넘파이배열, axis=0/1)
np.sort(넘파이배열, axis=0/1)

In [51]:
m1 = np.random.randint(1, 50, (5,5))
m1

array([[20, 26, 23, 47, 17],
       [ 3,  1,  2,  9, 49],
       [26, 32, 23, 19, 47],
       [36, 15,  1, 42, 34],
       [16,  3, 22,  3, 42]])

In [ ]:
열방향으로 합치는건지 행방향으로 합치는건지?

In [52]:
np.sum?

Signature:      
np.sum(
    a,
    axis=None,
    dtype=None,
    out=None,
    keepdims=<no value>,
    initial=<no value>,
    where=<no value>,
)
Call signature:  np.sum(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function sum at 0x00000198C67D2020>
File:            c:\users\choiminsoo\anaconda3\lib\site-packages\numpy\core\fromnumeric.py
Docstring:      
Sum of array elements over a given axis.

Parameters
----------
a : array_like
    Elements to sum.
axis : None or int or tuple of ints, optional
    Axis or axes along which a sum is performed.  The default,
    axis=None, will sum all of the elements of the input array.  If
    axis is negative it counts from the last to the first axis.

    .. versionadded:: 1.7.0

    If axis is a tuple of ints, a sum is performed on all of the axes
    specified in the tuple instead of a single axis or all the axes as
    before.
dtype : dtype, optional
    The type of the returned array and of the accumulator

In [59]:
np.sum(m1, axis=0) # 열 합계(행 방향 합계)(y축)
# 20+3+26+36+16 = 101

array([101,  77,  71, 120, 189])

In [60]:
np.sum(m1, axis=1) # 행 합계(열 방향 합계)(x축)

array([133,  64, 147, 128,  86])

In [62]:
# 1번째행의 합계는
m1[0,:]

array([20, 26, 23, 47, 17])

In [65]:
np.sum(m1[0,:], axis=0)

133

In [71]:
# 3열의 합
np.sum(m1[:,2], axis=0)
#행은 전부 다 뽑아와야 함

71

## np.sort()

In [75]:
# 정수 난수로 구성된 4x3
m2 = np.random.randint(1, 50,(4,3))
m2

array([[17, 40, 41],
       [ 3, 37, 27],
       [18, 31, 48],
       [11, 47, 24]])

In [73]:
np.sort?

Signature:       np.sort(a, axis=-1, kind=None, order=None)
Call signature:  np.sort(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function sort at 0x00000198C67D0EA0>
File:            c:\users\choiminsoo\anaconda3\lib\site-packages\numpy\core\fromnumeric.py
Docstring:      
Return a sorted copy of an array.

Parameters
----------
a : array_like
    Array to be sorted.
axis : int or None, optional
    Axis along which to sort. If None, the array is flattened before
    sorting. The default is -1, which sorts along the last axis.
kind : {'quicksort', 'mergesort', 'heapsort', 'stable'}, optional
    Sorting algorithm. The default is 'quicksort'. Note that both 'stable'
    and 'mergesort' use timsort or radix sort under the covers and, in general,
    the actual implementation will vary with data type. The 'mergesort' option
    is retained for backwards compatibility.

    .. versionchanged:: 1.15.0.
       The 'stable' option was added.

order : str or li

In [82]:
np.sort(m2) # 행 안에서 열 정렬 #default axis = -1

array([[17, 40, 41],
       [ 3, 27, 37],
       [18, 31, 48],
       [11, 24, 47]])

In [ ]:
# 행 방향에서 오름차순

In [84]:
np.sort(m2, axis = 0) #열정렬(행방향) 오름차순(요소별로)

array([[ 3, 31, 24],
       [11, 37, 27],
       [17, 40, 41],
       [18, 47, 48]])

In [86]:
m2[::-1, ::] # 행전체가 역순으로 바뀌는 것과는 다르다(sorting은 요소별 정렬)

array([[11, 47, 24],
       [18, 31, 48],
       [ 3, 37, 27],
       [17, 40, 41]])

In [87]:
m2

array([[17, 40, 41],
       [ 3, 37, 27],
       [18, 31, 48],
       [11, 47, 24]])

In [89]:
np.sort(m2, axis=1) # 행정렬(열방향) 오름차순

array([[17, 40, 41],
       [ 3, 27, 37],
       [18, 31, 48],
       [11, 24, 47]])

In [90]:
m2[::-1, ::-1] 

array([[24, 47, 11],
       [48, 31, 18],
       [27, 37,  3],
       [41, 40, 17]])

## 인덱스 소팅
np.argsort(넘파이배열, axis=0,1)

정렬값을 인덱스로 반환 (np.sort()를 인덱스로)

In [91]:
# 데이터를 원하는 기준에 따라 정렬

In [93]:
x = np.array([9,5,4])
np.argsort(x) # 오름차순 정렬 4 5 9 의 인덱스 값 
# 인덱스가 0 1 2 라서 오름차순인 2 1 0 순으로 변환함

array([2, 1, 0], dtype=int64)

In [94]:
x[np.argsort(x)] # 인덱스값으로 실제 값 출력

array([4, 5, 9])

## 넘파이 배열 요소 추가와 삭제
```
삽입

np.insert(배열, 위치인덱스, 값, axis=0/1)
2차원인 경우 axis를 설정하지 않으면 1차원 배열로 변경되어 삽입출력
삭제

np.delete(배열명, 위치인덱스, axis=0/1)
```

In [95]:
m3 = np.arange(1,11)
m3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [96]:
np.insert(m3, 0, 100)

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10])

In [98]:
m3[0] # 원래 값은 바뀌지 않음

1

In [99]:
np.insert(m3, -1, 500)  # 인덱싱/슬라이싱 end처럼 인식

array([  1,   2,   3,   4,   5,   6,   7,   8,   9, 500,  10])

In [100]:
np.insert(m3, len(m3), 500) 

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10, 500])

In [101]:
m4 = np.arange(1,10).reshape(3,3)
m4

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [103]:
np.insert(m4, 0, 100) # 2차원배열의 경우 axis 미설정시 1차원으로 변경되어 삽입 #0행0열인지 뭔지 모름

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [104]:
# 1열으로 [100,100,100] 삽입
np.insert(m4, 0, 100, axis=1)

array([[100,   1,   2,   3],
       [100,   4,   5,   6],
       [100,   7,   8,   9]])

In [105]:
# 리스트로 삽입
np.insert(m4, 0, [100,200,300], axis=1)

array([[100,   1,   2,   3],
       [200,   4,   5,   6],
       [300,   7,   8,   9]])

In [106]:
# 1행으로 [100,100,100] 삽입
np.insert(m4, 0, 100, axis=0)

array([[100, 100, 100],
       [  1,   2,   3],
       [  4,   5,   6],
       [  7,   8,   9]])

In [108]:
m4.shape, m4.shape[1], len(m4)
# 새 배열을 반환해줬을 뿐 배열 자체가 바뀐건 아님

((3, 3), 3, 3)

In [109]:
# 마지막 컬럼으로 삽입
# 배열명.shape[1] 칼럼 길이
np.insert(m4, m4.shape[1], [100,200,300], axis=1)

array([[  1,   2,   3, 100],
       [  4,   5,   6, 200],
       [  7,   8,   9, 300]])

In [110]:
# 마지막 행에 삽입
np.insert(m4, m4.shape[0], [100,200,300], axis=0)

array([[  1,   2,   3],
       [  4,   5,   6],
       [  7,   8,   9],
       [100, 200, 300]])

In [111]:
m4

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [112]:
np.delete(m4, 0, axis=0)

array([[4, 5, 6],
       [7, 8, 9]])

## 배열 합치기
```
np.vstack((배열1,배열2....)) : 세로 합치기
np.hstack((배열1,배열2....)) : 가로 합치기
np.concatenate((배열1, 배열2), axis=0/1 ) 2차원만 가능
```

In [117]:
a = np.array([1,2,3])
b = np.array([4,5,6])
np.vstack((a,b)) # 아래에

array([[1, 2, 3],
       [4, 5, 6]])

In [118]:
np.hstack((a,b)) #백터로

array([1, 2, 3, 4, 5, 6])

In [122]:
c = np.array([[1,2,3]]) # 2차원 [[]] 라서 값이 안채워져있을 뿐, 2차원
c, c.ndim, c.shape

(array([[1, 2, 3]]), 2, (1, 3))

In [120]:
d = np.array([[4,5,6]]) # 2차원
d, d.ndim, d.shape

(array([[4, 5, 6]]), 2, (1, 3))

In [121]:
f = np.concatenate((c,d), axis=0) #
f, f.ndim, f.shape

(array([[1, 2, 3],
        [4, 5, 6]]),
 2,
 (2, 3))

In [125]:
f = np.concatenate((c,d), axis=1) #
f, f.ndim, f.shape

(array([[1, 2, 3, 4, 5, 6]]), 2, (1, 6))

## boolean indexing, mask
```

조건절의 결과는 True, False로 반환
True인 결과의 데이터 반환
넘파이배열[조건절] : ==, !=, <=, >=, &, |
```, ~

In [126]:
matrix = np.arange(1, 21)
matrix

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [127]:
matrix > 10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [129]:
matrix[matrix > 10] # True 값만 표시

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [130]:
(matrix > 10).sum()

10

In [134]:
len(matrix[matrix > 10])

10

In [135]:
np.sum((matrix > 10)) # 데이터가 많을수록 이게 len보다 더 빠름

10

## Quiz : 1~100사이 난수 30개를 추출하여 넘파이 배열을 생성하고, 30보다 크거나 70보다 작은 수를 출력하라

In [145]:
a = np.random.randint(1, 100, 30)
b = a[a>30]
b[b<70]

array([39, 42, 68, 41, 59, 46, 37, 67, 63, 65, 42])

In [146]:
num = np.random.randint(1, 100, 30)
(num > 30) & (num < 70) # & <- 또는

array([ True, False, False,  True,  True, False,  True,  True,  True,
       False, False,  True,  True, False, False, False,  True, False,
       False,  True,  True,  True, False, False,  True,  True,  True,
       False,  True,  True])

In [149]:
num[(num > 30) & (num < 70)]

array([33, 51, 68, 67, 63, 34, 67, 60, 41, 32, 59, 63, 64])

In [ ]:
# 이 반대의 값을 뽑고 싶다면?

In [173]:
# ~은 reverse를 의미
num[~(num > 30) & (num < 70)]

array([ 9, 27,  7, 10, 14,  2, 30,  6, 27])

## 10보다 작거나 90보다 큰 수

In [170]:
num = np.random.randint(1, 100, 30)
num

array([ 9, 74, 77, 81, 27, 94,  7, 10, 63, 93, 14, 43, 79, 82, 68, 39, 85,
        2, 56, 39, 62, 30, 73, 98,  6, 72, 86, 27, 64, 36])

In [177]:
num[(num > 90) | (num < 10)]  # | <- 또는: & 하면 겹치는게 없어서 안됨

array([ 9, 94,  7, 93,  2, 98,  6])

## fancy indexing(filtering)
```
넘파이 배열에 배열로 인덱싱하면 인덱스 번호로 인식한다.

넘파이배열1[넘파이배열2]
넘파이배열2 : 인덱스 역할 (only 정수형)
```

In [179]:
n = np.random.randint(1,100,30)
i = np.array([0, 2, 3, 10, 20])
n, n[i]

(array([13, 37, 79, 47, 80, 76, 51, 99, 91, 84,  8, 51, 78, 79, 87, 51, 81,
        48, 12, 90, 27, 22,  5, 25, 97, 65,  3, 84,  9, 22]),
 array([13, 79, 47,  8, 27]))

## np.where()를 이용한 필터링
```
np.where(조건식) : 조건식 만족하는 인덱스 반환
np.where(조건식, T, F) : 조건식 만족하면 T값, 아니면F값
배열[np.where(조건식)] : 조건식 만족하는 실제 배열값
```

In [181]:
np.where?

Call signature:  np.where(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <built-in function where>
Docstring:      
where(condition, [x, y], /)

Return elements chosen from `x` or `y` depending on `condition`.

.. note::
    When only `condition` is provided, this function is a shorthand for
    ``np.asarray(condition).nonzero()``. Using `nonzero` directly should be
    preferred, as it behaves correctly for subclasses. The rest of this
    documentation covers only the case where all three arguments are
    provided.

Parameters
----------
condition : array_like, bool
    Where True, yield `x`, otherwise yield `y`.
x, y : array_like
    Values from which to choose. `x`, `y` and `condition` need to be
    broadcastable to some shape.

Returns
-------
out : ndarray
    An array with elements from `x` where `condition` is True, and elements
    from `y` elsewhere.

See Also
--------
choose
nonzero : The function that is called when x and y are omitted

Notes


In [182]:
a = np.arange(10)
a, np.where(a < 5, a, 10*a)
# a가 5보다 작으면 a를, 아니면 10을 곱하여 출력

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([ 0,  1,  2,  3,  4, 50, 60, 70, 80, 90]))

In [183]:
b = np.arange(20, 31)
b, np.where(b<25) # 조건을 하나만 주면 인덱스를 반환함

(array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]),
 (array([0, 1, 2, 3, 4], dtype=int64),))