In [1]:
import numpy as np
# Seed for reproducibility
np.random.seed(1)

In [2]:
# arange creates an array with a range of numbers
x = np.arange(10, 15)

In [3]:
# What's in x?
print(x)
type(x)

[10 11 12 13 14]


numpy.ndarray

In [4]:
# Basic indexing of x
x[2]

12

In [5]:
# Requesting specific indices
x[[1, 3]]

array([11, 13])

In [6]:
# Elementwise addition
x + 1

array([11, 12, 13, 14, 15])

In [7]:
# Elementwise multiplication
x * 2

array([20, 22, 24, 26, 28])

In [8]:
# Inner product
y = np.array([0, 1, 0, 0, 1])
np.dot(x, y)

25

In [9]:
# A few equivalent ways to create a matrix. Note that "arrays" in
# numpy are n-dimensional, while matrices are special 2-d arrays
a = np.matrix('1 2; 3 4; 5 6')
b = np.array([1, 2, 3, 4, 5, 6]).reshape(3,2)
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [10]:
# Default equality is elementwise
a == b

matrix([[ True,  True],
        [ True,  True],
        [ True,  True]], dtype=bool)

In [11]:
# Full matrix equality
np.array_equal(a, b)

True

In [12]:
# Back to our example vector for more complex indexing
x

array([10, 11, 12, 13, 14])

In [13]:
# Boolean expressions on an array create logical indices or "masks"
x > 2

array([ True,  True,  True,  True,  True], dtype=bool)

In [14]:
# We can use anything that is boolean-like (i.e., zero and non-zero) to create a mask, but we may need to convert it
print(repr(x % 2))
(x % 2).astype(bool)

array([0, 1, 0, 1, 0], dtype=int32)


array([False,  True, False,  True, False], dtype=bool)

In [15]:
# Using a mask
x[x > 2]

array([10, 11, 12, 13, 14])

In [16]:
# Another mask, select the odd number values
x[(x % 2).astype(bool)]

array([11, 13])

In [17]:
# Lots of standard numeric methods are available, for example sum
# Press the tab key after the period to see more options
x.sum()

60

In [18]:
# Drawing random integers
c = np.random.randint(1, 100, 5)
c

array([38, 13, 73, 10, 76])

In [19]:
# Which index is the highest?
c.argmax()

4

In [20]:
# All checks whether all values are True
(c > 1).all()

True

In [21]:
# Any checks whether any value is True
(c > 50).any()

True