In [1]:
import tensorflow as tf
print(tf.__version__)

1.2.0


In [2]:
x_data = [[73., 80., 75.],[93., 88., 93.],[89., 91., 90.],[96., 98., 100.],[73., 66., 70.]]
y_data = [[152.],[185.],[180.],[196.],[142.]]

X = tf.placeholder(tf.float32, shape=[None,3])  #shape에서 None은 지금은 5개지만 n개까지 가능하도록 None로 설정 그리고 3은 각 인스턴스(데이터)안에 포함된 피쳐의 개수 3개  
Y = tf.placeholder(tf.float32, shape=[None,1])  #마찬가지로 None로 설정 그리고 y의 피쳐의 개수는 1개

W = tf.Variable(tf.random_normal([3,1]), name="weight")
b = tf.Variable(tf.random_normal([1]), name="bias")

hypothesis = tf.matmul(X, W) + b

cost = tf.reduce_mean(tf.square(hypothesis - Y))


optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [3]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [8]:
for step in range(3001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict = {X: x_data, Y: y_data})
    if step % 10 == 0:
        print(step," Cost : ", cost_val, "\nPrediction:\n", hy_val)
        print("="*80)

0  Cost :  29726.2 
Prediction:
 [[ 294.35977173]
 [ 374.81066895]
 [ 358.01467896]
 [ 395.2791748 ]
 [ 286.68954468]]
10  Cost :  36.4391 
Prediction:
 [[ 141.95579529]
 [ 191.59107971]
 [ 177.50691223]
 [ 198.70704651]
 [ 146.93186951]]
20  Cost :  36.0007 
Prediction:
 [[ 141.51651001]
 [ 191.02185059]
 [ 176.96759033]
 [ 198.11610413]
 [ 146.49043274]]
30  Cost :  35.835 
Prediction:
 [[ 141.53700256]
 [ 191.00531006]
 [ 176.97279358]
 [ 198.11813354]
 [ 146.47061157]]
40  Cost :  35.6702 
Prediction:
 [[ 141.55879211]
 [ 190.99046326]
 [ 176.97962952]
 [ 198.12193298]
 [ 146.4520874 ]]
50  Cost :  35.5061 
Prediction:
 [[ 141.58056641]
 [ 190.97566223]
 [ 176.98643494]
 [ 198.12574768]
 [ 146.43362427]]
60  Cost :  35.343 
Prediction:
 [[ 141.60224915]
 [ 190.96089172]
 [ 176.99324036]
 [ 198.12953186]
 [ 146.41520691]]
70  Cost :  35.1808 
Prediction:
 [[ 141.62388611]
 [ 190.94616699]
 [ 177.        ]
 [ 198.13330078]
 [ 146.39685059]]
80  Cost :  35.0194 
Prediction:
 [[ 141.64