In [1]:
import tensorflow as tf
print(tf.__version__)

1.2.0


In [6]:
"""
x1 | x2 |  x3 | y
73 , 80 ,  75, 152
93 , 88 ,  93, 185
89 , 91 ,  90, 180
96 , 98 , 100, 196
73 , 66 ,  70, 142
"""

x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100.,70.]
y_data  = [152., 185., 180., 196., 142.]

In [7]:
x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)

y = tf.placeholder(tf.float32)

w1 = tf.Variable(tf.random_normal([1]), name = "weight1")
w2 = tf.Variable(tf.random_normal([1]), name = "weight2")
w3 = tf.Variable(tf.random_normal([1]), name = "weight3")
b = tf.Variable(tf.random_normal([1]),  name = "bias")


In [8]:
hypothesis = x1*w1 + x2*w2 + x3*w3 + b

In [9]:
cost = tf.reduce_mean(tf.square(hypothesis - y))

In [10]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)

In [11]:
train = optimizer.minimize(cost)

In [20]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())
for step in range(3001):
    cost_val, hy_val, _, w1_val, w2_val, w3_val, b_val = sess.run([cost, hypothesis, train, w1, w2, w3, b], feed_dict = {x1: x1_data, x2: x2_data, x3: x3_data, y: y_data})
    if step % 10 == 0:
        print(step," Cost : ", cost_val, "\nPrediction:\n", hy_val, "\n", w1_val, w2_val, w3_val, b_val)
        print("="*80)
    

0  Cost :  14891.9 
Prediction:
 [ 41.50660324  55.46178436  51.63835526  58.10248184  42.10884857] 
 [ 0.31735304] [-0.12070566] [ 1.01089811] [-0.16583999]
10  Cost :  1.87814 
Prediction:
 [ 149.45440674  185.20294189  179.47666931  197.31439209  141.06834412] 
 [ 0.5813989] [ 0.14351311] [ 1.27784491] [-0.16274226]
20  Cost :  1.73987 
Prediction:
 [ 149.78318787  185.59407043  179.86421204  197.73558044  141.36636353] 
 [ 0.58211118] [ 0.14465931] [ 1.27839553] [-0.16270693]
30  Cost :  1.73793 
Prediction:
 [ 149.78631592  185.59381104  179.86608887  197.73681641  141.36584473] 
 [ 0.58202732] [ 0.14500876] [ 1.27814031] [-0.16268083]
40  Cost :  1.73599 
Prediction:
 [ 149.78846741  185.59239197  179.86682129  197.73680115  141.36444092] 
 [ 0.58194155] [ 0.14535502] [ 1.27788281] [-0.16265476]
50  Cost :  1.73406 
Prediction:
 [ 149.7906189   185.5909729   179.86755371  197.73678589  141.36305237] 
 [ 0.58185649] [ 0.14570056] [ 1.27762532] [-0.16262868]
60  Cost :  1.73212 
Pr