In [1]:
%pylab
%matplotlib inline

Using matplotlib backend: agg
Populating the interactive namespace from numpy and matplotlib


In [2]:
cd ..

/home/scott/Documents/git/neukrill-net-work


In [3]:
import sys
import numpy as np
import skimage
import cv2
import sklearn
import imp

In [4]:
from holoviews import *

:0: FutureWarning: IPython widgets are experimental and may change in the future.


In [5]:
import neukrill_net.utils
import neukrill_net.highlevelfeatures

In [6]:
settings = neukrill_net.utils.Settings('settings.json')

In [7]:
X,y = settings.flattened_train_paths(settings.classes)

In [8]:
import neukrill_net.image_features

In [9]:
import sklearn.ensemble

In [71]:
imp.reload(neukrill_net.highlevelfeatures)
imp.reload(neukrill_net.image_features)

<module 'neukrill_net.image_features' from '/home/scott/Documents/git/neukrill-net-tools/neukrill_net/image_features.py'>

In [53]:
clf = sklearn.ensemble.RandomForestClassifier(n_estimators=100)
kpclf = neukrill_net.highlevelfeatures.KeypointEnsembleClassifier(
    lambda x:neukrill_net.image_features.get_ORB_keypoints(x,n=10),
    neukrill_net.image_features.get_ORB_descriptions,
    clf)

In [12]:
X_train, X_test, y_train, y_test = sklearn.cross_validation.train_test_split(X, y, test_size=0.8, random_state=42)

In [13]:
len(y_train)

6067

In [14]:
len(np.unique(y_train))

120

In [15]:
len(np.unique(y_test))

121

In [16]:
h = np.histogram(y, bins=np.arange(np.min(y),np.max(y)+1)-0.5)

In [17]:
h[0]

array([ 889,   13,   71,   49,   16,  532,  696,  242,  393,  170,  815,
       1934,  694,   77,  681,  173,   96,  178,   63,  286,  106,   49,
         87,   30,  899, 1189,   24,  201,  113,   42,   53,   38,   55,
        363,  394,  914,  519,  500,   36,   92,   80,   88,  385,  536,
         96,   27,   14,  136,   38,  511,   10,   31,   85,  114,   64,
         16,   10,  127,   75,   35,  229,    9,   19,   23,  132,  336,
         12,  190,  412,  274,  150,   76,  703,  123,   43,   56,   14,
         61,   14,   24,  141,  131,  108,  372,  625, 1172,  113,  108,
         13,   65,  287,  158,   49,   52,  153,  174,  212,  135,  483,
        179,   57,  247,   29,   30,  128,   21,   24,   38,  708,   54,
       1979,  678,   29,  439,  417,  352,  236,   73,  317,  175])

In [18]:
kpclf.fit(X_train, y_train)

Reached limit of patch size.
Reached limit of patch size.
Reached limit of patch size.
Reached limit of patch size.


In [54]:
skf = sklearn.cross_validation.StratifiedKFold(y, n_folds=5)
for train_index, test_index in skf:
    X_train = [X[i] for i in test_index]
    X_test = [X[i] for i in train_index]
    y_train = [y[i] for i in test_index]
    y_test = [y[i] for i in train_index]
    print len(np.unique(y_train)), len(np.unique(y_test))
    kpclf.fit(X_train,y_train)
    p = kpclf.transform(X_test).squeeze(0)[:,1:]
    print "Log-loss = {}".format(sklearn.metrics.log_loss(y_test, p))

121 121
Reached limit of patch size.
Reached limit of patch size.
Reached limit of patch size.
Reached limit of patch size.
Reached limit of patch size.
Reached limit of patch size.
Reached limit of patch size.
Reached limit of patch size.
Reached limit of patch size.
Reached limit of patch size.
Reached limit of patch size.
Reached limit of patch size.
Reached limit of patch size.
Reached limit of patch size.
Reached limit of patch size.
Reached limit of patch size.
Reached limit of patch size.
Reached limit of patch size.
Reached limit of patch size.
Reached limit of patch size.
Reached limit of patch size.
Reached limit of patch size.
Reached limit of patch size.
Reached limit of patch size.
Reached limit of patch size.
Reached limit of patch size.
Reached limit of patch size.
Reached limit of patch size.
Reached limit of patch size.
Reached limit of patch size.
Reached limit of patch size.
Reached limit of patch size.
Reached limit of patch size.
Reached limit of patch size.


/home/scott/Documents/git/neukrill-net-tools/neukrill_net/highlevelfeatures.py:540: RuntimeWarning: divide by zero encountered in true_divide
  vec = np.ones((1,self.num_classes)) / num_kp


ValueError: Found array with dim 1. Expected 24221

In [59]:
    print "Log-loss = {}".format(sklearn.metrics.log_loss(y_test, p.squeeze(0)))
    print "Accuracy = {}".format(sklearn.metrics.accuracy_score(y_test, p.squeeze(0)))
    print "AUC = {}".format(sklearn.metrics.auc(y_test, p.squeeze(0)))

ValueError: Found array with dim 24220. Expected 24221

In [61]:
p.squeeze(0).shape

(24220, 122)

In [62]:
len(y_test)

24221

In [63]:
p2 = kpclf.transform(X_test)

Reached limit of patch size.
Reached limit of patch size.
Reached limit of patch size.
Reached limit of patch size.
Reached limit of patch size.
Reached limit of patch size.
Reached limit of patch size.
Reached limit of patch size.
Reached limit of patch size.
Reached limit of patch size.
Reached limit of patch size.
Reached limit of patch size.
Reached limit of patch size.
Reached limit of patch size.
Reached limit of patch size.
Reached limit of patch size.
Reached limit of patch size.
Reached limit of patch size.
Reached limit of patch size.
Reached limit of patch size.
Reached limit of patch size.
Reached limit of patch size.
Reached limit of patch size.
Reached limit of patch size.
Reached limit of patch size.
Reached limit of patch size.
Reached limit of patch size.
Reached limit of patch size.
Reached limit of patch size.


In [64]:
p2.shape

(1, 24221, 122)

In [66]:
p22 = p2.squeeze(0)[:,1:]

In [68]:
    print "Log-loss = {}".format(sklearn.metrics.log_loss(y_test, p22))
    print "AUC = {}".format(sklearn.metrics.auc(y_test, p22))

Log-loss = 2.97927600074


ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

In [51]:
np.array([10])

array([10])

In [69]:
clf = sklearn.ensemble.RandomForestClassifier(n_estimators=100, max_depth=5)
kpclf = neukrill_net.highlevelfeatures.KeypointEnsembleClassifier(
    lambda x:neukrill_net.image_features.get_ORB_keypoints(x,n=10),
    neukrill_net.image_features.get_ORB_descriptions,
    clf)

In [70]:
skf = sklearn.cross_validation.StratifiedKFold(y, n_folds=5)
for train_index, test_index in skf:
    X_train = [X[i] for i in test_index]
    X_test = [X[i] for i in train_index]
    y_train = [y[i] for i in test_index]
    y_test = [y[i] for i in train_index]
    print len(np.unique(y_train)), len(np.unique(y_test))
    print "Fitting..."
    kpclf.fit(X_train,y_train)
    print "Classifying..."
    p = kpclf.transform(X_test).squeeze(0)[:,1:]
    print "Log-loss = {}".format(sklearn.metrics.log_loss(y_test, p))

121 121
Reached limit of patch size.
Reached limit of patch size.
Reached limit of patch size.
Reached limit of patch size.
Reached limit of patch size.
Reached limit of patch size.
Reached limit of patch size.
Reached limit of patch size.
Reached limit of patch size.
Reached limit of patch size.
Reached limit of patch size.
Reached limit of patch size.
Reached limit of patch size.
Reached limit of patch size.
Reached limit of patch size.
Reached limit of patch size.
Reached limit of patch size.
Reached limit of patch size.
Reached limit of patch size.
Reached limit of patch size.
Reached limit of patch size.
Reached limit of patch size.
Reached limit of patch size.
Reached limit of patch size.
Reached limit of patch size.
Reached limit of patch size.
Reached limit of patch size.
Reached limit of patch size.
Reached limit of patch size.
Reached limit of patch size.
Reached limit of patch size.
Reached limit of patch size.
Reached limit of patch size.
Reached limit of patch size.
Log-lo

KeyboardInterrupt: 

In [72]:
import time

In [73]:
clf = sklearn.ensemble.RandomForestClassifier(n_estimators=100, max_depth=5)
kpclf = neukrill_net.highlevelfeatures.KeypointEnsembleClassifier(
    lambda x:neukrill_net.image_features.get_ORB_keypoints(x,n=100),
    neukrill_net.image_features.get_ORB_descriptions,
    clf)
t0 = time.time()

skf = sklearn.cross_validation.StratifiedKFold(y, n_folds=5)
for train_index, test_index in skf:
    X_train = [X[i] for i in test_index]
    X_test = [X[i] for i in train_index]
    y_train = [y[i] for i in test_index]
    y_test = [y[i] for i in train_index]
    print len(np.unique(y_train)), len(np.unique(y_test))
    print "Fitting..."
    kpclf.fit(X_train,y_train)
    print "Classifying..."
    p = kpclf.transform(X_test).squeeze(0)[:,1:]
    print "Log-loss = {}".format(sklearn.metrics.log_loss(y_test, p))
    t1 = time.time()
    total = t1-t0
    print("Time={}".format(total))
    break

121 121
Fitting...
Classifying...
Log-loss = 3.72919764717
Time=283.954781055


In [75]:
clf = sklearn.ensemble.RandomForestClassifier(n_estimators=300, max_depth=10, n_jobs=6)
kpclf = neukrill_net.highlevelfeatures.KeypointEnsembleClassifier(
    lambda x:neukrill_net.image_features.get_ORB_keypoints(x,n=150),
    neukrill_net.image_features.get_ORB_descriptions,
    clf)
t0 = time.time()

skf = sklearn.cross_validation.StratifiedKFold(y, n_folds=5)
for train_index, test_index in skf:
    X_train = [X[i] for i in test_index]
    X_test = [X[i] for i in train_index]
    y_train = [y[i] for i in test_index]
    y_test = [y[i] for i in train_index]
    print len(np.unique(y_train)), len(np.unique(y_test))
    print "Fitting..."
    kpclf.fit(X_train,y_train)
    print "Fitting took {}".format(time.time()-t0)
    print "Classifying..."
    p = kpclf.transform(X_test).squeeze(0)[:,1:]
    print "Classifying took {}".format(time.time()-t0)
    print "Log-loss = {}".format(sklearn.metrics.log_loss(y_test, p))
    t1 = time.time()
    total = t1-t0
    print("Time={}".format(total))
    break

121 121
Fitting...
Classifying...


KeyboardInterrupt: 

In [77]:
clf = sklearn.ensemble.RandomForestClassifier(n_estimators=300, max_depth=10)
kpclf = neukrill_net.highlevelfeatures.KeypointEnsembleClassifier(
    lambda x:neukrill_net.image_features.get_ORB_keypoints(x,n=150),
    neukrill_net.image_features.get_ORB_descriptions,
    clf)
t0 = time.time()

skf = sklearn.cross_validation.StratifiedKFold(y, n_folds=5)
for train_index, test_index in skf:
    X_train = [X[i] for i in test_index]
    X_test = [X[i] for i in train_index]
    y_train = [y[i] for i in test_index]
    y_test = [y[i] for i in train_index]
    print len(np.unique(y_train)), len(np.unique(y_test))
    print "Fitting..."
    kpclf.fit(X_train,y_train)
    print "Fitting took {}".format(time.time()-t0)
    print "Classifying..."
    p = kpclf.transform(X_test).squeeze(0)[:,1:]
    print "Classifying took {}".format(time.time()-t0)
    print "Log-loss = {}".format(sklearn.metrics.log_loss(y_test, p))
    t1 = time.time()
    total = t1-t0
    print("Time={}".format(total))
    break

121 121
Fitting...
Fitting took 334.073971033
Classifying...
Classifying took 1161.15003395
Log-loss = 3.37332542612
Time=1161.29995704


In [78]:
clf = sklearn.ensemble.RandomForestClassifier(n_estimators=300, max_depth=10)
kpclf = neukrill_net.highlevelfeatures.KeypointEnsembleClassifier(
    lambda x:neukrill_net.image_features.get_ORB_keypoints(x,n=150),
    neukrill_net.image_features.get_ORB_descriptions,
    clf)
t0 = time.time()

skf = sklearn.cross_validation.StratifiedKFold(y, n_folds=2)
for train_index, test_index in skf:
    X_train = [X[i] for i in test_index]
    X_test = [X[i] for i in train_index]
    y_train = [y[i] for i in test_index]
    y_test = [y[i] for i in train_index]
    print len(np.unique(y_train)), len(np.unique(y_test))
    print "Fitting..."
    kpclf.fit(X_train,y_train)
    print "Fitting took {}".format(time.time()-t0)
    print "Classifying..."
    p = kpclf.transform(X_test).squeeze(0)[:,1:]
    print "Classifying took {}".format(time.time()-t0)
    print "Log-loss = {}".format(sklearn.metrics.log_loss(y_test, p))
    t1 = time.time()
    total = t1-t0
    print("Time={}".format(total))
    break

121 121
Fitting...
Fitting took 926.673700094
Classifying...
Classifying took 1442.56009007
Log-loss = 3.36479480283
Time=1442.6466291


In [80]:
h = np.histogram(y, bins=np.arange(np.min(y),np.max(y)+1)-0.5)

In [83]:
sorted(h[0])

[9,
 10,
 10,
 12,
 13,
 13,
 14,
 14,
 14,
 16,
 16,
 19,
 21,
 23,
 24,
 24,
 24,
 27,
 29,
 29,
 30,
 30,
 31,
 35,
 36,
 38,
 38,
 38,
 42,
 43,
 49,
 49,
 49,
 52,
 53,
 54,
 55,
 56,
 57,
 61,
 63,
 64,
 65,
 71,
 73,
 75,
 76,
 77,
 80,
 85,
 87,
 88,
 92,
 96,
 96,
 106,
 108,
 108,
 113,
 113,
 114,
 123,
 127,
 128,
 131,
 132,
 135,
 136,
 141,
 150,
 153,
 158,
 170,
 173,
 174,
 175,
 178,
 179,
 190,
 201,
 212,
 229,
 236,
 242,
 247,
 274,
 286,
 287,
 317,
 336,
 352,
 363,
 372,
 385,
 393,
 394,
 412,
 417,
 439,
 483,
 500,
 511,
 519,
 532,
 536,
 625,
 678,
 681,
 694,
 696,
 703,
 708,
 815,
 889,
 899,
 914,
 1172,
 1189,
 1934,
 1979]

In [84]:
np.where(np.array(h[0])>30)

(array([  0,   2,   3,   5,   6,   7,   8,   9,  10,  11,  12,  13,  14,
         15,  16,  17,  18,  19,  20,  21,  22,  24,  25,  27,  28,  29,
         30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,  42,
         43,  44,  47,  48,  49,  51,  52,  53,  54,  57,  58,  59,  60,
         64,  65,  67,  68,  69,  70,  71,  72,  73,  74,  75,  77,  80,
         81,  82,  83,  84,  85,  86,  87,  89,  90,  91,  92,  93,  94,
         95,  96,  97,  98,  99, 100, 101, 104, 107, 108, 109, 110, 111,
        113, 114, 115, 116, 117, 118, 119]),)

In [91]:
goodindices = [i for i in np.arange(0,len(y)) for keptclass in np.where(np.array(h[0])>30)[0] if y[i]==keptclass]

In [92]:
clf = sklearn.ensemble.RandomForestClassifier(n_estimators=300, max_depth=10)
kpclf = neukrill_net.highlevelfeatures.KeypointEnsembleClassifier(
    lambda x:neukrill_net.image_features.get_ORB_keypoints(x,n=150),
    neukrill_net.image_features.get_ORB_descriptions,
    clf)
t0 = time.time()

XX = [X[i] for i in goodindices]
yy = [y[i] for i in goodindices]

skf = sklearn.cross_validation.StratifiedKFold(yy, n_folds=2)
for train_index, test_index in skf:
    X_train = [XX[i] for i in test_index]
    X_test = [XX[i] for i in train_index]
    y_train = [yy[i] for i in test_index]
    y_test = [yy[i] for i in train_index]
    print len(np.unique(y_train)), len(np.unique(y_test))
    print "Fitting..."
    kpclf.fit(X_train,y_train)
    print "Fitting took {}".format(time.time()-t0)
    print "Classifying..."
    p = kpclf.transform(X_test).squeeze(0)[:,1:]
    print "Classifying took {}".format(time.time()-t0)
    print "Log-loss = {}".format(sklearn.metrics.log_loss(y_test, p))
    t1 = time.time()
    total = t1-t0
    print("Time={}".format(total))
    break

98 98
Fitting...
Fitting took 865.80667305
Classifying...
Classifying took 1311.93863297
Log-loss = 3.28194431706
Time=1312.02747798
