# 數據預處理

In [1]:
import numpy as np
import pandas as pd
import os

filepath = '/Users/mac/Desktop/Kaggle_datasets/Wiki_traffic/'
filename01 = 'train_1.csv'
filename02 = 'key_1.csv'
filename03 = 'sample_submission_1.csv'

df_train = pd.read_csv(os.path.join(filepath, filename01))
df_test = pd.read_csv(os.path.join(filepath, filename02))
df_ans = pd.read_csv(os.path.join(filepath, filename03))

In [2]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145063 entries, 0 to 145062
Columns: 551 entries, Page to 2016-12-31
dtypes: float64(550), object(1)
memory usage: 609.8+ MB


In [3]:
df_train

Page  2015-07-01  \
0                 2NE1_zh.wikipedia.org_all-access_spider        18.0   
1                  2PM_zh.wikipedia.org_all-access_spider        11.0   
2                   3C_zh.wikipedia.org_all-access_spider         1.0   
3              4minute_zh.wikipedia.org_all-access_spider        35.0   
4       52_Hz_I_Love_You_zh.wikipedia.org_all-access_s...         NaN   
5                 5566_zh.wikipedia.org_all-access_spider        12.0   
6               91Days_zh.wikipedia.org_all-access_spider         NaN   
7                A'N'D_zh.wikipedia.org_all-access_spider       118.0   
8                AKB48_zh.wikipedia.org_all-access_spider         5.0   
9                ASCII_zh.wikipedia.org_all-access_spider         6.0   
10               ASTRO_zh.wikipedia.org_all-access_spider         NaN   
11      Ahq_e-Sports_Club_zh.wikipedia.org_all-access_...         2.0   
12      All_your_base_are_belong_to_us_zh.wikipedia.or...         2.0   
13             AlphaGo_zh.wikipedia.org_all-access_spider         NaN   
14             Android_zh.wikipedia.org_all-access_spider         8.0   
15          Angelababy_zh.wikipedia.org_all-access_spider        40.0   
16               Apink_zh.wikipedia.org_all-access_spider        61.0   
17            Apple_II_zh.wikipedia.org_all-access_spider         4.0   
18              As_One_zh.wikipedia.org_all-access_spider        13.0   
19           B-PROJECT_zh.wikipedia.org_all-access_spider         NaN   
20                B1A4_zh.wikipedia.org_all-access_spider        22.0   
21                BDSM_zh.wikipedia.org_all-access_spider        25.0   
22               BEAST_zh.wikipedia.org_all-access_spider        19.0   
23             BIGBANG_zh.wikipedia.org_all-access_spider        23.0   
24          BLACK_PINK_zh.wikipedia.org_all-access_spider         NaN   
25              BLEACH_zh.wikipedia.org_all-access_spider        11.0   
26                BTOB_zh.wikipedia.org_all-access_spider        22.0   
27      Beautiful_Mind_zh.wikipedia.org_all-access_spider         NaN   
28              Beyond_zh.wikipedia.org_all-access_spider       291.0   
29                 Big_zh.wikipedia.org_all-access_spider         3.0   
...                                                   ...         ...   
145033  Sin_senos_sí_hay_paraíso_es.wikipedia.org_all-...         NaN   
145034  Anexo:Medallero_de_los_Juegos_Olímpicos_de_Río...         NaN   
145035  Arrival_(película)_es.wikipedia.org_all-access...         NaN   
145036  Anexo:Baloncesto_en_los_Juegos_Olímpicos_de_Rí...         NaN   
145037  Hasta_que_te_conocí_(serie_de_televisión)_es.w...         NaN   
145038  Westworld_(serie_de_televisión)_es.wikipedia.o...         NaN   
145039        Milénico_es.wikipedia.org_all-access_spider         NaN   
145040  Moonlight_(película)_es.wikipedia.org_all-acce...         NaN   
145041  Sully_(película)_es.wikipedia.org_all-access_s...         NaN   
145042  Pulsaciones_(serie_de_televisión)_es.wikipedia...         NaN   
145043  2091_(serie_de_televisión)_es.wikipedia.org_al...         NaN   
145044  Campeonato_Sudamericano_de_Fútbol_Sub-20_de_20...         NaN   
145045  Split_(película)_es.wikipedia.org_all-access_s...         NaN   
145046  Huracán_Matthew_es.wikipedia.org_all-access_sp...         NaN   
145047  Fences_(película)_es.wikipedia.org_all-access_...         NaN   
145048  Logan_(película)_es.wikipedia.org_all-access_s...         NaN   
145049  La_doña_(telenovela_de_2016)_es.wikipedia.org_...         NaN   
145050  RTS_(canal_de_televisión)_es.wikipedia.org_all...         NaN   
145051  La_ley_del_corazón_es.wikipedia.org_all-access...         NaN   
145052  The_Crown_(serie_de_televisión)_es.wikipedia.o...         NaN   
145053  Drake_(músico)_es.wikipedia.org_all-access_spider         NaN   
145054  Skam_(serie_de_televisión)_es.wikipedia.org_al...         NaN   
145055  Legión_(serie_de_televisión)_es.wikipedia.org_...         NaN   
145056  Doble_tentación_es.wikipedia.o

In [4]:
df_train_0 = df_train.fillna(0) #Fillna，反正分不出是0還是na就通通當成0

In [5]:
page_list = df_train['Page'].tolist()

In [6]:
page_list.sort() #排序page才方便跟test欄位比較

In [7]:
page_list

['!vote_en.wikipedia.org_all-access_all-agents',
 '!vote_en.wikipedia.org_all-access_spider',
 '!vote_en.wikipedia.org_desktop_all-agents',
 '"Awaken,_My_Love!"_en.wikipedia.org_all-access_all-agents',
 '"Awaken,_My_Love!"_en.wikipedia.org_all-access_spider',
 '"Awaken,_My_Love!"_en.wikipedia.org_desktop_all-agents',
 '"European_Society_for_Clinical_Investigation"_en.wikipedia.org_all-access_all-agents',
 '"European_Society_for_Clinical_Investigation"_en.wikipedia.org_all-access_spider',
 '"European_Society_for_Clinical_Investigation"_en.wikipedia.org_desktop_all-agents',
 '"Heroes"_(David_Bowie_album)_en.wikipedia.org_all-access_all-agents',
 '"Heroes"_(David_Bowie_album)_en.wikipedia.org_all-access_spider',
 '"Heroes"_(David_Bowie_album)_en.wikipedia.org_desktop_all-agents',
 '"Keep_me_logged_in"_extended_to_one_year_www.mediawiki.org_all-access_all-agents',
 '"Keep_me_logged_in"_extended_to_one_year_www.mediawiki.org_all-access_spider',
 '"Keep_me_logged_in"_extended_to_one_year_www

### 可以發現到：8703780/145063 = 每一頁有60個Id，代表60天的每日數據流量 <br/>
### 分別是從1/1~3/1的每日數據流量預測項目，上傳答案就是每日數據流量預測

In [8]:
df_test.info() #可以發現到：8703780/145063 = 每一頁有60個Id，分別是從1/1~3/1的每日數據流量預測項目，上傳答案就是每日數據流量預測

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8703780 entries, 0 to 8703779
Data columns (total 2 columns):
Page    object
Id      object
dtypes: object(2)
memory usage: 132.8+ MB


In [9]:
df_test

Page            Id
0        !vote_en.wikipedia.org_all-access_all-agents_2...  bf4edcf969af
1        !vote_en.wikipedia.org_all-access_all-agents_2...  929ed2bf52b9
2        !vote_en.wikipedia.org_all-access_all-agents_2...  ff29d0f51d5c
3        !vote_en.wikipedia.org_all-access_all-agents_2...  e98873359be6
4        !vote_en.wikipedia.org_all-access_all-agents_2...  fa012434263a
5        !vote_en.wikipedia.org_all-access_all-agents_2...  48f1e93517a2
6        !vote_en.wikipedia.org_all-access_all-agents_2...  5def418fcb36
7        !vote_en.wikipedia.org_all-access_all-agents_2...  77bd08134351
8        !vote_en.wikipedia.org_all-access_all-agents_2...  5889e6dbb16f
9        !vote_en.wikipedia.org_all-access_all-agents_2...  5f21fef1d764
10       !vote_en.wikipedia.org_all-access_all-agents_2...  6f07e1b8815a
11       !vote_en.wikipedia.org_all-access_all-agents_2...  228e54b5dea0
12       !vote_en.wikipedia.org_all-access_all-agents_2...  da1b34963ed7
13       !vote_en.wikipedia.org_all-access_all-agents_2...  ab5ccefaa2db
14       !vote_en.wikipedia.org_all-access_all-agents_2...  cbf42873ebf1
15       !vote_en.wikipedia.org_all-access_all-agents_2...  ac67e35ed44e
16       !vote_en.wikipedia.org_all-access_all-agents_2...  88c098aa640d
17       !vote_en.wikipedia.org_all-access_all-agents_2...  7c72842a89d1
18       !vote_en.wikipedia.org_all-access_all-agents_2...  8ce002f2c329
19       !vote_en.wikipedia.org_all-access_all-agents_2...  5f72d9920560
20       !vote_en.wikipedia.org_all-access_all-agents_2...  f93afd7f5d9b
21       !vote_en.wikipedia.org_all-access_all-agents_2...  14011cb66f2d
22       !vote_en.wikipedia.org_all-access_all-agents_2...  0065551ac465
23       !vote_en.wikipedia.org_all-access_all-agents_2...  175f1872729e
24       !vote_en.wikipedia.org_all-access_all-agents_2...  31d756e83124
25       !vote_en.wikipedia.org_all-access_all-agents_2...  e186c2363c5e
26       !vote_en.wikipedia.org_all-access_all-agents_2...  3bce56c2b977
27       !vote_en.wikipedia.org_all-access_all-agents_2...  d497981dce77
28       !vote_en.wikipedia.org_all-access_all-agents_2...  c813cec10548
29       !vote_en.wikipedia.org_all-access_all-agents_2...  5123e0ed62c9
...                                                    ...           ...
8703750  龙生九子_zh.wikipedia.org_mobile-web_all-agents_20...  1fb8f902ad0f
8703751  龙生九子_zh.wikipedia.org_mobile-web_all-agents_20...  0107f6d7cd82
8703752  龙生九子_zh.wikipedia.org_mobile-web_all-agents_20...  30c402ed9e49
8703753  龙生九子_zh.wikipedia.org_mobile-web_all-agents_20...  935fa0168d01
8703754  龙生九子_zh.wikipedia.org_mobile-web_all-agents_20...  1140b428380e
8703755  龙生九子_zh.wikipedia.org_mobile-web_all-agents_20...  cc5eadae0d7a
8703756  龙生九子_zh.wikipedia.org_mobile-web_all-agents_20...  f923701cdb05
8703757  龙生九子_zh.wikipedia.org_mobile-web_all-agents_20...  905679a20d39
8703758  龙生九子_zh.wikipedia.org_mobile-web_all-agents_20...  642354a50690
8703759  龙生九子_zh.wikipedia.org_mobile-web_all-agents_20...  7376c63bd4c1
8703760  龙生九子_zh.wikipedia.org_mobile-web_all-agents_20...  1f0566b71f7e
8703761  龙生九子_zh.wikipedia.org_mobile-web_all-agents_20...  938774bbb675
8703762  龙生九子_zh.wikipedia.org_mobile-web_all-agents_20...  53c046bac8cb
8703763  龙生九子_zh.wikipedia.org_mobile-web_all-agents_20...  ead2377353d3
8703764  龙生九子_zh.wikipedia.org_mobile-web_all-agents_20...  efa87c7d5160
8703765  龙生九子_zh.wikipedia.org_mobile-web_all-agents_20...  f239d6ceb17b
8703766  龙生九子_zh.wikipedia.org_mobile-web_all-agents_20...  0fef0826b1bc
8703767  龙生九子_zh.wikipedia.org_mobile-web_all-agents_20...  478d3c34b0c1
8703768  龙生九子_zh.wikipedia.org_mobile-web_all-agents_20...  6a1b6e3028fc
8703769  龙生九子_zh.wikipedia.org_mobile-web_all-agents_20...  3b5fb022accd
8703770  龙生九子_zh.wikipedia.org_mobile-web_all-agents_20...  a4456a9d271d
8703771  龙生九子_zh.wikipedia.org_mobile-web_all-agents_20...  d43a25cf4ef2
8703772  龙生九子_zh.wikipedia.org_mobile-web_all-agents_20...  8f47d2e020cd
8703773  龙生九子_zh.wikipedia.org_mobile-w

In [10]:
test_page_list = df_test['Page'].tolist()

In [11]:
test_page_list.sort() #排序page才方便跟test欄位比較

In [12]:
test_page_list #可以發現該有的欄位一模一樣

['!vote_en.wikipedia.org_all-access_all-agents_2017-01-01',
 '!vote_en.wikipedia.org_all-access_all-agents_2017-01-02',
 '!vote_en.wikipedia.org_all-access_all-agents_2017-01-03',
 '!vote_en.wikipedia.org_all-access_all-agents_2017-01-04',
 '!vote_en.wikipedia.org_all-access_all-agents_2017-01-05',
 '!vote_en.wikipedia.org_all-access_all-agents_2017-01-06',
 '!vote_en.wikipedia.org_all-access_all-agents_2017-01-07',
 '!vote_en.wikipedia.org_all-access_all-agents_2017-01-08',
 '!vote_en.wikipedia.org_all-access_all-agents_2017-01-09',
 '!vote_en.wikipedia.org_all-access_all-agents_2017-01-10',
 '!vote_en.wikipedia.org_all-access_all-agents_2017-01-11',
 '!vote_en.wikipedia.org_all-access_all-agents_2017-01-12',
 '!vote_en.wikipedia.org_all-access_all-agents_2017-01-13',
 '!vote_en.wikipedia.org_all-access_all-agents_2017-01-14',
 '!vote_en.wikipedia.org_all-access_all-agents_2017-01-15',
 '!vote_en.wikipedia.org_all-access_all-agents_2017-01-16',
 '!vote_en.wikipedia.org_all-access_all-

## 把ID跟df_train上的page對在一起(先排序好)，這樣才好ML並且放到df_ans當中

In [13]:
df_train_0_order = df_train_0.sort_values('Page') #排序好

In [14]:
df_train_0_order

Page  2015-07-01  \
37206        !vote_en.wikipedia.org_all-access_all-agents         3.0   
32275            !vote_en.wikipedia.org_all-access_spider         0.0   
8357            !vote_en.wikipedia.org_desktop_all-agents         3.0   
37207   "Awaken,_My_Love!"_en.wikipedia.org_all-access...         0.0   
32276   "Awaken,_My_Love!"_en.wikipedia.org_all-access...         0.0   
8358    "Awaken,_My_Love!"_en.wikipedia.org_desktop_al...         0.0   
37208   "European_Society_for_Clinical_Investigation"_...         0.0   
32277   "European_Society_for_Clinical_Investigation"_...         0.0   
8359    "European_Society_for_Clinical_Investigation"_...         0.0   
39669   "Heroes"_(David_Bowie_album)_en.wikipedia.org_...         0.0   
35987   "Heroes"_(David_Bowie_album)_en.wikipedia.org_...         0.0   
12170   "Heroes"_(David_Bowie_album)_en.wikipedia.org_...         0.0   
19611   "Keep_me_logged_in"_extended_to_one_year_www.m...         0.0   
82986   "Keep_me_logged_in"_extended_to_one_year_www.m...         0.0   
42124   "Keep_me_logged_in"_extended_to_one_year_www.m...         0.0   
23341   "Keep_me_logged_in"_extended_to_one_year_www.m...         0.0   
37209   "Weird_Al"_Yankovic_en.wikipedia.org_all-acces...      3966.0   
32278   "Weird_Al"_Yankovic_en.wikipedia.org_all-acces...       144.0   
8360    "Weird_Al"_Yankovic_en.wikipedia.org_desktop_a...      2403.0   
22945          %s_www.mediawiki.org_mobile-web_all-agents         0.0   
39670   'Tis_the_Season_(Vince_Gill_and_Olivia_Newton-...        15.0   
34746   'Tis_the_Season_(Vince_Gill_and_Olivia_Newton-...         9.0   
75165   'Tis_the_Season_(Vince_Gill_and_Olivia_Newton-...         9.0   
37210   'Tis_the_Season_en.wikipedia.org_all-access_al...        34.0   
34745   'Tis_the_Season_en.wikipedia.org_all-access_sp...         6.0   
10893   'Tis_the_Season_en.wikipedia.org_desktop_all-a...        29.0   
72749   'Tis_the_Season_en.wikipedia.org_mobile-web_al...         5.0   
64839       (1)_Ceres_de.wikipedia.org_desktop_all-agents       404.0   
23466   (236984)_Astier_fr.wikipedia.org_all-access_al...         0.0   
129577  (236984)_Astier_fr.wikipedia.org_all-access_sp...         0.0   
...                                                   ...         ...   
3471               龍千玉_zh.wikipedia.org_all-access_spider         0.0   
63993             龍千玉_zh.wikipedia.org_desktop_all-agents         0.0   
108626         龍千玉_zh.wikipedia.org_mobile-web_all-agents         0.0   
28920          龍應台_zh.wikipedia.org_all-access_all-agents       217.0   
972                龍應台_zh.wikipedia.org_all-access_spider         0.0   
62211             龍應台_zh.wikipedia.org_desktop_all-agents       136.0   
107130         龍抬頭_zh.wikipedia.org_mobile-web_all-agents         3.0   
29237          龍涎香_zh.wikipedia.org_all-access_all-agents        88.0   
1286               龍涎香_zh.wikipedia.org_all-access_spider         1.0   
61849             龍涎香_zh.wikipedia.org_desktop_all-agents        58.0   
31445          龍珠超_zh.wikipedia.org_all-access_all-agents         0.0   
3479               龍珠超_zh.wikipedia.org_all-access_spider         0.0   
64003             龍珠超_zh.wikipedia.org_desktop_all-agents         0.0   
108638         龍珠超_zh.wikipedia.org_mobile-web_all-agents         0.0   
30467         龐茲騙局_zh.wikipedia.org_all-access_all-agents       263.0   
2503              龐茲騙局_zh.wikipedia.org_all-access_spider         5.0   
63028            龐茲騙局_zh.wikipedia.org_desktop_all-agents       198.0   
29887          龔嘉欣_zh.wikipedia.org_all-access_all-agents       294.0   
1925               龔嘉欣_zh.wikipedia.org_all-access_spider        32.0   
62487             龔嘉欣_zh.wikipedia.org_desktop_all-agents       166.0   
107041         龔嘉欣_zh.wikipedia.org_mobile-web_all-agents       125.0   
63079             龔照勝_zh.wikipedia.org_desktop_all-agents        10.0   
108083        龙生九子_zh.wikipedia.org_mobile-web_all-agents        95.0   
46228      대문_commons.wikimedia.org_al

In [15]:
df_test_order = df_test.sort_values('Page')

In [16]:
df_test_order

Page            Id
0     !vote_en.wikipedia.org_all-access_all-agents_2...  bf4edcf969af
1     !vote_en.wikipedia.org_all-access_all-agents_2...  929ed2bf52b9
2     !vote_en.wikipedia.org_all-access_all-agents_2...  ff29d0f51d5c
3     !vote_en.wikipedia.org_all-access_all-agents_2...  e98873359be6
4     !vote_en.wikipedia.org_all-access_all-agents_2...  fa012434263a
5     !vote_en.wikipedia.org_all-access_all-agents_2...  48f1e93517a2
6     !vote_en.wikipedia.org_all-access_all-agents_2...  5def418fcb36
7     !vote_en.wikipedia.org_all-access_all-agents_2...  77bd08134351
8     !vote_en.wikipedia.org_all-access_all-agents_2...  5889e6dbb16f
9     !vote_en.wikipedia.org_all-access_all-agents_2...  5f21fef1d764
10    !vote_en.wikipedia.org_all-access_all-agents_2...  6f07e1b8815a
11    !vote_en.wikipedia.org_all-access_all-agents_2...  228e54b5dea0
12    !vote_en.wikipedia.org_all-access_all-agents_2...  da1b34963ed7
13    !vote_en.wikipedia.org_all-access_all-agents_2...  ab5ccefaa2db
14    !vote_en.wikipedia.org_all-access_all-agents_2...  cbf42873ebf1
15    !vote_en.wikipedia.org_all-access_all-agents_2...  ac67e35ed44e
16    !vote_en.wikipedia.org_all-access_all-agents_2...  88c098aa640d
17    !vote_en.wikipedia.org_all-access_all-agents_2...  7c72842a89d1
18    !vote_en.wikipedia.org_all-access_all-agents_2...  8ce002f2c329
19    !vote_en.wikipedia.org_all-access_all-agents_2...  5f72d9920560
20    !vote_en.wikipedia.org_all-access_all-agents_2...  f93afd7f5d9b
21    !vote_en.wikipedia.org_all-access_all-agents_2...  14011cb66f2d
22    !vote_en.wikipedia.org_all-access_all-agents_2...  0065551ac465
23    !vote_en.wikipedia.org_all-access_all-agents_2...  175f1872729e
24    !vote_en.wikipedia.org_all-access_all-agents_2...  31d756e83124
25    !vote_en.wikipedia.org_all-access_all-agents_2...  e186c2363c5e
26    !vote_en.wikipedia.org_all-access_all-agents_2...  3bce56c2b977
27    !vote_en.wikipedia.org_all-access_all-agents_2...  d497981dce77
28    !vote_en.wikipedia.org_all-access_all-agents_2...  c813cec10548
29    !vote_en.wikipedia.org_all-access_all-agents_2...  5123e0ed62c9
...                                                 ...           ...
3330  ［Alexandros］_ja.wikipedia.org_mobile-web_all-a...  a49077fb4250
3331  ［Alexandros］_ja.wikipedia.org_mobile-web_all-a...  b41e15bdce94
3332  ［Alexandros］_ja.wikipedia.org_mobile-web_all-a...  20befbc08a48
3333  ［Alexandros］_ja.wikipedia.org_mobile-web_all-a...  aed89c02c2bf
3334  ［Alexandros］_ja.wikipedia.org_mobile-web_all-a...  752fa508765f
3335  ［Alexandros］_ja.wikipedia.org_mobile-web_all-a...  b87fa58711d4
3336  ［Alexandros］_ja.wikipedia.org_mobile-web_all-a...  babdf0ab9c17
3337  ［Alexandros］_ja.wikipedia.org_mobile-web_all-a...  a31ff39e65b2
3338  ［Alexandros］_ja.wikipedia.org_mobile-web_all-a...  f6f755a4784f
3339  ［Alexandros］_ja.wikipedia.org_mobile-web_all-a...  07373bc81000
3340  ［Alexandros］_ja.wikipedia.org_mobile-web_all-a...  1a716410ef10
3341  ［Alexandros］_ja.wikipedia.org_mobile-web_all-a...  1c981138b1d0
3342  ［Alexandros］_ja.wikipedia.org_mobile-web_all-a...  835e9921004f
3343  ［Alexandros］_ja.wikipedia.org_mobile-web_all-a...  e80d82f38da3
3344  ［Alexandros］_ja.wikipedia.org_mobile-web_all-a...  c5eb03cebdf0
3345  ［Alexandros］_ja.wikipedia.org_mobile-web_all-a...  7abc0d37b8df
3346  ［Alexandros］_ja.wikipedia.org_mobile-web_all-a...  e27c1d7bca11
3347  ［Alexandros］_ja.wikipedia.org_mobile-web_all-a...  07a407b27394
3348  ［Alexandros］_ja.wikipedia.org_mobile-web_all-a...  43f0e83c0d8f
3349  ［Alexandros］_ja.wikipedia.org_mobile-web_all-a...  7ff0d300f855
3350  ［Alexandros］_ja.wikipedia.org_mobile-web_all-a...  fec442127f20
3351  ［Alexandros］_ja.wikipedia.org_mobile-web_all-a...  9cab502f0c43
3352  ［Alexandros］_ja.wikipedia.org_mobile-web_all-a...  f8c721fdecde
3353  ［Alexandros］_ja.wikipedia.org_mobile-web_all-a...  5837c7aa7bba
3354  ［Alexandros］_ja.wikipedia.org_mobile-web_all-a...  857c39e7e7ea
3355  ［Alexandros］_ja.wikipedia.org_mobile-web_all-a...  4424

In [17]:
df_ans.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8703780 entries, 0 to 8703779
Data columns (total 2 columns):
Id        object
Visits    int64
dtypes: int64(1), object(1)
memory usage: 132.8+ MB


In [17]:
df_ans 
#不過有個問題是這個Id可是沒有排序過的呢
#到時候按照page_list_order填上答案之後，在使用col=0的那一欄數字重新排位正確答案順序吧～

Id  Visits
0        bf4edcf969af       0
1        929ed2bf52b9       0
2        ff29d0f51d5c       0
3        e98873359be6       0
4        fa012434263a       0
5        48f1e93517a2       0
6        5def418fcb36       0
7        77bd08134351       0
8        5889e6dbb16f       0
9        5f21fef1d764       0
10       6f07e1b8815a       0
11       228e54b5dea0       0
12       da1b34963ed7       0
13       ab5ccefaa2db       0
14       cbf42873ebf1       0
15       ac67e35ed44e       0
16       88c098aa640d       0
17       7c72842a89d1       0
18       8ce002f2c329       0
19       5f72d9920560       0
20       f93afd7f5d9b       0
21       14011cb66f2d       0
22       0065551ac465       0
23       175f1872729e       0
24       31d756e83124       0
25       e186c2363c5e       0
26       3bce56c2b977       0
27       d497981dce77       0
28       c813cec10548       0
29       5123e0ed62c9       0
...               ...     ...
8703750  1fb8f902ad0f       0
8703751  0107f6d7cd82       0
8703752  30c402ed9e49       0
8703753  935fa0168d01       0
8703754  1140b428380e       0
8703755  cc5eadae0d7a       0
8703756  f923701cdb05       0
8703757  905679a20d39       0
8703758  642354a50690       0
8703759  7376c63bd4c1       0
8703760  1f0566b71f7e       0
8703761  938774bbb675       0
8703762  53c046bac8cb       0
8703763  ead2377353d3       0
8703764  efa87c7d5160       0
8703765  f239d6ceb17b       0
8703766  0fef0826b1bc       0
8703767  478d3c34b0c1       0
8703768  6a1b6e3028fc       0
8703769  3b5fb022accd       0
8703770  a4456a9d271d       0
8703771  d43a25cf4ef2       0
8703772  8f47d2e020cd       0
8703773  a78af728d84b       0
8703774  d1ba45c7ec08       0
8703775  f69747f5ee68       0
8703776  2489963dc503       0
8703777  b0624c909f4c       0
8703778  24a1dfb06c10       0
8703779  add681d54216       0

[8703780 rows x 2 columns]

## 目標就是把有order每一組的60天預測數據做出來，然後fit到對應的id格子去

In [18]:
list_train_order_value = df_train_0_order.values[:,1:] #除掉page那個欄位，取得純數字

In [19]:
list_train_order_value

array([[3.0, 4.0, 7.0, ..., 3.0, 1.0, 1.0],
       [0.0, 0.0, 1.0, ..., 1.0, 1.0, 0.0],
       [3.0, 4.0, 7.0, ..., 3.0, 1.0, 0.0],
       ..., 
       [4.0, 4.0, 3.0, ..., 277.0, 226.0, 287.0],
       [1077.0, 1210.0, 1080.0, ..., 904.0, 786.0, 761.0],
       [4345.0, 4737.0, 4633.0, ..., 3302.0, 2789.0, 3410.0]], dtype=object)

In [24]:
list_train_order_value = list_train_order_value.astype(int)

In [25]:
list_train_order_value 

array([[   3,    4,    7, ...,    3,    1,    1],
       [   0,    0,    1, ...,    1,    1,    0],
       [   3,    4,    7, ...,    3,    1,    0],
       ..., 
       [   4,    4,    3, ...,  277,  226,  287],
       [1077, 1210, 1080, ...,  904,  786,  761],
       [4345, 4737, 4633, ..., 3302, 2789, 3410]])

# 先跑一個Page的模型看看，取前面10天預測後面1天

In [32]:
page_data = list_train_order_value[0]

In [35]:
page_data

array([ 3,  4,  7,  4,  4,  2,  3,  7,  2,  0,  3,  1,  2,  2,  3,  2,  1,
        1,  1,  0,  6,  8,  5,  1,  2,  1,  2, 10,  4,  6,  4,  2,  1,  4,
        1,  2,  0,  0,  1,  0,  2,  3,  3,  1,  3,  3,  4,  1,  0,  3,  3,
        7,  4,  6, 14,  6,  5,  4,  7,  3,  2,  1,  3,  3,  2,  1,  1,  4,
        6,  3,  1,  3,  1,  3,  3,  1,  4,  4,  4,  5,  1,  3,  6,  3,  2,
        4,  4,  3,  3,  3,  2,  1,  0,  4,  7,  0,  6,  2,  2,  3,  2,  1,
        3,  1,  2,  1,  1,  4,  1,  6,  5,  3,  3,  9,  4,  6,  7,  8,  2,
        2,  4,  8,  6,  5,  5,  4,  2,  3,  5,  8,  7,  4, 10,  4,  1,  1,
        2, 14,  2,  4,  0,  5,  8,  9,  3,  4,  3,  5,  3,  3,  3,  1,  2,
        2,  2,  5,  2,  2,  1,  2,  2,  9,  3,  4,  4,  0,  4,  1,  3,  4,
        0,  3,  3,  1,  1,  2,  6,  4,  4, 10,  2,  4,  0,  3,  3,  2,  2,
        2,  3,  1,  1,  1,  4,  3,  0,  1,  2,  3,  2,  1,  1,  2,  2,  2,
        1,  2,  4,  2,  8,  4,  5,  6,  3,  4,  2,  9,  1, 11,  4,  2,  3,
        3,  1,  3,  2,  3

In [38]:
page_data.shape

(550,)

In [52]:
page_data_label = page_data[10:]

In [53]:
page_data_label.shape

(540,)

In [65]:
train_feature = []
for i in range(540):
    train_feature.append(page_data[i:i+10])

In [66]:
train_feature

[array([3, 4, 7, 4, 4, 2, 3, 7, 2, 0]),
 array([4, 7, 4, 4, 2, 3, 7, 2, 0, 3]),
 array([7, 4, 4, 2, 3, 7, 2, 0, 3, 1]),
 array([4, 4, 2, 3, 7, 2, 0, 3, 1, 2]),
 array([4, 2, 3, 7, 2, 0, 3, 1, 2, 2]),
 array([2, 3, 7, 2, 0, 3, 1, 2, 2, 3]),
 array([3, 7, 2, 0, 3, 1, 2, 2, 3, 2]),
 array([7, 2, 0, 3, 1, 2, 2, 3, 2, 1]),
 array([2, 0, 3, 1, 2, 2, 3, 2, 1, 1]),
 array([0, 3, 1, 2, 2, 3, 2, 1, 1, 1]),
 array([3, 1, 2, 2, 3, 2, 1, 1, 1, 0]),
 array([1, 2, 2, 3, 2, 1, 1, 1, 0, 6]),
 array([2, 2, 3, 2, 1, 1, 1, 0, 6, 8]),
 array([2, 3, 2, 1, 1, 1, 0, 6, 8, 5]),
 array([3, 2, 1, 1, 1, 0, 6, 8, 5, 1]),
 array([2, 1, 1, 1, 0, 6, 8, 5, 1, 2]),
 array([1, 1, 1, 0, 6, 8, 5, 1, 2, 1]),
 array([1, 1, 0, 6, 8, 5, 1, 2, 1, 2]),
 array([ 1,  0,  6,  8,  5,  1,  2,  1,  2, 10]),
 array([ 0,  6,  8,  5,  1,  2,  1,  2, 10,  4]),
 array([ 6,  8,  5,  1,  2,  1,  2, 10,  4,  6]),
 array([ 8,  5,  1,  2,  1,  2, 10,  4,  6,  4]),
 array([ 5,  1,  2,  1,  2, 10,  4,  6,  4,  2]),
 array([ 1,  2,  1,  2, 10,  4

In [69]:
train_feature_array = np.array(train_feature)

In [70]:
train_feature_array

array([[3, 4, 7, ..., 7, 2, 0],
       [4, 7, 4, ..., 2, 0, 3],
       [7, 4, 4, ..., 0, 3, 1],
       ..., 
       [1, 3, 2, ..., 1, 1, 4],
       [3, 2, 3, ..., 1, 4, 3],
       [2, 3, 1, ..., 4, 3, 1]])

In [71]:
len(train_feature_array)

540

In [181]:
######################### 建立模型
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout

model = Sequential() #一層一層到底，按順序

#輸入層（隱藏層1）
model.add(Dense(units=200, 
                input_dim=10, 
                kernel_initializer='uniform', 
                activation='relu'))
model.add(Dropout(0.5))

#隱藏層2，不用寫input_dim，因為就是前一層的units
model.add(Dense(units=200,  
                kernel_initializer='uniform', 
                activation='relu'))
model.add(Dropout(0.5))

#輸出層
model.add(Dense(units=1, #輸出一個數字 
                kernel_initializer='uniform'))

print(model.summary()) #可以清楚看到model還有參數數量


model.compile(loss='mse',   #二元用binary
              optimizer='adam', metrics=['accuracy'])

model.fit(x=train_feature_array, y=page_data_label,  #上面多分割一步在keras是內建的
                          validation_split=0.2, epochs=20, batch_size=150, verbose=0) #verbose=2表示顯示訓練過程

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_147 (Dense)            (None, 200)               2200      
_________________________________________________________________
dropout_99 (Dropout)         (None, 200)               0         
_________________________________________________________________
dense_148 (Dense)            (None, 200)               40200     
_________________________________________________________________
dropout_100 (Dropout)        (None, 200)               0         
_________________________________________________________________
dense_149 (Dense)            (None, 1)                 201       
Total params: 42,601
Trainable params: 42,601
Non-trainable params: 0
_________________________________________________________________
None


In [152]:
list_future = train_feature_array[-1].reshape(-1,10)
ans_list = list_future

In [153]:
np.append(ans_list,1) #測試用

array([2, 3, 1, 6, 3, 1, 1, 4, 3, 1, 1])

In [154]:
ans_list #其實並沒有加上去！！

array([[2, 3, 1, 6, 3, 1, 1, 4, 3, 1]])

In [155]:
ans_list[0:10]

array([[2, 3, 1, 6, 3, 1, 1, 4, 3, 1]])

In [156]:
for i in range(61):
    ans = model.predict(ans_list[i:i+10].reshape(-1,10))
    ans_list = np.append(ans_list, ans)

In [157]:
ans_list

array([ 2.        ,  3.        ,  1.        ,  6.        ,  3.        ,
        1.        ,  1.        ,  4.        ,  3.        ,  1.        ,
        2.07314897,  2.34163165,  2.23865843,  2.11607313,  1.92182565,
        1.96203339,  1.99277389,  1.95160294,  1.85660791,  1.8078903 ,
        1.83257496,  1.81137025,  1.76898634,  1.73631012,  1.71370244,
        1.69622028,  1.67314231,  1.64847136,  1.62789738,  1.61069787,
        1.59408164,  1.57588303,  1.55843711,  1.54275393,  1.52803504,
        1.51372468,  1.49985647,  1.48678863,  1.4745357 ,  1.46282303,
        1.4515537 ,  1.44077516,  1.43055797,  1.42085636,  1.41159749,
        1.4027617 ,  1.39435053,  1.38634956,  1.3787272 ,  1.37145722,
        1.36452818,  1.35792947,  1.35164583,  1.34565926,  1.33995485,
        1.33452082,  1.32934487,  1.32441378,  1.3197155 ,  1.31523955,
        1.31097543,  1.30691338,  1.3030436 ,  1.29935694,  1.29584455,
        1.29249907,  1.28931141,  1.28627467,  1.28338182,  1.28

In [158]:
ans_list_round = np.round(ans_list)

In [159]:
ans_list_round

array([ 2.,  3.,  1.,  6.,  3.,  1.,  1.,  4.,  3.,  1.,  2.,  2.,  2.,
        2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,
        2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.])

In [160]:
real_ans = ans_list_round[11:]

In [161]:
real_ans #測試第一組的60個數字

array([ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,
        2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

# 測試完畢，統整寫for迴圈

In [274]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout
import os


total_ans = []

for page in range(1,5):
    
    #提取資料
    page_data = list_train_order_value[page]
    
    page_data = np.trim_zeros(page_data, trim='f')  #拿掉前面有太多0的，會有bias
    
    page_data_label = page_data[10:] #每10組給出一次答案，所以答案不包含前10組
    
    train_feature = []
    for i in range(len(page_data_label)):
        train_feature.append(page_data[i:i+10])
    train_feature_array = np.array(train_feature)
    
    
    #標準化
    train_feature_array = train_feature_array/max(page_data)
    page_data_label = page_data_label/max(page_data)

    #print(train_feature_array) #測試用
    #print(page_data_label) #測試用
    
    
    #訓練模型
    model = Sequential() 
    
    model.add(Dense(units=100, 
                    input_dim=10, 
                    kernel_initializer='uniform'))
    model.add(Dropout(0.5))

    model.add(Dense(units=100,  
                    kernel_initializer='uniform'))
    model.add(Dropout(0.5))

    model.add(Dense(units=1))

    #print(model.summary())  #測試用

    '''
    weights_path = 'Savemodels/WIKI(Kaggles)_MLP.h5'

    if os.path.isfile(weights_path): 
        model.load_weights(weights_path) #只要跑過一次就取出來直接使用
    else:
        pass
    '''
    
    model.compile(loss='mse',   
                  optimizer='adam', metrics=['accuracy'])

    model.fit(x=train_feature_array, y=page_data_label,  
              validation_split=0.2, epochs=20, batch_size=200, verbose=1)
    
    #model.save_weights("Savemodels/WIKI(Kaggles)_MLP.h5") #方便下一次跑?
    
    
    
    #訓練後跑答案
    ans_list = train_feature_array[-1].reshape(-1,10)
    rand_list = np.random.randn(60) #常態分佈的雜訊
    
    for i in range(60): #做好做滿60次預測
        ans = model.predict(ans_list[i:i+10].reshape(-1,10))
        ans_add_noise = ans + 0.2*np.std(train_feature_array)*rand_list[i]
        #避免ans太快收斂，加入rand條件讓他上下波動
        
        if ans_add_noise < 0:
            ans_add_noise = 0  #瀏覽人次沒有在<0的啦～
        else:
            ans_add_noise = ans_add_noise
        
        ans_list = np.append(ans_list, ans_add_noise) 
                                            
    
    ans_list_round = np.round(ans_list*np.max(page_data)) #四捨五入成整數的瀏覽人次
    real_ans = ans_list_round[11:] #最終每組60個數字的答案
    
    
    total_ans.append(real_ans) #把每一組的60個數字通通加總在一張表上，最後再貼回去答案卷
    print('case completed: ', page)
    
    
print('All cases completed!!')

Train on 430 samples, validate on 108 samples
Epoch 1/40
430/430 [==============================] - 16s - loss: 0.0144 - acc: 0.2209 - val_loss: 0.0055 - val_acc: 0.1944
Epoch 2/40
430/430 [==============================] - 0s - loss: 0.0100 - acc: 0.2209 - val_loss: 0.0067 - val_acc: 0.1944
Epoch 3/40
430/430 [==============================] - 0s - loss: 0.0106 - acc: 0.2209 - val_loss: 0.0056 - val_acc: 0.1944
Epoch 4/40
430/430 [==============================] - 0s - loss: 0.0097 - acc: 0.2209 - val_loss: 0.0057 - val_acc: 0.1944
Epoch 5/40
430/430 [==============================] - 0s - loss: 0.0099 - acc: 0.2209 - val_loss: 0.0059 - val_acc: 0.1944
Epoch 6/40
430/430 [==============================] - 0s - loss: 0.0097 - acc: 0.2209 - val_loss: 0.0055 - val_acc: 0.1944
Epoch 7/40
430/430 [==============================] - 0s - loss: 0.0096 - acc: 0.2209 - val_loss: 0.0053 - val_acc: 0.1944
Epoch 8/40
430/430 [==============================] - 0s - loss: 0.0093 - acc: 0.2209 - val_

In [275]:
total_ans

[array([ 2.,  3.,  2.,  2.,  1.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,
         2.,  2.,  1.,  3.,  2.,  2.,  1.,  2.,  2.,  2.,  2.,  2.,  2.,
         2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  3.,  3.,  2.,  2.,  2.,
         2.,  2.,  2.,  2.,  3.,  2.,  2.,  1.,  2.,  2.,  1.,  2.,  2.,
         2.,  2.,  2.,  2.,  2.,  2.,  3.]),
 array([ 3.,  4.,  3.,  3.,  3.,  4.,  4.,  2.,  4.,  4.,  3.,  4.,  3.,
         3.,  3.,  3.,  3.,  4.,  4.,  3.,  3.,  4.,  4.,  4.,  3.,  3.,
         3.,  3.,  4.,  4.,  3.,  3.,  2.,  3.,  3.,  3.,  3.,  3.,  4.,
         4.,  3.,  3.,  3.,  3.,  3.,  3.,  4.,  2.,  3.,  3.,  4.,  3.,
         4.,  3.,  3.,  3.,  4.,  4.,  4.]),
 array([ 11744.,  13556.,  18877.,  14524.,  14094.,  12429.,  13344.,
          8226.,   6892.,   5692.,   7635.,  11605.,  10471.,  13326.,
         11992.,  13345.,  14287.,  11901.,  15411.,  13130.,  11847.,
         12417.,  11660.,   5249.,   5998.,   7023.,   7795.,   9281.,
         10505.,  14180.,  15272.,  12683.

In [250]:
total_ans = np.array(total_ans).reshape(1,-1)

In [247]:
total_ans

array([[  2.00000000e+00,   4.00000000e+00,   4.00000000e+00,
          4.00000000e+00,   3.00000000e+00,   4.00000000e+00,
          3.00000000e+00,   3.00000000e+00,   5.00000000e+00,
          5.00000000e+00,   3.00000000e+00,   5.00000000e+00,
          3.00000000e+00,   3.00000000e+00,   4.00000000e+00,
          4.00000000e+00,   5.00000000e+00,   4.00000000e+00,
          3.00000000e+00,   4.00000000e+00,   4.00000000e+00,
          4.00000000e+00,   4.00000000e+00,   4.00000000e+00,
          4.00000000e+00,   5.00000000e+00,   3.00000000e+00,
          4.00000000e+00,   3.00000000e+00,   3.00000000e+00,
          4.00000000e+00,   3.00000000e+00,   5.00000000e+00,
          4.00000000e+00,   4.00000000e+00,   3.00000000e+00,
          4.00000000e+00,   4.00000000e+00,   3.00000000e+00,
          5.00000000e+00,   3.00000000e+00,   3.00000000e+00,
          5.00000000e+00,   4.00000000e+00,   4.00000000e+00,
          4.00000000e+00,   3.00000000e+00,   3.00000000e+00,
        